### ISSUE TITLE
xquery trying to access wrong directory

### ISSUE THREAD

**Issue by nerdychic12** [eXist-db/exist#1009]
I started a directory in exist-db called "annotation" but then deleted this directory and started a new one called "annotations".

I wrote some xquery that should be retrieving from the second directory:
   /db/apps/annotations/data/cases.xml

but when I run the xquery I get a 404 message that says "/db/apps/annotation" not found. In other words, it is searching the first directory that I created, not the new one, despite the fact that I am asking my xquery file to retrieve from the new one. What's happening here? How can I fix it?

**Comment by joewiz** [comment]
It's hard to suggest an answer without seeing the code; feel free to paste it in here. What I would look for is: Are there any lingering references to the old collection? Does the URL you're requesting in your browser line up with the actual path to the resource in your database?

**Comment by duncdrum** [comment]
If you are querying via exide, your current application context might not be where you want to be.

**Comment by dizzzz** [comment]
no response for three weeks, I close this for now; please feel free to reopen for a followup
