### ISSUE TITLE
Presentation modifiers for Z datetime formatting picture string not supported

### ISSUE THREAD

**Issue by joewiz** [eXist-db/exist#1024]
Since #364, eXist added support for `[Z]` and `[z]` - the specifiers for formatting the timezone components of the datetime formatting picture string from the spec (https://www.w3.org/TR/xpath-functions-30/#rules-for-datetime-formatting). However, eXist doesn't handle the presentation modifiers for these two specifiers. For example:

```xquery
format-dateTime(xs:dateTime('2012-06-26T23:14:22.566-10:00'), '[Z0000]')
```

Should return `-1000`, but eXist returns `+00:00`.  There are actually two problems here: 

1. The presentation modifiers are not respected: `[Z0]`, `[Z0000]`, `[Z00:00t]`, `[ZN]`, etc.
2. Timezones with negative offsets are always returned as GMT (e.g., `-10:00` dateTimes such as the one above will be formatted `+00:00`). Positive offsets do not suffer from this problem (e.g., change `-10:00` to `+10:00` in the example above, and the result will be `+10:00`).

I believe the relevant code is https://github.com/adamretter/exist/blob/76abc91f1ad5d9697b6dbd466ef8dc60940ad9a4/src/org/exist/xquery/functions/fn/FnFormatDates.java#L318-L331. 

For convenience, here is a screenshot of the presentation modifier table from the spec (linked above):

> ![screen shot 2016-05-25 at 1 14 30 pm](https://cloud.githubusercontent.com/assets/59118/15549490/c5a10aaa-227a-11e6-9a87-b4fd60fe8423.png)

**Comment by adamretter** [comment]
@joewiz Would you have a moment to write some XQTest tests to add to https://github.com/eXist-db/exist/blob/develop/test/src/xquery/dates/format-dates.xql to show the issues?

**Comment by joewiz** [comment]
Sure, will do.

**Comment by joewiz** [comment]
Added in PR https://github.com/eXist-db/exist/pull/1096.

**Comment by adamretter** [comment]
@joewiz I just sent a PR for this, I don't yet have the `[ZN]` picture working correctly, so I have just set those tests to pending for now, otherwise all your new tests and the existing tests now pass.

**Comment by joewiz** [comment]
Whoo hoo! Thanks again, Adam!
