### ISSUE TITLE
Deadlock caused by expath zip:update

### ISSUE THREAD

**Issue by gspringtech** [eXist-db/exist#1028]
The zip:update function reads an existing zip file (or ODT, DOCX etc) and adds the supplied binary data at the named path:
   `zip:update('/db/temp/test.zip', 'content.xml', $binary-data)`
It returns the modified zip file - the original is not changed. 

If "shortly after" a function like sm:chmod() is used on the original zip file, there will be a Read lock which does not get released. Querying the parent collection (xmldb:get-child-resources) or attempting to run sm:chmod again will cause a deadlock.

Any zip file will do. I posted a more self-contained example to the exist-open list.
Attached are the pre- and post- outputs of jstack and /exist/status.xml

```
let $tz := '/db/test/about.odt'
(: disable for second run ... :)
let $update := zip:update($tz, 'content.xml',util:string-to-binary('abc'))
(: enable for second run ... :)
(:let $chmod := sm:chmod(xs:anyURI($tz), 'rw-rw----'):)
return "done"

[dumps-20160529.zip](https://github.com/eXist-db/exist/files/288054/dumps-20160529.zip)
```

**Comment by shabanovd** [comment]
@gspringtech test [this branch](https://github.com/shabanovd/exist/tree/bugfix/expath)

**Comment by gspringtech** [comment]
@shabanovd - thank you. This seems to have resolved the issue.
