### ISSUE TITLE
New java service wrapper: cannot change properties of windows service

### ISSUE THREAD

**Issue by dizzzz** [eXist-db/exist#1032]
- windows 7 / java 8 / 64 bit
- started with `java -jar start.jar` , install as service

the following error appears when selecting 'properties' from the context menu

![image](https://cloud.githubusercontent.com/assets/1700062/15674322/56c3b486-273c-11e6-95a4-e27f3509f2b4.png)

**Comment by ljo** [comment]
My win7/64-bit is a bit outdated, so I can only check later today.

**Comment by dizzzz** [comment]
I think it works (last time I checked)
