### ISSUE TITLE
Discuss: Remove sources from installer package

### ISSUE THREAD

**Issue by dizzzz** [eXist-db/exist#1035]
Since the eXist-db sources are so easy to download from GitHub, I'd like to suggest to remove the sources out of the installer package.

It would make our distribution significantly smaller.....

**Comment by shabanovd** [comment]
+1

On Thu, Jun 2, 2016 at 10:16 PM, Dannes Wessels <notifications@github.com>
wrote:

> Since the eXist-db sources are so easy to download from GitHub, I'd like
> to suggest to remove the sources out of the installer package.
>
> It would make our distribution significantly smaller.....
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/eXist-db/exist/issues/1035>, or mute the thread
> <https://github.com/notifications/unsubscribe/AAG3-ll-mwqueWJ8sWNG_Nbbthrrzqcyks5qHywfgaJpZM4Is4xL>
> .
>



-- 
Dmitriy Shabanov

**Comment by adamretter** [comment]
Are the sources in the distribution a copy of a git checkout? i.e. Can I start working with them immediately?

**Comment by wolfgangmm** [comment]
Being able to quickly apply small patches is sometimes useful, even on a version installed via the installer. If you have to support users, you can tell them to try this or that to figure out where the problem is. I actually do this quite often and it takes time if you first have to ask them to separately install the sources of the version they are running.

**Comment by Newtopian** [comment]
plus the space savings are not that significant, 10MB - 20MB

**Comment by dizzzz** [comment]
For non-Western users each mb counts on slow lines.....

That is kinda my idea

**Comment by joewiz** [comment]
How about a build target, `get-sources`? This could fetch the source based on the originally-built revision.

**Comment by joewiz** [comment]
Now that I think about it, there's no good way to fetch a subdirectory of a git revision (GitHub provides only complete tarballs), and there are sources in several directories...

**Comment by dizzzz** [comment]
I think my idea still holds :-)
