### ISSUE TITLE
Performance regression: new log4j2' LogManager.getLogger slows doen queries

### ISSUE THREAD

**Issue by dizzzz** [eXist-db/exist#1036]
As reported by @wolfgangmm in HipChat:

Since the update of log4j, `LogManager.getLogger()` is consuming an amazing amount of time, up to 98% for some queries.

It's the same effect on two different instances. log4j configuration unchanged.

Confirmation: going back to the previous version removes the bottleneck.

**Comment by dizzzz** [comment]
@adamretter are you aware of any regression in this area?

**Comment by adamretter** [comment]
@dizzzz I am not aware of any issues in this area, can you figure out how to reproduce and open an issue with the Apache Log4j project and paste the ticket reference in here please?

**Comment by tasmo** [comment]
Have the same issue with latest HEAD.

**Comment by adamretter** [comment]
@dizzzz Can you post a reference to the log4j ticket in Apache's Jira?

**Comment by dizzzz** [comment]
I'd need to create a reproducible test case myself first, I was only
echoing @wolfgangmm findings...

On Thu, Jun 9, 2016 at 12:19 PM, Adam Retter <notifications@github.com>
wrote:

> @dizzzz <https://github.com/dizzzz> Can you post a reference to the log4j
> ticket in Apache's Jira?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/eXist-db/exist/issues/1036#issuecomment-224855633>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ABnw3hKoFlN8EDnMDmYZ1e-f6SK_kOvcks5qJ-jGgaJpZM4Is5Oq>
> .
>



-- 
eXist-db Native XML Database - http://exist-db.org
Join us on linked-in: http://www.linkedin.com/groups?gid=35624

**Comment by adamretter** [comment]
Maybe worth testing again with https://github.com/eXist-db/exist/pull/1045

**Comment by wolfgangmm** [comment]
Yes, #1045 seems to have fixed the issue, thanks. The slowdown was visible in any app as loading a page became really slow.

**Comment by adamretter** [comment]
Very happy to hear that this was a simple fix :-)
