### ISSUE TITLE
Cannot save XML doc with xml:id + valide NCname

### ISSUE THREAD

**Issue by TonyTchang** [eXist-db/exist#1049]
Hello,

The following XQuery code:
`xquery version "3.0";
let $test := <testelt xml:id="{util:uuid()}">Machin chose</testelt>
return xmldb:store("/db/apps/newIAM/", "test.txt", $test)`

fails with the following error:
`<exception><path>/db/apps/newIAM/test.xql</path><message>err:XQDY0091 Value of xml:id attribute is not a valid NCName: 44fa3a98-e215-4996-bb76-614d03720181 [at line 3, column 15, source: /db/apps/newIAM/test.xql]</message></exception>`

Yet I believe it a valid NCname

**Comment by joewiz** [comment]
Which version of eXist?

**Comment by TonyTchang** [comment]
Sorry for not specifying: 3.0.RC1 (HEAD-e34eb95)

**Comment by dizzzz** [comment]
did you store the script as `test.xql` ?

**Comment by TonyTchang** [comment]
Yes, I do confirm it's test.xql trying to write to file test.txt. Same error message when I try writing to test.xml.

Have you tried reproducing the bug?

**Comment by ljo** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA1

Den 2016-06-16 kl. 12:25, skrev TonyTchang:
> Hello,
> 
> The following XQuery code:
> |xquery version "3.0";
> let $test := <testelt xml:id="{util:uuid()}">Machin chose</testelt>
> return xmldb:store("/db/apps/newIAM/", "test.txt", $test)|
> 
> fails with the following error:
> |<exception><path>/db/apps/newIAM/test.xql</path><message>err:XQDY0091
> Value of xml:id attribute is not a valid NCName:
> 44fa3a98-e215-4996-bb76-614d03720181 [at line 3, column 15, source:

Dear Tony et al, the error is correct if a bit inprecise. A valid xml:id
does not start with a digit. Prepend a valid initial char or a prefix if
you use uuid and it will be fine.

Regards,
Leif-Jöran


> /db/apps/newIAM/test.xql]</message></exception>|
> 
> Yet I believe it a valid NCname
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/eXist-db/exist/issues/1049>, or mute the thread
> <https://github.com/notifications/unsubscribe/AALr9uar0RWSiHhz3h5HfPHe
EuVu1msKks5qMSSWgaJpZM4I3Pc9>.
> 

-----BEGIN PGP SIGNATURE-----
Version: GnuPG v2

iEYEARECAAYFAldiqL8ACgkQhcIn5aVXOPLHbwCglw9Od9xeM7n7NQ/GsUoc58AV
dsUAn2TL39fK6J2rA/j12bpObkop23IN
=VRF+
-----END PGP SIGNATURE-----
