### ISSUE TITLE
Jetty9 : startup issue

### ISSUE THREAD

**Issue by dizzzz** [eXist-db/exist#1063]
*only* when exist-db is started with `java -jar start.jar' the following error is visible:

![clipboard01](https://cloud.githubusercontent.com/assets/1700062/16794639/761fba00-48d9-11e6-8472-e03cb07a597d.png)

`bin\startup.sh` looks just fine..... and 'jetty.xml' hasn't changed....

**Comment by dizzzz** [comment]
any idea @adamretter ?

**Comment by adamretter** [comment]
@dizzzz I have never used the launcher or started eXist in that way, so I completely forgot about it! I just sent a very simple PR which fixes this. Basically the launcher was sending the old config file path to JettyStart, it now sends the correct one.
