### ISSUE TITLE
3.0 RC1: fold-right omits the rightmost sequence element in processing

### ISSUE THREAD

**Issue by median1st** [eXist-db/exist#1067]
The fn:fold-right function omits the rightmost element from the processed sequence. This xquery snippet demonstrates the bug:
```
let $seq := (1,2,3,4)
return
    fold-right ($seq, (<state i='0'/>) , function($item as xs:integer, $accu as node()*) {
        ($accu, <state i='{$item}'/>)
    })
```
eXist-db 3.0 RC1 returns the following sequence as a result:

```
<state i="0"/>
<state i="3"/>
<state i="2"/>
<state i="1"/>

```
Note that the rightmost number ( 4 ) is omitted. When the same query is run in eXist-db 2.2, the result is correct:

```
<state i="0"/>
<state i="4"/>
<state i="3"/>
<state i="2"/>
<state i="1"/>

```

**Comment by dizzzz** [comment]
confirmed for existdb 3.0 (RC2)

**Comment by dizzzz** [comment]
waiting for a pull-in and review
