### ISSUE TITLE
After OutOfMemory error, lots of "IOException : error while writing to page X"

### ISSUE THREAD

**Issue by YassineMouhli** [eXist-db/exist#1068]
Our production database - eXist 2.1 - got a PermGen OutOfMemory error last week. We "solved" it by increasing the size of the PermGen memory pool. Since then we get constantly this error:  

2016-07-18 12:24:36,761 [DefaultQuartzScheduler_Worker-2] ERROR (BTree.java [sync]:868) - IO error while writing page: 24713 
java.io.IOException: Bad file descriptor

2016-07-18 12:26:39,239 [DefaultQuartzScheduler_Worker-3] ERROR (BFile.java [sync]:1667) - IO exception occurred while saving page 71 

Any ideas what we can do ?

**Comment by wolfgangmm** [comment]
This sounds like the out of memory has damaged one of the index files. I would recommend to run a full export using the system export tool and reimport everything into a clean database.

**Comment by YassineMouhli** [comment]
thank you for your replay, I'll try it .

currently I have another problem, after admin login successfully, I have a "Database is read-only"

Is that because the wrong index ?

This is the Exception in log file :
[eXistThread-33] ERROR (LocalCollection.java [storeXMLResource]:892) - org.exist.security.PermissionDeniedException: Database is read-only

**Comment by dizzzz** [comment]
The database  becomes readonly typically when there is not sufficient diskspace left. Please could you check?

Are you running windows? on the older exist-2.1 version, on windows, Java sometimes reports wrong values, making the database go in this state.  in the 3.0RCx improvements have been made, I think they are on in the 2.2 version already.
