### ISSUE TITLE
Current develop-Branch does not sign any jar

### ISSUE THREAD

**Issue by StephanMa** [eXist-db/exist#1079]
Cloning develop-branch does not sign any necessary jars.
(Ubuntu 16.04 Server, JRE 1.8.0._101)
Local: JRE 1.8.0_101
1) Cloning code `git clone http://github.com/eXist-db/exist -b develop --single-branch`
2) start building with `sudo ./build.sh`
3) run exist with `sudo ./startup.sh` 
4) Try to connect to eXist via Java Admin Client

Missing signed jar: `xmlrpc-client-3.1.3.jar`

Fix: 
`sudo ant jnlp-unsign-all`
`sudo ant jnlp-sign-all`

**Comment by joewiz** [comment]
Building from source has always required a separate jar signing step to allow jnlp-based launching of the Java Admin Client. This is only unnecessary when using a prebuilt (and presigned) installer.

**Comment by joewiz** [comment]
See the section called "Signing jar files for webstart" in http://exist-db.org/exist/apps/doc/building.xml.

**Comment by StephanMa** [comment]
Its  strange... i've never done this before and it worked "out of the box"...

thank you anyway

**Comment by dizzzz** [comment]
It should have worked with the installer, not for the github repo.

Probably you have used jars from the webstart cache .....
