### ISSUE TITLE
Incorrect results when using maps and wildcard with lookup operator

### ISSUE THREAD

**Issue by joewiz** [eXist-db/exist#1108]
The XQuery 3.1 spec contains an example of an expression involving a map and lookup operator whose key specifier is a wildcard. eXist's result for this query does not conform to the spec. 

The example is described at https://www.w3.org/TR/xquery-31/#id-lookup:

> If `$m` is bound to the weekdays map described in 3.11.1 Maps, then `$m?*` returns the values `("Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday")`, in implementation-dependent order.

If we construct a query using this [example weekdays map](https://www.w3.org/TR/xquery-31/#id-maps), eXist produces the map's **keys** instead of their values.

**The query:**

```xquery
xquery version "3.1";

let $m := 
    map {
        "Su" : "Sunday",
        "Mo" : "Monday",
        "Tu" : "Tuesday",
        "We" : "Wednesday",
        "Th" : "Thursday",
        "Fr" : "Friday",
        "Sa" : "Saturday"
    }
return
    $m?*
```

**Expected results:**

```xquery
("Sunday","Monday","Tuesday","Wednesday", "Thursday", "Friday","Saturday")
```

**Actual results:** (using eXist develop branch 052c842)

```xquery
("Tu", "Mo", "Su", "Fr", "Sa", "We", "Th")
```

Note that the differing order of the items in the results here is insignificant. The problem I'm reporting is that the spec says the lookup operator whose key specifier is a wildcard, i.e., `?*`, should return **values**, not keys. 

I confirmed the spec's behavior is followed by BaseX 8.5.2 and Saxon 9.7.0.4.

**Comment by dizzzz** [comment]
Closed?

**Comment by joewiz** [comment]
Thanks @dizzzz - it was closed by https://github.com/eXist-db/exist/pull/1118.

**Comment by dizzzz** [comment]
ah ok :-)
