### ISSUE TITLE
Firewall: eXistdb starts after a significant delay

### ISSUE THREAD

**Issue by dizzzz** [eXist-db/exist#1111]
I run eXist-db (installed via jar-installer) on windows7/64bit Java8 on a corporate network where no access is possible to the internet.

In the start sequence (started with `bin\startup.bat') eXist-db holds, there are no messages; after about 5-6 minutes the start continues. 

I expect there is one / are a few HTTP calls performed to the internet; which is not possible in our network configuration. I was able to grep a piece of a stackdump:

![capture](https://cloud.githubusercontent.com/assets/1700062/18278580/f8155f0c-7452-11e6-881b-f2ac7b24bd9b.PNG)

stackdump: shows that a query holds the HTTP connection for some time.... probably need to use `wireshark` to find these calls.

Interestingly I have seen a timeout too when restoring a backup; I think I recall it was in the eXide context.

I'll update this issue with my findings

**Comment by adamretter** [comment]
Almost certainly timeouts where we attempt to download something without testing connectivity first :-(.

Perhaps package updates for the Dashboard?

If you can get a dump from Wireshark/tcpdump then we will know what it is...

**Comment by dizzzz** [comment]
yeah I'll try wireshark...... I think there are actually three locations where such a call is done

- the  dashboard / package manager (I understand)
- during startup (which should not be there)
- during restore (this should not happen too)

I'll try to grap a dump for these situations...

**Comment by duncdrum** [comment]
@dizzzz any updates ?

**Comment by adamretter** [comment]
@dizzzz any updates on this, or can we close this?

**Comment by dizzzz** [comment]
can be closed.
