### ISSUE TITLE
missing support for namespace-node() test

### ISSUE THREAD

**Issue by telic** [eXist-db/exist#1120]
eXist supports the XQuery 3.0 feature of constructed namespace nodes, but does not support the corresponding `NamespaceNodeTest` needed to distinguish it from other node types.

For example,

```xquery
namespace test { 'test' } instance of namespace-node()
```

raises the error "err:XPST0003 unexpected token: ( [at line 1, column 53]"

(tested in eXist-3.0rc2-develop-c620d9c, rc1, and 2.2)

**Comment by adamretter** [comment]
@telic I just implemented this for you here - https://github.com/eXist-db/exist/pull/1131

**Comment by joewiz** [comment]
@telic Good eye! I'm curious how you came across this? And how did I ever miss your annotation-store app, https://github.com/telic/exist-annotation-store? Very cool! 

@adamretter Great, thanks for adding this!

**Comment by telic** [comment]
Thank you @adamretter 👍

> I'm curious how you came across this?

I was building a giant `typeswitch` statement to handle all the different built-in XQuery value types (see [this gist](https://gist.github.com/telic/d4a30a0ac94c0396d51e149364d2af14))

**Comment by joewiz** [comment]
@telic Neat, thanks for the gist!
