### ISSUE TITLE
err:XPTY0018 caused by variable declaration

### ISSUE THREAD

**Issue by telic** [eXist-db/exist#1121]
This simple query returns two items as expected:

```xquery
declare function local:test() { (1,<n/>) };
local:test()
```

However, simply adding an variable declaration causes a mysterious XPTY0018 error, eg

```xquery
declare variable $a := 'a';
declare function local:test() { (1,<n/>) };
local:test()
```

results in the error message 

> "err:XPTY0018 Cannot mix nodes and atomic values in the result of a path expression. [at line 1, column 24, source:...]"

**Comment by joewiz** [comment]
Likely related to #1114.

**Comment by adamretter** [comment]
@telic I have attempted to fix that here - https://github.com/eXist-db/exist/pull/1133; Unfortunately that part of eXist is pretty hairy and probably in need of some redesign in the longer term.

@joewiz I don't think that https://github.com/eXist-db/exist/issues/1114 is related.
