### ISSUE TITLE
Implement adaptive output serialization

### ISSUE THREAD

**Issue by joewiz** [eXist-db/exist#1124]
The XQuery 3.1 serialization spec has added a new output option, called "adaptive output."  (See
http://www.w3.org/TR/xslt-xquery-serialization-31/#adaptive-output.)  The idea behind adaptive output is "to allow any valid XDM instance to be serialized without raising a serialization error."  So if your query returns XML, JSON, map, array, functions, etc., you will see a usable rendition of these items. 

I have implemented a poor man's adaptive output in eXide's pretty-print.xql module, but it somewhat memory intensive, suffers from whitespace bugs due to its attempt to color and indent results, and limited to eXide. It would be nice to have this serialization method built-in and available more generally.

(For discussion about this and links to the eXide implementation, see this exist-open thread: http://markmail.org/message/47vaxvjjggt6kixx.)

**Comment by dizzzz** [comment]
link does not work for me....

**Comment by joewiz** [comment]
@dizzzz Thanks for letting me know! Fixed: Markdown didn't know that the period wasn't part of either URL.

**Comment by joewiz** [comment]
Work underway at #1448.
