### ISSUE TITLE
log files are rotated but keep growing

### ISSUE THREAD

**Issue by dizzzz** [eXist-db/exist#1126]
At an instance we see an interesting pattern in the 'rotated' logfiles: 

![l_3c29 tmp](https://cloud.githubusercontent.com/assets/1700062/18542305/7fb1ceae-7b2a-11e6-9770-d26ff69e713c.PNG)

rotation seems to be in place, but the file keeps growing and growing. 

- installed via JAR installer, 
- not running as service 

- Running with Java 1.8.0_101 [Oracle Corporation (Java HotSpot(TM) 64-Bit Server VM) in C:\Program Files\Java\jre1.8.0_101] 
- [eXist Version : 3.0.RC2] 
- [eXist Build : 20160825] 
 - [Git commit : develop-07e86ab] 
- [Operating System : Windows 7 6.1 amd64]

**Comment by dizzzz** [comment]
I checked contents: I confirm that subsequent files are the same files with some additional log entries

**Comment by dizzzz** [comment]
It turns out to be a known issue: https://issues.apache.org/jira/browse/LOG4J2-1435?jql=project%20%3D%20LOG4J2%20AND%20text%20~%20%22rotating%22 

We warned! We had 360Gig of logfiles :-( :-1:

**Comment by dizzzz** [comment]
it might be fixed in 2.6.2 : https://issues.apache.org/jira/browse/LOG4J2-904  ( [ref](https://logging.apache.org/log4j/2.x/changes-report.html#a2.6.2) )

**Comment by adamretter** [comment]
@dizzzz yes it is fixed in 2.6.2, should be a simple upgrade, happy to review a PR for it.

**Comment by dizzzz** [comment]
Ok, filed a PR ....
