### ISSUE TITLE
Restoring resources with LDAP-owner

### ISSUE THREAD

**Issue by ChiSamurai** [eXist-db/exist#1129]
We got the following scenario:
- make a backup from a LDAP connected exist install with collections and resources having LDAP users as owner
- create a new eXist install, built from latest git/development, copy /db/system/security/config.xml into the this one to connect it to LDAP
- when restoring the collection/resources with LDAP user as owner, the user is unknown to exist and therefore gets admin:dba as owner

Our /system/security - userdata is serveral years old now and already had some critical issues which makes it unreliable. Therefore restoring the user-data from the backup unfortunateliy is no option.

I haven't found a trick yet to trigger synchronizing the exist usertable with LDAP (in this case a complete sync from LDAP to eXist) and  restore the data into a fresh eXist install. I tried some workaround like creating a complete list with usernames and then do a fake login with wrong password for each account. The exist internal LDAP accounts only seem to get created when the login was successful.

Any ideas on this?

**Comment by claudius108** [comment]
With version 4.4.0, I was able to do a restore of a backup from version 2.* without problems.

So, the issues mentioned above are gone, as follows:
1. No need to copy /db/system/security/config.xml into the new eXist 4.4.0, as it is restored;
2. The collection/resources with LDAP user as owner are restored correctly as to owner:group.
