### ISSUE TITLE
Fix wrapper issues

### ISSUE THREAD

**Issue by dizzzz** [eXist-db/exist#1138]
* Settings chosen on install time, eg max_memory, is not reflected in tools/yajsw/conf/wrapper.conf making the db be run with default memory allocation, currently 1024 MB by the wrapper.
* No dynamic wrapper.conf settings at all from template wrapper.conf.install were expanded on unix platforms.
* The wrapper is always running as a privileged user eventhough eXist-db can be run as non-privileged user if specified in tools/yajsw/conf/wrapper.conf.
* Documentation is still referring to the old service wrapper so clients have problem installing the wrapper at all.

**Comment by ljo** [comment]
Both the bug, max_memory, and the feature, to run wrapper as non-privileged user under systemd  are addressed in #1141. Documentation is updated  with https://github.com/eXist-db/documentation/pull/78.

**Comment by dizzzz** [comment]
thnx!

**Comment by adamretter** [comment]
Thanks :-)

**Comment by joewiz** [comment]
+1! Thanks @ljo!
