### ISSUE TITLE
Typeswitch allows invalid checks

### ISSUE THREAD

**Issue by joewiz** [eXist-db/exist#1155]
I would expect the following query to fail, because `empty()` is not a type declaration:

``` xquery
xquery version "3.1";

let $item := ()
return
    typeswitch ($item)
    case empty() return
        'empty!?'
    default return
        'default'
```

eXist allows this through and in fact returns `empty!?`. This is using a current build of the develop branch.

**Comment by joewiz** [comment]
Looking at the spec for typeswitch expressions, only these item types should be allowed: https://www.w3.org/TR/xquery-31/#doc-xquery31-ItemType. 

> `KindTest | ("item" "(" ")") | FunctionTest | MapTest | ArrayTest | AtomicOrUnionType | ParenthesizedItemType`

I've added a narrow failing test to https://github.com/eXist-db/exist/blob/develop/test/src/xquery/xquery3/typeswitch.xql so that this issue is captured for future action. I'd be happy to modify the test if anyone has suggestions.

**Comment by joewiz** [comment]
Actually, I think the right spec reference is to the section on SequenceType Syntax: https://www.w3.org/TR/xquery/#id-sequencetype-syntax - and it's been `empty-sequence()` since XQuery 1.0.

**Comment by shabanovd** [comment]
@joewiz, you are right ;-)
