### ISSUE TITLE
log-system-out writes "raw" query to std out too

### ISSUE THREAD

**Issue by dizzzz** [eXist-db/exist#1169]
when `util:log-system-out("hahaha")`  is called from a not-stored-query, also the query itself is printed to standard out, giving a lot of noise.

e.g. the above yields into 

```
(Line: 1 util:log-system-out("hahaha")) hahaha
```

whilst I'd expect

```
(Line: 1 String) hahaha
```

the cause is in org.exist.xquery.AbstractExpression#getSource line 121:

```java
if(getSource() != null && getSource().getKey() != null) {
  buf.append(" ");
  buf.append(getSource().getKey());
}
```

as far as I see `getSource().getKey()` returns the whole query string, which does not make sense to me?

**Comment by dizzzz** [comment]
The change is from 2011 ( @adamretter  )  : https://github.com/dizzzz/exist/commit/b9b2f69638a3be94e7d1d5cb22bdad98625a3c50

**Comment by dizzzz** [comment]
my upcoming change wil write

```
(Line: 1 String) hahaha
```

**Comment by adamretter** [comment]
@dizzzz you should check the `instance of` class type of the Source, as we still want to log the filename for stored queries. non-stored queries don't have a filename.

**Comment by dizzzz** [comment]
@adamretter thnx :-) my code looks now like

```java
            if (getSource() instanceof StringSource) {
                buf.append(getSource().type());
            } else {
                buf.append(getSource().getKey());
            }
```

**Comment by adamretter** [comment]
@dizzzz looks reasonable

**Comment by dizzzz** [comment]
@somehow I'd not dare to change the StringSource implementation ; I guess it was done on purpose.... @wolfgangmm any idea?

**Comment by wolfgangmm** [comment]
getKey() is mainly used for XQuery pooling and should not be changed unless you want to refactor this as well.

**Comment by dizzzz** [comment]
@wolfgangmm I understand ; but the whole (huge) string might be a bit too much for a 'key', probably it is better to use the hashcode of the same string instead? That would load the system a bit less....

**Comment by adamretter** [comment]
@dizzzz I think you will also find that getKey is used to resolve the source code of the query, if that is the case you can't change it. If not, then yes a hash or CRC would be fine.

**Comment by shabanovd** [comment]
@dizzzz change `getKey` to hash or CRC will not solve your problem and plus to that it'll require additional calculations and memory.

**Comment by dizzzz** [comment]
@shabanovd @wolfgangmm OK lets not touch it.  My final change is building right now, please could you pull it in when done?

**Comment by adamretter** [comment]
@shabanovd A hash requires maybe 16 bytes, and the calculation is so fast as to appear instantaneous. Making copies of the hash (Java String is immutable) would ultimately lead to lowering memory consumption compare to copying the query source around.

**Comment by shabanovd** [comment]
@adamretter how are you going to release `String` memory? without that `hash` will consume additional memory.
