### ISSUE TITLE
Multiple Modules with the same Target Namespace

### ISSUE THREAD

**Issue by gspringtech** [eXist-db/exist#1174]
This is not handled by eXist. Only functions in the first location are recognised in the query.
Given two modules with the same namespace and two functions (test1, test2):

    import module namespace t = "http://example.com/test" at "test1.xqm", "test2.xqm";
    (t:test1(), t:test2())

**Comment by duncdrum** [comment]
@gspringtech could you point us to the xquery specs section that say this should be supported?

@joewiz thoughts?

**Comment by gspringtech** [comment]
@duncdrum 
https://www.w3.org/TR/xquery-31/#id-module-handling-multiple-same

**Comment by dizzzz** [comment]
@gspringtech thnx; clear!

**Comment by joewiz** [comment]
#3354 was orthogonal to this issue. This issue points out that eXist does not support multiple location hints following the `at` keyword in a module import.

**Comment by joewiz** [comment]
Take, for example, this main module:

**main.xq**
```xquery
xquery version "3.1";

import module namespace m="http://www.w3.org/TestModules/m30/test" at "test1.xq", "test2.xq"; 

$m:one + $m:two
```

And the following two library modules:

**test1.xq**

```xquery
xquery version "3.1";

module namespace t1="http://www.w3.org/TestModules/m30/test";

declare variable $t1:one := 1;
```

**test2.xq**

```xquery
xquery version "3.1";

module namespace t2="http://www.w3.org/TestModules/m30/test";

declare variable $t2:two := 2;
```

eXist will throw an exception when evaluating main.xq:

> Cannot compile xquery: err:XPDY0002 variable '$m:two' is not set. 

Thus, as @gspringtech originally stated, eXist is only importing the first library module, not the second.

This is using eXist 5.3.0-SNAPSHOT 97e80442aa438558b3dfb107ad16b354437b4582 20201021052237.
