### ISSUE TITLE
Backup failure

### ISSUE THREAD

**Issue by pherk** [eXist-db/exist#1175]
I asked this on exist-open without response ( I should be the only one with this problem??):
- after pulling latest commits on Nov 4 and rebuild my existdb installations are suffering from backup
  failure;  cron and dashboard initiated backups only; cmdln backups with backup.sh are ok.
- tons of error in exist.log: found orphaned document
- the resulting backup is nearly empty (1,7kB). 
   NB. The log file in export dir tells nothing about this, the run seems complete
 
same problem with fresh existdb from github source (3.0RC2 develop branch), 
only basic apps, no additional app/data

regards
Peter

Ubuntu 16.04LTS, java8-111

**Comment by dizzzz** [comment]
Please could you attach (parts of) the exist.log file to this ticket? rename to exist_log.txt is probably an option, (z)zipping it probably too

**Comment by pherk** [comment]
#eXist build info
project.version=3.0.RC2
project.built=20161110091651
scm.branch=develop
scm.revision=e12f039

[exist.20161110092228.log.gz](https://github.com/eXist-db/exist/files/582823/exist.20161110092228.log.gz)
[full20161110-0922.zip](https://github.com/eXist-db/exist/files/582825/full20161110-0922.zip)

[report.txt](https://github.com/eXist-db/exist/files/582827/report.txt)

**Comment by pherk** [comment]
the emergency export tool (java -jar start.jar org.exist.backup.ExportMain) shows the same symptoms on develop branch.

**Comment by wolfgangmm** [comment]
I confirm latest develop fails to create proper backups via dashboard or export tool. This is for sure a show stopper. Looking into it.

**Comment by dizzzz** [comment]
In this context, I'd like to suggest to have the 'ZIP' backup as default in the UI ; since java8 is 64bit only, the 4gig size should be not a problem anymore....
