### ISSUE TITLE
Add fn:put from XQuery 3.1 spec

### ISSUE THREAD

**Issue by joewiz** [eXist-db/exist#1178]
The XQuery 3.1 spec contains an optional feature, support for the `fn:put()` function from the XQuery Update Facility. See https://www.w3.org/TR/xquery-31/#id-fnput-feature and the spec for the function https://www.w3.org/TR/xquery-update-30/#id-func-put. Reading the specs for the function, it's left to the implementation to define what the behaviors are, but it seems supporting this function would be a relatively simple wrapper around `xmldb:store()` - and it would relieve users of the need to distinguish between the collection name and the document name when storing documents to the database. 

```
fn:put($node as node(), $uri as xs:string) as empty-sequence()
fn:put($node as node(), $uri as xs:string, $params as element(output:serialization-parameters)?) as empty-sequence()
```

The 2nd version here would only be needed if fn:put() were extended to write out to the filesystem. I suppose we could extend fn:put to be a wrapper for `file:serialize()`, but that version of the function would have to be limited to DBAs, in contrast to the more permissive `xmldb:store` which just requires permissions to write to the collection in question.

The primary benefits of this proposal are (1) simplifying the act of storing data to the database and (2) improving compliance with the features endorsed by the spec.

**Comment by joewiz** [comment]
It looks like `fn:put()` is actually being discussed at the moment in the WG: https://www.w3.org/Bugs/Public/show_bug.cgi?id=29959. Perhaps best to table this one until there is resolution to that discussion.

**Comment by dizzzz** [comment]
I'd propose to have a 'incubator' flag in conf.xml, switched off by default, so we can add bleading-edge functions to our codebase so we can use it/experiment with it, but because of this switch it is out-of-the-box not usable for a larger audience, so we can actually change behaviour whenever we want/need....

**Comment by joewiz** [comment]
Per https://www.w3.org/Bugs/Public/show_bug.cgi?id=29959#c13, the WG decided to "get rid of the optional fn:put() feature" from the spec (leaving it in the Update spec).
