### ISSUE TITLE
Update to Tika 1.16

### ISSUE THREAD

**Issue by joewiz** [eXist-db/exist#1179]
Looks like some nice additions: http://www.apache.org/dist/tika/CHANGES-1.14.txt

**Comment by dizzzz** [comment]
the challenge of Tika is to figure out (potential) jar conflicts, and which jars are really not needed (like jdbc drivers etc). Probably it is more easy (for some users) to run Tika as a standalone server and push files with HTTP to that server.

**Comment by joewiz** [comment]
Tika 1.15 is out: http://www.apache.org/dist/tika/CHANGES-1.15.txt

**Comment by joewiz** [comment]
Tika 1.16 is out: http://www.apache.org/dist/tika/CHANGES-1.16.txt

**Comment by joewiz** [comment]
Closed by #1391 (included in 3.5.0 release). Thanks again @dizzzz!
