### ISSUE TITLE
Backup/restore command line does not parse parameters

### ISSUE THREAD

**Issue by alebastrov** [eXist-db/exist#1195]
We use next eXistdb 2.2

We have **build.xml** fragment: which calls BACKUP 
~~~
 <java classname="org.exist.backup.Main" fork="true" failonerror="true">
            <arg value="-u"/>
            <arg value="${lc.user}"/>
            <arg value="-p"/>
            <arg value="${lc.pswd}"/>
            <arg value="-b"/>
            <arg value="${lc.db}"/>
            <arg value="-d"/>
            <arg value="${lc.file}"/>
            <arg value="-ouri"/>
            <arg value="xmldb:exist://${lc.endpoint}/xmlrpc"/>
            <arg value="-ossl-enable" />
            <arg value="${lc.ssl-enable}" />
            <classpath refid="classpath.core"/>
        </java>
~~~
When we pass the parameter **${lc.endpoint}** equals to **whatevereach-win80.some.thing.com** it passes to Main only part of parameter before the first **-** character, i.e. **whatevereach**, so exist got parameter like
**xmldb:exist://whatevereach** but it should equal to
**xmldb:exist://whatevereach-win80.some.thing.com/xmlrpc**

We expect that uri parameter will be passed into existdb will be **whatevereach-win80.some.thing.com**

**Comment by alebastrov** [comment]
The problem definitly in excalibur-cli.
It does not parse arguments properly, if it contains dash

**Comment by dizzzz** [comment]
is it an option to encode the dash?

**Comment by alebastrov** [comment]
I do not know if newest version works, but I had to fix it ASAP, so I write
~~~
private static final Pattern pattern = Pattern.compile("-o([^ ]++)(\\s|$)");
...
case OPTION_OPT: {
                    boolean found = false;
                    for (String arg : args){
                        if (found && !arg.startsWith("-")){
                            properties.setProperty(option.getArgument(0), arg);
                            break;
                        }
                        final Matcher matcher = pattern.matcher(arg);
                        found |= matcher.find() && option.getArgument(0).equals(matcher.group(1));
                    }
                    break;
                }
~~~
case OPTION_OPT: {
                    properties.setProperty( option.getArgument( 0 ), option.getArgument( 1 ) );
                    break;
                }
instead of 
~~~
~~~
