### ISSUE TITLE
PackageInstaller silently ignores install errors

### ISSUE THREAD

**Issue by JonathanRowell** [eXist-db/exist#1212]
An incorrect XML file in a package doesn't land in the database but remains unloaded. In repo\Deployment.java line 638 onwards, the call to targetCollection.validateXMLResource() can throw numerous types of errors which are handled in line 660 which just does a printStackTrace. Where this comes out I have NO idea, it is certainly not in any of the logs. It would be a far better idea to note here that an exception has occured and throw an exception at the end so that the installation fails, as well as to log it into some log somewhere. A stack trace, even if it did come out, is no use to anybody since it is the filename which is important (file.getName()).

**Comment by dizzzz** [comment]
Did you see my message of yesterday?

**Comment by JonathanRowell** [comment]
Yes, I did, but the original file has been overwritten during my build and I'll have to make a test file tomorrow.

**Comment by dizzzz** [comment]
fixed by https://github.com/eXist-db/exist/pull/1208

**Comment by JonathanRowell** [comment]
I have now made a grunt build for making a package containing any test code. In this case the collection is called test, the file test.xml which is faulty and does not get loaded by the package loader.

Of course Git doesn't support .xar so I have had to rename it .zip (which I suppose it is, sort of?)

**Comment by dizzzz** [comment]
yes, or add .txt after it; @adamretter it is this GitHub tracker he refers to

**Comment by JonathanRowell** [comment]
[JonathanTest-1.0.4.zip](https://github.com/eXist-db/exist/files/694417/JonathanTest-1.0.4.zip)

Yes, the problem is trying to drag and drop in Windows 7 under Virtual Box 5.0.30. The file gets dragged and dropped but github responds negatively. I have just moved the file to outside VB and the drop works perfectly. The .zip file contains the .xar file.

**Comment by dizzzz** [comment]
I confirm: the XAR file is installed, without the corrupt file; as you write;
However even with my recent changes there is nothing in any log files - I think this part of the code is not touched during deployment.....??

**Comment by dizzzz** [comment]
@wolfgangmm you are looking into this right now into this code?
