### ISSUE TITLE
required jars for contentextraction module are missing in WAR build

### ISSUE THREAD

**Issue by rvdb** [eXist-db/exist#1215]
When building a WAR file via the dist-war build task, the Tika-related libs needed for the contentextraction module aren't included, resulting in error messages such as 

    java.lang.NoClassDefFoundError: org/apache/tika/parser/Parser 
    
Manually copying all jars from the `${exist.home}/extensions/contentextraction/lib` folder to the resulting `WEB-INF/lib` folder in the extracted WAR tree solves the issue. This had been reported on the mailing list earlier: http://markmail.org/message/nlyeflol4cy4pvey.

I'll try and provide a fix for the build script in a PR.

**Comment by dizzzz** [comment]
which exist-db version?

**Comment by rvdb** [comment]
Sorry, from eXist-3.0RC1 onwards.
