### ISSUE TITLE
Null Pointer Exception on transform:transform

### ISSUE THREAD

**Issue by JonathanRowell** [eXist-db/exist#1230]
I'm getting an exception on doing a transform. I have already done the transform "by hand" using saxon HE version 9 and it's OK. The error is 

2017-01-13 15:01:42,005 [eXistThread-38] ERROR (XQueryServlet.java [process]:556) - null 
java.lang.NullPointerException
at org.exist.xquery.functions.transform.Transform$CachedStylesheet.getTemplates(Transform.java:572) ~[exist.jar:?]
at org.exist.xquery.functions.transform.Transform$CachedStylesheet.<init>(Transform.java:561) ~[exist.jar:?]
at org.exist.xquery.functions.transform.Transform.getSource(Transform.java:521) ~[exist.jar:?]
at org.exist.xquery.functions.transform.Transform.createHandler(Transform.java:424) ~[exist.jar:?]
at org.exist.xquery.functions.transform.Transform.eval(Transform.java:228) ~[exist.jar:?]
at org.exist.xquery.BasicFunction.eval(BasicFunction.java:70) ~[exist.jar:?]
at org.exist.xquery.InternalFunctionCall.eval(InternalFunctionCall.java:56) ~[exist.jar:?]
at org.exist.xquery.LetExpr.eval(LetExpr.java:142) ~[exist.jar:?]
at org.exist.xquery.LetExpr.eval(LetExpr.java:187) ~[exist.jar:?]

Attached a package. Just "eval"  transform.xql under test.

[JonathanTest-1.0.5.xar.zip](https://github.com/eXist-db/exist/files/706813/JonathanTest-1.0.5.xar.zip)

**Comment by dizzzz** [comment]
There are a number of issues with the XAR file. The file does niet seem to be valid, I cannot install it into my server;

To start: the error handling is not OK; To see the actual errors, you'd need to use the correct variable prefix:

```xquery
catch * {
   let $logged := concat($err:code," ",$err:description,": line:",$err:line-number," column:",$err:column-number)
   return $logged
 }
```

in addition the invocation of the function is not OK; out is required to make an `xs:anyURI` first:

```xquery
let $result := local:test-transform(xs:anyURI("xmldb:exist:///db/anretxt.xml"))
```

with these change I get a result, no NPE (current develop):

```xml
<schema xmlns="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" targetNamespace="http://www.bibdia.de/namespaces/anretxtRangeType" xml:mm="http://www.bibdia.de/namespaces/anretxtRangeType">
<annotation>
<documentation>Anrede von DBBEN</documentation>
</annotation>
<simpleType name="AnredeRangeType">
<restriction base="xs:positiveInteger">
<enumeration value="1"/>
<enumeration value="2"/>
<enumeration value="3"/>
<enumeration value="4"/>
<enumeration value="5"/>
<enumeration value="6"/>
</restriction>
</simpleType>
<element xmlns:ns0="http://www.bibdia.de/namespaces/anretxtRangeType" name="AnredeRange" ns0:type="AnredeRangeType"/>
</schema>
```

I cannot judge though if this is the expected outcome.

Also before my module changes of this weekend, The query yields not into a NPE when running your (modified) query.

**Comment by JonathanRowell** [comment]
Hi Dannes,


>>There are a number of issues with the XAR file. The file does niet seem to be valid, I cannot install it into my server;


Super, you have corrected the installation error - invalid file - and consequently the package doesn't install. It does on 3.0RC1. I'll remove that test.


>> To start: the error handling is not OK; To see the actual errors, you'd need to use the correct variable prefix:


This occurs in the first function, which refers to the problem regarding such prefixes in eXide and XQLint. Please ignore.


>>n addition the invocation of the function is not OK; out is required to make an xs:anyURI first


Fine, I missed that. There are places when a string in URI format is accepted without the xs:anyURI() coercion - one doesn't know when or not.


>>with these change I get a result, no NPE (current develop):


And when you DON'T change this, do you get an error with version 3.0RC - which is what it is all about. I get an error.

If you DON'T get an error with your version, then super - the problem is fixed for the next version of eXist, after the merge takes place.


Which then begs the question, should I start testing with the "nightly build" version?

I have no objection, since my work is not production.


>>I cannot judge though if this is the expected outcome.


Any outcome other than an NPE is a good outcome. I have not yet gotten round to making the system work with Jasmine, in which case I'd test with certain data and compare with an expected result.


So, all in all, very good


kind regards


Jonathan









________________________________

**Comment by dizzzz** [comment]
Without my script changes, the script did not compile and did not execute at all; I could not ignore that :-)

I'd suggest to have a look at the nightly build, which is very close to what we'll be releasing soon. However on http://static.adamretter.org.uk/exist-nightly/ the most recent is missing, I'll contact @adamretter  on what goes wrong.....

**Comment by dizzzz** [comment]
http://static.adamretter.org.uk/exist-nightly/eXist-db-setup-3.0.RC2-develop-c4cc7bb.jar  should be the latest

**Comment by JonathanRowell** [comment]
EXCELLENT!


Dank u wel!


Jonathan


________________________________

**Comment by dizzzz** [comment]
Ok to close?

**Comment by JonathanRowell** [comment]
I presume so, I actually haven't switched to nightly builds yet.
