### ISSUE TITLE
Natural sorting in exist-db

### ISSUE THREAD

**Issue by orazionelson** [eXist-db/exist#1231]
Hi all,
I'm using esist db and I have to sort a list like this:

```
R1.1.1, 
R1.1.10, 
R1.1.11, 
R1.1.2, 
R1.1.3,
```

In this way:
```
R1.1.1, 
R1.1.2, 
R1.1.3, 
R1.1.10, 
R1.1.11, 
```

I tried to use a collation like this:
`http://www.w3.org/2013/collation/UCA?numeric=yes`

```xquery
for $registro in collection($path)/EDITIO
        
        order by $registro/INFOED/FILE collation "http://www.w3.org/2015/collation/UCA?numeric=yes"
   
        return 
            if ($registro/INFOED/TIT-DOC = '...') 
            then <p>{$registro/INFOED/FILE}) {substring($registro/TENOR,1,60)}...</p>
            else <p>{$registro/INFOED/FILE}) {$registro/INFOED/TIT-DOC}</p>
```

But eXide debugger says: "Unknown collation"

How to?

Thanks,
Alfredo

**Comment by dizzzz** [comment]
Which eXistdb version do you use?

It looks we don't have this collation yet, hence the error message.

For this kind of ordering on 'semver' text I wrote myself some code....

**Comment by joewiz** [comment]
@orazionelson Unless there are some undocumented options I'm unaware of, eXist only supports the collation URIs specified in the documentation: http://exist-db.org/exist/apps/doc/xquery.xml#collations.

The one you tried—which is rooted in XQuery F&O at https://www.w3.org/TR/xpath-functions-31/#uca-collations—does **not** appear to be on this list of eXist's supported collations, but I see it is supported by other implementations. See Saxon (http://stackoverflow.com/questions/28071757/xslt-sort-alphabetically-then-numerically; http://www.saxonica.com/html/documentation/extensibility/config-extend/collation/UCA/) and BaseX (http://docs.basex.org/wiki/XQuery_3.1#Collations). 

This suggests it would be a good candidate for a feature request in eXist. The good news is that both Saxon and BaseX's collations support relies on the ICU4J library, which eXist also supports, so I imagine that the feature is within reach.

**Comment by orazionelson** [comment]
@dizzzz  i'm using the 2.2 stable.

So it seems that I've to rename files and directories :( 

Does'n exist a xquery function for natural sorting?

**Comment by joewiz** [comment]
You can hack it with casting - adapting one of the approaches like this: http://jaketrent.com/post/xquery-dynamic-order/.

Browsing through the eXist source code, I noticed an undocumented option to use a Java-based collation class. See https://github.com/eXist-db/exist/blob/develop/src/org/exist/util/Collations.java#L121-L139. I found one discussion on the list about this in the past. See http://markmail.org/message/elskhayhxxihmwzm. I don't know Java and so can't guide you in what value would get you the desired natural/numeric sort, but perhaps this is a step in the right direction.

**Comment by joewiz** [comment]
On a related point, see this list of available language collations built in to eXist: https://gist.github.com/joewiz/f5324ecad72d921bd632d08d124e8bc0.

**Comment by dizzzz** [comment]
so what I typically do is to tokenise and expand the (semver) version string, and have this used in an order by clause:

R1.1.1 -> R01.01.01 

it is a trick but it is fast enough ...

**Comment by orazionelson** [comment]
thanks @joewiz 
thanks @dizzzz the last function you linked seems to solve my troubles :+1:
