### ISSUE TITLE
Help for my first query

### ISSUE THREAD

**Issue by orazionelson** [eXist-db/exist#1232]
Hello,
I've a db with this structure:

archive
----folder1
--------document.1.1.xml
--------document.1.2.xml
--------document.1.3.xml
----folder2
--------document.2.1.xml
--------document.2.2.xml
--------document.2.3.xml

etc...

I'm trying to build a simple search form but something goes wrong.

Let's say, any document has a structure like this:

`<?xml version="1.0" encoding="ISO-8859-1"?><?xml-stylesheet type="text/xsl" href="../my.xslt"?>
<EDITIO>
    <INFOED>
     .......
    </INFOED>
    <TENOR>
        <TESTO>
In eundem modum pro civibus Urbevetanis, et sub eadem forma civibus Perusinis, ultra festum Omnium Sanctorum in anno minime valiture.Regni nostri anno primo.XIII octobris.
       </TESTO>
    </TENOR>
    <NOTE/>
</EDITIO>`

So, so starting from exist-db manual, I wrote a basic function:
` for $result in collection("/db/archive/folder1")/EDITIO[ft:query(., "urbevetanis")]  
   return
      $result`

 the result is 0

I found also this other method:
` for $result in collection("/db/registri_angioini/R1.1/")/EDITIO[. &= "urbevetanis"]
   return
      $result`

But the result is always 0.

What's wrong?

**Comment by joewiz** [comment]
@orazionelson Your use of the `ft:query()` function and the `&=` legacy full text query operator assume that you have configured a full text index on the `<EDITIO>` elements in your collection. Have you done so? To sidestep the need for an index, if only to get a result for now, you could change your query to the following:

```xquery
collection("/db/archive/folder1")/EDITIO[contains(., "Urbevetanis")]
```

(Note that `contains()` is case sensitive but does not require an index to be configured first.)

Also, for more context, could you specify your version of eXist and what "eXist-db manual" you are referring to?

**Comment by orazionelson** [comment]
@joewiz great!
I added the lucene config to collection.xconf and reindexed the collection
It Works!

**Comment by joewiz** [comment]
Good to hear! Congratulations!

Would you please close the issue?
