### ISSUE TITLE
Admin password does not work

### ISSUE THREAD

**Issue by Dimitri-UNHCR** [eXist-db/exist#1243]
Hi, after (multiple) clean installs, where I am sure I entered the correct password for admin, I am unable to log in even to do the basic tasks.

Can you please help?

I am using Java version 1.8.0_121

**Comment by joewiz** [comment]
Please close this issue and post your questions to the exist-open mailing list (and include your version of eXist and OS): https://lists.sourceforge.net/lists/listinfo/exist-open. The issues tracker is for reporting confirmed bugs.

**Comment by Dimitri-UNHCR** [comment]
Ok, thanks!

**Comment by joewiz** [comment]
Thank you! We're working on clearer instructions about the best way to get help.

**Comment by joewiz** [comment]
Sorry for any inconvenience!

**Comment by Dimitri-UNHCR** [comment]
Please do! :-)
It is a pity to get stuck on a password screen.

Keep up the great work!
