### ISSUE TITLE
wrong backup/restore command can change user password

### ISSUE THREAD

**Issue by orazionelson** [eXist-db/exist#1244]
Hi all,
I'm using exist-db 2.2 stable.

Today I corrupted my DB, so I lauched a restore by command line.

Important: I didn't set up a password for the backup when i made it.

But I launched a wrong restore command:
`bin/backup.sh -u admin -p mypassword -P anotherpassword -r /mybackuppath/db/myapp/data/__contents__.xml`

As you can see I added a the option for backup password, on a backup that wasn't set with it.

Then, when I come back on the Exist Web Interface: **I couldn't log**

So I tried to log-in with the backup password (wrongly wrote when I launched the restore) and I was able to log-in.

At the end, seems not normal that the backup.sh script can change the user password, or not?

**Comment by ChiSamurai** [comment]
Hi, I had the same issue with 3.0RC2: https://github.com/eXist-db/exist/issues/1115

**Comment by duncdrum** [comment]
indeed duplicate of #1115
