### ISSUE TITLE
Question: link index keys with documents

### ISSUE THREAD

**Issue by orazionelson** [eXist-db/exist#1246]
Hello,
I'm working on exist-db 2.2 stable.

I have collection of documents like this:
`<document>
Lorem ipsum dolor sit <name>John Smith</name> amet in suam etc etc etc <name>Cassius Clay</name>.
</document>`

I set-up a lucene index on: 

**qname="name"**

Then with this function:

`    util:index-keys(
        collection($config:data-root)/doc/name,
        (),
        function($key, $count) {
            <tr><td name="key">{$key}</td>
                <td name="frequency">{$count[1]}</td>
                <td name="documents">{$count[2]}</td>
            </tr>},
            100, 
            "lucene-index"
            )`
I have a list of marked-up names (with their frequency), more or less like "Indexes" in eXist-db "Monitoring app".

Now: how can I link the $key with the documents that contain the $key?

Thanks,
A.

**Comment by joewiz** [comment]
The `util:index-keys()` function returns only the keys and their frequency. To find the indexed nodes containing the key, use `ft:query()`:

```xquery
collection($config:data-root)/doc/name[ft:query(., $key)]
```

Also, please do not use the issues tracker for questions. Post questions to exist-open: https://lists.sourceforge.net/lists/listinfo/exist-open. The issue tracker is meant for reporting confirmed bugs.

**Comment by dizzzz** [comment]
In addition: far more people read the exist-open mailinglist, so there is a better chance for a reply.

**Comment by orazionelson** [comment]
Thanks, so I made in the right way, I just thought that there was a direct way to have something like an internal pointer to the document starting from index keys.

that's right, bye
A.

PS: Sorry, I'll use the sourceforge ML. By the way the resource is not mentioned in the exist-db.org website, where is suggested to use the Github also for questions. 
See:
"Community
If you'd like to contribute, ask questions or are looking for the sourcecode please see our github page for details."

**Comment by joewiz** [comment]
@orazionelson No worries, we need to figure out a better way to let people know. You're right, the GitHub page does link right to the Issues section, though the README.md file (shown on the same page) states:

> If you're looking for help or discussion, visit the eXist community [mailing lists](http://www.exist-db.org/exist/apps/doc/getting-help.xml) or consider purchasing the eXist book from O'Reilly.

Thanks for helping us see this!
