### ISSUE TITLE
"update replace" attribute

### ISSUE THREAD

**Issue by iguixa** [eXist-db/exist#1259]
The "update replace" statement to replace an attribute only changes the value and not the enter attribute.
Suppose:
```
<continent id="europe">
      <name>Europe</name>
      <area>9562488</area>
</continent>
```
and we can to change id="europe" per code="xxx".
The statement to get it should be:
```
update replace //continent[@id='europe']/@id 
with attribute code {'xxx'}
```
but the result is:
```
<continent id="xxx">
      <name>Europe</name>
      <area>9562488</area>
</continent>
```
Verified error in versions 2.0 and 3.0

**Comment by joewiz** [comment]
This behavior is as described in the documentation about replace:

> If it is an attribute or text node, the value of the attribute or the text node is set to the concatenated string values of all nodes in exprSingle. expr cannot be the root element of a document.

Given this, to replace an attribute node you'd need to delete the original and insert a new one in its place.

**Comment by joewiz** [comment]
@iguixa Does this answer your question? If so, would you please close the issue?

**Comment by iguixa** [comment]
Hi

I understand that a solution is to delete attribute and after insert attribute,  but the documentation does not indicate that this procedure should be followed. The documentation explains the replace statement and, according to the documentation, it should be possible to replace an attribute with the replace statement.

**Comment by duncdrum** [comment]
*cough* documentation label?

**Comment by iguixa** [comment]
[http://exist-db.org/exist/apps/doc/update_ext.xml#replace](url)
