### ISSUE TITLE
Mysterious error messages

### ISSUE THREAD

**Issue by duncdrum** [eXist-db/exist#1263]
### What is the problem
On a fresh install of exist3.0 stable on a win 7 system, after completing installation registering service etc. The console (s.b) has multiple lines off:

```Error getting buffer size in QueryServiceConfig: 1734 The array bounds are invalid.```

the error persists after multiple reboots and keeps clogging up the consoles. There are no effects i can discern so I expect some logging error the program runs fine. The exist logs do not show this error only the console in the tool window, and only on windows have i encountered this error.  

### What did you expect
 To not see any errors on a fresh install.

### Describe how to reproduce or add a test
Install exist-db3.0 > click on launcher > select "Show tool window" > Show console messages

### Context information
Please always add the following information
- eXist-db 3.0 /  acd0c14 
- Java8u121
- Operating system (Windows 7)
- 64 bit
- the system has 8gb ram available and system config using mainly defaults:
``` 
Min. Mem: 64
Max Mem: 4.096

General Cache: 512
Collection Cache: 64
```

**Comment by shabanovd** [comment]
I found [this](https://sourceforge.net/p/yajsw/discussion/810311/thread/0fce9a0d/) so far.

**Comment by daliboris** [comment]
I can reproduce the same behavior with eXist-db version 3.1.0 (build 20170307214949) - clean installation and first run.
New entries "Error getting buffer size in QueryServiceConfig: 1734..." appear after selecting Start Server or Stop Server.
I'm using Windows 8.1 64bit CZ (Windows 8.1 6.3 amd64)

**Comment by dizzzz** [comment]
some links:
- https://stackoverflow.com/questions/9582938/1734-the-array-bounds-are-invalid 
- https://social.technet.microsoft.com/Forums/windows/en-US/c4816a55-7b6f-4360-98e3-cb14b4e8a3a4/error-code-1734-the-array-bounds-are-invalid-when-trying-to-install-windows-service?forum=winserverDS

it looks like a RPC issue ; since last year we had a few yajsw upgrades, I hope these help...

- https://sourceforge.net/p/yajsw/support-requests/17/


I guess the only think we can do to keep yajsw up to date?

**Comment by duncdrum** [comment]
I no longer have access to the system on which I could produce this error, nor any other win7  system. 
Could we maybe add a test to appvoyer, to check the logs for the error messages in question?

**Comment by duncdrum** [comment]
Since i can longer test this, I m going to close. We should reopen if it still happens.
