### ISSUE TITLE
wildcard lookup for maps returns values rather than keys

### ISSUE THREAD

**Issue by peterstadler** [eXist-db/exist#1269]
This occurs only in specific contexts; please see the following test:

```xquery
xquery version "3.1";

module namespace map-lookup="http://exist-db.org/xquery/test/map-lookup";

declare namespace test="http://exist-db.org/xquery/xqsuite";

declare
    %test:assertEquals('a', 'b')
function map-lookup:wildcard1() {
    let $func := function($params as map()) as map() {
        map:new(
            for $param in map:keys($params)
            return map:entry($param, 'foo')
        )
    }
    let $map := map {'a' := 1, 'b' := 2}
    return
        map:keys($func($map))
};

declare
    %test:assertEquals('a', 'b')
function map-lookup:wildcard2() {
    let $func := function($params as map()) as map() {
        map:new(
            for $param in map:keys($params)
            return map:entry($param, 'foo')
        )
    }
    let $map := map {'a' := 1, 'b' := 2}
    return
        ($func($map))?*
};
```

### Context information
- Git commit : develop-2b67440
- eXist Build : 20170213
- Java 1.8.0_112
- Operating System : Mac OS X 10.11.6 x86_64

**Comment by dizzzz** [comment]
Could you elaborate on what you see and what you expect to see?

**Comment by peterstadler** [comment]
Yes, sorry: Both tests are identical but `map-lookup:wildcard1()` returns (in the last line of the test function) the keys of a map via `map:keys()` whereas `map-lookup:wildcard1()` uses the lookup operator `?*`. The first test (correctly) returns the map keys `('a', 'b')` but the second (wrongly) the map values `('foo', 'foo')`. 

NB: This strange behavior only occurs in this setup with the nested function call: a simple `map:keys($map)` is identical to `$map?*`

**Comment by peterstadler** [comment]
I'm getting a little confused now …
Is the lookup operator with a wildcard supposed to deliver the keys or the values when applied on a map?

My test can be simplified to 

```
xquery version "3.0";

let $map := map {'a' := 1, 'b' := 2}
return
    $map?*
```

When I run this on an older build (develop-5d6fc97 from May 2016) I get the keys ('a', 'b') – on a recent build (develop-2b67440) I get the values (1, 2).

**Comment by wshager** [comment]
@peterstadler the values, no doubt. Note that this operation is very costly, so you should probably never use it :-)

**Comment by peterstadler** [comment]
ok, then I'm happy to close the ticket and will fix my code accordingly ;)

Thanks and sorry for the noise!
