### ISSUE TITLE
Dynamic function call in a 'where' filter of 'for' on an empty sequence is evaluated

### ISSUE THREAD

**Issue by ptrckb** [eXist-db/exist#1270]
In the following example, the filter function gets evaluated even though the sequence of the 'for' is empty (`empty($words) => true()`)

``` xquery
xquery version "3.1";

declare function local:test($x as xs:string) as xs:boolean {
    true()
};
let $f := local:test#1
let $words := analyze-string('', '\w+')/fn:match/text()
return for $w in $words where $f($w) return $w
```

resulting in the error
```
exerr:ERROR XPTY0004: The actual cardinality for parameter 1 does not match the cardinality declared in the function's signature: local:text($x as xs:string) xs:boolean. Expected cardinality: exactly one, got 0.
```

If the 'where' clause is changed to avoid the dynamic function call (`where local:test($w)`), the filter function is not called and no error is reported.

Tested on eXistdb v3.0.

**Comment by shabanovd** [comment]
Will this cover your needs?
```
xquery version "3.1";

declare function local:test($x as xs:string) as xs:boolean {
    true()
};
let $f := local:test#1
let $words := analyze-string('', '\w+')/fn:match/text()
return for $w in $words[$f(.)] return $w
```

**Comment by ptrckb** [comment]
That's what I ended up with. More concise and readable than the 'where' filter. But my point was that the behavior with the filter is wrong and disturbing.

**Comment by shabanovd** [comment]
@ptrckb Can you provide full test?
