### ISSUE TITLE
err:XPTY0004 when searching in localhost (Shakespeare app)

### ISSUE THREAD

**Issue by lguariento** [eXist-db/exist#1272]
Hello,

when I search for a string locally (localhost:8080) I get the following error (see below), while when I send the same query on the exist-db website (http://exist-db.org/exist/apps/shakespeare/works/search.html?query=cleopatra&field=text&mode=any&scope=narrow) I correctly get the results I want.

What am I doing wrong? Has it something to do with my configuration?

Thanks!

err:XPTY0004 xs:string(
               ) is not a sub-type of text() [at line 72, column 23, source: jar:file:/Applications/eXist-db.app/Contents/Resources/eXist-db/exist.jar!/org/exist/xquery/lib/kwic.xql]
In function:
	kwic:callback(function?, text(), xs:string) [109:38:jar:file:/Applications/eXist-db.app/Contents/Resources/eXist-db/exist.jar!/org/exist/xquery/lib/kwic.xql]
	kwic:truncate-previous(node(), node()?, item()*, xs:integer, xs:integer, function?) [107:25:jar:file:/Applications/eXist-db.app/Contents/Resources/eXist-db/exist.jar!/org/exist/xquery/lib/kwic.xql]
	kwic:truncate-previous(node(), node()?, item()*, xs:integer, xs:integer, function?) [244:27:jar:file:/Applications/eXist-db.app/Contents/Resources/eXist-db/exist.jar!/org/exist/xquery/lib/kwic.xql]
	kwic:get-summary(node(), element(), element()?, function?) [335:17:jar:file:/Applications/eXist-db.app/Contents/Resources/eXist-db/exist.jar!/org/exist/xquery/lib/kwic.xql]
	kwic:summarize(element(), element()?, function?) [521:18:jar:file:/Applications/eXist-db.app/Contents/Resources/eXist-db/exist.jar!/org/exist/xquery/lib/kwic.xql]
	app:show-hits(node()*, map, xs:integer, xs:integer) [221:18:/db/apps/shakespeare/modules/app.xql]
	templates:call-with-args(function, function*, element(), map) [208:13:/Users/lg/Library/Application Support/org.exist/expathrepo/shared-0.4.0/content/templates.xql]
	templates:process-output(element(), map, item()*, element()) [205:9:/Users/lg/Library/Application Support/org.exist/expathrepo/shared-0.4.0/content/templates.xql]
	templates:call-by-introspection(element(), map, map, function) [187:28:/Users/lg/Library/Application Support/org.exist/expathrepo/shared-0.4.0/content/templates.xql]
	templates:call(item(), element(), map) [135:36:/Users/lg/Library/Application Support/org.exist/expathrepo/shared-0.4.0/content/templates.xql]
	templates:process(node()*, map) [146:81:/Users/lg/Library/Application Support/org.exist/expathrepo/shared-0.4.0/content/templates.xql]
	templates:process(node()*, map) [277:13:/Users/lg/Library/Application Support/org.exist/expathrepo/shared-0.4.0/content/templates.xql]
	templates:process-output(element(), map, item()*) [270:9:/Users/lg/Library/Application Support/org.exist/expathrepo/shared-0.4.0/content/templates.xql]
	templates:process-output(element(), map, item()*, element()) [205:9:/Users/lg/Library/Application Support/org.exist/expathrepo/shared-0.4.0/content/templates.xql]
	templates:call-by-introspection(element(), map, map, function) [187:28:/Users/lg/Library/Application Support/org.exist/expathrepo/shared-0.4.0/content/templates.xql]
	templates:call(item(), element(), map) [143:37:/Users/lg/Library/Application Support/org.exist/expathrepo/shared-0.4.0/content/templates.xql]
	templates:process(node()*, map) [146:81:/Users/lg/Library/Application Support/org.exist/expathrepo/shared-0.4.0/content/templates.xql]
	templates:process(node()*, map) [146:81:/Users/lg/Library/Application Support/org.exist/expathrepo/shared-0.4.0/content/templates.xql]
	templates:process(node()*, map) [146:81:/Users/lg/Library/Application Support/org.exist/expathrepo/shared-0.4.0/content/templates.xql]
	templates:process(node()*, map) [146:81:/Users/lg/Library/Application Support/org.exist/expathrepo/shared-0.4.0/content/templates.xql]
	templates:process(node()*, map) [146:81:/Users/lg/Library/Application Support/org.exist/expathrepo/shared-0.4.0/content/templates.xql]
	templates:process(node()*, map) [462:17:/Users/lg/Library/Application Support/org.exist/expathrepo/shared-0.4.0/content/templates.xql]
	templates:process-output(element(), map, item()*) [270:9:/Users/lg/Library/Application Support/org.exist/expathrepo/shared-0.4.0/content/templates.xql]
	templates:process-output(element(), map, item()*, element()) [205:9:/Users/lg/Library/Application Support/org.exist/expathrepo/shared-0.4.0/content/templates.xql]
	templates:call-by-introspection(element(), map, map, function) [187:28:/Users/lg/Library/Application Support/org.exist/expathrepo/shared-0.4.0/content/templates.xql]
	templates:call(item(), element(), map) [135:36:/Users/lg/Library/Application Support/org.exist/expathrepo/shared-0.4.0/content/templates.xql]
	templates:process(node()*, map) [131:51:/Users/lg/Library/Application Support/org.exist/expathrepo/shared-0.4.0/content/templates.xql]
	templates:process(node()*, map) [88:9:/Users/lg/Library/Application Support/org.exist/expathrepo/shared-0.4.0/content/templates.xql]
	templates:apply(node()+, function, map?, map?) [29:5:/Users/lg/Library/Application Support/org.exist/expathrepo/shared-0.4.0/content/templates.xql]

**Comment by joewiz** [comment]
Please provide all information requested in the issue template:

* eXist-db version + Git Revision hash e.g. eXist-db 3.0 / acd0c14
* Java version (e.g. Java8u121)
* Operating system (Windows 7, Linux, MacOs)
* 32 or 64 bit
* Any custom changes in e.g. conf.xml

Also: by chance, are you running eXist 3.0 installed over a previous version of eXist? If so, did you do a backup and restore when upgrading to 3.0?

**Comment by lguariento** [comment]
Hello Joe,

yes, I had a previous version installed. Anyway, I have now wiped out the old installation (both .app and org.exist folder), downloaded and installed eXist again, and I have the same error.

Version: 3.0 / acd0c14
Java version: ava8u121
OSX 10.12.3
64 bit
No changes to conf.xml, as I said I tried with a clean new installation (unless there's some hidden folder I should delete)

**Comment by joewiz** [comment]
I was able to confirm the error with the same version of eXist, Java, macOS - and this version of the Shakespeare app installed via Dashboard > Package Manager.

> Shakespeare's Works in TEI
> Version: 0.3.2
> Size: 3287k

I noticed that `system:get-version()` on http://exist-db.org/exist/apps/eXide/index.html indicated that the server hosting the Shakespeare app is running eXist 2.2. Thinking that something might've happened during the development of 3.0, I looked into the source history and found a change was made to the function signature of `kwic:callback`.

Note to @eXist-db/core: This is a great illustration of the need for a broader test suite that tests not just the core but apps and extensions too. If such a test suite included the URL <http://localhost:8080/exist/apps/shakespeare/works/search.html?query=cleopatra&field=text&mode=any&scope=narrow>, we'd have seen that a regression was introduced and that a corresponding change would need to be made to apps that relied on kwic.xql.

**Comment by adamretter** [comment]
@joewiz Yes I cleaned up the KWIC module because it had quite a lot of bugs that I was able to fix, fixing them needed some changes though. I think each app developer has to take responsibility for their app and testing it against whichever version of eXist they want to support.

Personally I am only interested in advancing the database, I have no interest in apps, and I don't want to have to maintain lots of apps which have nothing to do with the database core.

**Comment by joewiz** [comment]
@adamretter All the more reason for test suite. The core should be able to advance without fear of silent regressions, and app developers should get a heads up that they need to update their apps for compatibility with version x.y.z.

**Comment by joewiz** [comment]
Of course, for a test suite infrastructure to work, each app needs tests (this app didn't have one) - and nothing prevents app developers from creating these right away. No need to wait for a full test suite infrastructure to be ready. App developers should look at Wolfgang's http://gitlab.exist-db.org/tei-publisher/tei-publisher-app/tree/master/webtest.

Anyway, I think we can close this issue though now, right @lguariento?

**Comment by lguariento** [comment]
@joewiz yes, and thanks all for your support! Keep up the hard work.
