### ISSUE TITLE
diskImage installation on macOS dockicon

### ISSUE THREAD

**Issue by duncdrum** [eXist-db/exist#1275]
### What is the problem
The dock icon sticks around after eXist-db has been shut down for the first time after installation, like this: 
![screenshot 2017-02-21 22 34 45](https://cloud.githubusercontent.com/assets/6205362/23210627/ba7fcc0a-f8fe-11e6-9d30-81608b04f285.png)

This behaviour seems to stop after a reboot. 
### What did you expect
The dockicon to not stick around after exist has started, and for it to go away when stop-and-quitting exist. 

### Describe how to reproduce or add a test
Make a clean install of exist-db via .dmg image

### Context information
Please always add the following information
- eXist-db 3.0 /  acd0c14 
- Java8u121
-  MacOs 10.12.3
- 64 bit
- none clean install

**Comment by joewiz** [comment]
Dupe of #1248?

**Comment by duncdrum** [comment]
yes
