### ISSUE TITLE
util:log-system-out() with concat() doesn't print xml elements

### ISSUE THREAD

**Issue by GregorShear** [eXist-db/exist#1280]
This:
```
xquery version "1.0";
declare variable $commit external;
let $someVar := <test/>
let $out := util:log-system-out($someVar)
let $out := util:log-system-out(concat("hello ", $someVar, " world"))
return ()
```

produces this:
```
<test/>
hello  world
```

Expected output:
```
<test/>
hello <test/> world
```

### Context information
eXist-db 3.0
Java8u77 (build 1.8.0_77-b03)
MacOS 10.12.3 (16D32)
64 bit

**Comment by shabanovd** [comment]
@GregorShear why did you close it?

**Comment by dizzzz** [comment]
in `concat("hello ", $someVar, " world")` the contents of the element in $someVar would be visible..... which is empty, hence the output as shown.  ` util:log-system-out()` is very forgiving, if you provide a node, it will be fully serialised.
