### ISSUE TITLE
only one .xconf file per level rule not enforced nor flagged

### ISSUE THREAD

**Issue by tuurma** [eXist-db/exist#1282]
As per http://exist-db.org/exist/apps/doc/indexing.xml

> You can only have one .xconf file at each level.

Phrasing here suggest this is strict rule, not a guideline, yet no checks are in place or warnings raised when multiple .xconf files are present in a collection. 

It is unclear if multiple .xconfs are merged and acted upon or some arbitrary one is chosen?

**Comment by tuurma** [comment]
Checking further, there are checks in /db/system/config for that, nevertheless it is possible to have multiple .xconfs under /db/apps

**Comment by dizzzz** [comment]
sure, but is it clear which one is active?

**Comment by tuurma** [comment]
I suspect the first one registered in /db/system/config...
eXide produces warning when trying to trigger reindex after updating extra configuration file

**Comment by tuurma** [comment]
One observation, which I'm not sure is the expected behaviour: removing .xconf file from /db/apps via eXide does not trigger removing its counterpart from /db/system. All this I suspect must be potentially confusing for eXide users.

**Comment by adamretter** [comment]
@tuurma the `collection.xconf` should not really be placed in `/db/apps`, the reason why it is done so, is a limitation of eXist's implementation of packaging and should ideally be fixed in future.
