### ISSUE TITLE
when backing up with the Admin Client, an existing backup file is always overwritten

### ISSUE THREAD

**Issue by jensopetersen** [eXist-db/exist#129]
On Mac OS 10.9.1, using Oracle build 1.7.0_51-b13, I have done the following:

1 download latest develop (8dc2e164dd)
2 build
2 start up eXist
3 open up admin client against new build
4 accept default settings (connect type: remote) and log in to admin account with the default empty password
5 export the contents of the database to some destination
6 export the contents of the database to the same destination, using the same filename. Answer "No" to "OK to delete".
    # It does not matter what you answer - the original backup is deleted in any case.

**Comment by duncdrum** [comment]
looking at the commit this should have been closed with #1505. Please reopen if the problem persists.
