### ISSUE TITLE
webdav.ExistCollection.resourceCopyMove takes wrong Lock for copy

### ISSUE THREAD

**Issue by adamretter** [eXist-db/exist#1292]
See https://github.com/eXist-db/exist/blob/develop/extensions/webdav/src/org/exist/webdav/ExistCollection.java#L457

For performance reasons, Lock should be `READ_LOCK` when `mode == Mode.COPY`.

Suggest refactor to:
```java
final LockMode srcMode = (mode == Mode.COPY ? LockMode.READ_LOCK : LockMode.WRITE_LOCK);

...

srcCollection = broker.openCollection(srcCollectionUri, srcMode);

...

if (srcCollection != null) {
    srcCollection.release(srcMode);
}
```

**Comment by dizzzz** [comment]
AH... for a copy action READ lock is sufficient I guess...

**Comment by adamretter** [comment]
@dizzzz I believe so yes
