### ISSUE TITLE
webdav.ExistDocument.resourceCopyMove takes wrong Lock for copy

### ISSUE THREAD

**Issue by adamretter** [eXist-db/exist#1293]
See https://github.com/eXist-db/exist/blob/develop/extensions/webdav/src/org/exist/webdav/ExistDocument.java#L549

For performance reasons, Lock should be READ_LOCK when mode == Mode.COPY.

Suggest refactor to:

final LockMode srcMode = (mode == Mode.COPY ? LockMode.READ_LOCK : LockMode.WRITE_LOCK);

...

srcCollection = broker.openCollection(srcCollectionUri, srcMode);

...

if (srcCollection != null) {
    srcCollection.release(srcMode);
}

**Comment by dizzzz** [comment]
I will check on my pc, but this is about the deadlock, no?

**Comment by adamretter** [comment]
@dizzzz Nope nothing to do with deadlocks
