### ISSUE TITLE
Arrow Operator syntax edge-case error

### ISSUE THREAD

**Issue by adamretter** [eXist-db/exist#1298]
The following test-case for the arrow operator fails (also fails on Saxon and BaseX (but I don't think it should)):

``` xquery
xquery version "3.1";
declare namespace map = "http://www.w3.org/2005/xpath-functions/map";

function($k, $v) {
    "$k=" || $k
} =>
    map:for-each(
        map {
            "a" : "1",
            "b" : "2",
            "c" : "3"
        },
        ?
    )()
```

Previously described here: https://github.com/eXist-db/exist/pull/828#issuecomment-155055413, we should seek clarification from the XQuery WG.

**Comment by dizzzz** [comment]
if it fails in saxon..... interesting.

**Comment by joewiz** [comment]
@adamretter I tested after the merge of #1557, and your test still returns the following error:

> Cannot compile xquery: exerr:ERROR org.exist.xquery.XPathException: err:XPST0003 unexpected token: ( [at line 14, column 6]

(Line 14 is the last line of your query above.)

Perhaps you're right that clarification from the WG would help, especially given the observation about the same failure in Saxon and BaseX?

**Comment by line-o** [comment]
The spec clearly states the `U => f(A,B)` will evaluate to `f(U,A,B)`. https://www.w3.org/TR/xquery-31/#id-arrow-operator

Also @adamretter the below example does work:

```xquery
function($k, $v) { "$k=" || $k } 
    => (map:for-each(map { "a": "1", "b": "2", "c": "3" }, ?))()
```

**Comment by line-o** [comment]
@adamretter I believe this issue can be closed.

**Comment by adamretter** [comment]
@line-o following the spec, as you mentioned `U => f(A,B)` will evaluate to `f(U,A,B)`:

Let's break this down into steps, if I am not mistaken, then:

1. `function($k, $v) {"$k=" || $k}` reduces to: `function(item()*, item()*) as xs:string`

2. `map:for-each(map {"a" : "1"}, ?)` reduces to: `function(function(xs:anyAtomicType, item()*) as item()*)) as item()*`.

So I don't see why I can't feed (1) into (2) as the first argument, e.g.

```
function(item()*, item()*) as xs:string => function(function(xs:anyAtomicType, item()*) as item()*)) as item()*()
```

What did I miss?

**Comment by line-o** [comment]
@adamretter I totally agree, that this MAY/SHOULD work. I haven't checked how the other xquery implementations handle this, yet.
It seems, that it actually evaluates to something like `map:for-each($func, map{}, ?)`. This may due to `map:for-each($func, ?)` evaluating to a partial or that it is evaluated in a different order than what you expect.

The below example works flawlessly:

```xquery
let $function := map:for-each(map {"a" : "1"}, ?)
return function ($k, $v) { ``[`{$k}` `{$v}`]`` } => $function()
```

**Comment by line-o** [comment]
@adamretter what do you think, can we close this issue?

**Comment by adamretter** [comment]
I am still not happy that it doesn't work :-( But I don't really care any more, its just a shame that it can bite other users.

**Comment by joewiz** [comment]
Closing since eXist is working correctly in this respect, in line with Saxon and BaseX.
