### ISSUE TITLE
Trim packages from the default installer

### ISSUE THREAD

**Issue by joewiz** [eXist-db/exist#1302]
### What is the problem

The default installer contains 12 packages. Besides adding to the download size, each package adds time to the first time startup and clutter to the default dashboard. 

### Proposal

Adopt the following principles for judging which apps should be included in the default installer:

1. Include apps that are cited in the UI (namely, the menu bar references "dashboard," "eXide," and "Monitoring and Profiling") and the "shared-resources" package that these basic apps rely on. 

2. Include the core documentation (namely, "docs" and "fundocs") that arguably every user is likely to consult and the "markdown" package that fundocs relies on.

Other than these entries, demos and other libraries are readily accessible via the dashboard package manager, so should be excluded. 

A forthcoming PR will trim the following list of 12 packages (11.7 MB):

```
2.1M 00shared-resources-0.4.0.xar
646K bf-XForms-1.4.xar
559K dashboard-0.4.7.xar
497K demo-0.3.3.xar
4.3M doc-0.4.7.xar
1.4M eXide-2.3.2.xar
 30K fundocs-0.7.xar
8.4K markdown-0.4.xar
1.3M monex-0.9.6.xar
 19K xqjson-0.2.0.xar
200K xsltforms-594.xar
133K xsltforms-demo-0.1.5.xar
```

to this list of 7 packages (10.2 MB a marginal savings of 1.5 MB)

```
2.1M 00shared-resources-0.4.0.xar
559K dashboard-0.4.7.xar
4.3M doc-0.4.7.xar
1.4M eXide-2.3.2.xar
8.4K markdown-0.4.xar
 30K fundocs-0.7.xar
1.3M monex-0.9.6.xar
```

### Context information

- eXist-db version + Git Revision hash: eXist-db 3.0 develop

**Comment by wolfgangmm** [comment]
fundocs requires markdown, which should thus be included (the installer often runs without network access)

**Comment by joewiz** [comment]
@wolfgangmm Ah, thank you. I've updated the proposal and added markdown back in a new commit in the PR.

**Comment by dizzzz** [comment]
I remember a xar had a relation with xqjson too... can't recall which  one, probably demo...

**Comment by dizzzz** [comment]
Also we could consider stop distributing source code. With som instructions it can be done from GitHub without git

**Comment by joewiz** [comment]
@dizzzz If you find the xqjson dependency (even if it's on an app we drop from the default installer), please let me know, and I will adapt it to XQuery 3.1.

**Comment by dizzzz** [comment]
it is indeed the demo app:

```xml
<package xmlns="http://expath.org/ns/pkg" name="http://exist-db.org/apps/demo" abbrev="demo" version="0.3.3" spec="1.0">
    <title>eXist-db Demo Apps</title>
    <dependency package="http://exist-db.org/apps/shared" semver-min="0.4.0"/>
    <dependency package="http://xqilla.sourceforge.net/pkg/xqjson"/>
    <dependency processor="http://exist-db.org" semver-min="2.2.1"/>
</package>
```

**Comment by joewiz** [comment]
@dizzzz Okay, I'll work on removing the dependency - looks like it's limited to one file: https://github.com/eXist-db/demo-apps/blob/master/examples/contacts/contacts.xql.

**Comment by dizzzz** [comment]
you are so fast :-) I was still scanning the ticket updates of today

**Comment by joewiz** [comment]
Okay, I've created an issue to deal with the "demo" app. 

@dizzzz Thanks for your review of https://github.com/eXist-db/exist/pull/1303!
