### ISSUE TITLE
Unable to localize app title

### ISSUE THREAD

**Issue by tgraham-antenna** [eXist-db/exist#1306]
From http://markmail.org/message/z5krv2giftjkoon6

eXist-db has an i18n demo, and its techniques can be used for an app itself, but I'm left wondering how to, say, get an app title in Japanese in the dashboard of a Japanese user.

The EXPath Packaging System spec (http://expath.org/spec/pkg) allows only one `<title>`, and that `<title>` can contain only a string, so there doesn't appear to be a way to, e.g., have either multiple `<title>` or multiple things inside one `<title>` and select between them based on `xml:lang` value.

(Using 'eXist version 3.0 (develop-acd0c14)' on CentOS 7.)

**Comment by line-o** [comment]
@duncdrum would you elaborate why this issue was moved to 
https://github.com/eXist-db/existdb-dashboard/issues/12 ?
The dashboard has no defined way of extracting that information at this point.
existdb packages need to be able to provide localised application titles, first.

**Comment by duncdrum** [comment]
> but I'm left wondering how to, say,**get an app title in Japanese in the dashboard** of a Japanese user.

This is a feature request about dashboard, hence it should be in the dashboard repo

**Comment by joewiz** [comment]
Dashboard is only a manifestation of the underlying problem. Any application that reads the package `<title>` would reveal the same thing - e.g., public-repo. 

A comprehensive solution would first require updates, in the following order, to (1) the EXPath Package spec to support localization and then (2) eXist's EXPath package implementation. 

Then apps that read package info would have a localized string to display.

So really this properly would be classified as a feature request to the EXPath Package spec.

**Comment by duncdrum** [comment]
The OP directed his request at the Dashboard, if the maintainer of the Dashboard wants to move it elsewhere that is his/her call. As it stands its not and eXist-db/exist core request or feature.

**Comment by duncdrum** [comment]
This issue was closed, please continue discussion in eXist-db/existdb-dashboard#12 thx
