### ISSUE TITLE
calls to doc() in an XSLTSerlvet context executed within the database throw URIResolver errors

### ISSUE THREAD

**Issue by rvdb** [eXist-db/exist#1312]
### What is the problem
When called in an XSLT stylesheet, which is executed via XSLTServlet within the database, the `doc()` function fails with following error:

    SAX exception while transforming node: Exception thrown by URIResolver

Yet, the URI does resolve, and the same XSLT stylesheet is working without errors when called with the `transform:transform()` function, and when executed via XSLTServlet on the file system.

Moreover, **execution order** seems to matter (see below).

### What did you expect

In the sample app (see below), I'd expect the call to `doc('http://localhost:8080/exist/apps/doc-test/test.xml')` to be resolved properly, and to get following output from the simple XSLT stylesheet, irrespective of the execution context / order: 

    <xslt-output><h1>doc() has succeeded!</h1></xslt-output>

### Describe how to reproduce or add a test
The zip file attached [doc-test.zip](https://github.com/eXist-db/exist/files/814514/doc-test.zip) contains a sample web application demonstrating the problem, which can be reproduced by following steps:

1. install the `doc-test-0.1.xar` file in the database
2. navigate to http://localhost:8080/exist/apps/doc-test/test-XSLTServlet/

This will cause an HTTP ERROR 500, stating that 

> An error occurred: SAX exception while transforming node: Exception thrown by URIResolver

Additional remarks: 

#### 1. execution context matters
The error only occurs when the XSLT transformation is executed via XSLTServlet within the database.

- If the same XSLT transformation is executed via the `transform:transform()`  function in an XQuery script stored in the database, it succeeds without errors. See http://localhost:8080/exist/apps/doc-test/test-transform/ for an example.
- If the same XSLT transformation is executed via XSLTServlet on the file system, it succeeds without errors. See http://localhost:8080/exist/doc-test/test-XSLTServlet/ for an example (this requires that the zip file is extracted in the `${exist.home}/webapps/` directory.

#### 2. execution order matters
The error occurs when the XSLT transformation is executed via XSLTServlet within the database, but once the same transformation is executed via the `transform:transform()`  function in an XQuery script stored in the database, subsequent executions via XSLTServlet succeed without errors. See following steps:

1. Execute via XSLTServlet: http://localhost:8080/exist/doc-test/test-XSLTServlet/ --> error
2. Execute via `transform:transform()`: http://localhost:8080/exist/apps/doc-test/test-transform/ --> success
3. Execute via XSLTServlet: http://localhost:8080/exist/doc-test/test-XSLTServlet/ --> **success**

Since this error doesn't occur in eXist-3.0.RC1 (nor in eXist-3.0.RC2, although that version is giving me troubles with local paths to `doc()` that I couldn't reproduce, unfortunately), I suspect that it might be related to the issues that have been addressed recently in https://github.com/eXist-db/exist/pull/1221.

### Context information
- eXist-db version: 3.0 /  acd0c14
- Java: 1.8.0_112
- Operating system: Windows 7
- 64 bit
- No custom changes

**Comment by dizzzz** [comment]
In the mail the following files was added:
[doc-test-0.1.xar.txt](https://github.com/eXist-db/exist/files/815091/doc-test-0.1.xar.txt)

**Comment by rvdb** [comment]
I've finally had the chance to test, and can confirm this issue is fixed by @shabanovd's PR https://github.com/eXist-db/exist/issues/1316. What are the prospects for merging it into trunk? Even if it won't make it into the next eXist release, being able to update my webapps to the latest eXist development code would be a great temporary solution in the mean time.
