### ISSUE TITLE
Call to doc() inside XSL fails.

### ISSUE THREAD

**Issue by RemiKoutcherawy** [eXist-db/exist#1325]
### What is the problem
`<xsl:value-of select="$lutdoc//product/id"/>` fails :
```
exerr:ERROR Exception while transforming node: Internal error evaluating
template in module [at line 36, column 16]
```

### What did you expect
When uncommenting the 2 lines in the provided test it should report :
`<ok> Lutdoc: First 100 Second 200 LutIds:100 200 Name:First</ok>`

### Describe how to reproduce or add a test
A 'self containing' test, a test that can be run without dependancies. 
Given an XML with only <id> and "A-Lut.xml" containing both <id> and <name> used as Look Up Table the XSL matches <id> in current input and looks up using doc("A-Lut.xml") to output <name>.
The "A-Lut.xml" is first stored in the base by "A-Bug.xql" to make the test 'self contained'.
The XML input and the XSL are built in memory by the test, then passed to transform:transform()

`A-Bug.xql` stored in /db/apps/bugs
```xquery
xquery version "3.0";
declare namespace xmldb = "http://exist-db.org/xquery/xmldb";
declare option exist:serialize "method=xml media-type=text/html";

let $lut :=
<lut>
   <product>
     <name>First</name>
     <id>100</id>
   </product>
   <product>
     <name>Second</name>
     <id>200</id>
   </product>
</lut>

let $store := xmldb:store('/db/apps/bugs', 'A-Lut.xml', $lut)

let $xmlin :=
<root>
   <product>
     <id>100</id>
   </product>
</root>

let $xslSheet :=
   <xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
version="2.0">
     <xsl:param name="lut">A-Lut.xml</xsl:param>
     <xsl:template match="id">
       <xsl:variable name="lutdoc" select="doc($lut)"/>
       Lutdoc:<xsl:value-of select="$lutdoc"/>
<!--      LutIds:<xsl:value-of select="$lutdoc//product/id"/> -->
<!--      Name:<xsl:value-of select="$lutdoc//product/id[. = current()]/../name"/>-->
     </xsl:template>
   </xsl:stylesheet>

let $xmlout := transform:transform($xmlin, $xslSheet, ())
return <ok>{$xmlout}</ok>
```

### Context information
With
- eXist-db version: 3.0 / acd0c14
- Java: 1.8.0_112
- Operating system: macOS 10.12.3 (16D32)

It fails on `<xsl:value-of select="$lutdoc"/>`
```
exerr:ERROR Exception while transforming node: I/O error reported by XML
parser processing file:/Users/remi/git/exist-develop/A-Lut.xml:
/Users/remi/git/exist-develop/A-Lut.xml (No such file or directory) [at
line 38, column 16]
```
doc($lut) seems to read from the file system not the database.

With patch https://github.com/eXist-db/exist/pull/1316
in eXide, it finds the file "A-Lut.xml" in the base and reports:
`<ok> Lutdoc:First100Second200</ok>`
doc($lut) finds the file in the base, but seems to get only text.

Sadly the patch corrects only part of the bug.
Uncomment <xsl:value-of select="$lutdoc//product/id"/> and it fails :
```
exerr:ERROR Exception while transforming node: Internal error evaluating
template in module [at line 38, column 16]
```

Uncomment the next line, tweak xsl param, and it reports correctly :
`<ok> Lutdoc: First 100 Second 200 LutIds:100 200 Name:First</ok>`
exactly as Saxon on command line (in fact this is the return from embedded Saxon)

For the sake of completeness by "tweak xsl param" I mean
replace `xsl:param name="lut">A-Lut.xml</xsl:param>`
with `<xsl:param name="lut">xmldb:exist:///db/apps/bugs/A-Lut.xml</xsl:param>`
witch is a way to bypass the bug.

Rémi

**Comment by shabanovd** [comment]
@RemiKoutcherawy can you test this [branch](https://github.com/shabanovd/exist/tree/bugfix/isSameNode)?

**Comment by RemiKoutcherawy** [comment]
Le 11/03/2017 à 09:58, Dmitriy Shabanov
      a écrit :
    
    
      @RemiKoutcherawy
        can you test this branch?
      
      
    
    Hi, and thanks.
    
    Your branch is OK given full path in doc() inside XSL :
https://github.com/RemiKoutcherawy/exist/commit/4fe31a1c1e87f5f51baef7849adaedeffb345c62
    
    Down to the bone, from the command line :
    $ java -jar ./lib/endorsed/Saxon-HE-9.6.0-7.jar -xsl:A-sheet.xsl
    -s:A-xmlin.xml
    gives correct result.
    
    In eXist 
    doc(A-lut.xml) fails
    doc(xmldb:exist:///db/transform-test/A-Lut.xml) succeeds 
    
    In Saxon from the command line
    doc(A-lut.xml) succeeds
    doc(xmldb:exist:///db/transform-test/A-Lut.xml) fails
    
    A-sheet.xsl A-xmlin.xml can be found here:
https://github.com/RemiKoutcherawy/exist/commit/8d05db2c661091c0f5be0f7829cb06b1b5b403c1
    
    I simplified a bit, the xql is not used to store A-Lut.xml in the
    base, and can be reduced to 4 lines :
            String query =
                "import module namespace
    transform='http://exist-db.org/xquery/transform';\n" +
                "let $xml := doc('A-xmlin.xml')\n" +
                "let $xsl := doc('A-sheet.xsl')\n" +
                "return transform:transform($xml, $xsl, ())";
            String result = execQuery(query);
    
    No hurry
    With default param Oxygen is OK, and can be used to debug XSL.
    From Exist-db param can be used to prefix with
    "xmldb:exist:///db/path-to-lut-xml/" 
    
    Rémi
    
    
    
    
    
      
        
          
          
        
        
      
      {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/eXist-db/exist","title":"eXist-db/exist","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/eXist-db/exist"}},"updates":{"snippets":[{"icon":"PERSON","message":"@shabanovd in #1325: @RemiKoutcherawy can you test this [branch](https://github.com/shabanovd/exist/tree/bugfix/isSameNode)?"}],"action":{"name":"View Issue","url":"https://github.com/eXist-db/exist/issues/1325#issuecomment-285853915"}}}

**Comment by shabanovd** [comment]
>    In eXist
>    ```doc(A-lut.xml) fails
>    doc(xmldb:exist:///db/transform-test/A-Lut.xml) succeeds
>
>    In Saxon from the command line
>    doc(A-lut.xml) succeeds
>    doc(xmldb:exist:///db/transform-test/A-Lut.xml) fails

@RemiKoutcherawy I'd say your results expected. Saxon do not know eXist, so only running saxon under eXist allow to access db.

`In eXist doc(A-lut.xml) fails` - do you run stored xquery or just eval xquery?

**Comment by RemiKoutcherawy** [comment]
You are right.
I would have  prefered having the same XSL in and out the db.
All my xquery are stored, never thought of evaluating them outside, that's a new idea.
I'll tamper my fork.

**Comment by shabanovd** [comment]
@RemiKoutcherawy only relative paths can help you to have same XSL in and out the db.

**Comment by shabanovd** [comment]
btw, @RemiKoutcherawy test is [here](https://github.com/shabanovd/exist/blob/c68dabdd5945f40f2519041bb444178803c51beb/test/src/org/exist/xquery/TransformTest.java#L54)

**Comment by adamretter** [comment]
@RemiKoutcherawy You could also register an eXist URI resolver with Saxon I suspect if you wanted Saxon outside of eXist to be able to access an eXist database.
