### ISSUE TITLE
infinispan.xml to be reset after rebuild?

### ISSUE THREAD

**Issue by pherk** [eXist-db/exist#1335]
no big problem, but annoying.
I frequently forget to re-edit 
   webapp/WEB-INF/classes/infinispan.xml
after rebuild (bfSessionCache too small).

regards 
Peter

**Comment by joewiz** [comment]
Thank you for reporting your issue!

To be able to better understand you problem or suggestion, please add as much information as possible to this ticket. When there is no or just little information, it will be too difficult to work on it (and hence we will not be able to solve it)

Please fill in the following sections:

### What is the problem
> Describe exactly what you see (e.g. an output of an XQuery) 

### What did you expect
> Describe what you expected to happen. Add for example a reference to a [specification](https://www.w3.org/TR/xquery-3/).

### Describe how to reproduce or add a test
> Describe how we can can reproduce the problem.

> The *best* way is to provide a 'self containing' test, a test that can be run without dependancies. The [XQSuite - Annotation-based Test Framework for XQuery](http://exist-db.org/exist/apps/doc/xqsuite.xml) makes it very easy for you to create tests. These tests can be executed from the [eXide editor](http://exist-db.org/exist/apps/eXide/index.html) (XQuery - Run as Test)

### Context information
Please always add the following information
- eXist-db version + Git Revision hash e.g. eXist-db 3.0 /  acd0c14 
- Java version (e.g. Java8u121)
- Operating system (Windows 7, Linux, MacOs)
- 32 or 64 bit
- Any custom changes in e.g. conf.xml

**Comment by pherk** [comment]
I respect the template but thought it would be clear enough ;-)
My problem: parameter changes in infinispan.xml will be reset with each rebuild
  build.xml 
         copy $betterform.webapp/WEB-INF/classes/infinispan.xml to $exist.webapp/WEB-INF/classes
My Expection: changes should be preserved
Test: not needed, see above
Context:
- eXist-db newest develop
- java8
- Linux Ubuntu 12.04LTS, 64bit
