### ISSUE TITLE
backup/restore not working

### ISSUE THREAD

**Issue by andray71** [eXist-db/exist#1338]
### What is the problem
when executing command:
`bin/backup.sh --restore "$EXIST_BACKUP/backup-config-service.zip" -u admin -p "$EXIST_ADMIN_PASSW"`

getting error:
`Missing required arguments: [-b]null`

### What did you expect
database/collection restored. It worked in previous version 3.0

### Describe how to reproduce or add a test
just try to restore any collection using command line

### Context information
Please always add the following information
- eXist-db version: eXist-db 3.1.0 (running in Docker - FROM openjdk:latest...)
- Java version (e.g. Java8u121): 
openjdk version "1.8.0_121"
OpenJDK Runtime Environment (build 1.8.0_121-8u121-b13-1~bpo8+1-b13)
OpenJDK 64-Bit Server VM (build 25.121-b13, mixed mode)
- Operating system: Linux 4.9.12-moby amd64
- 64 bit
- Any custom changes in e.g. conf.xml: no

**Comment by wolfgangmm** [comment]
Argument -b is for creating a backup. You should remove it for restore.

**Comment by andray71** [comment]
the error I'm getting when i run restore, with out -b

**Comment by StephanMa** [comment]
I can confirm that the restore is not working with the current develop-branch

`sudo ./backup.sh -u admin -p "pass" -P "pass" -r Path_To_File.zip -ouri=xmldb:exist://localhost:8181/xmlrpc`

Error as described: 
`Missing required arguments: [-b]null`

**Comment by shabanovd** [comment]
@StephanMa, you can use `system:import` or `system:import-silently` xquery functions. (`system:import-silently` good for big backups, it redirect information to backup log file).

Here an example for your case: `system:import-silently("Path_To_File.zip", "pass", "pass")`.

**Comment by wolfgangmm** [comment]
The following command line should work on a headless system:

```sh
bin/client.sh -l -s -x "system:restore('/path/to/backup.zip', 'admin-pass', 'restore-admin-pass')"
```

**Comment by StephanMa** [comment]
Nice thank you!

**Comment by andray71** [comment]
Thanks!!!
