### ISSUE TITLE
cannot save xml when directory name contains diacritics

### ISSUE THREAD

**Issue by eduarddrenth** [eXist-db/exist#1346]
os: ubuntu
exist 3.0

steps:

1) mount dav://localhost:8080/exist/webdav/db
2) create a collection "tdb" (via collection browser)
3) create a directory "hânskriften" in tdb via nautilus
4) upload some xml file in it
5) use the collection browser to browse to the file
6) open the file in exide, change it, try to save it

You will see a fault: Collection /db/tdb/h%25C3%25A2nskriften not found. Could not locate collection: /db/tdb/h%25C3%25A2nskriften

opening and saving this file in oxygen via exist datasource succeeds.

**Comment by shabanovd** [comment]
@eduarddrenth this is eXide [issue](https://github.com/wolfgangmm/eXide/issues/151).
