### ISSUE TITLE
Document potential startup issues upgrading with apps installed where apps are not compatible with API anymore

### ISSUE THREAD

**Issue by ljo** [eXist-db/exist#1373]
### What is the problem
With some API changes installed apps cause startup issues when upgrading eXist-db. Noticed i) stopping startup, ii) only giving error

### What did you expect
Avoid stopping (severerst case) so that startup continues and the app can be upgraded. Minimally document  how to most easily remove the offending app to enable startup.

### Describe how to reproduce or add a test
Looking into all the cases yet. But startup should generally be made more robust and avoid stopping on errors. 

### Context information
- eXist-db version 2.3+

**Comment by joewiz** [comment]
I think I may have a case: https://github.com/wolfgangmm/monex/issues/44. Is that the phenomenon you were thinking of?

**Comment by duncdrum** [comment]
@ljo any progress on this?

**Comment by dizzzz** [comment]
reproducing is really easy (have a loaded with many default apps created in a 4.x database, restore database into 5.x: XARs are not updated) . running the package repair scripts alone does NOT help.

 I wrote a procedure how to d this manually, but can be automated. In essecne:

- stop database
- check in autodeploy the xar files
- remove the entries from two files in `exist-distribution\target\data\expathrepo\.expath-pkg`
- start database
- run package repair scripts
