### ISSUE TITLE
EXPath Repo creates static absolute path properties

### ISSUE THREAD

**Issue by mathias-goebel** [eXist-db/exist#1382]
### What is the problem
When installing a package, the repo system stores information in classpath.txt that contains absolut pathes from the filesystem. this makes it hard to move an instance from one location to another (same machine, or from local to server, when pathes are different).
see for example:
`webapp/WEB-INF/data/fs/db/apps/monex/.exist/classpath.txt`
`webapp/WEB-INF/data/expathrepo/monex-0.9.7/.exist/classpath.txt`

### What did you expect
I belive that i was able to move instances by copypasting or moving the folder in previous versions.

### Describe how to reproduce or add a test
start exist the first time with monex and a package that imports console in the autodeploy folder.
stop exist.
move the folder with for example `mv exist exist-moved`
start exist again
monex and console are not working and so the package with the dependency doesnt.

you can try it by calling `ant sade-dist-build` from https://gitlab.gwdg.de/fontane-notizbuecher/SADE.git develop branch
after the build task is completed 
`mv ./dist-build/antbuild/build/sade ./dist-build/antbuild/build/sade2
./dist-build/antbuild/build/sade2/bin/startup.sh`

### Context information
Please always add the following information
- eXist-db version 3.1.1
- openjdk version "1.8.0_121"
- OpenJDK Runtime Environment (build 1.8.0_121-8u121-b13-0ubuntu1.16.04.2-b13)
- OpenJDK 64-Bit Server VM (build 25.121-b13, mixed mode)
- ubuntu
- 64 bit

**Comment by dizzzz** [comment]
I have seen this file, it has been introduced rather recently. I did not realise the consequences. As I see it, this file is needed to initialise the java class loader. Moving (renaming) an app in a live database is probably not possible when additional JARs are in the XAR. Classloading is quite difficult....

**Comment by dizzzz** [comment]
@mathias-goebel did you actually move a directory in the filesystem (as in: not via the eXIst-db APIs). It depends on your definition of "folder" ... is this a filesystem directory or an eXist-db collection?

if you attempt to modify the filesystem.. this is really not supported, you should always use the xquery functions, or one of the APIs.

**Comment by mathias-goebel** [comment]
i mean folder/directory on the filesystem.
all configurations were relative to $EXIST_HOME.
a possible workflow was: build and test a version of eXist including all nessecary packages running for example in a home folder and after completing some testing or further development/bugfixing moving an instance to for example /opt

**Comment by dizzzz** [comment]
Ah ok. In general: one should not modify anything under `webapp/WEB-INF/data` ; it is not designed to do this, and in the end it will not work, or worse: it will de-stabilize your server! One should always use the API (HTTP API or xquery functions) to make modifications.

If it was possible in previous versions, you were lucky :-)

In addition: we do not  guarantee the content `webapp/WEB-INF/data` to be compatible between eXist-db versions.

TLTR: don;t try this at home :-)

**Comment by mathias-goebel** [comment]
No, i dont want to edit anything inside webbapps, nor do i want to edit anything inside the exist-db directory where i installed/builded the database in. i want to move the $EXIST_HOME dir after the first initialisation of the db.

**Comment by dizzzz** [comment]
ah ok. yes, then in the current implementation with the improved expath jar  things would not work..... We can improve that for sure, but I guess it is (partly) a third party app. @wolfgangmm has been working on it...

**Comment by joewiz** [comment]
In the 2017-03-27 community call @shabanovd confirmed that this is a bug: "eXist shouldn’t break when paths change."

**Comment by mathias-goebel** [comment]
besides the `classpath.txt` files are still present, i do not encounter the issue when moving $EXIST_HOME tested with eXist-5.0.0-RC5. so i can not confirm that eXist breaks when moving anymore, but for any production i still continue to prepare the database in a path equal to the target system on production.

you may consider to close this issue, but some concerns about the static paths in the textfiles are still left on my side.

**Comment by line-o** [comment]
Just tested on exist 5.3.0-SNAPSHOT: no `classpath.txt` files present. Closing this issue.
