### ISSUE TITLE
%test:pending messes with execution of testsuite

### ISSUE THREAD

**Issue by duncdrum** [eXist-db/exist#1389]
### What is the problem
using the example from the [documentation](http://exist-db.org/exist/apps/doc/xqsuite.xml?q=test&field=all&id=D1.2.8#D1.2.8) when adding a pending test it messes with the execution of not pending test.

I have another example, which i haven't been able to reduce for this issue, where pending tests are not counted at all in the testsuite report.  Something is off

### What did you expect
Following Adam's [example](https://github.com/eXist-db/exist/pull/365) when adding a ``%test:pending`` I expect a) the test suite to report the number of pending tests, b) report the number of not-pending tests and c) run all not-pending tests.

### Describe how to reproduce or add a test
Change the example linked above to this:
```xQuery
declare 
    %test:arg("n", 1) %test:assertEquals(1)    
    %test:arg("n", 5) %test:assertEquals(119)    
    %test:pending("something witty") %test:assertEquals(720) 
function m:factorial($n as xs:int) as xs:int {
    if ($n = 1) then
        1
    else
        $n * m:factorial($n - 1)
};
```
then run ``suite.xql``
Result:
```xml
 <testsuite package="http://foo.org/xquery/math" timestamp="2017-03-31T15:22:19.688+02:00" failures="0" pending="1" tests="1" time="PT0.001S">
```

which is odd there are *two* tests that should run as normal and *one* test pending.
In another example i can't get the test-suite to correctly report the number of pending test in a module at all, will try to add a reproducible example here. 

### Context information
Please always add the following information
- eXist-db version 3.1.1
- Java version (e.g. Java8u121)
- MacOs 10.12.4
- 64 bit

**Comment by adamretter** [comment]
`%test:pending` is interpreted at the function level and not the assert level.

I am not sure this is a bug. I had intended it to be interpreted at the function level. However, an enhancement/feature request could perhaps to be to make it more fine grained.

**Comment by duncdrum** [comment]
@adamretter in this case the documentation should match this intended use, and not list ``pending`` as with other assertions that can occur together. If ``pending`` is function level then i would expect none of the assertions to be executed, but currently one is executed and one silently omitted sounds pretty buggy to me.  Still working on a mwe for the other behaviour where ``pending`` assertions aren't counted at all.
