### ISSUE TITLE
Disabling the SQL Module breaks the build

### ISSUE THREAD

**Issue by adamretter** [eXist-db/exist#1392]
Because a test for the SQL Module is in the core `src/org/exist/xquery/modules/sql/ExecuteFunctionTest.java` if you disable the SQL module in `extensions/build.properties` or `extensions/local.build.properties` then eXist fails to build.

**Comment by opax** [comment]
Where would be the proper place for a unit test for a module? There is no `test` folder in `extensions/modules`. The only other module test I could find is for the compression module and lives in `test/src/xquery/modules/compression`. 

Would it be better to place `ExecuteFunctionTest.java` in `test/src/xquery/modules/sql`?

**Comment by adamretter** [comment]
@opax I think we might have to wait until we can reorganise the build into proper modules, e.g. https://github.com/eXist-db/exist/issues/736

**Comment by gmella** [comment]
@adamretter I just had a look on the sql module and think that this issue may be closed.

**Comment by adamretter** [comment]
@gmella thanks for the update :-)
