### ISSUE TITLE
MutableCollection throws an error

### ISSUE THREAD

**Issue by alebastrov** [eXist-db/exist#1393]
existDB 2.2, and 3.x as well

As you may see lockUser checking if broker.getCurrentSubject() equals to it. But they are different classes and cannot be checked by equality (Subject extends Account) - see J.Bloch effective Java

~~~
final Account lockUser = oldDoc.getUserLock();
            if(lockUser != null && !lockUser.equals(broker.getCurrentSubject())) {
                throw new PermissionDeniedException("The document is locked by user '" + lockUser.getName() + "'.");
}
~~~
So it needs to be changed for instance
~~~
final Account lockUser = oldDoc.getUserLock();
            if(lockUser != null && !lockUser.getName().equals(broker.getSubject().getName())) {
                throw new PermissionDeniedException("The document is locked by user '" + lockUser.getName() + "', but we are trying o do it as " + broker.getSubject().getName());
            }
~~~

**Comment by shabanovd** [comment]
@alebastrov It's ok because this [equals](https://github.com/eXist-db/exist/blob/develop/src/org/exist/security/AbstractAccount.java#L244) method is used.
