### ISSUE TITLE
Unexpected jmx repsonses

### ISSUE THREAD

**Issue by funkyfuture** [eXist-db/exist#1396]
### What is the problem

i'v started an exist-db instance that was invoked with this command:

    /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java -Xms128m -Xmx666m -Dfile.encoding=UTF-8 \
    -Djava.endorsed.dirs=/opt/exist_3.1_8080/lib/endorsed -Dcom.sun.management.jmxremote \
    -Dcom.sun.management.jmxremote.port=8081 \
    -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false \
    -Dexist.home=/opt/exist_3.1_8080 -jar /opt/exist_3.1_8080/start.jar jetty --http-port 8080

then i want to query the jmx interface:

    $ curl http://127.0.0.1:8081/exist/status?c=all
    curl: (52) Empty reply from server

but:

    $ curl http://127.0.0.1:8080/exist/status?c=all
    <jmx:jmx>…</jmx:jmx>

### What did you expect

A reply from port `8081` and non on that path from `8080`.

### Context information
- eXist-db version + Git Revision hash:  eXist-db 3.1.1 /  fe05cf7
- OpenJDK Runtime Environment (build 1.8.0_121-8u121-b13-0ubuntu1.16.04.2-b13)
- Ubuntu 16.04.2 LTS on a 64bit cpu
- only the https configuration has been disabled

**Comment by dizzzz** [comment]
You are mixing up some concepts. The JMX port (typically 1099) can only be accessed using e.g. the jconsole application. The response on port 8080 is actually eXist-db code that serializes (some) JMX data to an XML document. This input is used e.g. by the Monex application, and is designed to work this wat.

In your case, port 8081 will never respond on a HTTP call.

**Comment by funkyfuture** [comment]
thanks for your quick response. yeah, the sphere of concepts in Javaland will always remain a mystery to me.

my concept stemmed from [this page](http://exist-db.org/exist/apps/doc/jmx.xml):
- at the beginning it tells me about enabling the jmx agent
  - this suggests an opt-in, not a default
- 'Use JConsole', 'Use JMXClient' and 'JMXServlet' seem to be equally usable approaches to query that (seemingly same) backend
  - since i'd prefer a rest-api, i went straight to the latter
  - in particular, it's not obvious that this one relates to another backend
    - this may be derived from the knowledge what a certain port is usually used for

what would be the recommended way to achieve the following with command line arguments?
- application internals are not accessible via the application port
- a rest-api on another port for monitoring purposes

i'm also troubled by the thought that a whole lot of initmate information is available via the application port by default. even more considering there are plans to make the config writable via that interface.

**Comment by dizzzz** [comment]
There are two different levels of info; out of the box it is possible to retrieve JMX data from the java VM (think of memory usage etc). With the '-j' switch additional eXist-db specific data is made available.

Indeed, All three routes essentially provide the same information.

I realise that the documentation is not complete; it should be added that the JMX information is only accessible via the HTTP interface when

- the client access the API  on localhost 
- a token is provided when accessing the API from remote

So your data is safe. Exist-db does not provide a way of having parts of the HTTP interface exposed via different HTTP ports, I guess that is not the intention of an application server. For these use cases it is a better to look at a nginx based reverse proxy, and have the 8080 port not externally exposed. This is a typical setup for production environments anyway.

**Comment by funkyfuture** [comment]
> JMX information is only accessible via the HTTP interface when

this could be mentioned more explicitly.

**Comment by dizzzz** [comment]
yes, as already written in my response, and as ticketed by @joewiz we'll write about this.

**Comment by duncdrum** [comment]
please continue the discussion in the linked documentation issue. Thx.
