### ISSUE TITLE
client.sh does not handle '-p'

### ISSUE THREAD

**Issue by pherk** [eXist-db/exist#1401]
### What is the problem
> client.sh says: Didn't expect -p ...
client.sh -h shows a lonely p
nb --parse works

typo? `src/org/exist/client/CommandlineOptions.java`:
```java
    private static final Argument<List<File>> parseDocsArg = fileArgument("p", "--parse")
.description("store files or directories given as extra args on command line.")
```

### Context information
- eXist-db newest develop 
- Java8u121
- Ubuntu 16.04LTS

Peter

**Comment by adamretter** [comment]
@pherk Thanks for reporting
