### ISSUE TITLE
following-sibling axis not working correctly

### ISSUE THREAD

**Issue by merenyics** [eXist-db/exist#1407]
### What is the problem
> the following-sibling axis doesn't work when used with an element name. Both
`$items//b/following-sibling::a`
and
`$items//b[following-sibling::a]`
fail to return any nodes, even though the items in $items do contain such nodes. 

What does work is:

- the preceding-sibling axis used the same way, i.e. with an element name specified (no surprise here)
and the following workarounds
- `$items//b/following-sibling::*[name()='a']`
- `$items//b/self::*[following-sibling::a]` (so following-sibling with element name does work after all, but only under very special circumstances)

### What did you expect
> I expected the following-sibling axis to work correctly in all the above cases

### Comment
I saw this bug reported in the mailing list a couple of years ago, but it seemed to receive surprisingly little attention, even though it seems to me like a really huge, mission-critical issue. (Well, luckily, there is the workaround with name(), but still.) Would someone with more experience kindly let me know if I am missing something obvious here?

### Context information
Please always add the following information
- eXist-db version: 2.2 and 3.1.1 release versions
- Java version: Java8u121
- Operating system: Windows 10 - 64 bit
- no custom changes to config.

**Comment by wolfgangmm** [comment]
The following-sibling axis is for sure expected to work properly and covered by tests. There must be something specific to your case. At least a quick check on my installation did not reveal any issues. Could you provide more details?

**Comment by merenyics** [comment]
Thank you for the reply, I'll try to isolate the problem as much as I can, and will get back to you shortly. Maybe the problem has to do with the fact that the elements I referred to as 'b' and 'a' in my simplified example above are nested inside mixed elements and have text node siblings in all cases?

**Comment by joewiz** [comment]
A reproducible example would be great. Also, you mentioned an old post on exist-open - can you quote that here or provide a link?

**Comment by merenyics** [comment]
Admittedly, it's not very informative, but here is the link I was referring to:
[https://sourceforge.net/p/exist/mailman/message/31718021/](https://sourceforge.net/p/exist/mailman/message/31718021/)

At least, it seems to indicate that I am not the first one to stumble upon this kind of problem.

I am trying hard to reproduce the bug, but it seems rather elusive. All simple tests I have created so far failed to reproduce the issue I am facing in my real-life application. I can reproduce the bug with a very simple query, but only on my relatively large data set (which is the Comprehensive Dictionary of Hungarian). I am afraid the problem may have to do with the data, but I have no idea what it could be.

FYI, my query is quite simple:

```
xquery version "3.1";

let $dictcollection := collection('/db/apps/nytud/dictionary')
let $items := $dictcollection//gloss/following-sibling::hint

for $item in $items
return
    <res>{$item}</res>

```
This query run in eXide fails to return the thousands of 'hint' nodes that any of the workarounds manage to return correctly.

I haven't given up on reproducing the bug, maybe a small subset of my real data will suffice. I will get back to you once I have new information.

Thanks.

**Comment by merenyics** [comment]
OK, finally I have a very simple test case that fails on my computer consistently.

Create two documents in a collection:
**test0.xml** with the following content
```
<dic>
  <def>1<a>2</a>3<b>4</b>5</def>
  <def><a>6</a>7</def>
</dic>

```
and **test1.xml** with the following content
```
<dic>
  <def>1<a>2</a>3</def>
</dic>

```

run the query:
```
xquery version "3.1";

let $dictcollection := collection('/db/apps/nytud/queries/test... or wherever you put your test files')

return (
    count($dictcollection//a/following-sibling::*[name()='b']),
    count($dictcollection//a/following-sibling::b)
)

```
Observe the result: (1,0)

### Comments
- Removing the element `<a>` from **test1.xml** fixes the problem (result: (1,1))
- Adding an element `<b>` after `<a>` in **test1.xml** also fixes the problem (result: (2,2))

### Summary
So you need **two separate documents**, and one of them has to contain element `<a>` without an element `<b>` following it in order to reproduce the bug.

**Comment by joewiz** [comment]
Here's a self-contained test, with some unneeded details eliminated and with in-memory tests added showing that the problem is in the `on-disk2` test:

```xquery
xquery version "3.1";

let $in-mem-doc1 := 
    document {
        <root>
            <a/>
            <b/>
        </root> 
    }
let $in-mem-doc2 := 
    document {
        <root>
            <a/>
        </root>
    }
let $test-col := xmldb:create-collection('/db', 'test')
let $store-doc1 := xmldb:store($test-col, 'doc1.xml', $in-mem-doc1)
let $store-doc2 := xmldb:store($test-col, 'doc2.xml', $in-mem-doc2)
let $on-disk-doc1 := doc($store-doc1)
let $on-disk-doc2 := doc($store-doc2)
let $on-disk-tests := ($on-disk-doc1, $on-disk-doc2)/root
let $in-mem-tests := ($in-mem-doc1, $in-mem-doc2)/root
return 
    element results {
        element result { attribute n { "in-mem1" }, $in-mem-tests//a/following-sibling::*[name()='b'] },
        element result { attribute n { "in-mem2" }, $in-mem-tests//a/following-sibling::b },
        element result { attribute n { "on-disk1" }, $on-disk-tests//a/following-sibling::*[name()='b'] },
        element result { attribute n { "on-disk2" }, $on-disk-tests//a/following-sibling::b }
    }
```

The results:

```xml
<results>
    <result n="in-mem1">
        <b/>
    </result>
    <result n="in-mem2">
        <b/>
    </result>
    <result n="on-disk1">
        <b/>
    </result>
    <result n="on-disk2"/>
</results>
```

**Comment by merenyics** [comment]
That was really quick, great job! Thank you very much.

**Comment by joewiz** [comment]
Nicely reported!
