### ISSUE TITLE
Resource#createNewFile releases a lock it doesn't hold

### ISSUE THREAD

**Issue by adamretter** [eXist-db/exist#1413]
Document is retrieved without lock here: https://github.com/eXist-db/exist/blob/develop/src/org/exist/util/io/Resource.java#L659

Lock (which we have not acquired) is released here: https://github.com/eXist-db/exist/blob/develop/src/org/exist/util/io/Resource.java#L703

**Comment by dizzzz** [comment]
ouch....

**Comment by adamretter** [comment]
@dizzzz I am not sure any of the code in `org.exist.util.io` is actually really used anywhere. If not it is probably better to remove it...

**Comment by shabanovd** [comment]
It's in use.

**Comment by adamretter** [comment]
@shabanovd In eXist or in a 3rd party project?

**Comment by shabanovd** [comment]
3rd party projects

**Comment by shabanovd** [comment]
mean `org.exist.util.io.Resource` only

**Comment by adamretter** [comment]
@shabanovd Okay, just wondering if there is any value it staying in eXist or whether it is better to copy it to your 3rd party project? What do you think?

**Comment by shabanovd** [comment]
That is not single project, I did speak with different developers that use it in different projects.

**Comment by adamretter** [comment]
@shabanovd okay thanks
