### ISSUE TITLE
Windows10 issue with YAJSW

### ISSUE THREAD

**Issue by dizzzz** [eXist-db/exist#1417]
### What is the problem
On [exist-open](http://exist.markmail.org/search/windows+10+order:date-backward) reports have been made that eXist-db cannot be run as a service on windows 10

### What did you expect
eXist-db should also run on windows 10

### Describe how to reproduce or add a test
Install eXist-db on windows 10, install as service to be sure that the database is gracefully shutdown when windows is shutdown.

### Context information
Please always add the following information
- eXist-db : 3.1.1
- Java version : Java8u121
- Operating system : Windows 10
- 64 bit
- Any custom changes in e.g. conf.xml : none

### References
- All mails on [MarkMail.org](http://exist.markmail.org/search/windows+10+order:date-backward)

**Comment by dizzzz** [comment]
It might not be a YAJSW issue but an issue with that jna library;

please could you replace the files

```
./lib/core/jna/jna-4.2.2.jar
./lib/core/jna/jna-platform-4.2.2.jar
```

with the newest files found on https://github.com/java-native-access/jna#download  ?

- jna.jar
-  jna-platform.jar

Make a backup of the original files first (move outside the original location!), and give the the two downloaded files the same name as the originals ( *-4.2.2.jar )

**Comment by duncdrum** [comment]
@dizzzz where are we on this, good to close?

**Comment by adamretter** [comment]
We don't use YAJSW in eXist-db 5.0.0 anymore so I am going to close this. @dizzzz feel free to re-open if for some reason you need to.
