### ISSUE TITLE
XQJ SAX error retrieving elements with attributes containing quote

### ISSUE THREAD

**Issue by Torcsi** [eXist-db/exist#1420]
eXist version 2.2, 

#eXist build info 
project.version=2.2
project.built=20141120124006
scm.branch=master
scm.revision=5c5aadc

 java version  1.8.0_112-b15

OS: Windows 10

XQJ version 1.0.1

XML file created: /apps/test/quoted.xml
`<a b="&amp;#34;c"/>`

XQuery requested from eXide:

let $doc := doc('/apps/test/quoted.xml')
return $doc
Returned value, properly coloured but improperly coded:

> ... <a b="**"**c"/>

i.e. quote is not coded within the quoted text as &amp;quot; or &amp;#34;

Expected, instead, either 
```xml
<a b="&#34;c"/>
```
or
```xml
<a b="&quot;c"/>
```

The file accessed from WebDAV is proper.

The file retrieved through XMLDB collection.resource is also proper, the attributes are readable.

When a stored query is requested via XQJ downloaded from http://xqj.net/exist/

```java
	import javax.xml.xquery.*;

	 import org.w3c.dom.Node;

	 import javax.xml.namespace.QName;
	 import net.xqj.exist.ExistXQDataSource;

	public class XQJTest {

	public static void main(String[] args) {
		XQConnection conn = null;
		try {
			XQDataSource xqs = new ExistXQDataSource();
			xqs.setProperty("serverName", "localhost");
			xqs.setProperty("port", "8080");

			conn = xqs.getConnection();

			quoteTest(conn);
			conn.close();
		} catch (Exception e) {
			e.printStackTrace();
		} finally {
			try {
				if (conn != null)
					conn.close();
			} catch (Exception e) {
			}
		}
	}
	static void quoteTest(XQConnection conn) throws Exception {
		String sQuery = "let $doc := doc('/apps/test/quoted.xml')\n" +

				"return $doc";

		XQPreparedExpression xqpe = conn.prepareExpression(sQuery);

		XQResultSequence rs = xqpe.executeQuery();

		while (rs.next()) {
			Node n = rs.getNode();
			System.out.println(n.getLocalName());
		}
		rs.close();

	}
}
```

the following error received:

> [Fatal Error] :1:13: The reference to entity "quotc" must end with the ';' delimiter.
> javax.xml.xquery.XQException:
>   XQJTO013 - org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 13; The reference to entity "quotc" must end with the ';' delimiter.
>   Root Cause:
>   javax.xml.transform.TransformerException: org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 13; The reference to entity "quotc" must end with the ';' delimiter.
>   at com.arcanum.existdb.test.XQJTest.quoteTest(XQJTest.java:43)
>   at com.arcanum.existdb.test.XQJTest.main(XQJTest.java:21)
>   at org.apache.xalan.transformer.TransformerIdentityImpl.transform(TransformerIdentityImpl.java:502)
>   at com.arcanum.existdb.test.XQJTest.quoteTest(XQJTest.java:43)

No other way to retrieve the content is possible through XQJ

**Comment by dizzzz** [comment]
Notyet convinced it is an eXist-db issue or a XQJ issue;
- http://xqj.net/contact.jsp 
- http://xqj.net/issues/login_page.php 

we did not develop that code , nor do we have access to the sources....

**Comment by Torcsi** [comment]
Dear Dannes,
Thanks for prompt reply.
Since eXide also presents the data in this strange way and therefore it is not possible to cut and paste valid XML data, the issue may also apply to eXide, v. 2.2
(I could not check in 3.0, since there we found indexing issues.)

I will contact XQJ people.
Regards,
Attila

**Comment by dizzzz** [comment]
can you show (paste)  a screenshot of eXide showing the issue?
if you have an indexing issue in 3.1.x please file an issue in Github....

**Comment by dizzzz** [comment]
3.1.x / eXide returns `<a b="&#34;c"/>`
3.1.x / query via REST returns ``<a b="&amp;#34;c"/>``

**Comment by Torcsi** [comment]
[cid:image001.png@01D2B924.5DC7C4A0]
eXide version 2.1.3

Thanks for 3.1.x tests. Argument to update at us… though shall be hard to test the code > 10.000 lines of XQL.
A

**Comment by Torcsi** [comment]
The 2.2 rest interface result seems OK:
view-source:http://localhost:8080/exist/apps/test/quoted.xml

<a b="&#34;c"/>

**Comment by Torcsi** [comment]
XQJ bug, reported first in **2011**

**Comment by dizzzz** [comment]
please could you add a reference? (URL?)

**Comment by joewiz** [comment]
XQJ aside, I filed a PR for eXide that https://github.com/wolfgangmm/eXide/issues/161 fixes the issue with its results. @Torcsi Thanks for the report, and @dizzzz thanks for the helpful summary.

**Comment by Torcsi** [comment]
Our eXist servers contain sensitive data in intranet and we did not intend to provide a public eXist server even through secure logins and apache wrapper. I am sorry.
I believe the test case is so simple  that a single new installation of eXist is sufficient to reproduce it.

Thanks for all your valuable and prompt support.

**Comment by dizzzz** [comment]
You referred to a bug filed earlier. Please can you add a reference to that ?

**Comment by adamretter** [comment]
@Torcsi I stored the following XML document at `/db/quoted.xml`:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<a b="&#34;c"/>
```

I then retrieved it using the cURL and got:
```
$ curl http://localhost:8080/exist/rest/db/quoted.xml
<a b="&#34;c"/>
```

I then checked with your XQJ code, and indeed I received the same error that you did. However, I then did the same but captured the network traffic with Wireshark and that seemed to show that the XML sent from eXist-db was indeed valid:

```
POST /exist/rest/ HTTP/1.1
User-Agent: eXist XQJ
Content-Type: text/xml
Host: localhost:8080
Accept: text/html, image/gif, image/jpeg, *; q=.2, */*; q=.2
Connection: keep-alive
Content-Length: 179

<?xml version="1.0" ?><query xmlns="http://exist.sourceforge.net/NS/exist" enclose="yes" typed="yes" max="32767"><text>let $doc := doc('/db/quoted.xml')
return $doc</text></query>HTTP/1.1 200 OK
Date: Thu, 20 Apr 2017 20:32:58 GMT
Set-Cookie: JSESSIONID=a4d6qzdwb0fw1vjntwssxslne;Path=/exist
Expires: Thu, 01 Jan 1970 00:00:00 GMT
Last-Modified: Thu, 20 Apr 2017 20:31:02 GMT
Content-Type: application/xml; charset=UTF-8
Transfer-Encoding: chunked
Server: Jetty(9.3.9.v20160517)

113
<exist:result xmlns:exist="http://exist.sourceforge.net/NS/exist" exist:hits="1" exist:start="1" exist:count="1" exist:compilation-time="0" exist:execution-time="0">
    <exist:document exist:uri="/db/quoted.xml">
        <a b="&#34;c"/>
    </exist:document>
</exist:result>
0
```

So as the XML coming from eXist appears to be valid, I think the issue is likely in the xqj.net code, although I could be mistaken still. Perhaps Charles Foster (author of xqj.net) could help you?

**Comment by duncdrum** [comment]
@line-o duplicate of #291 ?
see #2375

**Comment by Torcsi** [comment]
We have solved with workarounds...
