### ISSUE TITLE
eXist 3.X lockup issues

### ISSUE THREAD

**Issue by jeffr22** [eXist-db/exist#1445]
While importing folders into eXist using OxygenXML (ver 19.0)  eXist would lockup completely. Job needed to be killed to proceed.  Example of the error is shown below. This behavior was identical on both eXist 3.1.1 and exist 3.2.0. The problem does not occur with eXist 2.2.

OS: Ubuntu 16.04
jeff@mygui:~/Temp$ java -version
openjdk version "1.8.0_131"
OpenJDK Runtime Environment (build 1.8.0_131-8u131-b11-0ubuntu1.16.04.2-b11)
OpenJDK 64-Bit Server VM (build 25.131-b11, mixed mode)

Log file with more detail is enclosed - J

[exist3.txt](https://github.com/eXist-db/exist/files/1008041/exist3.txt)
-------------------------------------------------------------------
Threads currently waiting for a lock:
=====================================
Thread: qtp220689785-29
           Lock type: COLLECTION
           Lock mode: READ
             Lock id: /db/lib
             Held by: [qtp220689785-21]
             Held by: [qtp220689785-21]
             Held by: [qtp220689785-21]
    Waiting for read: []
   Waiting for write: []

**Comment by dizzzz** [comment]
any idea what interface is used by OxygenXML ? "importing folders into eXist using OxygenXML" is a bit vague....

**Comment by dizzzz** [comment]
Hmmm are you sure you sent the LOG file (exist.log) ; this looks more like the console, which does not give any information on what is being done under the hood. In addition: all is done in about just one minute? can you provide more details on what we are looking at?

**Comment by jeffr22** [comment]
Dannes
Since posting the original issue, I installed eXist 3.2 on Windows, ran
the same experiment and got the same result I observed on Ubuntu. Work
internally reverted to eXist 2.2 however as eXist is important to us, so I
will reinstall 3.2 and get the log file.  I will also drop a note to the
OxygenXML folks and if possible get some notes on the interface they use,
however I would point out that just using the REST interface in our
application resulted in corruption of the database. This is code that has
run on eXist 1.X and exist 2.X for more than 5 years without issue  so I
doubt that Oxygen is playing any role here.
Will post that log file within the next couple of days - J

**Comment by dizzzz** [comment]
Hi,
thnx for the followup with Oxygen! 

Two items:
- I am a bit concerned though that you state there is a scenario that the REST corrupts the database. A lot of effort is done in testing and coding to avoid corruptions, and in 3.x many measures are taken to  reduce risks e.g. by extensively using Java's autoclosing features.  When possible I'd like to work with you to understand the corruption scenario (@adam and @wolfgangmm would be probably interested too).
- Deadlock are very scarce but when they happen it is very annoying; Maybe (...) it is easy to reproduce it via Oxygen, as you report. I know that @adamretter works on a revised locking strategy but that is not ready yet for production (nor did I review it yet). If we can reproduce the Lock, a fix might be rather easy to make.

I hope you can provide some more details so we can isolate issue (if any :-) )

cheers

Dannes

**Comment by jeffr22** [comment]
Dannes
I have run a number of tests to better pinpoint the issue here:
1)	I reinstalled exist3.2 again and ran all tests from either the exist
web console or the java client to eliminate any possible 3rd party issues
from OxygenXML.
2)	If I restore a backup created using the java client on the exist2.2
database then it fails every time when being restored to the new exist3.2
deployment. It fails in the restoration of some reasonably large Xquery
files, similar sized XML files do not cause problems.
3)	I ran some further experiments but the only way to consistently get the
lockup is to restore this backup (or others taken at earlier times of the
same database).
If you are interested in looking to repeat this experiment yourself I will
send you the backup given that you can assure me that the information on
their will remain confidential.
Best - J

**Comment by adamretter** [comment]
My Locking and Cache Improvements work likely solves this

**Comment by jeffr22** [comment]
Adam,
I installed eXist 4.0.0 and ran some initial tests. Certainly a big improvement over 3.X – I never was able to get that to work successfully with the applications that we run on the DB. We have continued to use eXist 2.2 for many years now and prior to that 1.4 and 1.2.
The issue with exist 3.X was an inability to import our XQ libs, which are between 500 and 3000 lines of code each. With 4.0 I still can’t import them using the exist webGui and the Collections utility. Every library returns a server error. However using OxygenXML for the import instead proved successful. I was also able to run a few test queries (which involve a lot of processing) and they produced the correct results. 
So initial results are promising, I will run more extensive test and provide a more detailed response in a week or twos time.
Regards - J

Sent from Mail for Windows 10

**Comment by duncdrum** [comment]
@Jeffr22 with more improvements in these core areas could confirm that you are still experiencing these problems with the latest RC of exist-db v5? Also what version of oxygen are you using, and how to you set-up the initial connection to exist?
