### ISSUE TITLE
Setting "java.io.File" content to a resource locks file

### ISSUE THREAD

**Issue by raducoravu** [eXist-db/exist#1446]
Let's say I'm using the API:

       `org.xmldb.api.base.Collection.createResource(String, String)`

to create a resource and then use the method:

      `org.xmldb.api.base.Resource.setContent(Object)`

to set a `java.io.File` object to the Resource.
After calling:

          `org.xmldb.api.base.Collection.storeResource(Resource)`

the file remains locked on disk, for example it cannot be deleted anymore on Windows. Possibly this happens because you are not closing the FileInputStream which you are probably using internally to read the file contents.

**Comment by dizzzz** [comment]
Yes these kind of issues frequently happen on windows, not only in eXist-db; closing a File (stream) does not alway 'unlock' such a file. We might have overlooked one or two cases, from what I see is that BinaryResources are always closed correctly, for XML resources it might be a bit different.

As you did not fill in the template: please provide
- exist version
- exact operating system
- java version
- exact use case (do you have copy-paste-able code?)

**Comment by raducoravu** [comment]
Java version: 1.8.0_121
Exist version: 3.0
OS: Windows 10 Pro

The code is quite mingled with ours, it would probably look like this:

      public void createResource(File file) throws DBException {
         org.xmldb.api.base.Collection existCollection = .existCollection....
         XmldbURI filenameUri filenameUri = URIUtils.encodeXmldbUriFor(file.getName());
  
          Resource document = existCollection.createResource(filenameUri.toString(), MimeType.BINARY_TYPE.getXMLDBType());
          ((EXistResource) document).setMimeType(MimeType.BINARY_TYPE.getName());
          document.setContent(file);
          existCollection.storeResource(document);
      }

As a workaround I created an InputSource containing a file input stream, used "document.setContent" to set the input source and then closed the input stream in our own code.

**Comment by dizzzz** [comment]
Probably... one needs to call `((EXistResource) document).freeResources()` at the moment the document can be released. @wolfgangmm ?

**Comment by adamretter** [comment]
@raducoravu Are you using a`LocalCollection` or a `RemoteCollection`?

**Comment by adamretter** [comment]
@raducoravu Assuming a `RemoteCollection` it seems that I may have spotted your issue in the past - https://github.com/eXist-db/exist/blob/develop/src/org/exist/xmldb/RemoteCollection.java#L564

Are you able to submit a PR?

**Comment by raducoravu** [comment]
I'm basically importing the File content to a remote collection.
Indeed that particular method should close the input streams that it has opened itself (that fileinputstream) and not close the ones that it receives from other input sources.
I'm not sure that I have the time to check out the entire Exist code, compile, make changes, test changes and submit a pull request. Fortunately I found a workaround on my side by opening there the FileInputStream and then closing it in my code after the content was imported.

**Comment by adamretter** [comment]
@raducoravu This was fixed by 73707ff

**Comment by raducoravu** [comment]
👍
