### ISSUE TITLE
Packages with semver-min=3.3.0 fails to install on 3.3.0-SNAPSHOT

### ISSUE THREAD

**Issue by joewiz** [eXist-db/exist#1455]
### What is the problem

Installing a .xar package built from https://github.com/wolfgangmm/eXide/tree/native-adaptive-serialization fails on eXist 3.3.0-SNAPSHOT, even though its `expath-pkg.xml` file states that it requires 3.3.0.

### What did you expect

I expected a package whose eXist dependency of `semver-min=3.3.0` would install on a snapshot build of 3.3.0. For example, this package should install without complaint on the current 3.3.0-SNAPSHOT https://github.com/wolfgangmm/eXide/blob/native-adaptive-serialization/expath-pkg.xml.tmpl#L5.

### Describe how to reproduce or add a test

Clone https://github.com/wolfgangmm/eXide/tree/native-adaptive-serialization, run `ant` to build the package, and install the resulting .xar file via Dashboard > Package Manager > Upload. It will return the following error:

> Package requires eXistdb version > 3.3.0. Installed version is 3.3.0-SNAPSHOT

exist.log reports:

```text
2017-06-09 11:11:01,843 [qtp2068499906-100] ERROR (Deploy.java [installAndDeployFromDb]:215) - Package requires eXistdb version > 3.3.0. Installed version is 3.3.0-SNAPSHOT 
org.expath.pkg.repo.PackageException: Package requires eXistdb version > 3.3.0. Installed version is 3.3.0-SNAPSHOT
        at org.exist.repo.Deployment.checkProcessorVersion(Deployment.java:293) ~[exist.jar:3.3.0-SNAPSHOT]
        at org.exist.repo.Deployment.installAndDeploy(Deployment.java:217) ~[exist.jar:3.3.0-SNAPSHOT]
        at org.exist.repo.Deployment.installAndDeploy(Deployment.java:163) ~[exist.jar:3.3.0-SNAPSHOT]
        at org.exist.xquery.modules.expathrepo.Deploy.installAndDeployFromDb(Deploy.java:213) [exist-modules.jar:3.3.0-SNAPSHOT]
        at org.exist.xquery.modules.expathrepo.Deploy.eval(Deploy.java:169) [exist-modules.jar:3.3.0-SNAPSHOT]
        at org.exist.xquery.BasicFunction.eval(BasicFunction.java:74) [exist.jar:3.3.0-SNAPSHOT]
        at org.exist.xquery.InternalFunctionCall.eval(InternalFunctionCall.java:41) [exist.jar:3.3.0-SNAPSHOT]
        at org.exist.xquery.LetExpr.eval(LetExpr.java:99) 
```

### Context information

- eXist-db version: 3.3.0-DEVELOP a059dec22
- Java version: 8u121
- Operating system: macOS 10.12.5
- 64 bit
- Any custom changes in e.g. conf.xml: none

**Comment by joewiz** [comment]
@adamretter Could you confirm my understanding of the semver policy? In principle, we should be able to install a package that requires 3.3.0 on 3.3.0-SNAPSHOT, right?

**Comment by joewiz** [comment]
Does anyone have any ideas or suggestions here? It would be great to be able to merge https://github.com/wolfgangmm/eXide/pull/168 before the release of 3.3.0, since 3.3.0 enables a feature the PR depends on. The PR updates eXide's package to declare semver-min="3.3.0", but due to this bug, a 3.3.0-DEVELOP system refuses to install the package.

A workaround to allow this eXide PR to be included with the 3.3.0 release would be to change eXide's semver-min value to 2.3.0, since such a version was never released. I'll do that in a few days if we don't have this issue sorted out.

**Comment by adamretter** [comment]
@joewiz I need to give this some thought, however `3.3.0` > `3.3.0-SNAPSHOT`. Let me get back to you...

**Comment by joewiz** [comment]
@adamretter Oh, I didn't realize that `3.3.0` > `3.3.0-SNAPSHOT` - but, of course, this makes sense. Changing the semver-min to `3.3.0-SNAPSHOT` in eXide's expath-pkg.xml file does allow it to install on 3.3.0-SNAPSHOT. So I think I'll update my PR to use the `-SNAPSHOT` variant for now, since that's accurate and would only lead to problems for people with older editions of `3.3.0-SNAPSHOT` before adaptive serialization was added. Thanks! I'm okay with closing this, as you've effectively solved the problem, but is there more you wanted to mull over?

**Comment by joewiz** [comment]
While it's still a work in progress, I've got what I think is a pretty robust semver checker: https://gist.github.com/joewiz/b349e2853a17bf817e5d0013d01fa9f9. 

It doesn't yet apply eXist-specific semver rules (there are a couple of such eXist-specific rules specified in https://github.com/eXist-db/exist/blob/develop/exist-versioning-release.md, namely the constraint about valid pre-release labels and build format/precedence), but I need to see which of these are really significant for the purposes of determining compatibility of features.

Thinking over the original issue here, I think that developers of apps like eXide that might have eXist-version-specific needs should probably just use `-SNAPSHOT` in their app's develop branch until a release is out. This would allow them to install their app on the development version of eXist. But since `-SNAPSHOT` could refer to any point in a the development cycle of a version before its release, app developers should probably avoid using `-SNAPSHOT` in a full release of their own app. As a result, here are my provisional takeaways:

- app developers should only cut a release of their app when the version of eXist with the required version is out.
- if app developers are eager to cut a release, they should request a release of eXist, rather than releasing their app with `-SNAPSHOT` in their app's requirements.

(My gist linked here could be used by apps that might want to probe the version of eXist, and based on this enable or disable certain advanced features that require a particular version. For example, we could release a version of eXide that only presents the adaptive serialization to users with 3.3.0+, while still allowing installation on earlier systems. Not that this would be straightforward to implement, but it would open this approach up.)

**Comment by joewiz** [comment]
Closing as invalid - since @adamretter explained how the issue I encountered was actually the expected/designed behavior of the semver system.
