### ISSUE TITLE
xmldb:store fails on remote binary resources

### ISSUE THREAD

**Issue by joewiz** [eXist-db/exist#1456]
### What is the problem

The following query worked in eXist 2.2 but fails on eXist 3.x:

```xquery
xquery version "3.0";

xmldb:store(
    '/db', 
    'image.jpg', 
    xs:anyURI('https://www.google.com/images/branding/googlelogo/1x/googlelogo_color_272x92dp.png'), 
    'image/png'
)
```

The error in eXide in eXist 3.3.0-DEVELOP:

> exerr:ERROR IOException while reading from URL: https://www.google.com/images/branding/googlelogo/1x/googlelogo_color_272x92dp.png [at line 3, column 1]

In my application (where I first saw this), my try-catch block's `$err:description` reports this before the IOException:

> java:java.nio.file.FileAlreadyExistsException module: (114,35) /Users/joe/workspace/exist/tools/jetty/tmp/existDBS396998373878243953.xml.

But no such file exists in that location.

It looks like the last change to xmldb:store was @adamretter's commit of Oct 15, 2016 that changed src/org/exist/xquery/functions/xmldb/XMLDBStore.java (starting around ~line 286): https://github.com/eXist-db/exist/commit/c0b66cecad66cd6f00c91d12301914f65e42cf39#diff-1ae2fca2d57a1afd1fa116bb2548908e.

### What did you expect

I expected xmldb:store to allow remote binary resources to be stored, as stated in the function documentation. (See http://exist-db.org/exist/apps/fundocs/view.html?uri=http://exist-db.org/xquery/xmldb#store.3.)

### Describe how to reproduce or add a test

See the query above.

### Context information

- eXist-db version: 3.3.0-DEVELOP a059dec22 (for 2.2, I tested on exist-db.org's eXide)
- Java version: 8u121
- Operating system: macOS 10.12.5
- 64 bit
- Any custom changes in e.g. conf.xml: none

**Comment by joewiz** [comment]
This is still an issue in the current develop branch.

@adamretter I'm curious to know if you think this regression is caused by https://github.com/eXist-db/exist/commit/c0b66cecad66cd6f00c91d12301914f65e42cf39#diff-1ae2fca2d57a1afd1fa116bb2548908e, as I suggested in the original issue? The function docs of `xmldb:store` say that the 3rd parameter (`$contents`) can be a URI:

> If `$contents` is of type `xs:anyURI`, the resource is loaded from that URI. 

Here is a query that produces a fuller report of the error in the original issue. 

```xquery
xquery version "3.1";

try { 
    xmldb:store(
        '/db', 
        'image.jpg', 
        xs:anyURI('https://www.google.com/images/branding/googlelogo/1x/googlelogo_color_272x92dp.png'), 
        'image/png'
    )   
} catch * { 
    map {
        "code": $err:code,
        "description": $err:description,
        "value": $err:value,
        "module": $err:module,
        "line-number": $err:line-number,
        "column-number": $err:column-number,
        "additional": $err:additional
    }
}
```

The results:

```xquery
map {
    "column-number": 5,
    "line-number": 4,
    "additional": (),
    "module": (),
    "code": Q{http://exist.sourceforge.net/NS/exist/java-binding}java.nio.file.FileAlreadyExistsException,
    "value": (),
    "description": "/var/folders/ky/gdx8y19x3gj7xxjm1zr3wr_r0000gn/T/existDBS5664432193589533316.xml. IOException while reading from URL: https://www.google.com/images/branding/googlelogo/1x/googlelogo_color_272x92dp.png"
}
```

Incidentally, a workaround which avoids relying on xmldb:store to fetch the remote resource by explicitly calling the native HTTP client doesn't work either:

```xquery
xquery version "3.1";

xmldb:store(
    '/db', 
    'image.png',
    util:base64-decode(httpclient:get(xs:anyURI("https://www.google.com/images/branding/googlelogo/1x/googlelogo_color_272x92dp.png"), false(), ())//httpclient:body),
    'image/png'
)
```

(Well, a file *is* stored, but it's a corrupted png file.)

It seems that only the EXPath HTTP Client is able to successfully retrieve remote resources:

```xquery
xquery version "3.1";

xmldb:store(
    '/db', 
    'image.png',
    hc:send-request(<hc:request href="https://www.google.com/images/branding/googlelogo/1x/googlelogo_color_272x92dp.png" method="get"/>)[2],
    'image/png'
)
```

So the original problem with `xmldb:store` may be part of a larger issue involving the fetching of remote resources - in which the EXPath HTTP Client is not affected but the native `httpclient` is alongside `xmldb:store`.

**Comment by JoernT** [comment]
same is true for store-as-binary:

The following function fails silently without any error in the logs:

 ```
declare function local:expath-get($url) {
    let $request := <expath:request method="GET" href="{$url}" timeout="120" override-media-type="application/binary">
                    </expath:request>
    let $debug := util:log("info", "start storing 10GB with eXistdb")
    return 
        try {
            let $store := xmldb:store-as-binary("/db/", "10GB-http.bin", expath:send-request($request)[2])
            let $debug := util:log("info","finished storing 10GB")

            return
                $store
        } catch * {
                <error code="{$err:code}">
                    <description>{$err:description}</description>
                </error>
        }
};

let $url := "https://speed.hetzner.de/10GB.bin"
 let $download := local:expath-get($url) 
 
(:let $download := local:http-get($url) :)
return
    $download 

```

**Comment by windauer** [comment]
I tested the above query from Joern as well. It works fine if the eXist-db has more RAM than the size of the binary to download. But the query fails on any eXistdb with less RAM than the filesize (tested from 3.4.x till 4.2.0-SNAPSHOT)

**Comment by windauer** [comment]
Forgot to mention: There are no error messages / warning in the logs, but in eXide I could see a "Size exceeds Integer.MAX_VALUE" error.

**Comment by dizzzz** [comment]
what happens if you switch to another binary manager?

https://github.com/eXist-db/exist/blob/develop/conf.xml.tmpl#L388

There is a chance that the expath client - or the library used under the hood- buffers all data in memory. I had a similar issue some time ago with the httpcomponents library,,,, a ContentTooLongException or so.

**Comment by windauer** [comment]
@dizzzz we use org.exist.util.io.FileFilterInputStreamCache as binary manager. From the description of the MemoryMappedFileFilterInputStreamCache and MemoryFilterInputStreamCache it sounds like these can only work worse. But I will give it a try.

**Comment by windauer** [comment]
I switched to the MemoryMappedFileFilterInputStreamCache and now I get this error message: 

`
<error code="err:XPTY0004"> <description>It is a type error if, during the static analysis phase, an expression is found to have a static type that is not appropriate for the context in which the expression occurs, or during the dynamic evaluation phase, the dynamic type of a value does not match a required type as specified by the matching rules in 2.5.4 SequenceType Matching. checking function parameter 3 in call xmldb:store-as-binary("/db/", "10GB-http.bin", hc:send-request($request)[2]): Unable to add binary value to result:Read timed out</description> </error>`

**Comment by windauer** [comment]
After a small change in the XQuery (storing the response in a variable before storing it) I'm back at the  Integer.MAX_VALUE error (still with the MemoryMappedFileFilterInputStreamCache as binary manager). My stomach is confused, feels like an issue in the expath http client but switching to the eXist-db internal httpclient we got errors as well. 
 
```
<error code="java:java.lang.IllegalArgumentException"> 
   <description>Size exceeds Integer.MAX_VALUE</description> 
</error>
```


The complete XQuery: 


```
xquery version "3.1";
import module namespace expath="http://expath.org/ns/http-client";

declare function local:expath-get($url) {
   let $request := <expath:request method="GET" href="{$url}" timeout="120" override-media-type="application/binary">
                   </expath:request>
   let $debug := util:log("info", "start storing 10GB with eXistdb")
   return 
       try {
           let $response := expath:send-request($request)[2]
           let $debug := util:log("info", "downloaded 10GB")
           let $store := xmldb:store-as-binary("/db/", "10GB-http.bin", $response)
           let $debug := util:log("info","finished storing 10GB")

           return
               $store
       } catch * {
               <error code="{$err:code}">
                   <description>{$err:description}</description>
               </error>
       }
};
let $url := "https://speed.hetzner.de/10GB.bin"
let $download := local:expath-get($url) 
return
   $download
```

**Comment by dizzzz** [comment]
nothing in the logs? even when you set it to debug mode?

**Comment by dizzzz** [comment]
As I said, I remember that the HTTP client jars has a limit on the size to can download, suprisinlgy. but there are some hints.... via [DDG](http://duckduckgo.com) http://mail-archives.us.apache.org/mod_mbox/spark-user/201502.mbox/%3c1423851878602-21648.post@n3.nabble.com%3e

**Comment by dizzzz** [comment]
and here: https://stackoverflow.com/questions/7536233/java-possible-filechannel-map-bug ; looks in the context of java's NIO....

**Comment by windauer** [comment]
Please find me debug log for the last run attached. I switched the Root level in log4j2.xml to "debug" but could not see anything that would help me but perhaps you find something. @JoernT already had a first look at the Java code itself but was rather clueless as well. 
   
[exist-2018-05-08-18-48.log](https://github.com/eXist-db/exist/files/1985054/exist-2018-05-08-18-48.log)

**Comment by windauer** [comment]
Thanks @dizzzz for the hints.. I think your hint about FileChannels might exactly be the issue while I don't think it depends on the httpclient. 

I just tested what happens if you upload 4GB via eXide > Manage > Upload into your DB and surprise, surprise.. I get the same error but this time even a stack trace which I attach to this comment. // cc @JoernT, @wolfgangmm 

* [exist-2018-05-09-11-27.log](https://github.com/eXist-db/exist/files/1987185/exist-2018-05-09-11-27.log)

**Comment by brobertson** [comment]
I am trying to upload packages comprising images, and these packages are often over 2GB in size. They fail due to this same issue. The Stackoverflow discussion below indicates that FileChannel.map take no more than Integer.MAX_VALUE of data, and that  "if you need greater maps than 2GB, just use more than a single ByteBuffer"

https://stackoverflow.com/questions/8076472/why-does-filechannel-map-take-up-to-integer-max-value-of-data

**Comment by alanpaxton** [comment]
Revisiting. This still fails per the original report, on

[eXist Version : 6.1.0-SNAPSHOT]
[Git commit : 12ae7647d2ec54ae37090c1c8a81af892e6e90ba]
