### ISSUE TITLE
Support request: Broken dashboard with traffic-encrypting proxy

### ISSUE THREAD

**Issue by funkyfuture** [eXist-db/exist#1458]
### What is the problem

We are routing http-traffic to our eXist-db instances through nginx as a proxy that also handles traffic encryption, on exist's contributed jetty all ssl-related configuration is deactivated.

While the dashboard does work when requested via `http`, but yields this document when requested via `https`:

```xml
<exception>
  <path>/db/apps/dashboard/modules/view.xql</path>
  <message>exerr:ERROR XPTY0004: The actual cardinality for parameter 1 does not match the cardinality declared in the function's signature: templates:apply($content as node()+, $resolver as function, $model as map?) item()*. Expected cardinality: one or more, got 0. [at line 38, column 22, source: /db/apps/dashboard/modules/view.xql]
In function:
	templates:apply(node()+, function, map?) [38:5:/db/apps/dashboard/modules/templates.xql]
  </message>
</exception>
```

This applies with Chromium 58.0.3029.110 as well as Firefox 54.0 on Ubuntu 16.04. curl does fine, so it may be related to some functionality that is implemented with Javascript .

The error is not evoked by our own apps, they work as expected.

### Context information
Please always add the following information
- eXist-db 3.2 /  691bcd6
- openjdk 8u131
- Ubuntu 16.04
- amd64
- nginx 1.10

**Comment by adamretter** [comment]
@funkyfuture Please can you move this issue to https://github.com/eXist-db/dashboard

**Comment by funkyfuture** [comment]
moved to https://github.com/eXist-db/dashboard/issues/56
