### ISSUE TITLE
Element constructor creates document node. It should not.

### ISSUE THREAD

**Issue by mjhallman** [eXist-db/exist#1463]
```xquery
let $x := element {"root"}  {}

return $x/root() instance of document-node()
```
This returns `true` in eXist-db which is incorrect. The result of `$x/root()` should be an `element()`.
I have tested this on Saxon and BaseX which both correctly return `false`.

**Comment by dizzzz** [comment]
please fill in the issue-template. It makes sure you'll add all required information, info we need to understand the exact context. thnx

**Comment by adamretter** [comment]
@dizzzz I helped @mjhallman report these. Everything that is needed to reproduce is there.

**Comment by adamretter** [comment]
It's the `HEAD` of the `develop` branch.

**Comment by adamretter** [comment]
A little investigation has shown that the problem is actually `fn:root`.  In-memory elements in eXist-db always have an Owner Document, which they should not when directly constructed with `element x {}`, and so `fn:root` always returns the `document-node()` by mistake.

See the examples here: https://www.w3.org/TR/xpath-functions/#func-root-examples

The following XQUnits show the issue:

```xquery
declare
    %test:assertEquals("false")
function root:in-mem-element() {
    fn:root(<anything/>) instance of document-node()
};
```
The above should return `false`, but eXist-db returns `true`.

```xquery
declare
    %test:assertEquals("true")
function root:in-mem-document() {
    fn:root(document { <anything/> }) instance of document-node()
};
```

The above should (and does in eXist-db) return `true`.

**Comment by adamretter** [comment]
@wolfgangmm I would welcome a discussion about this. From my perspective it requires quite some re-engineering of the in-memory DOM model, but maybe you have some clever ideas to fix this up?

**Comment by wolfgangmm** [comment]
@adamretter we know where the in-memory DOM is created by a constructor, so could just set a flag.

**Comment by duncdrum** [comment]
Yes someone working on tei-publisher just stumbled on `fn:root()` 
```
xquery version "3.0";
declare function local:node-kind
  ( $nodes as node()* )  as xs:string* {

 for $node in $nodes
 return
 if ($node instance of element()) then 'element'
 else if ($node instance of attribute()) then 'attribute'
 else if ($node instance of text()) then 'text'
 else if ($node instance of document-node()) then 'document-node'
 else if ($node instance of comment()) then 'comment'
 else if ($node instance of processing-instruction())
         then 'processing-instruction'
 else 'unknown'
 } ;

let $data :=
<root xml:base="bl">
    <dummy/>
</root>

return
    local:node-kind(root($data))
```

exist 4.1.0 returns: `document-node`
Saxon 9.8.0.8 returns: `element`
Zorba 2.9: returns: `element`

I also think this is wrong, `fn:doc()` should give you access to document-nodes, root should not return  document-node here.
