### ISSUE TITLE
Missing elements when using descendant-or-self

### ISSUE THREAD

**Issue by mjhallman** [eXist-db/exist#1464]
```xquery
let $block :=
<a>
    <z>
        <b></b>
    </z>
    <c>
        <b></b>
    </c>
</a>

return $block//*[name(.) eq 'b'][1]
```

This only returns 1 `<b>` element in eXist-db. It should return both `<b>` elements.
I have tested this in BaseX and Saxon and they are correct, whereas eXist-db is not.

**Comment by dizzzz** [comment]
please fill in the issue-template. It makes sure you'll add all required information, info we need to understand the exact context. thnx

**Comment by adamretter** [comment]
@dizzzz I helped @mjhallman report these. Everything that is needed to reproduce is there.

**Comment by dizzzz** [comment]
one essential thing for this issue: a hint missing regarding the eXist-db version.

**Comment by adamretter** [comment]
@dizzzz Ah okay, my bad. It's the `HEAD` of the `develop` branch.

**Comment by duncdrum** [comment]
duplicate of  #798
