### ISSUE TITLE
Error in adaptive serialization of fn:concat

### ISSUE THREAD

**Issue by joewiz** [eXist-db/exist#1467]
### What is the problem

eXist should reject `fn:concat#1` with error XPST0017 (https://www.w3.org/TR/xpath-30/#ERRXPST0017), since the concat function requires an arity of 2 or more. Instead, it serializes `fn:concat#1` as `fn:concat#-1`. (`fn:concat#2` correctly returns no error.)

### What did you expect

I expected eXist to reject `fn:concat#1` with error XPST0017 (https://www.w3.org/TR/xpath-30/#ERRXPST0017). 

### Describe how to reproduce or add a test

```xquery
xquery version "3.1";

declare namespace output="http://www.w3.org/2010/xslt-xquery-serialization";
declare option output:method "adaptive";

fn:concat#1
```

eXist returns the following result without raising an error:

> fn:concat#-1

BaseX returns the following error:

> [XPST0017] fn:concat(atom1,atom2[,...]): 1 argument supplied.

### Context information

- eXist-db version: 3.3.0-SNAPSHOT rev. 49624f2e7
- Java version: Java 8u131
- Operating system: macOS 10.12.5
- 64 bit
- Any custom changes in e.g. conf.xml: None

**Comment by duncdrum** [comment]
@joewiz the PR was merged can you re-confirm this issue, and check for missing tests, thx.

**Comment by joewiz** [comment]
The PR I think you're referencing, #1448, didn't actually address this issue; I only noticed this problem after that PR was merged (see https://github.com/eXist-db/exist/pull/1448#issuecomment-307592610). The problem is still evident in `develop-4.x.x`.

**Comment by joewiz** [comment]
Yes, I'll work on adding a test.

**Comment by joewiz** [comment]
This minor problem still affects eXist 5.0.0.
