### ISSUE TITLE
Problem with Ant task xdb:store

### ISSUE THREAD

**Issue by eriksiegel** [eXist-db/exist#1471]
In an eXist Ant build task I'm doing an `xdb:store`. Whatever I specify (I tried several variations of the options avaliable), this results in an error:

```
C:\Data\Erik\xmldev\Benjamins\awk-test\deploy\build.xml:76: java.nio.file.InvalidPathException: Illegal char <:> at index 2: /C:/xdata2/eXist-32/exist-eXist-3.2.0/conf.xml
	at sun.nio.fs.WindowsPathParser.normalize(Unknown Source)
	... (many more)
```

Since I did *not* specify or mention this `conf.xml` file,  this suggests to me that somewhere internally the code references `conf.xml` but has the URI wrong?

I am running the develop version of eXist (`c018bd4`) on Windows 10 (64), Java 1.8.0_131, no setup changes, a fresh installation, just checked out and did a build.

Reproduce: Try running the attached Ant build script (please change the configuration settings at the top first to your local settings).

[build.zip](https://github.com/eXist-db/exist/files/1107872/build.zip)

**Comment by adamretter** [comment]
@eriksiegel Okay I can reproduce this on a Windows 10 install. I will prepare a fix for eXist-db 3.6.0. We now have a Windows CI (AppVeyor) which should help us guard against this in future.
