### ISSUE TITLE
Error to start Java Client 3.3.0 from Dashboard/web browser 

### ISSUE THREAD

**Issue by andray71** [eXist-db/exist#1475]
Thank you for reporting your issue!

To be able to better understand you problem or suggestion, please add as much information as possible to this ticket. When there is no or just little information, it will be too difficult to work on it (and hence we will not be able to solve it)

Please fill in the following sections:

### What is the problem
> Trying to Open/Start Java Admin Client from Dashboard
Exception:
```
JNLPException[category: Security Error : Exception: null : LaunchDesc: 
<jnlp spec="7.0" codebase="http://localhost:8080/exist/webstart/" href="exist.jnlp" version="3.3.0">
  <information>
    <title>eXist XML-DB client</title>
    <vendor>exist-db.org</vendor>
    <homepage href="http://exist-db.org"/>
    <description>Integrated command-line and gui client, entirely based on the XML:DB API and provides commands for most database related tasks, like creating and removing collections, user management, batch-loading XML data or querying.</description>
    <description kind="short">eXist XML-DB client</description>
    <description kind="tooltip">eXist XML-DB client</description>
    <icon href="jnlp_logo.jpg"/>
    <icon href="jnlp_icon_128x128.gif" width="128" height="128"/>
    <icon href="jnlp_icon_64x64.gif" width="64" height="64"/>
    <icon href="jnlp_icon_32x32.gif" width="32" height="32"/>
  </information>
  <security>
    <all-permissions/>
  </security>
  <resources>
    <property name="jnlp.packEnabled" value="true"/>
    <property name="java.util.logging.manager" value="org.apache.logging.log4j.jul.LogManager"/>
    <java version="1.8+"/>
    <jar href="log4j-jul-2.8.2.jar" size="26272"/>
    <jar href="commons-codec-1.10.jar" size="307249"/>
    <jar href="cglib-nodep-3.1.jar" size="358483"/>
    <jar href="jcip-annotations-1.0.jar" size="4005"/>
    <jar href="pkg-java-fork.jar" size="87631"/>
    <jar href="commons-logging-1.2.jar" size="66579"/>
    <jar href="jargo-0.4.2-SNAPSHOT-7fa1d04.jar" size="200065"/>
    <jar href="xmlrpc-client-3.1.3.jar" size="65537"/>
    <jar href="rsyntaxtextarea-2.6.1.jar" size="1201107"/>
    <jar href="slf4j-api-1.7.21.jar" size="46264"/>
    <jar href="exist.jar" size="4441960"/>
    <jar href="quartz-2.2.3.jar" size="700323"/>
    <jar href="clj-ds-0.0.4.jar" size="290932"/>
    <jar href="jackson-core-2.7.4.jar" size="262996"/>
    <jar href="log4j-core-2.8.2.jar" size="1498139"/>
    <jar href="commons-pool-1.6.jar" size="118732"/>
    <jar href="xmlrpc-common-3.1.3.jar" size="122505"/>
    <jar href="jline-0.9.94.jar" size="93084"/>
    <jar href="j8fu-1.4.1.jar" size="54814"/>
    <jar href="log4j-api-2.8.2.jar" size="243001"/>
    <jar href="commons-io-2.5.jar" size="221540"/>
    <jar href="gnu-crypto-2.0.1.jar" size="644209"/>
    <jar href="ws-commons-util-1.0.2.jar" size="38575"/>
    <jar href="commons-collections-3.2.2.jar" size="630602"/>
    <jar href="log4j-slf4j-impl-2.8.2.jar" size="26094"/>
    <jar href="xmldb.jar" size="12768"/>
    <jar href="antlr-2.7.7.jar" size="464341"/>
    <jar href="jta-1.1.jar" size="16277"/>
  </resources>
  <application-desc main-class="org.exist.client.InteractiveClient">
    <argument>-ouri=xmldb:exist://localhost:8080/exist/xmlrpc</argument>
    <argument>--no-embedded-mode</argument>
  </application-desc>
</jnlp> ]
	at com.sun.javaws.security.JNLPSignedResourcesHelper.checkSignedResourcesHelper(Unknown Source)
	at com.sun.javaws.security.JNLPSignedResourcesHelper.checkSignedResources(Unknown Source)
	at com.sun.javaws.Launcher.prepareResources(Unknown Source)
	at com.sun.javaws.Launcher.prepareAllResources(Unknown Source)
	at com.sun.javaws.Launcher.prepareToLaunch(Unknown Source)
	at com.sun.javaws.Launcher.prepareToLaunch(Unknown Source)
	at com.sun.javaws.Launcher.launch(Unknown Source)
	at com.sun.javaws.Main.launchApp(Unknown Source)
	at com.sun.javaws.Main.continueInSecureThread(Unknown Source)
	at com.sun.javaws.Main.access$000(Unknown Source)
	at com.sun.javaws.Main$1.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
```

### What did you expect
> Java Admin Client started as in versions prior to 3.3.0

### Describe how to reproduce or add a test
> Start Java Admin Client from Dashboard

> The *best* way is to provide a 'self containing' test, a test that can be run without dependancies.

1. in IE or Chrome Start Dashboard
2. Click and open "Java Admin Client"

It is starts OK from "Quick Start" menu. the Quick Start menu not available if eXist runs as a service.

### Context information
Please always add the following information
- eXist-db version 3.3.0  
- Java version 1.8.0_131
- Operating system Windows 10 or Windows 2016
- 64 bit
- no changes to conf.xml

**Comment by dizzzz** [comment]
I'll check for you tonight. The stacktrace is not 'complete' I think, the caused-by is missing.

To mitigate, please could you clean your webstart cache?  https://www.java.com/en/download/help/plugin_cache.xml

**Comment by dizzzz** [comment]
The version in the DMG looks good; I expect that there is a caching issue as previously mentioned. Please could you verify?

**Comment by andray71** [comment]
I have cleared the cache, but no difference. Note: The eXist 3.1 instances is OK

I have eXist 3.3.0 installed on windows 10 and windows server 2016 - same problem (starting the client from browser/dashboard).
When I start it from "quick start" menu, it is OK (eXist runs as application not as service). 

Here is all I see in "Verifying Application" dlg -> "Application Error" dlg -> "Details" button -> "Exception" window:
JNLPException[category: Security Error : Exception: null : LaunchDesc: 
<jnlp spec="7.0" codebase="http://localhost:8080/exist/webstart/" href="exist.jnlp" version="3.3.0">
  <information>
    <title>eXist XML-DB client</title>
    <vendor>exist-db.org</vendor>
    <homepage href="http://exist-db.org"/>
    <description>Integrated command-line and gui client, entirely based on the XML:DB API and provides commands for most database related tasks, like creating and removing collections, user management, batch-loading XML data or querying.</description>
    <description kind="short">eXist XML-DB client</description>
    <description kind="tooltip">eXist XML-DB client</description>
    <icon href="jnlp_logo.jpg"/>
    <icon href="jnlp_icon_128x128.gif" width="128" height="128"/>
    <icon href="jnlp_icon_64x64.gif" width="64" height="64"/>
    <icon href="jnlp_icon_32x32.gif" width="32" height="32"/>
  </information>
  <security>
    <all-permissions/>
  </security>
  <resources>
    <property name="jnlp.packEnabled" value="true"/>
    <property name="java.util.logging.manager" value="org.apache.logging.log4j.jul.LogManager"/>
    <java version="1.8+"/>
    <jar href="log4j-jul-2.8.2.jar" size="26272"/>
    <jar href="commons-codec-1.10.jar" size="307249"/>
    <jar href="cglib-nodep-3.1.jar" size="358483"/>
    <jar href="jcip-annotations-1.0.jar" size="4005"/>
    <jar href="pkg-java-fork.jar" size="87631"/>
    <jar href="commons-logging-1.2.jar" size="66579"/>
    <jar href="jargo-0.4.2-SNAPSHOT-7fa1d04.jar" size="200065"/>
    <jar href="xmlrpc-client-3.1.3.jar" size="65537"/>
    <jar href="rsyntaxtextarea-2.6.1.jar" size="1201107"/>
    <jar href="slf4j-api-1.7.21.jar" size="46264"/>
    <jar href="exist.jar" size="4441960"/>
    <jar href="quartz-2.2.3.jar" size="700323"/>
    <jar href="clj-ds-0.0.4.jar" size="290932"/>
    <jar href="jackson-core-2.7.4.jar" size="262996"/>
    <jar href="log4j-core-2.8.2.jar" size="1498139"/>
    <jar href="commons-pool-1.6.jar" size="118732"/>
    <jar href="xmlrpc-common-3.1.3.jar" size="122505"/>
    <jar href="jline-0.9.94.jar" size="93084"/>
    <jar href="j8fu-1.4.1.jar" size="54814"/>
    <jar href="log4j-api-2.8.2.jar" size="243001"/>
    <jar href="commons-io-2.5.jar" size="221540"/>
    <jar href="gnu-crypto-2.0.1.jar" size="644209"/>
    <jar href="ws-commons-util-1.0.2.jar" size="38575"/>
    <jar href="commons-collections-3.2.2.jar" size="630602"/>
    <jar href="log4j-slf4j-impl-2.8.2.jar" size="26094"/>
    <jar href="xmldb.jar" size="12768"/>
    <jar href="antlr-2.7.7.jar" size="464341"/>
    <jar href="jta-1.1.jar" size="16277"/>
  </resources>
  <application-desc main-class="org.exist.client.InteractiveClient">
    <argument>-ouri=xmldb:exist://localhost:8080/exist/xmlrpc</argument>
    <argument>--no-embedded-mode</argument>
  </application-desc>
</jnlp> ]
	at com.sun.javaws.security.JNLPSignedResourcesHelper.checkSignedResourcesHelper(Unknown Source)
	at com.sun.javaws.security.JNLPSignedResourcesHelper.checkSignedResources(Unknown Source)
	at com.sun.javaws.Launcher.prepareResources(Unknown Source)
	at com.sun.javaws.Launcher.prepareAllResources(Unknown Source)
	at com.sun.javaws.Launcher.prepareToLaunch(Unknown Source)
	at com.sun.javaws.Launcher.prepareToLaunch(Unknown Source)
	at com.sun.javaws.Launcher.launch(Unknown Source)
	at com.sun.javaws.Main.launchApp(Unknown Source)
	at com.sun.javaws.Main.continueInSecureThread(Unknown Source)
	at com.sun.javaws.Main.access$000(Unknown Source)
	at com.sun.javaws.Main$1.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

**Comment by miljanuscumlic** [comment]
I want to confirm this issue. I have checked the Java Admin Client 3.3.0 with java versions:

- 1.8.0_92
- 1.8.0_131
- 1.8.0_141

I started the client from the Dashboard and the results were the same. I was getting this error dialog:
`Unable to launch application`
Clicking the `Details` button I have this **Error**
`Unsigned application requesting unrestricted access to system`
`Unsigned resource: http://localhost:8888/exist/webstart/exist.jar`
and two tabs.
On `Launch` tab:
```
<?xml version="1.0" ?><jnlp spec="7.0" codebase="http://localhost:8888/exist/webstart/" href="exist.jnlp" version="3.3.0"><information><title>eXist XML-DB client</title><vendor>exist-db.org</vendor><homepage href="http://exist-db.org"></homepage><description>Integrated command-line and gui client, entirely based on the XML:DB API and provides commands for most database related tasks, like creating and removing collections, user management, batch-loading XML data or querying.</description><description kind="short">eXist XML-DB client</description><description kind="tooltip">eXist XML-DB client</description><icon href="jnlp_logo.jpg"></icon><icon href="jnlp_icon_128x128.gif" width="128" height="128"></icon><icon href="jnlp_icon_64x64.gif" width="64" height="64"></icon><icon href="jnlp_icon_32x32.gif" width="32" height="32"></icon></information><security><all-permissions/></security><resources><property name="jnlp.packEnabled" value="true"></property><property name="java.util.logging.manager" value="org.apache.logging.log4j.jul.LogManager"></property><java version="1.8+"></java><jar href="log4j-jul-2.8.2.jar" size="26272"></jar><jar href="commons-codec-1.10.jar" size="307249"></jar><jar href="cglib-nodep-3.1.jar" size="358483"></jar><jar href="jcip-annotations-1.0.jar" size="4005"></jar><jar href="pkg-java-fork.jar" size="87631"></jar><jar href="commons-logging-1.2.jar" size="66579"></jar><jar href="jargo-0.4.2-SNAPSHOT-7fa1d04.jar" size="200065"></jar><jar href="xmlrpc-client-3.1.3.jar" size="65537"></jar><jar href="rsyntaxtextarea-2.6.1.jar" size="1201107"></jar><jar href="slf4j-api-1.7.21.jar" size="46264"></jar><jar href="exist.jar" size="4441960"></jar><jar href="quartz-2.2.3.jar" size="700323"></jar><jar href="clj-ds-0.0.4.jar" size="290932"></jar><jar href="jackson-core-2.7.4.jar" size="262996"></jar><jar href="log4j-core-2.8.2.jar" size="1498139"></jar><jar href="commons-pool-1.6.jar" size="118732"></jar><jar href="xmlrpc-common-3.1.3.jar" size="122505"></jar><jar href="jline-0.9.94.jar" size="93084"></jar><jar href="j8fu-1.4.1.jar" size="54814"></jar><jar href="log4j-api-2.8.2.jar" size="243001"></jar><jar href="commons-io-2.5.jar" size="221540"></jar><jar href="gnu-crypto-2.0.1.jar" size="644209"></jar><jar href="ws-commons-util-1.0.2.jar" size="38575"></jar><jar href="commons-collections-3.2.2.jar" size="630602"></jar><jar href="log4j-slf4j-impl-2.8.2.jar" size="26094"></jar><jar href="xmldb.jar" size="12768"></jar><jar href="antlr-2.7.7.jar" size="464341"></jar><jar href="jta-1.1.jar" size="16277"></jar></resources><application-desc main-class="org.exist.client.InteractiveClient"><argument>-ouri=xmldb:exist://localhost:8888/exist/xmlrpc</argument><argument>--no-embedded-mode</argument></application-desc></jnlp>
```

On `Exception` tab:
```
JNLPException[category: Security Error : Exception: null : LaunchDesc: 
<jnlp spec="7.0" codebase="http://localhost:8888/exist/webstart/" href="exist.jnlp" version="3.3.0">
  <information>
    <title>eXist XML-DB client</title>
    <vendor>exist-db.org</vendor>
    <homepage href="http://exist-db.org"/>
    <description>Integrated command-line and gui client, entirely based on the XML:DB API and provides commands for most database related tasks, like creating and removing collections, user management, batch-loading XML data or querying.</description>
    <description kind="short">eXist XML-DB client</description>
    <description kind="tooltip">eXist XML-DB client</description>
    <icon href="jnlp_logo.jpg"/>
    <icon href="jnlp_icon_128x128.gif" width="128" height="128"/>
    <icon href="jnlp_icon_64x64.gif" width="64" height="64"/>
    <icon href="jnlp_icon_32x32.gif" width="32" height="32"/>
  </information>
  <security>
    <all-permissions/>
  </security>
  <resources>
    <property name="jnlp.packEnabled" value="true"/>
    <property name="java.util.logging.manager" value="org.apache.logging.log4j.jul.LogManager"/>
    <java version="1.8+"/>
    <jar href="log4j-jul-2.8.2.jar" size="26272"/>
    <jar href="commons-codec-1.10.jar" size="307249"/>
    <jar href="cglib-nodep-3.1.jar" size="358483"/>
    <jar href="jcip-annotations-1.0.jar" size="4005"/>
    <jar href="pkg-java-fork.jar" size="87631"/>
    <jar href="commons-logging-1.2.jar" size="66579"/>
    <jar href="jargo-0.4.2-SNAPSHOT-7fa1d04.jar" size="200065"/>
    <jar href="xmlrpc-client-3.1.3.jar" size="65537"/>
    <jar href="rsyntaxtextarea-2.6.1.jar" size="1201107"/>
    <jar href="slf4j-api-1.7.21.jar" size="46264"/>
    <jar href="exist.jar" size="4441960"/>
    <jar href="quartz-2.2.3.jar" size="700323"/>
    <jar href="clj-ds-0.0.4.jar" size="290932"/>
    <jar href="jackson-core-2.7.4.jar" size="262996"/>
    <jar href="log4j-core-2.8.2.jar" size="1498139"/>
    <jar href="commons-pool-1.6.jar" size="118732"/>
    <jar href="xmlrpc-common-3.1.3.jar" size="122505"/>
    <jar href="jline-0.9.94.jar" size="93084"/>
    <jar href="j8fu-1.4.1.jar" size="54814"/>
    <jar href="log4j-api-2.8.2.jar" size="243001"/>
    <jar href="commons-io-2.5.jar" size="221540"/>
    <jar href="gnu-crypto-2.0.1.jar" size="644209"/>
    <jar href="ws-commons-util-1.0.2.jar" size="38575"/>
    <jar href="commons-collections-3.2.2.jar" size="630602"/>
    <jar href="log4j-slf4j-impl-2.8.2.jar" size="26094"/>
    <jar href="xmldb.jar" size="12768"/>
    <jar href="antlr-2.7.7.jar" size="464341"/>
    <jar href="jta-1.1.jar" size="16277"/>
  </resources>
  <application-desc main-class="org.exist.client.InteractiveClient">
    <argument>-ouri=xmldb:exist://localhost:8888/exist/xmlrpc</argument>
    <argument>--no-embedded-mode</argument>
  </application-desc>
</jnlp> ]
	at com.sun.javaws.security.JNLPSignedResourcesHelper.checkSignedResourcesHelper(Unknown Source)
	at com.sun.javaws.security.JNLPSignedResourcesHelper.checkSignedResources(Unknown Source)
	at com.sun.javaws.Launcher.prepareResources(Unknown Source)
	at com.sun.javaws.Launcher.prepareAllResources(Unknown Source)
	at com.sun.javaws.Launcher.prepareToLaunch(Unknown Source)
	at com.sun.javaws.Launcher.prepareToLaunch(Unknown Source)
	at com.sun.javaws.Launcher.launch(Unknown Source)
	at com.sun.javaws.Main.launchApp(Unknown Source)
	at com.sun.javaws.Main.continueInSecureThread(Unknown Source)
	at com.sun.javaws.Main.access$000(Unknown Source)
	at com.sun.javaws.Main$1.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
```

I downloaded exist.jnlp file and started it with `javaws exist.jnlp`, the result was the same. I managed to start the client with the command `start.jar client`. 

I have tested the client from 3.2.0 release with all above-mentioned java versions calling it from the Dashboard, and it worked fine.

So, when the invocation of the client from the 3.3.0 release goes through the JNLP something is going wrong in regard to java security policies, I presume.

**Comment by adamretter** [comment]
@miljanuscumlic Which OS were you using? Was it also Windows 10 as @andray71 originally reported?

**Comment by adamretter** [comment]
After installing 3.3.0 from the Jar Installer, I can indeed reproduce this issue on Windows 10 with Java 1.8.

**Comment by adamretter** [comment]
So after a little diagnosis, it seems that the error message is spot on, i.e.:
```
Unsigned resource: http://localhost:8888/exist/webstart/exist.jar
```

On Windows 10, if I run `jarsigner -verify c:\eXist-db\exist.jar` it states:
```
jar is unsigned. (signatures missing or not parsable)
```

The same problem occurs with `c:\eXist-db\start.jar` and `c:\eXist-db\exist-optional.jar`.
However, it seems that the jars in `c:\eXist-db\lib\**` are correctly signed.

It seems to me like something went wrong with the signing process either for or during the eXist-db 3.3.0 release. We should check 3.4.0 and see if it has the same issue...

**Comment by adamretter** [comment]
Okay so I just checked, and the same problem persists in eXist-db 3.4.0 for me. Looks like somehow not all the jars added to the installer are signed. We will have to investigate for 3.4.1...

**Comment by miljanuscumlic** [comment]
@adamretter Thanks for investigating on this. OS on which this is spotted in quite nostalgic Windows 5.1. So, in regard to this issue version does not matter. Also, it persists with exist 3.4.0 client.

**Comment by adamretter** [comment]
I can now confirm that this is also the case on MacOS as well as Windows.

The process we use for the release is something like:

```
$ git checkout eXist-3.1.0
$ ./build.sh jnlp-unsign-all all jnlp-sign-exist jnlp-sign-core
$ ./build.sh installer app-signed dist-war
```

If I run the `./build.sh jnlp-unsign-all all jnlp-sign-exist jnlp-sign-core`, and then check `exist.jar` with: `jarsigner -verify exist.jar`, then it tells me the Jar is signed.

If I then run `./build.sh installer`, and then check `exist.jar` with `jarsigner` it then reports: `jar is unsigned`. So, somehow either:
1. `exist.jar` is being recompiled (unsigned) and overwritten by the Ant target `installer`, or
2. The signing information is being removed by the Ant target `installer`.

I will investigate further.
