### ISSUE TITLE
Wrong version reported to exist.log and wrapper.log on Win10 tomcat7

### ISSUE THREAD

**Issue by duncdrum** [eXist-db/exist#1481]
### What is the problem
This [log-file](https://www.dropbox.com/s/yoqi0nstuvz8pvr/wrapper.log?dl=0) reports:
```
[eXist Version : 3.0]
```

However, as the owner has ensured me, it should be 3.3. I ran ``util:system-property`` with the following result(-s)

*   exist version: 3.3.0 build: 201707021658  
*   Java: 1.8.0_112   
*   OS: Windows 10  

### What did you expect
The eXist version in the log files to match the actual eXist version as seen by ``util:system-property``

### Describe how to reproduce or add a test
Compare the output of ``util:system-property("product-version")``with the contents of exist.log or wrapper.log

### Context information
The output(-s) of util:system-property
*   exist version: 3.3.0 build: 201707021658  
*   Java: 1.8.0_112   
*   OS: Windows 10.0  (amd64)
*   Tomcat: 7.0.56

**Comment by dizzzz** [comment]
in the log I see 

```
INFO|12032/0|Service eXist-db|17-03-07 00:16:22|07 ä¸æ?? 2017 00:16:22,033 [main] INFO  (JettyStart.java [run]:142) - [eXist Version : 3.0] 
INFO|12032/0|Service eXist-db|17-03-07 00:16:22|07 ä¸æ?? 2017 00:16:22,033 [main] INFO  (JettyStart.java [run]:143) - [eXist Build : 20170208] 
INFO|12032/0|Service eXist-db|17-03-07 00:16:22|07 ä¸æ?? 2017 00:16:22,033 [main] INFO  (JettyStart.java [run]:144) - [Git commit : develop-acd0c14] 
```

which is actually [version  3.0](https://github.com/eXist-db/exist/tree/eXist-3.0) 

the system  [properties file](https://github.com/eXist-db/exist/blob/develop/src/org/exist/system.properties) is empty in GitHub, so that would mean that during generating the release,  the file contains old data.  Maybe @adamretter can verify?

Finally.... the [exist-core.jar](https://github.com/eXist-db/mvn-repo/blob/master/org/exist-db/exist-core/3.3.0/exist-core-3.3.0.jar) artefact contains the 3.3 marker.

So..... Are you sure your environment is clean?

**Comment by duncdrum** [comment]
@dizzzz thanks for the quick response. No since this is not my system but a colleagues I m not sure about much here. However, we restarted the whole system once and the log still contains the lines that you quote, while system-properties report the values in my OP. Between reboot / startup and me running util there were no other changes to the system. The same behaviour was visible on a laptop install using jetty under Win10.

**Comment by dizzzz** [comment]
Please could you attach the exist.jar file of that system to this ticket? I'll do some archeology on this....

**Comment by duncdrum** [comment]
Here you go, 

https://www.dropbox.com/s/ngx1vwcm8b4qsdu/exist.jar?dl=0 <https://www.dropbox.com/s/ngx1vwcm8b4qsdu/exist.jar?dl=0>

Thanks for looking into this.

**Comment by dizzzz** [comment]
<img width="275" alt="exist_jar" src="https://user-images.githubusercontent.com/1700062/28239608-4547a010-6970-11e7-97f7-960ec887d1b5.png">

this jar file looks good.... both system.properties as the dates of the directories...... point to the 3.3 release.

maybe a second exist.jar exists on the class path?

**Comment by duncdrum** [comment]
@pingtzuchu unless you can chime in I'm going to close this. Since I have exerted my means of diagnosing from a distance.

**Comment by pingtzuchu** [comment]
Ok
Please close it.

The data still need lots of reformat here and there.

清華大學中國文學系副教授
教學網站：http://tinyurl.com/pingtzuchu/
台灣數位人文：http://tinyurl.com/dhintaiwan/
台灣數位人文學會：http://digital.ntu.edu.tw/tadh

2017-07-24 18:11 GMT+08:00 Duncan Paterson <notifications@github.com>:
