### ISSUE TITLE
Function documentation for xmldb:clear-lock

### ISSUE THREAD

**Issue by joewiz** [eXist-db/exist#1484]
### What is the problem

The function documentation for `xmldb:clear-lock()` appears to be a copy of `xmldb:document-has-lock()`. See https://github.com/eXist-db/exist/blob/develop/src/org/exist/xquery/functions/xmldb/XMLDBHasLock.java#L63-L74.

### What did you expect

The description should describe what the function actually does. Probably something like:

> Clears a write lock on the resource `$resource` in the collection `$collection-uri`. 

I'm not sure what the return value is supposed to be, but I think the current value must be wrong:

> the user id of the lock owner, otherwise if not locked the empty sequence

Perhaps it should be:

> `true()` if a lock was successfully cleared, `false()` if no lock was present

(But I'm really not sure what the function does in practice.)

### Describe how to reproduce or add a test

See link to source above or http://exist-db.org/exist/apps/fundocs/view.html?uri=http://exist-db.org/xquery/xmldb#clear-lock.2.

### Context information

- eXist-db version + Git Revision hash: 3.4.0-SNAPSHOT+201707142259 (af161fd52) 
- Java version: 1.8.0_131
- Operating system: macOS 10.12.5
- 32 or 64 bit: 64 bit
- Any custom changes in e.g. conf.xml: No

**Comment by duncdrum** [comment]
> The description should describe what the function actually does. 

Actually points to another problem. If a funcdoc is not as expressive as it could be there really isn't a straightforward place to raise an issue or make a pull request. 

Time for another label?
