### ISSUE TITLE
migration from v2.1 to v3.1

### ISSUE THREAD

**Issue by ilavaras** [eXist-db/exist#1487]
### What is the problem
Recently we migrated our app from from v2.1 to v3.1. One of our application was using SVN module to checkout code from SVN server. To my surprise, I did not find the module in the new version.

### What did you expect
How can I build the SVN extension module as mentioned in the previous document.
https://en.wikibooks.org/wiki/XQuery/Subversion#Enable_the_subversion_module_in_conf.xml
#SVN extension
  include.feature.svn = false

Question:
Can I get the source code from v2.1 and try to build it with v3.1 source code?  Or do we have separate code base for svn module in v3.1?

**Comment by joewiz** [comment]
Briefly, see this thread from exist-open: http://exist-open.markmail.org/thread/z3duondt23t7j6bx.
