### ISSUE TITLE
Installing using the setup jar on OS X Sierra fails

### ISSUE THREAD

**Issue by hcayless** [eXist-db/exist#1492]
### What is the problem

I'm running the JAR installer from <https://bintray.com/existdb/releases/exist/3.3.0/view>, and it fails trying to set the exec permission on the app launcher with the following command:

`/bin/chmod a+x /Applications/eXist-db/eXist-db.app/Contents/MacOS/JavaAppLauncher`

This file does not exist. There is one named `eXist-JavaAppLauncher` in that directory.

### Describe how to reproduce or add a test

Download the eXist setup JAR, and run `java -jar java -jar eXist-db-setup-3.3.0.jar`

### Context information
Please always add the following information
- eXist version: 3.3.0
- Java version 1.8.0-b132
- Operating system MacOS Sierra 10.12.5
- 32 or 64 bit -- 64
- Any custom changes in e.g. conf.xml -- none

**Comment by adamretter** [comment]
@hcayless Thanks for reporting. This one was actually fixed yesterday here - https://github.com/eXist-db/exist/pull/1488

There was meant to be a 3.4.0 release yesterday/today. I am told to expect it tomorrow now... Hopefully that will help you?
