### ISSUE TITLE
Java Admin Client deletes contents of the directory on backup

### ISSUE THREAD

**Issue by miljanuscumlic** [eXist-db/exist#1503]
### What is the problem
> Java Admin Client deletes contents of the directory on backup even I if choose No button in the Confirm deletion dialog

### What did you expect
> To store the backup without deleting anything

### Describe how to reproduce or add a test
> Open Java Admin Client
> Click Create Backup toolbar button
> In the opened dialog choose some directory with some content in it
> Erase eXist-backup.zip from the target field (i.e. backup as directory structure)
> Press OK button
> In the Confirm deletion dialog press No
> Voilà, contents of the chosen directory is deleted

### Context information
> - eXist-db version 3.4.0.
> - Java8u141
> - Operating system Windows XP
> - 32
> - Any custom changes in e.g. conf.xml: data directory

Resolution:
Code for buttons YES and NO in the Confirm deletion dialog should be exchanged, because when you press YES button in the Confirm deletion dialog, the contents are **not deleted**. The logic is inverse.

**Also**, close or cancel button in the same dialog should stop the backup procedure. But it acts as if I pressed YES button i.e. it proceeds with the backup and do not delete the contents.

**Comment by dizzzz** [comment]
With "directory" do you mean a directory on disk, or a collection in the database?

**Comment by miljanuscumlic** [comment]
It deletes contents in the chosen directory on the disk.
Before backup:
![folder before backup](https://user-images.githubusercontent.com/30440470/28745431-b1f8af84-7478-11e7-8938-118da2cf82c1.jpg)
During backup:
![folder during backup](https://user-images.githubusercontent.com/30440470/28745434-ba3d90ce-7478-11e7-99e2-dd0e66d74dd6.jpg)
After backup:
![folder after backup](https://user-images.githubusercontent.com/30440470/28745436-c0d0cfb4-7478-11e7-8db3-a8a714d34b56.jpg)
Pdf that was in the directory on disk (before backup) is deleted although I pressed No button.

**Comment by dizzzz** [comment]
Ah.... ok, I did not understand this initially.
Hmmmm this is bad indeed, though mixing up backup files with other files is probably a bad idea.
If there is content, I'd expect that the backup-tool would not start the backup at all, and leave the files there.

**Comment by dizzzz** [comment]
There is a bug indeed :-/

<img width="724" alt="clientframe_java_-_exist_-____development_github_exist_" src="https://user-images.githubusercontent.com/1700062/28745605-ea0cdcc6-747b-11e7-95a7-353ff5c09896.png">

**Comment by miljanuscumlic** [comment]
You are most welcome.
I agree that it is not a good idea, but I am new to exist and I am testing it. So, I thought to do the backup on the desktop, and all from it disappeared into thin air (I am not using Recycle Bin).
I think that's not how it should behave :) , so I reported it.
Thanks for the investigation.

**Comment by dizzzz** [comment]
fixed in https://github.com/eXist-db/exist/pull/1505

**Comment by miljanuscumlic** [comment]
Does this fix the behavior of the close button I have described earlier?

> Also, close or cancel button in the same dialog should stop the backup procedure. But it acts as if I pressed YES button i.e. it proceeds with the backup and do not delete the contents.

**Comment by dizzzz** [comment]
No it does not perse address that issue. You mean by clicking the [X] on top right?

I updated the PR

**Comment by miljanuscumlic** [comment]
Great. Yes, that's what I meant: [X].
