### ISSUE TITLE
Backup script reports an error during initialization of VM

### ISSUE THREAD

**Issue by miljanuscumlic** [eXist-db/exist#1504]
### What is the problem
> Backup script cannot find the directories and reports an error during initialization of VM
> ```
> The system cannot find the file C:\Programs\Java\jdk1.8.0_141.
> The system cannot find the file C:\Programs\exist-db.
> Error occurred during initialization of VM
> Could not reserve enough space for 2097152KB object heap
> ```

### What did you expect
> To back up the database

### Describe how to reproduce or add a test
> ```
>backup.bat -u admin -p pass -b  /db -d "C:\Documents and Settings\miljan\Desktop\exist\" -ouri=xmldb:exist://localhost:8888/xmlrpc
>```

### Context information
- eXist-db version 3.4.0.
- Java8u141
- Windows XP
- 32
- regular conf.xml

The database is extremely small in size.

**Comment by dizzzz** [comment]
I think the issue here is that you use a 32bit VM .... generally that is  not a good idea anymore :-) running 32bit/windows makes things even worse.

See https://stackoverflow.com/questions/4080023/jvm-heapsize-on-32-bit-os#4080220 .... the max heap size is approx. 1.6 gig;

Please also read this on Java8: https://www.java.com/en/download/faq/winxp.xml

".. users may still continue to use Java 8 on Windows XP at their own risk, but we can no longer provide complete guarantees for Java on Windows XP, since the OS is no longer being updated by Microsoft."

Here to tune the heap size: https://github.com/eXist-db/exist/blob/develop/bin/backup.bat#L60

**Comment by miljanuscumlic** [comment]
Thanks for this info. I couldn't agree with you more in regards with 32bit VM, but at this point I am stuck with it (very long story :). 
I have changed MX property in backup.bat with:
`set MX = 1024`
Then I got this report:
```
The system cannot find the file C:\Programs\Java\jdk1.8.0_141.
The system cannot find the file C:\Programs\exist-db.
java.nio.file.InvalidPathException: Illegal char <"> at index 46: C:\Documents and Settings\miljan\Desktop\exist" -ouri xmldb:exist:\localhost:8888\xmlrpc
        at sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:182)
        at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153)
        at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
        at sun.nio.fs.WindowsPath.parse(WindowsPath.java:94)
        at sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:255)
        at java.nio.file.Paths.get(Paths.java:84)
        at org.exist.backup.Main.process(Main.java:222)
        at org.exist.backup.Main.main(Main.java:418)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.exist.start.Main.invokeMain(Main.java:140)
        at org.exist.start.Main.run(Main.java:453)
        at org.exist.start.Main.main(Main.java:64)
```

The path is wrong cause there is a `"` character at the begging of the path which is not stripped from my command line parameter `"C:\Documents and Settings\miljan\Desktop\exist\"`.

**Comment by dizzzz** [comment]
it should read 'xmldb:exist://localhost:8888/xmlrpc'

**Comment by miljanuscumlic** [comment]
Yes, I agree about the spaces. I can use directory without spaces, but I just wanted to point that script does not handle them very well and throws an exception.

Ok. I hope I will make script work. 
When I call script like this:
`backup.bat -u admin -p pass -b  /db -d C:\temp\exist\ -ouri=xmldb:exist://localhost:8888/xmlrpc`

I am getting this:
```
The system cannot find the file C:\Programs\Java\jdk1.8.0_141.
The system cannot find the file C:\Programs\exist-db.
'-ouri' is missing an assignment operator(=). See usage for -o for proper values.
Usage: Main [Arguments]
....
```

**Comment by dizzzz** [comment]
It might be better to switch to the exist-open mailing list as this thread kinda migrates from an issue report into a support thread. On exist-open more ppl read messages and there therefore better interaction.

**Comment by miljanuscumlic** [comment]
Ok. Thanks for your time. I thought it was an issue.

**Comment by dizzzz** [comment]
Well, probably you found an issue with the -o option, I am not sure yet. But it is potentially a new issue .....

The best thing is to report a )potential) issue on the mailing lists. One of the members will read it, and ask you to create a ticket when it is indeed a problem.

The benefit of exist-open is... it is being read by a lot of ppl, this ticket probably by me :)
