### ISSUE TITLE
Remove deprecated "fn" functions in next major version (5.0.0)

### ISSUE THREAD

**Issue by joewiz** [eXist-db/exist#1510]
eXist has 4 functions that are nowhere to be found in the final XPath and XQuery F&O 3.1 spec:

1. `fn:map` - http://exist-db.org/exist/apps/fundocs/view.html?uri=http://www.w3.org/2005/xpath-functions#map.2
2. `fn:map-pairs` - http://exist-db.org/exist/apps/fundocs/view.html?uri=http://www.w3.org/2005/xpath-functions#map-pairs.3
3. `fn:equals` - http://exist-db.org/exist/apps/fundocs/view.html?uri=http://www.w3.org/2005/xpath-functions#equals.2
4. `fn:escape-uri` - http://exist-db.org/exist/apps/fundocs/view.html?uri=http://www.w3.org/2005/xpath-functions#escape-uri.2

As for 1 and 2, eXist's function docs notes that the two `fn:map*` functions are deprecated and "could be removed in the next major release version." (See screenshot below.)  

As for 3 and 4, I'm not sure when these were added to eXist, but they are not in the spec and so should be moved/removed too.  Since they are not currently marked as deprecated, they should be to alert developers of the planned change.  Perhaps `fn:equals` should be moved to the `util` module, and `escape-uri` is probably already reflected in `fn:escape-html-uri` but if it's moved to the `util` module would make a natural pair to `util:unescape-uri`.

This issue serves as a request to remove all 4 functions in the next major release version, 4.0.0.

> <img width="1162" alt="xquery_function_documentation" src="https://user-images.githubusercontent.com/59118/28882973-db6d62a6-777a-11e7-8b66-6eeb77d87554.png">

**Comment by joewiz** [comment]
I somehow neglected these functions in my most survey (now [updated](https://gist.github.com/joewiz/acb0558f078c0576a5e7#gistcomment-2165426)):

5. `map:for-each-entry`- http://exist-db.org/exist/apps/fundocs/view.html?uri=http://www.w3.org/2005/xpath-functions/map#for-each-entry.2
6. `map:new` - http://exist-db.org/exist/apps/fundocs/view.html?uri=http://www.w3.org/2005/xpath-functions/map#new.0

**Comment by joewiz** [comment]
We resolved during today's Community Call to defer the removal of these deprecated functions to eXist 5.0.0. To discourage their use in the meantime, I submitted PRs https://github.com/eXist-db/eXide/pull/180 and https://github.com/wolfgangmm/atom-editor-support/pull/9 to 

Unfortunately, two of the functions above still haven't been marked as deprecated (the others already are), so until we do so, users will have no idea that these functions are not part of the XQuery 3.1 spec:

- `fn:equals()`
- `fn:escape-uri()`

We should mark these as deprecated ASAP so that users are put on notice for the next major version.

**Comment by duncdrum** [comment]
This issue needs the deprecation label (sorry I missed it when commenting in HipChat)
