### ISSUE TITLE
User manager2 is not showing correct user data

### ISSUE THREAD

**Issue by miljanuscumlic** [eXist-db/exist#1511]
### What is the problem
> User manager2 is showing data from the previously opened user

### What did you expect
> To show user's own data

### Describe how to reproduce or add a test
> This is screencast: [user-manager-2.zip](https://github.com/eXist-db/exist/files/1201233/user-manager-2.zip)
> Open User manager from the Dashboard
> Right click on monex (or any other)
> Choose: Edit monex
> Close the app by clicking [x] in upper right corner
> Open User manager
> Right click on any user
> Edit user
> Data of the monex user are displayed

### Context information
Please always add the following information
- eXist-db version 3.4.0.
- Java8u141
- Windows XP
- 32 bit
- Chrome, Firefox

**Comment by joewiz** [comment]
A screencast is a great way to demonstrate complex UI interactions, but unfortunately the zip file you posted contains an .exe file, which I'm unable to view as a non-Windows user. Could you post your screencast in a standard video format or to some video sharing service like Youtube?

Also, I've never seen "Edit monex" in monex. Unless I can see the screencast I am not clear what "Edit monex" means.

**Comment by joewiz** [comment]
(I've updated my original post.)

**Comment by miljanuscumlic** [comment]
Here is the screencast on Youtube: https://youtu.be/4TNofaTsKNY
In my issue post it should be: 
> Edit user

not
> Edit monex.

**Comment by duncdrum** [comment]
The fact that you have ``package-manager2`` suggest the persistent log-in problem that came up in multiple issue reports already. Have you selected the ``Remember me`` checkbox in dashboard? If so could you try to test again without it?

**Comment by miljanuscumlic** [comment]
@duncdrum I have seen some of those issues but I did not find complete correlation with this one. 
I have tried with checked `Remember me` checkbox, and all I got were empty list and `Sorry, an error occurred` message. This issue I am reporting is with the unchecked `Remember me` checkbox in dashboard.

**Comment by duncdrum** [comment]
I still think that resolving eXist-db/dashboard/issues/44 might fix this as well. Something related to login seems to open dashboard apps in another dimension, so chances are that the old user data is coming from there.

**Comment by adamretter** [comment]
@JoernT Do you have any advice here please?

**Comment by JoernT** [comment]
No sorry. I assume that duncrum is right with the assumption that it has to do with eXist-db/dashboard/#44. Do you remember that you intially wrote that code @adamretter ;) ?

We've already deprecated the current dashboard in favor of the newer existdb-dashboard (soon to be migrated to github) and exist-db/usermanager. 

So it's the question how severe we consider this and if it's worth fixing or instead go for the next version.

**Comment by duncdrum** [comment]
I can reproduce this on fresh installations on macOS. My suggestion is to remove the old usermanager from the bundle of the default deployment apps, and replace it with Joern's new user manager, which does not suffer from this problem. 
This bug is quite annoying when users want to update and restore from backup but have to restart multiple times until they can reset the admin password.
