### ISSUE TITLE
Exist-db 3.4 fails to start - 

### ISSUE THREAD

**Issue by chippyash** [eXist-db/exist#1515]
### What is the problem
First start of eXist-db was good.  Rebooted machine after a package upgrade and now it hangs when starting up.  Get

`ERROR (JettyStart.java [run]:172) - configuration error: org.exist.storage.BrokerPoolServiceException: org.exist.util.DatabaseConfigurationException: Exception while reading lucene index directory: /home/akitson/eXist-db/webapp/WEB-INF/data/lucene/segments_2 
org.exist.EXistException: org.exist.storage.BrokerPoolServiceException: org.exist.util.DatabaseConfigurationException: Exception while reading lucene index directory: /home/akitson/eXist-db/webapp/WEB-INF/data/lucene/segments_2`

in logs/exist.log 

the eXist-db/webapp/WEB-INF/data/lucene/segments_2 directory does not exist

### Context information
- eXist-db version 3.4.0
- openjdk version "1.8.0_131"
- OpenJDK Runtime Environment (build 1.8.0_131-8u131-b11-2ubuntu1.16.04.3-b11)
- OpenJDK 64-Bit Server VM (build 25.131-b11, mixed mode)
- Operating system Linux 64 bit
- No changes

**Comment by adamretter** [comment]
Do you have more than one instance of eXist running?

**Comment by chippyash** [comment]
@adamretter No, I didn't.  As it was a recently fresh install and after waiting a few days, I simply deleted and re-installed it so cannot replicate again.  Thanks anyway.
