### ISSUE TITLE
Weird behavior when called by REST-Call

### ISSUE THREAD

**Issue by StephanMa** [eXist-db/exist#1525]
### What is the problem
Not really sure if bug or config error:

We call some xquery modules via REST. Via REST we are adding some data as payload to the REST Call.
But from time to time, it seems that xquery is not able to get access to the data.

Adding logging statements in xquery, which contains the data let the function work. It seems that maybe the variable is only filled if the variable is used inside of the called xquery function.

### What did you expect
I expect that the called xquery module is able to access the variable all the time and not only if you are using it again.

### Describe how to reproduce or add a test
This script does not work (snipped):
Variables are empty!

```xquery
xquery version "3.0";

declare option exist:serialize "method=xml media-type=text/xml omit-xml-declaration=no indent=yes";

let $method := request:get-method()
let $service-name := request:get-parameter("service", "")

let $data := root(request:get-data())/element()
let $xsdloc := xs:string($data/xsdloc[1]/text())


if($service-name!='') then

let $path := xs:string($data/path[1]/text())

let $xsdloc := xs:string($data/xsdloc[1]/text())

return

if($service-name='get-menu') then

let $content := $data/content[1]
let $selection := $data/selection[1]

let $menue := qxrxa:get-menu($path, $content, $selection, $xsdloc)

return
$menue
```

This Version works...

```xquery
xquery version "3.0";

declare option exist:serialize "method=xml media-type=text/xml omit-xml-declaration=no indent=yes";

let $method := request:get-method()
let $service-name := request:get-parameter("service", "")

let $data := root(request:get-data())/element()
let $xsdloc := xs:string($data/xsdloc[1]/text())


if($service-name!='') then

let $path := xs:string($data/path[1]/text())

let $xsdloc := xs:string($data/xsdloc[1]/text())

return

if($service-name='get-menu') then

let $content := $data/content[1]
let $selection := $data/selection[1]

let $log := util:log("ERROR", $content )
let $log := util:log("ERROR", $selection )
let $log := util:log("ERROR", $path)
let $log := util:log("ERROR", $xsdloc)

let $menue := qxrxa:get-menu($path, $content, $selection, $xsdloc)

return
$menue
```
The only differences are the logging statements..

### Context information
Please always add the following information
- eXist-db version: eXist 3.4.1 (last release) 
- Java version  Java8u144
- Ubuntu 16.04
- 64 bit
- Jetty: changed port to 80 and context to /
Conf: added self written module excel (which is not used by the function)

**Comment by StephanMa** [comment]
Does occur in every eXist Version (>= 3)

**Comment by adamretter** [comment]
@StephanMa Can you produce a self-contained test for us? And provide an example of the HTTP request you are sending to the script please?

**Comment by StephanMa** [comment]
@adamretter i will try to provide with everything necessary...

It should not be a permanent problem but it occurs regulary..

**Comment by adamretter** [comment]
@StephanMa any update on this please?

**Comment by StephanMa** [comment]
We still have this issue.. but currently i am not able to provide you with certain tests.
I would suggest to close this issue until i find another possibility to show this issue to you.
