### ISSUE TITLE
YAJSW: stdout output is truncated

### ISSUE THREAD

**Issue by dizzzz** [eXist-db/exist#1533]
### What is the problem
When running eXIist-db as a service (yajsw), not all logging from `util:log-system-out` is written to the file `wrapper.log`

e.g. the query 

```xquery
xquery version "3.1";

for $i in 1 to 1000
return
    util:log-system-out("message=" || $i)
```

only writes a limited nr of items to the file:

```
INFO|9197/0|Service eXist-db|17-08-28 21:41:05|(Line: 5 String) message=58
INFO|9197/0|Service eXist-db|17-08-28 21:41:05|(Line: 5 String) message=59
INFO|9197/0|Service eXist-db|17-08-28 21:41:05|(Line: 5 String) message=60
INFO|9197/0|Service eXist-db|17-08-28 21:41:05|(Line: 5 String) message=61
INFO|9197/0|Service eXist-db|17-08-28 21:41:05|[Fatal Error] :-1:-1: Premature end of file.
```
interesting facts:
- re-running the query does not write new data to the logs
- rerunning with `util:log-system-err` has the same behaviour ; after some entries it stops outputting
- rerunning the original query keeps the logfile quiet.
- updating yajsw to the latest version does not solve the issue

### What did you expect
The log file should always capture all stdout/stderr output

### Describe how to reproduce or add a test
- start exist: `./tools/yajsw/bin/installDaemon.sh`
- tail logfile `./tools/yajsw/logs/wrapper.log`
- run script 2x --> only a limited nr of entries are lofted

### Context information
Please always add the following information
- eXist-db version +  eXist-db 3.4.1 
- Java version (e.g. Java8u141)
- Operating system (MacOs)
- 64 bit
- Any custom changes in e.g. conf.xml: no

**Comment by adamretter** [comment]
@dizzzz I am not sure if this helps shed any light on the situation, but `:-1:-1: Premature end of file.` is emitted from Xerces when you try and parse an empty input as XML.

**Comment by dizzzz** [comment]
The interesting thing.... when running `runConsole.sh` then  the output is ok...

**Comment by dizzzz** [comment]
There is a workaround: use one of the available functions that uses the actual log4j2 logger. It is possible to define a separate logfile in log4j2.xml, and write to it.

**Comment by ljo** [comment]
I could have a look at this too.

**Comment by dizzzz** [comment]
![xquery_function_documentation](https://user-images.githubusercontent.com/1700062/31355238-bcd5d98c-ad39-11e7-8e5a-b118a3e0896d.png)

**Comment by dizzzz** [comment]
Example: add to '$EXIST_HOME/log4j2.xml' (or  '$EXIST_HOME/tools/yajsw/conf/log4j2.xml') two fragments:

in `Appenders`:

```xml
<RollingRandomAccessFile name="my_app" filePattern="${logs}/my_app.${rollover.file.pattern}.log.gz" fileName="${logs}/my_app.log">
  <Policies>
    <SizeBasedTriggeringPolicy size="${rollover.max.size}"/>
  </Policies>
  <DefaultRolloverStrategy max="${rollover.max}"/>
  <PatternLayout pattern="${exist.file.pattern}"/>
</RollingRandomAccessFile>
```

in `Loggers`
```xml
<Logger name="my_app" additivity="false" level="debug">
  <AppenderRef ref="my_app"/>
</Logger>
```

restart eXist-db.  Then in exide run

```xquery
xquery version "3.1";

util:log-app("INFO", "my_app", "info level"), 
util:log-app("DEBUG", "my_app", "debug level"), 
util:log-app("ERROR", "my_app", "error level"), 
util:log-app("TRACE", "my_app", "trace level") (: will not be logged due to level :)
```

the result in  `$EXIST_HOME/webapp/WEB-INF/logs` is a file called `my_app.log` containing

```
2017-10-10 12:24:23,400 [qtp336927685-46] INFO  (LogFunction.java [writeLog]:199) - (Line: 3 String) info level 
2017-10-10 12:24:23,400 [qtp336927685-46] DEBUG (LogFunction.java [writeLog]:205) - (Line: 3 String) debug level 
2017-10-10 12:24:23,400 [qtp336927685-46] ERROR (LogFunction.java [writeLog]:193) - (Line: 3 String) error level 
```

the logs are also written in `exist.log`, not sure if that is the actual intention :-)

**Comment by duncdrum** [comment]
@dizzzz i think i stumbled across this in docker, is this still an issue?

**Comment by dizzzz** [comment]
yes there is no fix, except not to abuse this as logging.

**Comment by adamretter** [comment]
@dizzzz we no longer use YAJSW in eXist-db 5.0.0 so I think we could close this now?
