### ISSUE TITLE
History Trigger's behavior depends on the filename of .xconf file

### ISSUE THREAD

**Issue by miljanuscumlic** [eXist-db/exist#1547]
### What is the problem
> History Trigger does not behave in the same way when the name of the .xconf file is something different than collection e.g. after I delete the .xconf document trigger is still working.

The documentation page https://exist-db.org/exist/apps/doc/triggers.xml states: 

> To configure triggers for a given collection - for example: /db/foo - create a new .xconf configuration file and store it in the system collection (e.g. /db/system/config/db/foo/collection.xconf). **You may choose any name** for this document so long as it has the .xconf extension, although collection.xconf is recommended. Note that since subcollections will inherit the configuration policy of their parent collections, you are not required to specify a configuration for every collection.

But if I use some other filename there is a difference in behavior.

### What did you expect
> Trigger to behave in same manner regardless of the .xconf document's filename.

### Describe how to reproduce or add a test
> 

- create a.xconf configuration file (or with any name other than collection) with the contents:
```
<collection xmlns='http://exist-db.org/collection-config/1.0'>
     <triggers>
       <trigger class="org.exist.collections.triggers.HistoryTrigger"/>
     </triggers>
</collection>
```

- put that document in proper subcollection of  /db/system/config (depending on your application's name)
- run Java application with some delete or update requests using xmldb; trigger should work ok (except it actually won't but that is another [issue](https://github.com/eXist-db/exist/issues/139))
- delete a.xconf configuration document
- run your application; trigger is still working as if the document is not deleted
- to stop the trigger exist have to be restarted

I have not tested it, but the application might not have to be in Java.

When the configuration file is named collection.xconf, trigger stops after the .xconf file is deleted.

### Context information
- eXist-db 3.4.0
- Java8u141
- Windows XP
- 32 bit
- Any custom changes in e.g. conf.xml: none

**Comment by adamretter** [comment]
I think we should instead update the documentation. I see no point in allowing the file to be named anything other than `collection.xconf`.

**Comment by miljanuscumlic** [comment]
OK Adam. I just followed your suggestion from the exist-open list, to open this issue so that this would not be forgotten.

**Comment by adamretter** [comment]
@miljanuscumlic Thank you. I have opened a documentation PR here - https://github.com/eXist-db/documentation/pull/129

**Comment by miljanuscumlic** [comment]
@adamretter No problem.
