### ISSUE TITLE
Suggestions for contributing.md

### ISSUE THREAD

**Issue by duncdrum** [eXist-db/exist#1554]
Inspired by [TravisCI](https://github.com/travis-ci/travis-ci/blob/master/CONTRIBUTING.md). Should there be a ``security@existsolutions.com`` contact, so that people reporting security issues don't have to open issues on a publicly visible repo?

Something like:

## Security Issues

***If you find a security vulnerability, do NOT open an issue.***

Any security issues should be submitted directly to <security@existsolutions.com>.  In order to determine whether you are dealing with a security issue, ask yourself these two questions:

*   Can I access something that's not mine, or something I shouldn't have access to?
*   Can I disable something for other people?

If the answer to either of those two questions are "yes", then you're probably dealing with a security issue. Note that even if you answer "no" to both questions, you may still be dealing with a security issue, so if you're unsure, just email us at <security@existsolutions.com>.

**Comment by adamretter** [comment]
Seems reasonable, apart from the email should be `security@exist-db.org`. We might also consider adding a `Security.txt` to the website - https://www.ietf.org/id/draft-foudil-securitytxt-00.txt

**Comment by duncdrum** [comment]
If you want to create the security.txt, it sounds like a good idea. I don't have sufficient privileges  on exist-db.org to do so.

**Comment by adamretter** [comment]
@ljo I have created a `security.txt` in `/home/existdb` on `exist-db.org` but I have no idea how to place it at http://www.exist-db.org/security.txt. Would you be able to move it into place please?
