### ISSUE TITLE
repo.xml corrupted after rebuild/install and package repair

### ISSUE THREAD

**Issue by pherk** [eXist-db/exist#1573]
### What is the problem

eXide repo.xml shows:
<meta xmlns="http://exist-db.org/xquery/repo">
    <description>eXide - a web based XQuery IDE</description>
    <author>Wolfgang Meier</author>
    <website>http://exist-db.org/exist/apps/eXide/docs/doc.html</website>
    <status>stable</status>
    <license>GNU-GPLv3</license>
    <copyright>true</copyright>
    <type>application</type>
    <target>eXide</target>
    <prepare>pre-install.xql</prepare>
    <finish/>
    <permissions xmlns:repo="http://exist-db.org/xquery/repo" user="eXide" group="eXide" mode="0775" #unknown="http://exist-db.org/xquery/repo"/>
... snip

the namespace problem is not confined to eXide repo.xml (monex and some of my apps are usually corrupted too). It seems that only element with xmlns:repo attribute are concerned (permission, change).

### What did you expect

error should not occur ;-)

### Describe how to reproduce or add a test
after ./build.sh rebuild and installation of custom apps via package manager,  run
~~~
import module namespace repair="http://exist-db.org/xquery/repo/repair"
at "resource:org/exist/xquery/modules/expathrepo/repair.xql";
declare namespace exrest = "http://exquery.org/ns/restxq/exist";

(: repair expath repo :)
  repair:clean-all()
, repair:repair()
~~~
editing of repo.xml and re-running repair() clears the problem, strangely!

### Context information
- eXist-db version 3.6-snapshot, newest develop 
- Java8u131
- Linux
- 64 bit
- no (relevant) custom changes

**Comment by pherk** [comment]
- backup/restore tried with #1640, no errors

**Comment by dizzzz** [comment]
We plan to release 3.6.1 soonish...
