### ISSUE TITLE
%private annotation acting too strict

### ISSUE THREAD

**Issue by JoernT** [eXist-db/exist#1574]
### What is the problem
When calling a public function of an app A from an app B an error occurs when the called function of app A is using private functions.

The error displayed in eXide is: "calling a private function from outside its module"

### What did you expect
i expect the public function of app A to be executed.

### Describe how to reproduce or add a test
i attached two app archives (as zip instead of .xar but that works anyway)

to reproduce:
* install existdb-packageservice.zip with packagemanager
* install existdb-dashboard.zip with packagemanager
* open eXide '/apps/existdb-dashboard/modules/test.xql' and press 'evaluate'

### Context information
Please always add the following information
- eXist-db 3.5.0
- Java version "1.8.0_112"
- Operating system MacOs
- 64 bit

[existdb-dashboard-0.6.0.zip](https://github.com/eXist-db/exist/files/1368988/existdb-dashboard-0.6.0.zip)
[existdb-packageservice-0.13.0.zip](https://github.com/eXist-db/exist/files/1368987/existdb-packageservice-0.13.0.zip)

**Comment by JoernT** [comment]
@wolfgangmm any idea where to look in the code for that problem?

**Comment by wolfgangmm** [comment]
@JoernT `org.exist.xquery.ExternalModuleImpl#getFunction` is the location to check. I'm not sure why it throws an error in your case.

**Comment by duncdrum** [comment]
@JoernT is this still an issue with 5-RC?

**Comment by duncdrum** [comment]
@JoernT is this still an issue? Could you provide a PR with a test that demonstrates the problem.

**Comment by duncdrum** [comment]
ping @JoernT
