### ISSUE TITLE
Regression? 3.5's installer doesn't create data folder.

### ISSUE THREAD

**Issue by funkyfuture** [eXist-db/exist#1576]
### What is the problem

While the installer of version 3.4.1 created the folder that was given as argument for the 'Data Directory', the one of 3.5.0 doesn't. This is at least true for relative paths that are supposed to be siblings of the installation target.

If this changed behaviour is intended, it should be mentioned in the changelog.

### Describe how to reproduce or add a test

```
$ java -jar ~/Downloads/eXist-db-setup-3.5.0.jar -console                                                                                                                                        
Select target path [/tmp] 
/tmp/test
press 1 to continue, 2 to quit, 3 to redisplay
1
Set Data Directory
Please select a directory where eXist-db will keep its data files. On Windows, this should be outside the 'Program Files' directory. Please make sure eXist can write to the directory it is installed in.
Data dir:  [webapp/WEB-INF/data] 
../data
press 1 to continue, 2 to quit, 3 to redisplay
1
Set Admin Password and Configure Memory
Enter password:  [] 
test
Enter password:  [test] 

------------------------------------------

Maximum memory in MB: [2048] 

Cache memory in MB: [256] 

press 1 to continue, 2 to quit, 3 to redisplay
1
[ Starting to unpack ]
[ Processing package: Sources (1/10) ]
[ Processing package: Core (2/10) ]
[ Processing package: Apps (3/10) ]
[ Processing package: shared (4/10) ]
[ Processing package: dashboard (5/10) ]
[ Processing package: doc (6/10) ]
[ Processing package: eXide (7/10) ]
[ Processing package: fundocs (8/10) ]
[ Processing package: markdown (9/10) ]
[ Processing package: monex (10/10) ]
[ Unpacking finished ]
[ Starting processing ]
Starting process Setting admin password ... (1/1)
--- Starting embedded database instance ---
Setting admin user password...
--- Initialization complete. Shutdown embedded database instance ---
[ Console installation done ]
$ [ -d /tmp/data ]; echo $?
1
```

versus

```
$ java -jar ~/Downloads/eXist-db-setup-3.4.1.jar -console                                                                                                                                        
/tmp/test
press 1 to continue, 2 to quit, 3 to redisplay
1
Set Data Directory
Please select a directory where eXist-db will keep its data files. On Windows, this should be outside the 'Program Files' directory. Please make sure eXist can write to the directory it is installed in.
Data dir:  [webapp/WEB-INF/data] 
../data
press 1 to continue, 2 to quit, 3 to redisplay
1
Set Admin Password and Configure Memory
Enter password:  [] 
test
Enter password:  [test] 

------------------------------------------

Maximum memory in MB: [2048] 

Cache memory in MB: [256] 

press 1 to continue, 2 to quit, 3 to redisplay
1
[ Starting to unpack ]
[ Processing package: Sources (1/10) ]
[ Processing package: Core (2/10) ]
[ Processing package: Apps (3/10) ]
[ Processing package: shared (4/10) ]
[ Processing package: dashboard (5/10) ]
[ Processing package: doc (6/10) ]
[ Processing package: eXide (7/10) ]
[ Processing package: fundocs (8/10) ]
[ Processing package: markdown (9/10) ]
[ Processing package: monex (10/10) ]
[ Unpacking finished ]
[ Starting processing ]
Starting process Setting admin password ... (1/1)
--- Starting embedded database instance ---
Setting admin user password...
--- Initialization complete. Shutdown embedded database instance ---
[ Console installation done ]
$ [ -d /tmp/data ]; echo $?
0
```

### Context information
Please always add the following information
- eXist-db 3.4.1 /  e8996ca |  3.5.0 / 12aea86
- OpenJDK Runtime Environment (build 1.8.0_131-8u131-b11-2ubuntu1.16.04.3-b11)
- Ubuntu Xenial
- 64 bit

**Comment by adamretter** [comment]
@funkyfuture Could you include the full-output above for 3.4.1 please? I am somewhat confused by this issue as there have been no significant changes to the installer between 3.4.1 and 3.5.0 that I can see: https://github.com/eXist-db/exist/compare/eXist-3.4.1...eXist-3.5.0

Also setting the password would not success without creating a data-directory.

I am also somewhat puzzled by your use of `../data`?

**Comment by funkyfuture** [comment]
i amended the formerly ellipsed content.

> I am also somewhat puzzled by your use of `../data`?

well, it's about segregation of concerns (application and application data itc), which is our policy here. afaict this is practiced for a while now without problems. the dream is that this will ease upgrades, but we haven't come to this point yet. (what puzzles me btw, that it seems to be common to not segregate these aspects in Javaland.)

**Comment by adamretter** [comment]
> i amended the formerly ellipsed content.
Sorry I am still seeing the ellipsed content!

>well, it's about segregation of concerns
Indeed, and correctly so. I just wondered why you didn't use the absolute path?

**Comment by funkyfuture** [comment]
> Sorry I am still seeing the ellipsed content!

sorry, i confused the previe with the result.

> I just wondered why you didn't use the absolute path?

we can move the whole directory w/o the need to touch the config.

**Comment by adamretter** [comment]
@funkyfuture So I can reproduce this exactly as you describe. However, I cannot see for any reason why there should be a different. Although obviously there is.

Is this a serious issue for you? or are you able to workaround?

**Comment by funkyfuture** [comment]
well, if you say that setting a password would be imposssible, then yes, it's a problem.

what i haven't tried out yet, is to provide an absolute path.

if that'd not be a straightforward solution, we could put a workaround in our wrapping installer script. what would be necessary for that?

- use the exist-db's installer default
- move the data folder after the installation
- adjust the `conf.xml`

would that suffice? and it would be a workaround, not a solution.

#964 is kind a relevant here too, imo.

**Comment by funkyfuture** [comment]
okay, i figured out that as a workaround it is sufficient to create the designated data folder before invoking the installer. and that should also be enough information to hunt that bug down.

**Comment by adamretter** [comment]
@funkyfuture as you have a workaround, I am going to label this "installer" and note that this will likely be solved by https://github.com/eXist-db/exist/pull/1489
