### ISSUE TITLE
Falsely deleting of blank character between two angle brackets

### ISSUE THREAD

**Issue by larifarian** [eXist-db/exist#1608]
Thank you for reporting your issue!

To be able to better understand you problem or suggestion, please add as much information as possible to this ticket. When there is no or just little information, it will be too difficult to work on it (and hence we will not be able to solve it)

Please fill in the following sections:

### What is the problem
> If there are only blank characters between two angle brackets, these will be deleted in exist-db. Its important to have the opportunity to code blank characters between two angle brackets (e.g. at transcribing a running text: 

`<tei:persName><tei:forename>Max</tei:forename>U+0020<tei:surname>Mustermann</tei:surname></tei:persName>`

### What did you expect
> Describe what you expected to happen. Add for example a reference to a [specification](https://www.w3.org/TR/xquery-3/).

### Describe how to reproduce or add a test
> Describe how we can can reproduce the problem.

> The *best* way is to provide a 'self containing' test, a test that can be run without dependancies. The [XQSuite - Annotation-based Test Framework for XQuery](http://exist-db.org/exist/apps/doc/xqsuite.xml) makes it very easy for you to create tests. These tests can be executed from the [eXide editor](http://exist-db.org/exist/apps/eXide/index.html) (XQuery - Run as Test)

### Context information
Please always add the following information
- eXist-db version + Git Revision hash e.g. eXist-db 3.0 /  acd0c14 
- Java version (e.g. Java8u121)
- Operating system (Windows 7, Linux, MacOs)
- 32 or 64 bit
- Any custom changes in e.g. conf.xml

**Comment by wolfgangmm** [comment]
There have been quite some fixes to whitespace handling recently. Could you make sure to test a newer build as it looks like you're on an earlier version of eXist?

**Comment by mathias-goebel** [comment]
it seems to me that `tei:person` is a so called mixed content node. have you tried to set `preserve-whitespace-mixed-content` to `yes` at `conf.xml`? to take effect changes here require new data import, i guess.

**Comment by larifarian** [comment]
Hallo zusammen,

Stefan Makowski hat die config-Datei angepasst (s. u.). Ein erster Test von Martina hat ergeben, dass die Leerzeichen jetzt gespeichert bleiben. 

@Vera: Kannst du da bitte einmal verafizieren ;-). Achtung: In der Editor-Ansicht werden die Leerzeichen nach dem speichern komischerweise wieder rausgelöscht, in der XML-Ansicht sind sie jedoch vorhanden. Ebenso waren sie nach Aufruf der Datei in der Datenbank noch da.

VG

Hans

**Comment by larifarian** [comment]
Hi,

It seems to me that changing the config file has solved the problem.

Thanks
