### ISSUE TITLE
dist-war build task includes unsigned JARs that overwrite a core JAR (causing a webstart error)

### ISSUE THREAD

**Issue by rvdb** [eXist-db/exist#1614]
### What is the problem
When deploying a WAR build of eXist-3.5.0, an error is thrown: 

> Unsigned application requesting unrestricted access to the system
> Unsigned resource: http://localhost:8888/exist-3.5.0/webstart/jcip-annotations-1.0.jar

I've verified the signatures of all 28 JAR files in the extracted WAR file's `WEB-INF\lib` folder that are listed in exist.jnlp,, and indeed only `WEB-INF\lib\jcip-annotations-1.0.jar` is the sole unsigned one. 

**YET**, I've noticed that the eXist source tree includes multiple copies of `jcip-annotations-1.0.jar`:

- `${exist_home}/lib/core/jcip-annotations-1.0.jar` (+- 5,5 Mb)
- `${exist_home}/extensions/contentextraction/lib/jcip-annotations-1.0.jar` (+- 2,2 Mb)
- `${exist_home}/extensions/betterform/main/lib/jcip-annotations-1.0.jar` (+- 2,2 Mb)

The one at `${exist_home}/lib/core/jcip-annotations-1.0.jar` is being signed by `jnlp-all`; the others aren't. Comparing with the version included in the WAR file, it is clearly one of the **unsigned** ones that ends up being copied there by the `dist-war` build target. 

One dirty workaround is replacing the extracted `WEB-INF\lib\jcip-annotations-1.0.jar` in the WAR tree with the signed `${exist_home}/lib/core/jcip-annotations-1.0.jar` from the eXist source tree.

On further inspection, I've noticed how the generated WAR file contains **all 3 versions** of `jcip-annotations-1.0.jar` in the `WEB-INF\lib` folder, so it makes sense that they eventually will overwrite each other when the WAR file is extracted.

Hence, IMO this rather seems an issue of incorrect file selection during the `dist-war` build task, unintendedly causing an unsigned JAR to be included in the WAR file, than a file signing issue.

![2017-11-13 16_23_52-winzip - exist-3 5 0 zip](https://user-images.githubusercontent.com/223134/32733609-0acd5626-c890-11e7-8f66-1d11d330ac67.png)

### What did you expect
I'd expect the java admin client to start without problems.

### Describe how to reproduce or add a test
I've taken following steps, starting from a freshly installed eXist-3.5.0 version:

1. sign all jar files via `build jnlp-all`
2. build the WAR dist via `build dist-war`
3. deploy the WAR file in a Tomcat servlet container
4. start the Java web client via the dashboard

### Context information
Please always add the following information
- eXist-db-3.5.0 / 12aea86
- Java jdk1.8.0_112
- Windows 7 Professional
- 64 bit
- Tomcat-7.0.50

**Comment by adamretter** [comment]
@rvdb Are you able to send us a PR to correct the issue?
I guess it is somewhere in `build/scripts/dist.xml` in the *target* `dist-war`.

**Comment by rvdb** [comment]
@adamretter I'm not sure how this should be resolved: clearly, during a `dist-war` build all necessary (core and extension) JARs are being copied to the WAR file's `WEB-INF\lib` folder. Yet, if there are duplicates, as in this case, how should they be treated? 

  - don't copy `${lib.extension}` JARs if they are already in `${lib.core}` ?
  - copy and rename `${lib.extension}` JARs if they are already in `${lib.core}` ?

(in both cases I fear my ANTcraft falls short)

**Comment by adamretter** [comment]
> don't copy ${lib.extension} JARs if they are already in ${lib.core} ?

That seems a reasonable option.

A quicker and simpler mechanism might just be to explicitly exclude `jcip-annotations-1.0.jar` from the relevant extension copy steps. You could also exclude any other jars for which you have spotted duplicates too.

**Comment by rvdb** [comment]
Ok, quick and dirty I should be able to do :-). I'll try fo find the time to give it a shot.

**Comment by dizzzz** [comment]
skipping duplicates is the best option..... i'll have a look

**Comment by dizzzz** [comment]
there are a few duplicate files:

- the YAJSW ones we need to keep them there.... there is no workaround
- jcip-annotations-1.0.jar should be just one
- also just one tagsoup-1.2.1.jar is required

./tools/yajsw/lib/core/commons/commons-collections-3.2.2.jar
./lib/core/commons-collections-3.2.2.jar

./tools/yajsw/lib/core/commons/commons-configuration2-2.0.jar
./lib/core/commons-configuration2-2.0.jar

./tools/yajsw/lib/core/commons/commons-vfs2-2.0.jar
./extensions/contentextraction/lib/commons-vfs2-2.0.jar

./extensions/contentextraction/lib/jcip-annotations-1.0.jar
./extensions/betterform/main/lib/jcip-annotations-1.0.jar
./lib/core/jcip-annotations-1.0.jar

./extensions/contentextraction/lib/tagsoup-1.2.1.jar
./extensions/expath/lib/tagsoup-1.2.1.jar

**Comment by dizzzz** [comment]
regarding jcip-annotations things are a bit complex ; the letterform application seems to use a separate classloader, which works a bit interesting, this seems to make it impossible  to use  only one JAR file...
