### ISSUE TITLE
Backup-restore failure : parsing errors

### ISSUE THREAD

**Issue by dizzzz** [eXist-db/exist#1620]
### What is the problem
During a simple backup - restore (no database cleanup in between), some files haven't been restored due to errors reported by the XML parser:

```
Exception: ------------------------------------
Exception: ------------------------------------
Problems occured found during restore:

WARN: Failed to restore resource 'repo.xml'
from file '/path/eXist-backup.zip#db/apps/shared-resources/repo.xml'.
Reason: Failed to invoke method parse in class org.exist.xmlrpc.RpcConnection: org.xml.sax.SAXParseException: Element type "repo:meta" must be followed by either attribute specifications, ">" or "/>".

WARN: Failed to restore resource 'build.xml'
from file '/path/eXist-backup.zip#db/apps/webstart/build.xml'.
Reason: Failed to invoke method parse in class org.exist.xmlrpc.RpcConnection: org.xml.sax.SAXParseException: The string "--" is not permitted within comments.

WARN: Failed to restore resource 'repo.xml'
from file '/path/eXist-backup.zip#db/apps/monex/repo.xml'.
Reason: Failed to invoke method parse in class org.exist.xmlrpc.RpcConnection: org.xml.sax.SAXParseException: Element type "permissions" must be followed by either attribute specifications, ">" or "/>".

WARN: Failed to restore resource 'repo.xml'
from file '/path/eXist-backup.zip#db/apps/eXide/repo.xml'.
Reason: Failed to invoke method parse in class org.exist.xmlrpc.RpcConnection: org.xml.sax.SAXParseException: Element type "permissions" must be followed by either attribute specifications, ">" or "/>".
```

There is need a `--` in comments (issue 2), and all of the `repo.xml` files contain a root element with an attribute which name starts with an `#` character:

```xml
<repo:meta xmlns="http://exist-db.org/xquery/repo" 
    xmlns:repo="http://exist-db.org/xquery/repo" 
   #unknown="http://exist-db.org/xquery/repo">
    <repo:description>Shared resources used by other apps</repo:description>
    <repo:author>Wolfgang Meier</repo:author>
    <repo:website>https://github.com/eXist-db/shared-resources</repo:website>
    <repo:status>alpha</repo:status>
    <repo:license>GNU-LGPL</repo:license>
    <repo:copyright>true</repo:copyright>
    <repo:type>library</repo:type>
    <repo:target>shared-resources</repo:target>
    <repo:prepare/>
    <repo:finish/>
    <repo:permissions user="admin" group="dba" mode="0775"/>
```

### What did you expect
A restore should work flawlessly 

### Describe how to reproduce or add a test
In the admin client, make a backup of a database (no special apps needed) and directly do restore from the backup.zip file.

### Context information
Please always add the following information
- eXist-db version : latest dev
- Java version (Java8u151)
- Operating system (MacOs)
- 64 bit
- Any custom changes in e.g. conf.xml

**Comment by adamretter** [comment]
The `repo.xml` file that you pasted above is not well-formed XML because of the `#unknown="http://exist-db.org/xquery/repo"`.

Is the `repo.xml` actually present in the database? And if so, how did that happen? It should not be possible to store invalid XML.

**Comment by dizzzz** [comment]
Yes it is stored in the database....

**Comment by dizzzz** [comment]
I’ll study further

**Comment by pherk** [comment]
- seems to be the same issue as reported in #1573 and #1587

**Comment by dizzzz** [comment]
![image](https://user-images.githubusercontent.com/1700062/33006886-6779d516-cdcc-11e7-9748-89174093b80c.png)

**Comment by dizzzz** [comment]
@pherk indeed but I did not no a repair  ; I'l mark this as a duplicate, thnx

**Comment by dizzzz** [comment]
@adamretter it is actually a problem, we need to address this ; interesting that 'something' allows to write invalid XML


Note: there are 2 issues: the interesting "double dash" and the #unknown attribute

**Comment by adamretter** [comment]
@dizzzz I have heard from @duncdrum and @wolfgangmm that your steps to reproduce this do not cause the issue for them. Can you tell me did you start from a clean database, or did you have an existing database?

**Comment by dizzzz** [comment]
I’ll follow up, but I started with a clean database....

**Comment by dizzzz** [comment]
Ok confirmed:  how to reproduce:

- clean checkout of git (4b4a8a3fd)
- start database with ./bin/startup.sh
- open eXide
- open '/db/apps/shared-resources/repo.xml'
- root element contains attribute with name starting with "#"

```
\21 Nov 2017 19:03:57,579 [main] INFO  (JettyStart.java [run]:146) - [eXist Version : 3.6.0-SNAPSHOT] 
21 Nov 2017 19:03:57,579 [main] INFO  (JettyStart.java [run]:147) - [eXist Build : 201711211902] 
21 Nov 2017 19:03:57,579 [main] INFO  (JettyStart.java [run]:148) - [Git commit : 4b4a8a3fd] 
21 Nov 2017 19:03:57,579 [main] INFO  (JettyStart.java [run]:150) - [Operating System : Mac OS X 10.13.1 x86_64] 
21 Nov 2017 19:03:57,579 [main] INFO  (JettyStart.java [run]:151) - [log4j.configurationFile : file:///xxxxxxxx/exist/log4j2.xml] 
21 Nov 2017 19:03:57,583 [main] INFO  (JettyStart.java [run]:152) - [jetty Version: 9.4.6.v20170531] 
```

**Comment by adamretter** [comment]
@dizzzz Okay so some good news. This is really really easy to reproduce. I have also written a test narrowing it down to an issue in the Memtree DOM (which I likely may have introduced during my DOM improvements) A fix will be coming soon...

**Comment by adamretter** [comment]
@dizzzz Okay so there was an existing DOM bug in eXist-db prior to my DOM improvements (I am comparing against eXist-3.1.0) that meant that the `repo.xml` was not stored correctly, however the Exception would be swallowed in `org.exist.repo.Deployment` :-(

I have first fixed `org.exist.repo.Deployment` so that it doesn't swallow significant errors. I am now looking into fixing the underlying DOM issue (which doesn't seem to be related to my DOM improvements).

**Comment by adamretter** [comment]
@dizzzz For the comments issue, it is reported in your log in '/path/eXist-backup.zip#db/apps/webstart/build.xml'. Where do I find a XAR that contains `webstart/build.xml`. Do I just build one from github.com/trundler/existdb-webstart?

**Comment by dizzzz** [comment]
Hmmmm no I cleaned that one. I’ll have a look

**Comment by dizzzz** [comment]
i cannot reproduce it for this configuration:

> 29 Nov 2017 18:37:13,617 [main] INFO  (JettyStart.java [run]:146) - [eXist Version : 3.6.0-SNAPSHOT] 
> 29 Nov 2017 18:37:13,617 [main] INFO  (JettyStart.java [run]:147) - [eXist Build : 201711291834] 
> 29 Nov 2017 18:37:13,617 [main] INFO  (JettyStart.java [run]:148) - [Git commit : 4b4a8a3fd] 

test procedure (1)
- create XAR file in eXide
- download XAR file
- unzip file
- add XML file with content comments with double dash
- build XAR file (run ant)
- deploy XAR via package manager

**Comment by adamretter** [comment]
@dizzzz Does this mean the issue is solved or not? Sorry I am not quite sure I understand your explanation.

**Comment by dizzzz** [comment]
For me it is solved as I cannot reproduce it (anymore). 

It looks like the package installer correctly does not install faulty xml documents.

(Side note: should the package installer abort the xar install when a failure occurs?)
