### ISSUE TITLE
general comparison to empty sequence sometimes raises an error

### ISSUE THREAD

**Issue by telic** [eXist-db/exist#1639]
### What is the problem

eXist sometimes raises a type error when making a general comparison to an empty-sequence on the right-hand side (eg. `current-date() = ()`). It never raises this error if the empty sequence appears on the left-hand side (eg. `() = current-date()`).

This appears to be due to inconsistent practice in the implementation of the `compareTo(Collator, Comparison, AtomicValue)` method in each of the `org.exist.xquery.value` classes. Some explicitly check for `.isEmpty()` at the start, but `BooleanValue`, `AbstractDateTimeValue`, and `BinaryValue` do not (and there may be others that I missed).

### What did you expect

A general comparison to the empty sequence should always return `false()`, since no "[pair of atomic values](https://www.w3.org/TR/xquery-31/#id-general-comparisons)" exists.

### Context information
- eXist-db 3.6.0 (build 201711271542) / ceaab01
- Java 1.8.0_152-b16
- MacOS 10.13.1
- 64 bit

**Comment by dizzzz** [comment]
<img width="835" alt="isempty" src="https://user-images.githubusercontent.com/1700062/33529936-cb2cc086-d877-11e7-81c5-ddddb413b2f5.png">

**Comment by dizzzz** [comment]
I think we can fix this in the GeneralCOmparison : 

org/exist/xquery/GeneralComparison.java:1094

```java
 default: {
                    // If right value is () always return false
                    return( rv.isEmpty() ? false : lv.compareTo( collator, relation, rv ) );
                }
```
