### ISSUE TITLE
XQ-3.1 import-module() with support for function-lookup()

### ISSUE THREAD

**Issue by cmisztur** [eXist-db/exist#164]
I am trying to get a import-module() function added into XQuery 3.1 at the moment. Sometime ago I managed to convince them to add function-lookup, but they said that import-module would have to wait for the future... well now it is the future ;-)

Personally I suspect that there is a bug/deficiency with the implementation of util:import-module/fn:function-lookup.

> I can’t exactly remember why, but I think function-lookup cannot see a 
> module imported dynamically via util:import-module. In the templating 
> module, I use the following approach, which has the advantage of 
> avoiding the non-standard util:import-module function: I have a main 
> module, which knows all modules to be used by the application and 
> imports them. In this main module, I create an inline function which 
> calls function-lookup. This inline lookup function is passed to the 
> templating module as a function parameter. Because of the closure, the 
> inline function will be in the context of the module in which it was 
> created and has access to any module imported there.

**Comment by line-o** [comment]
Does exist implement [fn:load-xquery-module](https://www.w3.org/TR/xpath-functions-31/#func-load-xquery-module)?

**Comment by joewiz** [comment]
@line-o Yes. See http://exist-db.org/exist/apps/fundocs/view.html?uri=http://www.w3.org/2005/xpath-functions#load-xquery-module.1.

**Comment by joewiz** [comment]
@cmisztur I think the `fn:load-xquery-module`, supported for some time now in eXist, should do the trick. Thanks for proposing this to the WG! Please open a new issue if you have any problems with the implementation of this function.
