### ISSUE TITLE
DOMFile has exposed its cache without synchronization

### ISSUE THREAD

**Issue by alebastrov** [eXist-db/exist#1652]
### What is the problem
DOMFile.java has field **dataCache** which is used internally as 
~~~
public synchronized final void addToBuffer(DOMPage page) {
        dataCache.add(page);
    }
~~~
and externally as
~~~
protected final Cache getPageBuffer() {
        return dataCache;
    }
~~~
I did not analize inheritances but getPageBuffer() is used, however in NodeIterator.java it is doing
without any synchronization. Looks like there is an error we've faced with (OOM error, dataCache is broken and cannot be freed).

The valid behavior is not to expose cache outside, we have to remove method
~~~
protected final Cache getPageBuffer() ...
~~~
and insert
~~~
public synchronized  final Cache deletePageBuffer(DOMPage page) {
       dataCache.remove(page);
    }
~~~
After that we have to invoke according methods to add/remove objects in cache.

### What did you expect
Sufficient syncronization on cache

### Describe how to reproduce or add a test
Impossible, just analizing source code

### Context information
 eXist-db any version 
Java8u121
Windows 10, 64 bit

**Comment by adamretter** [comment]
@alebastrov I think this is a non-issue in practice.

It looks to me like the `synchronized` keyword on `DOMFile#addToBuffer(DOMPage)` is redundant. All interactions with DOMFile should take place under a lock, which is available with `DOMFile#getLock()`.

If you take a look you will see that `NodeIterator.java` uses that lock. You will also see that `DOMTransaction` in `NativeBroker` uses that Lock too.

I will close this ticket for now, as I don't see a problem. However, if you find a code path where the lock is not used when reading or writing DOMFile then that is a bug, feel free to comment here and re-open the ticket.

**Comment by alebastrov** [comment]
@adamretter  In that case synchronized keyword should be removed in order not to add mess
