### ISSUE TITLE
AST "unexpected end of subtree" error with map postfix lookup

### ISSUE THREAD

**Issue by joewiz** [eXist-db/exist#1655]
### What is the problem

When filtering a map entry with a postfix lookup, an error is thrown if the postfix lookup expression does not come first in the predicate.

### What did you expect

I expected a postfix expression to be valid regardless of its position in a predicate.

### Describe how to reproduce or add a test

The following query triggers the error:

```xquery
xquery version "3.1";

let $map := map { "name": "mike" }
return
    $map["mike" eq ?name]
```

BaseX and Saxon both return the expected result without error:

```xquery
map { "name": "mike" }
```

eXist returns the following error:

`Cannot compile xquery: exerr:ERROR <AST>:0:0: unexpected end of subtree`

eXist is able to complete the query if the postfix lookup is performed first in the predicate:

```xquery
xquery version "3.1";

let $map := map { "name": "mike" }
return
    $map[?name eq "mike"]
```

### Context information

- eXist-db version + Git Revision hash: eXist 3.7.0-SNAPSHOT+9091c3032
- Java version: Oracle JDK 1.8.0_152
- Operating system: macOS 10.13.1
- 32 or 64 bit: 64 bit
- Any custom changes in e.g. conf.xml: none

**Comment by joewiz** [comment]
This bug is still present in eXist 5.0.0.

**Comment by line-o** [comment]
The same error is thrown with this `(map {"f": 1}, map {"f": 2}) ! ?f`
