### ISSUE TITLE
Update conf.xsd to allow unschedule-on-exception

### ISSUE THREAD

**Issue by joewiz** [eXist-db/exist#1657]
### What is the problem

conf.xml rejects `job/@unschedule-on-exception` as invalid, while this attribute is described in [conf.xml](https://github.com/eXist-db/exist/blob/develop/conf.xml.tmpl#L497-L500) and the documentation article on [Application Server Configuration](https://exist-db.org/exist/apps/doc/configuration.xml#D2.4.8.15.14) article in the documentation:

> Boolean: yes/true, no/false. Default: true. If true and an exception is encountered then the job is unscheduled for further execution until a restart; otherwise, the exception is ignored.

In preparing a PR, I'm unsure whether to encode this so-called boolean as `type="xs:boolean"` or `type="yes_no"` - I see more of the latter than the former in conf.xsd - or a third possibility, I suppose, `type="xs:string"`?

### What did you expect

All documented options to be allowed by the schema.  

I can submit a PR fixing this - just wanted to be sure which value to choose?

### Context information

- eXist-db version + Git Revision hash: eXist 3.7.0-SNAPSHOT+9091c3032
- Java version: Oracle JDK 1.8.0_152
- Operating system: macOS 10.13.1
- 32 or 64 bit: 64 bit
- Any custom changes in e.g. conf.xml: none

**Comment by adamretter** [comment]
@joewiz Having had a quick look at the code it seems that either `yes/no` or `true/false` are allowable. As such if we generally use `yes/no` I would suggest sticking with that.

https://github.com/eXist-db/exist/blob/develop/src/org/exist/scheduler/JobConfig.java#L80
https://github.com/eXist-db/exist/blob/develop/src/org/exist/util/Configuration.java#L1619
