### ISSUE TITLE
eXist DB and Zookeeper integration, or any other HA feature

### ISSUE THREAD

**Issue by akram** [eXist-db/exist#1681]
Hi all,

The eXist-db documentation states that eXists is for now single server, and
that it supports data replication in master-slave mode.

I want to build a Highly-Available cluster for eXist. Is there any
possibility to make the data replication use an elected master ?
The idea behind is to integrate it with zookeeper, unless someone did
already the job.

Do you have any other feedback about eXist in HA architecture ?

**Comment by dizzzz** [comment]
For the replication extension, please use https://github.com/eXist-db/messaging-replication/issues instead.

In the documentation (dit you find it?) you'll read that the replication function is built on top of ActiveMQ. Basically all what is possible with this broker can be done with the extension.

Please read the documentation (wiki) for additional information.

**Comment by akram** [comment]
Hi @dizzzz , the question is more about zookeeper integration than use of replication.
Would you mind reopening the issue to allow further discussion ?
