### ISSUE TITLE
macOS: start issue with java8 (DMG)

### ISSUE THREAD

**Issue by dizzzz** [eXist-db/exist#1685]
### What is the problem
With the latest DMG (v3.6.1) I cannot start eXist-db from the DMG:

![screenshot_11_1_18__21_20](https://user-images.githubusercontent.com/1700062/34845570-9609cebe-f715-11e7-80c2-5b7e96f09d49.jpg)

### What did you expect
I expected eXist-db to start by clicking on the icon.

### Describe how to reproduce or add a test

this should be enough ?
- install JDK9.0.1 
- start application

### Context information
Please always add the following information
- eXist-db version : 3.6.1 (DMG)
- Java version (Java8u151)
- Operating system (MacOs 10.13.2)
-  64 bit
- Any custom changes in e.g. conf.xml : none

for sure I have java8 installed....

![bash_ _139x24_and_new_issue_ _exist-db_exist](https://user-images.githubusercontent.com/1700062/34845737-3a2d2130-f716-11e7-8660-d997bf71e1d8.jpg)

**Comment by adamretter** [comment]
Nothing has changed here for several releases. What is your default `JAVA_HOME`? If it is Java 9, does it work if you switch to Java 8?

**Comment by dizzzz** [comment]
investigating... I removed JDK7....

```
/usr/libexec/java_home -V
Matching Java Virtual Machines (2):
    9.0.1, x86_64:	"Java SE 9.0.1"	/Library/Java/JavaVirtualMachines/jdk-9.0.1.jdk/Contents/Home
    1.8.0_151, x86_64:	"Java SE 8"	/Library/Java/JavaVirtualMachines/jdk1.8.0_151.jdk/Contents/Home
```

.. same result. removing Java9... yields into a working situation indeed :-/

**Comment by adamretter** [comment]
So your conclusion is... that if Java 9 is your default Java, then the installer fails?

**Comment by dizzzz** [comment]
in my .profile i force to use java8 ... but clicking on the icon will launch... with the default java9 JRE maybe? but that does not make sense.... /usr/libexec/java_home returns java9.0.1 for sure

**Comment by dizzzz** [comment]
from the console.app:

```
default	21:43:14.267727 +0100	eXist-JavaAppLauncher	Error launching JVM Runtime ((null)) Relative Path: '/XXXXXXX/eXist-db.app/Contents/PlugIns' (dylib: (null))
  error: This application requires that Java 8 or later be installed on your computer. Please download and install the latest version of Java from www.java.com and try again.
default	21:43:14.302453 +0100	trustd	cert[2]: AnchorTrusted =(leaf)[force]> 0
default	21:43:14.307523 +0100	launchservicesd	CHECKIN:0x0-0xb70b7 2404 org.exist.start.Main
default	21:43:14.413747 +0100	kernel	AGC:: [eXist-JavaAppLau pid:2404 mux-aware] starting, non-mux-aware app count 0 WS-ready 1 switch-state 0 IG FBs 1 EG FBs 0:0 power-state 6 3D idle HDA idle
default	21:43:14.494225 +0100	kernel	Sandbox: fseventsd(62) System Policy: deny(1) file-read-metadata /private/var/folders/sv/f7jcvp391bj_2c0tr0bg_rww0000gn/0/com.apple.LaunchServices.dv
default	21:43:14.494227 +0100	kernel	Sandbox: fseventsd(62) System Policy: deny(1) file-read-metadata /private/var/folders/sv/f7jcvp391bj_2c0tr0bg_rww0000gn/0/com.apple.LaunchServices.dv
default	21:43:14.494245 +0100	kernel	Sandbox: fseventsd(62) System Policy: deny(1) file-read-metadata /private/var/folders/sv/f7jcvp391bj_2c0tr0bg_rww0000gn/0/com.apple.LaunchServices.dv

```

**Comment by duncdrum** [comment]
Yes, I noticed the same behaviour,  exist doesn't like java9 as default JVM
*cough* eXist-db/website#16

**Comment by adamretter** [comment]
Seems to be fixed here - https://bitbucket.org/infinitekind/appbundler/commits/all
