### ISSUE TITLE
empty() removed too early

### ISSUE THREAD

**Issue by pherk** [eXist-db/exist#1707]
### What is the problem
the deprecated and removed empty() is still used, database after rebuild unusable.
I found
- ... modules/persistentlogin/login.xql
- dashboard/plugins/userManager/userManager.xqm

### What did you expect
empty() should be empty-sequence() in base installation

### Context information
- eXist-db 3.7.0-snapshot /23e4077
- Java8u161
- Linux
- 64 bit

**Comment by dizzzz** [comment]
Yes.... the PR requires some PRs for some apps...
