### ISSUE TITLE
eXist 3.4 index use/query optimization 

### ISSUE THREAD

**Issue by Torcsi** [eXist-db/exist#1710]
> Describe exactly what you see (e.g. an output of an XQuery) 
eXist 2.x optimized queries even in case when the query contains a precomputed variable as a source
eXist 3.x seems optimizing only queries if they start with the collection.

A complete study is posted adn accessed by @joewiz, downloadable from [here](http://www.arcdev.hu/temp/eXistDb_3_indexing_problem.pdf)

The issue was discussed in detail under this [issue ](http://www.arcdev.hu/temp/eXistDb_3_indexing_problem.pdf) but it may worth a dedicated one (this). Findings will be quoted in separate comments below.

### In eXist db 3.4

```
declare variable $body_sections := xmldb:xcollection(concat('/db/apps/sls/data/' 
,$lang))/sls:data/sls:sections/sls
...
let $inner_bodies := $body_sections[@uuid=$inner_uuid]/sls:body

```
this is **not optimized.**

```
let $other_body := arc:getB
ody(xmldb:xcollection(concat('/db/apps/sls/data/' 
,$other_lang))/sls:data/sls:sections/sls:section[@uuid=$uuid]/sls:body, $layerLevel, 
$versionDate, $user, $version, $source)

```
this is **optimized**.

### In 2.x both queries are optimized.

**Very complicated code was tested and fine-tuned taking benefit of 2.x speed. The current drop is over 6 times.**

> Describe what you expected to happen. 

Queries should be optimized even if they start from a variable. The current non-optimization is detrimental on performance.

### Describe how to reproduce or add a test
Not obvious; we have no resources for producing an independent test bed. However, the issue seemed to appear for others as well.

When we can make this, we will provide a separate comment.

### Context information
Please always add the following information
- eXist-db 3.4
- Java version Java8uXXX
- Operating system (possibly irrelevant)
- 32 or 64 bit (possibly irrelevant)
- Any custom changes (none)

**Comment by Torcsi** [comment]
Comments of @joewiz 

 The fix is actually what you've effectively done on line 115: do not refer to the collection indirectly via a variable (e.g., $body_sections), but instead refer to collections directly 
(e.g.,
` xmldb:xcollection(concat('/db/apps/sls/data/' ,$lang))/sls:data/sls:sections/sls[@uuid=$inner_uuid]/sls:body). 
`

Perhaps @wolfgangmm can comment on what has actually changed underneath the hood, but it probably has something to do with the query rewriting facility; it seems the query rewriter isn't as good at identifying node sets selected via variable that could benefit from indexes. I would like to be able to use variables to refer to collections, and in some cases I think I still do - there must be a pattern. But much of my code now uses collection() functions rather than variables that point to these nodes. I hope this helps you make the adjustments necessary to move to 3.x; its many other improvements are well worth the cost of making this change.

**Comment by Torcsi** [comment]
My response

We have systematically used the variable to avoid repetitive calculations of the same! especially if the $var (collection) is computed in a complex way, this should be optimized automagically. Surely others meet the same problem...

**Comment by rvdb** [comment]
@Torcsi Do you mean issue https://github.com/eXist-db/exist/issues/873? (The link in your original report is wrong.)

**Comment by Torcsi** [comment]
@rvdb The links should be OK, that discussion was about something else. 
Thanks I have not found the mentioned #873.
Consider this then as **duplication** and as such, I have immediately closed this.

**Comment by rvdb** [comment]
Well, this clearly shows the issue is still there, and causing performance problems for real-life queries. Since the other issue has partly been solved (apart from the performance regression), perhaps it doesn't harm bringing the performance regression for "indirect" queries on the radar again!

**Comment by dizzzz** [comment]
@wolfgangmm  ?
