### ISSUE TITLE
Add support for the xs:dateTimeStamp datatype

### ISSUE THREAD

**Issue by joewiz** [eXist-db/exist#1715]
### What is the problem

eXist supports all datatypes except one: the `xs:dateTimeStamp` datatype. From the XML Schema Datatypes spec:

> all values of dateTimeStamp are required to have explicit time zone offsets and the datatype is totally ordered.

So the following query should return `true()`:

```xquery
exists(fn:timezone-from-dateTime(xs:dateTimeStamp("2011-07-28T12:34:56-08:00")))
```

Instead, eXist returns the following error:

> Cannot compile xquery: exerr:ERROR Type: xs:dateTimeStamp is not defined

Similarly, eXist should complain about the missing explicit timezone offset in `xs:dateTimeStamp("2011-07-28T12:34:56")` but instead raises the error above.

### What did you expect

I expected eXist to support all datatypes defined at https://www.w3.org/TR/xpath-functions-31/#atomic-type-hierarchy and https://www.w3.org/TR/2012/REC-xmlschema11-2-20120405/datatypes.html#dateTimeStamp.

### Describe how to reproduce or add a test

See https://github.com/w3c/qt3tests/blob/master/xs/dateTimeStamp.xml.  This was the source of the sample query above.

### Context information

- eXist-db version + Git Revision hash: 3.7.0-SNAPSHOT develop
- Java version: 1.8.0_152
- Operating system: macOS 10.13.3
- 32 or 64 bit: 64 bit
- Any custom changes in e.g. conf.xml: none

**Comment by joewiz** [comment]
There's actually 3 more unimplemented datatype in eXist: [`xs:NMTOKENS`](https://www.w3.org/TR/xmlschema-2/#NMTOKENS), [`xs:IDREFS`](https://www.w3.org/TR/xmlschema-2/#IDREFS), and [`xs:ENTITIES`](https://www.w3.org/TR/xmlschema-2/#ENTITIES) - which [the XQuery spec](https://www.w3.org/TR/xpath-functions-31/#constructor-functions-for-xsd-list-types) calls "the three built-in list types defined in XML Schema Part 2: Datatypes Second Edition." 

I came across this after reading https://github.com/BaseXdb/basex/issues/1691. I performed Christian's test in eXide and got this error:

> Cannot compile xquery: exerr:ERROR Type: xs:NMTOKENS is not defined

This led me to look up the types above.

**Comment by adamretter** [comment]
So... `xs:dateTimeStamp` is defined in XML Schema 1.1, and is not present in XQuery 1.0. It was introduced in XQuery 3.0.

eXist-db's XQuery implementation internally does not have a good separation between the different versions of XQuery, and you will find several things that are 3+ that will run with a 1.0 declaration and vice-versa.

We could implement the type `xs:dateTimeStamp` very easily, however we would have no good/easy way of saying that it should only be XQuery 3+.
