### ISSUE TITLE
Remove duplicate functions from math-ext module

### ISSUE THREAD

**Issue by joewiz** [eXist-db/exist#1716]
### What is the problem

Since XQuery 3.0, all functions in the [math-ext module](http://exist-db.org/exist/apps/fundocs/view.html?uri=http://exist-db.org/xquery/math&location=java:org.exist.xquery.modules.math.MathModule) are duplicates except for `math-ext:degrees()` and `math-ext:radius()`

### What did you expect

Functions added to the XQuery 3.0 F&O spec in https://www.w3.org/TR/xpath-functions-30/#trigonometry and supported natively by eXist no longer need to be in an extension module. 

The functions in question from the old extension module could be marked as deprecated and removed in a future major version of eXist.

### Describe how to reproduce or add a test

n/a

### Context information

- eXist-db version + Git Revision hash: 3.7.0-SNAPSHOT develop
- Java version: 1.8.0_152
- Operating system: macOS 10.13.3
- 32 or 64 bit: 64 bit
- Any custom changes in e.g. conf.xml: none

**Comment by duncdrum** [comment]
makes sense to me, I think we should start using a `deprecation` label here in the main repo to keep better track of things
