### ISSUE TITLE
eXistdb Page not found, use the dashboard to install  missing application package

### ISSUE THREAD

**Issue by himanshubhargav** [eXist-db/exist#1728]
Thank you for reporting your issue!

To be able to better understand you problem or suggestion, please add as much information as possible to this ticket. When there is no or just little information, it will be too difficult to work on it (and hence we will not be able to solve it)

Please fill in the following sections:

eXistdb Page not found, use the dashboard to install  missing application package
When Log in into exist db, dashboard is not loaded.
![image](https://user-images.githubusercontent.com/36399087/36087856-7bb1defa-0ffa-11e8-87de-169c4ac94bdc.png)

**Comment by dizzzz** [comment]
Please fill in the WHOLE issue template, as a lot of essential information is missing.
