### ISSUE TITLE
inconsistent return of position()

### ISSUE THREAD

**Issue by duncdrum** [eXist-db/exist#1730]
Placeholder issue in case the error is with exist after all:

### Describe how to reproduce or add a test
```xquery
element result {
let $test := element root {
    for $i in 1 to 4
    return
        element item {$i}
}

for $item in $test//item[position() = (. to 3)]
return
   $item }
```
### What is the problem
eXist returns:
```xml 
<result>
    <item>1</item>
    <item>2</item>
    <item>3</item>
</result>
```
vs. Saxon `9.7.0.19-EE` see the [.net fiddle](http://xqueryfiddle.liberty-development.net/948Fn57/4)

```xml
<result>
   <item>1</item>
   <item>2</item>
</result>
```
### What did you expect
Identical outcomes between saxon and eXist. I would have expected the eXist result, but am no longer certain. Changing to `[position() = (1 to 3)]` gives identical results in both (three items) So eXist bug or [Saxon bug](https://saxonica.plan.io/issues/3666)?

### Context information
- eXist-db: `3.6.1`
- Java version: `1.8.0_162`
- Operating system: MacOs 10.13.3

**Comment by dizzzz** [comment]
What is basex reporting? For me, I have no idea what the correct should be.... @wolfgangmm

**Comment by duncdrum** [comment]
Confirmed by M. Kay:
> Looks like one of those bugs that has been there "forever".

We are in the clear over here.

**Comment by dizzzz** [comment]
thnx for consulting mr Kay
