### ISSUE TITLE
Upgrade to 4.0.0, monex disappears, won't reinstall

### ISSUE THREAD

**Issue by bkcsfi** [eXist-db/exist#1733]
### What is the problem
> Describe exactly what you see (e.g. an output of an XQuery) 

I configured a new instance of eXist-4.0.0 in docker and restored a full non-zip backup of a 3.6.1 instance to the new 4.0.0 instance

I noticed that apps dashboard no longer showed monex, but it was still installed and reachable via direct url.  I then followed the steps in the release notes to upgrade the dashboard  and restarted eXist, cleared my browser cache and re-logged in.

Monex is still missing from the dashboard (but still reachable by direct url)

I now have both "eXistdb Packagemanager" and "Package Manager" on the dashboard, though the later fails to launch.  Using the new eXistdb Packagemanager I see only 5 installed packages:

dashboard 1.0.0
exide 2.4.3
eXistdb Packagemanager 4.0.4
existdb-packageservice 1.0.0
Usermanager 0.15.1

I click '+' and choose Monitoring and Profiling for eXist (Monex) verson 0.9.12, click the down-arrow on the right. It says "package has been installed: monex"

exist.log does not in fact show that anything has happened (whereas other installs showed "Retrieving package from http://demo-exist-db .."  

Installing monex does not show "retrieving" nor anything else in eXist.log

Do I need to manually remove the old monex app, then re-install?

### What did you expect

I expect monex to be installed

### Describe how to reproduce or add a test
> Describe how we can can reproduce the problem.

restore an old database with old apps, then try to install new  monex

### Context information
Please always add the following information
- eXist-db version 4.0.0 build 201802141635
- Java version 1.8.0_131
- Operating system - evolvedbinary/exist-db:eXist-4.0.0

**Comment by bkcsfi** [comment]
hmm, I'm also missing the Scheduler app.  The apps I have are Backup, Collections, eXide, eXistdb Packagemanger, existdb-packageservice, Java Admin Client, Package Manager, Shutdown, Usermanager

**Comment by joewiz** [comment]
Did you complete the steps outlined in “Repairing the Package Repository After Restore” https://exist-db.org/exist/apps/doc/backup.xml#D2.4.16.9

**Comment by bkcsfi** [comment]
Hi, thanks for the tip.  I had in fact not done that step.
I've run it now, it produced the output shown below. I've refreshed the browser (cleared cache), monex and scheduler  are still missing. I re-opened the new packagemanger and retried to install monex, same result nothing is retrieved and the progress bar completes very quickly.

```
true()
2
true()
3
true()
4
true()
5
true()
6
true()
7
false()
8
true()
9
true()
10
<repair>
    <package name="http://exist-db.org/apps/existdb-packageservice" restored="true"/>
    <package name="http://exist-db.org/apps/eXide" restored="true"/>
    <package name="http://exist-db.org/apps/monex" restored="true"/>
    <package name="http://exist-db.org/apps/usermanager" restored="true"/>
    <package name="http://exist-db.org/apps/dashboard" restored="true"/>
    <package name="http://exist-db.org/apps/shared" restored="true"/>
    <package name="http://exist-db.org/apps/packagemanager" restored="true"/>
    <package name="http://www.functx.com" restored="true"/>
    <package name="http://xqilla.sourceforge.net/pkg/xqjson" restored="true"/>
</repair>
```

**Comment by joewiz** [comment]
@bkcsfi I'm not sure. Others may have more informed advice. If I were you I'd start over from restoring the instance and do the package repair right away. No guarantee of success. I'm just thinking that it would be helpful to eliminate traces of actions taken on the new instance before the package repair.

**Comment by bkcsfi** [comment]
perhaps related to this, after many hours of work I believe I have reconstructed most of our missing data. I initiated a full backup via the backup app. This appears in eXist.log

```
2018-02-15 00:48:54,660 [qtp180078856-267] INFO  (TriggerSystemTask.java [eval]:85) - Triggering SystemTask: org.exist.storage.ConsistencyCheckTask 
2018-02-15 00:48:54,662 [qtp180078856-267] INFO  (ConsistencyCheckTask.java [execute]:150) - Starting consistency check... 
2018-02-15 00:49:05,241 [qtp180078856-267] ERROR (ConsistencyCheckTask.java [execute]:163) - Errors found: 1 
2018-02-15 00:49:05,242 [qtp180078856-267] ERROR (ConsistencyCheckTask.java [execute]:168) - Fatal errors were found: pausing the consistency check task. 
2018-02-15 00:49:05,242 [qtp180078856-267] INFO  (ConsistencyCheckTask.java [execute]:173) - Finished consistency check 
2018-02-15 00:49:05,243 [qtp180078856-267] INFO  (ConsistencyCheckTask.java [execute]:177) - Starting backup... 
2018-02-15 00:49:05,470 [qtp180078856-267] ERROR (ConsistencyCheckTask.java [error]:246) - EXPORT: Skipping damaged document repo.xml 
2018-02-15 00:50:10,126 [qtp180078856-267] ERROR (ConsistencyCheckTask.java [error]:246) - EXPORT: Found an orphaned document: repo.xml 
2018-02-15 00:50:10,130 [qtp180078856-267] INFO  (ConsistencyCheckTask.java [execute]:184) - Created backup to file: /exist-data/export/full20180215-0049 
2018-02-15 00:50:10,131 [qtp180078856-267] INFO  (ConsistencyCheckTask.java [execute]:187) - Finished backup 
```
I'm surprised to see that there is a corruption issue, as the database has only been restarted 2 or 3 times since it was setup earlier today, each restart was clean, and the data was restored via xmlrpc (not direct db write).

Document repo.xml is not known to me.

the backup report ends with

```
  DOCUMENT: 93000 of 94770
  DOCUMENT: 94000 of 94770
  DOCUMENT: 94770 of 94770
----------------------------------------------
RESOURCE_ACCESS_FAILED:
Failed to access document data
Document ID: 877
```
I also see in the exist.log from 30 minutes ago, about 200 or so of these errors

```
2018-02-15 00:25:23,100 [qtp180078856-332] ERROR (DocUtils.java [getDocumentByPathFromDB]:159) - java.net.URISyntaxException: xmldb URI scheme does not start with xmldb:: resource:org/exist/
xquery/modules/expathrepo 
```

**Comment by adamretter** [comment]
@wolfgangmm as this seems to be Monex related, I think best to make you aware of it

**Comment by duncdrum** [comment]
following the uprade instructions from v3 to v4 seems to have taken care of the immediate issue. if there are further monex related issues please open a ticket in the monex repo, or if this is closed by mistake, reopen issue. thx.
