### ISSUE TITLE
HTTP HEAD returns 400 where HTTP GET returns 200

### ISSUE THREAD

**Issue by windauer** [eXist-db/exist#1745]
### What is the problem
HTTP HEAD request returns "HTTP/1.1 400 Bad Request" where HTTP GET return 200. 

```
✗ curl  -I http://localhost:8080/exist/apps/dashboard/index.html
HTTP/1.1 400 Bad Request
Set-Cookie: JSESSIONID=node02nm59o8zkqlj1wql8mce32czy20.node0;Path=/exist
Expires: Thu, 01 Jan 1970 00:00:00 GMT
Last-Modified: Fri, 23 Feb 2018 09:46:50 GMT
Created: Fri, 23 Feb 2018 09:46:50 GMT
X-XQuery-Cached: true
Content-Type: text/html;charset=utf-8
Content-Length: 4277
Server: Jetty(9.4.8.v20171121)
```

### What did you expect
A HTTP/1.1. 200 OK response for the HTTP HEAD request.

### Describe how to reproduce or add a test
Use `curl` to send HTTP requests against your local (or a remote) eXistdb
* HTTP GET: curl http://localhost:8080/exist/apps/dashboard/index.html
* HTTP HEAD: curl  -I http://localhost:8080/exist/apps/dashboard/index.html

### Context information
Please always add the following information
* eXist-db 4.1.0-SNAPSHOT / d8a366ac1
* Java 1.8.0_144
* MacOs High Sierra
* 64 bit
* no custom changes at all

**Comment by joewiz** [comment]
As this affects all eXist apps whose controller.xql or RESTXQ module do not explicitly support HEAD requests, one solution would be to add handling for HEAD requests in these locations. Is there a different approach?

**Comment by adamretter** [comment]
@windauer This was fixed and tested here - https://github.com/eXist-db/exist/pull/1696

If you don't implement HEAD, then why should HEAD return 200 OK?

**Comment by windauer** [comment]
got it
