### ISSUE TITLE
update insert preceding silently fails since v3.5.0

### ISSUE THREAD

**Issue by craigberry** [eXist-db/exist#1761]
[update_insert_preceding_bug.zip](https://github.com/eXist-db/exist/files/1777843/update_insert_preceding_bug.zip)

### What is the problem

The following statement works in eXist 3.4.1 (and prior) but fails in 3.5.0 through 4.0.0:

```XQuery
let $setid := update insert attribute id {$id} preceding $doc//annotation-item[@temp-id=$temp]/@status
```

See below for full context and reproducer.

### What did you expect

The statement should be inserting an `id` attribute before an existing `temp-id` attribute, and it does this in 3.4 and before but fails to do so in 3.5.0 and later.  When it fails, it fails silently and does not return such that statements following the update insert statement are not reached.

### Describe how to reproduce or add a test

The attached zip file has two files in it:

```
$ unzip -l update_insert_preceding_bug.zip
Archive:  update_insert_preceding_bug.zip
  Length      Date    Time    Name
---------  ---------- -----   ----
      639  03-03-2018 11:32   A00969_annotations.xml
      548  03-03-2018 11:32   testupdate.xql
---------                     -------
     1187                     2 files
```

Create a collection called `testupdate`, load those two files into it, start the remote console in Monex, and then run `testupdate.xql` from eXide.  In 3.4.1 and earlier, the `id` attribute will be successfully inserted and the "after update" message will be printed to the console.

In any failing version of eXist, the update fails silently.  The document it's trying to update is not changed, and the "after update" message never appears on the console.

### Context information

```
$ git describe --long
eXist-4.0.0-0-gcc66ebc3c
```

```
$ java -version
java version "1.8.0_121"
Java(TM) SE Runtime Environment (build 1.8.0_121-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.121-b13, mixed mode)
```

```
$ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.13.3
BuildVersion:	17D102
```

**Comment by algrw** [comment]
Hi all,

I still have an error (NPE) when updating a document (inserting a node following/preceding/into an existing one).

The context is:
eXist-db version 4.2.1 build 201806141356 - Git commit 32550c1
Java version 1.8.0_121
Operating system Windows Server 2008 R2 64 bits

I have the same error in version 5.0.0-RC1.

Attached are the logs and resources zip files.
[updateErrors_logs.zip](https://github.com/eXist-db/exist/files/2105616/updateErrors_logs.zip)
[updateErrors_resources.zip](https://github.com/eXist-db/exist/files/2105617/updateErrors_resources.zip)

To reproduce the issue, create a collection called AGD (/db/AGD) and upload the 2 documents from the resources zip file in it.
Then run the query update.xqy in eXide.

**Comment by duncdrum** [comment]
Yup, I can reproduce this, same error in the logs.

**Comment by algrw** [comment]
I made other tests and it works if I replace 
```
let $xmlInsert := util:parse(concat('<', $rubrCode, ' action="', $action, '">', $rubrVal, '</', $rubrCode, '>'))
let $upd := update insert $xmlInsert following $xmlSelectExist

```
with a proper XML fragment : 
```
let $xmlInsert := util:parse(concat('<dsn><', $rubrCode, ' action="', $action, '">', $rubrVal, '</', $rubrCode, '></dsn>'))
let $upd := update insert $xmlInsert//dsn following $xmlSelectExist

```

**Comment by duncdrum** [comment]
@algrw glad you got it working.
I still think that your original query should have thrown a better error not an npe

**Comment by algrw** [comment]
@duncdrum I agree with you.
But I will modify our queries accordingly. So for me you can close the request.
Thanks a lot

**Comment by adamretter** [comment]
@algrw So the query that you provided is NOT the same query as @craigberry provided. Please do not use the same issue, as these are different issues.

**Comment by adamretter** [comment]
@algrw So the issue is with in-memory document nodes and XQuery Update, your test-case can be condensed to:

empty.xml
```
<empty/>
```

test.xq
```
update insert document { <hello>world</hello> } into doc("/db/test1/empty.xml")/empty
```

I will send a PR.
