### ISSUE TITLE
Are the docs uptodate regarding the nginx-request-uri header?

### ISSUE THREAD

**Issue by funkyfuture** [eXist-db/exist#1765]
The documentation page on [proxying eXist-db](https://exist-db.org/exist/apps/doc/production_web_proxying.xml) shows an example configuration that includes a directive to set the request header `nginx-request-uri`. however, i can neither [find](https://github.com/eXist-db/exist/search?q=nginx-request-uri&type=Code&utf8=%E2%9C%93) any reference in the current code for it, nor could we ever solve a problem by setting this directive.

is this still a relevant information?
if so, i'd propose to expose it more emphasized as it as a non-standard.
if not, it should obviously removed.

**Comment by duncdrum** [comment]
@funkyfuture could you please open an issue in the [documentation repo](https://github.com/exist-db/documentation).  The docs are currently undergoing a major rewrite, so the problem is more likely to get addressed there.

**Comment by funkyfuture** [comment]
moved to https://github.com/eXist-db/documentation/issues/196
