### ISSUE TITLE
UnsupportedOperationException on BinaryValueFromFile#incrementSharedReferences

### ISSUE THREAD

**Issue by wolfgangmm** [eXist-db/exist#1768]
Since b80b97abe8372a05a0e47ab1d37d579e9ea17843, `BinaryValue` has a method `incrementSharedReferences`. It is only implemented by `BinaryValueFromInputStream` while `BinaryValueFromFile` and `BinaryValueFromBinaryString` throw an UnsupportedOperationException. This happens eg. in the following test snippet:

```xquery
let $binData := file:read-binary("/Users/wolfgang/Source/eXist/develop/VERSION.txt")
return
    element { "root" } {
        "bla"
    }
```

Because `incrementSharedReferences` can obviously be called on those classes, it should not just throw an exception but rather do nothing. Commenting out the `throw` fixes the issue.

**Comment by pherk** [comment]
should reference #1740
