### ISSUE TITLE
Permissions incorrect in Java admin tool Properties

### ISSUE THREAD

**Issue by joewiz** [eXist-db/exist#179]
With multiple files selected in the Java admin client, opening the Properties window always shows the permissions for the selected files as rw-rw-rw-, regardless of the actual permissions of the selected files. 

![screen shot 2014-03-27 at 8 58 12 am](https://cloud.githubusercontent.com/assets/59118/2537402/f84cfcd2-b5af-11e3-9d0d-303c6e9e6c86.png)

Notice here that the original files are rw-r--r--, but the Java admin client shows the permissions as rw-rw-rw-.  

A better approach would be to pick up the actual properties of the selected items. This should be straightforward if the properties are identical. If not identical, then it would make sense to display the overlapping set of properties. Even better, some UIs allow for a "gray dash" mark over the property checkbox that are not common across all the items; then the user can click once to turn all on, again to turn all off, or not at all to leave the original properties unchanged. I'm not sure if this UI element is available to the Java admin client though.

**Comment by duncdrum** [comment]
@joewiz there were some updates with respect to JAC can you please confirm with the latest develop, thx.

**Comment by joewiz** [comment]
@duncdrum Yes, the problem is still present in the latest develop.

**Comment by adamretter** [comment]
@joewiz What would you suggest it should do? If you have multiple files, there could be multiple differing permissions?

**Comment by joewiz** [comment]
@adamretter See the last paragraph of my original post for my suggestion. I'd start with not making up values :-) Then for the cases of differing values for a field, I believe the UI term for what I describe is an "indeterminate" state for a checkbox - I also see the term "TristateCheckBox" used. Some way to indicate that there are multiple values and you've got to choose one or leave existing non-identical values unchanged.

**Comment by joewiz** [comment]
This issue is still present in eXist 5.0.0 Java Admin Client.
