### ISSUE TITLE
Java9/10/... installation failure (on macOS and others)

### ISSUE THREAD

**Issue by duncdrum** [eXist-db/exist#1792]
### What is the problem
Starting exist via GUI results in 
![screen shot 2018-03-29 at 13 09 08](https://user-images.githubusercontent.com/6205362/38086180-ac9fbef2-3353-11e8-9d23-7b101b11e0ba.png)
 

### What did you expect
exist-db to start

### Describe how to reproduce or add a test
make sure that java 9 is in stalled and that:
```bash
echo $JAVA_HOME
/Library/Java/JavaVirtualMachines/jdk-9.0.4.jdk/Contents/Home
```

### Context information
Please always add the following information
- eXist-db version 4.0.0
- Java version 9.0.4
- Operating system MacOs
- 64 bit

**Comment by duncdrum** [comment]
@adam clicking the app icon in the aopp folder, ie. not starting via cli

**Comment by wolfgangmm** [comment]
@duncdrum The GUI starts ok if you launch from the command line, so it must be an issue with the bundled app. Indeed we call appbundler with

```xml
<bundleapp jvmrequired="1.8"
```

in `build/scripts/macosx.xml`. Could you check if it works for you if you change this setting?

**Comment by duncdrum** [comment]
This seems to be whats causing the problem, I'm running into other errors when trying to `build.sh`. I ll try to debug and report back before the end of the week

**Comment by adamretter** [comment]
So `jvmrequired=1.8` should mean Java 8 or later. It looks like this is relevant - https://bitbucket.org/infinitekind/appbundler/pull-requests/48/workaround-for-java-9/diff I will do some digging and make sure it works for Java 10 too.

**Comment by duncdrum** [comment]
@adam for me the following is happening:
```
java version "10.0.1" 2018-04-17
Java(TM) SE Runtime Environment 18.3 (build 10.0.1+10)
Java HotSpot(TM) 64-Bit Server VM 18.3 (build 10.0.1+10, mixed mode)
halmob03s-MBP:~ HALmob$ echo $JAVA_HOME
/Library/Java/JavaVirtualMachines/jdk-10.0.1.jdk/Contents/Home
halmob03s-MBP:~ HALmob$ /Applications/eXist-db.app/Contents/MacOS/eXist-JavaAppLauncher
2018-04-19 13:23:24.748 eXist-JavaAppLauncher[2558:13545] NSString *findJavaDylib(NSString *, _Bool, _Bool, _Bool, _Bool) Searching for a JRE.
2018-04-19 13:23:24.749 eXist-JavaAppLauncher[2558:13545] NSString *findJREDylib(int, _Bool, _Bool) JRE search exception: 'launch path not accessible'
2018-04-19 13:23:24.818 eXist-JavaAppLauncher[2558:13545] NSString *findJavaDylib(NSString *, _Bool, _Bool, _Bool, _Bool) No matching JRE or JDK found.
2018-04-19 13:23:24.818 eXist-JavaAppLauncher[2558:13545] int launch(char *, int, char **) Launchpath: (null)
2018-04-19 13:23:24.821 eXist-JavaAppLauncher[2558:13545] int launch(char *, int, char **) Error launching JVM Runtime ((null)) Relative Path: '(null)' (dylib: (null))
  error: This application requires that Java 8 or later be installed on your computer. Please download and install the latest version of Java from www.java.com and try again.
```

**Comment by dizzzz** [comment]
hmmmm does java9 work for you ? I have a dejavu....  note the difference in how the java version is reported. maybe the internal tokenizer does not recognize the new version pattern.... or does not allow two numbers for the main version :-) 

```
java version "1.8.0_161"
Java(TM) SE Runtime Environment (build 1.8.0_161-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.161-b12, mixed mode)
```

vs

```
java version "9.0.4"
Java(TM) SE Runtime Environment (build 9.0.4+11)
Java HotSpot(TM) 64-Bit Server VM (build 9.0.4+11, mixed mode)
```

**Comment by duncdrum** [comment]
@dizzz nope tried with java 9 with the same results. Just posted the java 10 result, since it's what adam was using. I m pretty sure if it works with 9 it will work with 10.

**Comment by dizzzz** [comment]
ah right... i missed this, (how?)

**Comment by duncdrum** [comment]
@joewiz superseded by #1847

**Comment by joewiz** [comment]
This is now the issue for tracking the issues running eXist installed via the official installer under Java 9/10

**Comment by adamretter** [comment]
Is this fixed on 4.3.0?

**Comment by duncdrum** [comment]
@adamretter  \o/
![screen shot 2018-07-07 at 10 08 25](https://user-images.githubusercontent.com/6205362/42408495-c483e430-81cd-11e8-8c45-08de0fa2bb61.png)

I would suggest updating the hombrew dependency for the next RC

**Comment by adamretter** [comment]
@duncdrum I am not sure I follow. How is this related to Homebrew?

**Comment by duncdrum** [comment]
@adamretter like this [depends_on_java '8'](https://github.com/Homebrew/homebrew-cask/blob/abb9dc1f1e7d76f3b8bebe7ad2fa099006098043/Casks/exist-db.rb#L15)

**Comment by adamretter** [comment]
@joewiz what do you think we should do about that?

**Comment by joewiz** [comment]
Agreed, if we are compatible with the current stable release of Java, then we should update the dependency declaration in homebrew from `java8` to `java` - across our various casks, exist-db, exist-db-nightly, and, when RC2 comes out, exist-db-rc.

**Comment by duncdrum** [comment]
and it is back both java and exist installed via homebrew
macOS `10.14`
with exist-db `4.4.0` and just 
`java version "10.0.2" 2018-07-17`

**Comment by joewiz** [comment]
@duncdrum Judging by the build date, were you using 4.4.0 (release) via DMG installer? Or a local build? What method of starting eXist? Also, which cask did you use to install the version java that gave you the problem - `java`, `java10`?

**Comment by duncdrum** [comment]
@joewiz as I meant to say installed via:
```bash
brew cask reinstall exist-db
```

java was installed way back when via
```
brew cask install java
```

At the time this meant Java10,  I have since then postponed the upgrade to 11. 
There were no other JVMs on my system, which used to work with exist `4.3.1` installed in the same manner, but not with `4.4.0`.

**Comment by joewiz** [comment]
What method of starting eXist?

**Comment by duncdrum** [comment]
GUI (clicking on exist-db icon in application folder)
