### ISSUE TITLE
Cannot install apps as 'admin'

### ISSUE THREAD

**Issue by dizzzz** [eXist-db/exist#1832]
### What is the problem
When attempting to install a XAR file via the package manager, the message "Permission Denied. You must be member of the dba group"

<img width="503" alt="dashboard" src="https://user-images.githubusercontent.com/1700062/38780440-715373f8-40d6-11e8-95fa-a1eef979eaaa.png">

### What did you expect
Being admin, install should be no problem installing a XAR

### Describe how to reproduce or add a test
- clean clone, build, start db
- open package manager, try to install e.g. the documentation app.

### Context information

- eXist-db version : 4.1-snapshot // b66fade3cb4598b0ee7f06d62c05fd2bb623e6d3 
- Java version (e.g. Java8u121) : java8U161
- Operating system (Windows 7, Linux, MacOs) : macOS
- 32 or 64 bit : 64 bit
- Any custom changes in e.g. conf.xml : none

**Comment by joewiz** [comment]
When you opened the package manager, you were prompted to authenticate. Could you specify whether you checked the "remember me" box or not? And could you try the opposite option and see if that avoids the permission denied error?

**Comment by dizzzz** [comment]
yes I checked the remember-me box. if I'd not select, the package manager does not open at all :-(

(this is a second serious issue)

**Comment by joewiz** [comment]
I can reproduce this error if I check the remember me box. But if I leave the remember me box unchecked, the package manager does open for me and lets me install apps. Could you log out from Dashboard, click on Package Manager, enter your credentials without checking the remember me box, and see if you're able to install packages? This works for me.

**Comment by dizzzz** [comment]
thnx @joewiz you are right !

**Comment by joewiz** [comment]
@JoernT Is there any reason you can think of that we should keep the "remember me" checkbox in the "classic" dashboard? It seems to me to only cause problems such as @dizzzz identified here. Shall I remove it and re-release?

**Comment by joewiz** [comment]
@JoernT @dizzzz I've submitted a PR implementing this workaround to the problem (originally reported in https://github.com/eXist-db/dashboard/issues/44), for your review: https://github.com/eXist-db/dashboard/pull/64. If you review and merge this, I'd be happy to prepare a new release for inclusion in eXist 4.1.0.
