### ISSUE TITLE
AppVeyor fails to build PRs

### ISSUE THREAD

**Issue by adamretter** [eXist-db/exist#1834]
When building `HEAD` of the `develop` branch, AppVeyor does a git clone to `C:\projects\exist`.

However, it seems something has changed at AppVeyor where PRs (and probably other branches) and cloned to `C:\project\exist-xxxxx` where `xxxxx` is some sort if unique identifier.

Unfortunately for reasons unknown to me, eXist requires you to set an `EXIST_HOME` variable, for our AppVeyor build this is set to `C:\projects\exist` in our `appveyor.yml`. We have two options:

1. Quick fix. Modify `appveyor.xml` to use some sort of build environment variable set by AppVeyor (if available) for EXIST_HOME.
2. Remove our dependency on the environment variable `EXIST_HOME`. This should be possible as this requirement is pretty unique to eXist-db, there are many other projects, databases included, which don't need such a fixed path.

**Comment by duncdrum** [comment]
removing EXIST_HOME would be for 5.0.0? I would welcome its demise, despite having to rewrite the docs :)

**Comment by dizzzz** [comment]
EXIST_HOME ... is used by the Configurator class no?

**Comment by adamretter** [comment]
@dizzzz Sure, probably a bunch of other places too - no reason why we can't detect it from the startup script that is executed by the OS though.

**Comment by dizzzz** [comment]
Your latest PR is about setting JAVA_HOME right?

**Comment by dizzzz** [comment]
@ljo please step in here please

**Comment by adamretter** [comment]
@dizzzz Nope. It sets EXIST_HOME and also adds a second Java version build. Also can you ask about the PR in the PR, so things don't get mixed.

I have opened a separate issue for EXIST_HOME here https://github.com/eXist-db/exist/issues/1836
