### ISSUE TITLE
There is no support for building a docker image on windows?

### ISSUE THREAD

**Issue by pvillads** [eXist-db/exist#1840]
I need to create a new docker image, since the memory allocation for the java VM is inadequate for the number and size of documents I need to store.

I thought this would be easy, given that the dockerfile is published, but it is only possible to do this on a Linux distro. If I try to do this with the bash shell that is included with windows, I get a series of errors:

```
bash build.sh eXist-4.1.0-minimal
build.sh: line 2: $'\r': command not found
build.sh: line 20: $'\r': command not found
: invalid option1: set: -
set: usage: set [-abefhkmnptuvxBCHP] [-o option-name] [--] [arg ...]
build.sh: line 23: $'\r': command not found
build.sh: line 25: $'\r': command not found
build.sh: line 30: $'\r': command not found
build.sh: line 34: syntax error near unexpected token `$'{\r''
'uild.sh: line 34: `exit_with_usage() {
```

### What is the problem
There is no support for building a modified image on windows. 

### What did you expect
I expected this to be readily available. If not, then please provide a way to change the java VM memory allocation at runtime through a parameter.

### Describe how to reproduce or add a test
git clone https://github.com/evolvedbinary/docker-existdb.git
cd docker-existdb
bash build.sh eXist-4.1.0-minimal

### Context information
Please always add the following information
exist-4.1.0 / version 2.16.1.windows.4
Java 1.8.0_161
windows 10, 64 bit

**Comment by grantmacken** [comment]
Have you tried to override the dockerfile 'entrypoint' passing the required
params to java on 'docker run' .

**Comment by grantmacken** [comment]
Hi adam,
I have just taken look at the docker image code. I don't use Windows
anymore, but i know it has docker support. I don't know about Windows
support for sed, bash etc.
Anyway the work around is to multistage in your dockerfile
In your dockerfile start FROM a minimal image that supports the script you
use. COPY over the script and then RUN the script in the container you
started from. Then start FROM again ...
I do this in
https://github.com/grantmacken/alpine-eXist
In my dockerfile I also set the workingdir which allow a simple entrypoint
with no CMD.

**Comment by dizzzz** [comment]
> "bash shell that is included with windows" -
What do do you mean? which bash?

**Comment by duncdrum** [comment]
@adamretter I think this should be moved to the evolvedbinary repo

**Comment by adamretter** [comment]
@grantmacken Unfortunately we are using the gcr.io images which are so minimal I doubt it is possible to run any sort of script in them, they really only support running the java executable.

**Comment by adamretter** [comment]
@pvillads We don't currently provide support for building the images on Windows. If you wish to do so, it is just a matter of porting the bash files to either Windows Batch or Powershell. If you wish to do so, please send us a PR with your improvements.
