### ISSUE TITLE
import statements are (wrongly) inherited from the main XQuery script

### ISSUE THREAD

**Issue by rvdb** [eXist-db/exist#1854]
### What is the problem
In eXist, XQuery modules that have been imported in a main XQuery script seem to inherit the main script's import statements, and can refer to each other, even though they don't import each other.

Take, for example, following main XQuery scripts:

- main.xq:

      import module namespace import1="import1" at "import1.xqm";
      import module namespace import2="import2" at "import2.xqm";
      $import1:string

- import1.xqm:

      module namespace import1="import1";
      (: note how we don't import "import2.xqm" here, but just declare the "import2" namespace :)
      declare namespace import2="import2";
      declare variable $import1:string := $import2:string;

- import2.xqm:

      module namespace import2="import2";
      declare variable $import2:string := "a variable in the import2 module";

When `main.xq` is executed with eXist, the value of `$import2:string` is returned:

    a variable in the import2 module

Yet, this is an invalid XQuery: since `import1.xqm` just declares the "import2" namespace without actually importing the `import2.xqm` module, the `$import2:string` variable shouldn't be accessible from `import1.xqm`, and an XQuery compilation error should be thrown. Instead, eXist seems to make `import1.xqm` inherit the `import module namespace import2="import2" at "import2.xqm";` statement from the main XQuery script. Indeed, removing it from `main.xq` makes eXist throw the (expected) error.

This illustrates that eXist seems to interpret importing rules too lax.

### What did you expect
I would expect eXist to throw a XQuery compilation error, as does Saxon:

    Error on line 5 of import1.xqm:
      XPST0008: Variable $import2:string has not been declared
    Error on line 4 column 1 of main.xq:
      XPST0008: Static errors were reported in the imported library module
    Static error(s) in query

### Describe how to reproduce or add a test
Copy the XQuery scripts mentioned above and included in this file ([import-test.zip](https://github.com/eXist-db/exist/files/1974344/import-test.zip)) and execute them with eXist. It makes no difference whether the files are stored on the file system or in the database.

### Context information
- eXist-db version + Git Revision hash: eXist-db 4.1.0 /  919514c68 
- Java version: Oracle JDK 1.8.0_172-b11
- Operating system: Windows 7
- 32 or 64 bit: 64 bit
- Any custom changes: none

**Comment by dizzzz** [comment]
from the spec:

'''
Implementations may provide mechanisms allowing the target namespace URI to be used as input to a process that delivers the module as a resource, for example a catalog, module repository, or URI resolver.
'''

I guess that if in an xquery already a module location is defined, it can be re-used during the whole lifespan of a query.....

and : https://www.w3.org/TR/xquery-30/#id-module-handling-cycles

**Comment by rvdb** [comment]
Ah, thanks for clarifying and deciphering that spec snippet for me, @dizzzz :-).

Apparently, I've based my expectations too easily on the Saxon validation output in Oxygen, which does not seem to support this re-use of imported modules. Interestingly, this made me assume that XSLT required such explicit import statements in each submodule as well, but that isn't the case either: with an XSLT version of the XQuery scripts from my initial post, Saxon issues a warning if a submodule imports another submodule that had been imported by the main stylesheet already:

    import2.xsl is included or imported more than once. This is permitted, but may lead to errors 
    or unexpected behavior

So, it's rather weird that import resolution seems to differ between Saxon-XSLT and Saxon-xQuery, but that's a whole different issue, completely unrelated to eXist.

Apologies for raising this non-issue, then, I'll close it right away!
