### ISSUE TITLE
"Unsigned application requesting unrestricted access to system" error when launching exist.jnlp

### ISSUE THREAD

**Issue by lguariento** [eXist-db/exist#1867]
### What is the problem
> On OSX 10.11.6, when launching the Java Admin Client locally, I get this error:

Unsigned application requesting unrestricted access to system
Unsigned resource: http://myip:8080/webstart/jcip-annotations-1.0.jar

### What did you expect
> I'd expect to see the Admin Client.

### Context information
Please always add the following information
- eXist-db 4.1.0
- Java 1.8.0_152-b16
- CentOS 7
- 64 bit

**Comment by joewiz** [comment]
Could you clarify your OS? Is it OS X 10.11.6 or CentOS 7? Or is one running the eXist server and one where you’re launching the client?

**Comment by adamretter** [comment]
Also how did you install eXist on one or both machines?

**Comment by lguariento** [comment]
The 'context information' is for the installation, with I did via `git clone`, master branch. I only have shell access to that CentOS machine. OS 10.11.6 is where I launch exist.jnlp.

**Comment by duncdrum** [comment]
@lguariento Does 10.11.6 support SIP?

**Comment by lguariento** [comment]
I'm not sure about that. All I know is that it used to work just fine with eXist-db 4.0. Also, I just tried on OSX 10.13.4, and I get

```
Unsigned application requesting unrestricted access to system
Unsigned resource: http://myip:8080/webstart/xmlrpc-client-3.1.3.jar
```

**Comment by duncdrum** [comment]
I'm going to duck and 🏃 , but did you perform the [singing step](http://www.exist-db.org/exist/apps/doc/building-db4.xml?q=signing%20jar&field=all&id=D2.4.10#D2.4.10) when building exist in your clone?

**Comment by lguariento** [comment]
No I didn't! am I supposed to do that? From the documentation it looks like it's part of the 'Using the Build System' section, i.e. alternative to git clone. Also, there's no mention of it in the GitHub build.md, which I got the impression was more accurate/up-to-date anyway. So? Do I have to recompile it?

**Comment by duncdrum** [comment]
Nah build system to using build.sh in a clone / forked repo. Given the type of error, I would start there. 

P.S.: the link will change very soon see #1868

**Comment by lguariento** [comment]
![java](https://user-images.githubusercontent.com/10143842/39955617-b6c0e986-55c9-11e8-83dc-fbe5f3b46973.jpg)

It worked, thanks! I got the above error, but at least I can open the client. Thanks!

**Comment by DatTranConggg** [comment]
Hey bro, Could you give me Step by Step to fix it ? plzzz

**Comment by lguariento** [comment]
See [here](http://www.exist-db.org/exist/apps/doc/exist-building.xml?field=all&id=D3.15.17#D3.15.17).
