### ISSUE TITLE
bug webdav windows 7 eXist 4

### ISSUE THREAD

**Issue by acqueron** [eXist-db/exist#1875]
context:
windows 7 64 bit
eXist 4

When i try to add eXist 4 as an external folder in windows explorer, i suceeded it but when i open xml files, there are truncated. It's the same problem with XMLSPY external web folder.
Before, this worked with eXist 2.1

Thank you for your help

**Comment by dizzzz** [comment]
Does it work ok for non-XML documents?
In essence no big modifications have been made in the webdav code for a very long time.

**Comment by acqueron** [comment]
Hello dizzzz
I work only with XML files (.xml and .xsd) and files are not opened completely

**Comment by bkcsfi** [comment]
This bug effects me too.. I am using cadaver, a linux CLI webdav client

I have noticed after updating to 4.1.0 that documents are randomly truncated when I get them via webdav.

example, using cat or less, the file is truncated

```
ls
1220025281.xml                     24576  May 22 11:39
```

```
less 1220025281.xml
        <lineitem id="680" linenumber="60">
            <part_description>PV0001-08912 - BC 18 1.HJ EN/FR</part_description>
            <quantity_ordered>100</quantity_ordered>
            <unit_price python.type="decimal.Decimal">0.50</unit_p
(END)
```
but other documents work ok

```
ls
1220025282.xml                     12288  May 22 11:39
1220025283.xml                     12288  May 22 11:39
1220025284.xml                     12288  May 22 11:39
```

```
less 1220025284.xml
(snip)

        <lineitem id="200" linenumber="18">
            <part_description>PV0103-14772 - Giant panda, male</part_description>
            <quantity_ordered>5</quantity_ordered>
            <unit_price python.type="decimal.Decimal">3.37</unit_price>
            <part_number>10123872</part_number>
            <quantity_shipped>5</quantity_shipped>
        </lineitem>
    </lineitems>
    <unknown_parts python.type="list"/>
</invoice>
(END)
```

its not just large documents that are truncated

```
ls 
1220025258.xml                      4096  May 22 10:22

less 1220025258.xml
(snip)
        </lineitem>
        <lineitem id="110" linenumber="3">
            <part_description>PV0108-13782 - Pig</part_description>
            <quantity_ordered>5</quantity_ordered>
            <unit_price python.type="decimal.Decimal">2.58</unit_price>
          
(END)
```

**Comment by dizzzz** [comment]
Some simple tests with curl for me, show that actually the whole documents are streamed out; this hints into changes client behaviour, not on the server. 

For windows: please check which *exact* versions of the webdav libraries are used; e.g. which version of MS office is installed? I am not an expert here, but there used to be a lot of issues here in the past.

About cadaver: also here: what version? also in this client there were issues in the past. 

:-(

**Comment by dizzzz** [comment]
Please check the webdav documentation ; in the past I wrote quite a lot on compatibility issues on windows XP and 7.

cadaver used to work as it is not explicitly mentioned in the documentation, but I don;t know which versions.

**Comment by dizzzz** [comment]
In the eXist-db documentation  I have written, a long time ago, some clues how to change the behavior of the 'Content Header". Please check this documentation (I guess this was not checked yet)

http://www.exist-db.org/exist/apps/doc/webdav.xml?field=all&id=D3.17.19#serialization

**Comment by duncdrum** [comment]
closing because of no response, if you continue to experience issues please open a new ticket, including full version info and steps to reproduce, thx.
