### ISSUE TITLE
ExistDb won't start on windows 10 with java version 8_171+

### ISSUE THREAD

**Issue by merenyics** [eXist-db/exist#1882]
### What is the problem
> With Java 8_171/172 on a Windows 10 machine, existDb (any recent version) seems to install normally, but start.jar fails to start exist with no error, no trace of any problem in the exist log, or any indication of the nature of the problem whatsoever. The only enrties in exist.log come from the embedded version run during setup to set admin privileges.

### What did you expect
> I expected existdb to start normally with Java 8_171+ installed

### Describe how to reproduce or add a test
> Do a clean install of existDb on a Windows 10 PC running Java 8_171+

### Context information
Please always add the following information
- eXist-db version: 3.x, 4.x
- Java version (Java8u171)
- Operating system (Windows 10)
- 64 bit
- No custom changes

**Comment by duncdrum** [comment]
Did you use the installer or build from source code? Can you confirm that the `$JAVA_HOME` property is set on your OS, and pointing to Java8?

**Comment by merenyics** [comment]
I used the .jar installer to install existdb. As for JAVA_HOME, I'm not sure, and don't have access to the given Windows 10 PC right now, but I assume the Java jre installer sets this environment variable during install. Will check as soon as I can.

**Comment by merenyics** [comment]
Originally, JAVA_HOME didn't point to the correct jre folder, but setting JAVA_HOME to `c:\Program Files (x86)\Java\jre1.8.0_171` didn't help. This time I got an error message during exist install saying something like `Java\jre1.8.0_171 is unexpected at this time`. I added double quotes to the path, reinstalled exist, this time there was no error, but start.jar still fails silently.

This may or may not be unrelated to the current problem, but I would like to add that quoting long path names in environment variables doesn't seem to be standard, but exist seems to require it (?)

**Comment by duncdrum** [comment]
i don't have access to win machines, so someone else should chime in here. You might have to relog to make sure that the correct java home sticks. So far this sounds more like a os problem, with handling multiple java jre. On our win test system, and in the past there were no problems with exist on win10 with java8.

**Comment by merenyics** [comment]
I'd just like to confirm that I have only one jre installed, and between java install, setting JAVA_HOME and installing existdb, I always restarted the machine, so the updated environment variable was definitely visible to the exist installer. The troubles started with the 171 java update, so it would be nice if anyone could confirm that they were able to do a clean new installation of any version of existdb while running java 8_171.

**Comment by dizzzz** [comment]
So, probably in the startup scripts there is still a reference to the old (wrong) JAVA_HOME location?

**Comment by merenyics** [comment]
I doubt it, because I installed exsitDb from scratch with only the new version of Java installed on my computer, and JAVA_HOME pointing to the correct folder. I also searched for the text 'jre' in the exist folder, and all occurrences seemed to refer to the correct (171) version. Will double-check though.
Meanwhile a silly(?) question: could the problem be that I installed the 32-bit version of Java? The PC I'm currently on has 64-bit Java, and it runs exist without a problem.

**Comment by dizzzz** [comment]
32bit can be indeed a problem, depending on the exact memory settings (Xmx). This detail was not in your original report though :-)

**Comment by merenyics** [comment]
Switching to the 64-bit jre solved the problem. Thank you for pointing me in the right direction. You might consider looking into why the 32-bit version fails so mysteriously.

**Comment by dizzzz** [comment]
is the memory / heap settings are set too high, java (the '.exe') will just 'die' immediately.
