### ISSUE TITLE
No charset in XMLRPC responses

### ISSUE THREAD

**Issue by zmbq** [eXist-db/exist#1899]
I'm using Python's XMLRPC package to access eXist-db, which in turn uses the very wide-spread requests package for handling HTTP.

I found out that even though I set UTF-8 as the default encoding, responses are not decoded by Python in UTF-8, but rather in the ISO-8859-1 character set. Further investigation shown that he content-type header returned from eXist is:

`content-type: text/xml`

The Requests package is very strict about this. If no character set is specified, it does what the standard says, meaning it uses ISO-8859-1 .

I can work around it and fix it on the client side, but still I think it would be better to change the content-type to `content-type: text/xml; charset=utf-8`

The REST API works well, returning a content type of `application/xml; charset=utf-8` .

All this is with eXist 4.10 on 64-bit Windows 10 with Java 8.

**Comment by joewiz** [comment]
@zmbq I really enjoyed your article about this bug! http://www.chelem.co.il/exist-db-utf-8-and-a-bug/ Thanks for sharing.
