### ISSUE TITLE
Cardinality of return types not enforced

### ISSUE THREAD

**Issue by joewiz** [eXist-db/exist#1917]
### What is the problem

eXist fails to enforce the cardinality of function return types, except in the case of the arrow operator.  For example, take the two following cases:

**Case 1:**
```xquery
index-of(("A", "B", "C", "B"), "B")
```

**Case 2:**
```xquery
("A", "B", "C", "B") => index-of("B")
```

The result of these cases should be identical, returning `(2, 4)` - a sequence of 2 integers. Before https://github.com/eXist-db/exist/pull/1916, eXist's return cardinality for `fn:index-of` was `ZERO_OR_ONE`, so both should have raised an error, but only Case B did. 

This observation, together with the very large number of cardinality mismatches documented at https://gist.github.com/joewiz/78b1827971a3c1c5dec8fc2d13dec8b2, suggests that eXist may be failing to enforce its own cardinality checks.

### What did you expect

I expect eXist to enforce its return type's cardinality regardless of how a function is called - either directly, via arrow operator, etc.

### Describe how to reproduce or add a test

I think that developing a test for this would require java skills that I unfortunately lack.  

(Return types are correctly enforced in XQuery:

```xquery
xquery version "3.1";

declare function local:zero-or-one-integer($x as item()*) as xs:integer? {
    $x
};

local:zero-or-one((1, 2))
```

This correctly raises the error.  So the issue reported here appears to only affect functions implemented in Java.)

### Context information

- eXist-db version + Git Revision hash: eXist 4.2.0
- Java version: 1.8.0_172-b11
- Operating system: macOS 10.13.5
- 32 or 64 bit: 64 bit
- How is eXist-db installed: clone from GitHub
- Any custom changes in e.g. conf.xml: none

**Comment by joewiz** [comment]
In eXist 5.2.0, no error is raised in the `index-of` examples at the beginning of this issue. But I assume the general problem of "eXist not enforcing return types on XQuery functions implemented in Java" persists in eXist 5. I seem to recall seeing confirmation of that statement but can't find it at the moment. 

Would it be correct to advance this to the eXist 5 milestone then?

**Comment by adamretter** [comment]
@joewiz eXist-db 5.2.0 is still very lax about enforcing return types.

It also doesn't cope well with compound types, e.g. `map(xs:string, map(xs:string, xs:int)`, I think I fixed the `document-node(element(x))` compound thing recently, but that might need further testing too.

**Comment by ndw** [comment]
Adam suggested I append this here as a related error.

This query should raise an error, but it does not at the moment:

```
xquery version "3.1";

declare function local:foo(
) as element(bar)
{
    <not-bar>test</not-bar>
};

local:foo()
```

**Comment by alanpaxton** [comment]
I've confirmed that in 6.1.0-SNAPSHOT the original reported cases DO NOT return an error; this is correct behaviour. I will investigate whether there is still a more general problem with cardinality checking.

**Comment by alanpaxton** [comment]
> Adam suggested I append this here as a related error.
> 
> This query should raise an error, but it does not at the moment:
> 
> ```
> xquery version "3.1";
> 
> declare function local:foo(
> ) as element(bar)
> {
>     <not-bar>test</not-bar>
> };
> 
> local:foo()
> ```

This is also reported in https://github.com/eXist-db/exist/issues/3780

**Comment by joewiz** [comment]
I have updated the referenced gists with eXist 6.1.0-SNAPSHOT 65d3d5e6968ae8e281cc9926604b055254022529 20220512042037. The updated signature mismatches detected by the script are https://gist.github.com/joewiz/78b1827971a3c1c5dec8fc2d13dec8b2#file-signature-mismatches_results-xml.

Some cases are not necessarily bugs - but are due to eXist’s less verbose signature reporting. Others, like contains-token, are clearly bugs:

```xml
<testcase name="fn_contains-token_3">
    <name>contains-token#3</name>
    <arg>xs:string*</arg>
    <arg>xs:string</arg>
    <arg>
        <expected>xs:string</expected>
        <actual>xs:string?</actual>
    </arg>
    <return>xs:boolean</return>
</testcase>
```

Here the cardinality on the 3rd argument is wrong in eXist.

**Comment by joewiz** [comment]
Leaving out the cases where the function signature mismatches are due to eXist's less verbose signature reporting, here are functions that I think contain real issues:

```xml
<signature-mismatches>
    <testcase name="fn_collection_1">
        <name>collection#1</name>
        <arg>
            <expected>xs:string?</expected>
            <actual>xs:string*</actual>
        </arg>
        <return>item()*</return>
    </testcase>
    <testcase name="fn_contains-token_3">
        <name>contains-token#3</name>
        <arg>xs:string*</arg>
        <arg>xs:string</arg>
        <arg>
            <expected>xs:string</expected>
            <actual>xs:string?</actual>
        </arg>
        <return>xs:boolean</return>
    </testcase>
    <testcase name="fn_current-dateTime_0">
        <name>current-dateTime#0</name>
        <return>
            <expected>xs:dateTimeStamp</expected>
            <actual>xs:dateTime</actual>
        </return>
    </testcase>
    <testcase name="fn_document-uri_1">
        <name>document-uri#1</name>
        <arg>
            <expected>node()?</expected>
            <actual>node()*</actual>
        </arg>
        <return>xs:anyURI?</return>
    </testcase>
    <testcase name="fn_format-integer_2">
        <name>format-integer#2</name>
        <arg>
            <expected>xs:integer?</expected>
            <actual>xs:numeric?</actual>
        </arg>
        <arg>xs:string</arg>
        <return>xs:string</return>
    </testcase>
    <testcase name="fn_format-integer_3">
        <name>format-integer#3</name>
        <arg>
            <expected>xs:integer?</expected>
            <actual>xs:numeric?</actual>
        </arg>
        <arg>xs:string</arg>
        <arg>xs:string?</arg>
        <return>xs:string</return>
    </testcase>
    <testcase name="fn_json-to-xml_1">
        <name>json-to-xml#1</name>
        <arg>xs:string?</arg>
        <return>
            <expected>document-node()?</expected>
            <actual>item()?</actual>
        </return>
    </testcase>
    <testcase name="fn_json-to-xml_2">
        <name>json-to-xml#2</name>
        <arg>xs:string?</arg>
        <arg>map(*)</arg>
        <return>
            <expected>document-node()?</expected>
            <actual>item()?</actual>
        </return>
    </testcase>
    <testcase name="fn_xml-to-json_2">
        <name>xml-to-json#2</name>
        <arg>node()?</arg>
        <arg>
            <expected>map(*)</expected>
            <actual>map(*)?</actual>
        </arg>
        <return>xs:string?</return>
    </testcase>
</signature-mismatches>
```

None of these actually involves the cardinality of return types (i.e., the problem described in this issue's title), but the body of the original issue clearly addresses the more general problem of mismatches in the type and cardinality of parameters in function signatures, so I think it may well be worth reviewing these to see if we can better align eXist with the F&O spec.

The problem that @ndw [reported above](https://github.com/eXist-db/exist/issues/1917#issuecomment-723598283)—of eXist failing to raise errors when returned data doesn't match the name test given in the function signature—does rightly belong in this issue too, I think. It's not about cardinality *per se*, but it does point to eXist's failure to respect directives in function signatures.

In another [comment above](https://github.com/eXist-db/exist/issues/1917#issuecomment-607711559) , @adamretter also pointed to the issue of "compound types, e.g. `map(xs:string, map(xs:string, xs:int)`".
