### ISSUE TITLE
file:serialize() with UTF-8 results in wrong encoded characters

### ISSUE THREAD

**Issue by floerke** [eXist-db/exist#1922]
### What is the problem
When serializing XML to a external file, you get a wrong result when using UTF-8 encoding.

```xquery
(: -*- coding: utf-8 -*- :)
xquery version "1.0" encoding "utf-8";

declare namespace system="http://exist-db.org/xquery/system";
declare namespace file="http://exist-db.org/xquery/file";

let
  $dmy := session:set-current-user("admin",""), 
  $data := <a>ä</a>,
  $doit1 := file:serialize(<a>ä</a>,concat(system:get-exist-home(),'/test_utf8.xml'),('method=xml','omit-xml-declaration=no','encoding=utf8')),
  $doit2 := file:serialize(<a>ä</a>,concat(system:get-exist-home(),'/test_ascii.xml'),('method=xml','omit-xml-declaration=no','encoding=us-ascii')),
  $doit3 := file:serialize(<a>ä</a>,concat(system:get-exist-home(),'/test_iso.xml'),('method=xml','omit-xml-declaration=no','encoding=iso-8859-1'))
return
  <dummy/> 
```

The results are attached.

### Context information
Please always add the following information
- eXist-db 4.0
- Java version 8-161
- Operating system Windows 7
- 64 bit

**Comment by floerke** [comment]
[test.zip](https://github.com/eXist-db/exist/files/2083308/test.zip)

**Comment by adamretter** [comment]
@floerke I modified you script a little to simplify it a little:

```xquery
(: -*- coding: utf-8 -*- :)
xquery version "3.1" encoding "utf-8";

declare namespace file="http://exist-db.org/xquery/file";

let
  $dir := "/tmp/",
  $dmy := xmldb:login("/db", "admin",""), 
  $data := <a>ä</a>,
  $doit1 := file:serialize(<a>ä</a>, $dir || 'test_utf8.xml', ('method=xml','omit-xml-declaration=no','encoding=utf8')),
  $doit2 := file:serialize(<a>ä</a>, $dir || 'test_ascii.xml', ('method=xml','omit-xml-declaration=no','encoding=us-ascii')),
  $doit3 := file:serialize(<a>ä</a>, $dir ||'test_iso.xml', ('method=xml','omit-xml-declaration=no','encoding=iso-8859-1'))
return
  <dummy/> 
```

If you are on Windows you can replace ` $dir := "/tmp/",` with ` $dir := "c:\temp\" or similar.

On my machine this appears to work. I am validating the created files with the `UTF8 Validator` which is available from here: https://github.com/digital-preservation/utf8-validator

I am not saying there isn't a problem, but I can't yet see the problem. Can you try the above script and then check your output files with the UTF-8 validator please?

**Comment by adamretter** [comment]
@floerke Did you manage to test this?

**Comment by floerke** [comment]
Hi @adamretter, my daily business prevent me from investigating your comment. I will comment this week.

**Comment by floerke** [comment]
Retesting with

* eXist 4.2.1, Windows7, 64Bit, Java8

results in wrong encoded character (see screenshot). The utf-8 xml contains the byte E4 (instead of C3 A4) for german umlaut ä.

**Comment by floerke** [comment]
![encoding_error](https://user-images.githubusercontent.com/26478323/42277908-3dc64662-7f99-11e8-904b-6bea24d5faf8.png)

**Comment by adamretter** [comment]
@floerke What is your Windows locale set to please?

**Comment by adamretter** [comment]
@floerke further testing from me, does not yet discover your issue:

* eXist-db: `5.0.0-SNAPSHOT`
* Java: `Oracle 1.8.0_144`
* Operating system: `Windows 10 Pro N 64-bit (10.0, Build 14393)`
    * Language: `English (Regional Setting: English)`
    * Location: `United Kingdom
    * Codepage: `850`

I ran the simplified query above, and then used the UTF-8 Validator tool that I mentioned to check each file:

```
validate c:\tmp\test_ascii.xml
Validating: c:\tmp\test_ascii.xml
Valid OK (took 0ms)
```

```
validate c:\tmp\test_utf8.xml
Validating: c:\tmp\test_utf8.xml
Valid OK (took 0ms)
```

```validate c:\tmp\test_iso.xml
Validating: c:\tmp\test_iso.xml
Valid OK (took 0ms)
```

Can you tell me what your language and region settings are please? Also did you try the UTF-8 Validator program on the output files?

Can you also please run `chcp` and tell me what code page you have active?

I am wondering if, the differences between your and my setup is either:
1. Changes between Windows 7 and 10 in how default character encoding is handled.
2. Changes between Java version for Windows on how character encoding is detected.
3. Windows Locale settings.

Interestingly I read that `chcp 65001` will set the code page to UTF-8. Although I would note that I do not have that set here, and have not had to set that.

Also if I run `set` from `cmd.exe` I don't have any locale or codepage environment variables set.

**Comment by floerke** [comment]
eXist-db: 4.2.1
Java: Oracle 1.8.0_162
Operating system: Microsoft Windows 7 Pro [Version 6.1.7601], Service Pack 1, 64-Bit
Language: Deutsch (Deutschland) = "German (Reginal Setting: Germany)"
Location: Germany
Codepage: 850

...>java -jar utf8-validator-1.3-SNAPSHOT.jar test_utf8.xml
Validating: test_utf8.xml
[ERROR] Invalid UTF-8 sequence, byte 2 of 3 byte multibyte sequence. @ byte posi
tion: 43
[ERROR] Invalid UTF-8 sequence, byte 3 of 3 byte multibyte sequence. @ byte posi
tion: 44 

No additional locale or codepage environment variables set, too.

Strange...

**Comment by floerke** [comment]
Maybe we can strip down the problem with a small Java-Commandline snippet. Are you able extract, what file:serialize is doing when writing a string to a file?

**Comment by adamretter** [comment]
@floerke so the issue *might* be here: https://github.com/eXist-db/exist/blob/develop/extensions/modules/src/org/exist/xquery/modules/file/SerializeToFile.java#L208

When calling `new OutputStreamWriter(os)` you can specify a character encoding.

If you don't specify a character encoding, the Java doc says `Creates an OutputStreamWriter that uses the default character encoding.`. It seems that ultimately calls `Charset.defaultCharset().name()`. So could you on your platform from a very small Java app try something like this:

```java
import java.nio.charset.Charset;

public class CheckCharset {
    public static void main(final String args[]) {
        System.out.println("defaultCharset=" + Charset.defaultCharset().name());
    }
}
```

On my Windows platforms here it reports:" `defaultCharset=UTF-8`.

**Comment by adamretter** [comment]
@floerke If you could let me know in the next day or so that would be excellent, as I am hoping to push out a hotfix release.
