### ISSUE TITLE
Namespaces mangled on using doc() with file:/ 

### ISSUE THREAD

**Issue by eriksiegel** [eXist-db/exist#1976]
### What is the problem
After reporting #1975 I tried to load the doc from the file system using `doc('file:/path/to/file.xml')` (as the `admin` user).

Big surprise: it totally mangles the namespaces!

What goes in as:
```xml
<book dtd-version="2.0xxxxx" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:mml="http://www.w3.org/1998/Math/MathML" xml:lang="en">
```

Comes out as:
```xml
<book xmlns="http://www.w3.org/1998/Math/MathML" xmlns:mml="http://www.w3.org/1998/Math/MathML" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns="" dtd-version="2.0xxxxx" xml:lang="en">
```

Note the double `xmlns=""`, this makes the document not well-formed

### What did you expect
Using `doc()` with a `file:/` URL should load the document from the file system as-is, not mangle it.

### Describe how to reproduce or add a test
Try to load the following XML (in the zip) file from the file system using `doc('file:/path/to/the/file.xml')` in an XQuery script as admin. 
[aic.15.2018-06-15-2.xml.zip](https://github.com/eXist-db/exist/files/2141334/aic.15.2018-06-15-2.xml.zip)

### Context information
See #1975

**Comment by dizzzz** [comment]
what version of exist-db are you using? I am surprised that `doc('file:///')` actually works :-)
please could you verify what happens when you put three slashes after file: ?

**Comment by eriksiegel** [comment]
file:/// doesn't change anything

The XQuery was stored in eXist. I have tried to run iut both from within oXygen using its eXist connector and through the REST interface: All the same results

Version information (as I already provided): See #1975 (4.2.1 running on W10)

I think its *very* troublesome that a parsed XML file contains these kinds of errors. That looks like a very fundamental flaw...

**Comment by duncdrum** [comment]
this reminds me of what happened to repo.xml files a while ago.
