### ISSUE TITLE
Nixos and non-standard paths

### ISSUE THREAD

**Issue by tasmo** [eXist-db/exist#1999]
The installer cannot set rights through `chmod`

```shell
[ WARNING: Error executing
/bin/chmod a+x /.../exist/start.jar ]
[ ERROR: The installation was not completed ]
[ Unpacking finished ]
```

because it is not found under `/bin`.

When using `startup.sh` there is a similar problem

```shell
/.../exist/bin/functions.d/eXist-settings.sh: line 14: /usr/bin/dirname: No such file or directory
/.../exist/bin/functions.d/eXist-settings.sh: line 14: /bin/pwd: No such file or directory
Unable to find start.jar. Please set EXIST_HOME to point to your installation directory.
```

These are the paths on Nixos

```shell
$ type chmod
chmod is /run/current-system/sw/bin/chmod
$ type dirname
dirname is /run/current-system/sw/bin/dirname
$ type pwd
pwd is a shell builtin
pwd is /run/current-system/sw/bin/pwd
```

The solution for the `startup.sh` script is to change line 14 in `bin/functions.d/eXist-settings.sh` to

```shell
                (cd $(dirname "$p") ; pwd)
```

bash should know the path to the executables anyway.

**Comment by duncdrum** [comment]
@tasmo any progress on the env PR?

**Comment by tasmo** [comment]
Personally I'm giving up on NixOS. It is a good idea for orchestrating more servers but not as a developer desktop OS.

**Comment by adamretter** [comment]
I already modified all our scripts to use `/bin/env`
