### ISSUE TITLE
Fetching LDAP groups does not work correctly because some escaping is missing

### ISSUE THREAD

**Issue by simar0at** [eXist-db/exist#2001]
### What is the problem
- If you have a user name containing ```\``` and ```()``` like ```Omar\, Siam``` in an organisational unit like ```Austrian Center for digital humanities (ACDH)``` the LDAP code is unable to search for the corresponding groups because  for the search the DN is taken as is.

### What did you expect
* The ```\``` and ```()``` need to be escaped. ```\5c, \28, \29```.

### Describe how to reproduce or add a test
* Try the literal representation in Apache Directory Studio. Does not work.

### Context information
Please always add the following information
- eXist Version : 4.3.0 eXist Build : 201807061041 Git commit : 3d6c60327
- jre1.8.0_172
- Windows 10
- 64 bit
- JAR installer

**Comment by adamretter** [comment]
@simar0at Can you suggest:

1) All the places in the LDAP code we need to encode strings before sending them? I am guessing it is not just for group searches.

2) What the encoding scheme should be? I am guessing we may need to encode more than just `\`, `(`, and `)` characters?

**Comment by simar0at** [comment]
Isn't there a class containing SearchAttributes? Perhaps this class should do the magic. It's a particularity of LDAP search filters. As in these () are used to delimit search terms they have to be encoded and \ needs to be encoded because it is the escape character used to encode characters. I think that it is sufficient to have these three encoded. I don't know for sure and I can't do further research. Sorry.

**Comment by adamretter** [comment]
Would you be able to test out this patch and let me know if it works for you? - https://github.com/eXist-db/exist/pull/2012
