### ISSUE TITLE
eXist-db installed as yajsw daemon service does not startup on Ubuntu 16.04 / Ubuntu 18.04

### ISSUE THREAD

**Issue by kohsah** [eXist-db/exist#2005]
### What is the problem
> set EXIST_HOME, JAVA_HOME install eXist-db as a non-privileged daemon service. Attempt to start-up exist-db using systemd. Startup failes.

### What did you expect
> eXist-db should have started.

### Describe how to reproduce or add a test
> Install eXist-db 4.2.1 or eXist-db 4.3.0 using the jar installer and attempt to register as a service with yajsw.

### Fixing the Problem

`yajsw/conf/wrapper.conf` is set with an incorrect path (possibly by the eXist-db installer). It points to a non-existent JVM on my system 
```
wrapper.java.command=/Library/Java/JavaVirtualMachines/jdk1.8.0_151.jdk/Contents/Home/bin/java
```
Once i change it to the actual `<JAVA_HOME_PATH>/bin/java` and reinstall the daemon, eXist-db startups fine with yajsw.

**Comment by claudius108** [comment]
Fixing wrapper.java.command=/usr/bin/java is not solving for me in Ubuntu 18, java 1.8.0_171, and eXist 4.2.1.

**Comment by dizzzz** [comment]
You need to fix it in `$EXIST_HOME/tools/yajsw/conf/wrapper.conf` too...

**Comment by claudius108** [comment]
In $EXIST_HOME/tools/yajsw/conf/wrapper.conf.in there is wrapper.java.command=@java.vm@, and in $EXIST_HOME/tools/yajsw/conf/wrapper.conf there is wrapper.java.command=/usr/bin/java.
Neither with wrapper.java.command=/usr/lib/jvm/java-8-oracle in $EXIST_HOME/tools/yajsw/conf/wrapper.conf is not working.

**Comment by dizzzz** [comment]
not sure if you need to re-install the service when the file is update. e.g. if a copy is installed in /etc/init.d in stead of a symlink.....

**Comment by claudius108** [comment]
Sure, I am reinstalling the service ...

**Comment by adamretter** [comment]
So it seems that we ship `wrapper.conf.install` as `wrapper.conf` inside the IzPack installer. From `installer/install.xml.tmpl`:

```
<singlefile src="tools/yajsw/conf/wrapper.conf.install"
                target="$INSTALL_PATH/tools/yajsw/conf/wrapper.conf" override="true"/>
            <parsable type="plain" targetfile="$INSTALL_PATH/tools/yajsw/conf/wrapper.conf"/>
```

**Comment by wolfgangmm** [comment]
I can only guess, but I assume either (1) the wrapper.conf.install was already there when we were still relying on jsw instead of yajsw and I simply copied the steps, or (2) it was necessary for windows.

It would be important to see if the suggested service installation works without hardcoded path on windows when you start eXist via start.jar the first time.

**Comment by adamretter** [comment]
@wolfgangmm From the git history it looks like you added it when you switched to YAJSW.
I don't think it can be for Windows purposes, as the path in that file to Java is a Mac style filesystem path.

**Comment by claudius108** [comment]
Thank you, Adam, I can now confirm that installing 4.3.0, as you said, works.

**Comment by wolfgangmm** [comment]
@adamretter after removing `conf/wrapper.conf` and `conf/wrapper.conf.install`, installing the service worked on windows 10, whereas it would fail when those files were present.

**Comment by claudius108** [comment]
eXist 4.3.1 still needs the workaround mentioned by Adam above.

**Comment by adamretter** [comment]
@claudius108 So the fix https://github.com/eXist-db/exist/commit/ed7b83b787f557ab62907629026acb3d905947a7 by @wolfgangmm was not enough?

**Comment by dizzzz** [comment]
See #2043
