### ISSUE TITLE
Wrong MIME type on HTML5 pages in XHTML namespace

### ISSUE THREAD

**Issue by dariok** [eXist-db/exist#2006]
## What is the problem
When using eXide to create an HTML file with the option "HTML5 file in XHTML namespace", this file is saved (and consequently served) with the incorrect MIME type of `text/html`. Additionally, the doctype is omitted by Jetty. While it is possible to manually change the MIME type, it is changed back to `text/html` each time you save the file from eXide.

### _The beginning of the file in eXide as auto-created_:

    <?xml version="1.0" encoding="UTF-8"?>
    <!DOCTYPE html>
    <html xmlns="http://www.w3.org/1999/xhtml">
        <head>

### The response of eXist with such a file:
_HTTP header_: `Content-Type: text/html;charset=utf-8`
_Beginning of file_:

    <?xml version="1.0" encoding="UTF-8"?>
    <html xmlns="http://www.w3.org/1999/xhtml">
        <head>

### What did you expect
1. The correct namespace, `application/xhtml+xml`;
1. The file with correct doctype - just a it is in eXide

### Describe how to reproduce or add a test
Create a file in eXide with the above parameters and check the response as served by Jetty.

Please always add the following information
- eXist 3.6.1, Build 201801032119
- Java 1.8.0_151
- Ubuntu 16.04 / Kernel Linux 4.4.0-042stab126.1 amd64
- JAR installer
- No custom changes

**Comment by joewiz** [comment]
Which file extension are you using? If you’re using `.html` could you please test `.xhtml` and report your results? 

In my next reply, I’ll cover the difference between eXide’s templates, eXide’s saving behavior, eXist’s file extension-based mime-type resolution, and XQuery serialization.

**Comment by dariok** [comment]
The extension does not seem to make a difference. Cf. http://exist.baukast.digital:8888/exist/apps/pageCount/index.xhtml which also is returned as `text/html`.
