### ISSUE TITLE
calling a non-existent templating function no longer(?) reports error

### ISSUE THREAD

**Issue by merenyics** [eXist-db/exist#2050]
### What is the problem
> If I remember correctly, prior to version 4.3 calling a templating function like this
 `<div class="some:function"/>` 
resulted in an error being thrown immediately, indicating that the given function does not exist. Right now, using 4.3, the server does not respond within a reasonable amount of time, I can see in Monex that a query is running (view.xql) but it won't return, I need to kill it manually.

### What did you expect
> I expected to get the error message I used to get, instead of the query hanging

### Describe how to reproduce or add a test
> Just try calling a non-existent function using templating

### Context information
Please always add the following information
- eXist-db version 4.3
- Java version Java8u161
- Operating system Windows 10 
- 64 bit
- How is eXist-db installed? (JAR installer)
- no custom changes

**Comment by adamretter** [comment]
@wolfgangmm I wonder if this is that infinite issue I pointed out to you - where it tries to call a function with 1 parameter, then 2, then 3 and then so on and so on...

**Comment by windauer** [comment]
I exerienced the same issue and can confirm this!
