### ISSUE TITLE
eXist-db 4.3.0 incorrect undefined variable in for loop

### ISSUE THREAD

**Issue by ahenket** [eXist-db/exist#2055]
As of eXist-db 4.3.0 there is a problem when you reuse a variable in a for loop, before the return statement. eXist-db then claims the variable is not set.

Reproduction code:

```xquery
let $xml            := <x valueSet="2.16.840.1.113883.2.4.3.11.60.40.2.17.1.7"/>
let $associations   := doc(xmldb:store('/db', 'termasoc.xml', $xml))/x

return
<x>
{
    for $association in $associations
    let $vsref          := string($association/@valueSet)
    let $check          := if (string-length($vsref) gt 0) then true() else false()
    return ()
}
</x>
```

Expected return: 

```xml
<x/>
```

Actual return:

```err:XPDY0002 undefined value for variable '$vsref' [at line 11, column 47]```

The issue only occurs when the xml fragment comes from the db. It does not occur when the fragment comes from memory.

Context: eXist-db 4.3.0 dmg version stable as found on eXist-db.org. macOS Mojave (10.14 bèta (18A336e)), Java(TM) SE Runtime Environment (build 1.8.0_121-b13). Reproducible under Windows 10 using the jar installer.

Possibly related to: https://github.com/eXist-db/exist/issues/2054

**Comment by duncdrum** [comment]
could you try with
`doc(xmldb:store('/db/apps', 'termasoc.xml', $xml))//x`
 the return type of doc() is document-node hence two `//` might be required

**Comment by ahenket** [comment]
/x  is enough as what I store is exactly 1 node, but I tried with //x just now and that does not change the situation.

**Comment by adamretter** [comment]
I wonder if this is related?

**Comment by adamretter** [comment]
I wonder if this is related? https://github.com/eXist-db/exist/pull/2053

**Comment by adamretter** [comment]
Thanks for your bug report :-)

So this seems to have already been fixed on the `HEAD` of `develop-4.x.x`. Could you test with that, or test when 4.3.1 comes out shortly?

As I think this is already fixed, I am going to close this issue. Please re-open with details if you believe it is still not fixed.
