### ISSUE TITLE
Undefined variable throws wrong dynamic error as static, should throw static error

### ISSUE THREAD

**Issue by adamretter** [eXist-db/exist#2060]
This XQuery in eXist-db throws an `XPDY0002` error:

```xquery
<pass>{$var}</pass>
```

The `XPDY` indicates a dynamic error, however if we try to catch it:

```xquery
try {
	<pass>{$var}</pass>
} catch err:XPDY0002 {
	<failed/>
}
```

We still get an `XPDY0002` error, i.e. we can't catch it.

Two things are going wrong here in eXist-db:

1. The `XPDY0002` error is being thrown as a static error, and not a dynamic error. So we can't catch it.
2. I think we are using the wrong error here. The error I think we should be using is `XPST0008` which is a static error.
    1. I would note that the error occurs during query compilation (not execution) in eXist-db and so is in fact a static error!
    2. Saxon and BaseX both report `XPST0008`.

The culprit seems to be here: https://github.com/eXist-db/exist/blob/eXist-4.3.0/src/org/exist/xquery/VariableReference.java#L64

Comments?

**Comment by dizzzz** [comment]
Makes sense to me..... @wolfgangmm  ?
