### ISSUE TITLE
Passing the password to the Java Admin Client from the command line

### ISSUE THREAD

**Issue by ttasovac** [eXist-db/exist#2063]
### What is the problem
It is impossible to set the password in the Java Admin Client GUI from the command line.

`/Applications/eXist-db.app/Contents/Resources/eXist-db/bin/client.sh -ouri=xmldb:exist://XXX.XXX.XX.XXX:8080/exist/xmlrpc -u admin -P xxxxxx`

will open the GUI, with the URL entered correctly, but the password field will remain empty

### What did you expect
To have the password field filled out. 

The password is correctly passed in the interactive shell mode (using the `-s` option) but not when we open a GUI.

### Describe how to reproduce or add a test
See above

### Context information
Please always add the following information
- eXist-db version: 5.0.0RC2 but this is not a new problem, it's been a feature for as long as I know
- Java version: 1.8.0_144-b01
- Operating system: Mac OS 10.13.6
- How is eXist-db installed? brew cask

**Comment by duncdrum** [comment]
@eXist-db/core someone more familiar with how the java admin client is supposed to work, please take a look.

**Comment by dizzzz** [comment]
I am not aware that this should be possible, as there is a login box.
But to go back... what is the usecase to have this password filled in? what is the purpose?
Filling a password might impose some risks....

**Comment by ttasovac** [comment]
I like to start the Java Admin Client from a script. It would be easier if the password could be filled out the same way the URL can be filled out from the script. So this is just a matter of convenience. And consistency: passing a password to the interactive shell mode from a script works.
