### ISSUE TITLE
Restoring from backup fails in 5.0.0

### ISSUE THREAD

**Issue by ttasovac** [eXist-db/exist#2064]
### What is the problem
Restoring from backup fails in 5.0.0 with the message

```
Starting restore of backup...
Processing backup: /Users/ttasovac/Downloads/test.zip#db/test/__contents__.xml
Creating collection /db/test
An unrecoverable error occurred while restoring
collection '/db/test': Database instance 'exist' is not available. Aborting restore!
Finished restore of backup.
```
### Describe how to reproduce or add a test
1.  Create a new collection ("test")
2. Back up the collection "test" 
3. Restore from the previously made backup
4. The restore will fail.

### Context information
Please always add the following information
- eXist-db version: 5.0.0RC1 and 5.0.0RC2
- Java version: 1.8.0_144-b01
- Operating system: Mac OS
- 64 bit
- How is eXist-db installed? DMG

**Comment by adamretter** [comment]
Thanks for reporting @ttasovac. I have sent a PR with a fix for this, in the mean time you might be able to workaround by using the restore function of the Dashboard?
