### ISSUE TITLE
NPE in LuceneMatchListener.scanMatches when expanding node containing both Lucene & NGram matches

### ISSUE THREAD

**Issue by joewiz** [eXist-db/exist#2102]
### What is the problem

In a search application I'm building, I encountered an NPE when using `util:expand` to expand hits in a query that includes hits on Lucene full text and ngram indexes. 

### What did you expect

[The documentation](https://exist-db.org/exist/apps/doc/kwic) indicates that Lucene full text and ngram indexes both support match highlighting, so it should be possible to apply `util:expand` to a node that contains hits from both index types. Doing so should certainly not cause an NPE.

### Describe how to reproduce or add a test

The following query will reproduce the error, in the form of 3 tests wrapped in try-catch blocks. While test 1 is correct, tests 2 and 3 trigger an NPE:

```xquery
xquery version "3.1";

(: setup :)
let $data := 
    <root>
        <x>Hello</x>
        <y>Hello</y>
    </root>
let $xconf := 
    <collection xmlns="http://exist-db.org/collection-config/1.0">
        <index>
            <lucene>
                <text qname="x"/>
            </lucene>
            <ngram qname="y"/>
        </index>
    </collection>
let $xconf-col := xmldb:create-collection("/db/system/config/db", "temp")
let $store-xconf := xmldb:store($xconf-col, "collection.xconf", $xconf)
let $data-col := xmldb:create-collection("/db", "temp")
let $store-data := xmldb:store($data-col, "test.xml", $data)

(: the heart of the test :)
let $q := "Hello"
let $doc := doc($store-data)
let $x-hits := $doc/root[ft:query(x, $q)]
let $y-hits := $doc/root[ngram:contains(y, $q)]
let $hits := ($x-hits | $y-hits)
return
    <tests>
        <test n="1">{ try { util:expand($x-hits) } catch * { $err:code } }</test>
        <test n="2">{ try { util:expand($y-hits) } catch * { $err:code } }</test>
        <test n="3">{ try { util:expand($hits)   } catch * { $err:code } }</test>
    </tests>
```

The results I would have expected:

```xml
<tests>
    <test n="1">
        <root>
            <x><exist:match xmlns:exist="http://exist.sourceforge.net/NS/exist">Hello</exist:match></x>
            <y>Hello</y>
        </root>
    </test>
    <test n="2">
        <root>
            <x>Hello</x>
            <y><exist:match xmlns:exist="http://exist.sourceforge.net/NS/exist">Hello</exist:match></y>
        </root>
    </test>
    <test n="3">
        <root>
            <x><exist:match xmlns:exist="http://exist.sourceforge.net/NS/exist">Hello</exist:match></x>
            <y><exist:match xmlns:exist="http://exist.sourceforge.net/NS/exist">Hello</exist:match></y>
        </root>
    </test>
</tests>
```

The actual results:

```xml
<tests>
    <test n="1">
        <root>
            <x><exist:match xmlns:exist="http://exist.sourceforge.net/NS/exist">Hello</exist:match></x>
            <y>Hello</y>
        </root>
    </test>
    <test n="2">java:java.lang.NullPointerException</test>
    <test n="3">java:java.lang.NullPointerException</test>
</tests>
```

To obtain a full stack trace of the NPE, remove the try-catch block from the 2nd or 3rd test. The key portion from of the trace from exist.log is:

```text
2018-08-09 01:18:30,855 [qtp2027762133-72] ERROR (XQueryServlet.java [process]:552) - null 
java.lang.NullPointerException: null
	at org.exist.indexing.lucene.LuceneMatchListener.scanMatches(LuceneMatchListener.java:217) ~[exist-index-lucene.jar:4.3.1]
	at org.exist.indexing.lucene.LuceneMatchListener.startElement(LuceneMatchListener.java:128) ~[exist-index-lucene.jar:4.3.1]
	at org.exist.indexing.AbstractMatchListener.startElement(AbstractMatchListener.java:100) ~[exist.jar:4.3.1]
	at org.exist.indexing.ngram.NGramIndexWorker$NGramMatchListener.startElement(NGramIndexWorker.java:770) ~[exist-index-ngram.jar:4.3.1]
	at org.exist.storage.serializers.NativeSerializer.serializeToReceiver(NativeSerializer.java:271) ~[exist.jar:4.3.1]
	at org.exist.storage.serializers.NativeSerializer.serializeToReceiver(NativeSerializer.java:273) ~[exist.jar:4.3.1]
	at org.exist.storage.serializers.NativeSerializer.serializeToReceiver(NativeSerializer.java:99) ~[exist.jar:4.3.1]
	at org.exist.storage.serializers.Serializer.serializeToReceiver(Serializer.java:1065) ~[exist.jar:4.3.1]
	at org.exist.storage.serializers.Serializer.toSAX(Serializer.java:870) ~[exist.jar:4.3.1]
	at org.exist.dom.persistent.NodeProxy.toSAX(NodeProxy.java:712) ~[exist.jar:4.3.1]
	at org.exist.xquery.functions.util.Expand.eval(Expand.java:113) ~[exist.jar:4.3.1]
```

### Context information

- eXist-db version + Git Revision hash: eXist 4.3.1 release (3b195797a2c2f35913891412859b06d94f189229)
- Java version: 10.0.2+13
- Operating system: macOS 10.13.6
- 32 or 64 bit: 64 bit
- How is eXist-db installed? DMG
- Any custom changes in e.g. conf.xml: none

**Comment by dizzzz** [comment]
According to [the code](https://github.com/eXist-db/exist/blob/e2276c54b046eddb8b81579f1714303fad92a66a/extensions/indexes/lucene/src/org/exist/indexing/lucene/LuceneMatchListener.java#L217)  an index configuration is missing at that point of execution.... (constructed by [this line](https://github.com/eXist-db/exist/blob/e2276c54b046eddb8b81579f1714303fad92a66a/extensions/indexes/lucene/src/org/exist/indexing/lucene/LuceneMatchListener.java#L172))

**Comment by adamretter** [comment]
@joewiz Did you resolve this one?

**Comment by duncdrum** [comment]
@joewiz ?

**Comment by joewiz** [comment]
@adamretter @duncdrum @dizzzz I just confirmed that the problem is still present in 5.2.0 (release version).

**Comment by marmoure** [comment]
in my initial testing of this issue i came with the expectation that only test 1 will yield results , when tested seems like the NPE does not happen in test `2`
tested by 
```xquery
xquery version "3.1";

(: setup :)
let $data := 
    <root>
        <x>Hello</x>
        <y>Hello</y>
    </root>
let $xconf := 
    <collection xmlns="http://exist-db.org/collection-config/1.0">
        <index>
            <lucene>
                <text qname="x"/>
            </lucene>
            <ngram qname="y"/>
        </index>
    </collection>
let $xconf-col := xmldb:create-collection("/db/system/config/db", "temp")
let $store-xconf := xmldb:store($xconf-col, "collection.xconf", $xconf)
let $data-col := xmldb:create-collection("/db", "temp")
let $store-data := xmldb:store($data-col, "test.xml", $data)

(: the heart of the test :)
let $q := "Hello"
let $doc := doc($store-data)
let $y-hits := $doc/root[ngram:contains(y, $q)]
return
    <tests>
        <test n="2">{ try { util:expand($y-hits) } catch * { $err:code } }</test>
    </tests>
```
the results we get are like this
```xml
<tests>
    <test n="2">
        <root>
            <x>Hello</x>
            <y><exist:match xmlns:exist="http://exist.sourceforge.net/NS/exist">Hello</exist:match></y>
        </root>
    </test>
</tests>
```

**Comment by adamretter** [comment]
@marmoure Running Joe's example query on eXist-db 6.2.0, I can confirm that I see the same problem that he reported, i.e. the results are:

```xml
<tests>
    <test n="1">
        <root>
            <x>Hello</x>
            <y>Hello</y>
        </root>
    </test>
    <test n="2">java:java.lang.NullPointerException</test>
    <test n="3">java:java.lang.NullPointerException</test>
</tests>
```

What is really interesting, is that what you have discovered is that there seems to be some state polluting the results depending on whether n 1,2, or 3, is involved. For example:

-----
## Scenario 1
```
let $q := "Hello"
let $doc := doc($store-data)
let $x-hits := $doc/root[ft:query(x, $q)]
let $y-hits := $doc/root[ngram:contains(y, $q)]
let $hits := ($x-hits | $y-hits)
return
    <tests>
        <test n="1">{ try { util:expand($x-hits) } catch * { $err:code } }</test>
        <test n="2">{ try { util:expand($y-hits) } catch * { $err:code } }</test>
        <test n="3">{ try { util:expand($hits)   } catch * { $err:code } }</test>
    </tests>

**Comment by adamretter** [comment]
@joewiz My findings around the missing `exist:match` may be premature... I am confused… I have tried running your original query on eXist-db 4.3.1, and I don’t get the results that you reported in the issue.


So against eXist-db 4.3.1, you reported the results as:
```xml
<tests>
    <test n="1">
        <root>
            <x><exist:match xmlns:exist="http://exist.sourceforge.net/NS/exist">Hello</exist:match></x>
            <y>Hello</y>
        </root>
    </test>
    <test n="2">java:java.lang.NullPointerException</test>
    <test n="3">java:java.lang.NullPointerException</test>
</tests>
```
But trying to reproduce it now on eXist-db 4.3.1 I am seeing:
```xml
<tests>
    <test n="1">
        <root>
            <x>Hello</x>
            <y>Hello</y>
        </root>
    </test>
    <test n="2">java:java.lang.NullPointerException</test>
    <test n="3">java:java.lang.NullPointerException</test>
</tests>
```

**Comment by marmoure** [comment]
i have tested this scenario in `exist 4.3.1` and all sub scenarios and `exist:match` is not working properly  
the match on the ngram hit seems to be stable but the match on the `ft:query` is always on and off

**Comment by joewiz** [comment]
I was unable to get eXist 4.x running on my system, but I agree we need to reassess this issue against the current stable version of eXist, 6.2.0. I can reproduce the results that @marmoure and @adamretter shared in eXist 6.2.0. I can, however, see `<exist:match>` if I change one thing about the original test: adding a single whitespace following the word "Hello" in the `<x>` and `<y>` elements. I can also achieve different results if I change `$x-hits` from:

`$doc/root[ft:query(x, $q)]`

... to:

`$doc/root/x[ft:query(., $q)]`

My preliminary takeaways are:

- The `util:expand()` function can under some circumstances fail to wrap hits with `<exist:match>` elements. 
- There seems to be some pollution of state when `ngram:contains()` and `ft:query()` are used in the same query.
- We need to break down this monolithic test into atomic ones to tease out the variations we see in the setup. 

@adamretter Do you think XQSuite would be the best approach for splitting up the tests?

**Comment by marmoure** [comment]
@joewiz you can use docker to run exist 4.3.1
docker pull existdb/existdb:4.3.1
Then 
docker run -it -p 8080:8080 existdb/existdb:4.3.1

**Comment by joewiz** [comment]
@marmoure Thanks for the tip! I'd forgotten about Docker. I think 4.x is pretty much out of scope now, except perhaps to try to find out when any regressions were introduced.

**Comment by adamretter** [comment]
@joewiz So apart from the NPE in this ticket (which we will shortly send a PR for), I believe we have identified 3 other issues that should be dealt with separately, each with their own distinct GitHub issue:

1. The `exist:match` element sometimes appears and sometimes does not appear when running the same query multiple times.

2. The `exist:match` element when used with `ft:query` fails to be correctly added for `<x>Hello</x>`, it is only added if you introduce whitespace, i.e. `<x>Hello </x>`. Do you agree that it should match both?

3. The two queries `$doc/root[ft:query(x, $q)]` and `$doc/root/x[ft:query(., $q)]` appear to produce different results (with regards to `exist:match`). Do you agree that should not be the case?


> Do you think XQSuite would be the best approach for splitting up the tests?

I don't think its the best as XQSuite doesn't offer strict isolation guarantees between tests (i.e. side-effects if they exist can cause one test to effect another)... but I think we can try and make it work.

**Comment by marmoure** [comment]
@joewiz  for me i can't see the difference between
`$doc/root[ft:query(x, $q)]`
and
`$doc/root/x[ft:query(., $q)]`
i m seeing consistent results none of them produce a match for me
on the other hand add a space to the `<x>Hello</x>` produce a match for me
if we try
```xquery
let $q := "Hello"
let $doc := doc("/db/temp/test.xml")
let $x-hits := $doc/root[ft:query(x, $q)]
return util:expand($x-hits)  
```
i m getting
```xml
<root>
    <x><exist:match xmlns:exist="http://exist.sourceforge.net/NS/exist">Hello</exist:match> </x>
    <y><exist:match xmlns:exist="http://exist.sourceforge.net/NS/exist">Hello</exist:match></y>
</root>
```

**Comment by marmoure** [comment]
after the fix to the NPE was introduced i m seeing something odd with the matches
the ngram hit is being wrapped twice 
the full test 
```xquery
xquery version "3.1";
(: setup :)
let $data := 
    <root>
        <x>Hello </x>
        <y>Hello</y>
    </root>
let $xconf := 
    <collection xmlns="http://exist-db.org/collection-config/1.0">
        <index>
            <lucene>
                <text qname="x"/>
            </lucene>
            <ngram qname="y"/>
        </index>
    </collection>
let $xconf-col := xmldb:create-collection("/db/system/config/db", "temp")
let $store-xconf := xmldb:store($xconf-col, "collection.xconf", $xconf)
let $data-col := xmldb:create-collection("/db", "temp")
let $store-data := xmldb:store($data-col, "test.xml", $data)

(: the heart of the test :)
let $q := "Hello"
let $doc := doc("/db/temp/test.xml")
let $x-hits := $doc/root[ft:query(x, $q)]
let $y-hits := $doc/root[ngram:contains(y, $q)]
let $hits := ($x-hits | $y-hits)
return util:expand($y-hits)
```
the results
```xml
<root>
    <x><exist:match xmlns:exist="http://exist.sourceforge.net/NS/exist">Hello</exist:match> </x>
    <y><exist:match xmlns:exist="http://exist.sourceforge.net/NS/exist"><exist:match>Hello</exist:match></exist:match></y>
</root>
```
