### ISSUE TITLE
JMX servlet does not contain eXist-db specific information

### ISSUE THREAD

**Issue by dizzzz** [eXist-db/exist#2118]
### What is the problem
The url http://localhost:8080/exist/status does not return all required information for the Monex app. As a result the Monex app does not work as expected.

in logging:

```
2018-08-16 10:25:52,196 [main] WARN  (AgentFactory.java [getInstance]:46) - Failed to instantiate class for JMX agent: org.exist.management.impl.JMXAgent 
```

with debugger

```
java.lang.IllegalAccessException: Class org.exist.management.AgentFactory can not access a member of class org.exist.management.impl.JMXAgent with modifiers "private"
```

![image](https://user-images.githubusercontent.com/1700062/44214884-6e609580-a171-11e8-9b26-0614556c4fff.png)

### What did you expect
The XML file should contain the sections as defined in `org/exist/management/impl/JMXAgent.java`

### Describe how to reproduce or add a test
- Start monex
- retrieve XML via URL

### Context information

- eXist-db version : 4.x.x / 24ec68348bcd7854d65b75c396de3acdfbd2932a
- Java version (e.g. Java8u121) // java8U172
- Operating system (Windows 7, Linux, MacOs) / windows
- 32 or 64 bit / 64
- How is eXist-db installed? (JAR installer, DMG, WAR file, clone from GitHub) / clone
- Any custom changes in e.g. conf.xml / nope

**Comment by duncdrum** [comment]
yup same as 5.0.0 logs a couple:
```
16 Aug 2018 15:11:23,987 [main] WARN  (AgentFactory.java [getInstance]:53) - No default constructor found for Agent: org.exist.management.impl.JMXAgent. Will try singleton pattern…
16 Aug 2018 15:11:25,578 [main] ERROR (PluginsManagerImpl.java [addPlugin]:239) - java.lang.ClassNotFoundException: org.exist.storage.md.MDStorageManager 
16 Aug 2018 15:11:25,579 [main] ERROR (PluginsManagerImpl.java [addPlugin]:239) - java.lang.ClassNotFoundException: org.exist.monitoring.MonitoringManager 
```

Not sure about the storage manage, but MonitoringManager sounds relevant.
