### ISSUE TITLE
backup/restore not working

### ISSUE THREAD

**Issue by andray71** [eXist-db/exist#2151]
### What is the problem

executing command:

```bash
bin/backup.sh -u admin -p [password] -r /backup/backup-config-service.zip
```

getting errors:

```bash
/opt/exist/bin/functions.d/eXist-settings.sh: line 74: $'-Dfile.encoding=UTF-8;\n    fi\n\n    OS=Linux\n    if [  == Darwin ]; then\n\tCLIENT_NAME=Client\n        JAVA_OPTIONS=': command not found
/opt/exist/bin/functions.d/eXist-settings.sh: line 34: locale: command not found
/opt/exist/bin/functions.d/eXist-settings.sh: line 35: locale: command not found
Using locale: en_US.UTF-8
```

### What did you expect

restored content from the zip file (old backup)

works fine when i restore it using Java Admin UI

older versions (3.*) worked fine.

### Describe how to reproduce or add a test

running the eXist in alpine docker image

### Context information

- eXist-db version  - 4.3.1
- Java version - 1.8.0_171
- Operating system - Linux 4.9.93-linuxkit-aufs amd64
- 64 bit
- How is eXist-db installed? Jar inside alpine docker image
- Any custom changes - no

**Comment by duncdrum** [comment]
From the error message I would say this is a problem with how Java is configured inside alpine. You could try with the exist-db provided images. Or we need more info about your docker configuration, whats the base image, how do you install java, how do you install exist, etc.

**Comment by omkarnix** [comment]
If no one else is working on this issue, I would like to give a try to investigate.

**Comment by joewiz** [comment]
@omkarnix That would be great, thank you!

**Comment by duncdrum** [comment]
@andray71 is this still a problem? without more info I'm afraid this will be a nofix

**Comment by dizzzz** [comment]
2 years no response. please feel free to re-open/add details
