### ISSUE TITLE
REST interface does not accept accented characters

### ISSUE THREAD

**Issue by eriksiegel** [eXist-db/exist#2160]
### What is the problem
I have XML files in my database with accented characters in their filenames that I would like to access with REST. For instance `/db/TEST/bäk.xml`

I do not seem to be able to access this file using the REST interface. I tried (in the Chrome's address bar) `http://.../exist/rest/db/TEST/bäk.xml` and `http://.../exist/rest/db/TEST/b%C3%A4k.xml` but all yield the same result: _Document /db/TEST/bäk.xml not found_

I _suppose_  the problem is with multibyte Unicode characters in general?

BTW, I also need this for the PUT and DELETE REST functionality but that fails as well. 

### What did you expect
The contents of the file

### Describe how to reproduce or add a test
Create a file with an accented character somewhere. Try to retrieve it using REST

### Context information
- eXist 4.3.1 build 201807241821
- Java version 1.8.0_181
- Operating system W10
- 64 bit
- JAR installed
- Any custom changes in e.g. conf.xml? Data directory moved to outside eXist installation directory

**Comment by joewiz** [comment]
I suspect that underlying this is the phenomenon I described in https://github.com/eXist-db/exist/issues/1824#issuecomment-381876383. I don't think I had ever quite encountered this aspect of it - where there's no way at all to address a resource over REST - though I am able to see it over WebDAV via http://localhost:8080/exist/webdav/db/b%C3%A4k.xml. That URL opens up just fine for me in Chrome. But if I change `webdav` to `rest`, I get your result:

> HTTP ERROR 404
>
> Problem accessing /exist/rest/db/b%C3%A4k.xml. Reason:
> 
>    Document /db/bäk.xml not found

**Comment by duncdrum** [comment]
@joewiz agreed
@eric consolidating this ticket, please continue the discussion in #1824
