### ISSUE TITLE
Unable to start eXist-db.app with Java 11

### ISSUE THREAD

**Issue by joewiz** [eXist-db/exist#2171]
### What is the problem

Starting eXist-db.app with Java 11 on macOS yields the following error:

> This application requires that Java 8 or later be installed on your computer. Please download and install the latest version of Java from www.java.com and try again.

This problem is analogous to https://github.com/eXist-db/exist/issues/1792 and is caused by a version string parsing bug in the "appbundler" tool used to create eXist-db.app, https://bitbucket.org/infinitekind/appbundler. 

References:
- Commit in default branch addressing version checking (2017-08-01) https://bitbucket.org/infinitekind/appbundler/commits/ce0600b603c11a1fe120b6de3aa9a3feb97971b8
- @adamretter's self-built, self-patched appbundler jar (2018-01-14): https://github.com/eXist-db/exist/pull/1687
- Unmerged PR addressing version checking (2018-01-30): https://bitbucket.org/infinitekind/appbundler/pull-requests/48/workaround-for-java-9/diff
- A mavenized fork of appbundler on GitHub (last updated 2017-12-11): https://github.com/teras/appbundler. Contains a commit addressing version checking (2017-12-08): https://github.com/teras/appbundler/commit/873c9abbbabb5098b2e432de73f726e9e6242682.

### What did you expect

I expected eXist-db.app to start with any version of Java 8 or higher.

### Describe how to reproduce or add a test

1. Install Java 11. Uninstalling other versions of Java may be necessary to prevent earlier versions from being the system default. Opening a new Terminal window and running `java -version` should report Java 11.
2. Download eXist-db-4.4.0 DMG installer, open the DMG, and drag eXist-db.app into the Applications folder. 
3. Start eXist-db.app

Alternative route: `brew cask install java exist-db` and start /Applications/eXist-db.app.

### Context information

- eXist-db version + Git Revision hash: eXist 4.4.0 release
- Java version: Java 11
- Operating system: macOS 10.13
- 32 or 64 bit: 64 big
- How is eXist-db installed? DMG
- Any custom changes in e.g. conf.xml: none

**Comment by joewiz** [comment]
I've confirmed that a PR submitted to the appbundler code base fixes the issue: https://bitbucket.org/infinitekind/appbundler/pull-requests/49/account-for-change-in-location-of-jdk/diff. I'll prepare a PR built from this branch.

**Comment by duncdrum** [comment]
work for me @joewiz want to do the honors of closing?

**Comment by joewiz** [comment]
@duncdrum Thanks!

Closed by https://github.com/eXist-db/exist/pull/2187.
