### ISSUE TITLE
XXE in RESTServer.java

### ISSUE THREAD

**Issue by ProDigySML** [eXist-db/exist#2180]
# The Issue

An XML External Entity attack is a type of attack against an application that parses XML input. This attack occurs when XML input containing a reference to an external entity is processed by a weakly configured XML parser. This attack may lead to the disclosure of confidential data, denial of service, server side request forgery, port scanning from the perspective of the machine where the parser is located, and other system impacts.

# Where the Issue Occurred

The following code snippets display the usage of `XMLReader` without securely disabling entities:

https://github.com/eXist-db/exist/blob/3d5ceea8762702b74209836f58cbc5c0d00f1211/src/org/exist/http/RESTServer.java#L970

The insecure XML parsing is used within the REST server in the following code:

https://github.com/eXist-db/exist/blob/3d5ceea8762702b74209836f58cbc5c0d00f1211/src/org/exist/http/RESTServer.java#L318

**Comment by dizzzz** [comment]
I am pretty sure things have already been fixed with https://github.com/eXist-db/exist/pull/2145

**Comment by ProDigySML** [comment]
@dizzzz Unfortunately the parser here is different to what has been patched previously (as far as I know). 
![image](https://user-images.githubusercontent.com/16996819/46252630-a6683180-c4ae-11e8-8878-51f11b126386.png)

**Comment by dizzzz** [comment]
Right you are! we should get the XMLparser here from the pool too... @adamretter @wolfgangmm

**Comment by dizzzz** [comment]
please could you file this issue at security@exist-db.org ?
