### ISSUE TITLE
New feature requirement: actual file sizes of indexes in jmx status report

### ISSUE THREAD

**Issue by pwin** [eXist-db/exist#2184]
### What is the problem
I had a paradoxical extremely large index file (ngram.dbx) occur in exist-db v2.1 but did not "see" this developing from the data in e.g. monex

### What is the suggestion
proposal for jmx information to be extended to include actual size of the index files (in addition to the memory footprint of the index caches)

**Comment by adamretter** [comment]
@duncdrum I don't think this should have been moved. The JMX info is part of the eXist-db project.

**Comment by duncdrum** [comment]
Yes but the code that displays it, sits here. To address the OP, we could also report the filesize without modifying the jmx report.
