### ISSUE TITLE
map with duplicate keys should throw an error

### ISSUE THREAD

**Issue by line-o** [eXist-db/exist#2203]
### What is the problem

The following code

```xquery
map { 'a': 1, 'a': 2 }
```

evaluates to

```xquery
map { 'a': 2 }
```

### What did you expect

An error should be raised, that key 'a' was entered twice.
BaseX does exactly that:

```
XQUERY map {'a':1, 'a':2}
Stopped at ., 1/5:
[XQDY0137] Key "a" already exists in map (values: 1 vs. 2).
```

This should not affect `map:put` or `map:merge` where this actually overwrites the given key in the returned, new map.

### Context information

- eXist-db 5.0.0-RC3 /  bfdcc8406 
- Java version: 1.8.0_152
- Operating system: MacOS (Mojave)
- build from source / clone from GitHub

**Comment by duncdrum** [comment]
Yup, the [specs](https://www.w3.org/TR/xquery-31/#id-map-constructors) are pretty unambiguous.
