### ISSUE TITLE
ActiveMQ: Synchronization between servers

### ISSUE THREAD

**Issue by sunxinpeng1994** [eXist-db/exist#2228]
The original question is on [stackoverflow](https://stackoverflow.com/questions/52599870/exist-db-content-synchronize-issue-between-different-servers)

### What is the problem
There are two eXist-db servers. One is master and one is slave. I know we can replicate the content using ActiveMQ when they are running in the same time(I made this work). But I want to know is there a way to replicate the content manually? Like synchronizing content from A server when B server starts. Actually, they are the same folder in two servers.

### What did you expect
Use xQuery to synchronize contents between two servers manually.

### Describe how to reproduce or add a test
Just install two servers and activeMQ.

### collection.xconf of target folder as below
```xml
<collection xmlns="http://exist-db.org/collection-config/1.0">
    <triggers>
        <trigger class="org.exist.jms.replication.publish.ReplicationTrigger">
            <!-- 
                Class name of the initial context provider, default value 
                for ActiveMQ
                see javax.naming.Context#INITIAL_CONTEXT_FACTORY
            -->
            <parameter name="java.naming.factory.initial" value="org.apache.activemq.jndi.ActiveMQInitialContextFactory"/>
            <!-- 
                URL of the message broker, default value for ActiveMQ 
                see javax.naming.Context#PROVIDER_URL
            --> 
            <parameter name="java.naming.provider.url" value="tcp://localhost:61616"/>
            <!-- 
                Lookup connection factory
                see javax.naming.InitialContext#lookup(String) 
            -->
            <parameter name="connection-factory" value="ConnectionFactory"/>
            <!--
                Lookup destination (topic)
                see javax.naming.InitialContext#lookup(String) 
            -->
            <parameter name="destination" value="dynamicTopics/eXistdb-replication-example"/>
        </trigger>
        <trigger event="update" class="org.exist.collections.triggers.XQueryTrigger">
            <parameter name="url" value="xmldb:exist:///db/triggerUpdate.xql"/>
        </trigger>
    </triggers>
</collection>
```

### Context information
Please always add the following information
- eXist-db 3.4.1
- Java version 1.8.0_181
- Operating system Linux redhat
- 64 bit
- How is eXist-db installed? JAR installer
- Any custom changes in e.g. conf.xml Enable startupTrigger

**Comment by dizzzz** [comment]
What version of the extension are you using?

**Comment by sunxinpeng1994** [comment]
> What version of the extension are you using?

Messaging and Replication
Version: 0.30.2

**Comment by sunxinpeng1994** [comment]
Can I have the document about `function replication:sync()`? Because I don't find anything related.

**Comment by dizzzz** [comment]
if you use eXide you should be able to see which functions are available....

the code should look like

```xquery
xquery version "3.0";

import module namespace replication="http://exist-db.org/xquery/replication" 
              at "java:org.exist.jms.xquery.ReplicationModule"; 

replication:sync("/db/resource.xml")
```
