### ISSUE TITLE
LDAP: Different hasGroup() and findAllGroupNames() implementations lead to 500 in web user manager

### ISSUE THREAD

**Issue by simar0at** [eXist-db/exist#2281]
### What is the problem
LDAPRealm contains a findAllGroupNames() implementation that returns all groups in LDAP. This could be a very large number, only a view of them relevant to a particular exist instance. The caching mechanism now only saves groups to the local instance which are actually used by some LDAP user account exist read from LDAP. There are filter options for this and there are default groups in an LDAP/AD database that don't have any users assigned at all.
Yet there is the hasGroup() function that assumes that any group returned by findAllGroupNames() can be found when looking at the local cache.
This makes e. g. the logic in web UI user manager fail with error 500

### What did you expect
Either hasGroup() needs to check against the LDAP DB or the listing returned by findAllGroupNames() should only contain locally cached groups. The latter could be achieved by using the very simple findAllGroupNames() implementation found in other real implementations.

### Describe how to reproduce or add a test

1. Configure LDAP
1. Let exist read the users from the DB
1. Try to open the web user manager.
1. It reports a 500 error from the server and the groups list is empty.

### Context information
Please always add the following information
- eXist 4.5.0-SNAPSHOT Git commit: f62496a5e Git branch: develop-4.x.x
- jdk1.8.0_192
- Windows 10
- 64 bit
- Compiled with IntelliJ IDEA from git source
- Enabled LDAP and configured it to read from an UCS Core Edition Samba AD replacement

**Comment by adamretter** [comment]
@simar0at Could you please test the fix https://github.com/eXist-db/exist/pull/2327 and report back.
