### ISSUE TITLE
LockTable change - LinkedTransferQueue -> LinkedBlockingQueue

### ISSUE THREAD

**Issue by adamretter** [eXist-db/exist#2287]
We don't need the complexity of a TransferQueue.

TransferQueue offers additional synchronisations e.g allowing the producer to wait upon the consumer,  we don't need such functionality, and so can use the simpler LinkedBlockingQueue. This could mean that LinkedBlockingQueue has less overhead than LinkedTransferQueue, and we could benefit from that.

**Comment by duncdrum** [comment]
care to expand a bit?

**Comment by adamretter** [comment]
@duncdrum I wrote a little more.

**Comment by adamretter** [comment]
We no longer use a queue in the LockTable, so this is no longer relevant.
