### ISSUE TITLE
BackupSystemTask is not limiting the backups as folders

### ISSUE THREAD

**Issue by claudius108** [eXist-db/exist#2387]
### What is the problem
A backup job as below is not limiting the number of backups in case when suffix is not equal with ".zip
```xml
<job type="system" class="org.exist.storage.BackupSystemTask" cron-trigger="0 0 3 ? * * *">
        <parameter name="dir" value="/home/claudius/exist-db/backup" />
        <parameter name="prefix" value="full-backup-" />
        <parameter name="collection" value="/db" />
        <parameter name="user" value="admin" />
        <parameter name="password" value="password" />
        <parameter name="zip-files-max" value="2" />
</job>
```
### What did you expect
I would expect only two backups to be maintained.

### Describe how to reproduce or add a test
Anyone can reproduce this issue, by using the above backup job in conf.xml.

### Context information
- eXist-db 4.4.0 / ab5716180
- java version "1.8.0_191"
- ubuntu 18
- 64 bit
- How is eXist-db installed? - JAR installer

**Comment by claudius108** [comment]
Hi,

I found the line that does not allow purging of backups if the suffix is not equal with ".zip", in class BackupSystemTask:
line 110 - if (".zip".equals(suffix) && zipFilesMax > 0) {

I would rather replace the parameter "zip-files-max" with "max-backups", and let the case of backup up as zip files being idempotent with case of backup as folder, for large databases.

**Comment by claudius108** [comment]
I am currently testing a small fix, for a PR.

**Comment by duncdrum** [comment]
see #891
