### ISSUE TITLE
Collection names displayed using URL quoting

### ISSUE THREAD

**Issue by zopyx** [eXist-db/exist#241]
I created a collection through the web with name 'ß'. The collection browser display the name of this collection as the url encoded represenation of the UTF8 char values.

![screenshot 2014-06-15 20 04 29](https://cloud.githubusercontent.com/assets/594239/3281600/da030996-f4b7-11e3-9daf-5e8c0d938358.png)

**Comment by duncdrum** [comment]
duplicate of #1824
