### ISSUE TITLE
Disable _xquery and _xupdate execution by default

### ISSUE THREAD

**Issue by joewiz** [eXist-db/exist#2428]
### What is the problem

XQuery and XUpdate execution is allowed by default. While a mechanism for disabling them was added in https://github.com/eXist-db/exist/pull/1419 and documented in https://github.com/eXist-db/documentation/pull/163, they should be disabled by default. This would change the eXist API and so would require a major release. We didn't do this in 4.0.0, so 5.0.0 is an opportunity before us.

### What did you expect

Secure by default.

### Describe how to reproduce or add a test

n/a

### Context information

- eXist-db version + Git Revision hash: eXist 4.x
- Java version: all
- Operating system: all
- 32 or 64 bit: all
- How is eXist-db installed? all
- Any custom changes in e.g. conf.xml: none

**Comment by adamretter** [comment]
I don't think this should be disabled by default, instead it should be in the Production Good Practice section of the docs.

Disabling this by default reduces functionality that is widely documented both in our documentation, the eXist-db book, and elsewhere.

**Comment by duncdrum** [comment]
My main concern with disabling this by default is for tools, docker, node, puppet etc all might directly or indirectly rely on this behaviour. No other db software that I know comes as a hardened production-system OOTB.

**Comment by dizzzz** [comment]
What about detecting that the  _xquery and _xupdate execution is switched on , and have this explicitly logged into STDOUT and exist.log ? Like an "advisory" ...

The atleast ppl will be informed and can then actively take actions.....

**Comment by joewiz** [comment]
Sounds like changing the default would hurt more than it helps, and the focus should be on making it very clear to amateurs / first time deployers of web apps that they need to read the Best Practices document. On exist-open, Duncan also pointed out that the docs cover this and he asked the question about how we could communicate the existence of this better. Dannes' idea here is a concrete proposal in that direction, which sounds good to me! Maybe the notice could also include a link to the Best Practices document? I think this issue can be closed - unless there are other opinions in the next few days?
