### ISSUE TITLE
existdb is not responding: System maintenance task reported error: this IndexWriter is closed

### ISSUE THREAD

**Issue by sbhusala** [eXist-db/exist#2444]
### What is the problem
[exist.20190115000317.log](https://github.com/eXist-db/exist/files/2804870/exist.20190115000317.log)

existdb is not responding throwing an error as System maintenance task reported error: this IndexWriter is closed
We would like to know the cause for this behavior 
### What did you expect
eXistdb should works as expected in this case eXistdb was not responded and application could not able to read the data.
### Describe how to reproduce or add a test
Currently we could not able to reproduce the issue, issue was resolved after restart of eXistdb service.

### Context information
Please always add the following information
- eXist-db version 4.3.0
- Java version openjdk version "1.8.0_161"
- Operating system -Linux
-  64 bit
- How is eXist-db installed? --> JAR installer
- Any custom changes in e.g. [conf.xml](url)

**Comment by duncdrum** [comment]
Very quick guess. The log shows exist '4.2.1'. Could you be trying to access exist via oxygen, using the old jar files saved by oxygen? If so delete the old connection in oxygen, and then create a new one.

**Comment by adamretter** [comment]
According to the log file your server ran out of memory and crashed, i.e.

```
 Caused by: java.lang.OutOfMemoryError: GC overhead limit exceeded
```

**Comment by sbhusala** [comment]
Hi Adam,

Thanks, Can you please suggest what are the actions to take in order to resolve these issues.

Regards,
Srinu B

**Comment by duncdrum** [comment]
@sbhusala impossible to say without looking at your code. Provided that you have no bad code, then the only way is to increase the memory available to exist on the server. 

However since this does not appear to be a bug, i would invite you to take the discussion to the mailing list or to stackoverflow, issues are for bug reports only. Thx

**Comment by dizzzz** [comment]
no response since months.
