### ISSUE TITLE
Collection without group leads to java-error

### ISSUE THREAD

**Issue by ChiSamurai** [eXist-db/exist#246]
We had a problem with a recursive function checking permissions using the security module function sm:get-permissions(). Our function broke up due to a java exception because one collection had an owner but was missing a group.

Maybe this should better not lead into java-exception but in some exist-exception or into an entry in the error log?

> An error occurred: null
> 
> Caused by:
> 
> javax.servlet.ServletException: An error occurred: null
>     at org.exist.http.servlets.EXistServlet.doGet(EXistServlet.java:256)
>     at javax.servlet.http.HttpServlet.service(HttpServlet.java:735)
>     at javax.servlet.http.HttpServlet.service(HttpServlet.java:848)
>     at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:669)
>     at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:457)
>     at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:137)
>     at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:575)
>     at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:231)
>     at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1075)
>     at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:384)
>     at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:193)
>     at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1009)
>     at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:135)
>     at org.eclipse.jetty.server.Dispatcher.forward(Dispatcher.java:229)
>     at org.eclipse.jetty.server.Dispatcher.forward(Dispatcher.java:103)
>     at org.exist.http.urlrewrite.Forward.doRewrite(Forward.java:46)
>     at org.exist.http.urlrewrite.XQueryURLRewrite.doRewrite(XQueryURLRewrite.java:567)
>     at org.exist.http.urlrewrite.XQueryURLRewrite.service(XQueryURLRewrite.java:355)
>     at javax.servlet.http.HttpServlet.service(HttpServlet.java:848)
>     at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:669)
>     at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1448)
>     at de.betterform.agent.web.filter.XFormsFilter.doFilter(XFormsFilter.java:177)
>     at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1419)
>     at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:455)
>     at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:137)
>     at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:533)
>     at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:231)
>     at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1075)
>     at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:384)
>     at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:193)
>     at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1009)
>     at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:135)
>     at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:154)
>     at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116)
>     at org.eclipse.jetty.server.Server.handle(Server.java:368)
>     at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:488)
>     at org.eclipse.jetty.server.AbstractHttpConnection.headerComplete(AbstractHttpConnection.java:932)
>     at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.headerComplete(AbstractHttpConnection.java:994)
>     at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:640)
>     at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:235)
>     at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:82)
>     at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:628)
>     at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:52)
>     at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:608)
>     at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:543)
>     at java.lang.Thread.run(Thread.java:745)
> Caused by: java.lang.NullPointerException
>     at org.exist.xquery.functions.securitymanager.PermissionsFunction.permissionsToXml(PermissionsFunction.java:489)
>     at org.exist.xquery.functions.securitymanager.PermissionsFunction.functionGetPermissions(PermissionsFunction.java:297)
>     at org.exist.xquery.functions.securitymanager.PermissionsFunction.eval(PermissionsFunction.java:250)
>     at org.exist.xquery.BasicFunction.eval(BasicFunction.java:70)
>     at org.exist.xquery.InternalFunctionCall.eval(InternalFunctionCall.java:56)
>     at org.exist.xquery.DebuggableExpression.eval(DebuggableExpression.java:58)
>     at org.exist.xquery.DebuggableExpression.eval(DebuggableExpression.java:65)
>     at org.exist.xquery.LetExpr.eval(LetExpr.java:189)
>     at org.exist.xquery.LetExpr.eval(LetExpr.java:187)
>     at org.exist.xquery.ForExpr.eval(ForExpr.java:304)
>     at org.exist.xquery.BindingExpression.eval(BindingExpression.java:164)
>     at org.exist.xquery.DebuggableExpression.eval(DebuggableExpression.java:58)
>     at org.exist.xquery.DebuggableExpression.eval(DebuggableExpression.java:65)
>     at org.exist.xquery.LetExpr.eval(LetExpr.java:189)
>     at org.exist.xquery.ForExpr.eval(ForExpr.java:304)
>     at org.exist.xquery.BindingExpression.eval(BindingExpression.java:164)
>     at org.exist.xquery.AbstractExpression.eval(AbstractExpression.java:71)
>     at org.exist.xquery.PathExpr.eval(PathExpr.java:264)
>     at org.exist.xquery.EnclosedExpr.eval(EnclosedExpr.java:80)
>     at org.exist.xquery.AbstractExpression.eval(AbstractExpression.java:71)
>     at org.exist.xquery.PathExpr.eval(PathExpr.java:264)
>     at org.exist.xquery.ElementConstructor.eval(ElementConstructor.java:311)
>     at org.exist.xquery.DynamicCardinalityCheck.eval(DynamicCardinalityCheck.java:74)
>     at org.exist.xquery.functions.system.AsUser.eval(AsUser.java:93)
>     at org.exist.xquery.InternalFunctionCall.eval(InternalFunctionCall.java:56)
>     at org.exist.xquery.AbstractExpression.eval(AbstractExpression.java:71)
>     at org.exist.xquery.PathExpr.eval(PathExpr.java:264)
>     at org.exist.xquery.AbstractExpression.eval(AbstractExpression.java:71)
>     at org.exist.xquery.XQuery.execute(XQuery.java:297)
>     at org.exist.xquery.XQuery.execute(XQuery.java:217)
>     at org.exist.http.RESTServer.executeXQuery(RESTServer.java:1533)
>     at org.exist.http.RESTServer.doGet(RESTServer.java:508)
>     at org.exist.http.servlets.EXistServlet.doGet(EXistServlet.java:222)
>     ... 45 more
> 
> Caused by:
> 
> java.lang.NullPointerException
>     at org.exist.xquery.functions.securitymanager.PermissionsFunction.permissionsToXml(PermissionsFunction.java:489)
>     at org.exist.xquery.functions.securitymanager.PermissionsFunction.functionGetPermissions(PermissionsFunction.java:297)
>     at org.exist.xquery.functions.securitymanager.PermissionsFunction.eval(PermissionsFunction.java:250)
>     at org.exist.xquery.BasicFunction.eval(BasicFunction.java:70)
>     at org.exist.xquery.InternalFunctionCall.eval(InternalFunctionCall.java:56)
>     at org.exist.xquery.DebuggableExpression.eval(DebuggableExpression.java:58)
>     at org.exist.xquery.DebuggableExpression.eval(DebuggableExpression.java:65)
>     at org.exist.xquery.LetExpr.eval(LetExpr.java:189)
>     at org.exist.xquery.LetExpr.eval(LetExpr.java:187)
>     at org.exist.xquery.ForExpr.eval(ForExpr.java:304)
>     at org.exist.xquery.BindingExpression.eval(BindingExpression.java:164)
>     at org.exist.xquery.DebuggableExpression.eval(DebuggableExpression.java:58)
>     at org.exist.xquery.DebuggableExpression.eval(DebuggableExpression.java:65)
>     at org.exist.xquery.LetExpr.eval(LetExpr.java:189)
>     at org.exist.xquery.ForExpr.eval(ForExpr.java:304)
>     at org.exist.xquery.BindingExpression.eval(BindingExpression.java:164)
>     at org.exist.xquery.AbstractExpression.eval(AbstractExpression.java:71)
>     at org.exist.xquery.PathExpr.eval(PathExpr.java:264)
>     at org.exist.xquery.EnclosedExpr.eval(EnclosedExpr.java:80)
>     at org.exist.xquery.AbstractExpression.eval(AbstractExpression.java:71)
>     at org.exist.xquery.PathExpr.eval(PathExpr.java:264)
>     at org.exist.xquery.ElementConstructor.eval(ElementConstructor.java:311)
>     at org.exist.xquery.DynamicCardinalityCheck.eval(DynamicCardinalityCheck.java:74)
>     at org.exist.xquery.functions.system..

**Comment by duncdrum** [comment]
see #101

**Comment by line-o** [comment]
Is it possible to create a collection without a group in eXist 4, 5 or 6?

**Comment by duncdrum** [comment]
It shouldn’t, but I think it is still possible to delete a group and have orphaned accounts it collections afterwards.

**Comment by line-o** [comment]
So the steps to reproduce would be

1. create user U that is only a member of group G
1. create a collection C that belongs to user U and group G
1. remove group G
1. check permissions of collection C

**Comment by duncdrum** [comment]
Yes

**Comment by line-o** [comment]
I can confirm that the steps above do not lead to a NPE

I listed all users and groups that are currently known to the instance. Note the absence of user `U` and group `deleteme` while they are still listed as the owner and the group that collection `orphan-test` was assigned to.

```xquery
map {
    "users": ["SYSTEM","admin","eXide","guest","monex","nobody","packageservice"],
    "groups": ["U","dba","eXide","guest","monex","nogroup","packageservice","test"],
    "collection-permissions": <sm:permission xmlns:sm="http://exist-db.org/xquery/securitymanager" owner="U" group="deleteme" mode="rwxr-xr-x">
    <sm:acl entries="0"/>
</sm:permission>
}
```

**Comment by line-o** [comment]
I would like to close this issue. Anyone against it?

**Comment by duncdrum** [comment]
@line-o i would prefer to close this via PR with a fitting test. The NPE could be triggered by eg. `guest` Trying to write or even read from that collection.

**Comment by line-o** [comment]
The original issue is about reading permissions from a collection "without a group".

I do not see why adding tests covering a collection whose owner and group were removed does affect this.

For me this issue is not reproducible and can therefore be closed.

**Comment by duncdrum** [comment]
Fine by me, I wasn’t able to reliably reproduce either, but I have seen similar crashes in client dbs.

**Comment by line-o** [comment]
A _lot_ has changed in the PermissionsFunction.java class since 2014. I highly doubt this problem still exists.

**Comment by line-o** [comment]
I did dive way deeper into the code than I initially wanted. It seems to me very unlikely to have a situation were permissions to a resource or collection are missing the user or group part. Especially since you can as I tested remove both and the permissions are still readable.
Somewhat related thoughts:
It would be more interesting what happens to the collections and resources if a group or user with the same name are created after they were initially removed.
Since everything else tries to mimic unix style permissions it is very likely that - internally - the permissions are bound to a unique identifier and a new group G would have a different internal id.

**Comment by duncdrum** [comment]
This is almost certainly the case. New groups or users with the name of a previously deleted account, will have new ids, and unable to access orphaned resources belonging to the old id. 

But that is a separate issue.

**Comment by line-o** [comment]
Closing as not reproducible
