### ISSUE TITLE
creating library from exide fails

### ISSUE THREAD

**Issue by eduarddrenth** [eXist-db/exist#2477]
### What is the problem
follow the new application wizard in exide
finally click done
nothing happens, no error, also not in log
out of memory

### What did you expect
> app created

### Describe how to reproduce or add a test
> see above

### Context information
Please always add the following information
- eXist-db 45 
- Java version 1.8.0_191
- Operating system ubu 1804
- 64 bit
- How is eXist-db installed? (JAR installer)
- Any custom changes in e.g. conf.xml, nothing all default

**Comment by joewiz** [comment]
Which version of eXide? 

What options and values do you use when creating the app in the eXide wizard?

**Comment by eduarddrenth** [comment]
2.4.6, "Empty Package" and "library", the rest default
