### ISSUE TITLE
Some resources are not handled correctly in latest releases

### ISSUE THREAD

**Issue by dizzzz** [eXist-db/exist#2506]
Exist-db 4.6 and 5.0.0RC6

the following items need to be adressed:

- mime-types.xml  is copied to `eXist-db\src\org\exist\util\mime-types.xml` but should end in `eXist-db\exist-core\src\main\resources` (or we should git rid of the one in EXIST_HOME at all, of have it copied from the resources
- `eXist-db\exist-core\src\main\resources\org\exist\xquery\parser` should only contain the .g files as the rest should be generated. 

![image](https://user-images.githubusercontent.com/1700062/53095469-3caff900-351d-11e9-8e40-5bdcef3ed05a.png)

and

![image](https://user-images.githubusercontent.com/1700062/53095489-489bbb00-351d-11e9-86b4-080ca116a68c.png)

**Comment by adamretter** [comment]
Regards the `eXist-db\exist-core\src\main\resources\org\exist\xquery\parser` don't worry about that one just yet. That get's fixed as part of the Maven build.

**Comment by dizzzz** [comment]
ok. the .g files should end up in `exist-core/src/main/antlr2` according to spec. I can't find a maven plugin though :-(
