### ISSUE TITLE
RestXQ: register function with header-param() and cookie-param()

### ISSUE THREAD

**Issue by mathias-goebel** [eXist-db/exist#2524]
### What is the problem
With RestXQ i want to pass header and/or cookie parameter to the function. But even a simple function is not registered, when i add one of `%rest:header-param()` and `%rest:cookie-param()`.

### Describe how to reproduce or add a test
with enabled RestXQ (should be default) store the following module in the database at "/db/test.xqm"
```xq
xquery version "3.1";
module namespace openapi-test-simple="https://lab.sub.uni-goettingen.de/restxqopenapi/test1";
declare namespace rest = "http://exquery.org/ns/restxq";
declare namespace test="http://exist-db.org/xquery/xqsuite";

declare
  %rest:GET
  %rest:path("/test/cookie")
  %rest:cookie-param("tasty_cookie", "{$test}", "strawberry")
function openapi-test-simple:get-cookie($test as xs:string?)
as element(test) {
    <test>{ $test }</test>
};
```
afterwards the registration will return the empty sequence and no error is thrown to `restxq.log`, the registry remains unchanged, try it with
```xq
exrest:register-module(xs:anyURI("/db/test.xqm"))
```

when removing the parameter annotation, everything is fine. I see the same behaviour for `%rest:header-param`.

### Context information
* eXist-db 4.6.0 from bintray bz2
* openjdk version "1.8.0_201"
* Linux, Fedora 29

**Comment by dariok** [comment]
I think function parameters that are set by annotations need to be `zero-or-more`. Try `function openapi-test-simple:get-cookie($test as xs:string*)` – in my quick test that did the trick.

**Comment by mathias-goebel** [comment]
You are right. Thank you. I was reading the eXist book where this constraint is not mentioned.

**Comment by adamretter** [comment]
@dariok Indeed you are correct :-)
