### ISSUE TITLE
xpath issue

### ISSUE THREAD

**Issue by eduarddrenth** [eXist-db/exist#2527]
in exist 4.6 this xpath yields 4 results instead of 1:

//tei:entry[position()=1]/tei:form/tei:gram[@type='pos']

on this xml: [huis.zip](https://github.com/eXist-db/exist/files/2915540/huis.zip)

I can fix it using:

//tei:entry[position()=1]/tei:form[@type='lemma']/tei:gram[@type='pos']

**Comment by joewiz** [comment]
I can confirm the report. I've reduced it to the following test case:

```xquery
<root>
    <a>
        <b>
            <c foo="bar"/>
        </b>
        <x>
            <y>
                <b>
                    <c foo="bar"/>
                </b>
            </y>
        </x>
        <x>
            <y>
                <b>
                    <c foo="bar"/>
                </b>
            </y>
            <y>
                <b>
                    <c foo="bar"/>
                </b>
            </y>
        </x>
    </a>
</root>
/a[1]/b/c[@foo="bar"]
```

Expected results: `<c foo="bar"/>`
Actual results: 4 of these.

Saxon and BaseX return the expected results. eXist 4.x.x-develop (e935f4e2) returns the erroneous results.

@eduarddrenth Thanks for reporting this, but next time, **please** complete the issue template, to help us best address your issue.

**Comment by eduarddrenth** [comment]
sorry, I know, busy busy busy.... and I thought better you know it thsi way than not at all

keep up the good work

**Comment by dizzzz** [comment]
@eduarddrenth thnx for the report! but.... we are all busy :-)

**Comment by line-o** [comment]
#3075 fixed this

**Comment by line-o** [comment]
There will likely be no back port to v4.x.x for this. I hope upgrading to v5.3.0 is an option for you @eduarddrenth

**Comment by eduarddrenth** [comment]
thnks. I'm on 5.2.0 for quite some time
