### ISSUE TITLE
why are not indent the files by default on existdb 4.5? performance?

### ISSUE THREAD

**Issue by rpompaideasoft** [eXist-db/exist#2528]
### What is the problem
> Why the XML documents are not storing indent?

### What did you expect
> XML docs storing indent.

### Describe how to reproduce or add a test
> Opening indent XML docs after store.

### Context information
oxygen: 21.0 build 2019022207
Windows 10 64 bit
eXist-db: 4.5
java: jdk1.8.0_192

**Comment by joewiz** [comment]
@rpompaideasoft Please fill out the issue template.

**Comment by dizzzz** [comment]
@rpompaideasoft 
- connecting via WebDAV or XML (with the libraries)
- any changes in conf.xml ?
- can you add some screenshots?

**Comment by rpompaideasoft** [comment]
@dizzzz
Test:
![test45xquery1](https://user-images.githubusercontent.com/32643223/53665396-1a6b5900-3c4a-11e9-8942-a6a066c632d6.png)
Result:
![test45xquery2](https://user-images.githubusercontent.com/32643223/53665412-22c39400-3c4a-11e9-8d3b-0b0c4bf93147.png)

**Comment by duncdrum** [comment]
@rpompaideasoft you can configure oxygen to auto-indent when opening xml files via its preferences.

**Comment by rpompaideasoft** [comment]
@dizzzz i know. But when de file is too long is slow opening and most be save before can compare to other

**Comment by rpompaideasoft** [comment]
Any way to configure at least in test environment

**Comment by dizzzz** [comment]
see @duncdrum 's answer?

**Comment by duncdrum** [comment]
This is really a question for the OxygenEditor forum. To change your preferences go to `Preferences > Format` and select: `Format and Indent the Document on Open`
![screenshot 2019-03-03 at 12 12 10](https://user-images.githubusercontent.com/6205362/53694348-e4df8080-3dad-11e9-9c10-a710ed24475a.png)

**Comment by joewiz** [comment]
I’ll just add two eXist-related factors to consider when discussing whitespace:

1. In your example screenshot, you’re storing a document constructed in the body of an XQuery, where the “boundary-space” option by default is set to “strip”, which will cause all boundary space in XML documents built with direct constructors to be stripped. You can experiment by adding this to your prolog: `declare boundary-space preserve;`
2. In conf.xml the serializer has a property, indent. Toggling this will affect default serialization.

**Comment by contra8** [comment]
Sorry for showing up late ;-)

My team was running an eXist-db 2.2 which delivered all XML documents with "pretty print" indentation. This pretty print was not made by the Oxygen XML Author we use but server-side.

Now we updated to eXist-db 5.2.0 but there is no server-side pretty print although we have this code in our conf.xml:

<serializer add-exist-id="none"
               compress-output="no"
               enable-xinclude="yes"
               enable-xsl="no"
               indent="yes"
               match-tagging-attributes="no"
               match-tagging-elements="no">

What am I doing wrong? Is there another place to configure server-side pretty print resp. indentation?

**Comment by joewiz** [comment]
@contra8 To disable "pretty printing", set `indent="yes"` to `"no"`. Alternatively, instead of making this change globally via conf.xml, you can limit this change to WebDAV connections, via the `webdav.properties` file, as documented here: https://exist-db.org/exist/apps/doc/webdav#serialization.

**Comment by contra8** [comment]
Thanks @joewiz - I am sorry my information was misleading. Here is the situation:

1. We want pretty print in our XML files when we consume them via WebDAV.
2. We have the configuration in conf.xml of our eXist 5.2 as shown above, with indent="yes"
3. But still, when we open the files in Oxygen 21.1, the XML files are displayed without pretty print.

Maybe there can be other places where the configuration from conf.xml might be overruled?

**Comment by joewiz** [comment]
@contra8 Do you have a webdav.properties file set to indent=no?

**Comment by joewiz** [comment]
@contra8 Can you post a set of steps we can follow to reproduce your results? Start from 1. Start a new document in oXygen and save it to eXist via WebDAV. 2. Close document. 3. Reopen the saved document via WebDAV. 4. Pretty printing is lost/preserved? Please supply the document you use. And indicate whether you have a webdav.properties file and what its indent property is set to.

**Comment by joewiz** [comment]
Or, if your steps for reproducing require different steps, please post these.

**Comment by pdbro2k** [comment]
Sorry for showing up even later but I had exactly the same problems with version 4.7.1 and since I don't see any real solutions here, I want to share mine: I ended up wrapping the node with <code>parse-xml(serialize($node, map { "method": "xml", "indent": true() }))/*</code> before passing it to `xmldb:store`.

By the way, I noticed that for some reason only the REST interface seems to use the serialization attrs from conf.xml as it pretty-prints any node stored by `xmld:store()` while WebDAV and XMLRPC do not and there aren't any additional property files overwriting this option.
