### ISSUE TITLE
move and copy triggers not firing

### ISSUE THREAD

**Issue by phattire** [eXist-db/exist#255]
It appears the move document (before and after) and copy (before and after) document are not working in eXist 2.1.  (We have not verified move/copy collection triggers.)  We are not having issues with the other document triggers.  Our collection.xconf trigger definition does not call out which trigger events to fire on.

**Comment by gspringtech** [comment]
The copy- and move-document triggers are documented as having 2 parameters (old-uri,new-uri) - you can see this in the example code above and in the documentation. In fact, these should only have ONE parameter. I have read XQueryTrigger.java (from about 729) and successfully tested the move-document trigger with one parameter. 

So - the 'bug' is in the documentation - not the code.

**Comment by gspringtech** [comment]
Further to the previous comment, the after-move-document is receiving the OLD URI, not the new. This needs to be fixed in the source - either by adding the NEW uri (to match the documentation) or changing the uri from old to new.

**Comment by gspringtech** [comment]
And finally, the after-copy-collection parameters are in the wrong order in the documentation - they should be (old-url, new-url).
