### ISSUE TITLE
conf.xml / jobs / unschedule-on-exception not working

### ISSUE THREAD

**Issue by phattire** [eXist-db/exist#256]
Within conf.xml user jobs, we have added unschedule-on-exception not working="false" (and tried "no" also).  Jobs are still stopping (showing as COMPLETE) when a syntax error is found within the xquery being called in the job.

eXist 2.1

**Comment by duncdrum** [comment]
closing as invalid @phattire please open a new issue if you are still experiencing this including step to reproduce, and working code that shows the problem, thanks.
