### ISSUE TITLE
eXist-db special characters in transformation and xmldb:store

### ISSUE THREAD

**Issue by karbecker** [eXist-db/exist#2620]
Error explanation see: https://stackoverflow.com/questions/54809838/exist-db-special-characters-in-transformation-and-xmldbstore

Please create a collection named `temp` under /db/apps/ and copy the attached files into this collection. evaluate transformation.xq. Using `let $store := xmldb:store("/db/apps/temp", $filename, $transform, $mime-type)` in Line 20 does _not_ work:

    err:XPTY0004 checking function parameter 3 in call xmldb:store("/db/apps/temp", untyped-value-check[xs:string, $filename], $transform, untyped-value-check[xs:string, $mime-type]): XPTY0004: The actual cardinality for parameter 3 does not match the cardinality declared in the function's signature: xmldb:store($collection-uri as xs:string, $resource-name as xs:string?, $contents as item(), $mime-type as xs:string) xs:string?. Expected cardinality: exactly one, got 3617. [at line 20, column 56, source: xquery version "3.1";

using `string-join($transform)` does work.

Files: [temp.zip](https://github.com/eXist-db/exist/files/3019052/temp.zip)

**Comment by joewiz** [comment]
@karbecker Welcome, and thanks for posting this issue. Could you fill out the rest of the issue template? It's especially essential to supply the version info. Please add this:

```md
- eXist-db version + Git Revision hash e.g. eXist-db 3.0 /  acd0c14: 
- Java version (e.g. Java8u121): 
- Operating system (Windows 7, Linux, MacOs): 
- 32 or 64 bit: 
- How is eXist-db installed? (JAR installer, DMG, WAR file, clone from GitHub): 
- Any custom changes in e.g. conf.xml: 
```

**Comment by karbecker** [comment]
- eXist-db version + Git Revision hash e.g. eXist-db 4.5
- eXist Build: 201811211859
- Java version (e.g. Java8u121): `openjdk version "1.8.0_191"
OpenJDK Runtime Environment (build 1.8.0_191-8u191-b12-2ubuntu0.18.04.1-b12)
OpenJDK 64-Bit Server VM (build 25.191-b12, mixed mode)`
- Operating system: Ubuntu 18.04
- 64 bit 
- How is eXist-db installed? (JAR installer, DMG, WAR file, clone from GitHub):  JAR Installer
- Any custom changes in e.g. conf.xml: not that I know of

**Comment by adamretter** [comment]
Your XSLT is returning multiple nodes, in this instance 3617 nodes. However the `xmldb:store` function is defined to only take single item. So the error you are seeing here is indeed correct.

**Comment by joewiz** [comment]
@adamretter I believe the report suggests a misleading mistake in the function signature of `transform:transform`, which indicates that it returns a single `node()` or empty sequence. The fact that it returns 3,617 nodes means that either the function has a bug, or, more likely, its signature is wrong. (For comparison, the standard XQuery `fn:transform` function clearly contemplates multiple result documents. See https://www.w3.org/TR/xpath-functions-31/#func-transform.) If you agree with this assessment, please let me know, and I will be happy to open a new issue clearly stating this as the issue.

**Comment by adamretter** [comment]
@joewiz Indeed. The function signature for `transform:transform` is wrong, it can return `zero-or-more` nodes.

Unfortunately eXist-db has a long standing bug where it does not enforce the actual return type of functions.

Btw - I have started the `fn:transform` implementation.
