### ISSUE TITLE
Unable to start eXist-db.app

### ISSUE THREAD

**Issue by Bpolitycki** [eXist-db/exist#2658]
Related to #2171 and #1792

### What is the problem
Starting eXist-db.app with Java 12 on macOS (10.14.3) yields the following error:

> This application requires that Java 8 or later be installed on your computer. Please download and install the latest version of Java from www.java.com and try again.

### What did you expect
I expected eXist-db.app to start with any version of Java 8 or higher.

### Describe how to reproduce or add a test

1. Install Java via `brew cask install java`. Opening a new Terminal window and running `java -version `should report Java 12.0.1.
2. Install eXist-db via `brew cask install exist-db`.
3. Start eXist-db.app via the GUI (clicking on exist-db icon in application folder) or use `$ /Applications/eXist-db.app/Contents/MacOS/eXist-JavaAppLauncher`, which produces the following output:

`2019-04-27 10:53:29.516 eXist-JavaAppLauncher[671:12307] NSString *findJavaDylib(NSString *, _Bool, _Bool, _Bool, _Bool) Searching for a JRE.
2019-04-27 10:53:29.517 eXist-JavaAppLauncher[671:12307] NSString *findJREDylib(int, _Bool, _Bool) JRE search exception: 'launch path not accessible'
2019-04-27 10:53:29.587 eXist-JavaAppLauncher[671:12307] int launch(char *, int, char **) Launchpath: /Library/Java/JavaVirtualMachines/openjdk-12.0.1.jdk/Contents/Home/lib/jli/libjli.dylib
2019-04-27 10:53:29.593 eXist-JavaAppLauncher[671:12307] int launch(char *, int, char **) Error launching JVM Runtime ((null)) Relative Path: '/Library/Java/JavaVirtualMachines/openjdk-12.0.1.jdk/Contents/Home' (dylib: /Library/Java/JavaVirtualMachines/openjdk-12.0.1.jdk/Contents/Home/lib/jli/libjli.dylib)
  error: Diese Anwendung benötigt die Java 8 Laufzeitumgebung oder höher auf Ihrem Computer installiert sein. Bitte installieren Sie die neueste Version von Java von www.java.com und erneut versuchen.`

4. Checking `echo $JAVA_HOME` and `echo $EXIST_HOME` produces the following outputs:
`/Library/Java/JavaVirtualMachines/openjdk-12.0.1.jdk/Contents/Home`

and 

`/Applications/eXist-db.app/Contents/Resources/eXist-db`

### Context information
- eXist-db version 4.6.1
- Java version 12.0.1
- Operating system Mac OS 10.14.3
- 64 bit
- How is eXist-db installed? DMG

**Comment by dizzzz** [comment]
I'd recommend to stick for with Java8 for now;
I don't think you can just assume that a super-new JVM is qualified to work OK. we focus on Java8 right now. Java11 is a bonus :-P

**Comment by dizzzz** [comment]
and: please translate the german text as we are not native speakers....

**Comment by Bpolitycki** [comment]
You're right – just downgraded to Java11 and it seems this solved the problem. 

And sorry – the text translated to english:
`error: This application requires that Java 8 or later be installed on your computer. Please download and install the latest version of Java from www.java.com and try again.`

**Comment by adamretter** [comment]
@Bpolitycki The issue is the AppBundler that we use, it does not always have support for the latest Java version. Could you consider opening an issue with the upstream project here please - https://bitbucket.org/infinitekind/appbundler/issues
