### ISSUE TITLE
Wrong newly-created element updated in update insert attribute

### ISSUE THREAD

**Issue by IanDavey** [eXist-db/exist#2659]
Suppose we have the following document:
```xml
<deck>
  <card identifier="first"/>
</deck>
```
Let's run the following XQuery, with `$identifier := 'second'`:
```xquery
(: prior let statements omitted :)
let $loc := $doc//card[@identifier='first']
let $insert := update insert <card/> following $loc
return update insert attribute identifier { $identifier } into $loc/following-sibling::card[1]
```
As expected, we now have:
```xml
<deck>
  <card identifier="first"/>
  <card identifier="second"/>
</deck>
```
Run the XQuery again, with `$identifier := 'third'`.  We now have:
```xml
<deck>
  <card identifier="first"/>
  <card/>
  <card identifier="third"/>
</deck>
```
What I expected:
```xml
<deck>
  <card identifier="first"/>
  <card identifier="third"/>
  <card identifier="second"/>
</deck>
```
Has some optimization kept stale references going into new XQuery?

(obviously, this is a simplified case, and I came across this issue with the caller providing the actual "card")

- eXist-db version: 4.6.1
- Java version: Java8u161
- Operating system: Windows Server 2012 R2 Standard
- 64 bit
- How is eXist-db installed? JAR installer
- No custom conf.xml changes

Also worth noting: eXist-db 4.0.0 produced the expected behavior.

**Comment by dizzzz** [comment]
I assume it is fixed with https://github.com/eXist-db/exist/pull/2623
