### ISSUE TITLE
How to enable the logs with queries triggered on eXistDB

### ISSUE THREAD

**Issue by sbhusala** [eXist-db/exist#2660]
What did you expect
Kindly provide the suggestions to renable the logs with queries triggered on eXistDB

Context information
Please always add the following information

eXist-db version
Version: 1.4.3
SVN Revision: 17131
Build: 20120913

Java version
OpenJDK Runtime Environment (IcedTea6 1.13.13) (rhel-1.13.13.1.el6_8-x86_64)
OpenJDK 64-Bit Server VM (build 23.41-b41, mixed mode)

Operating system -- Linux

32 or 64 bit

How is eXist-db installed --JAR installer

**Comment by adamretter** [comment]
Log files can be found in `$EXIST_HOME/webapp/WEB-INF/logs`.

I am not quite sure what you mean by "re-enable"...

**Comment by sbhusala** [comment]
Hi Adam,
Thanks, but my question is how to add more information on logs. currently I can only see limited information which will not helping me to troubleshoot my issues.

I would like to have detailed logs/Debug mode logs , is there way to configure that ?

Regards,
bhusala

**Comment by duncdrum** [comment]
There is still some mentions of old logging code in the docs [log4j](https://exist-db.org/exist/apps/doc/devguide_log4j.xml?field=all&id=D3.3.2#D3.19). 

Out of curiosity why stick with `1.4.3` this is severely outdated.

**Comment by dizzzz** [comment]
@sbhusala I expect that in the provided documentation there are some hints. If not, please read the log4j documentation (the 1.x generation).
folowing up on @duncdrum : what is the reason to use 1.4.x ? it is extremely old....

**Comment by joewiz** [comment]
@sbhusala If you are trying to produce log entries via XQuery, see the standard `fn:trace` function, whose output appears in `exist.log` if you scroll to the bottom of `log4j2.xml` and change the following element from: 

```xml
<Root level="debug">
    <AppenderRef ref="exist.core"></AppenderRef>
</Root>
```

to having a `@level` of `debug`. Or see the eXist-specific `util:log*` and `console:log` functions.

**Comment by dizzzz** [comment]
I am not sure if the `fn:trace()` function was already available in v1.4.x ...

**Comment by joewiz** [comment]
You’re completely right, Dannes. With luck, util:log* were there, but not fn:trace or console:log. Adjusting log4j configuration would’ve been slightly different too.

**Comment by dizzzz** [comment]
sure, that is why I pointed to the 1.2.x documentation
