### ISSUE TITLE
Request for eXist db Data restoration steps from 1.4.3 to 4.1.4

### ISSUE THREAD

**Issue by sbhusala** [eXist-db/exist#2663]
### What is the problem
> We would like to copy the entire data eXist from 1.4.3 version to 4.1.4 , can you please share if any required steps has to be taken care
> 

### What did you expect
> Document or suggestions to copy the data from eXist 1.4.3version to 4.1.4

eXist-db version
Version: 1.4.3
SVN Revision: 17131
Build: 20120913

Java version
OpenJDK Runtime Environment (IcedTea6 1.13.13) (rhel-1.13.13.1.el6_8-x86_64)
OpenJDK 64-Bit Server VM (build 23.41-b41, mixed mode)

Operating system -- Linux

32 or 64 bit

How is eXist-db installed --JAR installer

**Comment by dizzzz** [comment]
Did you try the backup-restore route? I have no idea if that work/should work, as the internals and the user/security model has changed a lot in the last 7+ years. But there will be a route.. maybe by using the ant tasks...

**Comment by sbhusala** [comment]
Thanks Dizz, what is meant by ant tasks ? any document available ? Thanks in advance !

**Comment by brihaye** [comment]
Hello,

Le 02/05/2019 à 20:55, Dannes Wessels a écrit :

> Did you try the backup-restore route? I have no idea if that work/should 
> work, as the internals and the user/security model has changed a lot in 
> the last 7+ years. But there will be a route.. maybe by using the ant 
> tasks...

Good question Dannes but, errr... shouldn't sbhusala make a try first ?

My 0 cents...

Cheers,

p.b.

**Comment by dizzzz** [comment]
@sbhusala please could you try a regular backup-restore first?

**Comment by sbhusala** [comment]
Sure, I w

> @sbhusala please could you try a regular backup-restore first? This should be the correct and easiest way...

**Comment by sbhusala** [comment]
dizzz, Sure  I will do.

Is that same process to copy the data from 4.1.4 to 1.4.3 ? as well.

**Comment by sbhusala** [comment]
Hi All ,
while taking backup from eXist db-4.1.4 it is getting freeze and could not able to proceed further.
Can you please suggest if there any other process to take back from eXist db vesrion ?
Thanks in advance !
