### ISSUE TITLE
5.0.0-RC7 marked as 'latest release' in github

### ISSUE THREAD

**Issue by core-code** [eXist-db/exist#2664]
i think '5.0.0-RC7' should be marked as 'pre-release' in github, and 4.6.1 should be marked as 'latest-release' to match what the homepage says...

**Comment by joewiz** [comment]
Could you provide some links to documentation about this feature of GitHub and describe how this would help you or other users?

**Comment by dizzzz** [comment]
I am also curious what 'marked' mean.

**Comment by duncdrum** [comment]
I would argue that `RC-7` is a proper release as far as GitHub is concerned. The automated tagging of our docker build pipeline should recognizes pre-release tags from GitHub, but we would need to test that.

**Comment by core-code** [comment]
hello @joewiz 

> Could you provide some links to documentation about this feature of GitHub 

https://help.github.com/en/articles/creating-releases

> and describe how this would help you

by properly marking releases as either stable or unstable, i can ensure eXist-db is properly supported by the 'homebrew-cask' project for easy installation on macOS

> or other users?

any other user going to the github download page will immediately see which releases are stable (and therefore recommended for normal users) and which are not

> I am also curious what 'marked' mean.

i am referring to this

<img width="120" alt="Bildschirmfoto 2019-05-03 um 10 20 55" src="https://user-images.githubusercontent.com/1261954/57126406-2c25c580-6d8d-11e9-8001-579077a6c21a.png">

normally projects properly mark RC releases as 'Pre-release' instead of as 'Latest release'

**Comment by dizzzz** [comment]
ahhhhh, that part. OK.

**Comment by joewiz** [comment]
@core-code Thank you for this context. It makes sense that we should label release candidates as pre-release. 

I worked with the caskroom community to set up two casks, one for stable releases at https://github.com/Homebrew/homebrew-cask/blob/master/Casks/exist-db.rb and one when we enter a release candidate phase at https://github.com/Homebrew/homebrew-cask-versions/blob/master/Casks/exist-db-rc.rb (which is deleted when a release candidate graduates to a stable release). We update the casks as part of our release procedures, as documented at https://github.com/eXist-db/exist/blob/develop/exist-versioning-release.md.

**Comment by core-code** [comment]
thanks for the explanation, i guess if you keep homebrew versions up-to-date yourself at the moment, then any changes to the github releases aren't urgent at all...

**Comment by duncdrum** [comment]
this has now been fixed in line with the OPs request, thanks for the report.

**Comment by core-code** [comment]
thanks too!
