### ISSUE TITLE
diacrits in filenames make upload fail

### ISSUE THREAD

**Issue by eduarddrenth** [eXist-db/exist#2665]
### What is the problem

A file with a diacritic in the name (i.e. tweeënhalf.xml) cannot be uploaded using the new db manager so it seems.

### What did you expect
tweeënhal.xml to be uploaded

### Describe how to reproduce or add a test

try to upload tweeënhalf.xml to some collection

### Context information
Please always add the following information
- eXist-db 4.6.1
- Java version: openjdk version "1.8.0_191"
- Operating system: ubuntu 1804
- 64 bit
- JAR installer

**Comment by adamretter** [comment]
@eduarddrenth Apologies, but can you tell me what the "new db manager" refers to?

**Comment by eduarddrenth** [comment]
Sorry, the one reachable from eXide via file

The 'old' one, via dashboard, deprecated as I understand, does upload but changes the name. The file cannot be deleted than. The name is after this correctly displayed in the 'new' db manager and from there it can be deleted.

**Comment by adamretter** [comment]
@eduarddrenth Okay then I am moving this to the eXide repo as it sounds like it is an issue with eXide in the first instance.
