### ISSUE TITLE
Controller fails on first access to app

### ISSUE THREAD

**Issue by wolfgangmm** [eXist-db/exist#2691]
5.0/develop: the first time one tries to access the root page of any of the installed apps, only a collection is returned. The controller is not evaluated/fails due to the collection not being found.

**Comment by StephanMa** [comment]
We had the same problems....
It was solved by commention https://github.com/eXist-db/exist/blob/develop/exist-core/src/main/java/org/exist/http/urlrewrite/XQueryURLRewrite.java#L791 out
