### ISSUE TITLE
fn:tokenize default case-insensitive

### ISSUE THREAD

**Issue by trondaal** [eXist-db/exist#2694]
Hi, 

seems like fn.tokenize is  default case-insensitive for characters in the pattern and behaves as if the i-flag was specified.

try:
tokenize('firstSecondThirdLast', '[A-Z]')

Should split on the capital letters only, but splits on every character.
The error is found in the latest release, but also found in an earlier release I have tried.

Regards,
Trond

**Comment by adamretter** [comment]
@trondaal if you would like to contribute some XQSuite tests fro the issue that would be great. I have attached a patch to fix your bug. So once we have tests we can open a PR.

[FunTokenize.patch.txt](https://github.com/eXist-db/exist/files/3181968/FunTokenize.patch.txt)
