### ISSUE TITLE
macOS appbundler limitation means Oracle JDK 8 is mandatory 

### ISSUE THREAD

**Issue by joewiz** [eXist-db/exist#2695]
### What is the problem

eXist uses [appbundler](https://bitbucket.org/infinitekind/appbundler) for the macOS .app distribution. The appbundler's `launch` method used by eXist has a hidden dependency on Oracle JDK 8 and will thus prevent eXist from launching without it. This has affected eXist since v3.0.4, if not earlier versions.

I've submitted a PR to appbundler fixing the issue: https://bitbucket.org/infinitekind/appbundler/pull-requests/55. There's no ETA for this merge, but I hope it is in time for the release of 4.7.0 and 5.0.0-RC8. Once it is merged in, the mavenized branch of eXist will immediately pick it up, but the develop-4.x branch will need its `tools/appbundler` jar to be updated. I can do this as I did with https://github.com/eXist-db/exist/pull/2187.

**Update (2019-05-31):** My PR to appbundler has been merged, so I've now submitted a corresponding PR for `develop-4.x.x`, https://github.com/eXist-db/exist/pull/2768 - an important bugfix for users of 4.x.

### Context information

- eXist-db version + Git Revision hash: all since v3.0.4, if not earlier versions
- Java version: all
- Operating system: macOS
- 32 or 64 bit: 64 bit
- How is eXist-db installed? DMG or locally built .app 
- Any custom changes in e.g. conf.xml: none

**Comment by adamretter** [comment]
@joewiz Actually for the Mavenized branch we will need a new version of the appbundler-maven-plugin

**Comment by joewiz** [comment]
@adamretter I've submitted a PR for `develop-4.x.x` systems. I'm not sure what actions are needed for `appbundler-maven-plugin` to ensure this change is propagated to `develop`?

**Comment by adamretter** [comment]
@joewiz I have published updated releases of the AppBundler, and the PRs to update eXist-db are here: https://github.com/eXist-db/exist/pull/2769 and https://github.com/eXist-db/exist/pull/2770

**Comment by joewiz** [comment]
My PR #2768 in fact contained a regression in recent commits to appbundler. I've [reported this bug](https://github.com/TheInfiniteKind/appbundler/issues/45) to the upstream project and will submit a revised PR for 4.x.x when appbundler is fixed.

**Comment by adamretter** [comment]
@joewiz Do we still need an update?

**Comment by joewiz** [comment]
@adamretter No, I think we're all set now:

- develop: https://github.com/eXist-db/exist/pull/2790
- develop-5.0.0: https://github.com/eXist-db/exist/pull/2793
- develop-4.x.x: https://github.com/eXist-db/exist/pull/2794
