### ISSUE TITLE
4.6.1 yajsw configuration file not being updated with dzdo

### ISSUE THREAD

**Issue by oberoc** [eXist-db/exist#2698]
### What is the problem
> When using the tools/yajsw/bin/installDaemon.sh using dzdo instead of sudo, it fails. We recently switched from sudo to dzdo to support our infrastructure so on the cmd line, I'm doing this `dzdo PATH=$PATH tools/yajsw/bin/installDaemon.sh`. Also, I had to change the two places in the `installDaemon.sh` from `sudo` to `dzdo`. What is happening is that the `tools/yajsw/conf/wrapper.conf` never gets updated with the EXIST_HOME and we have the original `/Users/wolfgang/Releases` paths put into the `/etc/init.d/eXist-db` script.

### What did you expect
>  For the `/etc/init.d/eXist-db` to be written out properly. :)

### Describe how to reproduce or add a test
> Set up a system with dzdo (it is a Centrify product, so that might not be possible)

> 

### Context information
Please always add the following information
- eXist-db-4.6.1
- Java8u212
- Redhat Enterprise Linux 7.6
- 64 bit
- tar.bz2
- No changes to conf.xml

**Comment by adamretter** [comment]
I am afraid that those scripts are designed to be run with a system that has `sudo` installed. As `dzdo` is a commercial product, I think it is unlikely we will change this. I am afraid that you might have to either maintain your own version of those scripts, or send us a PR which enables them to work with both sudo and dzdo.
