### ISSUE TITLE
scheduler:resume-scheduled-job appears to always return true

### ISSUE THREAD

**Issue by phattire** [eXist-db/exist#274]
scheduler:resume-scheduled-job always returns true regardless of job-name supplied.

When attempting to resume a job in the "COMPLETE" state, scheduler:resume-scheduled-job returns "true" -- but the job does not return to "NORMAL".  Additionally, when supplying ANY string to the scheduler:resume-scheduled-job function, it is ALWAYS returning true.

There is no output to the logs.

**Comment by duncdrum** [comment]
@phattire can you provide a working code sample, including a description of the expected output vs actual output.
