### ISSUE TITLE
Graceful shutdown didn't happen , hence the process had to be killed to stop the exist. It corrupted the existDB  

### ISSUE THREAD

**Issue by sbhusala** [eXist-db/exist#2753]
### What is the problem
Graceful shutdown didn't happen , hence the process had to be killed to stop the exist. It corrupted the existDB  

### What did you expect
Please provide the solution or suggestion to resolve these issues

### Describe how to reproduce or add a test
> Describe how we can can reproduce the problem.

> The *best* way is to provide a 'self containing' test, a test that can be run without dependancies. The [XQSuite - Annotation-based Test Framework for XQuery](http://exist-db.org/exist/apps/doc/xqsuite.xml) makes it very easy for you to create tests. These tests can be executed from the [eXide editor](http://exist-db.org/exist/apps/eXide/index.html) (XQuery - Run as Test)

### Context information
Please always add the following information
- eXist-db version + Git Revision hash e.g. eXist-db 3.0 /  acd0c14  --> 4.2.1 
- Java version (e.g. Java8u121) --> 1.8.0_201
- Operating system -->Linux 3.10.0-957.10.1.el7.x86_64 amd64
- 32 or 64 bit --> 64 bit
- How is eXist-db installed? --> JAR installer
- Any custom changes in e.g. conf.xml Yes

**Comment by adamretter** [comment]
Hey @sbhusala can you please provide us with the output from `jstack` when this occurs?

**Comment by duncdrum** [comment]
closing due to no response. If you still experience this issue please open a new ticket.
