### ISSUE TITLE
hc:send-request on empty repsonse with status 404

### ISSUE THREAD

**Issue by mathias-goebel** [eXist-db/exist#2783]
### What is the problem
The httpclient (`hc:send-request`) throws err:ERROR on an empty resource. While other resources with status code 404 seems to be no problem.

### What did you expect
response header and no second item in the returning sequence

### Describe how to reproduce or add a test
```xq
xquery version "3.1";
hc:send-request(<hc:request href="https://d-nb.info/gnd/117444839/about/rdf" method="get"/>)
```
eXist 3.5.0 returns an empty sequence, what is not what i expect as there is no information on the response headers, but at least there is no error.
eXist 5.0.0-RC8 throws `exerr:ERROR Header is not content type [at line 2, column 1]`

### Context information
- eXist-db 5.0.0-RC8 pulled from docker hub (tag latest)

**Comment by duncdrum** [comment]
@dizzzz any ideas related to this and httpclient changes on 5.0.0?

**Comment by dizzzz** [comment]
not yet...

**Comment by mathias-goebel** [comment]
thx.
