### ISSUE TITLE
XPath general comparison optimisation bug

### ISSUE THREAD

**Issue by fjeneau9** [eXist-db/exist#2786]
### What is the problem
xpath bug.  Result sets are incorrect.

first xpath is returning more than one item - ("topicValue","topicValue")
second xpath is not returning an empty set - ("topicValue")

### What did you expect
first xpath should have only returned 1 value - ("topicValue")
second xpath should have returned an empty set - ()

### Describe how to reproduce or add a test
```
let $dita := 
    <dita>
        <topic>
            <prolog>
                <metadata>
                    <data name="topicType" value="topicValue"/>
                </metadata>
            </prolog>
            <topic>
                <prolog>
                    <metadata>
                        <data name="topicType" value="topicValue"/>
                    </metadata>
                </prolog>
            </topic>
        </topic>
    </dita>
let $xpath1 := $dita/topic/prolog//data[@name eq 'topicType']/@value
let $xpath2 := $dita/topic/topic/topic/prolog//data[@name eq 'topicType']/@value
```

### Context information
- eXist-db versions: 5.0.0-RC8-SNAPSHOT, 4.7.0, 4.6.1, 4.3.1, 3.4.1, 2.2
- Java version: jdk 1.8.0_144
- Operating system: Win 8.1, Win 10
- 64 bit
- install method: JAR installer
- custom changes: none

**Comment by fjeneau9** [comment]
Dunno if it helps in finding a solution, but if I add /string() for $xpath1, I get the expected single result back.

ie. `$dita/topic/prolog//data[@name/string() eq 'topicType']/@value`

Regardless, it should work without having to do this.

**Comment by adamretter** [comment]
So just:
```
let $dita := 
    <dita>
        <topic>
            <prolog>
                <metadata>
                    <data name="topicType" value="topicValue"/>
                </metadata>
            </prolog>
            <topic>
                <prolog>
                    <metadata>
                        <data name="topicType" value="topicValue"/>
                    </metadata>
                </prolog>
            </topic>
        </topic>
    </dita>
return
  count($dita/topic/prolog//data[@name eq 'topicType']/@value)
```

is enough to reproduce the problem... i.e. incorrectly returning `2` instead of `1`.

Interestingly, if you remove the predicate then you get the correct results. Also as @fjeneau9 pointed out changing the predicate to `[@name/string() eq 'topicType']` also works-around the issue.

**Comment by adamretter** [comment]
So the issue is related to a bad query optimisation. 

The expression `$dita/topic/prolog//data[@name eq 'topicType']/@value` is being rewritten to:

```xquery
$dita/child::{}topic
            (# exist:optimize-field #)
            (# exist:optimize #)
            {
                descendant::{}data[range:eq(attribute::{}name, "topicType")][ancestor::{}prolog]
            }
            /attribute::{}value

**Comment by line-o** [comment]
@fjeneau9 the fastest version yielding the correct results is
```xquery
let $xpath1 := $dita/topic/prolog//data/@name[. = 'topicType']/../@value
let $xpath2 := $dita/topic/topic/topic/prolog//data/@name[. = 'topicType']/../@value
```
