### ISSUE TITLE
WebDAV delete causes 5.0.0-RC8 db to hang 

### ISSUE THREAD

**Issue by joewiz** [eXist-db/exist#2787]
### What is the problem

When deleting a database resource with eXist-5.0.0-RC8 using a WebDAV client, the database hangs and the database has to be hard killed.

### What did you expect

I expected the resource to be deleted without any delay.

### Describe how to reproduce or add a test

1. Create a test collection and upload a resource like an xml or json file
2. Using the WebDAV Client (I tested Transmit 5.2.3 and oXygen XML Editor 21.1), delete the resource
3. Database becomes unresponsive to all requests. 
4. Kill database. Restart triggers recovery run.

I've attached jstack output from step 3 above before killing the database: 
[jstack.log](https://github.com/eXist-db/exist/files/3263941/jstack.log)

Note that deleting via eXide and Java Admin does not exhibit these symptoms.

### Context information

- eXist-db version + Git Revision hash: eXist 5.0.0-RC8 (current develop)
- Java version (e.g. Java8u121): OpenJDK (Azul Zulu) 1.8.0_212-b04
- Operating system: macOS 10.14.5
- 32 or 64 bit: 64 bit
- How is eXist-db installed? cloned from GitHub
- Any custom changes in e.g. conf.xml: none

**Comment by dizzzz** [comment]
whoops
