### ISSUE TITLE
[BUG] string-length() after simple map operator

### ISSUE THREAD

**Issue by djbpitt** [eXist-db/exist#2798]
Thank you for reporting your issue!

To be able to better understand you problem or suggestion, please add as much information as possible to this ticket. When there is no or just little information, it will be too difficult to work on it (and hence we will not be able to solve it)

Please fill in the following sections:

### What is the problem
> Describe exactly what you see (e.g. an output of an XQuery) 

In eXide, `1 ! string-length(.)` incorrectly returns `1`. It should raise a type error. 

### What did you expect
> Describe what you expected to happen. Add for example a reference to a [specification](https://www.w3.org/TR/xquery-3/).

`1 ! string-length()` (no dot inside the parentheses) correctly returns `1`. The reason different behavior with and without the dot is expected is explained at <https://www.biglist.com/lists/lists.mulberrytech.com/xsl-list/archives/201906/msg00021.html>. Saxon correctly implements the different behavior. And eXist correctly raises a type error with `string-length(1)`.

### Describe how to reproduce or add a test
> Describe how we can can reproduce the problem.

Type `1 ! string-length(.)` into eXide and press the Eval button.

### Context information
Please always add the following information
- eXist-db version + Git Revision hash e.g. eXist-db 3.0 /  acd0c14 : exist-db 4.4
- Java version (e.g. Java8u121) : Java 8
- Operating system (Windows 7, Linux, MacOs) : Centos 6
- 32 or 64 bit : 64 bit
- How is eXist-db installed? (JAR installer, DMG, WAR file, clone from GitHub) : jar
- Any custom changes in e.g. conf.xml : no

**Comment by adamretter** [comment]
Unfortunately this is related to eXist-db's bogus handling of `.` (i.e. the context item), see - https://github.com/eXist-db/exist/issues/2308#issuecomment-443990266

**Comment by line-o** [comment]
exist 5.3.0 is affected
