### ISSUE TITLE
Bug in tokenize()?

### ISSUE THREAD

**Issue by djbpitt** [eXist-db/exist#2804]
Thank you for reporting your issue!

To be able to better understand you problem or suggestion, please add as much information as possible to this ticket. When there is no or just little information, it will be too difficult to work on it (and hence we will not be able to solve it)

Please fill in the following sections:

### What is the problem
> Describe exactly what you see (e.g. an output of an XQuery) 

`tokenize("hIh", "[aeiou]")`  should tokenize only on lower-case vowels, but it returns each instance of "h" as a separate token, that is, it tokenizes incorrectly on the upper-case "I".

### What did you expect
> Describe what you expected to happen. Add for example a reference to a [specification](https://www.w3.org/TR/xquery-3/).

I expected the function to return a single token. This is what happens in Saxon.

### Describe how to reproduce or add a test
> Describe how we can can reproduce the problem.

Run the sample above.

### Context information
Please always add the following information
- eXist-db version + Git Revision hash e.g. eXist-db 3.0 /  acd0c14 : 4.4
- Java version (e.g. Java8u121): 8
- Operating system (Windows 7, Linux, MacOs): Centos 6
- 32 or 64 bit: 64
- How is eXist-db installed? (JAR installer, DMG, WAR file, clone from GitHub): jar
- Any custom changes in e.g. conf.xml: no

**Comment by gchwalisz** [comment]
It looks like the fn:tokenize function was case-insensitive by default. 
The issue from couple of days before: https://github.com/eXist-db/exist/issues/2694

**Comment by djbpitt** [comment]
Yes, this is a duplicate of #2694. Apologies for not catching that.
