### ISSUE TITLE
descriptor.xml not properly registered

### ISSUE THREAD

**Issue by duncdrum** [eXist-db/exist#2808]
### What is the problem
Upon start of exist we get the following warnings:
```
13 Jun 2019 10:39:51,084 [qtp606365803-40] WARN  (Descriptor.java [<init>]:100) - Giving up unable to read descriptor file from /exist/descriptor.xml 
13 Jun 2019 10:39:51,084 [qtp606365803-40] WARN  (Descriptor.java [<init>]:113) - Giving up unable to read descriptor.xml file from classloader in package org.exist.http, eXist-db Core, version 5.0 
```

Yet the file `descriptor.xml` is present at `exist/etc`, so chances are exist is looking in the wrong location

### What did you expect
Exist to know where to look for this file, and find it.              

### Describe how to reproduce or add a test
Start exist and check `exist.log`

### Context information
Please always add the following information
- eXist-db version 5.0.0-RC8-SNAPSHOT
- Java version (8)
- OS Docker
- 64 bit

**Comment by duncdrum** [comment]
on exist 5.2.0 
OS: docker (on macOS)

```24 Jan 2020 11:10:28,374 [qtp954928973-29] WARN (Descriptor.java [<init>]:116) - Giving up unable to read descriptor.xml file from classloader in package org.exist.http, eXist-db Core, version 5.2```

**Comment by ihine** [comment]
`23 Apr 2021 15:21:50,243 [qtp386201215-27] WARN  (Descriptor.java [<init>]:116) - Giving up unable to read descriptor.xml file from classloader in package org.exist.http, eXist-db Core, version 5.2`
