### ISSUE TITLE
Threads in waiting state forever with existdb 4.7.0

### ISSUE THREAD

**Issue by kvlnkarthik** [eXist-db/exist#2835]
When two threads one performing read operation and the other write operation, threads reach BLOCKED state waiting for locks acquired by one another. As a result no further requests are processed until existdb is restarted.
Thread (T1) is trying to write xml to database to a specific folder using PUT request using the REST. Say for eg : /db/ABC/content/1/2/3.xml. This thread has acquired WRITE lock on MutableCollection with URI(/db/ABC/content/1/2) and is waiting for lock on CollectionStore(collections.dbx) acquired by another thread T2.
Thread (T2) is trying to perform execute XQuery .It is executed using POST request over the REST API. XQuery tries to perform a search on /db/ABC/ level to look for documents that contains the given input. So as part of execution it entered the synchronized block ,i.e., ownership on CollectionCache ,acquired lock on CollectionStore and successfully opened other documents/collections under /db/ABC/ . But when it tried to open the MutableCollection with URI(/db/ABC/content/1/2) it entered into waiting state as Thread T1 has already acquired the lock.
T2 waits for Thread T1 to release the lock on MutableCollection and T1 waits for CollectionStore lock acquired by T2. Both threads wait for each other holding the critical resources blocking all other threads in the DbBrokerPool.

Exist db version : 4.7.0
Java version 1.8.0_91-b14
Operating system RHEL 7 64 bit
eXist-db is installed via JAR installer
eXist-db runs inside a VM with 32 GB and 4 CPU
Heap memory assigned for exist-db process is Xms = 1024 mb , Xmx= 15360 mb

We are constantly hitting this issue in our load tests. Is there anything that we could do to avoid this issue. Could you please suggest us the way forward here. Any help would be highly appreciated . Thanks a million !
Please let us know if any information is needed.

**Comment by kvlnkarthik** [comment]
We installed 4.7.0 in our servers and tested in 3 deployments. Tests passed successfully in all 3 servers. As part of our regression tests we ran the same test in the servers again but unfortunately this time it failed. 

Can you please let us know if the issue is still seen in 4.7.0 as well. 

Is 5.x.x a official release or a beta release ?

**Comment by dizzzz** [comment]
5.x.x is still a Release Candidate: pretty complete but we are ironing out some late issues.

**Comment by adamretter** [comment]
@kvlnkarthik eXist-db 5.0.0-RC8 will likely be released later today or possibly tomorrow now. I would suggest that you test with that. It has a completely rewritten locking architecture.

5.0.0-RC8 is likely to be the last 5.0.0 Release Candidate. All being well, it will become the final 5.0.0 release in the near future.

**Comment by kvlnkarthik** [comment]
@adamretter , @dizzzz  
Thank you for the response. Can ye please let us know the probable date of release for final 5.0.0.

Also is there any chance to fix the issue on 4.x.x version?

**Comment by iampopuri** [comment]
@adamretter @dizzzz Whether this issue not fixed in 4.7.0 stable release?

**Comment by adamretter** [comment]
@kvlnkarthik @iampopuri It is unlikely this will be fixed in 4.x.x.

The locking work that went into eXist-db 5.0.0 was substantial and took over 1 year of man hours. You can find 2 links to detailed technical reports on what was changed on the 3rd slide of this PDF - http://adamretter.org.uk/presentations/locking-and-cache-improvements_xml-prague_existdb_20180208.pdf

**Comment by iampopuri** [comment]
@adamretter Thanks for providing more details. Do you know by when we can expect 5.0.0 release? An approximate timeline should be fine.

**Comment by adamretter** [comment]
@iampopuri Above what I have mentioned above. It is hard to say.

I would think about 2 weeks would be reasonable for users to report issues with a `5.0.0-RC8`.  If there are no subsequent issues found in `5.0.0-RC8` over 5.0.0-RC7` in that time. Then I think a final 5.0.0 could be released. However, I would strongly advise you to start your testing with `5.0.0-RC8` ASAP.

**Comment by iampopuri** [comment]
@adamretter We couldn't find 5.0.0-RC8 release. 
Is it planned to release today? If not, can we get the nightly build link?

**Comment by duncdrum** [comment]
@iampopuri if you use the `:latest` tag for our docker images, you basically get the current state of RC8, e.g.:
`docker pull existdb/existdb:latest`

**Comment by kvlnkarthik** [comment]
@duncdrum 
We do not use docker in our environments. We cloned the code and trying to build but unfortunately didn't succeed so far. 

Is there any way for us to get the exist set up jar of 5.0.0-RC8 so that we can start our load test immediately?

**Comment by kvlnkarthik** [comment]
As we were unable to get 5.0.0-RC8 build , we installed 5.0.0-RC7 on our servers to start the load test. 

With 5.0.0-RC7 we saw huge drop in the throughput. We could only process 2500-3000 messages in an hour whereas in 4.7.0 servers the rate was around 6000-7000 messages per hour.  i.e., Throughput has come down by half . 

Is it expected to be such slow compared to earlier versions or do you think that it is slow due to any issues in 5.0.0-RC7 ?

**Comment by duncdrum** [comment]
Yes these are known issues with RC7, we are trying to address in RC8. If you had problems building from source, i d suggest opening a new ticket, providing us with some details about where things went wrong., i.e. the maven output.

**Comment by kvlnkarthik** [comment]
@duncdrum 
We got coupe of errors - one where the maven build failed because it couldn't rename one of the directory in target folder of existdb-distribution. So manually renamed and continued the build from there but ended up with the same error as mentioned in #2803. We did not collect logs then. 

When we run maven build again to collect the logs we hit another issue . This time with existdb-Ant Tasks module. Will raise a new one and add the logs for the build errors. 

Just observed that in the server where we have 5.0.0. RC 7 installed , all threads are seen in waiting for locks again. Please find the attachment for Jstack collected.

[JstackFromeXist500RC7.zip](https://github.com/eXist-db/exist/files/3339673/JstackFromeXist500RC7.zip)

**Comment by dizzzz** [comment]
Yesterday I pulled in an update regarding `uk.ac.ic.doc.slurp.multilock.MultiLock` (https://github.com/eXist-db/exist/pull/2855) by @adamretter  ;

**Comment by kvlnkarthik** [comment]
Cloned the code this morning in another system and managed to get 5.0.0-RC8 built . Installed this on one of our server and started the load . This time the issue popped up right away . Threads were seen in waiting state and no request was processed further.

Attached Jstack  & exist.log from the server .

[eXistdb500RC8Logs.zip](https://github.com/eXist-db/exist/files/3342160/eXistdb500RC8Logs.zip)

Please let us know if you need any further information.

**Comment by kvlnkarthik** [comment]
We got the maven build successful in another system. Installed on couple of servers and started our  test case . We hit the same issue seen earlier in 4.2.1,4.7.0 versions in 5.0.0-RC8 as well just after running for about an hour. Threads are seen in Waiting state for acquiring locks and no further requests are processed.

Please find the attachment for Jstack and exist logs captured from the server. 

P.S: We cloned the code from develop-5.0.0 branch and git commit id is  as follows :

`[Git commit : 605a807cee97adc6ab4ea45f434678dbe1fea436]
`

[existdb500RC8_7249.zip](https://github.com/eXist-db/exist/files/3345260/existdb500RC8_7249.zip)

**Comment by duncdrum** [comment]
@kvlnkarthik I think the fixes in https://github.com/eXist-db/exist/pull/2962 should help you out here, can you please check again with current `HEAD` of `develop`

**Comment by adamretter** [comment]
Hi @kvlnkarthik if you build from the HEAD of `develop` your performance problems are now hopefully resolved. If not try disabling the Lock Table in `conf.xml` and then try again.

As well as the JStack traces, I also need a dump of the Lock Table (obviously you will need it enabled in `conf.xml` for this to work). The LockTable dump can be gathered from JConsole via JMX by choosing the `dumpToConsole` operation (see page 22 - https://www.evolvedbinary.com/technical-reports/exist-db/locking-and-cache-improvements/locking-and-cache-improvements-20180205.pdf)

**Comment by alebastrov** [comment]
If I'm not mistaken, the description is similar to usual deadlock situation - defferent ordering when acquiring locks on different objects. Thread 1 gets lock on A, then B, Thread 2 gets lock on B, then A 

I think in this case you should make sure that first of all CollectionStore lock is acquired before lock on MutableCollection is going to be acquired too.

**Comment by adamretter** [comment]
I am closing this as we have not heard from the reporter since June.
