### ISSUE TITLE
Docker tagging strategy

### ISSUE THREAD

**Issue by adamretter** [eXist-db/exist#2841]
We should formalise our Docker Tagging strategy. For best practices see - https://blogs.msdn.microsoft.com/stevelasker/2018/03/01/docker-tagging-best-practices-for-tagging-and-versioning-docker-images/

**Comment by duncdrum** [comment]
We have done this already in the old repo, which carries over to the maven builds (just implemented as part of maven on Travis now, not dockerHub). Its in the readme, what is missing in your view?

**Comment by duncdrum** [comment]
Dead horse is dead
