### ISSUE TITLE
Restore: wrong location data directory

### ISSUE THREAD

**Issue by dizzzz** [eXist-db/exist#2874]
### What is the problem
When running restore of a backup file, in localmode, an "unexpected" location is used for the data directory.

### What did you expect
Use the data directory `EXIST_HOME/data` in stead of `EXIST_HOME/../data`

### Describe how to reproduce or add a test
Run

```
bin\backup.bat -r full20190409-0300.zip -ouri=xmldb:exist:/// -R -q -P "password"
```

the data directory is actually written in the directory `exist-distribution\target\data` in stead of `exist-distribution\target\exist-distribution-5.0.0-RC8-SNAPSHOT-dir`

the current directory is `exist-distribution\target\exist-distribution-5.0.0-RC8-SNAPSHOT-dir`

### Context information
Please always add the following information
- eXist-db version : v5 RCx
- Java version (e.g. Java8u201)
- Operating system (Windows 10)
- 64 bit
- How is eXist-db installed? (clone from GitHub, exist-distribution-5.0.0-RC8-SNAPSHOT-dir)
- Any custom changes in e.g. conf.xml - none

**Comment by duncdrum** [comment]
I thought we were going to get rid of `EXIST_HOME` (and good riddance) so then the `exist-distribution\target\data` makes somewhat more sense. But i m sure there are standard project layout rules to consider. @adamretter ?

**Comment by dizzzz** [comment]
sorry, i referred EXIST_HOME as the location where eg the BIN directory is in. Please provide a better name if it is too confusing. it was not $EXIST_HOME :-) 

The is is, as reported, that the directory is one directory level off. I had no time yet to debug.

**Comment by dizzzz** [comment]
when `-Dexist.home` is set, the correct 'data' location is used....

**Comment by dizzzz** [comment]
Update: in the `Configurator` is see a relative path passing by `../data` *but* this is relative to EXIST_HOME (still used!), instead of `EXIST_HOME/etc` where the `conf.xml` data is in these days.

**Comment by dizzzz** [comment]
confirmed.
