### ISSUE TITLE
uber.jar might be missing monex websocket stuff

### ISSUE THREAD

**Issue by duncdrum** [eXist-db/exist#2880]
On the docker images the `rconsole` url consistently reports a `404`. I think that this might be related to monex websocket jars not being in the flattened `uber.jar` thats on the classpath for the `entrypoint` of the image. 

monex requires
```
jackson-annotations-2.9.8.jar
jackson-databind-2.9.8.jar
javax.websocket-api-1.1.jar
```

and i can't locate them in the uber jar. When `jar tf ./exist.uber.jar > jar-contents.txt` [jar-contents.txt](https://github.com/eXist-db/exist/files/3393603/jar-contents.txt)
@adamretter should they be included by our current architecture, do we need to adjust how / when the uber jar is generated?

**Comment by adamretter** [comment]
So which Jars do we talk about?

**Comment by duncdrum** [comment]
`exist/lib/exist.uber.jar`

**Comment by adamretter** [comment]
@duncdrum According to the `pom.xml` for Monex, Jackson annotations should be in the Monex XAR - https://github.com/eXist-db/monex/blob/master/pom.xml#L103
