### ISSUE TITLE
Remove draft notation for map constructor entries

### ISSUE THREAD

**Issue by joewiz** [eXist-db/exist#2887]
### What is the problem

The draft syntax for map entries is still supported in eXist, which allows users to write bad code. 

A major version such as 5.0 would be a good opportunity to remove this syntax—just as we removed other draft-era functions like `map:new`.

### What did you expect

Map constructor entry syntax is as follows: https://www.w3.org/TR/xquery-31/#prod-xquery31-MapConstructorEntry

However, according to http://exist-db.org/exist/apps/doc/xquery#legacy-features:

> Map notation: During the drafting of XQuery 3.0, the specification changed slightly and so did the implementation in eXist-db. To keep backwards compatibility, eXist allows the older notation in map constructors: `key:=value` in addition to the new one, `key: value`.

### Describe how to reproduce or add a test

Code such as `map { "name" := "joe" }` should raise an error.

### Context information

- eXist-db version: current 4.x and 5.x 
- Java version: n/a
- Operating system: n/a
- 32 or 64 bit: n/a
- How is eXist-db installed? n/a
- Any custom changes in e.g. conf.xml: n/a

**Comment by adamretter** [comment]
@joewiz Seems like a good idea to me

**Comment by joewiz** [comment]
As @duncdrum mentioned during the Community Call, this PR would require a new release of shared-resources, since the HTML templating module contains one use of the old syntax: https://github.com/eXist-db/shared-resources/blob/master/content/templates.xql#L94-L97. 

Also, many HTML templating apps' `view.xql` files would need to be updated, e.g., https://gitlab.existsolutions.com/tei-publisher/tei-publisher-app/blob/master/modules/view.xql#L26-29.

**Comment by duncdrum** [comment]
exide's app-generator uses the proper syntax since 2016, generator apps always used the correct syntax in `view.xql`. 
I think this counts as sufficient time, for users to escape the tyranny of the defaults.

**Comment by line-o** [comment]
@joewiz oh wow, this beauty is hiding in a lot more places than I thought.

**Comment by joewiz** [comment]
@line-o Sure is! The most common culprit is view.xql of HTML Templating apps. I wonder if @craigberry could figure out a way to extend his code audit script to find these. I used the regex `map\s*\{[^\}]+?:=` over all of the XQuery files stored on my system. There were some false positives, but on the whole, it helped.

**Comment by joewiz** [comment]
@line-o I've completed reviewing the 18 eXist-db organization repositories with a `view.xql` file https://github.com/search?utf8=%E2%9C%93&q=org%3AeXist-db+filename%3Aview.xql&ref=simplesearch. 

- eXistSolutions repositories (7): https://github.com/search?q=org%3AeXistSolutions+filename%3Aview.xql&type=Code
- All GitHub repositories (1,088): https://github.com/search?q=filename%3Aview.xql&type=Code

Unfortunately, GitLab doesn't support searching by filename, but I've already submitted a PR for tei-publisher: https://gitlab.existsolutions.com/tei-publisher/tei-publisher-app/merge_requests/73.

**Comment by joewiz** [comment]
FYI, the previous behavior has been in place since this PR, which was released in eXist 2.2: https://github.com/eXist-db/exist/pull/320.

**Comment by joewiz** [comment]
New releases of the following stock apps have been published to the public repo:

- dashboard v2.0.2
- shared-resources v0.8.4
- monex v2.0.3

The following apps have PRs that need to be merged before a release can be cut:

- eXide (actually an xqlint issue) - https://github.com/wolfgangmm/xqlint/pull/2
- documentation - https://github.com/eXist-db/documentation/pull/365 
- fundocs - https://github.com/eXist-db/function-documentation/pull/32 (also related https://github.com/eXist-db/function-documentation/pull/33)

No changes to packageservice, functx, or markdown were needed.

I published new releases of the following non-core apps:

- public repo v0.8.3
- demo v0.4.3
- xsltforms-demo v0.1.5
- tei-pm v1.1.4

My PRs updating the other following non-core apps still need review:

- TEI Publisher - https://gitlab.existsolutions.com/tei-publisher/tei-publisher-app/merge_requests/73
-

**Comment by joewiz** [comment]
I've submitted PRs for the TEI Publisher showcases apps:
- Shakespeare - https://gitlab.existsolutions.com/tei-publisher/shakespeare-pm4/merge_requests/1
- Van Gogh - https://gitlab.existsolutions.com/tei-publisher/vangogh/merge_requests/1
- EEBO - https://gitlab.existsolutions.com/tei-publisher/eebo-pm4/merge_requests/1

**Comment by joewiz** [comment]
Other repositories with the same PR that will need new releases:

- JFreeChart https://github.com/eXist-db/jfreechart/pull/32
- Messaging & Replication https://github.com/eXist-db/messaging-replication/pull/158
- Website https://github.com/eXist-db/website/pull/21

I started a PR for AtomicWiki but then discovered it needed quite a bit more work to account for the removed functions. I pasted in the full audit, in case anyone is willing to complete the work:
- https://github.com/eXist-db/AtomicWiki/pull/64

**Comment by joewiz** [comment]
Thanks to help from @dizzzz, I've just released:
- Function Documentation v1.1.1 
- JFreeChart v0.5.0

This leaves only: 
- eXide - action @wolfgangmm for https://github.com/wolfgangmm/xqlint/pull/2
- Messaging & Replication (which is not yet ready for a new release) - action @dizzzz 
- Website - https://github.com/eXist-db/website/pull/21
- AtomicWIki - https://github.com/eXist-db/AtomicWiki/pull/64
- TEI Publisher & apps based on it - see links above
