### ISSUE TITLE
dirname returns whitespace instead of an escaped whitespace

### ISSUE THREAD

**Issue by mathias-goebel** [eXist-db/exist#289]
in
exist / bin / functions.d / eXist-settings.sh
you are using `dirname` that can't handle whitespaces very well.
see for example:

``` bash
$ dirname /some_path\ with_space/somefile
/some_path with_space
```

in my case this causes an error when executing `startup.sh`, but starting with `run.sh` works just fine. strange.

**Comment by duncdrum** [comment]
a lot has changed with scripts since exist2.2RC2. Is this still an issue, otherwise i m going to close this. Please open a new issue, if whitespaces are still misbehaving.

**Comment by mathias-goebel** [comment]
i can not start eXist on linux when the path to eXist contains a whitespace. but is not related to the function mentioned above.
will continue at #3101
