### ISSUE TITLE
(4.x.x) Unattended installation fails on Windows only

### ISSUE THREAD

**Issue by ohumbel** [eXist-db/exist#2895]
### What is the problem
Starting an unattended installation on Windows by specifying an `autoinstaller.xml` file leads to the following error:
```
[ Starting processing ]
Starting process Setting data dir... (1/2)
Error: main class net.sf.saxon.Transform not found
```
Please note that this error only occurs on the `develop-4.x.x` branch (and only on Windows).

### What did you expect
I expected the unattended installation to run without errors, as it does on Linux and Mac

### Describe how to reproduce or add a test
Start the unattended installation under Windows with the 4.8.0-SNAPSHOT installer, as described in detail in the [pull request 2896](https://github.com/eXist-db/exist/pull/2869)

### Context information
- eXist-db version: eXist-db 4.8.0-SNAPSHOT  /  commit bddb39173b20c55446b565b7550e241764a93f56
- only occurs on the `develop-4.x.x` branch
- Java version Java8u121 (but does not matter)
- Operating system: Windows *only*
- 64 bit (but does not matter)
- How is eXist-db installed? Unattended, see [pull request 2896](https://github.com/eXist-db/exist/pull/2869)
- No custom changes

**Comment by joewiz** [comment]
Fixed by #2896.
