### ISSUE TITLE
Creating users without group in the command-line client should throw an error

### ISSUE THREAD

**Issue by opax** [eXist-db/exist#290]
With the command-line client, the `adduser` command allows to create users without groups. The corresponding `/db/system/security/exist/accounts/user.xml` does not contain a group element.

The correct behavior would be to display an error instead of creating the user.

**Comment by adamretter** [comment]
@opax What is the `command-line` client? Do you mean the Java Admin Client?

**Comment by dizzzz** [comment]
The client has a headless option in which you can type
Commands. Same can be done in the gui...

**Comment by opax** [comment]
I did open the ticket because of the discussion on pull request #285.
