### ISSUE TITLE
Restoring a backup overwrites newer apps

### ISSUE THREAD

**Issue by adamretter** [eXist-db/exist#2914]
When restoring a backup, if the backup contains older apps, then can easily overwrite the newer apps, or worse you end up with a mess of old apps with some orphaned newer files.

Restore should detect app versions and offer the user a choice about whether to replace the newer version with the older version, or ignore the older version.

Example:
---
**NOTE**: EXPath Apps shipped with previous version of eXist-db, are not guaranteed to be forwards compatible with RC8. As such when restoring a backup to RC8 you should at least exclude the following from your `/db/apps` folder:
1. `/db/apps/dashboard`
2. `/db/apps/doc`
3. `/db/apps/eXide`
4. `/db/apps/fundocs`
5. `/db/apps/markdown`
6. `/db/apps/monex`
7. `/db/apps/packageservice`
8. `/db/apps/shared-resources`

If in doubt, you should consider excluding `/db/apps` entrirely from your backup archive during the restore, and then subsequently installing the latest versions of the Apps you need via the Dashboard's Package Manager.

**Comment by dizzzz** [comment]
I actually have been thinking about a small tool that
1) scans the apps in `autodeploy` -> find app names 
2) checks on low-level the contents of the files `data/expathrepo/.expath-pkg/`
3) remove entries of the apps of (1) from the files in `data/expathrepo/.expath-pkg/`

this helped me a lot last months....

**Comment by craigberry** [comment]
@adamretter should /db/apps/usermanager be on that list?

**Comment by craigberry** [comment]
I posted this on the mailing list but will mention it here too as a way consistently to exclude core apps before doing a restore of a full backup created by an earlier version of eXist.  It feels like a hackish workaround and no doubt a better-integrated solution will arise out of this discussion, but it gets me by for now.

1.) If your full backup is zipped, either unzip it or extract `db/apps/__contents__.xml` from it.
2.) Run that file through the stylesheet below with your favorite XSLT processor to generate a replacement `__contents__.xml` with the core apps removed.
3.) Restore from the unzipped directory tree or replace `db/apps/__contents__.xml` in the zip archive and restore from that.  The data from the old core apps will still be there, but the restore will ignore what's not in the manifest.

Here's the stylesheet:

```XSLT
<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:exist="http://exist.sourceforge.net/NS/exist" version="1.0">
<xsl:output method="xml" omit-xml-declaration="yes" indent="no" />
<!--
   Usage:
     xsltproc -o db/apps/__contents__.xml.new drop_core_apps_from_backup.xsl db/apps/__contents__.xml
     mv db/apps/__contents__.xml.new db/apps/__contents__.xml
-->

 <!-- identity -->
 <xsl:template match="node() | @*">
     <xsl:copy>
       <xsl:apply-templates select="node() | @*"/>
     </xsl:copy>
 </xsl:template>

 <!-- override -->
 <xsl:template match="exist:subcollection[@name='dashboard' or @name = 'doc' or @name = 'eXide' or @name = 'fundocs' or @name = 'markdown' or @name = 'monex' or @name = 'packageservice' or @name = 'shared-resources' or @name = 'usermanager']"/>

</xsl:stylesheet>
```


I ran it over an unzipped backup directory with xsltproc like so:

```
$ xsltproc -o db/apps/__contents__.xml.new drop_core_apps_from_backup.xsl db/apps/__contents__.xml
```


Then I compared the file I started with and the edited version to make sure it removed the core apps but left everything else:

```
$ diff -pu db/apps/__contents__.xml db/apps/__contents__.xml.new
--- db/apps/__contents__.xml	2019-08-02 14:44:52.000000000 -0500
+++ db/apps/__contents__.xml.new	2019-08-03 16:03:10.000000000 -0500
@@ -1,19 +1,19 @@
<collection xmlns="http://exist.sourceforge.net/NS/exist" name="/db/apps" version="1" owner="SYSTEM" group="dba" mode="755" created="2019-05-20T21:53:09.329-05:00">
    <acl entries="0" version="1"/>
    <subcollection name="shakespeare" filename="shakespeare"/>
-    <subcollection name="dashboard" filename="dashboard"/>
+
    <subcollection name="annotation-service" filename="annotation-service"/>
    <subcollection name="testupdate" filename="testupdate"/>
    <subcollection name="EarlyPrintTexts" filename="EarlyPrintTexts"/>
    <subcollection name="atom-editor" filename="atom-editor"/>
    <subcollection name="demo" filename="demo"/>
    <subcollection name="shc" filename="shc"/>
-    <subcollection name="usermanager" filename="usermanager"/>
-    <subcollection name="markdown" filename="markdown"/>
-    <subcollection name="monex" filename="monex"/>
-    <subcollection name="eXide" filename="eXide"/>
-    <subcollection name="shared-resources" filename="shared-resources"/>
-    <subcollection name="fundocs" filename="fundocs"/>
+
+
+
+
+
+
    <subcollection name="EarlyPrintAnnotations" filename="EarlyPrintAnnotations"/>
-    <subcollection name="doc" filename="doc"/>
+
</collection>
\ No newline at end of file
```


Then I replaced the original version with the edited version:

```
$ mv db/apps/__contents__.xml.new db/apps/__contents__.xml
```

And did a restore of the whole db/ directory (a backup created under 4.7.0) using 5.0-RC8.  The dashboard works fine and as far as I can tell none of the core apps got downgraded or polluted by pieces of older versions.

**Comment by wolfgangmm** [comment]
Fix in #2944

**Comment by craigberry** [comment]
There may also be a problem for things that are under db/system other than db/system/security, which obviously needs a way to be restored as it's the only supported way to keep user accounts.  As an example of what I'm talking about, I did a full restore after excluding core apps and then got:

```
HTTP ERROR 500

Problem accessing /exist/apps/dashboard/. Reason:

    Server Error
Caused by:

javax.servlet.ServletException: javax.servlet.ServletException: An error occurred while processing request to /exist/apps/dashboard/: exerr:ERROR error found while loading module functx: Error while loading module http://www.functx.com: error found while loading module from http://www.functx.com: org.exist.xquery.XPathException: err:XPST0003 unexpected token: xmlns [at line 1, column 45]

	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:168)
	at org.eclipse.jetty.server.handler.gzip.GzipHandler.handle(GzipHandler.java:753)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
<snip>
```

I don't know if functx.xql actually got downgraded (not sure there is a newer version) or got restored with the wrong character encoding or some other error occurred with the restore that left it non-functional.  But it is in the backup that I (mostly) restored (before the disk filled up):

```
# unzip -l full20190806-1720.zip | grep 'functx'
      419  08-06-2019 19:17   db/system/repo/functx-1.0/expath-pkg.xml
      580  08-06-2019 19:17   db/system/repo/functx-1.0/repo.xml
      840  08-06-2019 19:17   db/system/repo/functx-1.0/__contents__.xml
    90794  08-06-2019 19:17   db/system/repo/functx-1.0/functx/functx.xsl
    81751  08-06-2019 19:17   db/system/repo/functx-1.0/functx/functx.xql
      801  08-06-2019 19:17   db/system/repo/functx-1.0/functx/__contents__.xml
```

and it seems to me it would in general be better if a core capability like this preserved what comes with the new version of eXist and didn't overwrite it during a restore.  I have for now abandoned efforts to do full restores and am only planning to restore the security database and a couple of specific data collections.

**Comment by adamretter** [comment]
@wolfgangmm does your PR account for "library" XARs which are installed in `/db/system` and not `/db/apps`?
