### ISSUE TITLE
Please restore bin/ directory to macOS DMG install in 5.x

### ISSUE THREAD

**Issue by craigberry** [eXist-db/exist#2917]
As discussed on [exist-open](https://sourceforge.net/p/exist/mailman/message/36732691/), I took 5.0-RC8 for a spin on macOS Mojave and someone moved my cheese :-).  Specifically, the bin directory and all of its shell scripts are not present when using the DMG installer, but were in 4.x.  I develop on macOS and deploy on Linux and I like to be able to develop and test my scripts in my development environment.  I have a lot of scripts with things like this:

```
#/bin/sh
if [ "$(uname)" == "Darwin" ]; then
   exist='/Applications/eXist-db.app/Contents/Resources/eXist-db/bin/client.sh'
else
   exist='/home/exist/eXist-db/bin/client.sh'
fi
```

It's true I always had to do `sudo chmod +x` on those scripts after installation, but that's never bothered me.  Having to maintain my own set of those scripts would bother me.  And it's not like there is a large storage footprint from including these.  Here's the total from a 4.7.0 installation:

```
$ du -h bin/
16K	bin/functions.d
12K	bin/batch.d
56K	bin/
```

I'm under the impression that restoring this to the install would be a relatively minor build-time configuration change.  I would really appreciate having that change made.

**Comment by adamretter** [comment]
We decided at the Community Call today, that you are correct and these are valuable. We will add them back in for the next release. In the mean time you can use the scripts in the [bin.zip](https://github.com/eXist-db/exist/files/3469049/bin.zip) file by unzipping them to `/Applications/eXist-db.app/Contents/Resources/bin`.

**Comment by craigberry** [comment]
Thank you!
