### ISSUE TITLE
RC2.2 causes an error when inserting a library that is recursively referenced.

### ISSUE THREAD

**Issue by WillemvdW** [eXist-db/exist#294]
I have just installed RC2.2 and was copying our application code when I noticed that the db seems become unresponsive when saving certain module files. From the logs it appears that it is in some sort of an endless loop recompiling dependencies.

This is how it happened. I renamed the file that was already present, and copied it using oxygen from an instance running v2.1.
I had to forcibly kill exist, since no other way was available to stop it. When restarting, the file was not present. However, opening the original file, modifying it and saving it caused no error. Seems to be only when inserting the file anew. Using Oxygen 15.1 to do the insert.

When RestXq is enabled, this causes exist to hang in a repeating loop of trying to compile the dependent libraries. Note that in this case the libraries do not have the .xqm ending, but and .xql ending.

After disabling, restXq, the database did not hang, but Oxygen still reports an error when saving the file. However, it appears as if it has been saved correctly.

I created a small example with 2 libraries and a calling function, but could not replicate the problem. It seems that there need to be more libraries involved. The best would be to provide the full application to whoever needs to test it. You can request that for us, or we can give you access to the application from a remote location.

**Comment by adamretter** [comment]
@WillemvdW @wolfgangmm @dizzzz I can attack this one before the 3.0 release if someone can tell me how to simply reproduce it?

**Comment by adamretter** [comment]
@WillemvdW @wolfgangmm @dizzzz Any update please, it has now been 8 days. I would like to get this resolved for you...

**Comment by adamretter** [comment]
@WillemvdW I cannot reproduce your issue with the backup that you provided @wolfgangmm. I would appreciate it if you could tell me how to reproduce please?

**Comment by WillemvdW** [comment]
Hi Wolfgang, Adam
      
      The issue manifests only if you take a new instance of exist on
      which the application has not been loaded, and then I use Oxygen
      to copy all the files (xql and xqm) into the new instance. At some
      point in the copy this fails. Then you recopy the missing files,
      and thereafter the problem goes away because the referenced
      libraries are now present.
      
      Hope this helps.
      
      Willem
      
      On 6/9/2015 10:24 PM, Adam Retter wrote:
    
    
      @WillemvdW I cannot reproduce your
        issue with the backup that you provided @wolfgangmm. I would appreciate it if
        you could tell me how to reproduce please?
      —
        Reply to this email directly or view
          it on GitHub.

**Comment by adamretter** [comment]
@WillemvdW I need more detail please, I have a folder called `kwantu-resources` but in which order should I import the various sub-folders and files via oXygen?

I really need exact steps to reproduce this from you if you want it fixed please.

**Comment by WillemvdW** [comment]
On 6/10/2015 6:28 PM, Adam Retter
      wrote:
    
    
      @WillemvdW I need more detail please,
        I have a folder called kwantu-resources but in
        which order should I import the various sub-folders and files
        via oXygen?
      I really need exact steps to reproduce this from you if you
        want it fixed please.
      —
        Reply to this email directly or view
          it on GitHub.
      
        
          
          
        
        
      
    
    Hi Adam,
    
    I copy the whole directory as is in one copy. If you want, we can do
    it on Skype. I have a new installation of the LTS version ready that
    we can use to check.
    
    Willem

**Comment by adamretter** [comment]
@WillemvdW I couldn't see how to do that from oXygen. So yes a Skype would be good, my username is 'adam.retter'

**Comment by adamretter** [comment]
Okay I spent some time on Skype with @WillemvdW and unfortunately we cannot reproduce the issue. As such I am going to close the ticket. If anyone else has the same problem or can reproduce, please re-open the ticket and let me know.
