### ISSUE TITLE
Docker performance issues

### ISSUE THREAD

**Issue by wolfgangmm** [eXist-db/exist#2943]
Using the docker image for 5.0.0-RC8 as base image, I see huge performance differences between eXist develop running outside and inside docker. To reproduce, pull `existdb/teipublisher:latest` and call e.g.

`/exist/apps/tei-publisher/test/F-rom.xml.pdf?odd=shakespeare.odd&cache=no&token=1247446086376194&source=yes`

within your browser. This generates FO output for Shakespeare's "Romeo and Juliet" and takes  4 to 5s running develop outside docker. With docker, it is considerably slower, taking minutes instead of seconds.

Similar performance differences can also be seen on other operations, but less dramatic.

I first thought it might be due to the garbage collection settings as I can see eXist crawling along below 500mb memory (despite 8gb being available to the docker container). Changing the settings did not make any difference though.

### Context information
Please always add the following information
- eXist-db 5.0.0-RC8 docker image
- Java version 1.8.0_162
- MacOs 10.14.5
- Docker desktop 2.1.0.0, engine 19.03.1

**Comment by StephanMa** [comment]
I had also performance issues while using the TEI publisher App. Suddenly it took all 8 cores with 100% utilization and using the entire RAM and  Swap. Maybe it’s not related but just for the case it is...

**Comment by wolfgangmm** [comment]
Funny enough: docker on windows 10 is much faster with results being delivered after 20s (though running on a weaker surface pro). This seems to indicate there are some OS specifics involved.

**Comment by StephanMa** [comment]
I’ve tested it on a dedicated Ubuntu 18.04 headless server with docker.

**Comment by dizzzz** [comment]
@StephanMa if Java (java vm, parts of it) is swapped out, you have a problem. Is that happening?

**Comment by wolfgangmm** [comment]
@dizzzz I assigned 8gb to the docker container and my bigger machine has 64gb, so swapping should not happen ever.

**Comment by dizzzz** [comment]
Please could you change the java version? Java8 has only after a certain [patch level](https://blog.softwaremill.com/docker-support-in-new-java-8-finally-fd595df0ca54) good docker support, and Java10+ ([link](https://blog.docker.com/2018/04/improved-docker-container-integration-with-java-10/)).

**Comment by wolfgangmm** [comment]
@dizzzz eXist's current docker image for RC8 has openjdk version "1.8.0_212", so this should be ok.

**Comment by dizzzz** [comment]
@wolfgangmm OK. just checking as in the original ticket something else is mentioned.

**Comment by dizzzz** [comment]
@wolfgangmm is it an option to check with Java11 ? And... is the switch `-XX:+UseG1GC` used?

**Comment by duncdrum** [comment]
I ll try to get to the bottom of this in the next couple of days, but top of my head two areas could be causing this: 
-   the volume mount in particular the writes into `APFS` (this would explain better performance on win and other nixes) 
-   the memory allocation not working as expected

there are others but these would be the top two to investigate

**Comment by adamretter** [comment]
I think this is to be expected, one does not use Docker for performance, and certainly not for I/O bound workloads like a database ;-)

**Comment by duncdrum** [comment]
@adamretter this used to be true, but the i/o overhead is much less than what wolfgang is describing.

**Comment by line-o** [comment]
I also experienced a drastic decrease in performance when importing into Existdb in docker (OSX, 2gb ram,  ~2s/task) vs. bare-metal (linux, 2gb ram, 150ms/task). This even ramped up over time on docker up to ~8s/task, but would go down to 2s again after pausing for a minute. The bare-metal system stayed at 150ms/task constantly.

**Comment by duncdrum** [comment]
so this is pretty high on my to-do list, I need the exact commands that folks use to start their containers. @line-o how do you import? whats the output of `docker stats`

**Comment by line-o** [comment]
@duncdrum POSTing to a custom endpoint (web-annotation-service) which leads to a 100 calls to  xmldb:store per request on average.

**Comment by duncdrum** [comment]
For macOS users: 
![Screenshot 2021-03-07 at 23 48 31](https://user-images.githubusercontent.com/6205362/110257789-a8981980-7f9f-11eb-85b8-37f4dc4214b4.png)

there are known performance bottlenecks on macOS due to their os specific implementation of the Hypervisor protocol. I can't say if anything beyond that is going on, without reproducers: including daemon and volume configs, as well as start commands. Since none are provided here i ll close.
