### ISSUE TITLE
docker change admin pw via ARG or file

### ISSUE THREAD

**Issue by eduarddrenth** [eXist-db/exist#2957]
Now you can change the admin password during docker build like this:

...."sm:passwd('admin','replacethis')"

Via docker image history the password can easily be viewed.

Using the shell form of RUN you could do this:

ARG PW
....."sm:passwd('admin','${PW}')"

But this is not available in distroless.

Another option is perhaps to introduce this:

COPY pwfile /tmp
....."sm:passwd-file('admin','/tmp/pwfile')"
RUN rm /tmp/pwfile

**Comment by duncdrum** [comment]
see https://docs.docker.com/develop/develop-images/build_enhancements/

**Comment by eduarddrenth** [comment]
So what is the solution?

1) create a file apw.txt containing the run commands
2) put RUN --mount=type=secret,id=mysecret ???? in DockerFile
3) docker build --secret id=apw,src=apw.txt .

**Comment by duncdrum** [comment]
Yes one way to use `--secret` where the official image is used as `BASE` image is to put the whole RUN into the `apw.txt` file and execute it during `docker build …` 
You will also need o execute the `Entrypoint` command as part of your `Dockerfile` so that exist starts once with the new password.

**Comment by eduarddrenth** [comment]
ok, but how do I execute it during build? What should I replace my ???? in step 2 with?

**Comment by eduarddrenth** [comment]
Sorry, I think we do not understand each other enough, at least I don't understand you completely and I do not see how buildkit helps here. For now, since we fully control the machine docker runs on, I'll stick to having passwords in build history. Maybe I'll use multistage build to get rid of history, or something like https://tuhrig.de/flatten-a-docker-container-or-image/.

**Comment by paya001** [comment]
> Sorry, I think we do not understand each other enough, at least I don't understand you completely and I do not see how buildkit helps here. For now, since we fully control the machine docker runs on, I'll stick to having passwords in build history. Maybe I'll use multistage build to get rid of history, or something like https://tuhrig.de/flatten-a-docker-container-or-image/.

Hello eduarddrenth,

This worked for me:


with Docker BuildKit enabled
[https://docs.docker.com/develop/develop-images/build_enhancements/](url)

and with this exact Dockerfile
```
#syntax=docker/dockerfile:1.0.0-experimental
FROM existdb/existdb:5.3.0-SNAPSHOT
RUN --mount=type=secret,id=secretCommand,required,target=/tmp/secretCommand ["java", "org.exist.start.Main", "client", "--no-gui",  "-l", "-u", "admin", "-P", "", "-F", "/tmp/secretCommand"]
EXPOSE 8080 8443
CMD [ "java", "-jar", "start.jar", "jetty" ]
```

while having file with this content:
```
sm:passwd('admin','123')
```
in following location on machine where you build your Docker images:
```
 /home/jenkins/dockerbuildsecrets/createexistdb_admin_password_xquery_command
```

after building the image using this command:

```
 docker build --no-cache --progress=plain --secret id=secretCommand,src=/home/jenkins/dockerbuildsecrets/createexistdb_admin_password_xquery_command . -t createexistdb:0.0.1
```

and spinning up the container using
```
docker run -it -p 18080:8080 -p 18443:8443 --name createexistdb createexistdb:0.0.1
```

you will have running exist-db with administrator password set to :  1232:09 PM 4/18/2020

**Comment by eduarddrenth** [comment]
I'll have a look, didn't know about th -F option, in the admin docs (https://exist-db.org/exist/apps/doc/java-admin-client) you easily miss things

**Comment by eduarddrenth** [comment]
I ended up just doing:

```
FROM existdb/existdb:5.2.0
COPY adminpw /tmp
RUN [ "java", "org.exist.start.Main", "client", "--no-gui",  "-l", "-u", "admin", "-P", "", "-F", "/tmp/adminpw" ]
RUN rm /tmp/adminpw
```

**Comment by eduarddrenth** [comment]
well... ```rm /tmp/adminpw``` doesn't work because of ^5$#@1! distroless

**Comment by paya001** [comment]
Hello,
If you will be using docker buildkit the same as in my example,  there is
no need to delete the file since the file is only available to that one
particular RUN command and it will not be included in the final image.

**Comment by eduarddrenth** [comment]
ok, I guess buildkit is the way to go, looks like a good default to build using buildkit. Better than my copy/rm approach, which simple and more straightforward, but buildkit does a more sofisticated job so to see. Why isn't buildkit the standard in docker (yet), do you know?

**Comment by duncdrum** [comment]
@paya001 not sure if the `CMD` in your example actually works or does anything with 5.x.  But the rest is spot on. 

@eduarddrenth many build kit feature come from swarm/compose slowly trickling down. It ll be the default soon. It is the safest way to deal with secrets for containers.

**Comment by eduarddrenth** [comment]
ok, thnx for these insights
