### ISSUE TITLE
Data Volume

### ISSUE THREAD

**Issue by StephanMa** [eXist-db/exist#2959]
current release: Docker eXist-db 5.1
no changes
build with `docker-compose`

It seems that the data volume isnt available to configure.

i have mounted a volume to `/exist/webapp/WEB-INF/data` but data isnt stored in this volume.

![Unbenannt](https://user-images.githubusercontent.com/6735556/63089769-4ad55400-bf59-11e9-9824-72f5540094bd.PNG)

config works as expected

**Comment by adamretter** [comment]
The path from RC8 onwards is /exist/data

**Comment by StephanMa** [comment]
Thanks
