### ISSUE TITLE
Test Crypto library compatibility with eXist 5

### ISSUE THREAD

**Issue by joewiz** [eXist-db/exist#2964]
Please check https://github.com/eXist-db/crypto-exist-java-lib/pull/11 to make sure:

- crypto library is compatible with eXist 5
- confirm if it's only compatible with >= eXist 5, or if it's also backward compatible with 4.x
- if only compatible with eXist 5, increment the crypto library to a new major version for the package to indicate the breaking change
- and indicate the dependency on eXIst 5 in expath-pkg.xml

(As discussed on today's Community Call.)

**Comment by adamretter** [comment]
Closed by https://github.com/eXist-db/crypto-exist-java-lib/pull/17
