### ISSUE TITLE
Blank page when searching no results

### ISSUE THREAD

**Issue by lbjensen** [eXist-db/exist#2993]
I'm not sure what has happened, but suddently our application dda.dk/simple-search returns no results.
Also, if we give a direct document, only a blank is showing.
Localhost:8080/exist gives
http://localhost:8080/exist/404.html
![billede](https://user-images.githubusercontent.com/54734752/64060005-025b9e80-cbc7-11e9-9704-64332eb4b85c.png)
I'm no expert in existdb, but I have a huge understanding in databases and linux. The existdb is behind a haproxy server, but I can only find minor errors in the logfiles.
dashboard is not working either, but I'm not sure is has worked at any time

### What is the problem
until this monday we could use the application but since then, it has not worked.

### Describe how to reproduce or add a test
just go to 
http://dda.dk/simple-search and search for 31083 (no results)
or go to
http://dda.dk/catalogue/31083 (blank page)

[java error - existdb.txt](https://github.com/eXist-db/exist/files/3562125/java.error.-.existdb.txt)

I suspect it have corrupted my database somehow, but I'm not sure how to correct this.
The system is running in vmware and we have tried to restore an old snapshot from the 18/8, but this has no effect at all.

Please always add the following information
- eXist-db version: 3.6.0
- Java version: 1.8.0_201
- Operating system: ubuntu 16.04
- 64 bit
- How is eXist-db installed?  clone from GitHub

Hope someone can help

Cheers
Lars
Denmark

**Comment by lbjensen** [comment]
I have now tried to do a backup and this fails
look at attached file.
It says 
Failed to backup resource 1644.xml from collection <path to data>/data
[backup error - existdb.txt](https://github.com/eXist-db/exist/files/3562144/backup.error.-.existdb.txt)

Cheers
Lars

**Comment by adamretter** [comment]
@lbjensen We can't directly support your application I am afraid. But we can try and help you get eXist-db back up and running.

The error logs you have provided are from the client-side which doesn't tell us a great deal.

From the server:
1. Can you tell us the status of the eXist-db process.
2. Can you provide any relevant errors from `logs/exist.log`.
3. What do you see if you access http://your-server:8080/exist/rest/db/

Thanks Adam.

**Comment by lbjensen** [comment]
Hi Adam

Thanks for taking time answering my question
Could this be due to a corrupt xml file?
Can I temporary delete/move the xml out of the database?

The exist-db is running, and I can connect to the database with admin user
● eXist-db.service - eXist-db – Native XML Database –
   Loaded: loaded (/etc/systemd/system/eXist-db.service; enabled; vendor preset: enabled)
   Active: active (running) since Fri 2019-08-30 15:57:56 CEST; 20h ago
     Docs: http://exist-db.org/exist/apps/doc/
  Process: 6718 ExecStop=/usr/lib/jvm/java-8-oracle/jre/bin/java -Dwrapper.pidfile=/opt/exist/tools/yajsw/work/wrapper.eXist-db.pid -Dwrapper.service=true -Dwrapper.visible=false -Djna_tmpdir=/opt/exist/too
  Process: 6814 ExecStart=/usr/lib/jvm/java-8-oracle/jre/bin/java -Dwrapper.pidfile=/opt/exist/tools/yajsw/work/wrapper.eXist-db.pid -Dwrapper.service=true -Dwrapper.visible=false -Djna_tmpdir=/opt/exist/to
 Main PID: 6834 (java)
    Tasks: 63
   Memory: 1.4G
      CPU: 7min 42.833s
   CGroup: /system.slice/eXist-db.service
           ├─6834 /usr/lib/jvm/java-8-oracle/jre/bin/java -Dwrapper.pidfile=/opt/exist/tools/yajsw/work/wrapper.eXist-db.pid -Dwrapper.service=true -Dwrapper.visible=false -Djna_tmpdir=/opt/exist/tools/yajs
           └─6855 /usr/lib/jvm/java-8-oracle/jre/bin/java -classpath /opt/exist/tools/yajsw/wrapperApp.jar:/opt/exist/tools/yajsw/classes:/opt/exist/start.jar -Dfile.encoding=UTF-8 -Dexist.home=. -Djetty.ho
2.
Logfile is attached, truncated a lot, but still a lot of errors, info and warnings
[exist.log](https://github.com/eXist-db/exist/files/3562361/exist.log)

3.
![billede](https://user-images.githubusercontent.com/54734752/64062994-7b222100-cbee-11e9-8e3d-d71e30cf78bb.png)

Hope you can find the error

Cheers
Lars

**Comment by adamretter** [comment]
It appears that the server is running correctly, the errors towards the end of the log are related to either bad-requests of XQuery code errors.

However, that said earlier in the logs, there are errors like:
```
2019-08-30 14:11:48,690 [DefaultQuartzScheduler_Worker-3] ERROR (FileUtils.java [measureFileStore]:193) - java.nio.file.NoSuchFileException: /data/exist_data/dbx_dir.lck 
```
These don't look too good. Could something else have been messing with `/data/exist_data`?

If its possible for you - Your best bet, is probably to shutdown, wipe the data directory and restore your most recent backup (assuming you have been taking regular backups).

**Comment by lbjensen** [comment]
Hi @adamretter 

That error came, when I tried to connect to the database with the client.
The problem occurred monday 26/8, so I don't expect this is the reason.

We do not have e valid database backup. We only do the VmWare snapshot of the server, unfortunately.
Is there any way to recover or repair the database without the backup available?

Cheers
Lars

**Comment by adamretter** [comment]
Yes you can do an emergency export - please see the docs

**Comment by lbjensen** [comment]
Hi @adamretter 

It turns out, the system has been non working for almost 2 month.
I will try to restore it to before the last running date

Thanks for your advice

Cheers
Lars
Denmark
