### ISSUE TITLE
Install eXist-db 5.0.0 as Linux service

### ISSUE THREAD

**Issue by bogdan-cercelaru** [eXist-db/exist#3003]
Hello

I installed 5.0.0 on a CentOS using JAR installer and tried to install it as Linux service to be started up at boot.
Unfortunately the new version doesn't contain "tools" folder with the "yajsw" wrapper anymore. It works when it is started using bin/startup.sh script but I need it to be installed as a service.
Please note that documentation still mentions the "yajsw" wrapper to install it as a service.

**Comment by duncdrum** [comment]
can you point me to where in the docs that is?

**Comment by bogdan-cercelaru** [comment]
Here you can find the documentation: https://exist-db.org/exist/apps/doc/advanced-installation#linux

**Comment by duncdrum** [comment]
got it see https://github.com/eXist-db/documentation/issues/333

**Comment by adamretter** [comment]
@bogdan-cercelaru We removes YAJSW in 5.0.0 as it seemed to cause more problems than it solved. I actually meant to update the docs but it seems I missed that.

If CentOS 5 has SystemD? You can using the following systemd config:

```
[Unit]
Description=eXist-db NoSQL Database
After=syslog.target

[Service]
Type=simple
User=existdb
Group=existdb
ExecStart=/existdb/bin/startup.sh
Restart=on-abort

[Install]
WantedBy=multi-user.target
```

The above assumes you have installed eXist-db into `/existdb` and it is owned by a dedicated service account, user `existdb` and group `existdb`.

**Comment by bogdan-cercelaru** [comment]
Thank you @adamretter but I am on CentOS 6.10 and it has SysV (init.d) not SystemD.
I've managed to do this using the following start/stop functions:
```
start() {
        echo -n "Starting eXist-db... "
        nohup ${EXISTDB_HOME}/bin/startup.sh &
        return 0
}

stop() {
        PID=$(ps aux | grep "${EXISTDB_HOME}" | grep -v grep | awk '{ print $2}')
        echo "Shutting down eXist-db with PID ${PID} ..."
        kill -15 ${PID}
        return 0
}
```

**Comment by adamretter** [comment]
@bogdan-cercelaru as an alternative for stopping you could call `bin/shutdown.sh`

**Comment by bogdan-cercelaru** [comment]
@adamretter i've tried it but it doesn't seems to work. I cannot stop eXist-db instance started with `bin/startup.sh` using `bin/shutdown.sh`.

**Comment by adamretter** [comment]
@bogdan-cercelaru If you changed the `admin` password, you need to pass that as an argument to `bin/shutdown.sh` using `-p`.

**Comment by bogdan-cercelaru** [comment]
Yes, it works using the `-p` to pass the `admin` password.
Thank you @adamretter

**Comment by craigberry** [comment]
We had a discussion about this on the [mailing list](https://sourceforge.net/p/exist/mailman/message/36737278/).  

The release notes for 5.0 also say, "We no longer support running eXist-db inside a 3rd-party Servlet container such as Apache Tomcat. If you wish to operate eXist-db as a Server, you should instead run the server using the provided Jetty start-up scripts."  I don't know what scripts are being referred to here -- surely bin/startup.sh with a roll-your-own systemd configuration is not a "Jetty start-up script"?  Or maybe "Server" in this context means something completely different from a Linux service?

There are also things the wrapper could do for you that you now have to figure out a different way to do.  For example, I was using the wrapper to control Java memory use.  The only way I can see to do that now is to manually edit bin/startup.sh and add or modify the desired `-Xms` and `-Xmx` switches to the Java command.  I believe the former can be set at installation time but not the latter.

**Comment by adamretter** [comment]
@craigberry the Jetty startup scripts are indeed those in `bin\startup.sh`.  The systemd config is now in the documentation. For setting such JVM options you can use the environment variable `JAVA_OPTS`
