### ISSUE TITLE
Loading via no-gui client complains about missing collection

### ISSUE THREAD

**Issue by adamretter** [eXist-db/exist#3007]
Trying to load a bunch of files from an `output` directory via the no-gui JAC doesn't work. The following command:

```
client.bat --collection /db/xmark --parse output/ --no-gui --user admin
```

Gives the error:
```
Please specify target collection with --collection
```

**Comment by duncdrum** [comment]
shouldn't they all be escaped? `--collection "/db/xmark/"`

**Comment by adamretter** [comment]
@duncdrum What you have there is quoting not escaping. The quoting is only needed around special characters such as spaces etc.
