### ISSUE TITLE
the token "in" is not in lucene index

### ISSUE THREAD

**Issue by eduarddrenth** [eXist-db/exist#3021]
### What is the problem

the token "in" does not end up in a lucene index

### What did you expect
"in" being in the index

### Describe how to reproduce or add a test

deploy the test app from the zip: 
[test.zip](https://github.com/eXist-db/exist/files/3637839/test.zip)

- inspect the index: "in" isn't in it

### Context information
Please always add the following information
- eXist-db version 5.0.0
- Java version from docker image of 5.0.0
- Operating system: docker on ubuntu latest lts
- 64 bit
- How is eXist-db installed? docker

**Comment by joewiz** [comment]
The word you mention is one of the default stopwords in the standard analyzer. To learn how to configure stopwords, see https://exist-db.org/exist/apps/doc/lucene.

**Comment by eduarddrenth** [comment]
tanks for the pointer
