### ISSUE TITLE
Strange warning on install - "Please consider reporting this to the maintainers of org.exist.storage.BrokerPool"

### ISSUE THREAD

**Issue by wetndusty** [eXist-db/exist#3030]
Xist version 5.0.0 (5a27d10ba1710c1df751344b53ac6e4cb4778e3b), Copyright (C) 2001-2019 The eXist-db Project
eXist-db comes with ABSOLUTELY NO WARRANTY.
This is free software, and you are welcome to redistribute it
under certain conditions; for details read the license file.

Connecting to database...
Using config: /home/wetndusty/eXist-db/etc/conf.xml
Connected :-)
Changed admin password OK!
shutting down database...
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.exist.storage.BrokerPool (file:/home/wetndusty/eXist-db/lib/exist-core-5.0.0.jar) to field java.lang.Thread.threadLocals
WARNING: Please consider reporting this to the maintainers of org.exist.storage.BrokerPool
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

**Comment by dizzzz** [comment]
what java version are you using? This message  is a warning that things will change in the future,
I'd recommend to stay at Java8 right now. Java11 might yield into the same kind of warnings, not sure.

**Comment by wetndusty** [comment]
its linux mint preinstalled java

OpenJDK Runtime Environment (build 11.0.4+11-post-Ubuntu-1ubuntu218.04.3)
OpenJDK 64-Bit Server VM (build 11.0.4+11-post-Ubuntu-1ubuntu218.04.3, mixed mode, sharing)

**Comment by duncdrum** [comment]
While we've undertaken some steps to ensure that exist runs under Java11, we do not use any Java11 language features, so there are no benefits from doing so. At the moment the recommended java version is 8. As long as you stick with java 11 there should't be any problems as the result of this warning. If you want to be on the safe side, you could consider installing java8.

**Comment by wetndusty** [comment]
it not production so it ok

i post this mainly as "FYI" :)

**Comment by duncdrum** [comment]
Yes thank you for the report, we are currently discussing when to make the move to java 11.

**Comment by wetndusty** [comment]
i guess this warning for java 11 and remain as warning before java 12 - so it`s ok - at first look it work as expected

**Comment by adamretter** [comment]
You will be fine on Java 11. I have run eXist-db on Java 11 without problems.

The warnings are about how out code does reflection in some places, those mechanisms I think will be disabled from JDK 13 onwards.

**Comment by duncdrum** [comment]
I m going to close this. thank you for your report, we are aware of the issue, and will address it when we add support for java version > 11.  For now the current LTS is supported and working.
