### ISSUE TITLE
util:get-resource-by-absolute-id() is broken in 5.0.0

### ISSUE THREAD

**Issue by 03b8** [eXist-db/exist#3031]
Hi there. I noticed that the `util:get-resource-by-absolute-id()` doesn't return anything when provided with a valid id parameter in eXist 5.0.0. I compared the behavior of the function in 4.7.1 and 5.0.0 by using the two corresponding Docker images from Docker Hub and a short XQuery snippet:
```
let $doc := doc("/db/apps/eXide/build.xml")
(: $doc can also be any other document of course :)
let $abs-id := util:absolute-resource-id($doc)
return $doc = util:get-resource-by-absolute-id($abs-id)
```
This snippet:
* returns `true()` on eXist 4.7.1 from Docker Hub `existdb/existdb:4.7.1` (image id `1937aedf933b`)
* returns `false()` on eXist 5.0.0 from Docker Hub `existdb/existdb:5.0.0` (image id `72d679c573f1`)

My OS is Debian 9. Please let me know if there's other info you need.

**Comment by duncdrum** [comment]
Yup i can reproduce this. @adamretter are there changes with respect to resource-ids as part of the lock table?

**Comment by adamretter** [comment]
@duncdrum Nothing intentional that I am aware of.

**Comment by line-o** [comment]
#3337 is a duplicate will add my test case here and then close mine.
