### ISSUE TITLE
org.exist.EXistException: database instance 'exist' is not available

### ISSUE THREAD

**Issue by sbhusala** [eXist-db/exist#3038]
Thank you for reporting your issue!

To be able to better understand you problem or suggestion, please add as much information as possible to this ticket. When there is no or just little information, it will be too difficult to work on it (and hence we will not be able to solve it)

Please fill in the following sections:

### What is the problem
> eXist db service is not starting as expected.

### What did you expect
> eXist db services needs to be start as expected. 

### Context information
Please always add the following information
- eXist-db version + Git Revision hash --> 1.4.3
- Java version (e.g. Java8u121) --> Java HotSpot(TM) 64-Bit Server VM (build 25.144-b01, mixed mode)
- Operating system (Windows 7, Linux, MacOs) --> Linux
- 32 or 64 bit --> Red Hat Enterprise Linux Server release 7.6 (Maipo
- How is eXist-db installed? (JAR installer, DMG, WAR file, clone from GitHub) --> jar
- Any custom changes in e.g. conf.xml Yes. 

Logs: 

05 Oct 2019 14:09:58,328 [main] INFO  (JettyStart.java [run]:90) - Configuring eXist from /opt/exist/conf.xml
05 Oct 2019 14:09:58,329 [main] INFO  (JettyStart.java [run]:91) -
05 Oct 2019 14:09:58,329 [main] INFO  (JettyStart.java [run]:92) - Running with Java 1.8.0_144 [Oracle Corporation (Java HotSpot(TM) 64-Bit Server VM) in /usr/java/jdk1.8.0_144/jre]
05 Oct 2019 14:09:58,329 [main] INFO  (JettyStart.java [run]:97) -
05 Oct 2019 14:09:58,329 [main] INFO  (JettyStart.java [run]:101) - [eXist Version : 1.4.3]
05 Oct 2019 14:09:58,329 [main] INFO  (JettyStart.java [run]:103) - [eXist Build : 20120913]
05 Oct 2019 14:09:58,329 [main] INFO  (JettyStart.java [run]:105) - [eXist Home : /opt/exist]
05 Oct 2019 14:09:58,330 [main] INFO  (JettyStart.java [run]:107) - [SVN Revision : 17131]
05 Oct 2019 14:09:58,330 [main] INFO  (JettyStart.java [run]:115) - [Operating System : Linux 3.10.0-957.21.3.el7.x86_64 amd64]
05 Oct 2019 14:09:58,330 [main] INFO  (JettyStart.java [run]:118) - [jetty.home : /opt/exist/tools/jetty]
05 Oct 2019 14:09:58,330 [main] INFO  (JettyStart.java [run]:120) - [log4j.configuration : file:/opt/exist/log4j.xml]
05 Oct 2019 14:09:59,700 [main] INFO  (FileResource.java [<clinit>]:60) - Checking Resource aliases
05 Oct 2019 14:09:59,762 [main] INFO  (HttpServer.java [setStatsOn]:1130) - Statistics on = false for org.mortbay.jetty.Server@1ed1993a
org.exist.EXistException: database instance 'exist' is not available
        at org.exist.storage.BrokerPool.getInstance(BrokerPool.java:295)
        at org.exist.storage.BrokerPool.getInstance(BrokerPool.java:280)
        at org.exist.JettyStart.run(JettyStart.java:156)
        at org.exist.JettyStart.main(JettyStart.java:60)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.exist.start.Main.invokeMain(Main.java:128)
        at org.exist.start.Main.run(Main.java:407)
        at org.exist.start.Main.main(Main.java:59)

**Comment by duncdrum** [comment]
@sbhusala wow that exist version is ancient, as such i don't think an issue here is the best spot to get help. Please contact our mailing list, with concrete details about the config modifications, and you usage scenario. There might be other users with very old exist versions running on contemporary hardware, that can maybe help. 

A lot has happened between exist v1 and v5, i would strongly encourage you to look into upgrading.

**Comment by dizzzz** [comment]
I agree; this ticket is more a support request, not a bug report.

**Comment by dizzzz** [comment]
> Any custom changes in e.g. conf.xml Yes.

what are these?

**Comment by duncdrum** [comment]
as mentioned before please contact the mailing list. We do not provide support for existv1 via GitHub tickets.
