### ISSUE TITLE
Bug in util:eval-with-context's handling of / when context item has been declared

### ISSUE THREAD

**Issue by joewiz** [eXist-db/exist#3039]
### What is the problem

Since #2155, the use of `/` when a context item has been declared in the prolog has worked correctly in eXist. 

However, when using [`util:eval-with-context`](http://exist-db.org/exist/apps/fundocs/index.html?q=eval-with-context) to evaluate an expression and override the default context, expressions that select `/` are not evaluated relative to the supplied context. Instead, `/` selects all database contents—proving that the context has not been properly set.

### What did you expect

I expected `util:eval-with-context` to correctly handle expressions against `/`.

For example, the following expression should return 1 but instead returns the count of documents in the database:

```xquery
util:eval-with-context("count(/)", (), false(), document { <x/> })
```

In contrast, setting the context item via prolog declaration works correctly. The following query returns `1`, not the count of documents in the database.

```xquery
xquery version "3.1";

declare context item := document { <x/> };

count(/)
```

Allowing users to set a context is precisely the purpose of `util:eval-with-context`. 

### Describe how to reproduce or add a test

The following XQSuite test raises an error:

```xquery
xquery version "3.1";

module namespace ewc="http://exist-db.org/xquery/eval-with-context";

declare namespace test="http://exist-db.org/xquery/xqsuite";

declare
    %test:assertEquals(1)
function ewc:root-node() {
    util:eval-with-context('count(/)', (), false(), document { <x/> })
};
```

The error:

```xml
<testcase name="root-node" class="ewc:root-node">
    <failure message="assertEquals failed." type="failure-error-code-1">1</failure>
    <output>376</output>
</testcase>
```

### Context information

- eXist-db version + Git Revision hash: 5.0.0 (release)
- Java version: OpenJDK 12.0.2+10
- Operating system: macOS 10.13.6
- 32 or 64 bit: 64 bit
- How is eXist-db installed: Mac DMG app
- Any custom changes in e.g. conf.xml: none

**Comment by joewiz** [comment]
The motivation for my report is similar to that of #2155. This time I'm reviewing final proofs of the manuscript of my forthcoming XQuery book, and I'm trying to test that all code samples work as expected. To do so, I've pasted them all into a single query as an array of maps; a separate array centrally defines the context items. (This is a pattern used in XQTS.) I'd tried to use `eval-with-context` to supply the context item for these code samples, and found unexpected errors. If there's a fix, I'd be grateful, as it would help with my proofing of the book before publication!

**Comment by joewiz** [comment]
While `util:eval-with-context` is eXist-specific, the corresponding function in BaseX, [`xquery:eval`](http://docs.basex.org/wiki/XQuery_Module#xquery:eval), is able to set the context item. The following expression in BaseX  returns `1` as expected. 

```xquery
xquery:eval("count(/)", map {"": document { <x/> } } )
```

**Comment by adamretter** [comment]
As well as https://github.com/adamretter/exist/commit/fe87ab4714328a462be73f511aa604fa421ca3ef which I just did yesterday, it looks like I already tried to fix and investigate this in the past but it stalled on waiting for comments from @wolfgangmm here - https://github.com/eXist-db/exist/pull/3163
