### ISSUE TITLE
5.0 indexes not recomputed after move($source, $target) operation

### ISSUE THREAD

**Issue by Jo-Calder** [eXist-db/exist#3040]
### What is the problem
base-uri($node) shows the URI where the resource containing $node was stored, rather than the location it has been moved to. 

### What did you expect
base-uri($node) shows the URI for the node's new location

### Describe how to reproduce or add a test
Within a collection `_shared-prefix_`, create a collection `staging` containing a collection `data` and within the latter a resource such as 

```
<index xmlns="http://example.org/namespace">
    <item>A</item>
</index>
```

Create a collection, sister to `staging` called `prod`.

Create an index scoping over both source and target, such as
```
<collection xmlns="http://exist-db.org/collection-config/1.0">
    <index xmlns:mynamespace="http://example.org/namespace">
        <range>
            <create qname="mynamespace:item" type="xs:string"/>
        </range>
    </index> 
</collection>
```

Check that the following returns a uri containing `staging`: 

```
xquery version "3.1";
declare namespace ns ="http://example.org/namespace";
base-uri(collection("_shared-prefix_")//ns:item)
```

Execute

`xmldb:move("_shared-prefix_/staging/data", "_shared-prefix_/prod")`

The XQuery above (with version spec) should not return a URI containing `_shared-prefix_/staging`.

### Context information

- eXist Version: 5.0.0
- eXist Build: 20190902160649
- Operating System: Linux 4.18.0-80.el8.x86_64 amd64 (RHEL 8)
- Java Version: 1.8.0_222
- How is eXist-db installed? (JAR installer, DMG, WAR file, clone from GitHub): JAR
- Any custom changes in e.g. conf.xml: (none)

**Comment by joewiz** [comment]
I can confirm this report. Below is an XQSuite test, with a minimal form of the test demonstrating the error:

```xquery
xquery version "3.1";

module namespace bum="http://exist-db.org/xquery/base-uri-move-test";

declare namespace test="http://exist-db.org/xquery/xqsuite";

declare variable $bum:XML := <item/>;

declare
    %test:setUp
function bum:setup() {
    let $testCol := xmldb:create-collection("/db", "test")
    let $testColA := xmldb:create-collection("/db/test", "a")
    let $testColB := xmldb:create-collection("/db/test", "b")
    let $testColAData := xmldb:create-collection("/db/test/a", "data")
    return
        (
            xmldb:store($testColAData, "test.xml", $bum:XML),
            xmldb:move($testColAData, $testColB)
        )
};

declare
    %test:tearDown
function bum:tearDown() {
    xmldb:remove("/db/test")
};

declare
    %test:assertEquals("/db/test/b/data/test.xml")
function bum:base-uri-after-move() {
    base-uri(collection("/db/test")/item)
};
```

The result:

```xml
<testcase name="base-uri-after-move" class="bu:base-uri-after-move">
    <failure message="assertEquals failed." type="failure-error-code-1">/db/test/b/data/test.xml</failure>
    <output>/db/test/a/data/test.xml</output>
</testcase>
```
