### ISSUE TITLE
id() is quite slow

### ISSUE THREAD

**Issue by jeti69** [eXist-db/exist#3052]
### What is the problem
> When using function id() I wonder why it takes such a long time to execute. In Monex >Profiling id() is listed with 6.4 s for about 5000 calls (cf. screen monex-profiling). 
![monex-profiling](https://user-images.githubusercontent.com/56030773/66920383-717c3d80-f023-11e9-9b4d-7c16c56fb0ae.png)
It seems quite a lot to me.

### What did you expect
> I would expect it being a lot faster, as Wolfgang Meier told me when visiting us at DOSCO, HD.

### Describe how to reproduce or add a test
> Thats difficult because data and xql code is complex. I attached a screen of the xql chunk as well (cf. screen xql-screen).
![xql-screen](https://user-images.githubusercontent.com/56030773/66920952-8efdd700-f024-11e9-9601-9366dc43299a.png)

> Attribute xml:id is only indexed as it automatically is.
> Our xml:ID values are added while XML data is imported.

### Context information
- eXist-db 5.0.0
- Java8u129
- Windows 7, 64 bit
- JAR installer

Best regards
Jens

**Comment by tuurma** [comment]
Hi Jens, it's very hard to work if we have no option to reproduce your situation. If I were to guess, I would search for the culprit in instantiating the collection - this can be quite costly if repeated 5 thousand times. If you could factor the fragment

`let $searchColl := ...`

somehow outside of the part which is iterating then it might help.

**Comment by joewiz** [comment]
Closing due to lack of response. Please reopen if you are able to supply the necessary details.
