### ISSUE TITLE
ERROR (PluginsManagerImpl.java [addPlugin]:239) - java.lang.ClassNotFoundException: org.exist.storage.md.MDStorageManager

### ISSUE THREAD

**Issue by patrickBoucly** [eXist-db/exist#3053]
### What is the problem
Error report on exist.log:
ERROR (PluginsManagerImpl.java [addPlugin]:239) - java.lang.ClassNotFoundException: org.exist.storage.md.MDStorageManager

### What did you expect
Installation without any error

### Describe how to reproduce or add a test
[log_install_exist471.txt](https://github.com/eXist-db/exist/files/3734430/log_install_exist471.txt)
I get this log error on installation step

### Context information
Please always add the following information
- eXist-db version 4.7.1
- Java version : Java8u171
- Operating system Debian 8 
- 64 bit
- How is eXist-db installed? (I download eXist-db-4.7.1.tar.bz2 on bintray and install the product as a service)

maybe related with https://github.com/eXist-db/exist/pull/2127?

Thanks for your support

**Comment by adamretter** [comment]
Thanks for reporting I believe that this was fixed in 5.0.0.

The error message is actually really just a warning and can be ignored.

**Comment by patrickBoucly** [comment]
thanks!
