### ISSUE TITLE
No returned compiled query into Pool 

### ISSUE THREAD

**Issue by alebastrov** [eXist-db/exist#3058]
Thank you for reporting your issue!

To be able to better understand you problem or suggestion, please add as much information as possible to this ticket. When there is no or just little information, it will be too difficult to work on it (and hence we will not be able to solve it)

Please fill in the following sections:

### What is the problem
> exist/exist-core/src/main/java/org/exist/storage/serializers/XIncludeFilter.java has borrowed from pool, but has no any return borrowed query back to it, although other classes do that
```
CompiledXQuery compiled = pool.borrowCompiledXQuery(serializer.broker, source);
```
(!) There is no finalize code
```
context.runCleanupTasks();
pool.returnCompiledXQuery(source, compiled);
```

### What did you expect
> that pool will be left unchanged after calling execute method

### Describe how to reproduce or add a test
> Just seen by eyes.

### Context information
Please always add the following information
- eXist-db version  (any+current)
- Java version N/A
- Operating system N/A
- 32 or 64 bit N/A

**Comment by alebastrov** [comment]
This was discovered due to fixing multithreading (OMG) issue with session variables, which are stuck somehow under high load

**Comment by adamretter** [comment]
I can confirm this is an issue.
