### ISSUE TITLE
Spatial index: GMLHSQLIndexWorker doesn't compiles

### ISSUE THREAD

**Issue by cmontemuino** [eXist-db/exist#306]
Please note that [GMLHSQLIndexWorker](https://github.com/eXist-db/exist/blob/develop/extensions/indexes/spatial/src/org/exist/indexing/spatial/GMLHSQLIndexWorker.java) class is not implementing [method getQueryRewriter from IndexWorker class](https://github.com/eXist-db/exist/blob/develop/src/org/exist/indexing/IndexWorker.java#L215).

BTW, I already checked the [AbstractGMLJDBCIndexWorker](https://github.com/eXist-db/exist/blob/develop/extensions/indexes/spatial/src/org/exist/indexing/spatial/AbstractGMLJDBCIndexWorker.java) and the method is not there.

**Comment by shabanovd** [comment]
Should we keep it, or it can be removed? Ask on ML?

**Comment by dizzzz** [comment]
check with pierrick at least ; he is the author; I studied the deps a few times, some downloads are missing. The spatial jars are now on Maven, but we only need a subset. The question is....... which? Tests are not complete

**Comment by adamretter** [comment]
@dizzzz I think it is kinda cool. However someone needs to own this code, i.e. make it compile, pass its tests and write some documentation so people can use it. I am not sure I am that person...

**Comment by dizzzz** [comment]
I could take the lead here.....

**Comment by adamretter** [comment]
Sold! ...to the man in the Orange avatar.

**Comment by dizzzz** [comment]
fixed with https://github.com/eXist-db/exist/pull/1249
