### ISSUE TITLE
Modules have shared non-deep-copied variables in different XQueryContexts (in CompiledXQuery))

### ISSUE THREAD

**Issue by alebastrov** [eXist-db/exist#3066]
Let's imagine we have 2 compiled XQueries. Each of them has its own `XQueryContext`.
Each context has loaded modules within. Let it be a module 'session' with session variable "xxx" that is equal to '0'.

If executing query sets a value for this variable to '1', EACH module with same session will get new value for the variable. Moreover, prepareForReuse() method is always clearing variables value, that may harm other compiled queries.

The issue should be fixed by creating deep-copy methods for Variable (VariableImpl, LocalVariable, etc.)  and copying context should also use deep copies for every variable in every module

### What is the problem
> XQueryContext has non-deep-copied 'contextStack', 'lastVar', etc fields, which are subject to be used separately if XQueryContext is created from another one

### What did you expect
> each XQueryContext HAS ITS OWN variables (hashcodes for variable with the same name should be different in different contexts)

### Describe how to reproduce or add a test
> Under high load we face a situation, when session variable 'xxx' is suddently changed (actually its values is cleared by prepareForReuse() method)

`2019-10-23 00:56:18,818 [https-jsse-nio-443-exec-2] INFO  (Transform.java [getContextSource]:782) - Variable (session) 33702864 is found in module 1598796643 
2019-10-23 00:56:18,819 [https-jsse-nio-443-exec-2] INFO  (Transform.java [getContextSource]:793) - JavaObjectValue 717019222 is found 
2019-10-23 00:56:18,820 [https-jsse-nio-443-exec-2] INFO  (Transform.java [getContextSource]:800) - Processing session@ 1004071787 with id 5B58E660C925B6D03EC0C121CF778929 in context 1011853826... 
2019-10-23 00:56:18,821 [https-jsse-nio-443-exec-2] INFO  (Transform.java [getContextSource]:809) - Session attribute lc.context.state found and it's in-memory#element 
` 
and several seconds later
`
2019-10-23 00:56:38,995 [https-jsse-nio-443-exec-9] INFO  (Transform.java [getContextSource]:782) - Variable (session) 33702864 is found in module 1598796643 
2019-10-23 00:56:38,996 [https-jsse-nio-443-exec-9] INFO  (Transform.java [getContextSource]:793) - JavaObjectValue 1166781280 is found 
2019-10-23 00:56:38,997 [https-jsse-nio-443-exec-9] INFO  (Transform.java [getContextSource]:800) - Processing session@ 1298060714 with id 5B58E660C925B6D03EC0C121CF778929 in context 1011853826... 
2019-10-23 00:56:38,998 [https-jsse-nio-443-exec-9] ERROR (Transform.java [getContextSource]:805) - No session attribute lc.context.state found `

You may see it above - first 4 rows show 'lc.context.state' variable is set to something, second 4 rows show that it's empty.
The load was there about 500k requests to get filtered content, filter is described in value of ' lc.context.state' session attribute

### Context information
Please always add the following information
- eXist-db version any
- Java version N/A
- Operating system N/A
- 32 or 64 bit N/A
- How is eXist-db installed? N/A
- Any custom changes in e.g. conf.xml N/A

**Comment by alebastrov** [comment]
This has been found while investigation issue with multithreading under high-load

**Comment by adamretter** [comment]
Is there some simple XQuery which run under heavy concurrent load will show this problem?

**Comment by alebastrov** [comment]
We have XQueryContext and requesting
'SessionModule module = (SessionModule) context.getModule(SessionModule.NAMESPACE_URI);' module

**Comment by adamretter** [comment]
@alebastrov That looks okay. Each `XQueryContext` should have its own instance of the `SessionModule.

I need more information about what you are then doing and why you think variables are getting scattered.

Also eXist-db 5.0.0 does not have a `SessionModule.SESSION_VAR` - so I think perhaps you have not tried this against the latest version of eXist-db?

**Comment by alebastrov** [comment]
It's fixed 2.2 version
But I reckon there is no difference between 2.2 and 5.0 versions, because the reason is that compiled query has its XQueryContext which MIGHT BE COPIED from another context.

The solution for issue is to use deep-copy for each non-primitive thing when context is being copied

**Comment by alebastrov** [comment]
As you can see from logs SessionWrapper has changed between logs. It supposed to be impossible.
But it turned out that XQueryContext might be copied from another one and after that both contexts are using THE SAME modules and variables inside them

**Comment by adamretter** [comment]
> XQueryContext which MIGHT BE COPIED

This only happens for `util:eval` as far as I can see, which would happen in the same thread, so not a problem.

> As you can see from logs SessionWrapper has changed between logs. It supposed to be impossible.

It's hard to know what your logs are showing.
The session is a piece of mutable memory held by the HTTP Server (Jetty) and it is shared between all query threads. If one query sets a session attribute, that will be reflected in all other queries that share the same session ID. So actually I think perhaps what you are seeing is expected?

Please test against 5.0.0, and report back anything that does not fit with what I just described.

**Comment by alebastrov** [comment]
so if some compiled xql code contains util:eval() will it use the same session?

**Comment by alebastrov** [comment]
existdb 5.0 is not a variant for us, because it'll take us several months to move on, with no guarantee we won't face the problems we've fixed in 2.2

**Comment by adamretter** [comment]
> so if some compiled xql code contains util:eval() will it use the same session?
It will use the same session as the parent query in which it is running.

> existdb 5.0 is not an option for us, because it'll take us several months to move on
I appreciate that moving to eXist-db is not easy. Conversely, I am afraid I cannot support older versions of eXist-db indefinitely.

> with no guarantee we won't face the problems we've fixed in 2.2
The only way to know, is for you to test it!

**Comment by line-o** [comment]
@alebastrov What do you mean with fixed version? Could you share what you changed?
> It's fixed 2.2 version

**Comment by alebastrov** [comment]
not sure that it's still a problem as we gave up using existdb
