### ISSUE TITLE
Parallel tests need separate log files.

### ISSUE THREAD

**Issue by adamretter** [eXist-db/exist#3094]
When we run tests in parallel each test has a separate data folder, this is usually enforced by the use of the `useTemporaryStorage` parameter to `ExistEmbeddedServer`.

At the moment the tests do not use separate Log4j log files. Ideally these need to be separated to also use temporary storage, otherwise two tests running in parallel can have file locking issues on the same log file on Windows.

**Comment by duncdrum** [comment]
good to close with https://github.com/eXist-db/exist/pull/3064/commits/67532c194d8576440d861dec338d5d0e033b1693 ?

**Comment by adamretter** [comment]
@duncdrum yup thanks
