### ISSUE TITLE
eXist 5.1.0 Cannot start from dmg on macOS 10.15.2 (beta)

### ISSUE THREAD

**Issue by ahenket** [eXist-db/exist#3120]
### The problem
The eXist-db.app does not run on macOS Catalina because the "developer cannot be verified"

<img width="546" alt="Schermafbeelding 2019-11-19 om 07 51 53" src="https://user-images.githubusercontent.com/5390573/69123465-bc192b80-0aa1-11ea-81e4-d61a3fcc8cdd.png">

### Expectation
Being able to start eXist-db.app

### Reproduction
Drag eXist-db.app to /Applications and double click it from there

### Workaround in terminal.app
`find /Applications/eXist-db.app -name "*" -exec xattr -d com.apple.quarantine {} \;`

### Environment
macOS 10.15.2 bèta (19C39d), vanilla download of the eXist-db.dmg from https://bintray.com/existdb/releases/exist/5.1.0/view

**Comment by adamretter** [comment]
@ahenket I am on macOS 10.14.5 ("Mojave") and I get the following error:

<img width="424" alt="Screenshot 2019-11-19 at 13 47 59" src="https://user-images.githubusercontent.com/1264057/69151838-56de2e00-0ad3-11ea-96e1-522afed59f93.png">

Are you able to confirm if that is the same error that you get?

**Comment by adamretter** [comment]
The `codesign` utility seems to show that neither the DMG file or the subsequent .app file are signed. This is rather bizare as signing is part of the release process. Let me see if I can correct this...

```
$ codesign -dv --verbose=4 ~/Downloads/eXist-db-5.1.0.dmg
/Users/aretter/Downloads/eXist-db-5.1.0.dmg: code object is not signed at all
```

```
$ codesign -dv --verbose=4 /Applications/eXist-db.app
/Applications/eXist-db.app: code object is not signed at all
```

**Comment by adamretter** [comment]
@ahenket It seems I made some sort of mistake in the release process.

I have now uploaded an updated DMG which is now correctly signed, its SHA256 checksum is `5cb87626efe0341d74fa700c04cca80790961950e09405aac88ac178f8328734`.

Thanks for reporting :-)

**Comment by ahenket** [comment]
The new download still triggers Gatekeeper "Apple cannot check for malicious software", but the difference is that I can now choose "Open Anyway" from the System Preferences > Security and Privacy > General tab

![Schermafbeelding 2019-11-19 om 18 49 38](https://user-images.githubusercontent.com/5390573/69172221-bc471480-0afd-11ea-8ea4-db9c1aebc475.png)

The suggestion in Dutch on this dialog is that the software "needs to be updated". Presumably there is another step involved next to signing to keep Apple gatekeeper happy.

**Comment by joewiz** [comment]
This isn’t new to 5.1.0 - it’s a Catalina issue for all versions of eXist on macOS started via .app. As I [posted to Slack a few weeks ago](https://exist-db.slack.com/archives/CG2MRUZ35/p1571242322041700):

> On macOS 10.15 Catalina, opening a fresh installation of eXist-db raises the following warning, because eXist’s binaries haven’t been notarized with Apple, as described here: https://developer.apple.com/documentation/xcode/notarizing_your_app_before_distribution#3087722.

**Comment by adamretter** [comment]
@joewiz Can we move this to a separate issue, as the title of this issue and the initial reported problem is not the same as the notarization stuff
