### ISSUE TITLE
display problem

### ISSUE THREAD

**Issue by SnowMakerDemo** [eXist-db/exist#3135]
![image](https://user-images.githubusercontent.com/28621460/69933363-64e77200-1509-11ea-94dd-fabba8ffe797.png)

eXist-db   eXist-db 5.1.0
windows10    computer's encoding GB2312
what should i do?

**Comment by adamretter** [comment]
Hmm... this looks like it could perhaps be a localisation issue where the client has chosen the wrong language translation file.

What result do you get if you run the following Java application from the `cmd.exe` on your machine?

```
import java.util.Locale;

public class LangMain {
  public static void main(final String args[]) {
    System.out.println(Locale.getDefault().getLanguage());
  }
}
```

**Comment by SnowMakerDemo** [comment]
zh

**Comment by dizzzz** [comment]
the definition is in https://github.com/eXist-db/exist/blob/0093df9c639e02f81a37340d24852d666a4843f9/exist-core/src/main/resources/org/exist/client/messages_zh_CN.properties :-/

**Comment by dizzzz** [comment]
@SnowMakerDemo  please please fill in the mandatory Issue template as important info is missing right now, e.g. what java implementation do you use?

**Comment by adamretter** [comment]
So you have a Chinese encoding and language setting. I then suspect that the font used doesn't support the appropriate unicode code points

**Comment by SnowMakerDemo** [comment]
Thank you for reporting your issue!

To be able to better understand you problem or suggestion, please add as much information as possible to this ticket. When there is no or just little information, it will be too difficult to work on it (and hence we will not be able to solve it).

Please fill in the following sections:

### What is the problem
display problem

### What did you expect
> display normal

### Describe how to reproduce or add a test
> 

> The *best* way is to provide an [SSCCE (Short, Self Contained, Correct (Compilable), Example)](http://sscce.org/). One type of SSCCE could be a small test which reproduces the issue and can be run without dependencies. The [XQSuite - Annotation-based Test Framework for XQuery](http://exist-db.org/exist/apps/doc/xqsuite.xml) makes it very easy for you to create tests. These tests can be executed from the [eXide editor](http://exist-db.org/exist/apps/eXide/index.html) (XQuery - Run as Test)

### Context information
Please always add the following information
- eXist-db version + Git Revision hash e.g. eXist-db 3.0 /  acd0c14 
![image](https://user-images.githubusercontent.com/28621460/70106563-f5938e80-167e-11ea-9125-3b3ebc05f281.png)

- Java version (e.g. Java8u121)
![image](https://user-images.githubusercontent.com/28621460/70106591-06dc9b00-167f-11ea-9ea7-6f7d745e3b25.png)

- Operating system (Windows 7, Linux, MacOs)
Windows 10
- 64 bit
- How is eXist-db installed? 
JAR installer
- Any custom changes in e.g. conf.xml
no  

if the font used doesn't support the appropriate unicode code points,what should i do ?   thank you.

**Comment by SnowMakerDemo** [comment]
hello @dizzzz,  :) . LoginPanel.2=\u00e7\u0094\u00a8\u00e6\u0088\u00b7\u00e5\u0090\u008d ， when i change LoginPanel.2  to \u7528\u6237\u540d\u79f0   page display ,
![image](https://user-images.githubusercontent.com/28621460/70120376-65b60a80-16a7-11ea-9ed3-3ea030ad79bb.png)
![image](https://user-images.githubusercontent.com/28621460/70120393-6fd80900-16a7-11ea-9cf5-19552c6b30c3.png)
What is  \u00e7\u0094\u00a8\u00e6\u0088\u00b7\u00e5\u0090\u008d   translated into Chinese?

**Comment by adamretter** [comment]
@SnowMakerDemo I am not sure if the problem is the Font, the CodePage or both. I am afraid that I am no expert in Chinese language display in Java.

I did a quick search and discovered this article: https://docs.oracle.com/javase/6/docs/technotes/guides/intl/fontconfig.html

If I look in the fontconfig properties file for Java on my Mac machine (`/Library/Java/JavaVirtualMachines/zulu8/jre/lib/fontconfig.properties.src`), I see references to code page GB18030, but not GB2312.

So it looks like Java might support codepage GB18030 but not GB2312.

A further bit more Googling reveals this article - https://en.wikipedia.org/wiki/GB_18030 which seems to say that GB18030 has replaced GB2312.

You might like to try one of two things:
1. Can you change the codepage for your machine to GB2312? This might be the easiest option.
2. Otherwise, you could follow the article https://docs.oracle.com/javase/6/docs/technotes/guides/intl/fontconfig.html to generate your own fontconfig for GB2312.

**Comment by adamretter** [comment]
> What is `\u00e7\u0094\u00a8\u00e6\u0088\u00b7\u00e5\u0090\u008d` translated into Chinese?

The above is a sequence of unicode code points expressed in Java String literal format. Each codepoint starts `\u` and then is followed by 4 hexadecimal digits which indicate its Unicode codepoint number. You can lookup the codepoints in a Unicode table on the web.

**Comment by SnowMakerDemo** [comment]
hello @adamretter  \u00e7    unicode   is   
![image](https://user-images.githubusercontent.com/28621460/70128408-bb92ae80-16b7-11ea-9d60-1f140ab08a8a.png)   
 is that right?

**Comment by adamretter** [comment]
@SnowMakerDemo that's correct

**Comment by SnowMakerDemo** [comment]
hello @adamretter   could you give me  url where i can find the 00e7 ?   thank you very much

**Comment by adamretter** [comment]
@SnowMakerDemo Sorry, I don't understand what you are asking for

**Comment by SnowMakerDemo** [comment]
hello  @adamretter  ， I overwrote the zh file in the exist-core.jar，change unicode from latin1  to utf-8 .  
native2ascii -reverse -encoding latin1 .\messages_zh_CN.properties .\test.properties
native2ascii -encoding utf-8 .\test.properties .\messages_zh_CN.properties
Please let me know if there is a good way in the future,thank you.

![image](https://user-images.githubusercontent.com/28621460/70200192-9bfa9500-174e-11ea-8c0d-141eb7ac8022.png)

**Comment by adamretter** [comment]
@SnowMakerDemo So, did you have to fix the zh file?
If so, would you be able to submit the updated file via a Pull Request?

**Comment by SnowMakerDemo** [comment]
hello @adamretter ，I‘m sorry for replying you so late。

cmd   input Two lines of command
native2ascii -reverse -encoding latin1 .\messages_zh_CN.properties .\test.properties
native2ascii -encoding utf-8 .\test.properties .\messages_zh_CN.properties

 ,And then replace the old messages_zh_CN.properties with  the new  messages_zh_CN.properties  。  I didn't fix the Java code。

**Comment by dizzzz** [comment]
looks like a simple fix, a PR is appreciated
