### ISSUE TITLE
Existdb 5.1.0 Context module removed. What used now?

### ISSUE THREAD

**Issue by rpompaideasoft** [eXist-db/exist#3138]
Thank you for reporting your issue!

To be able to better understand you problem or suggestion, please add as much information as possible to this ticket. When there is no or just little information, it will be too difficult to work on it (and hence we will not be able to solve it).

Please fill in the following sections:

### What is the problem
> Context module removed and there are no alternatives

### What did you expect
> Any alternative that provides the same functions or a different approach that solves the problem

### Describe how to reproduce or add a test
> We are migrating from exist db 4.7 to existdb 5.1.0 and we see these inconveniences.
> Example function: context:get-attribute()
> Error: No namespace defined for prefix context. QName is invalid:            INVALID_PREFIX

**Comment by adamretter** [comment]
The Context Module allowed an XQuery to effectively write and read mutable variables whose lifetime was only related to the execution of that query.

XQuery is a functional programming language, and as such does not allow mutable variables. The Context Module allowed the user to write bad code. The mutable variables permitted by the Context Module, prevented a whole raft of potential automated optimisations that we could employ.

If you previously used the Context Module, then you just need to slightly restructure your code to use immutable variables and pass state around.
