### ISSUE TITLE
How include custom extensions on existdb 5?

### ISSUE THREAD

**Issue by rpompaideasoft** [eXist-db/exist#3139]
### What is the problem
> We have a custom library and we want to include it in existdb 5.1.0
>Error:
Lucene index: analyzer class org.lucene.custom.analyzers.WhitespaceAnalyzerWithFilters not found. (org.lucene.custom.analyzers.WhitespaceAnalyzerWithFilters) 
2019-12-04 14:42:20,868 [global.launcher.startJetty] WARN  (LuceneConfig.java [parseConfig]:336) - Invalid lucene configuration element: No analyzer configured for id custom-ws 

### What did you expect
> The library is used to analyze indexes. 
>Example:
`<collection xmlns="http://exist-db.org/collection-config/1.0">
    <index xmlns:cs="http://custom-v1" xmlns:dc="http://purl.org/dc/terms">
        <fulltext default="none" attributes="false"/>
        <lucene>
            <analyzer class="org.apache.lucene.analysis.standard.StandardAnalyzer"/>
            <analyzer id="ws" class="org.apache.lucene.analysis.core.WhitespaceAnalyzer"/>
            <analyzer id="custom-ws" class="org.lucene.custom.analyzers.WhitespaceAnalyzerWithFilters"/>
            <text qname="cs:urn" analyzer="custom-ws"/>
            <text field="cs:urn" qname="cs:urn" analyzer="custom-ws"/>
        </lucene>
    </index>
</collection>`

### Describe how to reproduce or add a test
> Import or create an XML file in the collection where the indexes are defined

### Context information
- eXist-db 5.1.0
- Java 8
- Operating system Windows
- 64 bit

**Comment by joewiz** [comment]
I'm curious, where have you tried placing the library? Specifically, what location causes this error?

**Comment by rpompaideasoft** [comment]
> 
> 
> I'm curious, where have you tried placing the library? Specifically, what location causes this error?

>Having define the following index:
<collection xmlns="http://exist-db.org/collection-config/1.0">
    <index xmlns:cm="http://common" xmlns:dc="http://purl.org/dc/terms">
        <fulltext default="none" attributes="false"/>
        <lucene>
            <analyzer class="org.apache.lucene.analysis.standard.StandardAnalyzer"/>
            <analyzer id="ws" class="org.apache.lucene.analysis.core.WhitespaceAnalyzer"/>
            <analyzer id="custom-ws" class="org.lucene.custom.analyzers.WhitespaceAnalyzerWithFilters"/>
            <text qname="cm:urn" analyzer="custom-ws"/>
            <text qname="cm:code" analyzer="custom-ws"/>
        </lucene>
    </index>
</collection>

> Exist try indexed the collection but at not find the extension throw the error in log file(exist.log). Example:
2019-12-04 17:30:50,919 [global.launcher.startJetty] ERROR (AnalyzerConfig.java [configureAnalyzer]:174) - Lucene index: analyzer class org.lucene.custom.analyzers.WhitespaceAnalyzerWithFilters not found. (org.lucene.custom.analyzers.WhitespaceAnalyzerWithFilters) 
2019-12-04 17:30:50,919 [global.launcher.startJetty] WARN  (LuceneConfig.java [parseConfig]:336) - Invalid lucene configuration element: No analyzer configured for id custom-ws 

> Our extension is "lucene-custom-analyzer.jar" but we dont know how included in existdb 5.1.0

**Comment by adamretter** [comment]
@rpompaideasoft place the Jar file in $EXIST_HOME/lib and add it to `$EXIST_HOME/etc/startup.xml`, and `$EXIST_HOME/etc/client.xml` and then restart eXist-db.

**Comment by rpompaideasoft** [comment]
> 
> 
> @rpompaideasoft place the Jar file in $EXIST_HOME/lib and add it to `$EXIST_HOME/etc/startup.xml`, and `$EXIST_HOME/etc/client.xml` and then restart eXist-db.

Perfect!!!
