### ISSUE TITLE
http://exist-db.org/api/index.html  404

### ISSUE THREAD

**Issue by SnowMakerDemo** [eXist-db/exist#3143]
Thank you for reporting your issue!

To be able to better understand you problem or suggestion, please add as much information as possible to this ticket. When there is no or just little information, it will be too difficult to work on it (and hence we will not be able to solve it).

Please fill in the following sections:

### What is the problem
> Describe exactly what you see (e.g. an output of an XQuery) 
![image](https://user-images.githubusercontent.com/28621460/70287130-e2142f00-1808-11ea-917f-b8318bbc5248.png)
![image](https://user-images.githubusercontent.com/28621460/70287148-f0624b00-1808-11ea-9903-1b5b4bf11b53.png)

### What did you expect
> display normal

**Comment by duncdrum** [comment]
see https://github.com/eXist-db/documentation/issues/140

**Comment by SnowMakerDemo** [comment]
@duncdrum  thank you :)
