### ISSUE TITLE
Why is the parameter "id" of the function "createResource" in class "RemoteCollection" final?

### ISSUE THREAD

**Issue by novNorthSea** [eXist-db/exist#3152]
I want to add my resource in my java application through the `createResource` interface. But the implementation of the function `createResource` in `RemoteCollection` makes the parameter to be final and I can not dynamically set my resource id. So I have to change to the embed mode. By the way, the embed mode is a little complexed to configure.

**Comment by dizzzz** [comment]
Please could you fill-in the template as the report is not clear to us, a lot of details is missing. As it looks like a request for help and not a bug report, please send your question -with a bit more details- to the exist-open mailing list.

**Comment by dizzzz** [comment]
A piece of code would help too.

**Comment by adamretter** [comment]
@novNorthSea The id is the filename of the resource. This is given at Resource creation time, i.e.:

```java
try (final EXistResource resource = (EXistResource) collection.createResource("myfile.xml", XMLResource.RESOURCE_TYPE)) {
resource.setContent("<hello/>");
collection.storeResource(resource);
}
```

**Comment by dizzzz** [comment]
@adamretter thnx; but as no indication was  made regarding the eXist-db version... answering was not so straightforward :-/

**Comment by novNorthSea** [comment]
> @adamretter thnx; but as no indication was made regarding the eXist-db version... answering was not so straightforward :-/



> @novNorthSea The id is the filename of the resource. This is given at Resource creation time, i.e.:
> 
> ```java
> try (final EXistResource resource = (EXistResource) collection.createResource("myfile.xml", XMLResource.RESOURCE_TYPE)) {
>   resource.setContent("<hello/>");
>   collection.storeResource(resource);
> }
> ```

The eXist-db version is 5.1.0.
The impletition in "LocalCollection" is not the same. I think the resource id should be dynamically set when it is created in stand-alone mode. I check the git log and this was changed in 2013/1/30. The revision number is 8fe5cc978f9b24ebbed0503a7518e244db2adae8.

`org.exist.xmldb.LocalCollection#createResource(String id, final String type)`
`org.exist.xmldb.RemoteCollection#createResource(final String id, final String type)`

**Comment by dizzzz** [comment]
Hi, maybe I do not understand "But the implementation of the function createResource in RemoteCollection makes the parameter to be final and I can not dynamically set my resource id."  why final will make it impossible to dynamically set it. As a caller it would make no difference no?

**Comment by adamretter** [comment]
@novNorthSea I think you are confusing a final method parameter with the immutability of the object's field. Strings in Java are immutable and passed by reference-value, so whether we have:

`createResource(String id, final String type)` or `createResource(final String id, final String type)` makes absolutely no difference for the caller of the method. The `final` is used to ensure type-safety and document expected behaviour for the implementation inside the method.

**Comment by novNorthSea** [comment]
> Hi, maybe I do not understand "But the implementation of the function createResource in RemoteCollection makes the parameter to be final and I can not dynamically set my resource id." why final will make it impossible to dynamically set it? As a caller it would make no difference no?



> @novNorthSea I think you are confusing a final method parameter with the immutability of the object's field. Strings in Java are immutable and passed by reference-value, so whether we have:
> 
> `createResource(String id, final String type)` or `createResource(final String id, final String type)` makes absolutely no difference for the caller of the method, i.e. you.
> 
> The `final` is used to ensure type-safety and document expected behaviour for the implementation inside the method. This is only useful for the developers of that method, i.e. us.

Sorry for not stating my problem clearly at the first time.

I'm calling this function in a RESTful web API and the value of the parameter `id` is passed through the request. The value of `id` changes to "null" in this function but not the value I pass.

**Comment by dizzzz** [comment]
Hmmm, your statement makes no sense, for the reasons mentioned by adam; this is a fundamental Java question actually, not an API call question. And... Strings are immutable too...

**Comment by adamretter** [comment]
@novNorthSea I think you are confused somewhere. `RemoteCollection` is part of the XML:DB API, it is not used in the REST API.

**Comment by novNorthSea** [comment]
@dizzzz @adamretter 
`
    @PostMapping("/test")
    public void test(String resourceId) {

        final String driver = "org.exist.xmldb.DatabaseImpl";

        Collection col = null;
        XMLResource res = null;

        try {
            // initialize database driver
            Class cl = Class.forName(driver);
            Database database = (Database) cl.newInstance();
            database.setProperty("create-database", "true");
            DatabaseManager.registerDatabase(database);
            col = getOrCreateCollection("test");

            // create new XMLResource; an id will be assigned to the new resource
            **res = (XMLResource) col.createResource(resourceId, "XMLResource");**
            File f = new File("test.xml");
            if (!f.canRead()) {
                System.out.println("cannot read file test.xml");
                return;
            }

            res.setContent(f);
            System.out.print("storing document " + res.getId() + "...");
            col.storeResource(res);
            System.out.println("ok.");
        } catch (XMLDBException | ClassNotFoundException e) {
            e.printStackTrace();
        } finally {
            //dont forget to cleanup
            if (res != null) {
                try {
                    ((EXistResource) res).freeResources();
                } catch (XMLDBException xe) {
                    xe.printStackTrace();
                }
            }

            if (col != null) {
                try {
                    col.close();
                } catch (XMLDBException xe) {
                    xe.printStackTrace();
                }
            }
        }
    }
`

I call `createResource` in a RESTful API like above. I can set the id of my resource through `org.exist.xmldb.LocalCollection#createResource`. But I cannot do this when I use `org.exist.xmldb.RemoteCollection#createResource`.

**Comment by adamretter** [comment]
@novNorthSea OH! I see you are building your own REST API! Sorry I thought you meant eXist-db's built-in REST API.

So, if the above example works for you, can you show me an example that does not work?

**Comment by novNorthSea** [comment]
@adamretter 
Sorry for not replying in time.
The above example works in the embedded mode, since the implementation of the class `Collection ` is  `LocalCollection `. It won't work in stand-alone mode since the implementation of the class `Collection ` is  `RemoteCollection `.

**Comment by adamretter** [comment]
@novNorthSea What do you mean by "won't work", can you describe the specific error and where it occurs?

**Comment by novNorthSea** [comment]
@adamretter It means in stand-alone mode, the following code
`res = (XMLResource) col.createResource(resourceId, "XMLResource");`
won't work as I want. The `resourceId` becames "null" in the function `createResource ` of the class `RemoteCollection `.

**Comment by adamretter** [comment]
@novNorthSea I still don't think I understand what you are asking as it is impossible for `createResource` to modify the variable `resourceId`. In addition the implementation here does not set anything to `null` - `https://github.com/eXist-db/exist/blob/develop/exist-core/src/main/java/org/exist/xmldb/RemoteCollection.java#L148`

**Comment by adamretter** [comment]
@novNorthSea any further question?

**Comment by adamretter** [comment]
Closing due to a lack of response.
