### ISSUE TITLE
[BUG] Cannot set sticky bit

### ISSUE THREAD

**Issue by ahenket** [eXist-db/exist#3157]
**Describe the bug**
I was trying to set the sticky bit on a collection so any file created in that collection would be rw- for the group.

Based on http://www.exist-db.org/exist/apps/doc/security.xml?field=all&id=D3.25.7.29#unix-model I expected this would work:

```Xquery
sm:chmod(xs:anyURI($d), 'rwxrwtr-x')
```

The error I get is:

```exerr:ERROR Permission to modify permissions is denied for user 'admin' on '/db/apps/testcoll': Unrecognised mode syntax: Unknown mode String: rwxrwtr-x [at line 2, column 12]```

**Expected behavior**
I would have expected the sticky bit on that collection. Since this does not work for v2.2 nor v5.1 I'm expecting a syntax problem, but the eXist-db/Wikipedia documentation has not proven sufficient to find my error in that case.

**To Reproduce**
```Xquery
let $d  := xmldb:create-collection(repo:get-root(), 'testcoll')
let $c  := sm:chmod(xs:anyURI($d), 'rwxrwtr-x')

return
sm:get-permissions(xs:anyURI($d))
```

**Context:**
- I tried this on eXist-db 2.2 running on CentOS (jar version) and
- eXist-db 5.1 running on macOS (dmg version)

**Comment by line-o** [comment]
Since the execution is needed for collections you should use 'rwxrwTr-x' instead.

**Comment by adamretter** [comment]
@line-o `T` removes `x`, so then in your example a group would not be able to access that collection, is that what you wanted?

**Comment by line-o** [comment]
@line-o oh, never mind I mixed up the two 🍡

**Comment by ahenket** [comment]
For the record: changing to capital T (which should have been legal too):

```XQuery
let $c  := sm:chmod(xs:anyURI($d), 'rwxrwTr-x')
```

yields:

```No such handler: Default.queryPT```

**Comment by ahenket** [comment]
My current workaround is a sticky bit on the group and ACL that allows read/write. Sticky bit seems much cleaner in potential

**Comment by adamretter** [comment]
@ahenket Upon closer inspection in this instance I think the error message is correct, and you have a mistake in your mode.

As per the eXist-db documentation:

> In a permission string, the sticky bit permission replaces the execute (x) marker of the others.

You are trying to use the sticky bit in the marker of the *group* not *others*.

Presumably, you instead want the mode: 'rwxrwxr-T'

**Comment by adamretter** [comment]
@ahenket feel free to re-open if I have misunderstood.

**Comment by ahenket** [comment]
eXist-db 5.1.1 latest stable

```
let $d  := xmldb:create-collection(repo:get-root(), 'testcoll')
let $c  := sm:chmod(xs:anyURI($d), 'rwxrwxr-T')

return
sm:get-permissions(xs:anyURI($d))
```

`exerr:ERROR Permission to modify permissions is denied for user 'admin' on '/db/apps/testcoll': Unrecognised mode syntax: Unknown mode String: rwxrwxr-T [at line 2, column 12]`
