### ISSUE TITLE
[BUG] Prompting for desktop shortcuts during installation on headless system

### ISSUE THREAD

**Issue by contra8** [eXist-db/exist#3161]
**Describe the bug**
At the end of an installation on a headless system (Ubuntu) I am asked if I want shortcuts to be created on the desktop and in the Start Menu.

**Expected behavior**
Those shortcuts seem to make sense on a Windows system but not on a headless Ubuntu system. You should not be prompted to create those or not.

**To Reproduce**
Start installation via command line:
`java -jar exist-installer-5.1.1.jar -console`
At the end of installation, this dialog appears:
>**Setup Shortcuts**
>Create shortcuts in the Start Menu
>Enter Y for Yes, N for No:
>n
>**Create additional shortcuts on the desktop**
>Enter Y for Yes, N for No:
>n

**Context**
OS: Ubuntu 12.04 TLS (headless system)
eXist-db version: 5.1.1
Java version: OpenJDK 1.8.0_111

**Screenshots**
Screenshots of the dialog displayed can be found in my Dropbox [here](https://www.dropbox.com/s/63hqwsr1upmqoda/2019-12-10%2017.20.20.jpg?dl=0).

**Comment by adamretter** [comment]
@contra8 Actually I think this might be legitimate behaviour.

For example, you might opt to create shortcuts on a headless system but then install X11+Gnome/KDE, at which point the shortcuts are available to you.

Likewise, if you had X11 installed and you wanted to install via the console, you might still want to create the shortcuts.

As it offers you the option to not install the shortcuts, I think we have all use-cases covered.

Feel free to re-open the issue if you feel there is still a problem...
