### ISSUE TITLE
[BUG] Incorrect facet count with field query

### ISSUE THREAD

**Issue by joewiz** [eXist-db/exist#3207]
**Describe the bug**

When performing a field-based full text query, `ft:facet` returns incorrect results if the element name queried with `ft:query` is surrounded with parentheses. 

Here's a common use case that requires the use of parentheses: let's say we want to search the "title" field of our TEI *and* DocBook documents for the term "china", and return information on the "year-published" facet results. We should be able to do this, by querying both TEI and DocBook documents at once:

```xquery
collection("/db/data")/(tei:TEI|dbk:article)[ft:query(., "title:china")] 
=> ft:facets(map {"facets": "year-published"})
```

However, as the test query below shows, the use of parentheses around the element name—even a single name—causes `ft:facets` to return incorrect results.

**Expected behavior**

I expected ft:facet to produce correct results, despite the presence of parentheses in the ft:query expression that produces the hits.

**To Reproduce**

In the following xqsuite test, based on https://github.com/eXist-db/exist/blob/develop/extensions/indexes/lucene/src/test/xquery/lucene/facets.xql#L418-L429, the only change is that I have replaced `div` with `(div)`:

```xquery
declare
    %test:assertEquals(1)
function facet:query-no-default-index-but-facet() {
    let $result := doc("/db/lucenetest/multi-lang.xml")//(div)[ft:query(., "english:*", map { "leading-wildcard": "yes" })]
    return
        ft:facets($result, "language")?en
};
```

Instead of returning the expected result, 1, this version of the query returns 11:

```xml
<testcase name="query-no-default-index-but-facet" class="facet:query-no-default-index-but-facet">
    <failure message="assertEquals failed." type="failure-error-code-1">1</failure>
    <output>11</output>
</testcase>
```

Here is a standalone xqsuite with this function: [facets-trimmed.xql.zip](https://github.com/eXist-db/exist/files/4078659/facets-trimmed.xql.zip)

**Context (please always complete the following information):**
 - OS: macOS 10.15.2
 - eXist-db version: 5.2.0-SNAPSHOT develop (ad564d7)
 - Java Version: Zulu 8.42.0.23-CA-macosx (build 1.8.0_232-b18)

**Additional context**
- How is eXist-db installed? DMG
- Any custom changes in e.g. `conf.xml`? None

**Comment by joewiz** [comment]
My current workaround is to avoid the parentheses and instead to perform separate queries:

```xquery
(
    collection("/db/data")/tei:TEI[ft:query(., "title:china")],
    collection("/db/data")/dbk:article[ft:query(., "title:china")]
)
=> ft:facets(map {"facets": "year-published"})
```

@wolfgangmm Given that I've found a workaround, shall I close this, or would you like to keep it open as a bug report?

**Comment by wolfgangmm** [comment]
@joewiz I still think something is wrong with the merging of facets. I see wrong facet counts when I mix TEI and docbook - even when using two separate queries. So please keep the issue open.

**Comment by joewiz** [comment]
@wolfgangmm Ok, will do. Thank you!

**Comment by adamretter** [comment]
After a bit of debugging, I can report that this may not have anything specifically to do with the `ft:facets` function.

The problem occurs in the `LuceneIndexWorker$LuceneHitCollector#collect(int)` method during the execution of the XQuery function `ft:query`.

When `(div)` is used as the Context Sequence to `ft:query`, the `LuceneHitCollector` class has a `contextSet` variable that contains two nodes from the document `/db/lucenetest/multi-lang.xml`:
1. `<div><p>Es zwitschern<note>singen</note> die Vögel</p></div>`
2. `<div><p>And the birds are singing</p></div>`
This ultimately leads to an incorrect chain of `Match` objects being set on the `NodeProxy`.

Whereas when *just* `div` is used as the Context Sequence to `ft:query`, the `LuceneHitCollector` class has a `contextSet` variable that is empty, and so **no** incorrect Match objects are set on the `NodeProxy`.

I will report back further in due course. At the moment I am chasing through the logic to try and figure out why `(div)` causes a `contextSet` to be created, and `div` does not...

**Comment by adamretter** [comment]
I have discovered the first form of the query with just `div` gets rewritten by the `Optimizer`, whereas the second form of the query with `(div)` does not.

The query:
```xquery
doc("/db/lucenetest/multi-lang.xml")//div[ft:query(., "english:*", map { "leading-wildcard": "yes" })]
```
is rewritten by the `Optimizer` to:
```xquery
doc("/db/lucenetest/multi-lang.xml")(# exist:optimize null#) {
    //div[ft:query(., "english:*", map { "leading-wildcard": "yes" })]
}
```

Whereas the query:
```
doc("/db/lucenetest/multi-lang.xml")//div[ft:query(., "english:*", map { "leading-wildcard": "yes" })]
```
is **not** able to be rewritten to Optimize by eXist-db.

So two lines of investigation:
1. I am wondering if perhaps `LuceneIndexWorker$LuceneHitCollector#collect(int)` only correctly sets up the matches if the preceding expression was able to be rewritten to Optimize. If so that is a bug...
2. Why can't the second form of the query be rewritten to Optimize by eXist-db in the same manner as the first form of the query?
