### ISSUE TITLE
unparsed-text() for user guest seems to think it must read from the file system

### ISSUE THREAD

**Issue by xatapult** [eXist-db/exist#3220]
My XQuery script performs a call to `unparsed-text()` and asks for a file *in* the database that has world read permissions. E.g. 

```
unparsed-text('/db/apps/eXide/build.js')
```

What I get is: `err:FOUT1170 non-dba user not allowed to read from file system`

(Anyway, why is the error code something with FOUT, the Dutch word for error...)

**Expected behavior**
The unparsed text of the requested file 

**To Reproduce**
* run eXide as guest user. 
* Enter ` unparsed-text('/db/apps/eXide/build.js')`  as XQuery script
* Run it: error
* Login as amin
* Run it again: Ok

**Context (please always complete the following information):**
 - OS: WIndows 10
 - eXist-db version: 5.1.1 (latest version)
 - Java Version "1.8.0_241"

**Additional context**
- How is eXist-db installed? JAR installed
- Any custom changes in e.g. `conf.xml`? No

**Comment by joewiz** [comment]
I can confirm the report still affects 5.2.0-develop (current HEAD).

**Comment by adamretter** [comment]
@xatapult @joewiz hmm we seem to have a test case which covers this:

```xquery
declare
    %test:assertEquals("Hello&#10;world!&#xD;Hello&#xD;&#xA;world!")
function upt:unparsed-text-from-db() {
    unparsed-text("/db/test-unparsed-text/test.txt")
};
```
See https://github.com/eXist-db/exist/blob/develop/exist-core/src/test/xquery/unparsed-text.xql#L56

**Comment by joewiz** [comment]
@adamretter If the tests run as dba, they wouldn't encounter the bug.

**Comment by dariok** [comment]
It seems this one goes back a bit:

I tried reading a world-readable file from the DB using `unparsed-text()` on eXist 4.7.1 and I, too, get the `FOUT1170`.
Trying to open a URL (`http://exist.ulb.tu-darmstadt.de:8080/exist/restxq/edoc/collection/arndt/nav.xml`) using `unparsed-text()` without being logged in also throws `FOUT1170`. The same on 5.1.0

Don't know whether it's related: after logging in as admin, `unparsed-text()` on 4.7.1 throws `err:FOUT1170 Server returned HTTP response code: 500 for URL: http://exist.ulb.tu-darmstadt.de:8080/exist/restxq/edoc/collection/arndt/nav.xml`
(`doc()` says the same but returns code `FODC0005`)

The file is perfectly readable, though:
```
curl -v http://exist.ulb.tu-darmstadt.de:8080/exist/restxq/edoc/collection/arndt/nav.xml
*   Trying 130.83.152.153:8080...
* TCP_NODELAY set
* Connected to exist.ulb.tu-darmstadt.de (130.83.152.153) port 8080 (#0)
> GET /exist/restxq/edoc/collection/arndt/nav.xml HTTP/1.1
> Host: exist.ulb.tu-darmstadt.de:8080
> User-Agent: curl/7.65.3
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< Date: Mon, 27 Jan 2020 19:05:32 GMT
< Content-Type: application/xml; charset=UTF-8
< Vary: Accept-Encoding, User-Agent
< Transfer-Encoding: chunked
< Server: Jetty(9.4.14.v20181114)
< 
<struct xmlns="https://github.com/dariok/wdbplus/wdbmeta" label="Arndt">
    <view file="lese1" label="Vier Bücher von wahrem Christenthum. Buch 1. Deutscher Lesetext"/>
    <view file="de1" label="Vier Bücher von wahrem Christenthum. Buch 1, Kap. XXVII"/>
</struct>
```
