### ISSUE TITLE
get-remote-port() returns weird answer

### ISSUE THREAD

**Issue by xatapult** [eXist-db/exist#3242]
Calling `request:get-remote-port()` from a `http:localhost:8080/...` REST call returns a weird answer and **it changes** 😨 . I now get 56828, before that it was something like 56727 and now it's 56894...

No Apache or NGinx in between.

**Expected behavior**
`8080`

**To Reproduce**
Put this mini XQuery script somewhere and run it using something like `http://localhost:8080/exist/rest/...`. Try it a few times (refreshing the browser cache). I get different numbers on every call.

```Xquery
xquery version "3.1" encoding "UTF-8";
declare option exist:serialize "method=xml media-type=text/xml indent=yes";
<TEST>{  request:get-remote-port()  }</TEST>
```

**Context (please always complete the following information):**
 - OS: Windows 10
 - eXist-db version: 5.2.0
 - Java Version 1.8.0_202

**Additional context**
- How is eXist-db installed? JAR
- Any custom changes in e.g. `conf.xml`? No

**Comment by joewiz** [comment]
If you're expecting `8080` - the server port that eXist listens on by default - you should be using `request:get-server-port()`. The changing "remote port" when you use `request:get-remote-port()` is the *dynamic* or *ephemeral port* that your computer uses to send its request to eXist and that it listens for eXist's response on. This port number is typically assigned randomly and can change for each request. See https://unix.stackexchange.com/questions/65475/ephemeral-port-what-is-it-and-what-does-it-do. 

> ![Screen Shot 2020-02-05 at 9 32 08 AM](https://user-images.githubusercontent.com/59118/73850843-83fccb80-47fa-11ea-8785-bef2de785322.png)

**Comment by xatapult** [comment]
I was just typing I was mistaken. Thanks.
