### ISSUE TITLE
Max concurrent processes setting

### ISSUE THREAD

**Issue by nsincaglia** [eXist-db/exist#3252]
Currently, there is a setting which limits the same script from running concurrently via the Scheduler. 

This setting exists inside the exist core jar in the file `org/exist/scheduler/impl/quartz.properties` which is inconvenient to access. It was suggested that this setting could be moved into a file which is stored in the `$EXIST_HOME/etc` folder. This would make it easier to change this setting if one desired to do so.

**Comment by dizzzz** [comment]
Please could you point to this setting? I can't recall such one...
