### ISSUE TITLE
[BUG] Java memory settings for Windows service with eXist 5.x

### ISSUE THREAD

**Issue by vincentml** [eXist-db/exist#3253]
I have eXist 5.2.0 running as a service on Windows 2012 R2. Since upgrading to eXist 5.x I have observed that eXist would not use more than about 4 Gb of RAM regardless of the setting in the Launcher System Configuration panel for Max Memory or settings in /etc/launcher.properties. This might be a bug or at least an update that needs to be made in the System Configuration form. 

The expected behavior is that the Java Memory Min and Max limits that are configured in the Launcher System Configuration panel would be used for running eXist-db as a Windows service. Memory usage observed in Monex should reflect the configuration.

After reading through [Procrun documentation ](https://commons.apache.org/proper/commons-daemon/procrun.html) I finally found a solution/workaround:

1. Stop the eXist-db service
2. Run `regedit.exe`
3. Navigate to `HKEY_LOCAL_MACHINE\SOFTWARE\Wow6432Node\Apache Software Foundation\Procrun 2.0\eXist-db\Parameters\Java`
4. Next to the key JvmMs, right click and add a new DWORD key.
5. Give the new key a name `JvmMx`
6. Give the new key a decimal value that is a number of megabytes of memory to allow Java to utilize. For example, to set the memory limit to 12 Gb on a machine with 16 Gb total memory enter the value in Mb as 12288.
7. Start the eXist-db service

**Comment by adamretter** [comment]
Hmm that's interesting.

It looks like the min/max memory settings are written to `launcher.properties` by the Launcher Configuration dialog, but they are never used for anything.

I see that for Procrun's initial service installation, we can also set `--JvmMs` and `--JvmMx`. I need to check whether later modifying the settings you mention in the registry then overrides those.

Either way, the memory settings should be used, but they are not, so this is a bug!
