### ISSUE TITLE
Change order in file transformation?

### ISSUE THREAD

**Issue by karanda1990** [eXist-db/exist#3254]
Hi there, 
First of all: 
I am not sure, whether the title says what I need, but i cannot figure better words just now ... :-/

Please fill in the following sections:

### What is the problem
I have a collection of ~ 150 files(named like 00001.xml, 00010.xml, 00100.xml), which I transform into the elements of a bootstrap carousel. 

I transform them using below function and insert them into a `<div>` , where they are happily displayed, I can use my controls to go from one carousel-item to another. However, their order is not exactly what I need. 
I need 29 -> 30 -> 31-> 32 ->33 (you get it, right?)
I have 29 (currently the first file) -> 162 (last) ->161 ->160 ->30 -> 31 ->32->32 ->33-> 34 -> 140
It does not exactly seem random, but not ordered either :-D 

```
declare function app:XMLtoHTML ($node as node(), $model as map(*), $query as xs:string?){
let $ref := xs:string(request:get-parameter("document", ""))
let $xml := doc(concat("/db/apps/.../edition/",$ref))
let $xsl := doc("/db/apps/.../xslt/xmlToHtml.xsl")
let $params :=
<parameters>
   {for $p in request:get-parameter-names()
    let $val := request:get-parameter($p,())
    where  not($p = ("document","directory","stylesheet"))
    return
       <param name="{$p}"  value="{$val}"/>
   }
</parameters>
    for $doc in collection("/db/apps/.../edition/")
       return
            if (document-uri($doc) = '/db/.../edition/00029.xml')
            then
                <div class="carousel-item active"> {transform:transform($doc, $xsl, $params)} </div>
           else 
               <div class="carousel-item">{transform:transform($doc, $xsl, $params)}</div>
};
```

### What did you expect
I hoped for the carousel-items be displayed in order, as it was when I started working on this today at 9. unlucky me: I did not backup things -.- 

### Describe how to reproduce or add a test
It worked fine until I wanted to add my "production-xmls", so my best guess is that somehow I screwed exist up. Unfortunately I do not have a way to safely reproduce it...

### Context information
I am on Windows 10 (64 bit)
exist-db: 5.1.1
Java: 10.0.2 (Build 10.0.2 +19) amd64
I installed exist-db using the JAR installer.
I did not touch the conf.xml

**Comment by karanda1990** [comment]
Edit: 
Upon slowly refilling my DB: 
It works from 29 -> 39 but the fourties make trouble . 
I haven't checked further.

**Comment by adamretter** [comment]
Sounds like you want to add an `order by` clause.

```
for $doc in collection("/db/apps/.../edition/")
let $id := replace(document-uri($doc), ".*/([^.]*)\.xml", "$1") cast as xs:integer
order by $id
return
...
```

**Comment by karanda1990** [comment]
Thank you, once again! 

Any hints on why it is ordering "semi-ordered" as described above? or is this a random order, where only I perceive some regularity?

**Comment by adamretter** [comment]
@karanda1990 the default ordering is undefined by the XQuery spec. It is hard to guess why you get the ordering that you do, it could be related to the order in which the documents were stored/modified or some other hash based retrieval.
