### ISSUE TITLE
Having trouble downloading from JFrog

### ISSUE THREAD

**Issue by crumleyc** [eXist-db/exist#3273]
I am following the basic install instructions and I am not getting the same results. I am Using a Mac Desktop running Catalina and Java 13. When I download the .jar file as suggested in the documentation, I do get prompted to make an admin password but not application is installed. Just a directory of stuff is downloaded. When I download the .dmg file, the application is downloaded but I cant make an admin password and the dashboard is only has XQuery and some other icons for documentation. I must be doing something wrong, but I dont understand why this install isn't following the documentation on y'alls website. 
The Documentation I am following: http://exist-db.org/exist/apps/doc/basic-installationhttp://exist-db.org/exist/apps/doc/basic-installation I will say that when installing packages, the "source" as illustrated in the picture is not present for me when I get to that screen. 
The place I am downloading: https://bintray.com/existdb/releases/exist/5.2.0/view

**Comment by adamretter** [comment]
@crumleyc I note that you have said you are using Java 13. From the page that you referenced, it tells you there that you need Java 8.  -- Although actually that page seems outdated, we test with 8, 9, 10, and 11. So anything up to Java 11 should be fine.

**Comment by adamretter** [comment]
I will close this for now. The exist-open mailing list is a better place to ask questions.

**Comment by crumleyc** [comment]
Thank you!!

**Comment by adamretter** [comment]
@crumleyc No worries, if you still have problems feel free to re-open or ask on exist-open.
