### ISSUE TITLE
[BUG] eXist 5.2.0 (using Jetty 9.4.26) doesn't handle SNI certs

### ISSUE THREAD

**Issue by phattire** [eXist-db/exist#3277]
We use an SNI cert with a number of hostnames as well as a wildcard hostname.

When upgrading from eXist 5.1.0 to 5.2.0 (due to the newer Jetty), we receive an error on startup "KeyStores with multiple certificates are not supported on the base class".

Here is a discussion on the Jetty SslContextFactory:  https://github.com/eclipse/jetty.project/issues/4425

OS: Linux

**Comment by adamretter** [comment]
@phattire the advice in that thread is to change `new Server();` to `new SslContextFactory.Server();`.

However, we are already using `SslContextFactory.Server()`, see: https://github.com/eXist-db/exist/blob/develop/exist-jetty-config/src/main/resources/org/exist/jetty/etc/jetty-ssl-context.xml#L13

**Comment by adamretter** [comment]
@phattire If you want this issue resolved, we are going to need input from you...

Can you at least tell us how to reproduce the issue step by step? I am not even sure how to create and/or configure an SNI certificate at the moment

**Comment by adamretter** [comment]
Closing due to a lack of response. Please feel free to re-open.
