### ISSUE TITLE
My collection browser is gone

### ISSUE THREAD

**Issue by karanda1990** [eXist-db/exist#3284]
As I am building an Index of my App I wanted to reindex the collection, however it seems as if my collection browser has vanished in thin air? 

![grafik](https://user-images.githubusercontent.com/58807751/76227395-8bf7c300-621f-11ea-9139-7ed55f631268.png)

**Comment by adamretter** [comment]
The Collection Browser was removed in eXist-db 5.0.0 as it was unmaintained and buggy. There is a similar functionality in eXide or the Java Admin Client.

**Comment by karanda1990** [comment]
Do you mind pointing out where, since I haven't been able to find reindexing yet ... :-o

**Comment by adamretter** [comment]
I am not sure that there is a `reindexing` function, just a collection browser in eXide. There are XQuery commands to initiate a reindex though - `xmldb:reindex`

**Comment by karanda1990** [comment]
I didn't find a reindex function either in Exide. used the admin client. I do not have to do this that often :-D 
(I'll someday probably automate it) 

I have a new problem which I kind of link to my indexing stuff. 
Can I by chance just "ignore" non-xml files in a collection? 
I tried "?select='*xml'" following my path to the collection, but this breaks my transformation (posted on stackoverflow, since this is not an exist-db problem but a coding problem :-/

**Comment by joewiz** [comment]
@karanda1990 Please join the [exist-open mailing list](https://lists.sourceforge.net/lists/listinfo/exist-open) or [Slack](https://join.slack.com/t/exist-db/shared_invite/enQtNjQ4MzUyNTE4MDY3LWNkYjZjMmZkNWQ5MDBjODQ3OTljNjMyODkwNmY1MzQwNjUwZjMzZTY1MGJkMjY5NDFhOWZjMDZiMDdhMzY4NGY) for general questions. This issue tracker is for reporting bugs. Thanks, and welcome!
