### ISSUE TITLE
Startup splash screen in the way

### ISSUE THREAD

**Issue by xatapult** [eXist-db/exist#3301]
When I start eXist (5.2) on W10, it displays a splash window with some messages.

However, when your database has crashed it needs to recover and re-index stuff and *all the time* this window stays *on top* of all other windows. This makes working effectively impossible (on a PC with a single screen) because the middle of your screen is covered with the eXist splash.

Maybe you can make this splash screen non-global so it can disappear behind an active window? Or make it draggable/minimizable?

**Comment by adamretter** [comment]
@xatapult I think I have a fix for you - https://github.com/eXist-db/exist/pull/3315

Could you test it please?
