### ISSUE TITLE
[BUG] Upload a large file (>512kb) by code java 

### ISSUE THREAD

**Issue by darkmagician1711** [eXist-db/exist#3312]
> To be able to better understand you problem, please add as much information as possible to this ticket. Always test your bugs against the latest stable release of exist. We cannot provide support for older versions here on GitHub. If the version of eXist that is experiencing the issue is more than 1 major version behind the most recent release, please consider posting a question on our mailing list. 

**Describe the bug**
When I try to storeResource a large file (> 512kb) by code Java, it will get an error like the image below. I tried uploading a file < 512kb, it's ok.

**Expected behavior**
Am i missing something ?? 

**To Reproduce**
```Java
try {
  File file = new File(pathFileConfig + "\\" + neId + ".xml");
  if (!file.exist()) {
    Logger.info("File not found!!!");
    return;
  }
  resource.setContent(file);
  collection.storeResource(resource); <<<<====== error 
} catch (XMLDBException e) {
  e.printStackTrace();
} finally {
  if (resource!=null) {
    try {
      ((ExistResource) resource).freeResources();
    } catch (XMLDBException e) {
       e.printStackTrace();
    }
  }
}
```

**Screenshots**
exception here
![image](https://user-images.githubusercontent.com/33110709/77028544-9fe3b780-69cb-11ea-9eca-10f889e3c154.png)

![image](https://user-images.githubusercontent.com/33110709/77027177-0ff03e80-69c8-11ea-8960-e7460f9c955e.png)

**Context :**
 - OS: win10 build 18362
 - eXist-db version: 5.1.1
 - Java Version Java8u231

**Additional context**
- Any custom changes in e.g. `conf.xml`? None

**Comment by adamretter** [comment]
You have some dependencies missing in your project! I am not sure how your client project is setup but it is missing a dependency on Apache Commons IO.

We have a test here which passes for uploading larger files - https://github.com/eXist-db/exist/blob/eXist-5.2.0/exist-core/src/test/java/org/exist/xmldb/RemoteCollectionTest.java#L228
