### ISSUE TITLE
[BUG] "Unknown type: xs:numeric" error

### ISSUE THREAD

**Issue by joewiz** [eXist-db/exist#3323]
**Describe the bug**

In eXist 5.3.0-SNAPSHOT (develop HEAD), certain expressions related to the `xs:numeric` type produce the error:

> exerr:ERROR Unknown type: xs:numeric

**Expected behavior**

This type should be known to eXist.

**To Reproduce**

The following code produces the error:

```xquery
1 cast as xs:numeric
```

Here is a corresponding XQSuite test:

```xquery
xquery version "3.1";

module namespace it = "http://exist-db.org/xquery/test/integer-tests";

declare namespace test = "http://exist-db.org/xquery/xqsuite";

declare
    %test:args("1")
    %test:assertEquals(1)
function it:string-cast-as-numeric($string as xs:integer) as xs:numeric {
    $string cast as xs:numeric
};
```

Running this test in eXist 5.2.0 succeeds; the expression `1 cast as xs:numeric` also returns the expected `xs:numeric(1)` in BaseX and Saxon. But in eXist 5.3.0-SNAPSHOT, this test returns:

```xml
<testsuites>
    <testsuite package="http://exist-db.org/xquery/test/integer-tests"
        timestamp="2020-03-25T23:42:28.916-04:00" tests="1" failures="0"
        errors="1" pending="0" time="PT0.229S">
        <testcase name="string-cast-as-numeric"
            class="it:string-cast-as-numeric">
            <error type="java:org.exist.xquery.XPathException"
                message="exerr:ERROR Unknown type: xs:numeric [at line 10, column 35]..."/>
        </testcase>
    </testsuite>
</testsuites>
```

As discussed with @adamretter in Slack, there may be some relation between this issue and https://github.com/eXist-db/exist/pull/3266.

The problem was first observed when running the tests included as part of the documentation app's build script, tests which effectively weren't running between Feb 4 and Mar 23. To reproduce the error, clone and build the documentation app using these steps:

```bash
git clone https://github.com/eXist-db/documentation.git
cd documentation
mvn clean package
```

During the maven operation, the error is raised. Here's the portion of the console output from that build process where the error appears:

```text
[INFO]   running XQsuite test …
[INFO]         3 xqsuite tests:
[INFO]           [ 'section-headings',
[INFO]             'exerr:ERROR Unknown type: xs:numeric [at line 53, column 27, source: /db/apps/doc/modules/config.xqm]\nIn function:\n\ttests:missing-id() [18:1:/db/apps/doc/modules/test-suite.xql]\n\ttest:apply(function(*), item()*) [560:9:jar:file:/exist/lib/exist.uber.jar!/org/exist/xquery/lib/xqsuite/xqsuite.xql]\n\ttest:apply(function(*), element(), item()*) [467:9:jar:file:/exist/lib/exist.uber.jar!/org/exist/xquery/lib/xqsuite/xqsuite.xql]\n\ttest:call-test(function(*), element(), element()*) [279:32:jar:file:/exist/lib/exist.uber.jar!/org/exist/xquery/lib/xqsuite/xqsuite.xql]. Unknown type: xs:numeric' ]
[INFO] npm ERR! Test failed.  See above for more details.
```

Strangely, in the relevant code—`doc/modules/config.xqm`, `doc/modules/test-suite.xql`, and eXist's `xqsuite.xql` module—there is no direct invocation of the `xs:numeric` type.

**Context (please always complete the following information):**
 - OS: macOS 10.13.6
 - eXist-db version: 5.3.0-SNAPSHOT (develop 5d59f738b1e180c035a5605c02e2bdcb1cf6dfe5)
 - Java Version: OpenJDK Runtime Environment (Zulu 8.44.0.11-CA-macosx) (build 1.8.0_242-b20)

**Additional context**
- How is eXist-db installed?
    ```bash
    docker pull existdb/existdb:latest
    docker run -dit -p 8080:8080 --name docs --rm existdb/existdb:latest
    ```
- Any custom changes in e.g. `conf.xml`? No

**Comment by duncdrum** [comment]
Maven shouldn t matter here. The test suite ships as part of the app: `apps/docs/modules/test-runner.xql` You can simply execute the xquery in exide, IDE, …
