### ISSUE TITLE
Update to Java language level 11

### ISSUE THREAD

**Issue by adamretter** [eXist-db/exist#3362]

**Comment by dizzzz** [comment]
+1 from me, as the v11 is a LTS versions; I expect this version should be rather common after 2 years of the release. And stable. And the new GC is awesome.

**Comment by duncdrum** [comment]
If we are moving to java11 without implementing J11 language features (especially java-module) i m not in favour. J11 is a lot heavier then J8 when used without modules, there are also some components dependencies which have been removed from J11 we need to address.

Moving our docker images to j11 is work. There is a suitable distroless base image, but the `JAVA_TOOL_OPTIONS` will require rewriting and testing. Probably more parts of the docker file will need tweaking.

**Comment by adamretter** [comment]
@duncdrum I would like to understand the thinking/background behind your objections in a bit more detail...

> without implementing J11 language features (especially java-module) i m not in favour

What feature is it that you need from `java-module` that we don't currently have?

> J11 is a lot heavier then J8 when used without modules

How so?

> there are also some components dependencies which have been removed from J11 we need to address.

Hmm... I think that work was already one, otherwise eXist-db would not run on Java 11. No?

**Comment by duncdrum** [comment]
If we do not use java modules the full jvm is over 2.5 times the size of j8. Modules remove unused components to bring this back in line. Especially for docker (but also for shipping a win build with jdk) we add a lot of waste without any benefit. The feature is that we don t use java modules (they were introduced in j9 I think). 

I don t think our test coverage is high enough to be sure. The components I found when looking into upgrading, dealt with file system fonts, image binaries etc. the corresponding exist extensions are usually not well tested if at all. This might also effect apps like exide. Lastly, our integration tests use java8 so they might hide the fact, that a green result from building exist on j11, is not acting as expected when run on j11.

**Comment by dizzzz** [comment]
"If we do not use java modules the full jvm is over 2.5 times the size of j8." ... woops; any details/documentation on such things?

**Comment by adamretter** [comment]
```
$ cd /Library/Java/JavaVirtualMachines
$ find . -type d -d 1 -exec du -sh {} \;
155M	./zulu7.34.0.5-ca-jdk7.0.242-macosx_x64
230M	./adoptOpenJdk-8u232-b09-J9
371M	./jdk1.8.0_221.jdk
203M	./zulu8.40.0.25-ca-jdk8.0.222-macosx_x64
301M	./zulu9.0.7.1-jdk9.0.7-macosx_x64
303M	./zulu11.37.17-ca-jdk11.0.6-macosx_x64
302M	./liberica-jdk-11.0.6.jdk
321M	./zulu13.28.11-ca-jdk13.0.1-macosx_x64
```

@duncdrum the smallest JDK8 I have is OpenJDK with J9 at 230MB, the smallest JDK 11 I have is 302MB. However the JDK11 I have includes 57MB of source code (src.zip). After removing that there isn't much difference at least on my machine.

Also it just occurred to me that maybe I should be comparing JRE's as that is all that is needed for runtime (e.g. in the Docker Image) rather than JDK's:
* JRE from adoptOpenJdk-8u232-b09-J9: 134MB
* JRE from liberica-jdk-11.0.6.jdk: 124MB

So it seems that even ignoring modules, the full JRE11 is actually smaller than the JRE8.

Am I missing something?

**Comment by adamretter** [comment]
> That being said, j11 brings many container goodies I would want. So I’m in favor of j11, just not j11 with j8 features only.

If the size thing is now not an issue - Then I don't see a concrete use-case for adopting modules (just yet).

My fear is that adopting modules is a huge amount of work, and not one that I personally have the time to invest in without a concrete use-case. That being said, if others want to do the modularisation work then they are very welcome to do so :-)

**Comment by duncdrum** [comment]
I consistently get ~90MB with J8 and 250MB with J11, those were the same numbers that @reinhapa saw when he checked on one of the community calls if we could add J11 to chocolatey. I haven't looked in detail into what parts of the package are responsible for the size increase or compared them.

**Comment by adamretter** [comment]
> I consistently get ~90MB with J8 and 250MB with J11,

Interesting... where are your getting your JRE's?

**Comment by duncdrum** [comment]
i used Zulu, I assume patrick used adoptOpen, not sure what the default is for distroless.

**Comment by duncdrum** [comment]
> My fear is that adopting modules is a huge amount of work, and not one that I personally have the time to invest in without a concrete use-case. That being said, if others want to do the modularisation work then they are very welcome to do so :-)

Similarly, my fear is that switching docker to j11 base images is quite a bit of work, and without any  benefits or use-case, since we tweaked J8 to get as many container enhancements as it can get. If someone wants to put the work in go ahead, but without modules the size thing is going to bite.

**Comment by craigberry** [comment]
I'm not a Java person, and this seems really strange to me, but supposedly Java 8 will be supported through May 2026, two years longer than Java 11, and much longer than anything else in the Java 9 through 14 range:

[https://adoptopenjdk.net/support.html](https://adoptopenjdk.net/support.html)

**Comment by reinhapa** [comment]
@craigberry you can not compare Java 8 and 11 with the others as 8 & 11 are LTS releases. The big change is going beyond Java 8 though. After that the needed work to do should be less of a pain. I think one of the reasons being that all those having made it to past 8 will go from LTS to next LTS or even take the fast train of all releases in between ..

**Comment by eduarddrenth** [comment]
Java 11 please! We're building/running almost everything on Java 11 now, the world is slowly but surely leaving 8 behind

**Comment by reinhapa** [comment]
I would consider working towards Java 11 language level wise and preparing the source code for Java 17, without module in focus for now. When having Java 11 there are multiple Tools to see what Java 11+ modules would require. Here we nee to take the platform where exist is running on into account too. It does make no sense to have Java module support on a platform that does not support it.

**Comment by duncdrum** [comment]
@eduarddrenth you might want t give these a spin. A message to mailing list will follow shortly. As well as more documentation about changes other changes. 

https://hub.docker.com/r/duncdrum/existdb/tags

**Comment by eduarddrenth** [comment]
On this line in my Dockerfile, based on duncdrum/existdb:6.0.0:
```
RUN --mount=type=bind,source=data,target=/data --mount=type=secret,id=adminpw,required,target=/tmp/adminpw [ "java", "org.exist.start.Main", "client", "--no-gui",  "-l", "-u", "admin", "-P", "", "-F", "/tmp/adminpw" ]
```
I get
```
Caused by: java.lang.ClassNotFoundException: org.exist.start.Main
```
perhaps relates to:
```
ENV CLASSPATH=$EXIST_HOME/lib/exist.uber.jar:$EXIST_HOME/lib/exist-db-addons-${EXISTADDONSVERSION}.jar
```

**Comment by duncdrum** [comment]
> On this line in my Dockerfile, based on duncdrum/existdb:6.0.0:
> 
> ```
> RUN --mount=type=bind,source=data,target=/data --mount=type=secret,id=adminpw,required,target=/tmp/adminpw [ "java", "org.exist.start.Main", "client", "--no-gui",  "-l", "-u", "admin", "-P", "", "-F", "/tmp/adminpw" ]
> ```
> 
> I get
> 
> ```
> Caused by: java.lang.ClassNotFoundException: org.exist.start.Main
> ```
> 
> perhaps relates to:
> 
> ```
> ENV CLASSPATH=$EXIST_HOME/lib/exist.uber.jar:$EXIST_HOME/lib/exist-db-addons-${EXISTADDONSVERSION}.jar
> ```

@eduarddrenth thank you for testing the images, lets move the discussion into their repo to i can keep better track. while wrapping up the final tweaks and writing the docs. 

The `uber.jar` is no more in these images, its a simple wild card classpath selector, so dropping any `.jar` in `exist/lib` will put it on the classpath at jvm boot.

**Comment by adamretter** [comment]
eXist-db 7.0.0 is at Java Language Level 17
Closed by https://github.com/eXist-db/exist/pull/4574
