### ISSUE TITLE
[BUG] util:registered-functions returns QNames with null namespace prefixes

### ISSUE THREAD

**Issue by joewiz** [eXist-db/exist#3424]
**Describe the bug**

For a small number of eXist extension functions, `util:registered-functions` returns results with a null namespace prefix. 

This causes incorrect the namespace prefix for affected functions to be omitted in eXist's function documentation, and prevents IDEs such as oXygen from accessing the affected functions when users request function autocompletion/documentation based on a function's prefix. (See screenshots below.)

Affected functions:

- `http://exist-db.org/xquery/xmldb`
  - copy-collection
  - copy-resource
- `http://exist-db.org/xquery/inspection`
  - inspect-function
  - inspect-module
  - inspect-module-uri
- `http://exist-db.org/xquery/system`
  - restore
- `http://exist-db.org/xquery/sql`
  - execute
- `http://exist-db.org/xquery/util`
  - absolute-resource-id
  - binary-doc
  - binary-doc-available
  - binary-doc-content-digest
  - document-id
  - document-name
  - eval
  - eval-and-serialize
  - eval-inline
  - eval-with-context
  - get-resource-by-absolute-id
  - is-binary-doc
  - qname-index-lookup
- `http://exist-db.org/xquery/compression`
  - deflate
  - gzip
  - inflate
  - tar
  - ungzip
  - zip

**Expected behavior**

Every function returned by `util:registered-functions` should have the namespace prefix of its parent module—and should never return a null namespace prefix.

**To Reproduce**

The query below lists which functions are affected.

```xquery
xquery version "3.1";

for $namespace-uri in util:registered-modules()
let $functions := try { util:registered-functions($namespace-uri) } catch * { <error>{$err:code} raised when getting registered functions for module {$namespace-uri}</error> }
return
    if ($functions instance of element(error)) then
        ()
    else
        let $prefix-analysis := 
            for $function in $functions
            group by $prefix := fn:prefix-from-QName($function)
            return
                map { 
                    "prefix": $prefix,
                    "functions": 
                        array { $function ! fn:local-name-from-QName(.) }
                }
        where count($prefix-analysis) gt 1
        order by $namespace-uri
        return
            map { 
                "module": $namespace-uri,
                "prefix-analysis": array { $prefix-analysis }
            }
```

Note, too, that running `inspect:inspect-functions` on the same modules returns results with a similar discrepancy - `base64-encode` has a prefix, whereas `binary-doc` lacks one:

```xml
<function name="util:base64-encode" module="http://exist-db.org/xquery/util"/>
<function name="binary-doc" module="http://exist-db.org/xquery/util"/>
```

**Screenshots**

oXygen's function documentation omits util:binary-doc:

> ![Screenshot 2020-05-14 at 08 57 22](https://user-images.githubusercontent.com/59118/82607390-aedf1580-9b86-11ea-8f1e-9c3ecbbfbaf0.png)

eXist's function documentation omits the prefix for util:binary-doc:

> ![Screen Shot 2020-05-14 at 11 30 30 AM](https://user-images.githubusercontent.com/59118/82607430-c1f1e580-9b86-11ea-9127-615d46a7e684.png)

**Context (please always complete the following information):**
 - OS: macOS 10.13.6
 - eXist-db version: 5.2.0, 5.3.0-SNAPSHOT
 - Java Version: 1.8.0_242 (Zulu 8.44.0.11-CA-macosx) (build 1.8.0_242-b20)

**Additional context**
- How is eXist-db installed? DMG, source
- Any custom changes in e.g. `conf.xml`? no

**Comment by dizzzz** [comment]
It looks like that all the 'wrong' functions use the same 'new' function definitions:  

<img width="788" alt="image" src="https://user-images.githubusercontent.com/1700062/82675191-bfee5c00-9c44-11ea-9bcf-f1ed0bc07077.png">

**Comment by dizzzz** [comment]
I found the issue... fix on its way

**Comment by dizzzz** [comment]
this sequence shall be empty:

```xquery
for $namespace-uri in util:registered-modules()
let $functions := try { util:registered-functions($namespace-uri) } catch * { <error>{$err:code} raised when getting registered functions for module {$namespace-uri}</error> }
for $fie in $functions
return
	if( contains($fie,":") or contains($namespace-uri, "w3.org") )
	then   () else $fie || " in " || $namespace-uri 
```

**Comment by joewiz** [comment]
@dizzzz Your test query is exactly right. Thank you!
