### ISSUE TITLE
[BUG] util:registered-functions throws XPathException with certain modules

### ISSUE THREAD

**Issue by joewiz** [eXist-db/exist#3425]
**Describe the bug**

For 3 eXist extension modules, `util:registered-functions` throws an XPathException error.

Example error:

> No module found matching namespace URI: `http://exist-db.org/xquery/memsort`

Affected modules:

- `http://exist-db.org/xquery/console `
- `http://exist-db.org/xquery/memsort `
- `http://expath.org/ns/crypto `

**Expected behavior**

This function should not raise an error when provided with a valid extension module namespace URI.

**To Reproduce**

The following query shows which modules produce the error.

```xquery
xquery version "3.1";

for $namespace-uri in util:registered-modules()
return
    try { 
        let $functions := util:registered-functions($namespace-uri) 
        return
            ()
    } catch * { 
        <error>{$err:code} raised when getting registered functions for module {$namespace-uri}</error>
    }
```

**Context (please always complete the following information):**
 - OS: macOS 10.13.6
 - eXist-db version: 5.2.0, 5.3.0-SNAPSHOT
 - Java Version: 1.8.0_242 (Zulu 8.44.0.11-CA-macosx) (build 1.8.0_242-b20)

**Additional context**
- How is eXist-db installed? DMG, source
- Any custom changes in e.g. `conf.xml`? no

**Comment by dizzzz** [comment]
First thoughts:
- class files loaded via modules are not found with `registered-functions` call
