### ISSUE TITLE
[BUG] I/O error crashes database completely (NFS storage)

### ISSUE THREAD

**Issue by karkraeg** [eXist-db/exist#3437]
## Description

We are running eXist DB on a Virtual Server with 64 GB RAM to handle XSLT Transformations with some additional Xquery on large numbers of individual XML files (up to 500.000 files transformed with a schematron validation, Xquery over all files to gather statistics). The Servers storage is mounted via NFS (via fstab). eXist works installed on this folder, but we encountered multiple crashes of the database, sometimes rendering our system completely useless (wouldn't start even after days of restoring) while in the exist.log we see lines like these:

```
2020-05-06 11:32:05,103 [qtp885339784-17496] WARN  (Paged.java [read]:957) - error while reading page: page: 1146; file = dom.dbx; address = 47b000; page header = 64; data start = 47b040 
java.io.IOException: Input/output error
2020-05-06 11:32:05,109 [qtp885339784-17496] ERROR (DOMFile.java [load]:3205) - java.io.IOException: Input/output error 
2020-05-06 11:32:05,235 [qtp885339784-17496] WARN  (TransactionManager.java [close]:409) - Transaction was not committed or aborted, auto aborting! 
2020-05-06 11:32:05,245 [qtp885339784-17496] ERROR (EXistServlet.java [doGet]:286) - null 
2020-05-06 11:32:21,951 [qtp885339784-17497] WARN  (Paged.java [read]:957) - error while reading page: page: 1353; file = dom.dbx; address = 54a000; page header = 64; data start = 54a040 
java.io.IOException: Input/output error
2020-05-06 11:32:21,953 [qtp885339784-17497] ERROR (DOMFile.java [load]:3205) - java.io.IOException: Input/output error 
2020-05-06 11:32:21,968 [qtp885339784-17497] WARN  (TransactionManager.java [close]:409) - Transaction was not committed or aborted, auto aborting! 
2020-05-06 11:32:21,977 [qtp885339784-17497] ERROR (EXistServlet.java [doGet]:286) - null
```

In 2 of four times our hosting provider had very short outages of the NFS File System, but in the other two instances they did not report anything. Am I correct in assuming that the I/O Error causes the database to crash completely? Is it therefor not safe to use storage mounted via NFS to install eXist on? We do have the option to mount the storage via an S3 / Ceph object storage, is this an option to be considered?

We can't have our system crash with the slightest unavailability of the storage so I need to be clear about which way eXist needs storage to be mounted - thanks!

## Context

 - OS: Ubuntu 18.04
 - eXist-db version: 5.2.0
 - Java Version:
openjdk 11.0.7 2020-04-14
OpenJDK Runtime Environment (build 11.0.7+10-post-Ubuntu-2ubuntu218.04)
OpenJDK 64-Bit Server VM (build 11.0.7+10-post-Ubuntu-2ubuntu218.04, mixed mode, sharing)

**Additional context**
- How is eXist-db installed? JAR installer headless
- Custom changes in e.g. `conf.xml`:

```
   <db-connection cacheSize="2048M"
                  checkMaxCacheSize="true"
                  collectionCache="1024M"
                  database="native"
                  pageSize="4096"
                  nodesBuffer="1000"
                  cacheShrinkThreshold="10000"
                  minDiskSpace="1024M"
                  posix-chown-restricted="true"
                  preserve-on-copy="false"
                  files="/home/storage/exist_5/data">
```

**Comment by dizzzz** [comment]
which NFS version?  AFAIK *java* requires NFS4+, but better is to use ISCSI

**Comment by dizzzz** [comment]
it has been a long time that I faces similar issues (few years), finding references is hard.

this is one: https://www.ibm.com/support/pages/network-file-system-nfs-recommendations-websphere-application-server-avoid-data-loss

**Comment by karkraeg** [comment]
`nfsstat -m` outputs `vers=4.2`, but the Hosting provider mentioned in a Mail to me that our NFS (version 3) can only use UIDs and GIDs instead of Usermapping. So he thinks its Version 3 I guess

**Comment by adamretter** [comment]
> Am I correct in assuming that the I/O Error causes the database to crash completely?

It is almost impossible to say without knowing the complete story of what was happening when that error occurred.

Both of the errors that you showed (`DOMFile#load` and `Paged#read`) are read operations. If they occurred due to a disk becoming unavailable and you were able to cleanly shutdown the database. Then you would not have a corrupt database.

However, you might also see those on re-starting a database if the database files are corrupt.

In general running a database on any non-locally attached disk adds a lot of risk. Any time the connection becomes unreliable you will potentially risk a database corruption.

My advice would be to store the database on locally attached disk.

S3 or Ceph Object Store won't help as they both have an Object based API. You might find that CephFS is more or less reliable than NFS, but ultimately you still have the network risks.

They are certainly tuning options for NFS v4 that can reduce the risk when using NFS with databases, but you can't eliminate the network issues.

**Comment by karkraeg** [comment]
Thanks for your answers and insights. I think we ran into I/O Errors both while restoring and running (we had log entries like this: `2020-04-24 17:53:55,019 [db.exist.scheduler.quartz-worker-3] ERROR (BTree.java [sync]:1022) - IO error while writing page: 7104415 
java.io.IOException: Input/output error` and we'll look into different storage solutions now.

**Comment by karkraeg** [comment]
Hi @adamretter sorry to aks again: Is it possible to run eXist on S3 storage?

**Comment by adamretter** [comment]
@karkraeg eXist-db does not support S3 at this time.
