### ISSUE TITLE
[BUG] string-join doesn't honour order

### ISSUE THREAD

**Issue by lguariento** [eXist-db/exist#3445]
The string-join function does not honour the order of the nodes passed to it. It always returns the nodes in the order they appear in the document.

This code in eXide:

```xquery
let $index := 
<root>
    <forename>Thomas</forename>
    <surname>Pennant</surname>
</root>

let $person := string-join($index/(surname | forename), ' ')

return $person
```

Will always return 'Thomas Pennant', even though `(surname | forename) ` above might make one think that it should return Pennant Thomas.

eXist-db 5.2
openjdk 13.0.2 2020-01-14
centOS 7

**Comment by dizzzz** [comment]
please could you (try to) strip down the query a bit? e.g. is the predicate `[@xml:id eq '1']` important or not?

**Comment by lguariento** [comment]
I've updated my post. I wouldn't know how to strip it down further!

**Comment by dizzzz** [comment]
For xquery related questions I'd recommend to check with Saxon first; here also `Thomas Pennan` is returned, so we need to study the meaning of `|` first;

**Comment by joewiz** [comment]
In `(surname | forename)`, the `|` is an OR operator. Thus, the expression will always return matching results—all surname OR forename elements—in *document order*. If you want to select nodes in a particular order, use `,` instead—constructing a new sequence:

```
xquery version "3.1";

let $index := 
<root>
    <forename>Thomas</forename>
    <surname>Pennant</surname>
</root>

let $person := string-join($index/(surname, forename), ' ')

return $person
```

**Comment by lguariento** [comment]
This is not a bug then, closing.
