### ISSUE TITLE
[BUG] Calling sm:id from inside a test causes an NPE

### ISSUE THREAD

**Issue by EfraimFeinstein** [eXist-db/exist#3468]
**Describe the bug**

Using eXist 5.2.0, if sm:id is called from a test (from eXide, say), an NPE is returned. Calling from outside a test gives the correct result.

**Expected behavior**

The expected behavior of sm:id() would be a return of the real and/or effective user.

**To Reproduce**

```xquery
xquery version "3.1";

module namespace t="http://exist-db.org/xquery/test";

import module namespace test="http://exist-db.org/xquery/xqsuite" at "resource:org/exist/xquery/lib/xqsuite/xqsuite.xql";

declare
  %test:name("cause an NPE")
  %test:assertEmpty
  function t:test-sm-id() {
  let $id := sm:id()
  return ()
};
```

**Context (please always complete the following information):**
 - OS: Ubuntu 20.04
 - eXist-db version: 5.2.0
 - Java Version Java 1.8.0_252 (or Java 11.0.7 )

**Additional context**
- How is eXist-db installed? eXist installed via jar installer, running inside a docker container
- Any custom changes in e.g. `conf.xml`? No

**Comment by StephanMa** [comment]
Had the same experience using `sm:id` in our project

**Comment by joewiz** [comment]
I can confirm the supplied test triggers an NPE. The testsuite returns:

```xml
<testcase name="cause an NPE" class="t:test-sm-id">
    <error type="java:java.lang.NullPointerException" message=""/>
</testcase>
```

The testsuite swallows the NPE, so there's no trace in exist.log.

**Comment by dizzzz** [comment]
I am wondering.... I can't find the proof of a NPE ?

**Comment by joewiz** [comment]
@dizzzz I'm sorry, you're right, I do not getting the issue in eXist 5.3.0-SNAPSHOT either. I must've been trying in 4.7.1 (where the error does happen) and forgot to switch back to 5.3.0, so I mislabeled this as a 5.3.0 issue. I've switched the milestone to 4.7.2. Not that the branch is being developed, but it should be clearer now. Thanks!

**Comment by dizzzz** [comment]
I'd suggest to close this issue, as we will not back port code to 4.x ...
