### ISSUE TITLE
[BUG] XQuery replace of child element of parent element with some attribute corrupts document

### ISSUE THREAD

**Issue by ssire** [eXist-db/exist#3475]
**Describe the bug**

Replacing an element of a document using the xquery update replace operation can cause a `java.lang.NullPointerException` and corrupt the document. This happens when the parent of the replaced element has an attribute and when the child is a unique child.

**Expected behavior**

The xquery update operation should complete normally.

**To Reproduce**

Save this script as tnr_update.xqm in the database then run it with XQuery > Run as a test in eXide 

```xquery
xquery version "3.1";

module namespace t="http://exist-db.org/xquery/test";

declare namespace test="http://exist-db.org/xquery/xqsuite";

declare variable $t:XML := document {
<Test><Content Foo="bar"><A/></Content></Test>
};

declare
    %test:setUp
function t:setup() {
    let $testCol := xmldb:create-collection("/db", "test")
    return
        xmldb:store("/db/test", "test.xml", $t:XML)
};

declare
    %test:tearDown
function t:tearDown() {
    xmldb:remove("/db/test")
};

declare
    %test:assertXPath("deep-equal($result, <Test><Content Foo='bar'><AA/></Content></Test>)")
function t:test() {
    let $content := doc('/db/test/test.xml')/Test/Content
    let $legacy := $content/A
    return
      update replace $legacy with <AA/>,
    doc('/db/test/test.xml')/Test 
};
```

this gives : 

```xml
<testsuites>
    <testsuite package="http://exist-db.org/xquery/test" timestamp="2020-07-07T17:29:54.894+02:00" tests="1" failures="0" errors="1" pending="0" time="PT0.003S">
        <testcase name="test" class="t:test">
            <error type="java:java.lang.NullPointerException" message=""/>
        </testcase>
    </testsuite>
</testsuites>
```

the terminal console shows :

```
Page 1332: 0/0[element (1) children: 1 attributes: 0] 16/1[element (1.1) children: 2 attributes: 1] 33/2[[attribute (1.1.1):'bar'] ] ; records in page: 3 (header says: 3); currentTupleID: 3; data length: 47 (last non-zero byte: 64)
```

if you look at the temporary file after the exception you will see that <Content> has lots its content :

```xml
<Test>
    <Content Foo="bar"/>
</Test>
```

the file can still be read but it is not possible to delete it with Java admin client, and to update anymore the parent node.

Note that you can run the script above without the exception if :

* you remove Foo="bar" (both in the $t:XML sample doc and in the assert)
* you put more than one <A/> child in the <Content/> and you replace a specific one (.e.g. A[1]) 

** Extra notes **

Once you corrupted a file with this bug, you can "repair" it by adding a node in the document root node : 

```xquery
update insert <Hello/> into doc('/db/test/test.xml')/Test
```

this will insert the node at the wrong position : 

```xml
<Test>
    <Content Foo="bar">
       <Hello/>
    </Content>
</Test>
```

but then you can delete the document...

**Context:**
 - OS: Mac OS X 10.15.3 x86_6
 - eXist-db version: eXist-5.2.0 (eXist Build: 0200123133609) but also on 4.7.1
 - Java Version: "12.0.1" 2019-04-16

**Additional context**
- How is eXist-db installed? : JAR installer
- Any custom changes in e.g. : NO

**Comment by joewiz** [comment]
On first glance, this would suggest that eXist's XQuery Update is deeply broken. I'd have thought that this kind of test would already be included in the eXist test suite, or that we'd have gotten reports before. Very strange.

**Comment by ssire** [comment]
Dear all, have you made any progress on this ? Today I bumped again into this problem (I had forgotten it so it took me a while  to realize I was reconstructing more or less the same sample script to exhibit it to you...)

I found a temporary solution which is to replace the xquery update "replace" operation with a "delete" operation followed by an "insert" operation, that seems to work so far (as long as you don't care about preserving the child sequence ordering if you use it also on sequence with more than one child)...no exception, no corrupted document...

**Comment by adamretter** [comment]
@ssire Sorry for the slow progress on this. Somehow I missed your enquiry and it seems no one else picked it up in the mean-time. I was able to reproduce the problem you described, and have started by adding tests for it here - https://github.com/eXist-db/exist/pull/3576

@joewiz I would not be surprised. We have had a lot of issues around XQuery Update causing data corruption over the years, and there are very few test cases for the facility.

**Comment by dizzzz** [comment]
I honestly missed this one too.....

**Comment by adamretter** [comment]
@ssire Okay I have pushed a fix - hopefully it will be merged soon.
