### ISSUE TITLE
[feature] util:eval should return line/column number on error of provided query

### ISSUE THREAD

**Issue by adamretter** [eXist-db/exist#3512]
It would be nice to have a way to reset the line numbers when using `util:eval` for example if the passed in query to be evaluated is user-defined.

For example, the following query returns line number 12, as that is the overarching line number, but it would be nice to have a flag so that it returns line number 4, as that is the line with $query where the error occurs.

```
let $query :=
"<a>
    <b>
        <c>
            { no:such-function() }
        </c>
    </b>
</a>"
return

    try 
    {
        util:eval($query)
    } catch * {
        $err:line-number
    }
```

**Comment by joewiz** [comment]
For reference, see the `pass` parameter in BaseX's `xquery:eval` function: https://docs.basex.org/wiki/XQuery_Module#xquery:eval.
