### ISSUE TITLE
[BUG] missing location info in errors about unknown type

### ISSUE THREAD

**Issue by joewiz** [eXist-db/exist#3518]
**Describe the bug**

In eXist, errors involving unknown types caused by expressions like `<x/> instance of x`, `<x/> castable as x`, or `<x/> cast as x` lack location information.

**Expected behavior**

I expected the errors to report the location of the error in the query, as they do in BaseX and Saxon. As shown below, Saxon locates the error best of all.

**To Reproduce**

```xquery
xquery version "3.1";

let $instance-of := <x/> instance of x
return
    $instance-of
```

eXist error:

> exerr:ERROR Type: x is not defined

BaseX error:

> Stopped at 4/1: [XPST0051] Unknown type: x.

Saxon error:

> Unknown simple type x
>
> Start location: 3:38

The processors produce analogous results for the following variants:

```
xquery version "3.1";

let $castable-as := <x/> castable as x
return
    $castable-as
```

```
xquery version "3.1";

let $cast-as := <x/> cast as x
return
    $cast-as
```

**Context (please always complete the following information):**
 - OS: macOS 10.15.6
 - eXist-db version: eXist 5.3.0-SNAPSHOT 2e983c7a95fa4f8bde6b3e5a44fda59326d1de3b 20200816082230
 - Java Version: openjdk version "14.0.2" 2020-07-14 (build 14.0.2+12-46)

**Additional context**
- How is eXist-db installed? 5.3.0-SNAPSHOT built from source 
- Any custom changes in e.g. `conf.xml`? None.

**Comment by joewiz** [comment]
The current develop branch (eXist 5.3.0-SNAPSHOT e92ea8f70512dd6dbb49bc1fc059f64944bee045 20200915110349) is still affected.

**Comment by dizzzz** [comment]
in `XQueryTree.g` is the following code:

<img width="629" alt="image" src="https://user-images.githubusercontent.com/1700062/94480614-d8641980-01d6-11eb-9de3-df7bb120b93f.png">

the expression  `sequenceType [type]` throws (when java code is generated) an `XPathException` that we could catch as follows, so the step location information is added to the Exception:

```
try {
..
} catch (XPathException ex) {
ex.setLocation(step.getLine(), step.getColumn());
throw ex;
}
```

I have no clue how to do so, or if it is the correct approach. @ljo @wolfgangmm  please could you help?

**Comment by line-o** [comment]
@joewiz The error is thrown in the Type class L 465 - adding line and column number there should fix this issue.
https://github.com/eXist-db/exist/blob/22ab41e95a7a19a73b0b281b867e313c74c703b2/exist-core/src/main/java/org/exist/xquery/value/Type.java#L465

**Comment by line-o** [comment]
I digged a little deeper and found were the exception is thrown. This is where the exception should be catched and re-thrown in order to add line and column numbers.
https://github.com/eXist-db/exist/blob/develop/exist-core/src/main/antlr/org/exist/xquery/parser/XQueryTree.g#L972

**Comment by line-o** [comment]
OK, I played around with this idea. It turns out that the variable `t` used here

https://github.com/eXist-db/exist/blob/22ab41e95a7a19a73b0b281b867e313c74c703b2/exist-core/src/main/antlr/org/exist/xquery/parser/XQueryTree.g#L977

returns 0 for line _and_ column. 
So, re-throwing exceptions achieves
`Cannot compile xquery: err:XPST0051 Unknown simple type x at line 0 column 0`
at best.

**Comment by line-o** [comment]
It looks like any exception thrown in XQueryTreeParser.java is unable to access line and column.
@ljo @wolfgangmm please tell me I am wrong.

**Comment by dizzzz** [comment]
A bit higher in the call hierarchy the 'step' variable has the location info, hence my attempt to catch the exception, enrichtm and rethrow. My antlr skills are too fragile to code this in the `.g` file.

**Comment by line-o** [comment]
@dizzzz yep, trying this for "cast as" which is a little easier since it is inlined more.

**Comment by line-o** [comment]
That was a quick deep dive into the XQuery parser. Massive benefit, though. Look at the expressions it fixes in #3546

**Comment by line-o** [comment]
Root cause was that the virtual AST node `atomicType` never had a location info attached to it.

https://github.com/eXist-db/exist/blob/22ab41e95a7a19a73b0b281b867e313c74c703b2/exist-core/src/main/antlr/org/exist/xquery/parser/XQuery.g#L590

**Comment by line-o** [comment]
There is likely more of those in the XQueryParser.
