### ISSUE TITLE
[feature] Join eXist-db Slack without exist-db.org / existsolutions.com domain account

### ISSUE THREAD

**Issue by Flurb** [eXist-db/exist#3575]
Hi all!

I would like to participate in the next Open Community Call, but I cannot join your Slack because I don't have an account from a valid domain (exist-db.org or existsolutions.com).

Is it possible to join without this restriction?

**Comment by adamretter** [comment]
@Flurb You should be able to sign up to Slack with your own email address. What seems to be the issue?

**Comment by Flurb** [comment]
I can't continue with Google account, and when I try to create a new account I get the following message:

```
You can use any account with the domain:

exist-db.org
existsolutions.com

Don’t have an email address from one of those domains?
Contact the workspace administrator at eXist-db.org for an invitation.
```

**Comment by adamretter** [comment]
It seems it is now only possible for people to join if they have an @exist-db.org email address. I also tried creating an Invite Link - but it will expire after 30 days. I will try and find a better way to automate this.

In the mean time here is an invite link for you @Flurb : https://join.slack.com/t/exist-db/shared_invite/zt-89ukckoj-zbbC_V2QDIR5nGMokG9TQA
