### ISSUE TITLE
grouping fails inside a default-namespaced element

### ISSUE THREAD

**Issue by EfraimFeinstein** [eXist-db/exist#359]
On a recent eXist 2.2RC build from git.

Executing the following test case XQuery:

```
<x xmlns="test:example">{
    for $x in 1 to 10
    group by $y := $x > 5
    return <y>{$y}</y>
}</x>
```

gives an error: variable '$y' is not set.

Removing xmlns="test:example" removes the error.

Using declare default element namespace "test:example"; also has the error.

**Comment by opax** [comment]
I think this may be closed. The query returns the correct result in eXist-3.2.0.

**Comment by dizzzz** [comment]
Thnx for validating!
