### ISSUE TITLE
Login asked for REST request when already logged in

### ISSUE THREAD

**Issue by wshager** [eXist-db/exist#361]
A login box is presented when I try to PUT content but I'm already logged in. The PUT request was forwarded to REST from the controller via this entry:

``` xml
<dispatch xmlns="http://exist.sourceforge.net/NS/exist">
    <forward url="{$exist:resource}">
      {$login("org.exist.login", "/", (), false())}
    </forward>
</dispatch>
```

**Comment by line-o** [comment]
I can't reproduce the issue with the provided information.

1. create `controller.xq` with restricted route to PUT data
2. login to `org.exist.login`
3. call restricted route and PUT some data providing only the session cookie as authentication

The above works in several projects in different environments (public package repository to name one).

I close this issue as resolved after several years of inactivity. Please reopen if there is more information.
