### ISSUE TITLE
[BUG] "The function documentation has not been generated yet." persists after generation of documentation.

### ISSUE THREAD

**Issue by pdurusau** [eXist-db/exist#3619]
Strictly cosmetic but a bug none the less.

**Describe the bug**
The message "The function documentation has not been generated yet. Please contact the database administrator in order to have the the function documentation generated." perists even after the documentation has been generated.

Quiting eXist after generating the documentation and restarting doesn't remove this message. 

**Expected behavior**
The message: "The function documentation has not been generated yet. Please contact the database administrator in order to have the the function documentation generated." should NOT appear after documentation has been generated.

**To Reproduce**
Open eXistdb 5.2.0 on Linux, go to http://localhost:8080 and open XQuery Function Documentation. Generate documentation, close eXistdb, reopen and observe the same message. 

**Context
 - OS: Debian 10.4
 - eXist-db version: 5.2.0
 - Java Version 1.8.0_20

**Additional context**
- How is eXist-db installed? Jar Installer
- Any custom changes in e.g. `conf.xml`? no

**Comment by dizzzz** [comment]
Is there anything special in exist.log?

**Comment by pdurusau** [comment]
Just checking the log and went to duplicate the issue but gone. Did have to close the browser in between so suspect it was a browser cache issue. Sorry! Appreciate all the hard work! Close this issue.
