### ISSUE TITLE
[BUG] incomplete type error reporting

### ISSUE THREAD

**Issue by PieterLamers** [eXist-db/exist#3628]
**Describe the bug**
Type error message about a mismatch between the expected element name and the supplied element does not report the element names.

**Expected behavior**
report the element names

**To Reproduce**
`let $test as element(b)? := <a/>
return $test`

will return `err:XPTY0004 Invalid type for variable $test. Expected element()?, got element()`
whereas it should return ...`Expected element(b)?, got element(a)`

**Context (please always complete the following information):**
 - OS: linux
 - eXist-db version: 5.3.0-SNAPSHOT dated 20200816142230 2e983c7a95fa4f8bde6b3e5a44fda59326d1de3b

**Comment by line-o** [comment]
Just for reference: This will return without an error in 5.2.0 - which is way worse.

**Comment by line-o** [comment]
@PieterLamers could you provide the commit hash you built from? It is listed in exist.log when you start up the database.

**Comment by PieterLamers** [comment]
@line-o 2e983c7a95fa4f8bde6b3e5a44fda59326d1de3b if that's what you mean.

**Comment by line-o** [comment]
current develop 9ad24bd93f2183f0b61d2ca10ea77fe2a922af00 is also affected
