### ISSUE TITLE
[feature] Integrate XQuery Test Suite into CI for PR checks

### ISSUE THREAD

**Issue by joewiz** [eXist-db/exist#3632]
Integrating an automated run https://github.com/eXist-db/exist-xqts-runner into the CI checks performed with every PR will allow the eXist community to take advantage of the 30K+ XQuery tests created by the W3C working group and community. CI should report on the % of passed tests before the PR and with the PR, and should note newly failed or fixed tests. Test results should be retrievable for some time.

**Comment by line-o** [comment]
Running this on each PR (on travis) would eat up our credits in no time. I therefore suggest to create a GitHub action that can be manually triggered on any branch.

**Comment by joewiz** [comment]
@line-o Makes sense!

Also somewhat related to the discussion of CI-based testing: https://github.com/eXist-db/exist/pull/3341.

**Comment by duncdrum** [comment]
see #3766 
so what are the parameters for how we want this to look?

**Comment by adamretter** [comment]
The problem is not plumbing this into the CI. That has never really been the issue.

The problems are:
1. where to upload the JUnit results?
2. how to process those results into summary stats?
3. and where to build and host graphs that show those results and the change over time?

**Comment by duncdrum** [comment]
1. and 3. => GitHub (pages)
2. can you expand on what processing is necessary

**Comment by joewiz** [comment]
Closed by #4661.
