### ISSUE TITLE
[BUG] First run of DMG eXist.app on macOS quits before launch

### ISSUE THREAD

**Issue by joewiz** [eXist-db/exist#3637]
To reproduce:

1. Download the DMG edition of the current release of eXist from https://github.com/eXist-db/exist/releases.
2. Drag eXist-db.app into the Applications folder.
3. Launch eXist-db.app. 
4. Approve the Gatekeeper dialog confirming that you want to open the app.
5. The app bounces in the dock but then quits.
6. A 2nd attempt to open the app succeeds as normal.

eXist should not quit on first launch.

**Comment by JoernT** [comment]
Does not run for me at all.

Mac Big Sur - 11.4

After performing steps 1-4 as described by @joewiz above a dialog opens saying that my Java version is not sufficient though i got openjdk 11 installed and JAVA_HOME set.

Subsequent runs always result in the same behavior.

**Comment by JoernT** [comment]
Funny thing is that the installation starts when directly going to 

`/Applications/eXist-db.app/Contents/Resources/bin`

and running `./startup.sh`

But then it fails with the following error while starting up:
> WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.exist.storage.BrokerPool (file:/Applications/eXist-db.app/Contents/Resources/../Java/exist-core-5.3.0.jar) to field java.lang.Thread.threadLocals
WARNING: Please consider reporting this to the maintainers of org.exist.storage.BrokerPool
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

**Comment by joewiz** [comment]
Retesting my steps with eXist 5.3.0, I can no longer reproduce the issue. eXist starts as expected on first launch (once you've [cleared the macOS Gatekeeper warnings](https://support.apple.com/en-us/HT202491#:~:text=if%20you%20want%20to%20open%20an%20app%20that%20hasn%E2%80%99t%20been%20notarized%20or%20is%20from%20an%20unidentified%20developer) about opening the app). This is with:

- macOS 11.4
- OpenJDK 1.8.0_292 (AdoptOpenJDK 8, installed via Homebrew)

@JoernT What you described in your first post sounds like a different and more serious issue than what I described - which deserves its own issue if you're able to reproduce it. If you do open a new issue, please provide more info on the JDK distro you're running. It helps to post the result of `/usr/libexec/java_home`, `java -version`, and `ls /Library/Java/JavaVirtualMachines`. If that last command returns more than one result, you might benefit from [completely removing Java from your system](https://github.com/HistoryAtState/hsg-project/wiki/Troubleshooting#remove-all-versions-of-java), then installing just one JDK. I've tested and had good success AdoptOpenJDK 8, which you can install via Homebrew with `brew install --cask homebrew/cask-versions/adoptopenjdk8`.
