### ISSUE TITLE
User-group relations not restored w/o restart

### ISSUE THREAD

**Issue by mgraauw** [eXist-db/exist#3650]
**Describe the bug**
When restoring a backup (from eXist 2.2, but most likely applies to all backups) to eXist 5.2.0, users and groups are restored, but the user-group relations only after exist restart.

Example: my backup has a group `lab`, and a user `marc`, who is a member of group `lab`.
* After clean install of 5.2.0, I have the usual users (`admin`, `guest`, **NO** `marc`).
* After restoring, I see user `marc' and group `lab`, but `marc` is only a member of the group `nogroup`.
    * Same results in:
        *  User Manager
        * Java Admin Client,
        * XQuery via: `sm:get-user-groups('marc')`

After stop and start of eXist, `marc` is member of group `lab`. This led me to believe the restore had failed and retry several times until I found a restart solved things. Apparently user-group relations aren't refreshed properly after restore.

**Expected behaviour**
user-group membership should be available right after restore.

**Context (please always complete the following information):**
 - OS: Win 10
 - eXist-db version: 5.2.0
 - Java Version JRE 1.8.0_211

**Additional context**
Installing with jar installer

**Comment by adamretter** [comment]
I can confirm that this is an issue on versions 5.1.1 and 5.3.0-SNAPSHOT.
