### ISSUE TITLE
[feature] add PATCH support to RESTservlet

### ISSUE THREAD

**Issue by line-o** [eXist-db/exist#3698]
**Is your feature request related to a problem? Please describe.**

APIs make use of a number of different HTTP verbs `OPTION`, `HEAD`, `PUT`, `POST` and `GET` are already supported.

`PATCH` is not supported yet.

**Describe the solution you'd like**

```sh
curl -XPATCH http://localhost:8080/exist/apps/myapp/resource/x -H "Content-Type: application/json" -d '{"property1":"value1"}'
```

would work as expected.

For that existdb's RESTServlet must override the `service` method of `javax.servlet.http.HTTPServlet` in order to recognize the PATCH verb as well.

**Describe alternatives you've considered**

The `PUT` verb can be used as a fallback until this feature is added to Existdb's XqueryServlet

**Additional context**

Reference: https://cxf.apache.org/javadoc/latest/org/apache/cxf/transport/servlet/AbstractHTTPServlet.html#service-javax.servlet.ServletRequest-javax.servlet.ServletResponse-

**Comment by adamretter** [comment]
The goal is to ultimately remove the XQueryServlet. Would it make more sense to add it to the RESTServer?

**Comment by wolfgangmm** [comment]
Totally agree. XQueryServlet would be the wrong place. The request will go to the RESTServer.

**Comment by line-o** [comment]
Oh, OK then. I change that

**Comment by joewiz** [comment]
Regarding removal of XQueryServlet, see https://github.com/eXist-db/exist/issues/555. It's labeled as a 6.0.0 feature.
