### ISSUE TITLE
[BUG] id() function does not operate on given nodeset

### ISSUE THREAD

**Issue by jeanpaulrehr** [eXist-db/exist#3752]
**Description**

In eXist 5.3 SNAPSHOT (also confirmed in 5.1):

A sequence of nodes are first filtered by an attribute value in a predicate. When the resulting sequence is searched using `id("value")` a node **which should not be in the result sequence** is still there. When the same search is done using a predicate `[@xml:id="value"]` the result is not returned.

**Expected behavior**
`id("value")` and `[@xml:id="value"]`  should return the same result. In the test case below, this means both should return an empty sequence.

**To reproduce**

```xquery
xquery version "3.1";

declare namespace tei="http://www.tei-c.org/ns/1.0"; 

let $test-coll := "/db/apps/"

let $doc :=
    <listPlace xmlns="http://www.tei-c.org/ns/1.0">
        <place type="unknown" xml:id="lo_bosquet">
	    <desc>
                <placeName>lo Bosquet</placeName>
           </desc>
	</place>
	<place type="domus" xml:id="domus_jordan_de_lanta--lo_bosquet">
	    <desc>
		<placeName xml:lang="en">domus of Jordan de Lanta</placeName>
		<placeName xml:lang="fr">domus de Jordan de Lanta</placeName>
		<settlement ref="#lo_bosquet"/>
	    </desc>
	</place>
	<place type="village" xml:id="varennes_haute-garonne">
	    <desc>
		<placeName>Varennes</placeName>
		<region>Haute-Garonne</region>
		<geo>43.47653 1.68875</geo>
	    </desc>
        </place>
</listPlace>

let $store := xmldb:store($test-coll,"listPlace.xml",$doc)

let $placeDoc := doc($store)

let $villageList := $placeDoc//tei:place[@type="village"]

(: the following should return nothing, but returns one entry :)
return $villageList/id("lo_bosquet")


(: the following returns nothing - ie. correct result :)
(: return  $villageList[@xml:id="lo_bosquet"]  :)
```

**Context:**
 - OS: macOS Catalina 10.15.7
 - eXist-db version:  5.3.0 SNAPSOT 2021-02-19 03:55 UTC
 - Java Version 8 251 (build 1.8.0_251-b08)

**Additional context**
- eXist from TAR file
- No customizations

**Comment by line-o** [comment]
@jeanpaulrehr Oh my, I just read the [specification for `fn:id`](https://www.w3.org/TR/xpath-functions-31/#func-id) and it clearly states:

> The function returns a sequence, in document order with duplicates eliminated, containing every element node E that satisfies all the following conditions:

> E is in the target document. The target document is the document containing $node, or the document containing the context item (.) if the second argument is omitted. The behavior of the function if $node is omitted is exactly the same as if the context item had been passed as $node.

If you agree that what you observed is in fact according to the above specification we can close the issue.

Sorry for not checking when we discussed it in slack.

**Comment by line-o** [comment]
So, since you use `fn:id#1` the target document is the one that contains the context item. That is the complete document and never a filtered list.

**Comment by jeanpaulrehr** [comment]
If it's in compliance with the specification, we can't call it a bug :)
