### ISSUE TITLE
Permissions does not copy on copy operation 

### ISSUE THREAD

**Issue by shabanovd** [eXist-db/exist#377]
here an old fix https://github.com/shabanovd/exist/commit/8d36f0fa33a65dc235ea7068196de2ea708fd5e6

**Comment by adamretter** [comment]
Can you be specific, are you copying a collection or file?

**Comment by shabanovd** [comment]
To reproduce 
 - create collection
 - add document there
 - set permissions
 - copy that collection

new document must have same permissions as source one have
