### ISSUE TITLE
[feature] Linux/arm64 version of docker image existdb

### ISSUE THREAD

**Issue by jbwaagmeester** [eXist-db/exist#3778]
**Is your feature request related to a problem? Please describe.**
It would be great to be able to run a simple docker image of existdb on an arm device (like a raspberry pi). Right now only linux/amd64 images are available through docker hub.

**Describe the solution you'd like**
A dockerfile to build linux/arm64 images of existdb.

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by jbwaagmeester** [comment]
Today I have been playing around with the [dockerfile](https://github.com/eXist-db/exist/commit/0697249cf4b7a83ddc6318a80ee177bececf548c#diff-e06009c91b03b0212493cef67386d831bde8dc3729db1c33707e1f24458c1ad2L7) a bit (see below) I have used the arm version of openjdk 11 (I was not able to find version 8), but I am not sure if this change is even possible. Then I tried to find an ARM64 version of all the Apache FOP and Batik files, which I found (I hope) [here](https://packages.debian.org/search?searchon=contents&keywords=libfreetype&mode=filename&suite=stable&arch=any).

When I am trying to compile the image (following [these](https://www.docker.com/blog/multi-arch-images/) instructions) I get the following error in my terminal:

```
error: failed to solve: rpc error: code = Unknown desc = failed to solve with frontend dockerfile.v0: failed to create LLB definition: failed to process "${build-tstamp}": missing ':' in substitution
```
For now, I am not sure how to solve this. I will try to read up on it a bit more when I have time.

```
FROM arm64v8/openjdk:11-jdk-slim as builder

# Install tools required by FOP
WORKDIR /usr/local
RUN apt-get update && apt-get install -y --no-install-recommends \
  expat \
  fontconfig \
  liblcms2-2 \
  ttf-dejavu-core

FROM gcr.io/distroless/java:11

# Copy over dependancies for Apache FOP, missing from gcr's JRE
COPY --from=builder /usr/lib/aarch64-linux-gnu/libfreetype.so.6 /usr/lib/aarch64-linux-gnu/libfreetype.so.6
COPY --from=builder /usr/lib/aarch64-linux-gnu/liblcms2.so.2 /usr/lib/aarch64-linux-gnu/liblcms2.so.2
COPY --from=builder /usr/lib/aarch64-linux-gnu/libpng16.so.16 /usr/lib/aarch64-linux-gnu/libpng16.so.16
COPY --from=builder /usr/lib/aarch64-linux-gnu/libfontconfig.so.1 /usr/lib/aarch64-linux-gnu/libfontconfig.so.1

# Copy dependancies for Apache Batik (used by Apache FOP to handle SVG rendering)
COPY --from=builder /etc/fonts /etc/fonts
COPY --from=builder /lib/aarch64-linux-gnu/libexpat.so.1 /lib/aarch64-linux-gnu/libexpat.so.1
COPY --from=builder /usr/share/fontconfig /usr/share/fontconfig
COPY --from=builder /usr/share/fonts/truetype/dejavu /usr/share/fonts/truetype/dejavu

# Copy eXist-db
COPY LICENSE /exist/LICENSE
COPY autodeploy /exist/autodeploy
COPY etc /exist/etc
COPY lib /exist/lib
COPY logs /exist/logs


# Build-time metadata as defined at http://label-schema.org
# and used by autobuilder @hooks/build
LABEL org.label-schema.build-date=${build-tstamp} \
      org.label-schema.description="${project.description}" \
      org.label-schema.name="existdb" \
      org.label-schema.schema-version="1.0" \
      org.label-schema.url="${project.url}" \
      org.label-schema.vcs-ref=${build-commit-abbrev} \
      org.label-schema.vcs-url="${project.scm.url}" \
      org.label-schema.vendor="existdb"

EXPOSE 8080 8443

# make CACHE_MEM and MAX_BROKER available to users
ARG CACHE_MEM
ARG MAX_BROKER

ENV EXIST_HOME "/exist"
ENV CLASSPATH=/exist/lib/${exist.uber.jar.filename}

ENV JAVA_TOOL_OPTIONS \
  -Dfile.encoding=UTF8 \
  -Dsun.jnu.encoding=UTF-8 \
  -Djava.awt.headless=true \
  -Dorg.exist.db-connection.cacheSize=${CACHE_MEM:-256}M \
  -Dorg.exist.db-connection.pool.max=${MAX_BROKER:-20} \
  -Dlog4j.configurationFile=/exist/etc/log4j2.xml \
  -Dexist.home=/exist \
  -Dexist.configurationFile=/exist/etc/conf.xml \
  -Djetty.home=/exist \
  -Dexist.jetty.config=/exist/etc/jetty/standard.enabled-jetty-configs \
  -XX:+UnlockExperimentalVMOptions \
  -XX:+UseCGroupMemoryLimitForHeap \
  -XX:+UseG1GC \
  -XX:+UseStringDeduplication \
  -XX:MaxRAMFraction=1 \
  -XX:+ExitOnOutOfMemoryError

HEALTHCHECK CMD [ "java", \
    "org.exist.start.Main", "client", \
    "--no-gui",  \
    "--user", "guest", "--password", "guest", \
    "--xpath", "system:get-version()" ]

ENTRYPOINT [ "java", \
    "org.exist.start.Main", "jetty" ]
```

**Comment by adamretter** [comment]
@jbwaagmeester It looks like you have taken the Dockerfile from `exist-docker/src/main/resources` in our Git repo? That `Dockefile` is actually a template that is interpolated when the Maven build is run. The error you are seeing with `${build-tstamp}` is because that would have been replace by Maven with a real value before Docker is called. For experimentation, I suggest building exist-db from source and then making a copy of the Dockerfile from `exist-docker/target/`.

I would also suggest to stick with Java 8 for the time being with eXist-db. You can find an example of a Arm64 Docker Image with Java 7 (you can switch that out for Java 8!) that my company use as the build environment for RocksDB here - https://github.com/evolvedbinary/docker-rocksjava/blob/master/centos7_arm64v8/Dockerfile

**Comment by jbwaagmeester** [comment]
Yes, you are right. I will use the other file then. Thanks for the suggestions!

**Comment by duncdrum** [comment]
@jbwaagmeester note that the builds in Adam’s link use centOS, to get fop working I would stick with a Debian based image, alternatively go all alpine in builder and final build stage

**Comment by jbwaagmeester** [comment]
> @jbwaagmeester It looks like you have taken the Dockerfile from `exist-docker/src/main/resources` in our Git repo? That `Dockefile` is actually a template that is interpolated when the Maven build is run. The error you are seeing with `${build-tstamp}` is because that would have been replace by Maven with a real value before Docker is called. For experimentation, I suggest building exist-db from source and then making a copy of the Dockerfile from `exist-docker/target/`.
> 
> I would also suggest to stick with Java 8 for the time being with eXist-db.
> 
> You can find examples of Arm64 Docker Images with Java 7 (you can switch that out for Java 8!) that my company use as the build environment for RocksDB here:
> 
> 1. https://github.com/evolvedbinary/docker-rocksjava/blob/master/centos7_arm64v8/Dockerfile
> 2. https://github.com/evolvedbinary/docker-rocksjava/blob/master/alpine3_arm64v8/Dockerfile

I am not entirely sure how to find this dockerfile you mention. Could you perhaps explain it to me or provide me with some link to an explanation? When I build the image, mount a container and try to use the 'cp' command I get various folders but no exist-docker/target/dockerfile.

**Comment by adamretter** [comment]
The Dockerfile isn't in the container. When you build eXist-db from source you will find it in the sourcetree target

**Comment by duncdrum** [comment]
aka you need to run `mvn clean package` in the checked out sourcecode repo. Make sure that maven (the build tool) is using java 8.

**Comment by jbwaagmeester** [comment]
I feel like I am wasting your collective time, nothing you both said makes sense to me. Even after extensive searching online, I am only able to see the history of the image I pulled into docker, but then there are all these hashes. I think I will have to dive into this a bit more later. Thanks anyway.

**Comment by adamretter** [comment]
@jbwaagmeester Here are some instructions from start to finish. You will need Java JDK 8, Git, Docker, and Maven 3.6.3 installed.

```
git clone https://github.com/exist-db/exist.git
cd exist
mvn clean package -Ddocker=true
cd exist-docker/target
cat Dockerfile
```

**Comment by jbwaagmeester** [comment]
Ok, it almost seems to work by using `arm64v8/alpine:3.6` and building with `docker buildx build --platform linux/arm64 -t <IMAGE NAME> .`. I get to build step 13 from 14. The issue seems to be the logs from /exist/logs. I get the following `error: failed to solve: rpc error: code = Unknown desc = failed to compute cache key: "/logs" not found: not found`. Anyone has an idea to solve this issue?

**Comment by adamretter** [comment]
@jbwaagmeester No idea, I haven't seen that before.

**Comment by duncdrum** [comment]
It looks like the xslt we run on the log config file, isn’t working on your alpine base image. Just in-line it to run with default logs config, or pick a different tool to run the xslt

**Comment by jbwaagmeester** [comment]
Would have a suggestion of doing either of those things? The existdb default logs are in exist/logs, right? And how would I be able to pick a different tool to run the xslt? In the current Dockerfile I don't see xslt being mentioned, so I am not sure what it running it at the moment.

**Comment by duncdrum** [comment]
for future reference the xslt is run via assembly before being copied in the dockerfile `exist-docker/src/assembly/dist-assembly-docker.xml` 

the xslt lives here: `exist-docker/src/main/xslt/log4j2-docker.xslt`

the OPs fix is running with the default files, instead of the modified ones. As this seems to have done the trick, i m going to close this issue as e're not currently working on ARM images. Please open a new issue if there are outstanding questions
