### ISSUE TITLE
[BUG] incorrect arity on function duplicates reporting

### ISSUE THREAD

**Issue by PieterLamers** [eXist-db/exist#3790]
**Describe the bug**
When you load a library module that has a function that has been defined multiple times, you will get a report like the following: `err:XQST0034 Function test:my-function#0 is already defined.`

**Expected behavior**
Instead of `#0` we want the correct number of arguments reported as the arity of the duplicate function.

**To Reproduce**
create a library module by the name `test.xqm` with the following:
```
xquery version "3.1";

module namespace test = 'http://test';

declare function test:my-function( $argument as item()* ) { () };
declare function test:my-function( $argument as item()* ) { () };
```

create a main module with the following:
```
xquery version "3.1";

import module namespace test = 'http://test' at 'test.xqm';
```
Oxygen will now report as follows:
```
err:XQST0034 error found while loading module test: Error while loading module test.xqm: Function test:my-function#0 is already defined.
```
**Context (please always complete the following information):**
 - OS: Windows 10
 - eXist-db version: 5.3.SNAPSHOT 288f3cc74549e8a913bf363250b0744f2695b8e6
 - Java Version1.8.0_281-b09

**Comment by joewiz** [comment]
@PieterLamers Interesting! Could you clarify what you mean by this please in the section on reproducing the bug?

> Oxygen will now report as described.

**Comment by PieterLamers** [comment]
@joewiz I'd missed your feedback, updated the original posting now. @line-o I know it is just a minor reporting issue, but I still think this is a bug, and not an enhancement. `#0` means that there are no arguments, and in the example it should report `#1`.

**Comment by line-o** [comment]
✅ @PieterLamers
