### ISSUE TITLE
document-node()

### ISSUE THREAD

**Issue by jensopetersen** [eXist-db/exist#382]
Calling document-node() returns in all nodes in an in-memory document and all nodes accessed by node() in a stored document, whereas it should return all document nodes in the context. The document node cannot be accessed on the child or descendant axes.

See http://markmail.org/thread/bpgngbsg3suliioo.

**Comment by adamretter** [comment]
Unfortunately I can no longer find the test that shows the issue with differing whitespace nodes between memtree and persistent DOMs. So I will just submit the fix for the issue describing by @jensopetersen
