### ISSUE TITLE
[BUG] SQL prepared insert statement inserts empty string instead of NULL 

### ISSUE THREAD

**Issue by PieterLamers** [eXist-db/exist#3828]
**Describe the bug**
I want to insert a NULL value using a prepared statement.

**Expected behavior**
I expect an empty `<sql:param/>` to insert NULL rather than ''.

**To Reproduce**
I am using some Benjamins internal module (`jbdba`) to create the connection and the handle that I will use here. The MySQL statement is below, but I have confirmed the same to hold for SQL Server.
```
let $sql-create-statement := '
  CREATE TABLE `test` (
    `test_id` int NOT NULL AUTO_INCREMENT,
    `charfield` varchar(45) DEFAULT NULL
    PRIMARY KEY (`test_id`)
  );
'

let $insert-string := 'INSERT INTO test (charfield) VALUES (?);'

let $insert-params :=
  <sql:parameters>
    <sql:param sql:type="varchar"/>
  </sql:parameters>
  
let $insert-result := jbdba:execute-prepared-sql-raw( $jbdba:db-some-db, $insert-string, $insert-params )

return $insert-result
```
I am not sure what the intended behavior is, and it is possible (but inconvenient) to work around this problem by not passing in NULL as a parameter, but rather directly in the insert string. However, it would make more sense to also be able to pass in a NULL value through a parameter. Also, I believe (but cannot test anymore) that this is a regression from 4.7.

**Notes**
To reproduce you will need to run the CREATE statement in MySQL first, and replace the custom `jbdba` function by generic code. I am currently not able to produce that.
I have also tried `<sql:param sql:type="varchar" sql:null="true" />` and also tried with integer field, but in all cases an empty string is presented (leading to an error in the case of an integer field).

**Screenshots**
![image](https://user-images.githubusercontent.com/52227100/115499170-405f7780-a26f-11eb-8853-a921a89854cd.png)

**Context (please always complete the following information):**
 - OS: Windows
 - eXist-db version: 5.3.0-SNAPSHOT 288f3cc74549e8a913bf363250b0744f2695b8e6
 - Java Version 1.8.0_281-b09

**Comment by adamretter** [comment]
I had to check the code to be certain, but I now see it is also documented in the description of the `sql:execute` function - https://exist-db.org/exist/apps/fundocs/view.html?uri=http://exist-db.org/xquery/sql&location=java:org.exist.xquery.modules.sql.SQLModule#execute.4

For a null, you need to explicitly specify a`<sql:null/>` child element. For example:

```
let $insert-params :=
  <sql:parameters>
    <sql:param sql:type="varchar"><sql:null/></sql:param>
  </sql:parameters>
  ```

If that works, I think we could close this issue. If not just let me know...

**Comment by PieterLamers** [comment]
@adamretter I must be blind, I do not see that anywhere on the fundocs page (neither does Ctrl-F). However, I'd be happy to drop the issue if it works. Will try now.

**Comment by PieterLamers** [comment]
`<sql:null/>` as the content of the `sql:param` works! Would be nice to have a clearer location for the documentation of this otherwise hidden feature.

**Comment by adamretter** [comment]
>  I must be blind, I do not see that anywhere on the fundocs page

It appears in the fundocs for 5.2.0 and 5.3.0-SNAPSHOT. It looks like the exist-db.org website might be out of date :-(
I am afraid I don't have any control over the exist-db.org website to update it.
