### ISSUE TITLE
Error in fn:format-number

### ISSUE THREAD

**Issue by lcahlander** [eXist-db/exist#383]
If you evaluate the following in eXide:

&lt;html xmlns="http://www.w3.org/1999/xhtml"&gt;
    &lt;head&gt;
        &lt;title&gt;&lt;/title&gt;
    &lt;/head&gt;
    &lt;body&gt;
        &lt;table&gt;
            &lt;tr&gt;
                &lt;th&gt;Formula&lt;/th&gt;
                &lt;th&gt;Expected&lt;/th&gt;
                &lt;th&gt;Actual&lt;/th&gt;
            &lt;/tr&gt;
            &lt;tr&gt;
                &lt;td&gt;format-number(12345.6, '#,###.00')&lt;/td&gt;
                &lt;td&gt;12,345.60&lt;/td&gt;
                &lt;td&gt;{try {format-number(12345.6, '#,###.00')} catch \* {$err:code}}&lt;/td&gt;
            &lt;/tr&gt;
            &lt;tr&gt;
                &lt;td&gt;format-number(12345678.9, '9,999.99')&lt;/td&gt;
                &lt;td&gt;12,345,678.90&lt;/td&gt;
                &lt;td&gt;{try {format-number(12345678.9, '9,999.99')} catch \* {$err:code}}&lt;/td&gt;
            &lt;/tr&gt;
            &lt;tr&gt;
                &lt;td&gt;format-number(123.9, '9999')&lt;/td&gt;
                &lt;td&gt;0124&lt;/td&gt;
                &lt;td&gt;{try {format-number(123.9, '9999')} catch \* {$err:code}}&lt;/td&gt;
            &lt;/tr&gt;
            &lt;tr&gt;
                &lt;td&gt;format-number(0.14, '01%')&lt;/td&gt;
                &lt;td&gt;14%&lt;/td&gt;
                &lt;td&gt;{try {format-number(0.14, '01%')} catch \* {$err:code}}&lt;/td&gt;
            &lt;/tr&gt;
            &lt;tr&gt;
                &lt;td&gt;format-number(-6, '000')&lt;/td&gt;
                &lt;td&gt;-006&lt;/td&gt;
                &lt;td&gt;{try {format-number(-6, '000')} catch \* {$err:code}}&lt;/td&gt;
            &lt;/tr&gt;
            &lt;tr&gt;
                &lt;td&gt;format-number(12.34, '0.000e00')&lt;/td&gt;
                &lt;td&gt;1.234e01&lt;/td&gt;
                &lt;td&gt;{try {format-number(12.34, '0.000e00')} catch \* {$err:code}}&lt;/td&gt;
            &lt;/tr&gt;
            &lt;tr&gt;
                &lt;td&gt;format-number(12.34, '#.000e0')&lt;/td&gt;
                &lt;td&gt;0.123e2&lt;/td&gt;
                &lt;td&gt;{try {format-number(12345.6, '#,###.00')} catch \* {$err:code}}&lt;/td&gt;
            &lt;/tr&gt;
            &lt;tr&gt;
                &lt;td&gt;format-number(1234.5678, '#ʹ##0•00', 'ch')&lt;/td&gt;
                &lt;td&gt;1ʹ234•57&lt;/td&gt;
                &lt;td&gt;{try {format-number(1234.5678, '#ʹ##0•00', 'ch')} catch \* {$err:code}}&lt;/td&gt;
            &lt;/tr&gt;
        &lt;/table&gt;
    &lt;/body&gt;
&lt;/html&gt;

You will see failures for the examples in http://www.w3.org/TR/xpath-functions-30/#func-format-number

I found this, because I was trying:

fn:format-number(3.1, '000.0') and got 3.1

where xsl:format-number(3.1, '000.0') returns what I expected as 003.1

Also, the documentation for fn:format-number is wrong.  The $picture should be referring to the W3C spec mentioned above and not java.text.Decimal.

format-number
format-number($value as numeric?, $picture as xs:string) as xs:string
The formatting of a number is controlled by a picture string. The picture string is a sequence of •characters•, in which the characters assigned to the variables decimal-separator-sign, grouping-sign, decimal-digit-family, optional-digit-sign and pattern-separator-sign are classified as active characters, and all other characters (including the percent-sign and per-mille-sign) are classified as passive characters.
Parameters:
$value? The number to format
$picture    The format pattern string. Please see the JavaDoc for java.text.DecimalFormat to get the specifics of this format string.
Returns:
xs:string : the formatted string
format-number
format-number($value as numeric?, $picture as xs:string, $decimal-format-name as 
xs:string) as xs:string
Parameters:
$value? The number to format
$picture    The format pattern string. Please see the JavaDoc for java.text.DecimalFormat to get the specifics of this format string.
$decimal-format-name    The decimal-format name must be a QName, which is expanded as described in [2.4 Qualified Names]. It is an error if the stylesheet does not contain a declaration of the decimal-format with the specified expanded-name.
Returns:
xs:string : the formatted string

**Comment by dizzzz** [comment]
Formula	| Expected	| Actual
-------------|---------|-----
format-number(12345.6, '#,###.00')	| 12,345.60	| 12,345.60
format-number(12345678.9, '9,999.99')	|  12,345,678.90  | 	err:XTDE1310
format-number(123.9, '9999')	 | 0124	 | err:XTDE1310
format-number(0.14, '01%')	 | 14%	 | 14
format-number(-6, '000')  | 	-006	 | 0-6
format-number(12.34, '0.000e00')	 | 1.234e01	 |  err:XTDE1310
format-number(12.34, '#.000e0')  | 	0.123e2	 |  12,345.60
format-number(1234.5678, '#ʹ##0•00', 'ch')	1ʹ234•57	err:XTDE1310

**Comment by lagivan** [comment]
@refond you saved my day mentioning `xsl:format-number`, thanks! This issue is very confusing. 

@dizzzz one more example:

Formula  | Expected | Actual
----------- | ------------ | ---------
format-number(0.100, '0.#####') | 0.1 | 0.10000

**Comment by joewiz** [comment]
Is this still a bug in 3.0RC1? If so, we need tests to be written, I presume?

**Comment by joewiz** [comment]
Is this all still a bug in 3.0RC1? If so, we need tests to be written, I presume?

**Comment by joewiz** [comment]
Is this all still a bug in 3.0RC1? If so, we need tests to be written, I presume?

**Comment by joewiz** [comment]
(Sorry if you got duplicates of my comment. The site was stuck.)

**Comment by joewiz** [comment]
The bugs in the `format-number` function reported here are still current with eXist 4.2.1.

**Comment by brobertson** [comment]
How can the community help with correcting this 5 year old bug? Do test cases like this help:

`(format-number(0.14, '01%') eq "14%")`

**Comment by adamretter** [comment]
We should likely test against XQTS 3.1 - https://github.com/w3c/qt3tests/blob/master/fn/format-number.xml

**Comment by dizzzz** [comment]
SOme time ago I created a script that transforms the w3c document into a XQsuite test file. I was not allowed to integrate the file :-(

**Comment by line-o** [comment]
From what I understand the function `fn:format-number` just needs to do what `xsl:format-number`. Am I reading this correctly?

**Comment by adamretter** [comment]
@dizzzz we now have all those tests as part of this - https://github.com/exist-db/exist-xqts-runner

**Comment by adamretter** [comment]
@brobertson I have started a new implementation which I hope will be correct, I will try and finish it in the next few days.

**Comment by adamretter** [comment]
This can be testes with [exist-xqts-runner-assembly-1.0.0.jar](https://github.com/eXist-db/exist-xqts-runner) -ts fn-format-number

**Comment by brobertson** [comment]
Lovely. Thanks!
