### ISSUE TITLE
validation mode="no"

### ISSUE THREAD

**Issue by twcook** [eXist-db/exist#393]
2.2RC build 

Fails to skip validation if document contains a reference to a schema.  

IOW: If I want to upload documents that reference schemas with XML Schema 1.1 features, I cannot turn off validation and upload them.  I would have to edit all the documents to remove the reference to the schema.  

I validated this by removing the schema ref in a document after it failed to upload with a validation error.

**Comment by dizzzz** [comment]
it is specific about xsd1.1? there is no support for that (yet).
uploading XML with references to schemas should just work, as documented (use of catalogs etc)

ok to close?
