### ISSUE TITLE
[BUG] Cache module: "lazy creation disabled" error thrown when lazy creation is enabled

### ISSUE THREAD

**Issue by joewiz** [eXist-db/exist#3932]
**Describe the bug**

With a fresh build of 5.3.0-SNAPSHOT, calling `cache:put("foo", "bar", "baz")` fails with this error:

> `cache:lazy-creation-disabled` There is no such named cache: `foo`, and lazy creation of the cache has been disabled.

But in conf.xml, the cache module has the default parameter:

```xml
<module uri="http://exist-db.org/xquery/cache" class="org.exist.xquery.modules.cache.CacheModule">
    <parameter name="enableLazyCreation" value="true"/>
```

From my reading of PR #3877 where the new options were added and the accompanying [documentation PR #614](https://github.com/eXist-db/documentation/pull/614), using `cache:put` to lazily create a cache when `conf.xml` has `enableLazyCreation=true` (i.e., the default) should not throw this error.

**Expected behavior**

If `conf.xml` has `enableLazyCreation=true` (i.e., the default), a call to `cache:put()` for a cache that hasn't been explicitly created should not trigger a `cache:lazy-creation-disabled` error.

**To Reproduce**

The following test assumes that `conf.xml` has `enableLazyCreation=true`. 

```xquery
xquery version "3.1";

module namespace t="http://exist-db.org/xquery/test";

declare namespace test="http://exist-db.org/xquery/xqsuite";

declare
    %test:setUp
function t:setup() {
    if (cache:names() = "foo") then
        cache:destroy("foo")
    else
        ()
};

declare
    %test:tearDown
function t:tearDown() {
    cache:destroy("foo")
};

declare
    %test:assertEmpty
function t:test() {
    try {
        cache:put("foo", "bar", "baz")
    } catch * {
        $err:code
    }
};
```

The test suite returns this result:

```xml
<testsuite package="http://exist-db.org/xquery/test" timestamp="2021-06-14T12:30:27.216-04:00"
    tests="1" failures="1" errors="0" pending="0" time="PT0.001S">
    <testcase name="test" class="t:test">
        <failure message="assertEmpty failed." type="failure-error-code-1"/>
        <output>cache:lazy-creation-disabled</output>
    </testcase>
</testsuite>
```

**Context (please always complete the following information):**
 - OS: macOS 11.4
 - eXist-db version: eXist 5.3.0-SNAPSHOT e371efd9987a9a2f4414839c7bf1dbc20107b6d1 20210604033555
 - Java Version: OpenJDK 1.8.0_292 (liberica-jdk-full)

**Additional context**
- How is eXist-db installed? Built via source, running DMG version
- Any custom changes in e.g. `conf.xml`? none

**Comment by adamretter** [comment]
@joewiz I am afraid that I have not been able to reproduce the behaviour that you have described. Just to be certain I have added some additional tests to try and show that. Could you take a look at the tests in - https://github.com/eXist-db/exist/pull/3935

**Comment by joewiz** [comment]
@adamretter Thank you! I wasn't able to test it before the 5.3.0 release but just repeated my test on the released version and confirmed that there's no longer any trace of the problem I initially reported. 

Going back over this in my head, I think I had run https://github.com/HistoryAtState/hsg-project/blob/master/build/configure-exist.xsl#L15-L21 on my conf.xml - which I used to have to do to work with the cache module. I didn't notice that eXist switched the cache module to on by default at some point in the development of eXist 5. I can't find the commit, but in my investigation just now, the cache module went from disabled by default in 5.0.0-RC7 and earlier to enabled by default in 5.0.0-RC8 and since. 

So, the cache module worked fine and works fine in eXist 5.3.0. Sorry for the misleading/misinformed report!
