### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by StephanMa** [eXist-db/exist#3956]
> To be able to better understand you problem, please add as much information as possible to this ticket. Always test your bugs against the latest stable release of exist. We cannot provide support for older versions here on GitHub. If the version of eXist that is experiencing the issue is more than 1 major version behind the most recent release, please consider posting a question on our mailing list. 

**Describe the bug**
I tried to migrate a TEI Publisher-App to eXist 5.3.0. This App does a certain amount of styling via ODD. When I try to recompile the ODD, I get an error that all files (*print, *epub, *latex, *web) couldn't be saved. 
When opening e.g. *-web.invalid.xql, I see that one function was added twice. 
```xquery

(: generated template function for element spec: item :)
declare %private function model:template-item($config as map(*), $node as node()*, $params as map(*)) {
    <t xmlns=""><li onclick="goTo('{$config?apply-children($config, $node, $params?uri)}')">{$config?apply-children($config, $node, $params?content)}
        				                
        				            </li></t>/*
};

(: generated template function for element spec: item :)
declare %private function model:template-item($config as map(*), $node as node()*, $params as map(*)) {
    <t xmlns=""><li onclick="goTo('{$config?apply-children($config, $node, $params?uri)}')">{$config?apply-children($config, $node, $params?content)}
        				                
        				            </li></t>/*
};
```

**Expected behavior**
I expect that recreating the functions from ODD Files works as it did on eXist 5.2.0.

**To Reproduce**
> The *best* way is to provide an [SSCCE (Short, Self Contained, Correct (Compilable), Example)](http://sscce.org/). One type of SSCCE could be a small test which reproduces the issue and can be run without dependencies. The [XQSuite - Annotation-based Test Framework for XQuery](http://exist-db.org/exist/apps/doc/xqsuite.xml) makes it very easy for you to create tests. These tests can be executed from the [eXide editor](http://exist-db.org/exist/apps/eXide/index.html) (XQuery - Run as Test)

```extraction from ODD
<elementSpec ident="item" mode="change">
        				    <model predicate="ancestor::div[@type='SVPListe']" behaviour="inline">
        				        <param name="uri" value="substring(@corresp,2)"/>
        				        <param name="name" value="concat('id_', @xml:id)"/>
        				        <param name="content" value="."/>
        				        <pb:template xmlns="" xml:space="preserve">
        				            <li onclick="goTo('[[uri]]')">[[content]]
        				                
        				            </li>
                                </pb:template>
        				    </model>
        				</elementSpec>
```

If the above isn't working, please tell us the exact steps you took when you encountered the problem:
1. using attached ODD
2. regenerate files from ODD
[example.txt](https://github.com/eXist-db/exist/files/6725994/example.txt)

**Screenshots**
![Bildschirmfoto 2021-06-28 um 13 52 23](https://user-images.githubusercontent.com/6735556/123632386-2797b300-d818-11eb-8719-563b69144bdd.png)

**Context (please always complete the following information):**
Mac M1
macOS Big Sur 11.4
JDK 15.0.2

**Additional context**
- How is eXist-db installed? [e.g. JAR installer, DMG, … ]: builded via man and started via `./startup.sh`
- Any custom changes in e.g. `conf.xml`? none

**Comment by line-o** [comment]
Hello @StephanMa the issue you are describing hints at a problem in the ODD compilation of TEI Publisher. This is not an issue of existdb. I would suggest you open an issue at https://github.com/eeditiones/tei-publisher-app 
It is also very important to include the version of TEI-Publisher your experiencing this issue with. Upgrading tei-publisher might solve your problem already.

**Comment by StephanMa** [comment]
Hmm alright… will copy this content and create a new issue for the tei publisher

**Comment by line-o** [comment]
👍🏼

**Comment by line-o** [comment]
Thank you for going the extra mile,
because tei-publisher is in another github organization this issue cannot be moved automatically.

**Comment by StephanMa** [comment]
No problem... :) 
For reference... https://github.com/eeditiones/tei-publisher-app/issues/55
