### ISSUE TITLE
[BUG] Unable to notarise exist-db installer for macOS

### ISSUE THREAD

**Issue by line-o** [eXist-db/exist#3961]
While releasing eXist-5.3.0 we were unable to notarise the `.dmg` file.
Apple reported that a binary contained in the app was not notarised/signed which resulted in the entire installer to be rejected.

The binary in question is `eXist-db-5.3.0.dmg/eXist-db.app/Contents/Java/jansi-2.3.3.jar/org/fusesource/jansi/internal/native/Mac/x86/libjansi.jnilib`

Further research found that this seems to be a common problem with jansi.

- https://github.com/Unidata/netcdf-java/issues/199
- https://issues.apache.org/jira/browse/MNG-7172

Below the complete notarisation error report:

```json
{
  "logFormatVersion": 1,
  "jobId": "4e307444-2077-4820-bac6-5d133bf5e43b",
  "status": "Invalid",
  "statusSummary": "Archive contains critical validation errors",
  "statusCode": 4000,
  "archiveFilename": "eXist-db-5.3.0.dmg",
  "uploadDate": "2021-06-28T15:20:28Z",
  "sha256": "8c51155ab84b5eb52b8cbaebf4dd7be5d94c55ec08087793d1c531049377f93a",
  "ticketContents": null,
  "issues": [
    {
      "severity": "error",
      "code": null,
      "path": "eXist-db-5.3.0.dmg/eXist-db.app/Contents/Java/jansi-2.3.3.jar/org/fusesource/jansi/internal/native/Mac/x86/libjansi.jnilib",
      "message": "The binary is not signed.",
      "docUrl": null,
      "architecture": "i386"
    },
    {
      "severity": "error",
      "code": null,
      "path": "eXist-db-5.3.0.dmg/eXist-db.app/Contents/Java/jansi-2.3.3.jar/org/fusesource/jansi/internal/native/Mac/x86/libjansi.jnilib",
      "message": "The signature does not include a secure timestamp.",
      "docUrl": null,
      "architecture": "i386"
    },
    {
      "severity": "error",
      "code": null,
      "path": "eXist-db-5.3.0.dmg/eXist-db.app/Contents/Java/jansi-2.3.3.jar/org/fusesource/jansi/internal/native/Mac/x86_64/libjansi.jnilib",
      "message": "The binary is not signed.",
      "docUrl": null,
      "architecture": "x86_64"
    },
    {
      "severity": "error",
      "code": null,
      "path": "eXist-db-5.3.0.dmg/eXist-db.app/Contents/Java/jansi-2.3.3.jar/org/fusesource/jansi/internal/native/Mac/x86_64/libjansi.jnilib",
      "message": "The signature does not include a secure timestamp.",
      "docUrl": null,
      "architecture": "x86_64"
    },
    {
      "severity": "error",
      "code": null,
      "path": "eXist-db-5.3.0.dmg/eXist-db.app/Contents/MacOS/eXist-JavaAppLauncher",
      "message": "The executable does not have the hardened runtime enabled.",
      "docUrl": null,
      "architecture": "x86_64"
    }
  ]
}
```

**Comment by line-o** [comment]
According to @wolfgangmm we use jAnsi only to colorise terminal output at to locations in InteractiveClient 
Maybe we can figure out a way to go on without jAnsi.

**Comment by adamretter** [comment]
@line-o Cool to see that you have found that issue...

jansi was added to fix a problem that we previously had in the Java Admin Client, so I would rather not remove it.

Also, unfortunately that isn't the only native binary we need to deal with... So we will have to figure out a way to also sign, notarize native binaries regardless... unless we can persuade the upstream sources to do it for us and release updates.

**Comment by joewiz** [comment]
I see the error report mentions eXist-JavaAppLauncher - which reminded me that we're using the appbundler project for creating the macOS app bundle. I searched that project and found a few issues where people discuss code signing and notarization. Here's one - https://github.com/TheInfiniteKind/appbundler/issues/39#issuecomment-497701092 - but there may be other helpful ones, or if not, we could ask questions there?

**Comment by adamretter** [comment]
@joewiz Just thinking about whether these things should be signed upstream or not... I am not certain, if I were to publish some code which is reused in other projects but I sign my binaries, I am putting somewhat my reputation on the line for the downstream projects. Maybe it should be the responsibility of the downstream project (i.e. eXist-db) to sign all binaries that it delivers as part of its product.

Thoughts?

**Comment by line-o** [comment]
@adamretter I am not going to notarise (putting my reputation on the line) for binaries I have not inspected myself.

**Comment by adamretter** [comment]
@line-o So you are in agreement then that eXist-db must inspect and sign and notarize ever binary it ships (as opposed to upstream projects signing components)?

**Comment by line-o** [comment]
No, on the contrary - any binary not built by us, that is included in the Mac build must have been signed by the respective creator.

**Comment by adamretter** [comment]
@line-o So the upstream provider should certify their binaries even if they are used in products in an unexpected manner?

**Comment by line-o** [comment]
Do we use jansi in an unexpected manner?

**Comment by adamretter** [comment]
@line-o I don't mean "us". I mean anyone could...

**Comment by line-o** [comment]
Well our dmg and app are signed by us. I do not see that `$binary-signing-entity` will get punished just because we happen to deliver a copy of their binary packaged with our code.

**Comment by line-o** [comment]
As long as it is not the binary itself causing the harm of course.

**Comment by duncdrum** [comment]
FWIW i m with @line-o  on this one. Chain of trust means there is a chain that has more than one link. So i m in favor of signing things upstream, and have downstream ppl damage our reputation, by signing their own reputation damaging binaries which might include our righteous ones.
