### ISSUE TITLE
Possible to trigger Garbage Collect via xQuery?

### ISSUE THREAD

**Issue by karkraeg** [eXist-db/exist#3978]
Hi, 
is it possible to trigger Monex' Garbage Collection via xQuery?

Thanks!

**Comment by joewiz** [comment]
Not directly, to my knowledge. You could make an HTTP request to eXist's `/status` endpoint. This is what Monex does. The URL:

```
http://localhost:8080/exist/status?operation=gc&mbean=java.lang:type=Memory&token={$your_jmxtoken}
```

The token can be found in the eXist data directory as `jmxservlet.token` or via the `console:jmx-token()` function (only available to admin/dba users):

```xquery
xquery version "3.1";

import module namespace console="http://exist-db.org/xquery/console";

console:jmx-token()
```

**Comment by karkraeg** [comment]
Thanks! This works 👍
