### ISSUE TITLE
[Exist 2.2] - No module found matching namespace "http://exist-db.org/xquery/console"

### ISSUE THREAD

**Issue by raducoravu** [eXist-db/exist#402]
I have an XQuery like:

       <builtin-functions> {
           for $mod in util:registered-modules()
           let $functions := util:registered-functions($mod)
           order by $mod descending
           return
           <module namespace="{$mod}">
           <description>{util:get-module-info($mod)}</description>
           {
               for $f in $functions 
               return
               util:describe-function($f)
           }
           </module>
       } </builtin-functions>

which iterates all registered module namespaces and then uses "registered-functions" to get all functions for a module.
When it is run using Exist 2.2 it reports the following problem:

     exerr:ERROR No module found matching namespace URI: http://exist-db.org/xquery/console [at line 3, column 23, source: String]

It seems that registered-functions throws this exception when queried about the "http://exist-db.org/xquery/console" namespace although it is a registered module namespace.

**Comment by dizzzz** [comment]
This information is available in most modules, but I am not sure if/how it is exposed to xqueries

**Comment by wolfgangmm** [comment]
util:get-module-info and util:describe-function have been marked deprecated
