### ISSUE TITLE
Disable xinclude processing in eXide's "download app" command

### ISSUE THREAD

**Issue by awagner-mainz** [eXist-db/exist#403]
After running into this problem for the fiftieth time (or so it feels), I have again lost my xi:include statements somewhere along the download/edit/distribute/deploy path and ended up with flat (and redundant) xml files. On the eXist-db mailing list, other persons have confirmed to have run into this.

I would suggest disabling resolving/expanding XIncludes in eXide's "download app" or at least have an option to turn it off.

**Comment by dizzzz** [comment]
SHould be moved to @wolfgangmm eXide tracker https://github.com/wolfgangmm/eXide

**Comment by dizzzz** [comment]
moved to eXide bugtracker
