### ISSUE TITLE
[BUG] Negative number of hits on structure.dbx

### ISSUE THREAD

**Issue by mgraauw** [eXist-db/exist#4032]
**Describe the bug**
Possibly more a question than a bug. On one of our production machines I see a _negative_ number of hits on structure.dbx (BTree)Size: 27994 / Used: 27994 / Fails: 5691887 / Hits: -1011861852
This is not seen on our other eXist installations.

Is this within expectation? If so, how should negative hits be interpreted?
**Expected behavior**
I'd expect hits to be >= zero in all cases.

**To Reproduce**
n/a

**Screenshots**
![image](https://user-images.githubusercontent.com/6449289/132534234-d205d6eb-d282-4bd9-8422-859c9edc87bf.png)

**Context (please always complete the following information):**
 - OS:  CentOS
 - eXist-db version: 5.3.0
 - Java Version 1.8.0_202

**Comment by dizzzz** [comment]
I expect it has to do with a too large number stored in a signed variable type. I'd be interested to see the raw JMX values...

**Comment by mgraauw** [comment]
OK, that explains it, doesn't bother us really - closing
