### ISSUE TITLE
output XQuery comments

### ISSUE THREAD

**Issue by jesselet** [eXist-db/exist#404]
xquery version "3.0";
    (:for eXist 2.2:)
    <r>
        <a>1</a>(:comment:)
        <b>2</b>
        (:<c>3</c>:)
        <d>4</d>
    </r>

    (:output as follows: ----------
    <r>
        <a>1</a>
        <b>2</b>
    (:
        <c>3</c>
    :)
        <d>4</d>
    </r>
    ----------:)

**Comment by dizzzz** [comment]
confirmed, it is still there.

**Comment by shabanovd** [comment]
Funny staff here that bug is missing first comment -)
Return must be
```
<r>
    <a>1</a>(:comment:)
    <b>2</b>
    (:<c>3</c>:)
    <d>4</d>
</r>
```

**Comment by shabanovd** [comment]
Note for code update
```
{ !(inAttributeContent || inElementContent) }?
	EXPR_COMMENT
```
