### ISSUE TITLE
[BUG] faulty typechecking of `xs:boolean` err:XPTY0004 xs:integer(0)

### ISSUE THREAD

**Issue by duncdrum** [eXist-db/exist#4056]
Unless i m imagining things, `xs:boolean` should accept `true/false` and `0/1`

the function definition of `system:export`
```xquery
system:export($dir as xs:string, $incremental as xs:boolean?, $zip as xs:boolean?) as node()
```
This 
```xquery
system:export('/tmp', 0, 0) 
```
leads to
```shell
err:XPTY0004 xs:integer(0) is not a sub-type of xs:boolean [at line 3, column 23, source: String/118545130305502994]
```

same with `'0'`.

This
```xquery
system:export('/tmp', xs:boolean(0), xs:boolean(0))
```

works, but i don't think the explicit typecasting should be necessary there.                    
see #4055

**Context (please always complete the following information):**
 - OS: [docker]
 - eXist-db version: [e.g. 5.4.0-SNAPSHOT]
 - Java Version [Java8

**Additional context**
- How is eXist-db installed? [docker ]

**Comment by line-o** [comment]
The only way to allow integers to be passed to system:export is to change the signature and then do the conversion inside the function.
I would use `system:export('/tmp', false(), false())` in your case. Is that not possible?

**Comment by line-o** [comment]
That is definitely not a bug in the XQuery implementation. `xs:integer(0)` is not autocastable to xs:boolean. The specification allows literal xs:decimals to be used in functions that expect xs:integer.
Example (this is allowed)
```xquery
let $i as xs:integer := 0,
(function ($i as xs:integer) { $i })(1) 
```

**Comment by line-o** [comment]
But even for other subtypes of xs:integer like xs:positiveInteger this is not allowed. I am also not happy about this specific rule in Xquery 3.1. See also https://github.com/eXist-db/exist/issues/3330 on more details on this.

**Comment by duncdrum** [comment]
> An instance of a datatype that is defined as ·boolean· can have the following legal literals {true, false, 1, 0}. 

none of these work, boolean should accept `false` `true` `0` `1` ?
[source](https://www.w3.org/TR/xmlschema-2/#boolean)

**Comment by line-o** [comment]
That is from the XMLschema spec `true()` and `false()` work

**Comment by duncdrum** [comment]
ok i ll chuck this down as duncdrum doesn't like the specs.
