### ISSUE TITLE
Java admin client launches on different workspace in Ubuntu (unity)

### ISSUE THREAD

**Issue by gtnewton** [eXist-db/exist#406]
Launching a jnlp file (icedtea openjdk 7, 64bit Ubuntu 14.04, unity, two monitors) causes the admin client to launch on another workspace (i.e. workspace to the right instead of on the current workspace). Also, no icon is displayed for the running client, making it appear as though the client has crashed. I'm not sure if this is reproducible on a single-monitor machine.
To reproduce (from cli): 
1) javaws http://exist-db.org/webstart/exist.jnlp
2) splash screen launches on left monitor, followed by warning dialogues being launched on the right monitor. 
3) Once all dialogues are gone the screen is blank, and there is no indication that the app is running.
4) If workspaces are turned on, switch to next workspace. Admin client is running happily there.

I notice that other jnlp launchers (NASA World Wind, for example), do not do this. Is this something that can be fixed?

**Comment by adamretter** [comment]
@zwobit Could you try my patch and report if it works? It is rumoured you have a Ubuntu with dual screens ;-)

**Comment by gtnewton** [comment]
I just tried refreshing my tree and rebuilding, but I got 'Fatal: Launch Error: Could not launch JNLP file. The application has not been initialized'. I haven't tried a completely fresh pull/build/test cycle, but can if need be. I could also try against a public-facing machine running a build with your patch.

**Comment by dizzzz** [comment]
Greg, is there any trace visible? Note that the client requires Java8 since
recently....

regards

Dannes

**Comment by gtnewton** [comment]
That's probably my problem. I'm on Ubuntu 14.04 and OpenJDK 8 is not available in repos. I'll try to work around it and will respond again when I have this aspect sorted out.

**Comment by dizzzz** [comment]
You can download an rpm from oracle ?

**Comment by gtnewton** [comment]
OK. I grabbed Oracle's java 8 and ran its javaws against a fresh build of eXist. The effect was the same: the admin client launches on a separate workspace.
Question: to test the new patch, do I just do a fresh pull from github and run a build, or is it more complicated?

**Comment by dizzzz** [comment]
For webstart you also need to sign the jars; http://exist-db.org/exist/apps/doc/building.xml

**Comment by gtnewton** [comment]
OK, so I did a fresh git clone to a new directory, checked out the develop branch and ran build.sh, then build.sh jnlp-all. Turned on SSL and launched using startup.sh and then ran the oracle java 8 javaws with an htpps URL. Everything works just fine - that is, I *do* get an admin client.
The problem is that it launches on the workspace to the right, as before. There is also no indicator that there is a running application (no icon in the dock).

**Comment by adamretter** [comment]
The easiest way to get Java 8 on Ubuntu with updates is to use this ppa for
Oracle's JDK -
http://www.webupd8.org/2012/09/install-oracle-java-8-in-ubuntu-via-ppa.html

On 9 April 2015 at 16:04, Greg Newton <notifications@github.com> wrote:

> That's probably my problem. I'm on Ubuntu 14.04 and OpenJDK 8 is not
> available in repos. I'll try to work around it and will respond again when
> I have this aspect sorted out.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/eXist-db/exist/issues/406#issuecomment-91257011>.
>



-- 
Adam Retter

skype: adam.retter
tweet: adamretter
http://www.adamretter.org.uk

**Comment by adamretter** [comment]
@gtnewton The patch has not been committed yet, I was just asking @zwobit if he could apply and test it. But... as you are here, you can apply the patch to your local copy by changing the line as described here https://github.com/eXist-db/exist/issues/406#issuecomment-65797807 and then rebuilding eXist and seeing if it works for you. Let me know...

**Comment by gtnewton** [comment]
OK, I tried changing that line and re-compiled. No joy I'm afraid. Still launches on the workspace to the right.

**Comment by adamretter** [comment]
@gtnewton Okay thanks for reporting, I will try and test when I am next in the office as there is a second screen there.

**Comment by adamretter** [comment]
I am not sure we know how to fix this one. So I am closing for now, feel free to re-open if you have a solution.
