### ISSUE TITLE
[BUG] Default Namespace not changeable

### ISSUE THREAD

**Issue by StephanMa** [eXist-db/exist#4077]
**Describe the bug**
Creating an element automatically and changing the defaut namespace leads to an error

**Expected behavior**
Changing of default NameSpace

**To Reproduce**
```xquery
xquery version "3.1";

let $element := element test {
    namespace {""} {"http://test.org"}
}
return $element
```

**Screenshots**
![image](https://user-images.githubusercontent.com/6735556/140072937-f7a998db-309c-402d-a990-71fcf92bb0be.png)

**Context (please always complete the following information):**
 - OS: Ubuntu 20.04
 - eXist-db version: 5.3.0-Snapshot
 - Java Version 1.8.0_252

**Additional context**
- eXist is running via Docker
- small further changes to config (changed Port to 8182)

**Comment by joewiz** [comment]
As noted in the XQuery spec:

> Computed namespace constructors have no effect on the statically known namespaces. If the prefix a is not already defined in the statically known namespaces, the following expression results in a static error [err:XPST0081].

As your query already has a default element namespace, you cannot reassign the default namespace to a new namespace with the computed namespace constructor. 

For your query to work, you would need to define the default element namespace accordingly.

```xquery
xquery version "3.1";

declare default element namespace "http://test.org";

element test { namespace {""} {"http://test.org"} }
```

This is not unique to eXist. You'd get the same results in BaseX and Saxon.

**Comment by joewiz** [comment]
Even more relevant is this, from [3.9.4 In-scope Namespaces of a Constructed Element](https://www.w3.org/TR/xquery-31/#id-ns-nodes-on-elements):

> If the name of an element in an element constructor is in no namespace, creating a default namespace for that element using a computed namespace constructor is an error [err:XQDY0102]. For instance, the following computed constructor raises an error because the element's name is not in a namespace, but a default namespace is defined.
> 
> ```xquery
> element e { namespace {''} {'u'} }
> ```

(I found this section by searching the spec for the `XQDY0102` error code in your eXide screenshot.

**Comment by StephanMa** [comment]
Thanks
