### ISSUE TITLE
[BUG] Some nodes are "blind" along their preceding and following axes

### ISSUE THREAD

**Issue by joewiz** [eXist-db/exist#4085]
**Describe the bug**

eXist fails to locate *some* nodes along the `preceding` and `following` axes, when a document is stored in the database and when a predicate has been applied to the `for` clause of a FLWOR expression or to the LHS of a simple map operator. It's as if *certain* nodes are "blind" when looking down these axes, whereas *others* can "see" along theirs. 

In contrast, when the predicate is removed, or when an in-memory document is queried, eXist locates all nodes correctly. In these circumstances, *all* nodes have equal visibility, as expected.

This issue is present in 4.x and 5.x.

**Expected behavior**

eXist should locate all matching nodes, regardless of the presence of a predicate or the location of the queried document.

Applications sensitive to this bug include TEI applications that need to report what "page" each hit in a sequence of hits appears on, since the query must traverse the preceding axis from the hit to its first preceding `<pb>` element. Predicates are rather essential in finding hits for queries.

**To reproduce**

The XQSuite test below demonstrates the issue by altering (a) whether the document is located (a.1) in the database or (a.2) in memory, (b) whether a predicate is (b.1) used to filter the initial expression or (b.2) not, (c) whether the expression iterates over hits with (c.1) a FLWOR expression or (c.2) the simple map operator, and (d) whether the expression traverses the (d.1) `preceding` axis or (d.2) `following` axis. 

The bug arises only when factors (a.1) + (b.1) are present—i.e., when document stored in the database, and when a predicate is applied to the initial expression. 

For example, given an XML document, stored in eXist as `/db/test/test.xml`:

```xml
<root>
    <pb id="pb1"/>
    <div>
        <p>
            <w id="w1"/>
            <w id="w2"/> 
            <w id="w3"/>
        </p>
        <pb id="pb2"/>
        <p>
            <w id="w4"/> 
            <w id="w5"/>
        </p>
    </div>
    <pb id="pb3"/>
</root>
```

... a query that iterates over this document's `<w>` elements and applies any sort of filter - even a meaningless `[true()]` - and then traverses the `preceding` axis to select the element's preceding `<pb>` element, will trigger the bug. Here's an example query:

```xquery
for $w in doc("/db/test/test.xml")//w[true()]
return
    $w/preceding::pb[1]
```

| `w/@id` | expected result | actual result |
| -- | -- | -- |
| w1 | `<pb id="pb1"/>` | `<pb id="pb1"/>` |
| w2 | `<pb id="pb1"/>` | `()` |
| w3 | `<pb id="pb1"/>` | `()` |
| w4 | `<pb id="pb2"/>` | `<pb id="pb2"/>` |
| w5 | `<pb id="pb2"/>` | `()` |

The XQSuite below performs this and variations on the test—showing the bug affects not just FLWOR expressions but simple map operator expressions too, and not just the `preceding` but also the `following` axis. The corresponding failing tests are:

- `preceding-with-predicate-db-flwor`
- `preceding-with-predicate-db-map`
- `following-with-predicate-db-flwor`
- `following-with-predicate-db-map`

```xquery
xquery version "3.1";

module namespace t="http://exist-db.org/xquery/test";

declare namespace test="http://exist-db.org/xquery/xqsuite";

declare variable $t:XML := document {
<root>
    <pb id="pb1"/>
    <div>
        <p>
            <w id="w1"/>
            <w id="w2"/> 
            <w id="w3"/>
        </p>
        <pb id="pb2"/>
        <p>
            <w id="w4"/> 
            <w id="w5"/>
        </p>
    </div>
    <pb id="pb3"/>
</root>
};

declare
    %test:setUp
function t:setup() {
    let $testCol := xmldb:create-collection("/db", "test")
    return
        xmldb:store("/db/test", "test.xml", $t:XML)
};

declare
    %test:tearDown
function t:tearDown() {
    xmldb:remove("/db/test")
};

(: PRECEDING AXIS TESTS :)

declare
    %test:assertEquals("w1:pb1", "w2:pb1", "w3:pb1", "w4:pb2", "w5:pb2")
function t:preceding-with-predicate-mem-flwor() {
    for $w in $t:XML//w[true()]
    let $preceding-page := $w/preceding::pb[1]
    return
        if ($preceding-page) then
            $w/@id || ":" || $preceding-page/@id
        else
            $w/@id || ":PRECEDING_PB_NOT_FOUND"
};

declare
    %test:assertEquals("w1:pb1", "w2:pb1", "w3:pb1", "w4:pb2", "w5:pb2")
function t:preceding-with-predicate-mem-map() {
    $t:XML//w[true()] 
        ! (./@id || ":" || (./preceding::pb[1]/@id, "PRECEDING_PB_NOT_FOUND")[1])
};

declare
    %test:assertEquals("w1:pb1", "w2:pb1", "w3:pb1", "w4:pb2", "w5:pb2")
function t:preceding-with-predicate-db-flwor() {
    for $w in doc("/db/test/test.xml")//w[true()]
    let $preceding-page := $w/preceding::pb[1]
    return
        if ($preceding-page) then
            $w/@id || ":" || $preceding-page/@id
        else
            $w/@id || ":PRECEDING_PB_NOT_FOUND"
};

declare
    %test:assertEquals("w1:pb1", "w2:pb1", "w3:pb1", "w4:pb2", "w5:pb2")
function t:preceding-with-predicate-db-map() {
    doc("/db/test/test.xml")//w[true()] 
        ! (./@id || ":" || (./preceding::pb[1]/@id, "PRECEDING_PB_NOT_FOUND")[1])
};

declare
    %test:assertEquals("w1:pb1", "w2:pb1", "w3:pb1", "w4:pb2", "w5:pb2")
function t:preceding-without-predicate-flwor() {
    for $w in doc("/db/test/test.xml")//w
    let $preceding-page := $w/preceding::pb[1]
    return
        if ($preceding-page) then
            $w/@id || ":" || $preceding-page/@id
        else
            $w/@id || ":PRECEDING_PB_NOT_FOUND"
};

declare
    %test:assertEquals("w1:pb1", "w2:pb1", "w3:pb1", "w4:pb2", "w5:pb2")
function t:preceding-without-predicate-map() {
    doc("/db/test/test.xml")//w 
        ! (./@id || ":" || (./preceding::pb[1]/@id, "PRECEDING_PB_NOT_FOUND")[1])
};

(: FOLLOWING AXIS TESTS :)

declare
    %test:assertEquals("w1:pb2", "w2:pb2", "w3:pb2", "w4:pb3", "w5:pb3")
function t:following-with-predicate-mem-flwor() {
    for $w in $t:XML//w[true()]
    let $following-page := $w/following::pb[1]
    return
        if ($following-page) then
            $w/@id || ":" || $following-page/@id
        else
            $w/@id || ":FOLLOWING_PB_NOT_FOUND"
};

declare
    %test:assertEquals("w1:pb2", "w2:pb2", "w3:pb2", "w4:pb3", "w5:pb3")
function t:following-with-predicate-mem-map() {
    $t:XML//w[true()] 
        ! (./@id || ":" || (./following::pb[1]/@id, "FOLLOWING_PB_NOT_FOUND")[1])
};

declare
    %test:assertEquals("w1:pb2", "w2:pb2", "w3:pb2", "w4:pb3", "w5:pb3")
function t:following-with-predicate-db-flwor() {
    for $w in doc("/db/test/test.xml")//w[true()]
    let $following-page := $w/following::pb[1]
    return
        if ($following-page) then
            $w/@id || ":" || $following-page/@id
        else
            $w/@id || ":FOLLOWING_PB_NOT_FOUND"
};

declare
    %test:assertEquals("w1:pb2", "w2:pb2", "w3:pb2", "w4:pb3", "w5:pb3")
function t:following-with-predicate-db-map() {
    doc("/db/test/test.xml")//w[true()] 
        ! (./@id || ":" || (./following::pb[1]/@id, "FOLLOWING_PB_NOT_FOUND")[1])
};

declare
    %test:assertEquals("w1:pb2", "w2:pb2", "w3:pb2", "w4:pb3", "w5:pb3")
function t:following-without-predicate-flwor() {
    for $w in doc("/db/test/test.xml")//w
    let $following-page := $w/following::pb[1]
    return
        if ($following-page) then
            $w/@id || ":" || $following-page/@id
        else
            $w/@id || ":FOLLOWING_PB_NOT_FOUND"
};

declare
    %test:assertEquals("w1:pb2", "w2:pb2", "w3:pb2", "w4:pb3", "w5:pb3")
function t:following-without-predicate-map() {
    doc("/db/test/test.xml")//w 
        ! (./@id || ":" || (./following::pb[1]/@id, "FOLLOWING_PB_NOT_FOUND")[1])
};
```

The results of this test are as follows:

```xml
<testsuite package="http://exist-db.org/xquery/test" timestamp="2021-11-20T23:59:52.783-05:00"
    tests="12" failures="4" errors="0" pending="0" time="PT0.005S">
    <testcase name="following-with-predicate-db-flwor" class="t:following-with-predicate-db-flwor">
        <failure message="assertEquals failed." type="failure-error-code-1">w1:pb2 w2:pb2 w3:pb2
            w4:pb3 w5:pb3</failure>
        <output>w1:pb2 w2:FOLLOWING_PB_NOT_FOUND w3:FOLLOWING_PB_NOT_FOUND w4:pb3
            w5:FOLLOWING_PB_NOT_FOUND</output>
    </testcase>
    <testcase name="following-with-predicate-db-map" class="t:following-with-predicate-db-map">
        <failure message="assertEquals failed." type="failure-error-code-1">w1:pb2 w2:pb2 w3:pb2
            w4:pb3 w5:pb3</failure>
        <output>w1:pb2 w2:FOLLOWING_PB_NOT_FOUND w3:FOLLOWING_PB_NOT_FOUND w4:pb3
            w5:FOLLOWING_PB_NOT_FOUND</output>
    </testcase>
    <testcase name="following-with-predicate-mem-flwor" class="t:following-with-predicate-mem-flwor"/>
    <testcase name="following-with-predicate-mem-map" class="t:following-with-predicate-mem-map"/>
    <testcase name="following-without-predicate-flwor" class="t:following-without-predicate-flwor"/>
    <testcase name="following-without-predicate-map" class="t:following-without-predicate-map"/>
    <testcase name="preceding-with-predicate-db-flwor" class="t:preceding-with-predicate-db-flwor">
        <failure message="assertEquals failed." type="failure-error-code-1">w1:pb1 w2:pb1 w3:pb1
            w4:pb2 w5:pb2</failure>
        <output>w1:pb1 w2:PRECEDING_PB_NOT_FOUND w3:PRECEDING_PB_NOT_FOUND w4:pb2
            w5:PRECEDING_PB_NOT_FOUND</output>
    </testcase>
    <testcase name="preceding-with-predicate-db-map" class="t:preceding-with-predicate-db-map">
        <failure message="assertEquals failed." type="failure-error-code-1">w1:pb1 w2:pb1 w3:pb1
            w4:pb2 w5:pb2</failure>
        <output>w1:pb1 w2:PRECEDING_PB_NOT_FOUND w3:PRECEDING_PB_NOT_FOUND w4:pb2
            w5:PRECEDING_PB_NOT_FOUND</output>
    </testcase>
    <testcase name="preceding-with-predicate-mem-flwor" class="t:preceding-with-predicate-mem-flwor"/>
    <testcase name="preceding-with-predicate-mem-map" class="t:preceding-with-predicate-mem-map"/>
    <testcase name="preceding-without-predicate-flwor" class="t:preceding-without-predicate-flwor"/>
    <testcase name="preceding-without-predicate-map" class="t:preceding-without-predicate-map"/>
</testsuite>
```

**Related issues**

[Several issues](https://github.com/eXist-db/exist/issues?q=is%3Aissue+is%3Aopen+axis+OR+axes++) describe problems in eXist's handling of XPath axes. The most directly related ones are:

- https://github.com/eXist-db/exist/issues/1892 also demonstrates a query that returns incorrect results when the queried document is stored in the database and when the query involves a predicate, albeit a positional predicate; and it also was present in both 4.x and 5.x. However, that issue does not demonstrate the same inconsistent results within a single query. Also, that issue focused only on the `preceding-sibling` axis. This current issue did not reveal any problem with `preceding-sibling` axis; I saw no problems when traversing other axes (like `preceding-sibling`, `following-sibling`, and `ancestor`) in this test.
- https://github.com/eXist-db/exist/issues/3404#issuecomment-629079936 asserts that eXist "seems to have a problem dealing with a predicate on the `following` axis". It reports the issue is present in 5.2.0.
- https://github.com/eXist-db/exist/issues/3431 also demonstrates a query that returns incorrect results when the queried document is stored in the database and a predicate is present. However, it doesn't probe the in-memory scenario. It focuses on `preceding-sibling` and predicates. (The supplied XQSuite test needs improvement to demonstrate the effect of different factors without altering the test manually.) It reports the issue is present in 5.2.0. 
- https://github.com/eXist-db/exist/issues/3459 only addresses in-memory nodes but notes a failure with predicates not illustrated in this issue; also, that issue was not present in eXist 4.7.1 but is present in eXist 5.2.0+.
- 

**Context (please always complete the following information):**
 - OS: macOS 12.0.1
 - eXist-db version: eXist 4.7.1 and 5.4.0-SNAPSHOT b94802cdb3f1036c5ab12a69225d9bf4b272d5db 20211109062951
 - Java Version: OpenJDK 1.8.0_312 (liberica-jdk8-full 1.8.0_312-b07)

**Additional context**
- How is eXist-db installed? 4.7.1 release DMG, 5.4.0-SNAPSHOT built from source, run as Mac app
- Any custom changes in e.g. `conf.xml`? none

**Comment by joewiz** [comment]
For further context, I discovered this issue when using a tool I wrote for performing XPath on a TEI collection stored in eXist. The tool displays the serialized TEI of each hit alongside the image of the corresponding printed page in the publication where the hit appears. 

In the screenshot below, we see the example I first spotted. It shows the expected page image for the 1st hit, but the page images are unexpectedly missing for the 2nd and 3rd hits. Hit no. 1 shows the page image, because the `preceding::tei:lb` query finds its expected target. But the page image for hits nos. 2 and 3 show up blank, because `preceding::tei:lb` unexpectedly returns the empty sequence. Hit nos. 2 and 3 are "blind", but hit no. 1 "can see."

<img width="990" alt="Screen Shot 2021-11-21 at 1 12 24 AM" src="https://user-images.githubusercontent.com/59118/142751842-9555112f-7dca-4b2f-be4e-d7e805b07111.png">

**Comment by joewiz** [comment]
Based on feedback from the Community Call, we agree this is a high priority issue, because it affects all queries/applications that use these axes.

Also, I have confirmed that the results do **not** change if tests are adjusted as follows:

1. Disabling index optimizer via the ["no-index" pragma](http://exist-db.org/exist/apps/doc/xquery#pragmas).
2. Removing the `document` node from `$t:XML`
3. Moving the `[true()]` predicate outside the `for` clause by binding a variable `$ws` to `doc("/db/test/test.xml")//w[true()]` and iterating over this variable in the `for` clause.

**Comment by joewiz** [comment]
I've added a plainer description of the bug in the "To reproduce" section, containing a sample document and a query and its unexpected results.

**Comment by line-o** [comment]
I traced down the root cause of this issue.
As a workaround until this is fixed and released:
Rewrite your query using non-abbreviated form.
The example provided here
```
doc("/db/test/test.xml")//w[true()]
```
becomes
```
doc("/db/test/test.xml")/descendant-or-self::node()/w[true()]
```

In the long form the expected results are returned.
