### ISSUE TITLE
[BUG] eXist doesn't allow XQuery 3.1 empty enclosed expression {} in direct element constructor

### ISSUE THREAD

**Issue by joewiz** [eXist-db/exist#4088]
**Describe the bug**

XQuery 3.1 allows an empty enclosed expression `{}`, but eXist raises an error when an empty enclosed expression is enclosed inside a direct element constructor, e.g., `<x>{}</x>`. The error raised is:

> Cannot compile xquery: err:XPST0003 unexpected token: } (while expecting closing tag for element constructor: x) 

In contrast, no error is raised with the equivalent, expressed with a computed element constructor: `element x {}`.

**Expected behavior**

According to the definition of Enclosed Expressions in the XQuery 3.1 spec (https://www.w3.org/TR/xquery-31/#id-enclosed-expr), the EBNF form clearly labels the inner expression as optional:

```
EnclosedExpr ::= "{" Expr? "}"
```

... and:

> An enclosed expression is an instance of the `EnclosedExpr` production, which allows an optional expression within curly braces.] [Definition: In an enclosed expression, the optional expression enclosed in curly braces is called the content expression.] If the content expression is not provided explicitly, the content expression is `()`.

Saxon and BaseX both accept `<x>{}</x>`. 

**To reproduce**

```xquery
xquery version "3.1";

module namespace t="http://exist-db.org/xquery/test";

declare namespace test="http://exist-db.org/xquery/xqsuite";

declare
    %test:assertTrue
function t:test() {
    try { util:eval('exists(<x>{}</x>)') } catch * { $err:code }
};
```

(Without the try-catch block, eXist won't even compile the test.)

This test returns the following error:

```xml
<testsuite package="http://exist-db.org/xquery/test" timestamp="2021-11-25T20:26:49.656-05:00" tests="1" failures="0" errors="1" pending="0" time="PT0.002S">
    <testcase name="test" class="t:test">
        <error type="err:FORG0006" message="Invalid argument type. value of type xs:QName has no boolean value."/>
    </testcase>
</testsuite>
```

**Context (please always complete the following information):**
 - OS: macOS 12.0.1
 - eXist-db version: 5.3.0 release
 - Java Version: OpenJDK 1.8.0_312 (liberica-jdk8-full 1.8.0_312-b07)

**Additional context**
- How is eXist-db installed? DMG jar
- Any custom changes in e.g. `conf.xml`? none

**Comment by joewiz** [comment]
Here are tests adapted from QT3:

```xquery
xquery version "3.1";

module namespace ee="http://exist-db.org/xquery/test/enclosed-expressions";

declare namespace test="http://exist-db.org/xquery/xqsuite";

(:~ Enclosed expressions in element content may be empty in 3.1. Tests borrowed from QT3.
 : 
 : @see https://github.com/w3c/qt3tests/blob/44252d2496286b0bd0ca1e3b3622f369f0890557/prod/DirElemContent.xml#L1173-L1193
:)

declare
    %test:assertEquals("<elem>contentcontent</elem>")
function ee:K2-DirectConElemContent-26a() {
    <elem>content{()}content</elem>
};

declare
    %test:assertEquals("<elem>contentcontent</elem>")
function ee:K2-DirectConElemContent-26b() {
    <elem>content{(:comment:)}content</elem>
};
```

**Comment by joewiz** [comment]
The issue extends to empty enclosed expressions in direct attribute constructors:

```xquery
<x y="{}"/>
```

... raises:

> Cannot compile xquery: err:XPST0003 unexpected token: } (while expecting closing tag for element constructor: x) 

In contrast, computed attribute constructors like `attribute y {}` have no such problem.

I think the relevant section of the XQuery parser is: https://github.com/eXist-db/exist/blob/develop/exist-core/src/main/antlr/org/exist/xquery/parser/XQuery.g#L1976-L2003.

**Comment by joewiz** [comment]
@line-o reported and fixed a very similar phenomenon involving functions with empty bodies: https://github.com/eXist-db/exist/issues/3551.

**Comment by line-o** [comment]
The solution to allow empty function bodies to be parsed correctly was to explicitly check for this special case:

https://github.com/eXist-db/exist/blob/b94802cdb3f1036c5ab12a69225d9bf4b272d5db/exist-core/src/main/antlr/org/exist/xquery/parser/XQuery.g#L522-L523

**Comment by line-o** [comment]
This should also work for the two rules @joewiz pointed out.
