### ISSUE TITLE
build dist doesn't build working distribution - missing autodeploy

### ISSUE THREAD

**Issue by gtnewton** [eXist-db/exist#410]
Issue: dist creation fail (404 dashboard not found)
Process: clone, ./build.sh, ./build.sh dist
Problem: no autodeploy directory in dist result
Solution: copy autodeploy folder to dist directory
Forked and fixed by adding necessary stanza to dist.xml script
Making pull request

ps. startup.sh output complains about lib/test directory missing. Added mkdir lib/test to dist.xml.

**Comment by dizzzz** [comment]
in  'develop' I don't see the lib/test message.
