### ISSUE TITLE
Changed code signature in macOS version 5.3.1?

### ISSUE THREAD

**Issue by suschizu** [eXist-db/exist#4121]
hey @adamretter - I've received a warning that the code signature has changed from version 5.3.0 to 5.3.1

EXPECTED Juri Leino (C55AYSHE46) but FOUND Evolved Binary Ltd (33UQ8QKUAH)
download: 
https://github.com/eXist-db/exist/releases/download/eXist-5.3.1/eXist-db-5.3.1.dmg

Can you confirm this? Thanks

**Comment by adamretter** [comment]
The 5.3.1 macos package was indeed signed by Evolved Binary
