### ISSUE TITLE
Upload of directories fails

### ISSUE THREAD

**Issue by henrik-ryom** [eXist-db/exist#413]
I have a lot of xml (legacy) documents encoded in iso-8859-1, with doctype declarations and with named character entities where the encoding can't handle the character. I have a catalog which gives me the DTDs and information on how to resolve character entities. These documents are spread over many folders and subfolders.

I use the catalog in many other applications and I have updated my conf.xml so eXist is aware of the catalog.

When I upload a single document (through the client or oXygen) there is no problem resolving entities, but when I upload a directory or a list of files, eXist complains about validation errors an won't import the (some of the) documents.

Is there a difference in using the catalog here?

**Comment by henrik-ryom** [comment]
I uploaded the documents with the gui client.
It looks like, I get the errors with documents in sub-folders and subsub...-folders.

**Comment by duncdrum** [comment]
see discussion in #3062. There will be further changes to how ingest works for these cases. 
If the problem still exist please open a new issue, with some examples so we can reproduce this behaviour thanks.

**Comment by joewiz** [comment]
Closing due to lack of response to request for additional details.
