### ISSUE TITLE
[BUG][vulnerability]

### ISSUE THREAD

**Issue by sbhusala** [eXist-db/exist#4139]
**Describe the bug**
A About the recent vulnerability of log4J. We have checked the existDB jar and found the we are using Log4j-core.2.11.0 in it.
As a workaround we have removed JNDIloopup.class files from the jar and added it back.

**Expected behavior**
Could you please let us know what will be the permanent fix for it.

xquery version "3.1";
eXide version 2.4.8

**Comment by sideeffect42** [comment]
Please check out #4114 and #4125.

There is a new release eXist-db 5.3.1 which contains log4j 2.15.0 as an immediate fix.
Removing the `JNDILookup.class` can still be applied as defense in depth.

In any case, I have detected in the request logs of our installation that the log4shell vulnerability has been used to attack also eXist-db installations in the wild since at least 2021-12-10 (possibly even earlier).

It is very advisable to study your own request logs and take action if you see any signs of compromise!

**Comment by adamretter** [comment]
There is also a 4.8.0 release (should you need to stay on the 4.x.x line) that includes log4j 2.15.0

**Comment by sbhusala** [comment]
It seems 2.15.0 is also vulnerbale , could you please confirm if 

> Please check out #4114 and #4125.
> 
> There is a new release eXist-db 5.3.1 which contains log4j 2.15.0 as an immediate fix. Removing the `JNDILookup.class` can still be applied as defense in depth.
> 
> In any case, I have detected in the request logs of our installation that the log4shell vulnerability has been used to attack also eXist-db installations in the wild since at least 2021-12-10 (possibly even earlier).
> 
> It is very advisable to study your own request logs and take action if you see any signs of compromise!

It seems 2.15.0 is also vulnerable asper latest status , could you please share latest insights on this ? which version is most suitable ? by considering log4j latest jar

**Comment by sbhusala** [comment]
> There is also a 4.8.0 release (should you need to stay on the 4.x.x line) that includes log4j 2.15.0

It seems 2.15.0 is also vulnerable asper latest status , could you please share latest insights on this ? which version is most suitable ? by considering log4j latest jar

**Comment by sideeffect42** [comment]
@sbhusala Please see #4125.

As mentioned already above you can remove the JNDI lookup class from the JAR if you fear that 2.15.0 is not secure enough.

**Comment by sbhusala** [comment]
> There is also a 4.8.0 release (should you need to stay on the 4.x.x line) that includes log4j 2.15.0

Seems latest suggested version is 2.17.1 version, could you please let us know which eXist db version is having this log4j 2.17.1 version ? Thanks in advance !

**Comment by sbhusala** [comment]
Hi All,
Can you please someone suggest which is best eXist db version(which includes log4j 2.17.1 version).
TIA !

**Comment by dizzzz** [comment]
4.10.0 / 6.0.0
note that from our perspective 2.17.1 is not required to have as safe system. please check previous discussions on slack
