### ISSUE TITLE
[BUG] fn:generate-id not spec compliant

### ISSUE THREAD

**Issue by martin-honnen** [eXist-db/exist#4150]
**Describe the bug**
`generate-id()` run on nodes from different document fragments created with `parse-xml-fragment` or `parse-xml` returns the same generated id for nodes with a different node identity.

**Expected behavior**
`generate-id` is a function defined to "In other cases, the function returns a string that uniquely identifies a given node. More formally, it is guaranteed that within a single ·execution scope·, fn:codepoint-equal(fn:generate-id($N), fn:generate-id($M)) returns true if and only if ($M is $N) returns true". 

However, when I use it with eXist-db, precisely in the eXide online tool, I find that the result returned by `generate-id()` for nodes with a different identity is the same.

**To Reproduce**

```xquery
xquery version "3.1";

let $node1 := parse-xml-fragment('<node>a</node>')/node(),
    $node2 := parse-xml-fragment('<node>b</node>')/node()
return ($node1 is $node2, codepoint-equal(generate-id($node1), generate-id($node2)))
```
gives `false()
true()` in the eXide web site.

**Context (please always complete the following information):**

"Only" tested online at http://exist-db.org/exist/apps/eXide/index.html

**Comment by dnovatchev** [comment]
This is an obvious bug.

Compare with two other, correct behaviors (BaseX and Saxon) - both produce `false(), false()`

**Comment by dizzzz** [comment]
Not clear about the "eXide web site: ; the demo server is rather old AFAIR.

**Comment by adamretter** [comment]
@martin-honnen Thanks very much for reporting, I have submitted a fix here - https://github.com/eXist-db/exist/pull/4167
As soon as it gets merged, it will appear in the next Nightly Build available from - http://www.evolvedbinary.com/afterdark.html
