### ISSUE TITLE
[feature] multi-arch docker images 

### ISSUE THREAD

**Issue by duncdrum** [eXist-db/exist#4151]
to better support arm processors, such as Apple Silicon, but also in cloud. We should produce native images for each platform. While `linux/amd64, linux/arm64` are the most important native images we could potentially add more architectures, provided that there is actual demand and use cases for them. 

There are two problems preventing us from simply doing so. 
The first is that the maven plugin [#1267](https://github.com/fabric8io/docker-maven-plugin/issues/1267) doesn't support buildx.  So for maven to spit out an ARM64 image at all, it needs to run on an ARM chip. There doesn't seem to be an easy way to get our hands on one with the current CI provider. 

The second problem is the that changes to the `Dockerfile` are required. There are architecture specific paths in the builder stage. That being said, all images used by us are already available as multi-arch. 

Some more research is necessary, but as of now our options are :
1. to ditch maven as intermediary for docker on CI, and publish multi-arch images without running on actual ARM chips, 
1. switch CI provider or find a way to use GitHub Actions on ARM [for free](https://github.com/actions/virtual-environments/issues/2187) or, 
1. to replace the current  maven-plugin with an [alternative plugin](https://github.com/GoogleContainerTools/jib) that supports v2 manifest files required by buildx, 

Happy to hear thoughts and suggestions, but these are in my current order of preference based on work overall feasibility and work required.

**Comment by duncdrum** [comment]
some updates: `distroless:java` images are not published as multi-arch and there are unmerged  and closed PRs waiting for over a year to add them, so I m not going to hold my breadth.

`distroless` also moved to J11 by default, meaning the J8 images no longer receive updates :-(

However, the `distroless:base` image is multi-arch (tested) which means we can refactor the Dockerfile to add our desired  java (temurin) to it.

**Comment by adamretter** [comment]
Just in case there is any confusion, `buildx` by itself is not enough to build multi-arch images, ultimately you have the same options regardless of whether you use buildx or not. `buildx` only provides a nicer CLI for doing so, but doesn't add any magic itself. As per the Docker documentation:
```
1. Using the QEMU emulation support in the kernel (**i.e.** only suitable for building from Linux Hosts)
2. Building on multiple native nodes using the same builder instance (**i.e.** you need hardware)
3. Using a stage in Dockerfile to cross-compile to different architectures
```

**Comment by duncdrum** [comment]
Yup no confusion. Qemu + buildx will give multi Linux arch. If we also want win, we need to spin up a win instance on top of that on ci.
