### ISSUE TITLE
does this need to be there ?

### ISSUE THREAD

**Issue by duncdrum** [eXist-db/exist#4153]
https://github.com/eXist-db/exist/blob/ca91ad0d237f3b5d7963dbc54d0d4388fc7a1ebd/exist-docker/pom.xml#L188

**Comment by joewiz** [comment]
I think it was a typo. Tracing via blame: 

- an extra `>` sign was introduced in https://github.com/eXist-db/exist/commit/364eadbca35631025487ce635d1be6349718f425
- the `>` was changed into `&gt;` here: https://github.com/eXist-db/exist/commit/1533551563661d2c2061d3ed1304cb257f216327#diff-5bb29ec9c8c46d69e66924b2d5582ff8d4acf6dd0ca9b1034fe00c0cc31bbed0L162-R163

Neither addition interferes with the file's well-formedness, and it still conforms to the POM XSD (maven-4.0.0.xsd), so it's harmless, but... I'd guess it's probably best to remove it.
