### ISSUE TITLE
Memory leak in Java Service Wrapper

### ISSUE THREAD

**Issue by adamretter** [eXist-db/exist#429]
As reported by Casey Jordan [(background is here)](http://markmail.org/thread/y2qre26tdqu62hqm):

Just wanted to give everyone a heads up that Java service wrapper versions 3.5.25 and below (Which is used by eXist) is subject to a fairly serious memory leak on Linux systems with glibc 2.17.x and lower. 

This is mainly just Debian based distros like CentOS. 

To fix, you can upgrade glibc (Which is usually not possible without upgrading the entire kernel) or upgrade to wrapper v3.5.26

**Comment by adamretter** [comment]
http://static.adamretter.org.uk/wrapper-patched/

**Comment by adamretter** [comment]
Should we replace the wrapper in eXist with my 3.2.56 patched version?

**Comment by dizzzz** [comment]
replacing would be ok for me (check sizes, remove symbols if required) but.... if an new wrapper version comes out, without this fix, i'll not spend too much time in re-applying and testing the patched version. IMO we should not do that....

**Comment by shabanovd** [comment]
Did you mean "we should not update if new version do not have the fix"?

**Comment by dizzzz** [comment]
I really don't like the idea to be forced to hold back improvements because ppl cannot/do not want to update highly recommended (security) updates on their system. And... We should not have the ownership of a well-maintained 3rd party software

**Comment by shabanovd** [comment]
So you recomend to crash by OOM, right?

**Comment by dizzzz** [comment]
no, i recommend ppl to keep their system patched

**Comment by adamretter** [comment]
Closed by https://github.com/eXist-db/exist/commit/ea34a8004a3a13f1440411f9ae10acb2e9c07b1f
