### ISSUE TITLE
[BUG] fn:xml-to-json() adds precision to integer

### ISSUE THREAD

**Issue by ahenket** [eXist-db/exist#4304]
**Describe the bug**
When you use `fn:xml-to-json()` you expect a number to come out with the same precision as it went in. However, eXist-db adds .0 to integers making them a decimal or real instead of an integer. When you run the same code below outside of eXist-db using Saxon, it gives back the expected result.

**Expected behavior**
Looking at https://www.w3.org/TR/xpath-functions-31/#func-xml-to-json I see:
> An element $E named number results in the output of the string result of xs:string(xs:double(fn:string($E)))

The output of `xs:string(xs:double(fn:string(0)))` yields 0, not 0.0

**To Reproduce**
```xquery
xml-to-json(
  <map xmlns="http://www.w3.org/2005/xpath-functions">
    <number key="integer">0</number>
  </map>
)
```

yields:
```json
{ "integer": 0.0 }
```

expected:
```json
{ "integer": 0 }
```

**Context (please always complete the following information):**
 - OS: macOS 12.2.1
 - eXist-db version: 6.0.1
 - java version "15.0.2" 2021-01-19

**Additional context**
- n/a

**Comment by joewiz** [comment]
Could you also test Saxon and BaseX?

**Comment by ahenket** [comment]
I did Saxon and that behaves as expected. I have no access to BaseX. Tried to work with it and failed.

Additional note:
Upon converting json back into xml, the 0.0 is turned back into 0, which seems to suggest rounding which is as much of a no-no as adding precision. However that at least seems within spec.

**Comment by joewiz** [comment]
BaseX also returns the expected value. (On macOS, install BaseX via `brew install basex` and start the GUI via `basexgui`.)

**Comment by joewiz** [comment]
@ahenket Would you be able to post an xqsuite test?

**Comment by ahenket** [comment]
Any place I can catch up on howto? I'm sure I could with a little pointer.

**Comment by joewiz** [comment]
@ahenket Sure! Here are some pointers. Besides the docs at https://exist-db.org/exist/apps/doc/xqsuite, there are lots of good examples in recent issues; for example, https://github.com/eXist-db/exist/issues/4252. To execute the XQSuite and see the results, save the query to the database and (a) in eXide select XQuery > Run as Test or (b) adapt this query to point to your module:

```xquery
xquery version "3.1";

import module namespace test="http://exist-db.org/xquery/xqsuite" at "resource:org/exist/xquery/lib/xqsuite/xqsuite.xql";

test:suite(
    inspect:module-functions(xs:anyURI("/db/test.xqm"))
)
```

**Comment by ahenket** [comment]
I'm not much of a Java coder and really unfamiliar with the source code, but ... this seems like an easy fix in [exist/FunXmlToJson.java](https://github.com/eXist-db/exist/blob/5bc6a35fd6d4a91742637aefe4ad53c2324284ee/exist-core/src/main/java/org/exist/xquery/functions/fn/FunXmlToJson.java#L182)

Current code
```java
final double tempDouble = Double.parseDouble(tempString);
jsonGenerator.writeNumber(tempDouble);
```

Suggested update:
```java
if (tempString.contains(".")) {
    final double tempDouble = Double.parseDouble(tempString);
    jsonGenerator.writeNumber(tempDouble);
}
else {
    final int tempInt = Integer.parseInt(tempString);
    jsonGenerator.writeNumber(tempInt);
}
```
