### ISSUE TITLE
[BUG] file:sync() returns <update/> elements for all files synced

### ISSUE THREAD

**Issue by domlatham** [eXist-db/exist#4321]
**Describe the bug**
`file:sync()` returns `<update/>` elements for all files synced.

**Expected behavior**
Previously (5.3.0) it would return `<update/>` elements only for files that had changed. 
My code evaluates this output to determine if there were changes and then do subsequent tasks.

**To Reproduce**
Call `file:sync('/db/file-module-test','/home/existdb/exist-sync/test-sync',())` twice and the result will be the same even though no updates have happened in the meantime.

**Comment by line-o** [comment]
Could you include the actual call to `file:sync`?

**Comment by domlatham** [comment]
I've updated the opening description

**Comment by line-o** [comment]
Thanks!
Looking at the code I can see:
a) the test is too complex
b) might have introduced this regression

I will create a test to prove your observation and then simplify the if-statement for future maintainers :)

Thanks for reporting this.

**Comment by line-o** [comment]
https://github.com/eXist-db/exist/blob/0998501dc3a36491dc05ceddf7c91fa25452e6f0/extensions/modules/file/src/main/java/org/exist/xquery/modules/file/Sync.java#L375-L379

**Comment by line-o** [comment]
So I managed to get to a point that looked very promising both in readability of the code and the logic.
The test I created is still failing though. After debugging this it turns out that 

`Files.getLastModifiedTime(targetFile)` does not take the target system timezone into account.
This way all files on the disk appear to be older all the time. :/

**Comment by line-o** [comment]
Scrap what I just wrote in the previous comment. The test to run the file:sync operation twice still fails is actually a result of the combination of the Java runtime and OSX. `Files.getLastModifiedTime()` will only return full seconds with this combination (see https://bugs.java.com/bugdatabase/view_bug.do?bug_id=8177809).
