### ISSUE TITLE
[BUG] Some files are not restored from backup starting with version 5.4.0 up to the latest

### ISSUE THREAD

**Issue by cwittern** [eXist-db/exist#4368]
**Describe the bug**

From a complete backup from the same or an earlier version of eXist, some files are not restored.  They seem to be parsed as XML, although they were stored and marked as "BinaryRessource" during the backup process.  The problem shows with certain types of files, including HTML5.  The attached backup file (created with version 5.4.0) demonstrates the problem - [eXist-backup.zip](https://github.com/eXist-db/exist/files/8600979/eXist-backup.zip)

This problem has been discussed in the Slack channel: https://app.slack.com/client/TG47XS7E2/CG2MRUZ35/thread/CG2MRUZ35-1651390531.411839

**Expected behavior**

I expect these files to be processed in a way that makes them function identical to the situation before the backup/restore process

**To Reproduce**

1. copy the attached backup file into  $PWD/backup
2. Run the following sequence of commands shows the problem:
```
#!/bin/sh
NAM=res-$(date +%Y-%m-%d-%H-%M)
#IMG=existdb/existdb:latest
IMG=existdb/existdb:5.4.0
CWD=$(pwd)
BKF=$(ls $CWD/backup/)
docker run -it -d -p 8080:8080 -p 8443:8443 -v $CWD/backup:/opt/backup --name $NAM $IMG
#docker run -it -d -p 8080:8080 -p 8443:8443 -v $CWD/etc:/exist/etc -v $CWD/backup:/opt/backup --name $NAM $IMG
sleep 60s
docker exec $NAM java org.exist.start.Main client --no-gui -u admin  --xpath "system:restore('/opt/backup/$BKF', '', '')"
```
4. The backup contains a collection with one file "/db/temp/dependencies.html"  (this file is part of the dashboard, it is here used to demonstrate the problem).  With the image variable above set to 5.3.1 the backup is successful, but with 5.4.0 and later it fails with the error message:
```
<system:restore xmlns:system="http://exist-db.org/xquery/system">
<system:info>Starting restore of backup...</system:info>
<system:info>Processing backup: /opt/backup/eXist-backup.zip#db/temp/__contents__.xml</system:info>
<system:collection>/db/temp</system:collection><system:warn>Failed to restore resource 'dependencies.html'
from file '/opt/backup/eXist-backup.zip#db/temp/dependencies.html'.
Reason: The XML parser reported a problem: fatal error at (1,2045) : The element type "link" must be terminated by the matching end-tag "&lt;/link&gt;".</system:warn>
<system:info>Finished restore of backup.</system:info>
</system:restore>

```

**Context (please always complete the following information):**
 - OS: the above docker is running on Ubuntu 20.04, but the problem has also be verified with 5.4.0 running directly on Ubuntu 20.04
 - eXist-db version: tested various versions as they are contained in the docker images: 5.3.1, 5.4.0, 6.0.0 and "latest" 
 - Java Version:   Java 1.8.0_275 [Oracle Corporation (OpenJDK 64-Bit Server VM) in /usr/lib/jvm/java-8-openjdk-amd64/jre

**Additional context**
- How is eXist-db installed? docker image
- Any custom changes in e.g. `conf.xml`?  no changes

**Comment by dizzzz** [comment]
<img width="724" alt="image" src="https://user-images.githubusercontent.com/1700062/166301382-ef0cb4dc-f6bc-4150-9ae5-27f7e58d4cd2.png">
with regular GUI restore

**Comment by dizzzz** [comment]
<img width="707" alt="image" src="https://user-images.githubusercontent.com/1700062/166303121-09b67241-23a4-4f0d-aaa1-ca55d18eb76a.png">
not reproduced with v5.3
