### ISSUE TITLE
Coding of path components in URIs

### ISSUE THREAD

**Issue by hungerburg** [eXist-db/exist#44]
This is a port of SF ticket http://sourceforge.net/p/exist/bugs/766/ - for short:

In a few places the eXist codebase uses "java.net.URLDecoder" (which is intended to be used on http _query strings_) instead of "java.net.URI", resulting in wrong coding of _path components_ in URIs and thereby creation of ressources, that cannot be fetched by the name, they were uploaded with.

Simplest way to show the (mis)behaviour:
- From the dashboard start collections browser,
- create collection "/db/testing",
- upload a ressource, eg. "A+A.svg"
- note that it gets represented as "A%2BA.svg" in the list widget,
- which is the same as displayed in "/exist/rest/db/testing/",
- and also in "/exist/webdav/db/testing/", while
- in eXide open dialog it will show up as "A+A.svg".

BUT
- fetching /exist/rest/db/testing/A%2BA.svg will result in a 404,
- same as /exist/rest/db/testing/A+A.svg,
- while fetching /exist/rest/db/testing/A%252BA.svg will work,
- same as /exist/webdav/db/testing/A%252BA.svg,
- all the while the file is inaccessible from eXide's "open", but
- double clicking in coll.browser will fire up eXide to "A%2BA.svg".

That is: there is **double encoding** happening. The plus sign is encoded to %2B on store, and the newly introduced percent sign has to be coded to %25 on retrieve. This applies to all the characters, that java.net.URLDecoder codes different from java.net.URI in path components (most prominently the plus sign, but also others).

**Comment by joewiz** [comment]
Is this not closed by #605?

**Comment by hungerburg** [comment]
Fixed by #605 , I can close
