### ISSUE TITLE
Invalid predicate optimisation when calling function by reference

### ISSUE THREAD

**Issue by adamretter** [eXist-db/exist#4412]
The following query incorrectly raises an error as it tries to send the entire sequence `("a", "b", "c")` into the argument `$y`:

```xquery
let $predicate := function($x as xs:string, $y as xs:string) as xs:boolean { $x eq $y }
return
	("a", "b", "c")[$predicate("b", .)]
```

Yielding the error:
```
An exception occurred during query execution: exerr:ERROR XPTY0004: The actual cardinality for parameter 2 does not match the cardinality declared in the function's signature: ($x as xs:string, $y as xs:string) xs:boolean. Expected cardinality: exactly one, got 3.
```

This query also fails due to the same cause:
```xquery
declare function local:pred($x as xs:string, $y as xs:string) as xs:boolean {
	$x eq $y
};

let $predicate := local:pred#2
return
	("a", "b", "c")[$predicate("b", .)]
```

Yielding the error:
```
An exception occurred during query execution: exerr:ERROR XPTY0004: The actual cardinality for parameter 2 does not match the cardinality declared in the function's signature: local:pred($x as xs:string, $y as xs:string) xs:boolean. Expected cardinality: exactly one, got 3.
```

The problem can be simplified to just:
```xquery
("a", "b", "c")[function($x as xs:string, $y as xs:string) as xs:boolean { $x eq $y }("b", .)]
```
Also yielding the error:
```
The actual cardinality for parameter 2 does not match the cardinality declared in the function's signature: ($x as xs:string, $y as xs:string) xs:boolean. Expected cardinality: exactly one, got 3
```

---
The following query which uses a function call as opposed to calling a function reference does work as expected:
```xquery
declare function local:pred($x as xs:string, $y as xs:string) as xs:boolean {
	$x eq $y
};

("a", "b", "c")[local:pred("b", .)]
```
Yielding the result `b`.

----
The problem is present in at least eXist-db `4.11.0-SNAPSHOT` through to `6.1.0-SNAPSHOT`.

I suspect this is another predicate optimisation issue, whereby it is attempting to incorrectly optimise the call to the Function Reference.

**Comment by adamretter** [comment]
As suspected, for a Function Reference, within the predicate it fails to detect the dependency on the Context Item and attempts a "positional promotion" here - https://github.com/eXist-db/exist/blob/develop/exist-core/src/main/java/org/exist/xquery/Predicate.java#L235

**Comment by joewiz** [comment]
This appears to have been introduced here https://github.com/eXist-db/exist/commit/7737139b3b327f5cb50c0ef5c64c3ad7b85b8450

The commit message notes:

> there is a regression in the XQTS for: `(0, 1, 2)[remove((1, "a string"), 2)]`

**Comment by adamretter** [comment]
@joewiz Hmm I am not certain, as the commit message seems to indicate an issue with FunctionCall (which does work at present) rather than FunctionReference. So I guess the FunctionCall issue was fixed after that. Also at that time, it is unlikely that eXist-db had FunctionReference in the form it has now, as they were introduced in XQuery 3.0.
