### ISSUE TITLE
[BUG] java.math.BigDecimal thorws exception when used as variable

### ISSUE THREAD

**Issue by dalcorta** [eXist-db/exist#4413]
**Describe the bug**

BigDecimal cannot be used in XML:DB API when setting a BigDecimal to a variable.

**Expected behavior**
java.math.BigDecimal should be cast to xs:decimal

**To Reproduce**
I have the following code:

```java
 XQueryService xqs = (XQueryService) collection.getService("XQueryService", "1.0");
 xqs.declareVariable("price", new BigDecimal(5770));
 
 CompiledExpression compiled = xqs.compile("xquery version \"3.1\"; for $item in collection()/Order "
				+ "where $item[@Px = $price] and $item/OrdQty[@Qty != 0] return $item");
```

It can't be compiled becouse an exception is thrown.
Caused by: org.exist.xquery.XPathException: err:FORG0001 cannot cast 'xs:anyAtomicType("5770")' to object [at line 1, column 81]
	at org.exist.xquery.value.UntypedAtomicValue.convertTo(UntypedAtomicValue.java:131) ~[exist-core-6.0.1.jar:6.0.1]
	at org.exist.xquery.value.UntypedAtomicValue.convertTo(UntypedAtomicValue.java:158) ~[exist-core-6.0.1.jar:6.0.1]

**Context (please always complete the following information):**
 - OS: Linux Mint 20.3
 - eXist-db version: 6.0.1
 - Java Version OpenJDK 64-Bit Server VM AdoptOpenJDK-11.0.11+9 (build 11.0.11+9, mixed mode)

**Additional context**
- How is eXist-db installed? JAR
- Any custom changes in e.g. `conf.xml`? No

**Comment by adamretter** [comment]
This is handled by `org.exist.xquery.XPathUtil.javaObjectToXPath(Object, XQueryContext, boolean)` so we would need to add a mapping in there.

@reinhapa I am wondering if the XML:DB Module should provide some "official" guidance on mapping Java Types into XDM Types. What do you think?
