### ISSUE TITLE
functx info warning at each eXist-db Startup

### ISSUE THREAD

**Issue by pcolot01** [eXist-db/exist#442]
During each eXist-db startup including the library functx, the following line is displayed : 

INFO: Warning: package uses old-style content dir: 'c:\eXist-db2.2\webapp\WEB-INF\data\expathrepo\functx-1.0\functx'

The error is very simple to correct. The new libraries expect to find the content collection in place of the functx collection in the package.

Could you correct the package deployed on http://demo.exist-db.org/exist/apps/public-repo ?

Could you document where is the corresponding GIT repository ?

Best regards

**Comment by duncdrum** [comment]
A lot of things have changed since 2.2 if this is still an issue, please open a new issue. Thx.
