### ISSUE TITLE
calling normalize-unicode() has no effect

### ISSUE THREAD

**Issue by jensopetersen** [eXist-db/exist#443]
normalize-unicode() does nothing, no matter which normalization form one asks for.

See http://markmail.org/thread/szmulgolc3fkisob.

This influences searchability. Test case:

```xml
	<collection xmlns="http://exist-db.org/collection-config/1.0" xmlns:xs="http://www.w3.org/2001/XMLSchema">
		<index>
			<lucene>
				<analyzer class="org.apache.lucene.analysis.standard.StandardAnalyzer"/>
				<text qname="word"/>
				<text qname="lucene"/>
			</lucene>
			<range>
				<create qname="range-us-collation" type="xs:string" collation="?lang=en-US&amp;strength=primary"/>
				<create qname="range-no-collation" type="xs:string"/>
			</range>
			<ngram qname="ngram"/>
		</index>
	</collection>
```
#
```xml
	<text>
		<lucene>&#x00C5;&#x0073;&#x0074;&#x0072;&#x00F6;&#x006D;</lucene>
		<ngram>&#x00C5;&#x0073;&#x0074;&#x0072;&#x00F6;&#x006D;</ngram>
		<range-us-collation>&#x00C5;&#x0073;&#x0074;&#x0072;&#x00F6;&#x006D;</range-us-collation>
		<range-no-collation>&#x00C5;&#x0073;&#x0074;&#x0072;&#x00F6;&#x006D;</range-no-collation>
	</text>
```
#
```xquery
	xquery version "3.0";
	
	let $doc := doc('/db/test/norm.xml')
	let $composed := '&#x00C5;&#x0073;&#x0074;&#x0072;&#x00F6;&#x006D;'
	let $decomposed := '&#x0041;&#x030A;&#x0073;&#x0074;&#x0072;&#x006F;&#x0308;&#x006D;'
	return 
		<results>
			<ngram>
				<composed>{$doc//ngram[ngram:contains(., $composed)]}</composed>
				<decomposed>{$doc//ngram[ngram:contains(., $decomposed)]}</decomposed>
			</ngram>
			<lucene>
				<composed>{$doc//lucene[ft:query(., $composed)]}</composed>
				<decomposed>{$doc//lucene[ft:query(., $decomposed)]}</decomposed>
			</lucene>
			<range-us-collation>
				<composed>{$doc//range-us-collation[. eq $composed]}</composed>
				<decomposed>{$doc//range-us-collation[. eq $decomposed]}</decomposed>
			</range-us-collation>
			<range-no-collation>
				<composed>{$doc//range-no-collation[. eq $composed]}</composed>
				<decomposed>{$doc//range-no-collation[. eq $decomposed]}</decomposed>
			</range-no-collation>
		</results>
```

**Comment by dizzzz** [comment]
hmm  not sure it is related, but did you install the icu4j library ?

**Comment by jensopetersen** [comment]
Sure.

**Comment by wolfgangmm** [comment]
I fixed normalize-unicode to behave as expected.

Concerning indexing: as I understand it, you would suggest that eXist should always normalize strings to NFC form before putting them into the index (unless an explicit collation is given)? Is that right?

**Comment by jensopetersen** [comment]
Thanks a lot! 

I think the standard approach would be to NFC-normalize when exchanging documents, because this brings backwards compatibility with non-Unicode operating systems and apps (I don't think this is all that important any more), but to NFD-normalize when searching, since this makes certain grep searches simpler, but the most important thing is to apply one NF and know which one it is, since then search input can be subjected to the same NF. 

Collation applies to how strings sort and in theory this applies no matter which NF is used, It is unclear to me whether ICU applies a certain NF when normalization is turned on for collation (it makes little sense to say that normalization can be turned on or off <http://userguide.icu-project.org/collation/concepts#TOC-Normalization> when it can be turned on in four different ways). 

Probably normalization has to be applied before collation when indexing. 

Why not give the user the option of applying one of the four NF in the collection.xconf? And if the NF is left undefined, then perhaps use NFC as default (since most input will probably be NFC)? 

There still are some apps which have problems rendering decomposed characters. I seem to remember that they looked bad in Firefox.

**Comment by jensopetersen** [comment]
Oh, I see you are not using ICU for unicode-normalization ….
