### ISSUE TITLE
asm java library prevents ExistDB from starting

### ISSUE THREAD

**Issue by mdekleine** [eXist-db/exist#444]
We are using a java component called Parboiled (https://github.com/sirthias/parboiled/wiki) to analyze and construct xml files from text files. This component itself uses ASM 4.0 (http://asm.ow2.org/).  When I place the jar file (asm-all-4.0.jar) file in the /lib/user map, then the ExistDb refuses to start and reports an error in the event log ; 
"The eXist-db Native XML Database service terminated with the following service-specific error: 
Incorrect function." 

Parboiled itself comes with 2 .jar files, which placed in the /lib/user map doesn't make a difference; the service still won't start.

Setup: 
- Windows 8.1, 64 bit,  (= development machine)
- Oracle ExistDB v2.2 rev 5c5aadc.
- java version "1.7.0_65"
- Java(TM) SE Runtime Environment (build 1.7.0_65-b20)
- Java HotSpot(TM) 64-Bit Server VM (build 24.65-b04, mixed mode)
We made some changes to memory usage and have in conf.xml the setting for <xquery enable-java-binding="yes"> Setting this to 'no' doesn't resolve the issue. We have installed ExistDB to start as a service. Exist-db is installed in the map d:\exist-db

We previously were running v2.1, rev18721 and the ExistDB service could be started without any problem

Any thoughts how to solve this? I cannot find any log file with more detailed information other than the previously mentioned event log entry.

thanks

**Comment by dizzzz** [comment]
the ASM lib has been causing some issues in the past, e.g.

- https://github.com/eXist-db/exist/pull/247
- https://github.com/eXist-db/exist/pull/242

I guess the conflict is caused by the already existing asm.jar provided by jetty:

https://github.com/eXist-db/exist/tree/develop/tools/jetty/lib


*maybe* it helps removing the jetty version (set aside).

**Comment by mdekleine** [comment]
Thanks for the suggestion (hmm, i could have searched myself...)
unfortunately moving the jetty version doesn't help; when moved eXist-db doesn't even start. Moving the asm-all.4.0.jar in the Jetty lib also isn't working.

**Comment by dizzzz** [comment]
moving = removing?

**Comment by mdekleine** [comment]
I made an 'archive' map and moved the org.objectweb.asm-3.1.0.v200803061910.jar file into that map.

**Comment by dizzzz** [comment]
if moving out does not help, I have no solution for you :-( Does de ASML project indicate incompatibilities or workarounds?

**Comment by dizzzz** [comment]
Is it fixed for you right now? It must be something specific on your system

**Comment by mdekleine** [comment]
It is not fixed. We didn't have the knowledge and resources to investigate this any further and will continue using 2.1 which does it's job pretty good. The actual solution will probably be to remove the actual routine and move it outside the exist-db space; then we definitely will upgrade to get all the benefits of the newer version.
