### ISSUE TITLE
Add support for SequenceTypeUnions in typeswitch case expressions

### ISSUE THREAD

**Issue by joewiz** [eXist-db/exist#445]
In the XQuery 3 spec, [typeswitch case clauses](http://www.w3.org/TR/xquery-30/#id-typeswitch) can contain union operators (or more properly, can contain [SequenceTypeUnions](http://www.w3.org/TR/xquery-30/#doc-xquery30-SequenceTypeUnion)).  Here is an example adapted from the spec:

```xquery
xquery version "3.0";

let $customer := <customer/>
return
typeswitch($customer/billing-address)
   case $a as element(*, USAddress)
            | element(*, AustraliaAddress)
            | element(*, MexicoAddress)
     return $a/state
   case $a as element(*, CanadaAddress)
     return $a/province
   case $a as element(*, JapanAddress)
     return $a/prefecture
   default
     return "unknown"
```

In eXide, this triggers the following error:

    error found while executing expression: org.exist.xquery.XPathException: err:XPST0003 expecting "return", found '|' [at line 7, column 13]

(Line 7 is the line with ` | element(*, AustraliaAddress)`.)

Please add support for SequenceTypeUnions in typeswitch case expressions.  Thanks!

**Comment by dizzzz** [comment]
I guess it is fixed.
