### ISSUE TITLE
[BUG] local-name is invoked when it shouldn't be 

### ISSUE THREAD

**Issue by PieterLamers** [eXist-db/exist#4466]
**Describe the bug**
with
```xquery
let $test as element(a):= 
  <a>
    <b></b>
  </a>
  
return $test/c/local-name()
```
`local-name#1` is invoked returning an empty string.

**Expected behavior**
empty-sequence() should be returned, similar to a call to `$test/c/string()`

**Context (please always complete the following information):**
 - OS: Windows, Linux
 - eXist-db version: 6.0.1
 - Java Version Java 8

Cf discussion on Slack: https://xmlcom.slack.com/archives/C011NLXE4DU/p1656648721760709

**Comment by joewiz** [comment]
In the linked xml.com Slack thread, Michael Kay confirmed:

> For the expression X/Y, if X is an empty sequence, then Y doesn't get evaluated and the result is empty.
