### ISSUE TITLE
Request for feedback: “Community Code Review and Merge Policy for the exist-db/exist Git Repository”

### ISSUE THREAD

**Issue by dariok** [eXist-db/exist#4479]
At the latest Community Call (Monday, July 11th 2022), we considered a proposal put forward to revise the “Community Code Review and Merge Policy
for the exist-db/exist Git Repository”.

Typically on a day-by-day basis the exist-db/exist repository has a volunteer team of between 1 to 4 people who are able to review and merge PRs (Pull Requests). We are very grateful to those volunteers who perform this involved work on a best effort basis in their spare time. Fortunately there is an increasing number of contributions to the project, but unfortunately this is outpacing the ability of our volunteers. We have 50+ open PRs at this moment!

The new policy proposal can be found at https://docs.google.com/document/d/1Y-f8P-p0VW6cmJSQrfGp4786qsMNW51qMp8h4Fh76-Y/edit?usp=sharing

Whilst this mostly concerns those directly contributing to the eXist-db Database Java Code Base, should you feel strongly about the topic, then we welcome your constructive feedback on the proposal. Should you feel uncomfortable with some aspect of the proposed policy, please make an alternative suggestion for that aspect.

All feedback must be submitted by Saturday, 16th July 2022 at 00:00 UTC. Feedback will be collated by Dario Kampkaspar and should be emailed to: dario.kampkaspar@tu-darmstadt.de

For reference a copy of this announcement can be found here: https://docs.google.com/document/d/1XSs4naogq0v8ah4fs319hTVMxsu34BBZJKaeyyAsFoE/edit?usp=sharing

**Comment by dariok** [comment]
I kindly request that all thoughts be send to me by email as stated above and not as a comment to this issue.

**Comment by dizzzz** [comment]
Please note -very very important- a lot of PRs are either marked draft or for exist v7

For the drafts: this is an author responsibility to ask ppl for help

For the v7: this can be solved by either heading to v7 asap or have a future release branch right now

My 2 CT's
