### ISSUE TITLE
[BUG] build failing on develop-4.x.x

### ISSUE THREAD

**Issue by mcmeeking** [eXist-db/exist#4492]
> To be able to better understand you problem, please add as much information as possible to this ticket. Always test your bugs against the latest stable release of exist. We cannot provide support for older versions here on GitHub. If the version of eXist that is experiencing the issue is more than 1 major version behind the most recent release, please consider posting a question on our mailing list. 

**Describe the bug**
Building exist with the `./build.sh` script throws a fatal error:

```
[echo] Compiling with Java 1.8 from 1.8 source to 1.8 target, debug on, optimize on, deprecation off
[javac] Compiling 5 source files to /tmp/existdb-src/exist-start/target/classes
[javac] Note: /tmp/existdb-src/exist-start/src/main/java/org/exist/start/Main.java uses unchecked or unsafe operations.
[javac] Note: Recompile with -Xlint:unchecked for details.
[javac] Compiling 1569 source files to /tmp/existdb-src/exist-core/target/classes
[javac] /tmp/existdb-src/exist-core/src/main/java/org/exist/client/QueryDialog.java:585: error: cannot find symbol
[javac]                     throw new XMLDBException(ErrorCodes.UNKNOWN_ERROR, "Query returned 'null' which it should never do, this is likely a bug that should be reported");
[javac]                                              ^
[javac]   symbol:   variable ErrorCodes
[javac]   location: class QueryDialog.QueryRunnable
[javac] Note: Some input files use or override a deprecated API.
[javac] Note: Recompile with -Xlint:deprecation for details.
[javac] Note: Some input files use unchecked or unsafe operations.
[javac] Note: Recompile with -Xlint:unchecked for details.
[javac] 1 error
```

**Expected behavior**
Build with the `./build.sh` should succeed.

**To Reproduce**
Run the `./build.sh` script in the latest `develop-4.x.x` branch

**Context (please always complete the following information):**
 - OS: macOS 12.4
 - eXist-db version: latest `develop-4.x.x` branch
 - Java Version openjdk@8 1.8.0_322

**Comment by dizzzz** [comment]
Thnx for your contribution!

I wonder why we (I) did not see this before :-(

**Comment by mcmeeking** [comment]
No worries, thanks for merging so quickly!
