### ISSUE TITLE
[BUG] Unable to navigate ancestor axis to document node

### ISSUE THREAD

**Issue by yamahito** [eXist-db/exist#4546]
**Describe the bug**
When working with a sequence of nodes returned by collection(), the document-node() is absent from the ancestor axis.

**Expected behavior**
Expected behaviour is to be able to access the ancestor document node.

**To Reproduce**

Create two functions in a module:

```Xquery
module namespace mod1 = "http://mod1";

declare function mod1:doc-node($node as node()) as document-node() {
    $node => document-uri() => doc()
};

declare function mod1:doc-node2($node as node()) as document-node() {
    $node/ancestor-or-self::document-node()
};
```

and call each of the functions for an element in the database:

```xquery
import module namespace mod1="http://mod1" at "/db/mod1.xqm";

collection($some-collection)[1] => mod1:doc-node(),
collection($some-collection)[1] => mod1:doc-node2()

```

The first function runs successfully.
The second will fail with a type error as the empty sequence is returned rather than the required document node.

**Context (please always complete the following information):**
 - OS: ubuntu
 - eXist-db version: 6.10-SNAPSHOT

**Additional context**
- How is eXist-db installed? existdb/existdb:latest docker image

**Comment by adamretter** [comment]
I think this can be simplified down to some one line expressions, by removing the functions and arrow operators we can reduce the complexity. I have stripped this back to the following test-cases:

1. Should return an empty result (works correctly):
```xquery
collection("/db")[1]/document-node()
```

2. Should return a non-empty result (works correctly):
```xquery
collection("/db")[1]/doc(document-uri(.))
```

3. Should return a non-empty result (works correctly):
```xquery
collection("/db")[1]/self::document-node()
```

4. Should return a non-empty result (**Fails**):
```xquery
collection("/db")[1]/ancestor-or-self::document-node()
```

@yamahito So if I have capture your test correctly and isolated it, then I think the problem lies solely with the `ancestor-or-self` Path Step.

**Comment by adamretter** [comment]
@yamahito I also found more based on your original enquiry in slack.

Aloo if these require `declare namespace config = "http://exist-db.org/collection-config/1.0";`; I have omitted it below to make it clearer what the issues are.

1. Should return a non-empty result (works correctly):
```xquery
(collection("/db/system/config/db")/config:collection)[1]/parent::node()
```
2. Should return an empty result (works correctly):
```xquery
(collection("/db/system/config/db")/config:collection)[1]/parent::*
```

3. Should return a non-empty result (**Fails**):
```xquery
(collection("/db/system/config/db")/config:collection)[1]/parent::document-node()
```

4. Should return a non-empty result (**Fails**):
```xquery
(collection("/db/system/config/db")/config:collection)[1]/parent::document-node(element(config:collection))
```

5. Should return a non-empty result (**Fails**):
```xquery
(collection("/db/system/config/db")/config:collection)[1]/ancestor::document-node()
```

6. Should return a non-empty result (**Fails**):
```xquery
(collection("/db/system/config/db")/config:collection)[1]/ancestor::document-node(element(config:collection))
```

7. Should return a non-empty result (**Fails**):
```xquery
(collection("/db/system/config/db")/config:collection)[1]/ancestor-or-self::document-node()
```

8. Should return a non-empty result (**Fails**):
```xquery
(collection("/db/system/config/db")/config:collection)[1]/ancestor-or-self::document-node(element(config:collection))
```
