### ISSUE TITLE
Problem saving in exist

### ISSUE THREAD

**Issue by diego1a** [eXist-db/exist#456]
I want to save in exist an xml with tags without blancks beetween them, for example i tried to save this: 
(XML TAG)sfggfdg(CLOSING XML TAG)(XML TAG)lololooo(CLOSING XML TAG)

And when i reload the collection there is this: 
        (XML TAG)sfggfdg(CLOSING XML TAG)
       (XML TAG)lololooo(CLOSING XML TAG)

Has exist any parameter to avoid this estructure saving the collection ?

Thanks in advance.

**Comment by joewiz** [comment]
There may be a few factors at play.  So, a few questions:  First, did you modify your conf.xml file's whitespace handling settings, or did you leave them as they are by default?  Second, how are you "reloading the collection"?  With eXide, a WebDAV client, or some other editor?

**Comment by diego1a** [comment]
Yes , firstly I've detect the problem inserting with XUpdate from web application with conf.xml default settings.
Then I've tried to make the change directly with exide and after saved I reload it with the same result.

After that, I changed conf.xml settings(suppress-whitespace, preserve-whitespace-mixed-content, serializer indent, ...), with the same result.

**Comment by diego1a** [comment]
I've resolved finally with the indent parameter, finally it has work fine.

Apart that the exide editor writes with indention the file is ok.

**Comment by joewiz** [comment]
Could you be a little more specific about what you did to achieve the desired result?  Also, could you please close this and the other two related issues, #460 and #461?  Thanks.

**Comment by dizzzz** [comment]
@diego1a  please a follow up....
