### ISSUE TITLE
Empty tag "source" should be self-closing in HTML5 

### ISSUE THREAD

**Issue by martindholmes** [eXist-db/exist#46]
When serializing output as HTML5, the `<source>` tag is output with a separate closing tag, instead of being a self-closing tag -- it's an empty tag according to the specification:

http://www.w3.org/TR/html51/embedded-content-0.html#the-source-element

I think this is because the HTML5 serializer is a subclass of the XHTML serializer, and this uses a list of element names (emptyTags) to determine which tags should be output as self-closing tags, and "source" isn't on the list:

https://github.com/eXist-db/exist/blob/develop/src/org/exist/util/serializer/XHTMLWriter.java

Outputting `<source>` with a separate closing tag results in validation errors from the HTML5 validator.

**Comment by joewiz** [comment]
Assign to milestone eXist 3.1?

**Comment by dizzzz** [comment]
Looks like @shabanovd files a PR, today?

**Comment by joewiz** [comment]
Fantastic! Thanks @shabanovd and @dizzzz, and to @martindholmes for reporting the issue!
