### ISSUE TITLE
Jetty 9: End of Community Support

### ISSUE THREAD

**Issue by stexandev** [eXist-db/exist#4607]
exist-db is still developed with [jetty 9.44 as a dependency](https://github.com/eXist-db/exist/blob/develop/exist-parent/pom.xml#L115)

the problem: jetty 9 is slowly reaching EOL with a yet unknown date; [End of Community Support has already passed by (June 1st, 2022)](https://github.com/eclipse/jetty.project/issues/7958).

any plans to migrate to jetty 10, yet?

**Comment by line-o** [comment]
There is a PR open #4575 that will bump jetty to v11. It is planned to be released with the next major version.

**Comment by hsg-commits** [comment]
See https://github.com/eXist-db/exist/pull/4575.

**Comment by dizzzz** [comment]
Fortunately still updates are made to 9.x ;
