### ISSUE TITLE
Serializer indention doesn't work

### ISSUE THREAD

**Issue by diego1a** [eXist-db/exist#461]
I am running the following query:

```xquery
xmldb:store('/db/apps/demo', 'index.html', <div><div>kakakakaka</div><div>papapapap</div></div>)
```
What I expect to have in the document is:

```xml
<div><div>kakakakaka</div><div>papapapap</div></div>
```

But instead I have:

```xml
<div>
    <div>kakakakaka</div>
    <div>papapapap</div>
</div>
```
How is that, and how can I have the former instead of the latter?

(I have tried to set `<serializer indent="no">` in conf.xml, but I guess the
serializer is not involved here.)

**Comment by joewiz** [comment]
Is this not a duplicate of #456?

**Comment by diego1a** [comment]
Yes, but with different explanation and example, so there is not answer to this problem ?

Thanks.

**Comment by diego1a** [comment]
I've resolved finally with the indent parameter, finally it has work fine.

Apart that the exide editor writes with indention the file is ok.

**Comment by dizzzz** [comment]
close issue?
