### ISSUE TITLE
problem with sequence selection containing util:random in predicate

### ISSUE THREAD

**Issue by christophe-g** [eXist-db/exist#462]
Sometimes, this query returns no result and sometimes more than 1 (1 result would be expected).
```xquery
xquery version "3.0";

let $seq := (1 to 65)
return 
    $seq[position() = (1 + util:random(64))]
```
Cheers,
C.

**Comment by dizzzz** [comment]
there was a discussion on the mailinglist : http://exist.markmail.org/thread/rbasz5xjwuautfde 

so... a bug or a feature ? :-)

**Comment by adamretter** [comment]
Oh yes this is definitely a bug. Not only does it sometimes return no items, sometimes it also returns more than 1 item. Almost certainly a problem in `position()` which has had many problems in eXist in the past also.

Switching from `util:random` to `math:random` shows the same problem too:

```xquery
xquery version "3.0";

import module namespace math = "http://exist-db.org/xquery/math";

let $seq := (1 to 65)
return
    $seq[position() = 1 + xs:integer(math:random() * 65)]
```

**Comment by shabanovd** [comment]
@christophe-g why you think that `util:random` must be deterministic function? and why you expect predicate act as function?

> For each item in the input sequence, the predicate expression is evaluated using an inner focus, defined as follows: The context item is the item currently being tested against the predicate. The context size is the number of items in the input sequence. The context position is the position of the context item within the input sequence.
>
>For each item in the input sequence, the result of the predicate expression is coerced to an xs:boolean value, called the predicate truth value, as described below. Those items for which the predicate truth value is true are retained, and those for which the predicate truth value is false are discarded.

http://www.w3.org/TR/xquery-30/#id-filter-expression

**Comment by jensopetersen** [comment]
See also https://github.com/eXist-db/exist/issues/426, https://github.com/eXist-db/exist/issues/362.

**Comment by shabanovd** [comment]
that issues are different (all of them -)

**Comment by wolfgangmm** [comment]
It is probably a wrong flag being set, most likely due to the cast. If you factor out the call to random, it works as expected:

```xquery
let $seq := (1 to 65)
let $rand := 1 + xs:integer(math:random() * 65)
return
    $seq[position() = $rand]
```

**Comment by adamretter** [comment]
So yes I think @shabanovd is correct here :-)

As he points out, it is just as the XQuery spec says, the predicate is evaluated once for each item in the sequence, so `util:random` or `math:random` is called 65 times. Placing the eval or random outside of the predicate means that the random is only evaluated once.

**Comment by adamretter** [comment]
This is expected behaviour, thanks @shabanovd

**Comment by christophe-g** [comment]
Oh ! thanks. 
You are right, once you  remember functions in predicates are evaluated for each sequence member, it is quite clear it's the expected behavior (thanks @shabanovd).

That could be a nice example of counter-intuitive programming though. 
C.

**Comment by dizzzz** [comment]
I did not realize....... thnx for this aha-moment :-)

**Comment by joewiz** [comment]
Fascinating!  Thanks, guys!
