### ISSUE TITLE
JSON annotation error

### ISSUE THREAD

**Issue by wshager** [eXist-db/exist#465]
The following should serialize to `intarray:[1]`

```xquery
<intarray json:array="true" json:literal="true">1</intarray>
```

**Comment by adamretter** [comment]
I think that JSON has to be either a map (object) or an array. So you could have either the following JSON:

```json
{
  "intarray": [
    1
  ]
}
```

or 

```json
[
  1
]
```

Which of these are you aiming for?

**Comment by adamretter** [comment]
I can get very close to my first example with this:

```xquery
xquery version "3.0";

declare namespace json = "http://www.json.org";

declare option exist:serialize "method=json media-type=text/javascript";

<root>
	<intarray json:literal="true" json:array="true">1</intarray>
</root>
```

Although I do see a bug where `json:literal` is ignored when used with `json:array` here.

**Comment by wshager** [comment]
That's what I mean yes.

**Comment by adamretter** [comment]
I can also get quite close to my second example with this:

```xquery
xquery version "3.0";

declare namespace json = "http://www.json.org";

declare option exist:serialize "method=json media-type=text/javascript";

<root><json:value json:array="true">1</json:value></root>
```

Again there is perhaps another bug with `json:literal`, where if I add it to the `json:value` then the array is instead returned as an object.

**Comment by wshager** [comment]
Sorry I didn't add that. I probably mentioned on the exist mailinglist but forgot to do so here.
