### ISSUE TITLE
[BUG] demo not working

### ISSUE THREAD

**Issue by KitWallace** [eXist-db/exist#4660]
Exist version 6.0.1 : Demos

/db/apps/demo/examples/web/guess-templates.xql

and 

/db/apps/demo/examples/web/guess.xql

have 

xquery version "1.0";

which stops the template example working

**Comment by line-o** [comment]
Could you see that changing the version fixes the issue?

**Comment by line-o** [comment]
Do we have to move this issue to the demo repo perhaps?

**Comment by KitWallace** [comment]
yes  changing to 3.0 fixes it

**Comment by KitWallace** [comment]
Ah yes - now I see all the separate repositories - apologies for littering

**Comment by KitWallace** [comment]
moved to Demo
