### ISSUE TITLE
[BUG] poms of two modules show up as untracked after build and are not updated on release

### ISSUE THREAD

**Issue by line-o** [eXist-db/exist#4694]
**Describe the bug**

When building exist I have two changed pom.xml files in my working directory.

- exist-core-jcstress/dependency-reduced-pom.xml
- exist-core-jmh/dependency-reduced-pom.xml

**Expected behavior**

Building exist from source does not add untracked files to the working directory. They should either be ignored or stay unchanged.

**To Reproduce**

1. checkout develop
2. run `mvn clean package`
3. run `git status`
4. the two poms mentioned above are shown as untracked files

**Screenshots**

When checking out the current master branch and building it both subprojects still show up as 6.1.0-SNAPSHOT (see screenshot below): 

<img width="639" alt="Screenshot 2023-01-20 at 15 16 18" src="https://user-images.githubusercontent.com/657222/213721716-dcf81aaa-f73f-4cec-a0cb-8024ea4685d7.png">

**Context (please always complete the following information):**
- Build: eXist-6.1.0-SNAPSHOT (b8e73493b95e252dbe09f4b3be1833bd4c62371e)
- Java: 1.8.0_352 (Azul Systems, Inc.)
- OS: Mac OS X 12.6.2 (aarch64)

**Additional context**
- How is eXist-db installed? built from source (develop, master)
- Any custom changes in e.g. `conf.xml`? none

**Comment by line-o** [comment]
This seems to even cause the test workflow in CI to fail see https://github.com/eXist-db/exist/actions/runs/3940322485/jobs/6741277473#step:4:21

**Comment by joewiz** [comment]
It appears that the 6.1.0 release didn't touch the poms of `exist-core-jcstress` or `exist-core-jmh`.

Compare the files listing of the [6.0.0](https://github.com/eXist-db/exist/commit/70875a0bb0c6e3d03324c01db984100bd8c32fb0) and [6.1.0](https://github.com/eXist-db/exist/commit/f90ddb547162d205b293a982bbe989e39651c605) releases.

**Comment by joewiz** [comment]
My results when running `mvn package` on develop HEAD:

> <img width="642" alt="Screenshot 2023-01-20 at 20 52 18" src="https://user-images.githubusercontent.com/59118/213835830-83cf0ca1-e159-44b9-b273-551a407d50d0.png">

**Comment by joewiz** [comment]
... and I don't get any untracked pom files. But I definitely see the mismatch between 6.2.0-SNAPSHOT for most of the build targets except for exist-core-jcstress and exist-core-jmh.

**Comment by line-o** [comment]
@joewiz try `mvn clean package`

**Comment by joewiz** [comment]
@line-o Running `mvn clean package`, I do get the 2 untracked `dependency-reduced-pom.xml` files in `exist-core-jcstress` and `exist-core-jmh` that you described. Does the issue description need to be updated to say `mvn clean package` instead of `mvn package`?

**Comment by line-o** [comment]
Well, on a clean checkout you would see it without clean I suppose

**Comment by joewiz** [comment]
Fair point! Then I suppose the more precise advice than "checkout develop" would be "Clone the repository and checkout develop; or, for an existing clone, run `mvn clean`"?

**Comment by joewiz** [comment]
... I'm not being nitpicky. I'm just trying to ensure others trying to reproduce are able to follow the instructions clearly so they can effectively investigate.

**Comment by line-o** [comment]
I changed it

**Comment by line-o** [comment]
The dependency-reduced-pom.xml are related to the quartz scheduler 
In `org.quartz-scheduler/quartz/pom.xml` on line 148 there is this line
```
<dependencyReducedPomLocation>${project.build.directory}/dependency-reduced-pom.xml</dependencyReducedPomLocation>           
```

**Comment by line-o** [comment]
So, `exist-core-jmh` and `exist-core-jcstress` must depend on the quartz scheduler. As it seems these dependency-reduced POMs are built artifacts they should be removed from the repository and ignored from here on.
On a side note: The quartz-package has not received updates in two years. Are there alternatives that might still be actively maintained?
