### ISSUE TITLE
XQTS workflow no longer working

### ISSUE THREAD

**Issue by line-o** [eXist-db/exist#4707]
Judging from the output of the most recent run of our XQTS workflow 
https://github.com/eXist-db/exist/actions/runs/4024734250/jobs/6917098711

the runner throws an uncaught exception at the very beginning 
see https://github.com/eXist-db/exist/actions/runs/4024734250/jobs/6917098711#step:5:8

and no report is generated
and https://github.com/eXist-db/exist/actions/runs/4024734250/jobs/6917098711#step:6:10

**NOTE** The workflow reports success without producing a report.

**Comment by line-o** [comment]
The breaking change for XQTS was introduced here https://github.com/eXist-db/exist/actions/runs/3085115897

**Comment by line-o** [comment]
Might be fixed by using the latest version of XQTS-runner, released yesterday. https://github.com/eXist-db/exist-xqts-runner/releases/tag/1.2.0

**Comment by joewiz** [comment]
It appears the XQTS workflow is working again - see https://github.com/eXist-db/exist/actions/workflows/ci-xqts.yml.

**Comment by line-o** [comment]
No @joewiz it's not. It's a false positive.

**Comment by line-o** [comment]
Since the updated XQTS runner (v1.2.0) seems to have memory issues we should consider to 

Not update XQTS runner and include the old slf4j activation library in existdb next to the new one. 

It is obvious that the current XQTS runner started failing when the old activation library was removed (#568).

**Comment by line-o** [comment]
I did a small test run to falsify my assumption. The interesting finding: even with the current version of XQTS runner 1.1.0 the workflow runs out of heap space which indicates that changes to existdb itself are causing these.
see https://github.com/eXist-db/exist/actions/runs/4104225085/jobs/7079420739#step:5:1432

**Comment by adamretter** [comment]
> XQTS runner workflow still reports as succeeding while it now fails due to the same heap space exceptions after https://github.com/eXist-db/exist/pull/4730 was merged.

That is intentional as the desired workflow has not yet been complete. I have been actively working on this https://github.com/eXist-db/exist/pull/4661. Please remain calm and give me the necessary time to finish that work in #4661.

**Comment by line-o** [comment]
So what I would like to achieve is that whenever the run of the XQTS does not produce any result then it should fail to indicate that there is a real issue not just failing test cases within the test suite.
