### ISSUE TITLE
some windows batch files have wrong line ends

### ISSUE THREAD

**Issue by nicg-corbas** [eXist-db/exist#474]
The Windows batch files in the 2.2 release appear to have been saved with Linux line endings.

**Comment by dizzzz** [comment]
Could you elaborate which of the scripts are affected?

**Comment by nicg-corbas** [comment]
Apologies - should have been much more clear - I'm seeing client.bat, check_jmx_status.bat and get_opts.bat all with (proper operating system) LF only linebreaks
