### ISSUE TITLE
[build] replace copy-maven-plugin

### ISSUE THREAD

**Issue by line-o** [eXist-db/exist#4753]
**Is your feature request related to a problem? Please describe.**

The maven project `exist-distribution` uses the plugin [ch.mfrey.maven.plugin]().
The last release, 1.0.0, was released on Oct 31, 2019. The GitHub repository has not seen any activity apart from the recent issue that I opened. It is safe to assume this plugin is no longer actively maintained.
 
**Describe the solution you'd like**

The functionality to copy files be implemented using other available, maintained alternatives. 
We do already pull in [copy-rename-maven-plugin](https://github.com/coderplus/copy-rename-maven-plugin), unfortunately this plugin has also not been maintained since 2014 (!). 
Is there an actively maintained maven plugin that can be used instead?

**Describe alternatives you've considered**

Since copying files is provided by maven itself we should investigate if copying XAR packages to autodeploy can be achieved without any third party plugin (candidate [maven-resources-plugin](https://maven.apache.org/plugins/maven-resources-plugin/)).

**Context**

- refs #4752 
- refs #4751
- refs #4749

**Comment by line-o** [comment]
related to #4752 #4751 #4749

**Comment by line-o** [comment]
[Using ant tasks within maven goals](https://maven.apache.org/guides/mini/guide-using-ant.html) could also be a viable alternative solution.

- they are well understood
- they can create, copy, rename, filter and replace files and directories

**Comment by eduarddrenth** [comment]
maven-resources-plugin works very well, no need then for mixing another technology (ant)

**Comment by line-o** [comment]
That sounds like you have experience using it. Would you be able to have a look at the exist-distribution POM and see if you are able to replace the current XAR copying with the maven provided plug-in? It is not obvious to me how to replace (and rename) resources.

**Comment by eduarddrenth** [comment]
I'll have a look, did not do renaming though

**Comment by line-o** [comment]
Renaming will be the stretch goal not needed here @eduarddrenth

**Comment by eduarddrenth** [comment]
prepared something here: https://github.com/fryske-akademy/exist/blob/636021d9bc558bd7339e5afbb7135ec58fce7cc6/exist-distribution/pom.xml#L710

cannot build and check though because of owasp trouble

**Comment by line-o** [comment]
@eduarddrenth Excellent! (apart from owasp blocking our builds).
Could you still open a PR for this (that way it is easier to checkout and test locally).

**Comment by adamretter** [comment]
I found that maven-resources-plugin was not sufficient, which is why I introduced the copy-maven-plugin. The renaming is required for the built distribution to function.

**Comment by eduarddrenth** [comment]
My change replaced ch.mfrey.maven.plugin, copy-rename-maven-plugin is untouched.

**Comment by eduarddrenth** [comment]
My change replaced ch.mfrey.maven.plugin, copy-rename-maven-plugin is untouched.

Assembly plugin can rename, would that be an option, see https://stackoverflow.com/questions/50457161/rename-a-file-using-fileset-in-maven.

**Comment by adamretter** [comment]
Closed by 300e9c093d663303bebdc7107c2ae5645fc14519
