### ISSUE TITLE
[BUG] implicit validation fails

### ISSUE THREAD

**Issue by eduarddrenth** [eXist-db/exist#4757]
**Describe the bug**
- During startup this error shows:

`CatalogUnavailableException: org.exist.EXistException: Database instance 'exist' is not available`

- validation is configured like this:
```xml
    <validation mode="yes">
        <entity-resolver>
            <catalog uri="/db/apps/corpora/xsd/fa_tei_catalog.xml"/>
        </entity-resolver>
    </validation>
```
The catalog file and accompanying xsd's are there.
- validation from now on does not work

**Expected behavior**
- No error in the log because the catalog file is valid
- validation operational

**To Reproduce**
`docker build --progress plain -t fails:1 .`

using this dockerfile

```Dockerfile
FROM existdb/existdb:6.2.0

COPY *.xar $EXIST_HOME/autodeploy/

RUN [ "java", "org.exist.start.Main", "client", "--no-gui",  "-l", "-u", "admin", "-P", "", "-x", "system:get-version()" ]
```

and this xar

[corpora-1.0.xar.zip](https://github.com/eXist-db/exist/files/10758532/corpora-1.0.xar.zip)

then run then image using [conf.xml.zip](https://github.com/eXist-db/exist/files/10759019/conf.xml.zip)

`docker run -it --mount type=bind,src=`pwd`/conf.xml,dst=/exist/etc/conf.xml -p 8080:8080 fails:1`

**Context (please always complete the following information)**

 - Build: [eXist-6.2.0]
 - Java: [1.8.0_352]
 - OS: [docker/linux]

**Comment by line-o** [comment]
@eduarddrenth did this used to work? If yes in which version of existdb?
Also: have you tried to resolve the file from the filesystem? 
The comment above the validation 

> "${WEBAPP_HOME}" and "${EXIST_HOME}" can be used as magic string.

indicate a filesystem path is expected here.

**Comment by eduarddrenth** [comment]
So you suspect a db path might not work? I'll try that

Op do 16 feb. 2023 21:40 schreef Juri Leino ***@***.***>:

**Comment by eduarddrenth** [comment]
yes, xmldb path to catalog is not supported

**Comment by line-o** [comment]
@eduarddrenth have you tried using a db-path with `xmldb-exist://` protocol?

**Comment by eduarddrenth** [comment]
yes, no luck

**Comment by line-o** [comment]
Thanks for confirming
