### ISSUE TITLE
[BUG] Cannot connect to oxygen with eXist-6.2.0 same bug than #2526

### ISSUE THREAD

**Issue by g-vidal** [eXist-db/exist#4785]
I am used tuse the connector between oXygen and eXist. 
**Describe the bug**
When trying to install a connector  from oXygen 25.0 on my fresh installed eXist 6.2.0 the files seemed to be downloaded the connector is created and the link appears. When I click on the link  I get the error message :
`Could not instantiate: ro.sync.db.nxd.exist.ExistSession due to: java.util.ServiceConfigurationError: org.apache.logging.log4j.spi.Provider: org.apache.logging.slf4j.SLF4JProvider not a subtype`

**Expected behavior**
The connector should open the database

**To Reproduce**
I have installed on my laptop  eXist5.5.1 and 6.2.0 in 2 different foldersand not done anything on any
I clear all exist-db connectors on oXygen and shutdown oXygen.
1. if I start eXist6.2.0 and create the connector  I get the above message
2. Clear ans shutdown again
3. if I start eXist5.5.1 and create the connector  evrything is OK my remote database opens and the link is operational
`

**Screenshots**

**Context (please always complete the following information)**
One option is to use [xst](https://www.npmjs.com/package/@existdb/xst), and copy and paste the output produced by running `xst info` here:**

#1 SMP Debian 5.10.162-1 (2023-01-21) x86_64 GNU/Linux
openjdk 17.0.6 2023-01-17
OpenJDK Runtime Environment (build 17.0.6+10-Debian-1deb11u1)
OpenJDK 64-Bit Server VM (build 17.0.6+10-Debian-1deb11u1, mixed mode, sharing)
~[exist-core-6.2.0.jar:6.2.0]

**Additional context**

- How is eXist-db installed? [e.g. JAR installer, DMG, … ] 
- headless jar
- Any custom changes in e.g. `conf.xml`?
- backup schedule

**Comment by reinhapa** [comment]
As with version of eXist-6.2.0 we updated the logging framework from SLF4J 1.x to 2.x that requires some other library requirements. Therefore you will need to configure a new connection as described here:
https://www.oxygenxml.com/doc/versions/25.0/ug-editor/topics/configure-exist-datasource.html

**Comment by g-vidal** [comment]
Many thanks for your quick answer, I have found this page but I was not able to find in my eXist-db installation the files mentionned
```shell
Click the Add Files button to add the eXist driver files. The following driver files should be added and they are found in the installation directory of the eXist database server. Make sure you copy the files from the installation of the eXist server where you want to connect from Oxygen XML Editor.

    The exist.jar file located in the base directory.
    All JAR files in the lib/core/ directory.
```
The base directory contains only :
```shell
autodeploy/  bin/  CONTRIBUTING.md  data/  etc/  lib/  LICENSE  logs/  README.md
```
There is no exist.jar in the whole eXist  hierarchy  (sudo -u existdb find . -name exist.jar output is empty)
There is no lib/core folder
```shell
ls lib/core
ls: impossible d'accéder à 'lib/core': Aucun fichier ou dossier de ce type
```
Where can I find the necessary files in the eXst installation folder ?
Thanks

**Comment by reinhapa** [comment]
@g-vidal in that case you can select all libraries within the `lib` folder.

**Comment by dizzzz** [comment]
Is the servlet/jmlp thingy still working? if so, then we'd need to update some jar files there as well....

https://github.com/eXist-db/exist/blob/develop/exist-core/src/main/java/org/exist/webstart/JnlpJarFiles.java#L53

**Comment by dizzzz** [comment]
anyway I'd like to get rid of this mechanism completely. For this we need to sit together with the oxygenXML guys...
I think recent developments will make this jar download thingy unnecessary .....

**Comment by g-vidal** [comment]
I have investigated  the  .com.oxygenxml/eXistdb folder  for 5.5.1 and 6.2.0. The results are below, of course there are differences between the versions but the file `log4j-slf4j-impl-X.XX.XX.jar` is missing. It does not exist in eXist/lib and in place there is  `log4j-slf4j2-impl-2.19.0.jar` which is not copied by the wizard.

I have emptied the files in the wizard then reload all the 25 files from 6.2.0 replacing `log4j-slf4j-impl` with `log4j-slf4j2-imp` but it does not work I get the following error

`Could not instantiate: ro.sync.db.nxd.exist.ExistSession due to: java.util.ServiceConfigurationError: org.apache.logging.log4j.spi.Provider: org.apache.logging.slf4j.SLF4JProvider not a subtype`

I have kept all the new jar versions uploaded by the wizard except log4j*.jar  and slf4j  replaced by the 5.5.1 versions, and the connector works properly again. That's weird  sould it be oXygen which is not amare of log4j-slf4j2-impl  ?


** for 5.5.1**
```shell
antlr-3.0.jar            j8fu-1.23.0.jar           log4j-core-2.15.0.jar        ws-commons-util-1.0.2.jar
bcprov-jdk15on-1.70.jar  jackson-core-2.13.1.jar   log4j-jul-2.15.0.jar         xmldb-api-1.7.0.jar
clj-ds-0.0.4.jar         jansi-2.4.0.jar           log4j-slf4j-impl-2.15.0.jar  xmlrpc-client-3.1.3.jar
commons-codec-1.15.jar   jargo-0.4.14.jar          pkg-java-1.6.1.jar           xmlrpc-common-3.1.3.jar
commons-io-2.11.0.jar    jcip-annotations-1.0.jar  quartz-2.3.2.jar
commons-logging-1.2.jar  jline-3.21.0.jar          rsyntaxtextarea-3.1.6.jar
exist-core-5.5.1.jar     log4j-api-2.15.0.jar      slf4j-api-1.7.33.jar
``` 
** for 6.2.0**
```shell
antlr-3.0.jar            exist-core-6.2.0.jar      jline-3.22.0.jar       rsyntaxtextarea-3.3.2.jar
bcprov-jdk15on-1.70.jar  j8fu-1.23.0.jar           log4j-api-2.19.0.jar   slf4j-api-2.0.6.jar
clj-ds-0.0.4.jar         jackson-core-2.13.4.jar   log4j-core-2.19.0.jar  ws-commons-util-1.0.2.jar
commons-codec-1.15.jar   jansi-2.4.0.jar           log4j-jul-2.19.0.jar   xmldb-api-1.7.0.jar
commons-io-2.11.0.jar    jargo-0.4.14.jar          pkg-java-2.0.0.jar     xmlrpc-client-4.0.0.jar
commons-logging-1.2.jar  jcip-annotations-1.0.jar  quartz-2.3.2.jar       xmlrpc-common-4.0.0.jar
```

**Comment by dizzzz** [comment]
it downloads the JNLP file to see what JAR files need to be downloaded.
so with new JAR files.... this list needs to be extended/updated.

**Comment by raducoravu** [comment]
@g-vidal One thing to try on your side (you should close Oxygen first):

From the folder created by the Oxygen Exist data source wizard containing all Exist JAR libraries remove all the "log4j-*.jar" libraries. Then re-start Oxygen and see if the connection works.

Oxygen uses the slf4j API version 2.17.1 along with the slf4j implementation for logging. It also contains an "log4j-to-slf4j-2.17.1.jar" bridge JAR library which delegates log4j API calls to the slf4j implementation.
The Exist client libraries on the other side use the slf4j API version 2.0.6 along with log4j implementations which provide the actual logging.

So it's a headache to make this work. We'll look more into this on our side.
It would help if Exist would shift from using Apache log4j 2.x and use for example logback but probably this is not an argument to do so..

**Comment by reinhapa** [comment]
> So it's a headache to make this work. We'll look more into this on our side. It would help if Exist would shift from using Apache log4j 2.x and use for example logback but probably this is not an argument to do so..

I guess using SLF4J in eXist internally would also solve a lot of problems as the needed implementation could be Chosen at will...

**Comment by g-vidal** [comment]
@raducoravu Your proposal works perfectly !
Here is what I did  :

1. erased connection and removed eXist connector
2. stop and restart oXygen
3. create a connector with the wizard on eXist-db-6.2.0 running on localhhost
4. create a connection on my migrated remote eXist-db-6.2.0
5. Open connection without any problem, edit docbook file and xQuery,  save the file and checked that permissions are respected.

Many thanks to you all for the time spent !
If I may express a will, the tandem eXist-oXygen is really very powerful and convenient I hope the link will be maintained !

**Comment by raducoravu** [comment]
@g-vidal thanks for testing this on your side, hopefully we can find some way on our side to make this work in the upcoming Oxygen 25.1 without the need to delete libraries.

**Comment by raducoravu** [comment]
As an update we release Oxygen 25.1 in which we made some changes to have it connect to an eXist 6.2.0 database without the need to remove various logging libraries from the eXist connection.

**Comment by goodzack** [comment]
For what it's worth, and for all the people who might come into this problem in the near future, I'm currently using oXygen 24.1 and I had the same problem. The solution proposed by @raducoravu [above](https://github.com/eXist-db/exist/issues/4785#issuecomment-1456201372) works perfectly.
