### ISSUE TITLE
[feature] Allow usage of Saxon PE/EE

### ISSUE THREAD

**Issue by kosek** [eXist-db/exist#4813]
It should be possible to use licensed Saxon PE/EE as a replacement for bundled Saxon HE. In order to do that exist-db should provide ability to specify license key and configuration for Saxon PE/EE.

See comment from @adamretter 
> It looks like since eXist-db 6.1.0, it is not possible to configure it manually for Saxon-EE.
Basically eXist-db 6.1.0 was updated to use Saxon’s S9 API instead of the JAXP API. This made it possible for us to implement fn:transform#1 from XQuery 3.1 in a cleaner manner.
In fact I found a TODO in the code about this here - https://github.com/eXist-db/exist/blob/develop/exist-core/src/main/java/org/exist/xquery/functions/fn/transform/Transform.java#L88
So I am afraid you need to use an older version of eXist-db (I would not really recommend that), or yourself or someone else needs to make some changes to eXist-db to support Saxon-EE custom config file and license. I think the changes required to eXist-db should be relatively small and easy to achieve, but I am afraid I don’t have the time right now to delve into that.

**Comment by adamretter** [comment]
Closed by https://github.com/eXist-db/exist/pull/4854
