### ISSUE TITLE
Custom xml file extension 

### ISSUE THREAD

**Issue by miquik** [eXist-db/exist#4814]
Hi everybody,
I would like to upload my xml files which have custom file estension. So I create a copy of mine-types.xml adding my own extension. Doc says that the library will search first in folder specify in “exist.home” property but it doesn’t seem to work.

So I try placed this file in almost every subfolder but It seems it is simply ignored. Am I missing something or doing something wrong?

Thanks

**Comment by adamretter** [comment]
@miquik Which version of eXist-db please?

**Comment by miquik** [comment]
Last version 6.2

**Comment by adamretter** [comment]
@miquik This is no longer configurable in eXist-db 5.x.x onwards.

You can if you wish patch/replace the file `org/exist/util/mime-types.xml` from inside exist-core-*.jar.

**Comment by line-o** [comment]
@miquik I am able to store XML data with any extension in eXist-db without making any change to mime-types.xml.

```bash
; xst run 'xmldb:store("/db", "asdf.mytype", <root />, "application/xml")'
/db/asdf.mytype
; xst run 'doc("/db/asdf.mytype")'
<root/>
```
What is your preferred way to upload data?

**Comment by miquik** [comment]
Thanks @adamretter and @line-o I will give a try
