### ISSUE TITLE
[BUG] XQuery bug of node selection of tail() after subsequence()

### ISSUE THREAD

**Issue by Twilight-Shuxin** [eXist-db/exist#4830]
**Describe the bug**
Give XPath Query
```
tail(subsequence((1 to 2),1,2))
```

Exist returns 0 element

**Expected behavior**

Should return one element 2

**To Reproduce**

Can just execute the query statement in http://exist-db.org/exist/apps/eXide/index.html

**Context (please always complete the following information)**

 - Build: latest development version built from source, commit dc0bfc8
 - Java: 17
 - OS: [Windows]

**Additional context**
- How is eXist-db installed? Jar installer
- Any custom changes in e.g. `conf.xml`? No

**Comment by joewiz** [comment]
I can reproduce the report with eXist 6.2.0. It's very strange and concerning that such a basic query would fail. 

XQSuite:

```xquery
xquery version "3.1";

module namespace t="http://exist-db.org/xquery/test";

declare namespace test="http://exist-db.org/xquery/xqsuite";

declare
    %test:assertEquals("2")
function t:test() {
    tail(subsequence((1 to 2),1,2))
};
```

Results:

```xml
<testsuite errors="0" failures="1" package="http://exist-db.org/xquery/test" pending="0" tests="1"
    time="PT0.001S" timestamp="2023-03-24T09:43:02.207-04:00">
    <testcase class="t:test" name="test">
        <failure
            message="assertEquals failed: wrong number of items returned by function. Expected: 1. Got: 0"
            type="failure-error-code-1">2</failure>
        <output/>
    </testcase>
</testsuite>
```

**Comment by line-o** [comment]
7.0.0-SNAPSHOT is affected as well

**Comment by line-o** [comment]
It is the call to `subsequence` that does not work well with the tail command. So the error likely lies in the eval methods of one of the two or their combination.

It does not matter how they are called. I tried the arrow operator and declaring the subsequence in a module variable. Both will still return an empty sequence.

**Comment by Twilight-Shuxin** [comment]
Thanks for the fix!

**Comment by line-o** [comment]
@Twilight-Shuxin We have to thank you for finding _and_ reporting it. :)
