### ISSUE TITLE
[BUG] permissions not honoured?

### ISSUE THREAD

**Issue by eduarddrenth** [eXist-db/exist#4840]
exide let's me save this document:
![image](https://user-images.githubusercontent.com/10200360/228245441-b7fe6b85-2c4b-453c-a958-a079f4b1f949.png)
while I am loggid in as admin:
![image](https://user-images.githubusercontent.com/10200360/228245768-294ec330-d8f8-4366-a150-92c27aa05af3.png)

Is that ok?

exist-db version 6.2.0

**Comment by line-o** [comment]
@eduarddrenth The screenshot shows that you are logged in as admin who is typically member of the DBA group. This group has leveraged access and might be able to do that. Any member of that group can change the permissions of any resource or collection in the database. In that regard a member of DBA is able to write to any resource or collection. So, for me, it comes down to the question: Is a member of DBA required to change the permissions first before reading from or writing to a collection that is restricted?

It is crucial that members of DBA can do that.

**Comment by eduarddrenth** [comment]
like on linux, agreed
