### ISSUE TITLE
poor admin performance with large collection

### ISSUE THREAD

**Issue by sebastianrahtz** [eXist-db/exist#485]
I have created a collection with 32000 XML files in, and find that I cannot do admin-like operations (e.g. change group permissions) because the system sits trying to load up the name of all the files (I assume). This seems a bit odd?

**Comment by joewiz** [comment]
Could you specify which tool you're using to perform these operations?  Java admin client, Dashboard > Collection Browser, Dashboard > eXide > File > Manage (aka DB Manager), or via your own custom XQuery code?

**Comment by wolfgangmm** [comment]
The Java admin client does indeed try to retrieve the metadata for all resources in the collection at once. The file dialog in eXide is a bit better because it loads the resources in batches. Increasing the collectionCache size in conf.xml may also help a bit in general. 

However, changing permissions on thousands of resources is not very efficient through either of the graphical interfaces. Scripting is much faster and I usually tend to write a small XQuery script if I have to modify a large collection. For example:

```xquery
for $r in xmldb:get-child-resources("/db/apps/eXide")
return
    sm:chmod($r, "rw-rw-r--")
```

or use the dbutil module, which has additional functions to scan collection hierarchies:

```xquery
import module namespace dbutil="http://exist-db.org/xquery/dbutil" at "/db/apps/shared-resources/content/dbutils.xql";

dbutil:scan-resources(xs:anyURI("/db"), function($resource) {
    sm:chmod($r, "rw-rw-r--")
})
```

The sm module provides everything you need to handle permissions etc.

**Comment by dizzzz** [comment]
An option could be to enable http compression in the XMLRPC interface....

**Comment by sebastianrahtz** [comment]
I was working in the simple "Collections" thing (
http://eebotcp.cloudapp.net:8080/exist/apps/dashboard/index.html). All I
wanted to was change the ownership of the whole collection, but I when I
select the collection name and try to change that, the lower pane just
starts endlessly "Loading...". Which puzzled me. I didn't want to change
all the texts in there, just the collection itself.

thanks for pointers about doing this sort of thing in XQuery. That's a bit
beyond my level as a (very rusty...) naive XQuery user.

On 19 February 2015 at 19:27, Dannes Wessels <notifications@github.com>
wrote:

> An option could be to enable http compression in the XMLRPC interface....
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/eXist-db/exist/issues/485#issuecomment-75118599>.
>



-- 

Sebastian Rahtz

Director (Research) of Academic IT

University of Oxford IT Services

13 Banbury Road, Oxford OX2 6NN. Phone +44 1865 283431


Não sou nada.

Nunca serei nada.

Não posso querer ser nada.

À parte isso, tenho em mim todos os sonhos do mundo.

**Comment by jensopetersen** [comment]
Hi Sebastian,

To change the owner of the collection, open eXide from the Dashboard, log in as admin, enter

	sm:chown(' /db/eebo/', 'fernando')

(using an actual username as the second argument),

and click Eval.

Best,

Jens

PS: I see that you do not index the collection. You will probably want to do that. Have a look at the Shakespeare app and <http://exist-db.org/exist/apps/doc/indexing.xml>.

On 19 Feb 2015 at 23:29:24, Sebastian Rahtz (notifications@github.com) wrote:

I was working in the simple "Collections" thing (
http://eebotcp.cloudapp.net:8080/exist/apps/dashboard/index.html). All I
wanted to was change the ownership of the whole collection, but I when I
select the collection name and try to change that, the lower pane just
starts endlessly "Loading...". Which puzzled me. I didn't want to change
all the texts in there, just the collection itself.

thanks for pointers about doing this sort of thing in XQuery. That's a bit
beyond my level as a (very rusty...) naive XQuery user.

On 19 February 2015 at 19:27, Dannes Wessels <notifications@github.com>
wrote:

> An option could be to enable http compression in the XMLRPC interface....
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/eXist-db/exist/issues/485#issuecomment-75118599>.
>



--

Sebastian Rahtz

Director (Research) of Academic IT

University of Oxford IT Services

13 Banbury Road, Oxford OX2 6NN. Phone +44 1865 283431


Não sou nada.

Nunca serei nada.

Não posso querer ser nada.

À parte isso, tenho em mim todos os sonhos do mundo.

**Comment by jensopetersen** [comment]
Make that 

sm:chown(xs:anyURI(' /db/eebo/'), 'fernando')

Sorry,

Jens

On 20 Feb 2015 at 00:02:03, Jens Østergaard Petersen (oesterg@gmail.com) wrote:

Hi Sebastian,

To change the owner of the collection, open eXide from the Dashboard, log in as admin, enter

sm:chown(' /db/eebo/', 'fernando')

(using an actual username as the second argument),

and click Eval.

Best,

Jens

PS: I see that you do not index the collection. You will probably want to do that. Have a look at the Shakespeare app and <http://exist-db.org/exist/apps/doc/indexing.xml>.

On 19 Feb 2015 at 23:29:24, Sebastian Rahtz (notifications@github.com) wrote:

I was working in the simple "Collections" thing (
http://eebotcp.cloudapp.net:8080/exist/apps/dashboard/index.html). All I
wanted to was change the ownership of the whole collection, but I when I
select the collection name and try to change that, the lower pane just
starts endlessly "Loading...". Which puzzled me. I didn't want to change
all the texts in there, just the collection itself.

thanks for pointers about doing this sort of thing in XQuery. That's a bit
beyond my level as a (very rusty...) naive XQuery user.

On 19 February 2015 at 19:27, Dannes Wessels <notifications@github.com>
wrote:

> An option could be to enable http compression in the XMLRPC interface....
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/eXist-db/exist/issues/485#issuecomment-75118599>.
>



--

Sebastian Rahtz

Director (Research) of Academic IT

University of Oxford IT Services

13 Banbury Road, Oxford OX2 6NN. Phone +44 1865 283431


Não sou nada.

Nunca serei nada.

Não posso querer ser nada.

À parte isso, tenho em mim todos os sonhos do mundo.

**Comment by sebastianrahtz** [comment]
thanks, Jens! makes sense.

Yes, I am indexing that huge great collection now. Its not a real
production system, i was just curious to see how long it would take me to
set up an eXist server using Azure.

Sebastian
