### ISSUE TITLE
[BUG] enforce-index-use is omitting search results 

### ISSUE THREAD

**Issue by marmoure** [eXist-db/exist#4884]
`enforce-index-use` is a value that is set in `etc/conf.xml`  and documented as follows:
```
 enforce-index-use
               When set to "strict", eXist will not use a range index unless all
                collections in the context sequence define it. When set to
                "always", the query engine will still use an index, even if only
                one collection has it defined. It thus leaves it to the user to
                properly define indexes and if you forget to specify an index on
                a particular collection, it will be missing in the results.
``` 
The value, by default, is set to `always`, and according to the documentation, this means it will ignore any collection without an index defined.
Most users are unaware of this, for eg: #3620. I found it while trying to fix the issue just mentioned. The following is the code that lead me to this discovery: https://github.com/eXist-db/exist/blob/165bbc58a3cf126a1749000f9a794395e80c39c0/exist-core/src/main/java/org/exist/xquery/pragmas/Optimize.java#L342
I don’t think the default value should be `always`. Ignoring search results without users knowledge should not be the default case.
@joewiz @adamretter

**Comment by adamretter** [comment]
> I don’t think the default value should be always. Ignoring search results without users knowledge should not be the default case.

I am inclined to agree with you @marmoure . Do you want to send a PR to change the default please?

**Comment by joewiz** [comment]
Very interesting. I see that this feature was introduced by @wolfgangmm in February 2012 here - https://github.com/eXist-db/exist/commit/176313ce50390631c65bccbc732ad7150b2b546f - and enhanced in September 2012 here - https://github.com/eXist-db/exist/commit/e295fd5f4ea1668cf4dc65215a18d3df1859e6ed.

I agree that eXist should default to "correctness" and let users opt in to an optimization that may exclude expected results, if they understand the feature. 

I don't see tests for this feature. I think this would be a good opportunity to add some basic tests. The XQSuite tests that I contributed to #3620 could serve as a way to prove that eXist is respecting the "strict" setting, and I could easily adjust them to assume an "always" setting. Unfortunately XQSuite doesn't have a way to dynamically change conf.xml values. Would this need a Java-based test? I'm happy to pitch in if I can.
