### ISSUE TITLE
Usage of xmlns:xml prefix causes org.exist.xquery.XPathException: exerr:ERROR err:XQST0070 can not redefine 'xmlns:xml'

### ISSUE THREAD

**Issue by agucabral21** [eXist-db/exist#494]
When using a xml document which has xmlns:xml="http://www.w3.org/XML/1998/namespace" declaration, exist returns org.exist.xquery.XPathException: exerr:ERROR err:XQST0070 can not redefine 'xmlns:xml'.

But according to the spec, it should raise no error because the prefix is using the correct namespace. It is correct to raise an error if the namespace were different to "http://www.w3.org/XML/1998/namespace" 

I think the error is caused here https://github.com/eXist-db/exist/blob/develop/src/org/exist/xquery/ElementConstructor.java#L109

You can find an example of the bug here:
```
xquery version "3.0";
let $row := <parent xmlns:xml="http://www.w3.org/XML/1998/namespace">
                <dummyElement>blabla</dummyElement>
            </parent>
return $row
```

**Comment by shabanovd** [comment]
On Thu, Feb 26, 2015 at 5:58 PM, Agustin Cabral <notifications@github.com>
wrote:

> When using a xml document which has xmlns:xml="
> http://www.w3.org/XML/1998/namespace" declaration, exist returns
> org.exist.xquery.XPathException: exerr:ERROR err:XQST0070 can not redefine
> 'xmlns:xml'.
>
> But according to the spec, it should raise no error because the prefix is
> using the correct namespace. It is correct to raise an error if the
> namespace were different to "http://www.w3.org/XML/1998/namespace"
>
> I think the error is caused here
> https://github.com/eXist-db/exist/blob/develop/src/org/exist/xquery/ElementConstructor.java#L109
>
> You can find an example of the bug here:
>
> xquery version "3.0";
> let $row :=
> blabla
>
> return $row
>

I can't run that script -(

-- 
Dmitriy Shabanov

**Comment by agucabral21** [comment]
There! sorry!

'xquery version "3.0";'
'let $row := <parent xmlns:xml="http://www.w3.org/XML/1998/namespace"> ''<dummyElement>blabla</dummyElement> </parent>'
'return $row'

**Comment by agucabral21** [comment]
I fixed it in the first comment, sorry!

**Comment by jensopetersen** [comment]
The code at https://github.com/eXist-db/exist/blob/develop/src/org/exist/xquery/ElementConstructor.java#L109 doesn't really check for the four conditions listed at http://www.w3.org/TR/xpath-30/#ERRXQST0070. As Augustin writes, it is not an error to apply the default xml namespace, if one does so correctly. Case is also relevant.
