### ISSUE TITLE
xmldb:create-collection() and encoding

### ISSUE THREAD

**Issue by ChiSamurai** [eXist-db/exist#495]
Some time ago we have been struggling with encoding in our collection-names. For example: `xmldb:create-collection()` allows creating collections with unencoded `@`  like `a@b` which then indeed is created and accessible by XQuery functions. Using that function with `xmldb:encode-uri("a@b")` also works, resulting two different collections: `a@b` and `a%40b`. 

This leads to some issues using WebDAV and JAC: "a@b" is not accessible by JAC, "a%40b" not accessible by WebDAV (tried with Konqueror). 

Referring to RFC3986 (Uniform Resource Identifier: Generic Syntax) there are reserved characters for controlling, seperating etc. and i.e. the "@" char is reserverd as well:

http://tools.ietf.org/html/rfc3986#section-2.2
http://en.wikipedia.org/wiki/Percent-encoding

Since the function call looks like this

```xquery
xmldb:create-collection($target-collection-uri as xs:string, $new-collection as 
xs:string) as xs:string?
```
unencoded strings are indeed accepted. Shouldn't this be avoided?

To avoid creating of non-RFC-compliant URIs, changing the function call to only accept `xs:anyURI` as `$new-collection` would solve this IMHO. But this would probably mean incompatibilities to existing apps, maybe an inner-function encoding of the submitted string would be a more compatible solution? Of course only if you see this as an issue at all :)

**Comment by adamretter** [comment]
I think this is likely related/similar to https://github.com/eXist-db/exist/pull/127

**Comment by hungerburg** [comment]
The @ character belongs to the reserved set, yet it is explicitly allowed to appear literally in path-segments of the path-component of a URI (RFC text section-3.3). Eg http://email.directory/someone@host.com is a fully RFC-compliant URI that needs no special encoding.

**Comment by adamretter** [comment]
@hungerburg Are you saying that this is acceptable behaviour?

**Comment by hungerburg** [comment]
@adamretter I do not know, if I fully understand. At first look there are two parts: HTTP REST space and WEBDAV space. HTTP is a subset of DAV, if I am not mistaken. So they should follow the same rules. I think that the recent commit https://github.com/eXist-db/exist/commit/2c00a7b85471400b9e556f36957e043ab483300a will bring them more in line. Although the @ sign is missing from the unit test, an HTTP PUT will most likely leave it unencoded. And that is the way it ought to be, it seems to me.

Then there is the underlying FS (in the case of binares) or eXist-db's XML store. All relevant filesystems can handle the @ sign in a filename and the xml-store can too. XML store can even handle slashes in filenames which only apple FS can, which fails at colons though. Then there is xmldb:uri. I dare not speak of it.

**Comment by ChiSamurai** [comment]
To give you an example on that issue:

1. xmldb:create-collection(xmldb:encode-uri("/db/test@test1"))
2. xmldb:create-collection("/db/test@test1")
3. put different ressources in there

this leads to two different collections since the FS obviously can handle that. Accessing them using xmldb-functions works fine. But with WebDAV or by REST, the encoded one is not accessible. They are accessible on Java admin client, but JAC can't handle the unencoded one correctly: it is displaying bot (with the same name), but trying to enter the unencoded collection leads to the encoded one.

**Comment by adamretter** [comment]
@dizzzz this sounds like it could be an issue in the WebDAV client?

**Comment by dizzzz** [comment]
It would then be an issue where the internal API is invoked... where much of the code is in essence copied from other places. The Data provided by the milton API should be OK though.

**Comment by hungerburg** [comment]
I'm on CC, so here my take: The report of 12 Aug 2015 starts quite clear; `xmldb:encode-uri("/db/test@test1")` is not the same as `"/db/test@test1"`; while it should be: The &#64; sign is _pchar_ in RFC speak. Then it gets murky: Did the OP use the - then not released - re-factored REST service? Can JAC browse the encoded path?
Generally, I'd say, xmldb:encode-uri() considered harmful. REST and WebDAV are right :)

**Comment by duncdrum** [comment]
consolidating this with #1824 all different sides of the same coin
