### ISSUE TITLE
Dashboard an eXide keep on losing authentication when contextPath is set to / and port is set to 80

### ISSUE THREAD

**Issue by lcahlander** [eXist-db/exist#497]
With the following jetty.xml, then authentication keeps on getting lost in both the dashboard and eXide.  

&lt;?xml version="1.0"?&gt;
&lt;!DOCTYPE Configure PUBLIC "-//Jetty//Configure//EN" "http://www.eclipse.org/jetty/configure.dtd"&gt;

&lt;!-- =============================================================== --&gt;
&lt;!-- Configure the Jetty Server                                      --&gt;
&lt;!--                                                                 --&gt;
&lt;!-- Documentation of this file format can be found at:              --&gt;
&lt;!-- http://wiki.eclipse.org/Jetty/Reference/jetty.xml_syntax        --&gt;
&lt;!--                                                                 --&gt;
&lt;!-- $Id$          --&gt;
&lt;!-- =============================================================== --&gt;

&lt;Configure id="Server" class="org.eclipse.jetty.server.Server"&gt;

  &lt;!-- =========================================================== --&gt;
  &lt;!-- Server Thread Pool                                          --&gt;
  &lt;!-- =========================================================== --&gt;
  &lt;Set name="ThreadPool"&gt;
    &lt;!-- Default queued blocking threadpool --&gt;
    &lt;New class="org.eclipse.jetty.util.thread.QueuedThreadPool"&gt;
      &lt;Set name="name"&gt;eXistThread&lt;/Set&gt;
      &lt;Set name="minThreads"&gt;10&lt;/Set&gt;
      &lt;Set name="maxThreads"&gt;200&lt;/Set&gt;
      &lt;Set name="detailedDump"&gt;false&lt;/Set&gt;
    &lt;/New&gt;
  &lt;/Set&gt;

  &lt;!-- ============================================================ --&gt;
  &lt;!-- Set connectors                                               --&gt;
  &lt;!-- See http://wiki.eclipse.org/Jetty/Howto/Configure_Connectors --&gt;
  &lt;!-- ============================================================ --&gt;

  &lt;Call name="addConnector"&gt;
    &lt;Arg&gt;
      &lt;New class="org.eclipse.jetty.server.nio.SelectChannelConnector"&gt;
        &lt;Set name="host"&gt;&lt;SystemProperty name="jetty.host"/&gt;&lt;/Set&gt;
        &lt;Set name="port"&gt;&lt;SystemProperty name="jetty.port" default="80"/&gt;&lt;/Set&gt;
        &lt;Set name="maxIdleTime"&gt;300000&lt;/Set&gt;
        &lt;Set name="Acceptors"&gt;2&lt;/Set&gt;
        &lt;Set name="statsOn"&gt;false&lt;/Set&gt;
        &lt;Set name="confidentialPort"&gt;&lt;SystemProperty name="jetty.port.ssl" default="443"/&gt;&lt;/Set&gt;
        &lt;Set name="lowResourcesConnections"&gt;20000&lt;/Set&gt;
        &lt;Set name="lowResourcesMaxIdleTime"&gt;5000&lt;/Set&gt;
      &lt;/New&gt;
    &lt;/Arg&gt;
  &lt;/Call&gt;

  &lt;!-- Configuration classes to use for /exist context --&gt;
  &lt;Array id="plusConfig" type="java.lang.String"&gt;
       &lt;Item&gt;org.eclipse.jetty.webapp.WebInfConfiguration&lt;/Item&gt;
       &lt;Item&gt;org.eclipse.jetty.webapp.WebXmlConfiguration&lt;/Item&gt;
       &lt;Item&gt;org.eclipse.jetty.webapp.MetaInfConfiguration&lt;/Item&gt;
       &lt;Item&gt;org.eclipse.jetty.webapp.FragmentConfiguration&lt;/Item&gt;
       &lt;Item&gt;org.eclipse.jetty.annotations.AnnotationConfiguration&lt;/Item&gt;
       &lt;Item&gt;org.eclipse.jetty.webapp.JettyWebXmlConfiguration&lt;/Item&gt;
  &lt;/Array&gt;

  &lt;!-- =========================================================== --&gt;
  &lt;!-- Set handler Collection Structure                            --&gt;
  &lt;!-- =========================================================== --&gt;
  &lt;Set name="handler"&gt;
    &lt;New id="Handlers" class="org.eclipse.jetty.server.handler.HandlerCollection"&gt;
      &lt;Set name="handlers"&gt;
        &lt;Array type="org.eclipse.jetty.server.Handler"&gt;
          &lt;Item&gt;
            &lt;New id="exist-webapp-context" class="org.exist.jetty.WebAppContext"&gt;
              &lt;!-- can either be '/exist' or '/' --&gt;
              &lt;Set name="contextPath"&gt;/&lt;/Set&gt;
              &lt;Set name="war"&gt;&lt;SystemProperty name="jetty.home" default="."/&gt;/../../webapp/&lt;/Set&gt;
              &lt;Set name="defaultsDescriptor"&gt;&lt;SystemProperty name="jetty.home" default="."
                /&gt;/etc/webdefault.xml&lt;/Set&gt;
              &lt;Set name="tempDirectory"&gt;&lt;SystemProperty name="jetty.home" default="."/&gt;/tmp&lt;/Set&gt;
              &lt;Set name="configurationClasses"&gt;&lt;Ref id="plusConfig"/&gt;&lt;/Set&gt;
              &lt;Call name="setAttribute"&gt;
                &lt;Arg&gt;org.eclipse.jetty.server.webapp.ContainerIncludeJarPattern&lt;/Arg&gt;
                &lt;Arg&gt;.*/servlet-api-[^/]*\.jar$|.*/content/.*\.jar$&lt;/Arg&gt;
              &lt;/Call&gt;
            &lt;/New&gt;
          &lt;/Item&gt;
          &lt;Item&gt;
            &lt;New id="Contexts" class="org.eclipse.jetty.server.handler.ContextHandlerCollection"/&gt;
          &lt;/Item&gt;
          &lt;Item&gt;
            &lt;New id="DefaultHandler" class="org.eclipse.jetty.server.handler.DefaultHandler"/&gt;
          &lt;/Item&gt;
          &lt;Item&gt;
            &lt;New id="RequestLog" class="org.eclipse.jetty.server.handler.RequestLogHandler"/&gt;
          &lt;/Item&gt;
        &lt;/Array&gt;
      &lt;/Set&gt;
    &lt;/New&gt;
  &lt;/Set&gt;

  &lt;!-- =========================================================== --&gt;
  &lt;!-- extra options                                               --&gt;
  &lt;!-- =========================================================== --&gt;
  &lt;Set name="stopAtShutdown"&gt;true&lt;/Set&gt;
  &lt;Set name="sendServerVersion"&gt;true&lt;/Set&gt;
  &lt;Set name="sendDateHeader"&gt;true&lt;/Set&gt;
  &lt;Set name="gracefulShutdown"&gt;1000&lt;/Set&gt;
  &lt;Set name="dumpAfterStart"&gt;false&lt;/Set&gt;
  &lt;Set name="dumpBeforeStop"&gt;false&lt;/Set&gt;

  &lt;!-- inclusions below --&gt;

  &lt;!-- =============================================================== --&gt;
  &lt;!-- Create the deployment manager                                   --&gt;
  &lt;!-- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - --&gt;
  &lt;!-- The deplyment manager handles the lifecycle of deploying web    --&gt;
  &lt;!-- applications. Apps are provided by instances of the             --&gt;
  &lt;!-- AppProvider interface.  Typically these are provided by         --&gt;
  &lt;!-- one or more of:                                                 --&gt;
  &lt;!--   jetty-webapps.xml       - monitors webapps for wars and dirs  --&gt;
  &lt;!--   jetty-contexts.xml      - monitors contexts for context xml   --&gt;
  &lt;!--   jetty-templates.xml     - monitors contexts and templates     --&gt;
  &lt;!-- =============================================================== --&gt;
  &lt;!-- from: jetty-deploy.xml--&gt;

  &lt;Call name="addBean"&gt;
    &lt;Arg&gt;
      &lt;New id="DeploymentManager" class="org.eclipse.jetty.deploy.DeploymentManager"&gt;
        &lt;Set name="contexts"&gt;
          &lt;Ref id="Contexts"/&gt;
        &lt;/Set&gt;

        &lt;!-- Add a customize step to the deployment lifecycle --&gt;
        &lt;!-- uncomment and replace DebugBinding with your extended AppLifeCycle.Binding class 
          &lt;Call name="insertLifeCycleNode"&gt;
            &lt;Arg&gt;deployed&lt;/Arg&gt;
            &lt;Arg&gt;starting&lt;/Arg&gt;
            &lt;Arg&gt;customise&lt;/Arg&gt;
          &lt;/Call&gt;
          &lt;Call name="addLifeCycleBinding"&gt;
            &lt;Arg&gt;
              &lt;New class="org.eclipse.jetty.deploy.bindings.DebugBinding"&gt;
                &lt;Arg&gt;customise&lt;/Arg&gt;
              &lt;/New&gt;
            &lt;/Arg&gt;
          &lt;/Call&gt;
          --&gt;
      &lt;/New&gt;
    &lt;/Arg&gt;
  &lt;/Call&gt;

  &lt;!-- =============================================================== --&gt;
  &lt;!-- Add a ContextProvider to the deployment manager                 --&gt;
  &lt;!-- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - --&gt;
  &lt;!-- This scans the webapps directory for war files and directories  --&gt;
  &lt;!-- to deploy.                                                      --&gt;
  &lt;!-- This configuration must be used with jetty-deploy.xml, which    --&gt;
  &lt;!-- creates the deployment manager instance                         --&gt;
  &lt;!-- =============================================================== --&gt;
  &lt;!-- from: jetty-contexts.xml --&gt;

  &lt;Ref id="DeploymentManager"&gt;
    &lt;Call name="addAppProvider"&gt;
      &lt;Arg&gt;
        &lt;New class="org.eclipse.jetty.deploy.providers.ContextProvider"&gt;
          &lt;Set name="monitoredDirName"&gt;&lt;SystemProperty name="jetty.home" default="."
            /&gt;/contexts&lt;/Set&gt;
          &lt;Set name="scanInterval"&gt;10&lt;/Set&gt;
        &lt;/New&gt;
      &lt;/Arg&gt;
    &lt;/Call&gt;
  &lt;/Ref&gt;

  &lt;!-- =============================================================== --&gt;
  &lt;!-- Add a WebAppProvider to the deployment manager                  --&gt;
  &lt;!-- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - --&gt;
  &lt;!-- This scans the webapps directory for war files and directories  --&gt;
  &lt;!-- to deploy.                                                      --&gt;
  &lt;!-- This configuration must be used with jetty-deploy.xml, which    --&gt;
  &lt;!-- creates the deployment manager instance                         --&gt;
  &lt;!-- =============================================================== --&gt;
  &lt;!-- from: jetty-webapps.xml --&gt;

  &lt;Ref id="DeploymentManager"&gt;
    &lt;Call id="webappprovider" name="addAppProvider"&gt;
      &lt;Arg&gt;
        &lt;New class="org.eclipse.jetty.deploy.providers.WebAppProvider"&gt;
          &lt;Set name="monitoredDirName"&gt;&lt;SystemProperty name="jetty.home" default="."/&gt;/webapps&lt;/Set&gt;
          &lt;Set name="defaultsDescriptor"&gt;&lt;SystemProperty name="jetty.home" default="."
            /&gt;/etc/webdefault.xml&lt;/Set&gt;
          &lt;Set name="scanInterval"&gt;10&lt;/Set&gt;
          &lt;Set name="contextXmlDir"&gt;&lt;SystemProperty name="jetty.home" default="."/&gt;/contexts&lt;/Set&gt;
          &lt;Set name="extractWars"&gt;true&lt;/Set&gt;
        &lt;/New&gt;
      &lt;/Arg&gt;
    &lt;/Call&gt;
  &lt;/Ref&gt;

  &lt;!-- =========================================================== --&gt;
  &lt;!-- Configure Authentication Login Service                      --&gt;
  &lt;!-- =========================================================== --&gt;
  &lt;Call class="java.lang.System" name="setProperty"&gt;
    &lt;Arg&gt;java.security.auth.login.config&lt;/Arg&gt;
    &lt;Arg&gt;&lt;SystemProperty name="jetty.home" default="."/&gt;/etc/login.conf&lt;/Arg&gt;
  &lt;/Call&gt;

  &lt;Call name="addBean"&gt;
    &lt;Arg&gt;
      &lt;New class="org.eclipse.jetty.plus.jaas.JAASLoginService"&gt;
        &lt;Set name="name"&gt;JAASLoginService&lt;/Set&gt;
        &lt;Set name="LoginModuleName"&gt;eXistDB&lt;/Set&gt;
      &lt;/New&gt;
    &lt;/Arg&gt;
  &lt;/Call&gt;

  &lt;!-- =============================================================== --&gt;
  &lt;!-- Configure SSL for the Jetty Server                              --&gt;
  &lt;!-- this configuration file should be used in combination with      --&gt;
  &lt;!-- other configuration files.  e.g.                                --&gt;
  &lt;!--    java -jar start.jar etc/jetty-ssl.xml                        --&gt;
  &lt;!--                                                                 --&gt;
  &lt;!--  alternately, add to the start.ini for easier usage             --&gt;
  &lt;!-- =============================================================== --&gt;

  &lt;Call name="addConnector"&gt;
    &lt;Arg&gt;
      &lt;New class="org.eclipse.jetty.server.ssl.SslSelectChannelConnector"&gt;
        &lt;Arg&gt;
          &lt;New class="org.eclipse.jetty.http.ssl.SslContextFactory"&gt;
            &lt;Set name="keyStore"&gt;&lt;SystemProperty name="jetty.home" default="."/&gt;/etc/keystore&lt;/Set&gt;
            &lt;Set name="keyStorePassword"&gt;secret&lt;/Set&gt;
            &lt;Set name="keyManagerPassword"&gt;secret&lt;/Set&gt;
            &lt;Set name="trustStore"&gt;&lt;SystemProperty name="jetty.home" default="."
              /&gt;/etc/keystore&lt;/Set&gt;
            &lt;Set name="trustStorePassword"&gt;secret&lt;/Set&gt;
          &lt;/New&gt;
        &lt;/Arg&gt;
        &lt;Set name="Port"&gt;&lt;SystemProperty name="jetty.port.ssl" default="443"/&gt;&lt;/Set&gt;
        &lt;Set name="maxIdleTime"&gt;30000&lt;/Set&gt;
        &lt;!-- 
           &lt;Set name="Acceptors"&gt;2&lt;/Set&gt;
           &lt;Set name="AcceptQueueSize"&gt;100&lt;/Set&gt; 
           --&gt;
      &lt;/New&gt;
    &lt;/Arg&gt;
  &lt;/Call&gt;

  &lt;!-- =============================================================== --&gt;
  &lt;!-- Configure request log handler       			                --&gt;
  &lt;!-- http://wiki.eclipse.org/Jetty/Howto/Configure_Request_Logs      --&gt;
  &lt;!-- =============================================================== --&gt;
  &lt;Ref id="RequestLog"&gt;
    &lt;Set name="requestLog"&gt;
      &lt;New id="RequestLogImpl" class="org.eclipse.jetty.server.NCSARequestLog"&gt;
        &lt;Arg&gt;&lt;SystemProperty name="jetty.home" default="."/&gt;/logs/yyyy_mm_dd.request.log&lt;/Arg&gt;
        &lt;Set name="retainDays"&gt;90&lt;/Set&gt;
        &lt;Set name="append"&gt;true&lt;/Set&gt;
        &lt;Set name="extended"&gt;false&lt;/Set&gt;
        &lt;Set name="LogTimeZone"&gt;GMT&lt;/Set&gt;
      &lt;/New&gt;
    &lt;/Set&gt;
  &lt;/Ref&gt;

  &lt;!-- =============================================================== --&gt;
  &lt;!-- Configure stderr and stdout to a Jetty rollover log file        --&gt;
  &lt;!-- this configuration file should be used in combination with      --&gt;
  &lt;!-- other configuration files.  e.g.                                --&gt;
  &lt;!--    java -jar start.jar etc/jetty-logging.xml                    --&gt;
  &lt;!-- =============================================================== --&gt;

  &lt;!-- &lt;New id="ServerLog" class="java.io.PrintStream"&gt;
       &lt;Arg&gt;
         &lt;New class="org.eclipse.jetty.util.RolloverFileOutputStream"&gt;
           &lt;Arg&gt;&lt;SystemProperty name="jetty.home" default="."/&gt;/logs/yyyy_mm_dd.stderrout.log&lt;/Arg&gt;
           &lt;Arg type="boolean"&gt;false&lt;/Arg&gt;
           &lt;Arg type="int"&gt;90&lt;/Arg&gt;
           &lt;Arg&gt;&lt;Call class="java.util.TimeZone" name="getTimeZone"&gt;&lt;Arg&gt;GMT&lt;/Arg&gt;&lt;/Call&gt;&lt;/Arg&gt;
           &lt;Get id="ServerLogName" name="datedFilename"/&gt;
         &lt;/New&gt;
       &lt;/Arg&gt;
     &lt;/New&gt;

     &lt;Call class="org.eclipse.jetty.util.log.Log" name="info"&gt;&lt;Arg&gt;Redirecting stderr/stdout to &lt;Ref id="ServerLogName"/&gt;&lt;/Arg&gt;&lt;/Call&gt;
     &lt;Call class="java.lang.System" name="setErr"&gt;&lt;Arg&gt;&lt;Ref id="ServerLog"/&gt;&lt;/Arg&gt;&lt;/Call&gt;
     &lt;Call class="java.lang.System" name="setOut"&gt;&lt;Arg&gt;&lt;Ref id="ServerLog"/&gt;&lt;/Arg&gt;&lt;/Call&gt; --&gt;

  &lt;!-- =========================================================== --&gt;
  &lt;!-- change java.io.tmpdir default value                         --&gt;
  &lt;!-- =========================================================== --&gt;
  &lt;Call class="java.lang.System" name="setProperty"&gt;
    &lt;Arg&gt;java.io.tmpdir&lt;/Arg&gt;
    &lt;Arg&gt;&lt;SystemProperty name="jetty.home" default="."/&gt;/tmp&lt;/Arg&gt;
  &lt;/Call&gt;
&lt;/Configure&gt;

**Comment by joewiz** [comment]
Your XML got mangled; surround it with 3 backticks (```) before & after, and it'll be formatted properly.

Also, some important info might include eXist version, browsers tried and version, and typical duration before session is lost or actions that trigger it.

**Comment by dizzzz** [comment]
no response? close  issue?
this tracker should NOT be a fire and forget location. No dumps please, and do a follow up when requested.

is this the default configuration? only add the actually changes.
