### ISSUE TITLE
Security setup in a docker context (remove guest access to exide)

### ISSUE THREAD

**Issue by LaurentNoyon** [eXist-db/exist#4970]
Hello dear existDB community,

I'm using exist in a docker context (and docker compose).

My DockerFile :

```
FROM existdb/existdb:5.3.1

RUN [ "java", "org.exist.start.Main", "client", "--no-gui",  "-l", "-u", "admin", "-P", "", "-x", "sm:passwd('admin', 'mypassword')" ]
```

I'm working on right access and security. In 5.3.1, it's possible to access database files by browsing eXide as a guest :
myurl/exist/apps/eXide/index.html 
or by accessing it with a direct link :
myurl/exist/apps/eXide/modules/load.xql?path=mypath

I would like to not give access to my data to a guest.

I have multiple ideas :

- remove guest user (but unfortunately it doesn't work I have a server error and I don't know if it would be possible to remove it automatically in a docker context)
![image](https://github.com/eXist-db/exist/assets/22801709/77f08f23-69e7-4c21-bcfa-6bcb923972fa)

- remove exide access, but then my admin account won't be able to browse data (and I would like to keep that)
![image](https://github.com/eXist-db/exist/assets/22801709/5cc10b8c-5942-4442-8197-0aa09b90da73)

- desactivate guest user but it doesn't seem to do anything
![image](https://github.com/eXist-db/exist/assets/22801709/e3739363-2301-4b5c-8d8d-ee6a9d58c62d)

Can you help me with that ? I would like to be able to access eXide only if I'm logged in with admin. 
Would it be possible to set it up automatically in a docker context or maybe after the build with some queries ?

Thanks in advance for your help.

**Comment by line-o** [comment]
@LaurentNoyon there is a setting in eXide that allows to limit access to it to logged in users. 
Sadly, this is currently not working properly. The underlying issue was fixed with https://github.com/eXist-db/eXide/pull/595 but this version of eXide is not released yet. 
What you can do is 

- clone the repository
- build the develop version of eXide
- install that version in your docker container
- configure eXide to only allow authorised users
- commit that change to your docker image

**Comment by ThomasPerraudin** [comment]
@line-o Do you know when this fixed version of eXide could be released?

**Comment by line-o** [comment]
@ThomasPerraudin the fix was released on May 11th https://github.com/eXist-db/eXide/releases/tag/v3.5.1 :tada:

**Comment by line-o** [comment]
@LaurentNoyon 

- install eXide 3.5.1 (via packagemanager for example)
- change configuration to disallow guest access
- commit change to docker container

**Comment by line-o** [comment]
@LaurentNoyon @ThomasPerraudin I see that this new version declares a minimum dependency on exist >= 6 .

**Comment by ThomasPerraudin** [comment]
@line-o Yes we will. Thank you.

**Comment by line-o** [comment]
@ThomasPerraudin I would recommend to go with 6.2.0

**Comment by duncdrum** [comment]
@LaurentNoyon you can install a different version of exide via the images  autodeploy folder as in the examples here https://github.com/eXist-db/exist/tree/develop/exist-docker/src/main/resources-filtered

**Comment by LaurentNoyon** [comment]
It seems that upgrading exist image to 6.2.0 also updated exide version to 3.5.0, and that version solves the security problem. Can you confirm that ? Where can I check which version of exide is installed with 6.2.0 docker image ?

Secondly, where should I copy my configuration file to restrict exide browsing only to logged users ? 
Should it be something like that ?
```COPY configuration.xml /exist/db/apps/eXide/configuration.xml```

Thanks for your help.

**Comment by line-o** [comment]
@LaurentNoyon The restricted access to eXide is not reliable in version 3.5.0: I was not able to access the application even when logged in. `v3.5.1` is the version were this works reliably.

Regarding automatically configuring eXide: I am not sure your command will succeed. I believe this will copy the file into the filesystem in the container but you will have to write it to the database instead. There are a number of options to do that.

[TEI-Publisher's Docker file](https://github.com/eeditiones/teipublisher-docker-compose/blob/0ae76787e00cc487075b246eaf9278568bf1b322/Dockerfile#L92) shows you how to initialise a existdb instance when setting up an instance inside of Docker.

After that eXide will be installed in the instance and you can run a command that will update the configuration using `bin/client.sh`.

What you can do while the instance of eXist inside the container is running is to
- use eXists REST API to `PUT` the file in the collection `/db/apps/eXide` (with curl) 
- use XML-RPC (through [xst](https://www.npmjs.com/package/@existdb/xst for example)

**Comment by LaurentNoyon** [comment]
Thanks for your help.

I managed to edit guest attribute to "no" using this query : 
`update replace collection(/db/apps/eXide)/configuration/restrictions/@guest with 'no'`

Now I still have a problem to update exide automatically from Dockerfile

I created a folder "build" next to my Dockerfile and placed eXide-3.5.1.xar inside (downloaded from here https://exist-db.org/exist/apps/public-repo/packages/eXide).
Then, in my Dockerfile : 
COPY build/*.xar /exist/autodeploy

The build doesn't show error.
Still, I'm stucked with version 3.5.0 when I look for version in exide/about menu. 

Do you have any idea why it won't take the xar file ?

**Comment by duncdrum** [comment]
Because autodeploy installs in alphabetical order change to the copy statement to this. 

```
COPY build/*.xar /exist/autodeploy/aaaa.xar
```

and you should be good.

**Comment by line-o** [comment]
@LaurentNoyon existdb will install all XARs in autodeploy in order of appearance _and_ will skip any package that is already installed.
It is very likely that the existing eXide XAR in autodeploy is installed first because of its lower version and then your newly added XAR is skipped because _a_ version of eXide is already installed.
Try removing any existing eXide version beforehand.
