### ISSUE TITLE
[BUG] type cast after arrow operator with empty-sequence as input causes cardinality error

### ISSUE THREAD

**Issue by PieterLamers** [eXist-db/exist#4971]
**Describe the bug**
Forwarding an non-existent node to a function that accepts an empty-sequence returns err:XPTY0004 
`Invalid cardinality for parameter $vp0. Expected exactly one, got 0 [at line 1, column 6, source: String/267377182041421505]`

**Expected behavior**
I expect an empty-sequence

**To Reproduce**
```
let $test := <foo/>
return $test/bar => xs:integer()
```
produces the error where it should return empty sequence. In contrast,

```
let $test := <foo/>
return $test/bar ! xs:integer(.)
``` 
works as expected.

**Context (please always complete the following information)**

 - Build: [eXist-6.2.0]
 - Java: openjdk 11.0.17
 - OS: Windows 10, Linux

**Additional context**
none relevant (I think)

**Comment by line-o** [comment]
I am able to reproduce the issue and it seems to be unrelated to node sets but applies to the `empty-sequence()` in general:

```xquery
xs:integer(()) 
```

evaluates to an empty sequence whereas

```xquery
() => xs:integer()
```

raises the error.

**Comment by line-o** [comment]
It seems to be specific to `xs:integer#1` since 

```xquery
() => number()
```

works fine.

**Comment by PieterLamers** [comment]
@line-o updated the title of the bug to reflect your findings. I think there could be more functions with this problem, as I have encountered the vp0 error more often.

**Comment by line-o** [comment]
@PieterLamers I was able to find the root cause and now I am sure it only applies to type casts (`xs:*`). I hope you do not mind that I reflect that in the title of this issue.

**Comment by dizzzz** [comment]
please could you add a link to the spec?

**Comment by PieterLamers** [comment]
@dizzzz here you go: https://www.w3.org/TR/xpath-functions-31/#constructor-functions
