### ISSUE TITLE
[BUG] file:directory-list#2 does not properly report an error on a non-existent directory

### ISSUE THREAD

**Issue by PieterLamers** [eXist-db/exist#5028]
**Describe the bug**
The Java code of `DirectoryList` throws an `IllegalStateException` when a non-existent directory is supplied as its first argument, which is an unchecked exception and therefore not caught in Java. From Oxygen, this results in a `Failed to invoke method queryPT in class org.exist.xmlrpc.RpcConnection:` message.

**Expected behavior**
We expect an XQuery error to be thrown with module, line number and column information.

**To Reproduce**
Assuming a non-existent path `/foo` run the following : 
`file:directory-list('/foo', '*')`

 - Build: [eXist-6.2.0]
 - Java: [1.8.0_347]
 - OS:  Windows 10

**Comment by nverwer** [comment]
I think that this can be solved by adding the following in DirectoryList.java, line 175:

```
        } catch (final  IllegalStateException e) {
            throw new XPathException(this, e.getMessage());
```
