### ISSUE TITLE
lang() function raises type error

### ISSUE THREAD

**Issue by jensopetersen** [eXist-db/exist#504]
This code should return the first desc element:

	xquery version "3.0";
	let $doc :=
	<desclist xml:lang="en">
		<desc xml:lang="en-US">
			<line>The first line of the description.</line>
		</desc>
		<desc xml:lang="fr">
			<line>La premi&#232;re ligne de la déscription.</line>
		</desc>
	</desclist>
	return
		$doc//desc[lang("en-US")]

It raises a type error (XPTY0004).

**Comment by ljo** [comment]
Yes, this seems to be the same as a previous issue with fn:lang. I have started to fix it.
