### ISSUE TITLE
Can't build an installer from working instance

### ISSUE THREAD

**Issue by amclark42** [eXist-db/exist#509]
Briefly: I cannot build an installer from a working installation of eXist without mucking around in the install code.

The long version:

Running eXist 2.2 (stable), I wanted to build a custom installer for local development work. To do so, I ran `./build.sh installer` from my working instance, then secure-copied the resulting JAR to my local Vagrant box. Installing on the VM worked fine, except that all the scripts in `$EXIST_HOME/bin/scripts` used the paths from the first installation - the one on my machine proper:
![screen shot 2015-03-10 at 1 50 48 pm](https://cloud.githubusercontent.com/assets/4063180/6581349/a56f4fe4-c72c-11e4-9570-8b56484dcfee.png)
![screen shot 2015-03-10 at 3 40 04 pm](https://cloud.githubusercontent.com/assets/4063180/6583647/d16247be-c73b-11e4-817d-1081c9932d8e.png)
I confirmed that I could change the paths manually/programmatically to get the new installation to work. This became plan B, since I much preferred to have the custom installer replace the paths and set the admin password.

When you run ./build.sh installer, izPack takes all the `*.sh` scripts in `$EXIST_HOME/bin` and copies them into `$EXIST_HOME/installer/scripts`, overwriting older files as necessary. This system is meant to work for people who want to build an installer from the source. Since my copy of eXistDB came prepackaged, the installer changed all `$EXIST_HOME/bin` scripts' references to `$JAVA_HOME` and `$EXIST_HOME` so they reflected the paths in my personal environment. And then, when I tried to build a new installer, those scripts (with those paths!) were copied over. Not great for sharing or re-use!

The overwriting scripts behavior is dictated by `$EXIST_HOME/build/scripts/installer.xml`, lines 197-209. I propose treating all the shell scripts like build.sh, [copying permissive scripts from `$EXIST_HOME/installer/scripts` into `$EXIST_HOME/bin`](https://github.com/eXist-db/exist/blob/develop/installer/scripts/build.sh), instead of the other way around.

![The main part of the installer fix](https://cloud.githubusercontent.com/assets/4063180/6584333/e1edbd66-c740-11e4-93a0-25ea425dfce5.png)

My solution was to comment out the script-copying behavior, as shown above. I also edited the scripts previously placed in `$EXIST_HOME/installer/scripts` back to their generalized, pre-install form. This worked perfectly. When I installed eXist on the VM, the scripts in `$EXIST_HOME/bin` had Vagrant VM-specific paths, and the scripts in `$EXIST_HOME/installer/scripts` retained their generalizable form. So I can build installations off of installations without worrying about paths.

![screen shot 2015-03-10 at 4 07 36 pm](https://cloud.githubusercontent.com/assets/4063180/6584327/dd36e54a-c740-11e4-925f-8bf2c5dc48b3.png)
![screen shot 2015-03-10 at 4 08 12 pm](https://cloud.githubusercontent.com/assets/4063180/6584330/df636262-c740-11e4-831c-8b2d5ba0eb8e.png)

**Comment by dizzzz** [comment]
The main use-case of these scripts are indeed to create an installer out of the git-repository.

I am not sure if I fully understand the change you are suggesting (does it work in our main use-case?) Please could you create a pull-request for your idea?

**Comment by amclark42** [comment]
I believe that this would work for both cases (build-from-source and build-from-installation). I'll send a pull request ASAP (need to set up git-flow).

**Comment by adamretter** [comment]
@dizzzz That is not the main use-case of the .sh scripts, see my comments in https://github.com/eXist-db/exist/pull/520
