### ISSUE TITLE
parentheses around context node disturb evaluation of ft: and range: functions

### ISSUE THREAD

**Issue by rvdb** [eXist-db/exist#522]
When the ft:query() function is called inside a predicate, parentheses around the context node seem to throw the evaluation of ft:query() in single-node execution mode, resulting in a substantial performance penalty.

This can be illustrated on the sample demo data in a vanilla eXist-2.2 installation. When following query is executed in eXide:

    collection('/db/apps/demo/data')//SCENE[ft:query(., 'the')]

...the resulting 71 nodes are found in +- 0.014 sec. When profiling is turned on in the Monex app, the "functions" tab doesn't list ft:query() after this query.

Yet, when the same query is run with parentheses around the context node for the predicate:

    collection('/db/apps/demo/data')//(SCENE)[ft:query(., 'the')]

...the resulting 71 nodes are found as well, but the query takes much longer: +- 0.4 sec. 
When profiling is turned on in the Monex app, the "functions" tab lists 72 calls for the ft:query() function. This number equals the total number of &lt;SPEECH> elements in the /db/apps/demo/data collection. In other words: due to the parentheses around the context node, the ft:query() function is evaluated separately for each context node (&lt;SPEECH>).

When testing this on the range index functions, I found another quirk:

    collection('/db/apps/demo/data')//SPEAKER[range:contains(., 't')]

...returns 236 nodes in 0.015 sec. Monex doesn't list the range:contains() function.

Wrapping the context node in parentheses:

    collection('/db/apps/demo/data')//(SPEAKER)[range:contains(., 't')]

...returns 0 nodes. Monex lists 1 range:contains() function call.

Note: the issue with range:contains() only occurs when this function is called directly. When called indirectly, via:

    collection('/db/apps/demo/data')//(SPEAKER)[contains(., 't')]

...the correct number of nodes is returned. No trace of range:contains() in Monex.

**Comment by adamretter** [comment]
I think this should have been closed by https://github.com/eXist-db/exist/pull/593. @rvdb @wolfgangmm can you confirm?
