### ISSUE TITLE
Delete the deprecated SOAP API

### ISSUE THREAD

**Issue by adamretter** [eXist-db/exist#532]
Hey guys, the SOAP API has been deprecated for a long time. I don't want to maintain it any more and I guess no one else does either. Can I delete it for the next release?

**Comment by ljo** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA1

Den 2015-03-19 11:10, Adam Retter skrev:
> Hey guys, the SOAP API has been deprecated for a long time. I don't want
> to maintain it any more and I guess no one else does either. Can I
> delete it for the next release?
>
Could we just make a small test poll to see how many actually using it
still? If it is a lot of people maybe find a maintainer otherwise I agree.

> —
> Reply to this email directly or view it on GitHub
> <https://github.com/eXist-db/exist/issues/532>.
> 

-----BEGIN PGP SIGNATURE-----
Version: GnuPG v2

iD8DBQFVCqHlhcIn5aVXOPIRAvitAKC5HSfzsCRl+036iKgGWiLeTaQcnACgvhe9
FvdTjogM03bn6EzTYKvN5ZA=
=j4p1
-----END PGP SIGNATURE-----

**Comment by dizzzz** [comment]
Probably yes, but sending out a question on exist open would be a good thing

**Comment by shabanovd** [comment]
+1 to remove or move to it own repo.

On Thu, Mar 19, 2015 at 1:10 PM, Adam Retter <notifications@github.com>
wrote:

> Hey guys, the SOAP API has been deprecated for a long time. I don't want
> to maintain it any more and I guess no one else does either. Can I delete
> it for the next release?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/eXist-db/exist/issues/532>.
>



-- 
Dmitriy Shabanov

**Comment by dizzzz** [comment]
One must contact the users first before removing a public API;

there as no maintenance, sure, but the code just works, why remove it then?
; moving it into an extension costs time.....

**Comment by shabanovd** [comment]
`the code just works` ... I'm not sure for 100% because there was some issues reports on ML

**Comment by shabanovd** [comment]
if we agree on move to extension somebody will/may find time for that -)

**Comment by JoernT** [comment]
I agree with Dannes - you can't know for sure if someone's probably relying on it. Though it's good thing to get rid of things that nobody really likes to put work in we still should ask before removing it.

**Comment by shabanovd** [comment]
I'm not against 'ask on ML', just some notes

**Comment by JoernT** [comment]
i can do it

**Comment by JoernT** [comment]
Ok, i've send a message to the list - if we don't hear something within a week or so i think we can remove it for next release.

**Comment by adamretter** [comment]
Thanks @JoernT.

The reason I want to remove it is because I am trying to modernise the API code as it is some of the oldest in eXist. If there is one less API I have to rewrite then that is good. If anyone wants to suggest removing any of the other APIs then I am open to suggestions...

**Comment by JoernT** [comment]
i completely with you in this point - if there's something nobody uses we should really get rid of it - it's just unnecessary noise then.

**Comment by adamretter** [comment]
Okay @JoernT asked on the exist-open mailing list. Due to a lack of requests to keep it, we will now remove it.

**Comment by dizzzz** [comment]
+1
