### ISSUE TITLE
Memory leak on backup restore with xquery triggers

### ISSUE THREAD

**Issue by line-o** [eXist-db/exist#5459]
**Describe the bug**

I was able to reproduce the memory leak using the original dataset provided by @dariok. With enough resources, about 10 GB of RAM, the process did finish successfully. After restoring the entire dataset of 35 GB, containing 26874 XML files (including .html, .xsl, .svg), almost 5 GB of RAM retained.

<img width="1567" alt="Screenshot 2023-07-04 at 14 24 36" src="https://github.com/eXist-db/exist/assets/657222/0c2ba6d8-b4ea-4324-95dc-85d576494b2b">

There is ~59000 instances of `TriggerStatePerThread$TriggerState`. Since I can see that there is two instances for each restored item that is ~29500 `CREATE_DOCUMENT` triggers - one for `BEFORE` and for the `AFTER` phase.
 
<img width="1156" alt="Screenshot 2023-07-05 at 11 32 00" src="https://github.com/eXist-db/exist/assets/657222/cc2d468a-f179-477b-8375-58fc6fbb43ce">

I was then wondering whether I was missing +3000 documents until I discovered that `CREATE_COLLECTION` was also invoked:
 
<img width="785" alt="Screenshot 2023-07-05 at 12 08 21" src="https://github.com/eXist-db/exist/assets/657222/9ac4a9ab-8c4e-4690-977b-9c7665113e94">
The original `collection.xconf` defines an update trigger as such:
```
 <triggers>
     <trigger event="update" class="org.exist.collections.triggers.XQueryTrigger">
         <parameter name="url" value="xmldb:exist:///db/apps/path/to/module.xql"/>
     </trigger>
</triggers>
```

With the `collection.xconf` as it is in the issue description (without any triggers configured) the outcome was very different. RAM usage stayed within reasonable bounds (<2 GB) and all memory was freed afterwards (see screenshot).
 
<img width="1569" alt="Screenshot 2023-07-05 at 09 26 17" src="https://github.com/eXist-db/exist/assets/657222/639767cf-d48b-47e7-a24b-0d49a10f9a40">

My analysis indicates that TriggerStates are held in memory indefinitely and are the cause of the leak. This is especially interesting as the events that were triggered are not the ones that are defined and thus one would not expect them to be fired at all.

**References**

refs #4890
refs #5295

**Expected behavior**

XQueryTriggerStates to be removed from memory once the trigger is done.

**To Reproduce**

If the above isn't working, please tell us the exact steps you took when you encountered the problem:

[full-backup-restore-with-triggers.zip](https://github.com/eXist-db/exist/files/15179694/full-backup-restore-with-triggers.zip)

1. start a clean instance of exist-db v6.2.0 with a profiler attached
2. restore the backup in the attached zip
3. the backup finishes
4. in the Profiler you should be able to find XqueryTriggerState instances that retain in memory

**Screenshots**

see above

**Context**

 - Build: eXist-6.2.0
 - Java: 1.8.0_352
 - OS: Mac OS X 14.5

**Additional context**
- How is eXist-db installed? built from source
- Any custom changes in e.g. `conf.xml`? none

**Comment by dizzzz** [comment]
images are not visible? 
![image](https://github.com/user-attachments/assets/4c010f6f-c611-4697-9618-7eed932517ed)

**Comment by adamretter** [comment]
@line-o Could we get an update please?

**Comment by line-o** [comment]
@adamretter Are you waiting for the screenshots? They are the same ones as in the other issue. I was expecting your PR, you were so eager to publish.
I really did not expect these to be important.

**Comment by adamretter** [comment]
> They are the same ones as in the other issue

@line-o Good to head - but we had no idea that was the case as you hadn't replied!
