### ISSUE TITLE
Broken tests on Travis-CI investigation 

### ISSUE THREAD

**Issue by shabanovd** [eXist-db/exist#547]
Let's try to find out why tests failing.

I see that problems starts right after `org.exist.collections.CollectionRemovalTest` or it happen before it?

Maybe we should try to disable test(s) (one that we'll think is problem maker) till tests start pass and enable it one by one till start failing again?

**Comment by adamretter** [comment]
@shabanovd Is this the travis-ci build?

**Comment by shabanovd** [comment]
yes, there

**Comment by adamretter** [comment]
If you ask Travis-CI support in their IRC room or by email, they can provide you with a hosted Travis VM for testing. This is probably the best approach. I did try and reproduce locally on Linux mint but could not.

**Comment by shabanovd** [comment]
TeamCity on RH give same errors

**Comment by adamretter** [comment]
@shabanovd Is that your own TeamCity? Maybe it is easier for you to chase the issue there...

**Comment by dizzzz** [comment]
if on RH gives similar results..... that is scary and encouraging the same time.

my question: what is the underlying filesystem? native? nfs3/4? iscsi?

**Comment by shabanovd** [comment]
ext4, but it can be virtual one ... need to check

**Comment by adamretter** [comment]
@shabanovd Any update on this?

**Comment by shabanovd** [comment]
Nothing so far

**Comment by duncdrum** [comment]
I can't locate the test on the latest builds is this still and issue, or superseded by later test-suite changes?
