### ISSUE TITLE
add a uninstall hook for xar packages

### ISSUE THREAD

**Issue by JoernT** [eXist-db/exist#550]
Currently there's a pre-install and post-install hook when deploying packages. Sometimes xar applications require additional resources that might exist outside of the database - in these cases an uninstall hook would be handy to erase all these external files from the system.

Other scenarios are:
- installation of files in the system collection
- creation of users and groups

Same applies here - would be nice if a xar would be able to cleanup when deleted from the database.

**Comment by dizzzz** [comment]
so you suggest a uninstall hook? (pre-uninstall or even post-)

**Comment by wolfgangmm** [comment]
This is already possible. Use <cleanup> in repo.xml and specify a query.
