### ISSUE TITLE
Delete the deprecated SOAPServer

### ISSUE THREAD

**Issue by adamretter** [eXist-db/exist#554]
Related to https://github.com/eXist-db/exist/issues/532

**Comment by dizzzz** [comment]
Also the soap server? hmmm :-/  I liked the wsdl like approach. But you are right....

**Comment by adamretter** [comment]
Sure it's a cool approach. A precursor which led me to develop RESTXQ. However this can be duplicated in XQuery or you could build atop RESTXQ. I did think about a SOAPXQ set of XQuery 3.0 annotations but unless someone pays me to implement them, I have more interesting spare-time projects :-)
