### ISSUE TITLE
[BUG] JNLP for eXist 6.3.0 release does not have references to bouncy castle libs

### ISSUE THREAD

**Issue by raducoravu** [eXist-db/exist#5544]
**Describe the bug**
Oxygen XML Editor uses the JNLP provided by the eXist server "exist/webstart/exist.jnlp" to check what libraries are referenced there and to download them for configuring the Exist connection from Oxygen to Exist.

**Expected behavior**
The exist.jnlp should refer all JAR libraries necessary by the eXist connector.
But when I use only the JAR libraries referenced from the  exist.jnlp in Oxygen I get an error when the connection is established:

     java.lang.NoClassDefFoundError: org/bouncycastle/crypto/ExtendedDigest
	at org.exist.util.crypto.digest.DigestType.<clinit>(DigestType.java:33)
	at org.exist.xmldb.RemoteCollection.getResource(RemoteCollection.java:428)

so I think the eXist JNLP should refer to some extra JAR libraries, the bouncycastle libraries.

**Comment by reinhapa** [comment]
@line-o as I remember one of the later bouncy castle libs has split out certain services to additional artifacts... maybe this causes the problem here..

**Comment by dizzzz** [comment]
@raducoravu  can I find a log file in the app? where to find on a Mac?

**Comment by dizzzz** [comment]
@raducoravu I have the ambition.... to change the connection mechanism. No download, pure xmlrpc or REST.... (we discussed it in Prague once I remember)

**Comment by dizzzz** [comment]
<img width="500" alt="image" src="https://github.com/user-attachments/assets/14c478a7-458c-4e8f-bffd-affdc1435c65">

**Comment by reinhapa** [comment]
> @reinhapa could this be caused by the changed xmldb-api jar?

Possible...

**Comment by line-o** [comment]
@dizzzz @reinhapa I was under the impression only the develop branch has the XMLDB API changes and not 6.x.x

**Comment by reinhapa** [comment]
> @dizzzz @reinhapa I was under the impression only the develop branch has the XMLDB API changes and not 6.x.x

As far as I know it should only differ on `develop` but I do not know the exact systems where that error from @dizzzz was coming from and more stack details are needed here...

**Comment by raducoravu** [comment]
With Oxygen 26.1 things seems to work just by adding a reference to bcprov-jdk18on-1.79.jar as @dizzzz did in the JNLP.
@dizzzz obtains another error related to "Collection.listChildCollections" because he is probably using an older Oxygen version. In Oxygen 26.1 I needed to write special code to take into account the API changes of the "Collection.listChildCollections" method.

**Comment by raducoravu** [comment]
> @raducoravu I have the ambition.... to change the connection mechanism. No download, pure xmlrpc or REST.... (we discussed it in Prague once I remember)

One could probably build an Oxygen Java-based plugin which handles the Exist DB connection in its own way, browsing files, opening, saving, imports and exports, running XQueries, but that would be quite a large undertake.

**Comment by reinhapa** [comment]
![image](https://github.com/user-attachments/assets/db0d07e4-c1a5-47ce-9ce8-b91c2cddc572)

@dizzzz the fix proposed on `develop` would work for Oxygen and `6.x.x`

**Comment by reinhapa** [comment]
> One could probably build an Oxygen Java-based plugin which handles the Exist DB connection in its own way, browsing files, opening, saving, imports and exports, running XQueries, but that would be quite a large undertake.

@raducoravu I would like to offer a complete gRPC Protobuf definition alongside with an updated [XMLDB::API](https://github.com/xmldb-org/) version that would open the creation of a simple remote client usable by Oxygen and others...

**Comment by raducoravu** [comment]
@reinhapa for now we do not have the human resources to re-implement our Exist DB connection using other APIs but if the APIs become available maybe we will in time.

**Comment by raducoravu** [comment]
@dizzzz we are using APIs like org.xmldb.api.base.Database.getCollection(String, String, String).
Besides using the APIs to list a collection's contents, open, save files we also seem to use APIs like "org.exist.xmldb.RemoteXPathQueryService.compileAndCheck(String)" to validate XQuery content.

**Comment by dizzzz** [comment]
Perfect :-) that will make things rather easy I think;

Let me have a look at it coming week...
