### ISSUE TITLE
Remove legacy full-text index

### ISSUE THREAD

**Issue by adamretter** [eXist-db/exist#556]
The legacy full-text index should be removed for the 3.0 release. We have been advising people not to use it since before eXist 2.0 was released!

**Comment by dizzzz** [comment]
Agree.

**Comment by wolfgangmm** [comment]
+1 Removing the index should not do any harm.

**Comment by adamretter** [comment]
I found some detail/discussion that I started about doing this previously: http://exist.markmail.org/thread/uymso4dl6idflmwc#query:+page:1+mid:uymso4dl6idflmwc+state:results

@wolfgangmm It would be good if you could give me any follow-up on that thread, i.e. if you have any strong thoughts on how to deal with `fn:matches`.

**Comment by dizzzz** [comment]
+1 :-)   note that the antlr-grammar needs to be updated as well, e.g. the `&=` thinghy shall go ...

**Comment by shabanovd** [comment]
Functions that may be affected https://github.com/eXist-db/exist/tree/develop/src/org/exist/xquery/functions/text

**Comment by adamretter** [comment]
Thanks @shabanovd We will also remove https://github.com/eXist-db/exist/blob/develop/src/org/exist/xquery/functions/text/TextModule.java and functions.
