### ISSUE TITLE
integrate betterFORM ModelValidator

### ISSUE THREAD

**Issue by JoernT** [eXist-db/exist#560]
ModelValidator is a new facility supporting automatic server-side validation of plain HTML5 forms. In addition it creates an XML structure from the request params as input for an xquery. It is part of the betterFORM framework. ModelValidator runs side-by-side with XForms.

Several parts needs update:
- updating of some libs either in betterform extension and eXistdb
- updates to betterform-config.xml in webapp
- update to web.xml
- replacement of betterform.jar 
- providing and adding a demo app showing the usage

**Comment by adamretter** [comment]
:-)

**Comment by adamretter** [comment]
@JoernT Are you still planning to add this?

**Comment by adamretter** [comment]
@JoernT Do you still plan to do this? or should be close this issue?

**Comment by JoernT** [comment]
just close please
