### ISSUE TITLE
Real user controllable transactions

### ISSUE THREAD

**Issue by adamretter** [eXist-db/exist#565]
The goal here is to push the Txn object out to the edges of eXist so that its lifetime is controllable by the user. A follow-up task is then to replace Txn with a truly isolated and consistent transaction mechanism.

1) The first step is to push use and access of Txn to the edges of eXist's APIs.

2) Once at the edges, Txn will be controlled initially by the existing APIs. So this means no disruption or change for the external API user.

3) Add Txn lifetime control methods to each API, so that the user has the option of controlling the Txn.

4) Replace Txn with a truly isolated and durable consistent transaction.

Work in progress is available here - https://github.com/adamretter/exist/tree/txn-thread

**Comment by caseydawsonjordan** [comment]
@wolfgangmm @shabanovd @adamretter Can we work to get this idea merged into 3.0? This would be very important for allowing multiple data stores to work around the same trasaction object. This is something that we need very badly since our stack consists of eXist+SQL+MapDB.

We are planning to move to 3.0 soon and my company could provide considerable amount of testing with real world data and use-cases around this.

Thanks!

**Comment by adamretter** [comment]
If @wolfgangmm @shabanovd are interested in seeing this merged into eXist, then I have some further commits for pushing transactions into the APIs that I will merge into my public branch before I create a PR. However, if they are not interested I don't want to expend wasted effort. So @wolfgangmm and @shabanovd can you let me know please?

@shabanovd Note this involves a lot of "API" changes...

**Comment by shabanovd** [comment]
@adamretter I'm not against API change but API change for nothing... To be more specific I and @caseydawsonjordan agree to spend next 2-3 months to force merge of latest eXist code to development and production. That is a lot of time and could be spend for something else. Hope, that it's clear what I was and will be "against" as hard as I can.

**Comment by adamretter** [comment]
@shabanovd Well I am only proposing to change the API so that transactions are to be explicitly passed around. I am not proposing in the first instance to replace `Txn` with anything better. So it will appear to be API changes without a concrete implementation reason from me; The concrete reason is in @caseydawsonjordan's system. How does that sound?

**Comment by caseydawsonjordan** [comment]
I have looked over much of the API changes and I think (in general) they
are good, and probably should have been done quite some time ago. Also, I
know that much of our code is messy and this would force us to clean it up
and make it safer. I don't mind putting in the effort to refactor. Knowing
what I know about our system, I think the effort to refactor everything,
and do it really well, is about 50-80 hours and would be well worth it. The
majority of this for us would be redesigning parts of our system that
really abused and mistreated brokers/transactions and thus make them much
safer.

What I want to know is if there are any major blockers from a technical
standpoint.

**Comment by shabanovd** [comment]
@adamretter Casey need simple pattern where transaction manager hold listeners and send events that transaction commit or rollback to that listeners. Do that require API changers?

**Comment by caseydawsonjordan** [comment]
Well @shabanovd I don't think we need listeners, I think that would be too sophisticated for our use case and possibly make things more complex. Right now I need 3 things:

1.) try-with-resouces support for transactions (This might already be in eXist 3.0, I haven't looked)
2.) I need the ability to create and use my own eXist transaction at the edges of the API, that way I can combine with a simple transaction manager mechanism (Maybe custom or just JPA)
3.) I need the ability to detect an already running trasaction for the current thread and use it if it already exists (For code which uses API's where I cannot pass around eXist transaction objects). I'm pretty sure either beingOrContinueTransaction or requireTransactionWithBroker would satisfy this.  

As far as I can tell this commit does all the things I need.

**Comment by shabanovd** [comment]
On Fri, Dec 4, 2015 at 7:20 PM, Casey Jordan <notifications@github.com>
wrote:

> Well @shabanovd <https://github.com/shabanovd> I don't think we need
> listeners, I think that would be too sophisticated for our use case and
> possibly make things more complex. Right now I need 3 things:
>
> 1.) try-with-resouces support for transactions (This might already be in
> eXist 3.0, I haven't looked)
>
That was done at 2.1 and can be used for long time already.

> 2.) I need the ability to create and use my own eXist transaction at the
> edges of the API, that way I can combine with a simple transaction manager
> mechanism (Maybe custom or just JPA)
>

Do you mean that you want annotations?

"combine with a simple transaction manager mechanism" will end up
notification from eXist storage on transaction status change to take action
on "external" transaction. JPA and similar just increase complexity.

APIs like https://en.wikipedia.org/wiki/Java_Transaction_API adding
overhead and can't give good performace on heavy loaded systems.


> 3.) I need the ability to detect an already running trasaction for the
> current thread and use it if it already exists (For code which uses API's
> where I cannot pass around eXist transaction objects). I'm pretty sure
> either beingOrContinueTransaction or requireTransactionWithBroker would
> satisfy this.
>

That is possible to add static helper class for that. Are that only methods
that you need?

-- 
Dmitriy Shabanov

**Comment by adamretter** [comment]
I am closing this, as I won't be doing this in eXist-db as we have already achieved it in FusionDB.
