### ISSUE TITLE
Potential memory leak in session

### ISSUE THREAD

**Issue by wolfgangmm** [eXist-db/exist#574]
I observe a rather high memory consumption in some apps which store temporary query results into the HTTP session. It turns out this is caused by ValueSequence keeping references to variables in the current XQuery context.

Consider to detach/clean up sequences before storing them into the session.

**Comment by shabanovd** [comment]
There is cleanup thread, no? Is it live system observation, or in test evnviroment?

**Comment by wolfgangmm** [comment]
I recognized it while running jmeter tests on a live system and applied a quick fix there. I'm not yet completely happy with it though, so I opened this issue to remember the problem.
