### ISSUE TITLE
bin/shutdown.sh not shuting down

### ISSUE THREAD

**Issue by mgr34** [eXist-db/exist#602]
In fact it appears to be doing nothing at all. I have to manually kill the thread. I've tried this on the most recent commit a277568192 and also the one from earlier today on two different machines. Both linux, one debain 7 and the other archlinux. Both with java 8. It was working fine the last few times I've updated. 

 More information available upon request.

**Comment by adamretter** [comment]
@mgr34 Yes sorry about that. @zwobit made me aware of this just a couple of days ago. It is a small regression recently introduced that I need to address. You should be able to shutdown eXist in the meantime by sending a SIGINT kill signal to it.

**Comment by mgr34** [comment]
Thanks for the fast response.
