### ISSUE TITLE
Monex failing

### ISSUE THREAD

**Issue by mgr34** [eXist-db/exist#603]
using a277568192 and a different commit from earlier today I take a fresh install, open the package manager and install Monex. Thereafter, I receive the following message 

````XML
<exception>
  <path>/db/apps/monex/modules/view.xql</path>
  <message>err:XPST0081 error found while loading module indexes: Error while loading module    indexes.xqm: No namespace defined for prefix text [at line 166, column 56]
  </message>
</exception>
````

I've tried restarting the server after some reading some about a different monex issue I saw in the mailing list. 

My apologies if I should put this in [here, on the monex issue tracker](https://github.com/wolfgangmm/monex), but considering this same version was functioning fine with an earlier version of exist (ea5fe459) this morning I think this maybe an exist issue.

**Comment by mgr34** [comment]
Ok, I just commented out the offending line and changed the following `else if`  to an `if` and so far so good. I need to page through the recent commits, I guess that legacy fulltext index was finally removed. 

```xml
 (: legacy fulltext index use the text:index-terms() function :)
        if ($indexes:index eq 'legacy-fulltext-index') then
            text:index-terms($indexes:node-set, $indexes:start-value, $indexes:callback, $indexes:max-number-returned)
```

So Far, so good.

**Comment by dizzzz** [comment]
Yes, last weekend the old FT index had been removed. On existopen there was a statement from @wolfgangmm  that eXide and the dashboard neer to be updated...

**Comment by mgr34** [comment]
Great, I thought I recall seeing some discussion or an announcement about this on the mailing list recently. It looks like removal has also effected Monex. Which on a second thought makes me think I should have attached this toe the monex project.

**Comment by dizzzz** [comment]
https://gist.github.com/wolfgangmm/5880377 ; but I did not check monex myself yet, there might be an issue overlooked yet.

**Comment by wolfgangmm** [comment]
Should all be fine with the latest monex.
