### ISSUE TITLE
key alt not work #bug

### ISSUE THREAD

**Issue by adripol94** [eXist-db/exist#606]
key "alt" not found.
When i press alt it doesn't paint nothing...
s.o client: Yosemite IOs
client java: 2.2

Alt+2 expected @ got nothing 
Alt+` expected [ got nothing
Alt+´ expected ] got nothing
Alt+3 expected # got nothing

**Comment by dizzzz** [comment]
Please could you be more specific and do not use abbreviations? I have some difficulty understanding you. Which client?

**Comment by jensopetersen** [comment]
Pressing Alt (⎇) in the Java Admin Client on Mac OS X in a window with an opened file or in the query dialog has no effect, making it difficult to input many common characters. In other windows, it is possible.

**Comment by adripol94** [comment]
jensopetersen described very well the problem.

**Comment by adripol94** [comment]
Can anyone help me?

**Comment by adamretter** [comment]
I think I need some more specifics. For example you cannot access the Menu directly using Alt on a Mac if that is what you are attempting? i.e. see http://superuser.com/questions/504111/how-to-select-file-menu-in-mac-just-like-alt-f-in-windows

Hmm it seems that for some combinations it works, and for others it does not. For example I can type a `ö` with `Alt+u o`, however I cannot type a `€` or a `#` in the Java Admin Client, those should be `Alt+2` and `Alt+3` respectively on my platform. I will see what I can find out...

**Comment by adamretter** [comment]
Apart from the pull-request above, there is a known issue in JDK 8 which has recently been fixed. Once the pull-request is merged, if the fix does not work for you, then you also need to update to at least JDK 1.8.0_u45 (see https://bugs.openjdk.java.net/browse/JDK-8068283).
