### ISSUE TITLE
Use JAXB for configurations

### ISSUE THREAD

**Issue by shabanovd** [eXist-db/exist#618]
Replace `org.exist.config.*` and `org.exist.util.Configuration` by JAXB

**Comment by adamretter** [comment]
@shabanovd Actually I already started this and logged an issue here - https://github.com/eXist-db/exist/issues/578. In addition JAXB also has some undesirable properties. I will close this as it is a duplicate of the other issue.

**Comment by shabanovd** [comment]
`JAXB also has some undesirable properties` - what kind?

**Comment by adamretter** [comment]
@No support for incremental updates and requires the entire object model to be in memory.

**Comment by shabanovd** [comment]
Ok, you remind me why I started Configurator ... same time I like idea to use standard annotations (if that be possible at all)

**Comment by adamretter** [comment]
@shabanovd what do you consider as "standard annotations"?

**Comment by shabanovd** [comment]
http://docs.oracle.com/javase/8/docs/api/javax/xml/bind/annotation/package-summary.html

**Comment by adamretter** [comment]
@shabanovd I think those are only for customising the generation of XML Schema and instances from POJOs. I would rather be inclined to go in the opposite direction

**Comment by shabanovd** [comment]
Can you describe it?
