### ISSUE TITLE
webdav.properties -> ident=no -> swallowing whitespaces

### ISSUE THREAD

**Issue by zopyx** [eXist-db/exist#625]
My *webdav.properties* contains *indent=no* in order to avoid reformatting
of the markup. However there is painful side-effect (likely a bug) when storing XHTML.

Markup containing whitespaces between <span> tags like

    <span class="firstname">Wilfried</span> <span class="lastname">Eberhardt</span>

will be returned over WebDAV  without whitespace:

    <span class="firstname">Wilfried</span><span class="lastname">Eberhardt</span>

The error can be reproduced by creating a HTML through a webdav client in exist-db 2.2 (e.g. with cadaver)

**Comment by dizzzz** [comment]
hmmm, did you set the 'preserve-whitespace-mixed-content' in `conf.xml` ?

**Comment by zopyx** [comment]
Indeed, this solves the problem.
