### ISSUE TITLE
extensions/build.properties: Apache FOP mirror down 404

### ISSUE THREAD

**Issue by mathias-goebel** [eXist-db/exist#627]
extensions/build.properties
link to http://apache.cs.uu.nl/dist/xmlgraphics/fop/binaries/
which is down.
try:
http://apache.openmirror.de/xmlgraphics/fop/binaries/fop-1.1-bin.zip

**Comment by adamretter** [comment]
Thanks @mathias-goebel I think the real solution here though would be for us to switch this to Ivy so that the dependencies are resolved without worrying about a downed mirror.

**Comment by dizzzz** [comment]
I have worked on that.... Lemme check

**Comment by dizzzz** [comment]
please *always* report which version you use;  has been fixed in december..

https://github.com/eXist-db/exist/blame/develop/extensions/build.properties#L162

fixed by https://github.com/eXist-db/exist/commit/f8bf0b84a79bfd6d36889556d1eb17465a5a16a2

**Comment by mathias-goebel** [comment]
the link i reported (as it appears in the current develop branch) was down during the last weeks, which indicates that it not an appropriate mirror you are using. now the server seems to be is back online, fine.

**Comment by dizzzz** [comment]
No the link had already been updated some time ago. It was already fixed for the upcoming release.
