### ISSUE TITLE
XSLTServlet truncates namespace prefixes

### ISSUE THREAD

**Issue by timathom** [eXist-db/exist#629]
Originally submitted to [Exist-open](http://sourceforge.net/p/exist/mailman/message/34121401/). Also separately reported on [XSLTForms list](http://sourceforge.net/p/xsltforms/mailman/message/24064765/), by a different user, in 2009.

Scenario: trying to run XSLTForms server-side in eXist 2.2, using a controller pipeline[[1](http://exist-db.org/exist/apps/doc/xforms.xml#D1.2.6.3)]. When documents containing elements with namespace prefixes are processed by XSLTServlet, the last character of the prefix is chopped off. This causes XSLTForms to fail when it tries to parse an XForms document with namespace-prefixed instance elements.

When I remove all namespace prefixes from the XForms document, the transformation via XSLTServlet is successful. 

This is not specific to XSLTForms. A generic XSLTServlet transformation outside of XSLTForms yields the following result:

XML document:

```
<?xml version="1.0" encoding="UTF-8"?> 
<test:root xmlns:test="http://example.org" xmlns:test2="http://example.org/2/">
    <test2:child>Testing namespace support in XSLTServlet</test2:child> 
</test:root>
```

Stylesheet:

```
<?xml version="1.0" encoding="UTF-8"?> 
<xsl:stylesheet     
    xmlns:xsl="http://www.w3.org/1999/XSL/Transform"     
    xmlns:xs="http://www.w3.org/2001/XMLSchema"     
    xmlns:test="http://example.org" 
    xmlns:test2="http://example.org/2/"
    exclude-result-prefixes="xs"
    version="2.0">     
    <xsl:output method="xml"/>
    <xsl:template match="/">
        <test>             
            <result1>                
                <xsl:value-of select="node-name(test:root)"/>
           </result1>             
           <result2>                 
                <xsl:value-of select="node-name(test:root/test2:child)"/>             
           </result2>         
        </test>    
    </xsl:template> 
</xsl:stylesheet>
```

Result:

```
<?xml version="1.0" encoding="UTF-8"?> 
<test xmlns:test2="http://example.org/2/" 
    xmlns:test="http://example.org">
    <result1>tes:root</result1>
    <result2>test:child</result2>
</test>
```

**Comment by duncdrum** [comment]
no longer able to reproduce with 5.0.0-RC8-SNAPSHOT.
