### ISSUE TITLE
util:document-name() fails with simple map operator (!)

### ISSUE THREAD

**Issue by joewiz** [eXist-db/exist#631]
`util:document-name()` returns empty when in the context of a simple map operator (!).  For example, this query returns empty:

```xquery
xquery version "3.0";

declare namespace h="http://www.w3.org/1999/xhtml";

//h:p ! util:document-name(.)
```

The same operation, expressed as a FLWOR expression, works:

```xquery
xquery version "3.0";

declare namespace h="http://www.w3.org/1999/xhtml";

for $hit in //h:p
return util:document-name($hit)
```

This is using the current eXist develop branch.

**Comment by adamretter** [comment]
I will also add that if you only have one node, then just a let/return is enough to make it work also:

```xquery
xquery version "3.0";

declare namespace h="http://www.w3.org/1999/xhtml";

let $p := //h:p[1]
return
  $p ! util:document-name(.)
```

**Comment by adamretter** [comment]
Interestingly if the `p` element is the root element of a document then you will get results, if it is a descendant then you will not. For some reason the leftOp side of Simple Map Operator sometimes returns an empty sequence when it should not

**Comment by adamretter** [comment]
So I have discovered that even wrapping the LHS in a  sequence constructor is enough to make it evaluate correctly, i.e. this works:

```xquery
xquery version "3.0";

declare namespace h="http://www.w3.org/1999/xhtml";

(//h:p) ! util:document-name(.)
```

**Comment by adamretter** [comment]
The problem is PathExpr.java line 260 is always setting a contextItem:

```java
exprResult.addAll(expr.eval(currentContext, current))
```

 which is used by the LocationStep on the LHS of the query, the contextItem should remain null in this instance so that the contextSequence is used instead. I am not sure how this is best solved. Perhaps @wolfgangmm has a suggestion?

**Comment by wolfgangmm** [comment]
I guess a wrong context item dependency is reported somewhere, causing PathExpr to take this route of execution. This is a difficult matter and I'll have to step through it myself to see where it goes wrong. Your observations should help a lot though. I'll do a debugging session later tonight.

**Comment by wolfgangmm** [comment]
It turns out it was an issue in our XQuery grammar. Not sure why we had it wrong, maybe the specs changed over time.

**Comment by joewiz** [comment]
Wow, thank you! I reach to this syntax often, so I appreciate not having to resort to the workaround anymore!
