### ISSUE TITLE
Logs not written to correct location

### ISSUE THREAD

**Issue by wshager** [eXist-db/exist#634]
Currently the logs are not written to `/webapp/WEB-INF/logs`, but to `/tools/wrapper/bin/webapp/WEB-INF/logs`. This is confirmed to be the case when running eXist as a service, or at least installed as upstart daemon. The cause lies in the new log4j configuration for the wrapper, in `/tools/wrapper/conf/log4j2.xml`.

**Comment by adamretter** [comment]
I think there used to be an XSLT that was executed against the log4j config file. How and when this was executed was not very clear to me when I did the log4j upgrade, perhaps this has caused an issue...

**Comment by dizzzz** [comment]
I think the xslt is still executed, but no modifications are changed. I remember we had to set the correctly directory because.... of the reason reported by wouter. same thing holds for the WAR deployment, I guess we have an issue there now as well...... or not :-)
