### ISSUE TITLE
TransformerFactory factory should be singleton

### ISSUE THREAD

**Issue by alexrwd** [eXist-db/exist#651]
We can see a lot of such rows in logs if we change level exist logs to debug:
2015-06-03 18:28:04,446 [http-bio-8080-exec-10] DEBUG (TransformerFactoryAllocator.java [getTransformerFactory]:91) - Set transformer factory: com.saxonica.config.ProfessionalTransformerFactory
2015-06-03 18:28:04,447 [http-bio-8080-exec-10] DEBUG (TransformerFactoryAllocator.java [getTransformerFactory]:101) - Set transformer attribute: , name: http://saxonica.com/oem-data, value: Licensor=Saxonica

exist constantly spends time on creation factory. I think transformation factory is created per session.
It seems to me that it should singleton because it is created based on conf.xml and could not be changed without restart of application.

**Comment by alexrwd** [comment]
Guys, will you include this fix in some intermediate version between 2.2 and 3.0? I would like to upgrade our eXist DB with this changes soon.

**Comment by shabanovd** [comment]
That change was merged to develop branch and will be in next release.

**Comment by alexrwd** [comment]
Where can I find information when we can expect next release?

**Comment by shabanovd** [comment]
That is nobody know for sure -)
You can build from source or I can build one for you.

**Comment by dizzzz** [comment]
a nighly build is made availabe by @adamretter on http://static.adamretter.org.uk/exist-nightly/ 
the jars seem to be no signed.

**Comment by adamretter** [comment]
@dizzzz Indeed the Jars are not signed as I have never needed signed jars. If someone *really* needs signed jars I could also create a signed build...

**Comment by adamretter** [comment]
@dizzzz I think we should link the nightly builds from the website perhaps, as we are frequently pointing people to them...

**Comment by dizzzz** [comment]
Yes, that sounds like a good idea!

**Comment by shabanovd** [comment]
@adamretter can you add link to README.md?

**Comment by dizzzz** [comment]
it is on the main pagie of exist on github

**Comment by adamretter** [comment]
@JoernT Please can you add the nightly builds to the eXist-db homepage?

**Comment by adamretter** [comment]
@shabanovd Yes, just did that for you :-)

**Comment by shabanovd** [comment]
@adamretter thanks -)

**Comment by dizzzz** [comment]
No signing is OK for me :) I know about side effects, they do not make you too happy... 

--
www.exist-db.org
