### ISSUE TITLE
Download at exist-db.org points to sourceforge

### ISSUE THREAD

**Issue by borsna** [eXist-db/exist#659]
Sourceforge is doing some pretty bad stuff to the binaries and i think it would be good to point the download to the releases on github.com instead.

http://sourceforge.net/projects/exist/files/Stable/2.2/ -> https://github.com/eXist-db/exist/releases/tag/eXist-2.2 on http://exist-db.org/exist/apps/homepage/index.html

More info:
https://helb.github.io/goodbye-sourceforge/

**Comment by adamretter** [comment]
@borsna They are not the same thing I am afraid. On SourceForge the downloads we provide are builds of our Installer etc. GitHub just provides Tarballs/zips of the source code.

We could perhaps use bintray.com instead of SourceForge for downloads though, I have certainly seen other Open Source projects moving there. @JoernT and @wolfgangmm should I look at doing that move for us?

**Comment by zwobit** [comment]
@adamretter i think it is also possible attach binaries to github releases/tags

**Comment by joewiz** [comment]
Yes, see https://help.github.com/articles/creating-releases/

> If you'd like to include binary files along with your release, such as compiled programs, drag and drop or select files manually in the binaries box.

**Comment by dizzzz** [comment]
The max size of files is rather small on GitHub. (Last time I checked). Not an option

Yes, sf.net is doing strange things lately, fortunately the community pressure is highly. Probably they have financial problems and a desperately searching for funding. Or a non-tech guy tries to make a career there.

Note that the strong point of sf.net is that they have a very large distributed and reliable network of hubs. This allows very fast downloads on every continent and every provider. Also for Asia, Africa, Russia and south Americas where the connection to 'the west' is slow and expensive. 

GitHub cannot provide this, and the other option mentioned by Adam does not have his strength....

**Comment by dizzzz** [comment]
In a recent 'alternatives for' article , the alternative for sf.net is sf.net :)

**Comment by zwobit** [comment]
For the file size [GitHub help](https://help.github.com/articles/distributing-large-binaries/)  says 1GB.

**Comment by joewiz** [comment]
Then we're all set, I think the largest jar at http://sourceforge.net/projects/exist/files/Stable/2.2/ is 123 MB.

**Comment by adamretter** [comment]
@dizzzz I think you are mistaken, bintray.com list one of their core features as a powerful CDN.

**Comment by dizzzz** [comment]
@zwobit... That is for the whole account?

http://stackoverflow.com/questions/6978954/add-binary-distribution-to-githubs-download-link deel below?

**Comment by joewiz** [comment]
> We don't limit the total size of your binary release files, nor the bandwidth used to deliver them. However, each individual file must be under 1GB in size.

**Comment by dizzzz** [comment]
Bintray is maxed on 30mb?

Anyway the globe wide distribution channel i consider essential.

**Comment by joewiz** [comment]
So the 1 GB limit is per file.

That stackoverflow thread is pretty old - but what exactly was your question about it (didn't understand "deel below").

I'd be surprised if github didn't have a CDN. Fastly reports github as a customer: https://www.fastly.com/customers/github/. That said, I don't have evidence github binaries is fast to Asia, Africa, Russia and South America. Might be worth a try - so feedback / evidence can be gathered?

**Comment by dizzzz** [comment]
I actually started to look for sf.net alternatives earlier this week; I found this article, but.... does not give too much hope. though he has probably different 'requirements' ....

* [14 Potential Alternatives to SourceForge for Binary Downloads](http://michaeltunnell.com/blog/15-miscellaneous/53-14-potential-alternatives-to-sourceforge-for-binary-downloads) (18/11/2014)

**Comment by dizzzz** [comment]
@joewiz sorry, auto spell corrector was active and set on dutch

**Comment by dizzzz** [comment]
Bittray confirmed the max size has been removed, but I asked for additional details ....  https://twitter.com/tombujok/status/430004014047326208

**Comment by zwobit** [comment]
@dizzzz I think in the linked GitHub pages at stackoverflow they are talking about the "repo". So there is a file size limit for versioned files.

**Comment by dizzzz** [comment]
Two things: 
- GitHub is no CDN, world wide are they? -- my main requirement ; the world is larger than the U.S. , Europe plus UK 
- from what I read here, we don't have sufficient facts to make a decision. 

In general The help pages of the services do not give good enough clues, so we need to contact the services. I started with one already.....

**Comment by dizzzz** [comment]
Ok feedback from bintray:
* no max size anymore for downloads (was 50 some time ago)
* multi continent distribution.

From Twitter:
@bintray: @dizzzz downloads are delivered via CDN (amazon cloudfront and akamai)

So.... Bintray is now a serious candidate for me!

**Comment by joewiz** [comment]
I've dropped a question to GitHub about this.  Will keep you updated.

**Comment by jbaruch** [comment]
If you have questions on @bintray you can ask them here :)

**Comment by adamretter** [comment]
I would be ***really*** surprised if a site of GitHub's size were not using a CDN.

**Comment by shabanovd** [comment]
Most likely, it quite slow for me.

**Comment by sanderd17** [comment]
After seeing this thread, bintray also looked as a viable alternative for our current SourceForge release hosting. But when trying to upload a ~500MB file, bintray reports that the maximum file size is 0.2GB, and advises me to upgrade to a premium plan. So there still seems to be a maximum file size at least.

**Comment by adamretter** [comment]
@sanderd17 Our largest files are currently less than 124MB so we might be okay for a while

**Comment by jbaruch** [comment]
@sanderd17 that shouldn't happen. Let me check and get back to you, guys.

**Comment by jbaruch** [comment]
Ok, so I figured it out. It's a combination of a desired functionality an a bug :)
Bintray doesn't have a limit of file size when uploading via REST (which is the normal way to get files to Bintray from Artifactory, CI servers and build tools). 
When uploading files from the UI we do impose a limit to prevent a browser timeout. Suggesting an upgrade to premium plan is a bug though.

**Comment by sanderd17** [comment]
I tried REST and the browser upload. With REST via curl, I didn't get a lot of feedback (should look into parameters to get better feedback), but at a certain point, it stopped with the message "file size too big". With the browser, I got the message that mentioned 0.2GB.

**Comment by adamretter** [comment]
If we are going to do this, then we should do it... So can we draw a consensus then? It seems that the BinTray folks are very helpful ;-)

**Comment by wolfgangmm** [comment]
Due to the positive feedback in this thread, I tried BinTray and uploading works very well. Let's go for it.

I created an organisation, so anyone from the core team who wants admin access and help set it up, send me the username.

**Comment by jbaruch** [comment]
:+1:

**Comment by ljo** [comment]
OK. +1

**Comment by joewiz** [comment]
FYI, I received a response from GitHub support last night that GitHub Releases is not CDN-backed; a check with curl will show the resources are actually stored on S3. They added the request for CDN backing to their issue tracker.

**Comment by adamretter** [comment]
@wolfgangmm My bintray username is `adamretter` please can you add me.

**Comment by dizzzz** [comment]
Super! Thnx @bintray !

--
www.exist-db.org

**Comment by grantmacken** [comment]
Hi, just my 2 cents worth.  I think from a user perspective, it would preferable to have existdb the release asset install  jar located on github.  IMO,  the expected social go-to point when finding out about the project and looking for an installable exist download file ought to be github.  Dialog ( comment, issues ) about the release I think ought to be at the download location.  This social aspect, is what made github as popular as it is. 
Once understood, using the  github API to create release asset is simple enough
-  create an annotated tag for release and push  git push origin --tags 
-  use github api to create release based on annotated tag
-  use github api  to get release and locate asset upload URI
-  use github api  to upload

**Comment by jbaruch** [comment]
@bintray has a github download badge, which makes finding the downloads a no-brainer. And is has all the social aspects of GitHub as well. Also, from user perspective, it has a "watch" feature, which allows users to get notified once a new version is released. @grantmacken did you take a look at @bintray?

**Comment by adamretter** [comment]
Downloads are now over at Bintray - https://bintray.com/existdb/releases/exist/3.0.RC1/view and we have added the download badge to our README.md.

**Comment by jbaruch** [comment]
You're more than welcome to transfer the maven artifacts to Bintray as well. It will make your build easier (as you can use [a built-in Ivy resolver](http://ant.apache.org/ivy/history/latest-milestone/resolver/bintray.html) to publish), it has auto-index generation and you can link them to [jcenter repository](https://bintray.com/bintray/jcenter) (1st class citizen in Gradle, Ivy and Groovy Grapes) and you can even sync to Maven central in a click of a button (or a REST call).

**Comment by adamretter** [comment]
@jbaruch Very kind, but we are not quite ready for that yet.

**Comment by jbaruch** [comment]
No problem at all. Let me know if (and when) you need help with that. Having the jars in central repositories like jcenter and maven central is very important for the users.

**Comment by adamretter** [comment]
@jbaruch completely agree. However at the moment we do not meet the requirements for Maven central. I generated all the poms by hand as our current build system doesn't support that. I hope to move us to Maven in the near future.

**Comment by jbaruch** [comment]
I see. Just for you to know, the requirements for jcenter are significantly easier than for maven central. All it requires is valid maven artifacts and a source url (this github repo).

**Comment by dizzzz** [comment]
@jbaruch good to know, thanks for your valuable feedback!

**Comment by jbaruch** [comment]
:+1:

**Comment by borsna** [comment]
great work! :+1:
