### ISSUE TITLE
infinite loops cannot be killed

### ISSUE THREAD

**Issue by wshager** [eXist-db/exist#676]
I've tried to kill some running queries (using monex) but they won't be terminated. The query possibly hits an infinite loop while creating a map.

**Comment by wshager** [comment]
the hanging query appears to also prevent a shutdown of exist.

**Comment by wolfgangmm** [comment]
I would need to see the code. I believe I made all of the looping constructs check the terminate flag, but it's possible I missed something.

**Comment by wshager** [comment]
I know this is little to go on... the loop seems to involve the recursive calling of functions, in this case both creating maps. I'll try to isolate a test.

**Comment by wshager** [comment]
xquery version "3.1";

declare namespace output="http://www.w3.org/2010/xslt-xquery-serialization";

declare function local:use($map){
    let $maps := array:for-each($map("process"),function($_){
        let $parsed := parse-json($_)
        return local:process($parsed)
    })
    return array:fold-left($maps,map {},function($acc,$map){
        map:new(($acc,$map))
    })
};

declare function local:get-map($map,$value){
    map:new(($map,map {
        "name":=$map("name") || $value
    }))
};


declare function local:process($value){
    let $case1 := array:filter($value,function($_){
        $_("name") = "case1"
    })
    let $case2 := array:filter($value,function($_){
        $_("name") = "case2"
    })
    let $map := 
        array:fold-left($case1,map {},function($acc,$_) {
            map:new(($acc,local:use($_)))
        })
    return map:new(($map,
        array:fold-left($case2,map {},function($acc,$_){
            let $map := local:get-map($_,"x")
            return map:new(($acc,map:entry($map("name"),$map)))
        })
    ))
};

let $dict := local:process([map { "name":="case1", "process":['[{"name":"case2","test":"stuff"},{"name":"case2","test":"stuff"}]']}])
return serialize($dict,
<output:serialization-parameters>
    <output:method>json</output:method>
</output:serialization-parameters>)

**Comment by wshager** [comment]
The `parse-json` line seems to be optional. When the "process" value is an array of maps, and the function would return `local:process($_)` the query hangs as well. 

I'd be happy to know how to prevent the problem too.

**Comment by wshager** [comment]
A simpler version:

```
xquery version "3.1";

declare namespace output="http://www.w3.org/2010/xslt-xquery-serialization";

declare function local:use($map){
    let $maps := array:for-each($map("process"),function($_){
        array:fold-left($_,map {},function($acc,$map){
            map:new(($acc,map:entry($map("name") || "x",$map)))
        })
    })
    return array:fold-left($maps,map {},function($acc,$map){
        map:new(($acc,$map))
    })
};


let $value := [map { "name":="case1", "process":[[map{"name":="case2","test":="stuff"},map{"name":="case2","test":="stuff"}]]}]
let $maps := 
    array:for-each($value,function($_) {
        local:use($_)
    })
return serialize($maps,
<output:serialization-parameters>
    <output:method>json</output:method>
</output:serialization-parameters>)

**Comment by wshager** [comment]
The problem is in the last array:for-each

**Comment by wshager** [comment]
Quick fix:

``` 
for $i in 1 to array:size($value) return
        map:new(($map,local:use($value($i))))

**Comment by wshager** [comment]
I guess my case would also be helped by having the map:merge function

**Comment by wolfgangmm** [comment]
As far as I know, map:merge is basically map:new. It was just renamed.

**Comment by wshager** [comment]
OK please ignore that then. I was thinking specifically about merging arrays of maps, but this means they can be array:flattened to sequences of maps. It's all still a bit confusing ;)

**Comment by wolfgangmm** [comment]
Ok, I confirm your query does indeed not stop, even though array:for-each should check the terminate flag. I will investigate why this happens. As far as I can see in the code, it should all be fine...

**Comment by wshager** [comment]
Would it be possible to separate the execution context from the database, so that runaway scripts can be killed without having to wait for the cooldown time the storage layer needs?

**Comment by wolfgangmm** [comment]
The problem is that you cannot just kill a thread without causing trouble. The query needs to cooperate and terminate properly if it is requested to do so. All looping constructs, function calls and the like do check for the terminate signal. 

But in your example the query does not stop even though it gets the signal. I have the debugger open on it...

**Comment by wshager** [comment]
I see. Sorry for my naive presumptions.

**Comment by wolfgangmm** [comment]
I found out the infinite loop was inside the query engine. No surprise the query couldn't be killed.

**Comment by joewiz** [comment]
Wow, great reporting, @wshager, and sleuthing, @wolfgangmm!

**Comment by wshager** [comment]
The fix works for my case. The query returns the expected result. Much obliged :+1:
