### ISSUE TITLE
xml-to-json does not escape properly

### ISSUE THREAD

**Issue by JonathanRowell** [eXist-db/exist#688]
import module namespace json = "http://www.json.org";

let $jrData := json:xml-to-json($result)

<result>
<Description>
<title>Alla turca </title>
<type>Sachbücher</type>
<date>1951</date>
<description>Sonate KV 331 mit dem 3. Satz "Alla turca".</description>
</Description>
</result>

<jrData>
{"title" : "Alla turca ", "type" : "Sachbücher", "date" : "1951",
"description" : "Sonate KV 331 mit dem 3. Satz "Alla turca"."}
</jrData>

 As one can see, the function xml-to-json ought to have escaped the double quotes in the data with a backslash.

**Comment by wolfgangmm** [comment]
The json:xml-to-json is a bit outdated (I wonder if we should remove the module from the next release). I would prefer to use the json serializer:

```xquery
xquery version "3.0";

declare namespace output="http://www.w3.org/2010/xslt-xquery-serialization";

let $xml := <test>
                <title>All turca</title>
                <description>Sonate KV 331 mit dem 3. Satz "Alla turca".</description>
            </test>
return
    serialize($xml, <output:serialization-parameters>
    <output:method>json</output:method>
</output:serialization-parameters>)
```

**Comment by JonathanRowell** [comment]
I don't think I would object, since I'll have to change the script if the module is fixed to remove the kludge I built into the XSLT which removes the Marc21 non-sorting characters. Does the XSLT processor have json output capabilities?

It would make Erik and Adam's book a bit out of date. And you'll probably need to remove THREE of them, for there is json (page 508), jsonp (page 509) and xqjson (page 524).

**Comment by adamretter** [comment]
@JonathanRowell I think you refer to the `json` and `jsonp` modules in the appendix? Also note that `xqjson` is unrelated to what @wolfgang is proposing. I also note that the book covers the built-in JSON serializer in eXist too which also won't be removed.

**Comment by adamretter** [comment]
@wolfgangmm I agree, can we remove those old modules?

**Comment by wolfgangmm** [comment]
Yes, we should remove json.xq and jsonp.xq.
