### ISSUE TITLE
util:string-to-binary() leaks files

### ISSUE THREAD

**Issue by dizzzz** [eXist-db/exist#69]
During intensive usage of util:string-to-binary() we found out that many files were written to jetty/tmp but these were never cleaned up.

As a result a system (linux, oracle java7) ran out of file handles over time.

example:

java      28644 29132 username  219u      REG              202,1      1700     411310 /opt/exist-trunk/tools/jetty/tmp/_mmtfm_16f53166-157f-4f5d-82a1-5c8c2c42e6bf/mmtf_1382636042437789285362156175046.tmp (deleted)
java      28644 29132 username  222u      REG              202,1      1700     411056 /opt/exist-trunk/tools/jetty/tmp/_mmtfm_16f53166-157f-4f5d-82a1-5c8c2c42e6bf/mmtf_1382636042437789285362156175046.tmp (deleted)
java      28644 29132 username  227u      REG              202,1      1700     411056 /opt/exist-trunk/tools/jetty/tmp/_mmtfm_16f53166-157f-4f5d-82a1-5c8c2c42e6bf/mmtf_1382636042437789285362156175046.tmp (deleted)
java      28644 29132 username  229u      REG              202,1      1700     411148 /opt/exist-trunk/tools/jetty/tmp/_mmtfm_16f53166-157f-4f5d-82a1-5c8c2c42e6bf/mmtf_1382636042437789285362156175046.tmp (deleted)
java      28644 29132 username  233u      REG              202,1      2690     411152 /opt/exist-trunk/tools/jetty/tmp/_mmtfm_16f53166-157f-4f5d-82a1-5c8c2c42e6bf/mmtf_1382636042437789285362156175046.tmp (deleted)
java      28644 29132 username  234u      REG              202,1      1700     411148 /opt/exist-trunk/tools/jetty/tmp/_mmtfm_16f53166-157f-4f5d-82a1-5c8c2c42e6bf/mmtf_1382636042437789285362156175046.tmp (deleted)
username@myserver:/opt/exist-trunk/tools/jetty/tmp$ lsof| grep mmtf | wc -l
2912

**Comment by joewiz** [comment]
Closed by #492?

**Comment by duncdrum** [comment]
@dizzzz good to close?

**Comment by dizzzz** [comment]
Think so Yes
