### ISSUE TITLE
error in tail-recursive array function with numbers

### ISSUE THREAD

**Issue by wshager** [eXist-db/exist#698]
The following tail-recursively optimized function throws an error when the array contains numbers:

```xquery
xquery version "3.1";

declare function local:replace($arr,$acc){
    if(array:size($arr)>0) then
        let $v := array:head($arr)
        let $v :=
            if($v = "x") then
                "y"
            else
                $v
        return
            local:replace(array:tail($arr),array:append($acc,$v))
    else
        $acc
};

local:replace([1,2,3],[])
```
exerr:ERROR Type error: cannot compare operands: xs:integer and xs:string [at line 4, column 5] In function: 	local:replace(item()*, item()*) [17:1:String]

**Comment by joewiz** [comment]
Am I wrong?  I thought for the optimizer to recognize tail recursion, you had to put the recursion bit in the "else" clause - i.e., in the tail.

(Apologies if this isn't directly related to the issue you raised here.)

**Comment by wshager** [comment]
@joe Could you rewrite this function to reflect that perhaps?

**Comment by joewiz** [comment]
I'd just flip the conditional logic.  Warning: untested!

```
xquery version "3.1";

declare function local:replace($arr,$acc){
    if (not(array:size($arr)>0)) then
        $acc
    else
        let $v := array:head($arr)
        let $v :=
            if($v = "x") then
                "y"
            else
                $v
        return
            local:replace(array:tail($arr),array:append($acc,$v))
};
```

**Comment by wshager** [comment]
@joe perhaps... 
Did you mean `array:size($arr) = 0`?
;-)

**Comment by joewiz** [comment]
Indeed, sir!  I tracked down where I read the bit about **tail**-recursion. Wolfgang wrote this:

> your function needs to be tail-recursive to allow for unlimited recursion, meaning that the last statement executed in the function should be the recursive function call.

- from http://markmail.org/message/3463w3h53xvhjsbg

**Comment by wshager** [comment]
I thought TCO to mean that the last line that a recursive function executes returns the accumulated result.

**Comment by wshager** [comment]
i.e. the last instruction, not the last line.

**Comment by joewiz** [comment]
@wolfgangmm Could you clarify our understanding of tail recursive functions in eXist?

**Comment by wshager** [comment]
Oops! The error is in the test `if($v = "x")` as I'm sure you will have spotted. My bad, very bad.

**Comment by wshager** [comment]
Closing this issue in shame...
