### ISSUE TITLE
optimize count expression

### ISSUE THREAD

**Issue by Flamenco** [eXist-db/exist#706]
For collection with 40,000 items

```
count(collection('/db/stuff')) = .04 secs
count(collection('/db/stuff')/*) = 6.5 seconds
collection('/db/stuff')/count(*) = 11.192 seconds
```

**Comment by dizzzz** [comment]
Please can you explain why you consider this a bug? What behavior do you expect?  (Essential info for a big report) which exist version?

**Comment by Flamenco** [comment]
This was tested using current master branch.

All expressions return the same value.  No content indexes need to be used.

I think it's self explanatory that the first expression is 162x/277x faster than the others should not need to be.

**Comment by telic** [comment]
The `/count(*)` form is actually quite different than the other two and it makes sense that it would be slower.  The first two are computing a *single* count of a single sequence. The other is computing a count *for each item* in the sequence.
