### ISSUE TITLE
VersioningTrigger/VersioningFilter not working

### ISSUE THREAD

**Issue by grzegorzewicz** [eXist-db/exist#711]
Forgive my english. In the CollectionConfiguration.java in exist 2.2 FINAL, there is very interesting method:

//TODO: code
    public boolean triggerRegistered(Class<?> triggerClass) {
        return false;
    }

this method is used by VersioningFilter class and startElement method and non of the document receives versioning metatags and conflict resolver is not working. Are you aware of that?

**Comment by adamretter** [comment]
@grzegorzewicz The Versioning Trigger is no longer part of eXist as per https://github.com/eXist-db/exist/pull/707. At the moment @zwobit is looking into placing this into its own Git repo, and so might be able to update you on that...

**Comment by zwobit** [comment]
Current repo is on bitbucket. It more or less just contains the old code from the existdb git repo. My plan is to create a xar out of it, so it is easily installable into existdb.
