### ISSUE TITLE
Binary-Files in older Versions are missing

### ISSUE THREAD

**Issue by StephanMa** [eXist-db/exist#712]
We are using eXist 2.0 for our Plattform.
So we have to build eXist very often while developing.
Since Friday we are no longer able to build eXist (2.0 and 2.2).

After some Investigations, we saw that git removes some binaries and java-files, while cloning
e.g. eXist/tools/ant, eXist/lib/* etc. etc. ! The Files are renamed to %Name +"REMOVED.git-id".

Are you able to disable this git-"feature"?

Best Regards
Stephan

**Comment by joewiz** [comment]
See this announcement from the exist-development mailing list: http://markmail.org/message/taqru6bdkzpap7hk.

**Comment by StephanMa** [comment]
The Problem is still there...
We get this issue still on a clean Installation of Ubuntu, while downloading the branch eXist-2.0.x and eXist-2.2. There is no given Repository to rebuild

**Comment by joewiz** [comment]
To help this issue along, could you further describe what exactly you're doing and the error(s) you're getting?

**Comment by StephanMa** [comment]
In an ANT-Task we pull eXist from this URL
https://github.com/eXist-db/exist/archive/eXist-2.0.x.zip

and while compiling eXist, the error occurs that some classe, like ant.Main are missing.

This Issue occurs while cloning the eXist-2.0.x Branch. So its not just a Problem of this ZIP-File.

When you are downloading this file / cloning this branch, just search for "REMOVED.git-id". There are several files, which were deleted by git or the cleaning-tool.

Thank you for your support!

**Comment by joewiz** [comment]
The guys involved with the changes to the git repository mentioned on eXist-development were @windauer and @adamretter. Guys, do you have suggestions for Stephan? Perhaps the zip file is stale? In this case, should Stephan perform a fresh checkout of the repo, instead of accessing the zip file?

**Comment by adamretter** [comment]
I am just checking Stephan's claim at the moment, sorry for the delay,
internet here is slow, so cloning is taking some time...

On 30 June 2015 at 15:22, Joe Wicentowski <notifications@github.com> wrote:

> The guys involved with the changes to the git repository mentioned on
> eXist-development were @windauer <https://github.com/windauer> and
> @adamretter <https://github.com/adamretter>. Guys, do you have
> suggestions for Stephan? Perhaps the zip file is stale? In this case,
> should Stephan perform a fresh checkout of the repo, instead of accessing
> the zip file?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/eXist-db/exist/issues/712#issuecomment-117205080>.
>



-- 
Adam Retter

skype: adam.retter
tweet: adamretter
http://www.adamretter.org.uk

**Comment by adamretter** [comment]
@joewiz @StephanMa Yeah it seems there are still problems. I think the only branch I fixed was `develop`. So the others which are older will still have issues. Will see what I can do...

**Comment by StephanMa** [comment]
Thank you! I appreciate your help.

**Comment by adamretter** [comment]
@StephanMa Okay I just repaied `master` and also `eXist-2.0.x`, I will continue with the other remaining ones

**Comment by StephanMa** [comment]
Everything is working fine.
Thanks for your fast support!

**Comment by zwobit** [comment]
@adamretter @StephanMa close?

**Comment by StephanMa** [comment]
It is fixed for eXist 2.0 but not for 2.2 (zip file) ...

**Comment by adamretter** [comment]
@StephanMa It should now be fixed for all branches and all tags apart from (`eXist-2.2.RC1`, `eXist-2.2.RC2` and `eXist-2.2`). I am just looking into those last three now...

**Comment by adamretter** [comment]
@StephanMa I think I have now repaired all tags and all branches. If you encounter any further problems just re-open the ticket with a comment.
