### ISSUE TITLE
Windows: Unclean shutdown

### ISSUE THREAD

**Issue by wolfgangmm** [eXist-db/exist#713]
On windows 7, 32bit: machine is shut down cleanly, but eXist crashes and reinforces a recovery run upon restart. This used to work in the past, i.e. eXist received the shutdown signal and stopped properly before windows powered off the machine.

Could someone confirm if this happens on other windows versions as well?

**Comment by dizzzz** [comment]
how significant is the 32bit thing? how to start the server? bin\startup.bat ?

**Comment by wolfgangmm** [comment]
@dizzzz Use the jar installer, then launch eXist via the start menu (using the launcher).

I have no idea if 32 bit is relevant here, but shutting down the machine definitely used to work on this very same machine with eXistdb 2.2. Same Java8, same setup.

**Comment by wolfgangmm** [comment]
The issue is reproducible:

* launch a fresh eXist (via the start menu or bin\startup.bat)
* install one or more apps via the dashboard
* shutdown windows, but without closing eXist
* restart windows and eXist
