### ISSUE TITLE
Installation issue of 3.0rc1 on CentOS 2.6 64bit

### ISSUE THREAD

**Issue by zopyx** [eXist-db/exist#728]
I installed 3.0RC1 on CentOS 2.6.

Starting existdb fails:

[ajung@dev1 existdb-3.0rc1]$ tools/wrapper/bin/exist.sh console
Running eXist-db Native XML Database...
/home/ajung/sandboxes/existdb-3.0rc1/tools/wrapper/bin/./wrapper-linux-x86-64: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /home/ajung/sandboxes/existdb-3.0rc1/tools/wrapper/bin/./wrapper-linux-x86-64)

**Comment by dizzzz** [comment]
Hmmmm, the 'ddl-hell' has started;  We have embedded a new wrapper.so file (custom build) to prevent memory leaks; and because of systems that cannot update libc ; The error suggests to upgrade libc? @adam ?

**Comment by adamretter** [comment]
@zopyx Do you really mean CentOS 2.6? Perhaps you mean 6.2?

**Comment by zopyx** [comment]
Sorry, CentOS 6.6, latest 6.X release.

2015-07-09 16:41 GMT+02:00 Adam Retter <notifications@github.com>:

**Comment by dizzzz** [comment]
I have the same issue,  6.2/6.3 depend on GLIBC_2.12 ; An action must be taken to make the wrapper compatible with the original binary distribution.

on  http://wrapper.tanukisoftware.com/doc/english/supported-platforms-350.html   : 

"During development and prior to each release of the Wrapper will be tested intensively to ensure functionality. The test environment uses the 2.6.18-6 + 2.6.31-20 kernel and should be downwards compatible. The used libc version is 2.3.6 + 2.10.1."

IMO... compatibility with " 2.3.6 + 2.10.1" must be restored.

**Comment by adamretter** [comment]
It's not a kernel version issue it's a glibc version issues. The version of Glibc was changed between RHEL/CentOS  6 and 7 branches. I will check which version the Tanuki release is compiled against, however I suspect it only supports one or the other...

**Comment by Annakan** [comment]
Should the RHEL/CentOS 6 considered dropped ? Or does a way around exist ?

**Comment by dizzzz** [comment]
Yes replacing two files makes it work again....

--
www.exist-db.org

**Comment by dizzzz** [comment]
Issue is not relevant anymore as we migrated to `yasjw`
