### ISSUE TITLE
A space in JAVA_HOME on Windows 7 causes build.bat to fail

### ISSUE THREAD

**Issue by adamretter** [eXist-db/exist#729]
Using cmd.exe:

```cmd
git clone https://github.com/exist-db/exist.git
cd exist
set JAVA_HOME="c:\Program Files\Java\jdk1.8.0_45"
build.bat
```

Results in:
`Files\Java\jdk1.8.0_45"" was unexpected at this time.`

**Comment by dizzzz** [comment]
yes, this has been the case for a long time :-( I typically use Program~1\Java\jdk as work around;  I am not sure anymore why I never fixed it,it might because XP, windows7 and ..... have different behaviour here....
