### ISSUE TITLE
The value of local-name applied to a text node is null, not the empty string

### ISSUE THREAD

**Issue by jensopetersen** [eXist-db/exist#735]
Calling local-name() on a text node should return the zero-length string. In the following, the let statement does nothing, but brings about a NPE.

	declare function local:copy($element as element(), $tests as element()) as element() {
		element {node-name($element)}
		{$element/@*,
		for $child in $element/node()
		let $name := $tests//test[case eq local-name($child)]
		return
			if ($child instance of element())
			then local:copy($child, $tests)
			else $child
		  }
	};
	
	let $fragment :=
	<x>
		<y>a</y>
	</x>
	
	let $tests :=
	<tests>
		<test>
			<case>y</case>
		</test>
	</tests>
	
	return
		local:copy($fragment, $tests)
	
Remove the text node in $fragment, and it works. Change local-name() to name() and it works.

local-name() applied to a text node evaluates to null, not the empty string:

	let $fragment :=
	<x>
		<y>a</y>
	</x>
	
	let $text-node := $fragment//text()
	
	return
		local-name($text-node)

With name() it returns the empty string.

**Comment by telic** [comment]
Actually, node-name should return the empty **sequence** for a text node, not an empty string.

Here's a simplified query that exhibits the NPE:

```
<a>b</a>/node-name(text())
```

Importantly, this only seems to be a problem with constructed nodes, not with text nodes in stored documents. If we had a document "test.xml" that contained `<a>b</a>`, the query `doc('test.xml')/a/node-name(text())` would work as expected.

**Comment by jensopetersen** [comment]
No, node-name should only return the empty sequence if it is passed the empty sequence. 

local-name() should return the empty string when passed a text node: "If the node identified by $arg has no name (that is, if it is a document node, a comment, a text node, or a namespace node having no name), the function returns the zero-length string." http://www.w3.org/TR/xpath-functions-31/#func-local-name.

name() and local-name() both return the empty string, also when passed the empty sequence. I don't understand why node-name returns the empty sequence in this (and other) cases (http://www.w3.org/TR/xpath-datamodel-31/#acc-summ-node-name). How can a name be a sequence?

**Comment by telic** [comment]
Apparently my brain was not fully engaged yesterday, sorry! Not only did my reduced test case not show the problem, but I was talking about node-name the whole while you were talking about local-name...

I've corrected my comment above accordingly.

The behaviour difference between local-name and node-name definitely is a little strange. It seems the authors of the spec were thinking of node-name more like other node property accessors, which all return the empty sequence if the property doesn't exist.  local-name and name, on the other hand, are not accessors: they return computed strings.
