### ISSUE TITLE
Switch from Ant to a Maven build system

### ISSUE THREAD

**Issue by adamretter** [eXist-db/exist#736]
I want to switch eXist from the existing Ant and shell script build system to Maven. The advantages I see are this:
1. A simple build process that is by convention
   1 Currently with Ant it is very hard to determine what JUnit tests are included in which build targets and which tests are never executed.
2. Easy management, resolution and update of dependencies.
   1. No longer need to keep dependencies in SCM (Git)
   2. Ability to detect unused and/or undeclared dependencies (`mvn dependency:analyze`)
   3. Ability to check/report on outdated dependencies which can help with security advisories and bugfixes (`mvn versions:display-dependency-updates` and `mvn versions:display-plugin-updates`)
3. Ability to publish Maven artifacts which is useful for users:
   1. Embedding eXist in others apps
   2. Building extensions for eXist (e.g. XARs that have a Java component)
   3. With the correct build process, publishing to Maven Central can be as easy as `mvn release:prepare && mvn release:perform`.
   4. Ability to publish Maven snapshots of nightly builds.
4. Multiple targets
   1. Ability to generate shell scripts for running eXist as part of the build
   2. IzPack installer
   3. Bin package with dependencies
   4. Src package with/without dependencies
   5. Javadoc package
5. Ability to run tools easily across the code-base as part of the build
   1. Ensure license headers are consistent (`mvn license:check` and `mvn license:format`)
   2. Ability to detect and report license conflicts e.g. GPL components (`license-verifier:check` and `license-verifier:report`).
   3. Ability to ensure coding standards (`mvn checkstyle:check`)
   4. Static analysis reports and warning
6. Auto code generation during build
   1. Antlr for the XQuery parser
   2. AspectJ for the Security annotations
7. Modular build system
   1. Just build/re-build the modules that you need during development and testing.
   2. Each extension module can be its own Maven module complete with tests. At present with Ant we cannot add XQuery tests for extension modules without introducing a reverse dependency.
8. Surefire for running the test suites and reporting which JUnit tests are actually run or not
   1. Ability to split the test suite into unit tests and integration tests with separate targets for each, should lead to faster test feedback

The switch will require some minimal reorganising of some of the folders within the eXist repo, for example `src/org` -> `src/main/java/org`; When the PR for this is committed to the code-base users will need to merge/rebase their branches (and/or forked repo branches).

**Comment by jensopetersen** [comment]
Thank you for this detailed advance explanation of what you wish to achieve. Now let's hear some arguments pro et con.

**Comment by adamretter** [comment]
@jensopetersen I opened a Doodle poll for gauging support, it is by invite, so I just invited you. If anyone else has a string opinion, please ask and I will also invite you.

**Comment by dizzzz** [comment]
thnx adam for elaborating on your ideas...

**Comment by dizzzz** [comment]
idea: we can make the build system a bit simpler by moving out the webstart/jnlp jars (signed) into a separate XAR library....

**Comment by adamretter** [comment]
@dizzzz `bin/start.sh` would become `mvn jetty:run`

**Comment by dizzzz** [comment]
Right, I do not agree on that. :) maven is to
Build not no execute. This is a serious point to me and the community. Maven as a build and dependency tool is ok, but there it stops.


--
www.exist-db.org

**Comment by adamretter** [comment]
@dizzzz Maven is much more than just a build an dependency tool. You can create scripts if you want, but you will end up reinventing wheels that are rounder and faster... Not to mention you then have to maintain these odd shaped wheels ;-)

**Comment by shabanovd** [comment]
@dizzzz running production by maven is safe and best way to go. Also possible to generate lib folder with all jars if prefer control things and have installer to deploy without maven.

**Comment by wolfgangmm** [comment]
On the server it should still be possible to deploy a pre-built eXist and run it without requiring anything other than java installed, using a non-root user. The guy who installs eXist is often not the administrator.

I most often launch eXist in either of those ways, depending on the concrete scenario: 1) java -jar start.jar, 2) bin/startup.sh, 3) bin/client.sh -l, 4) tools/wrapper/bin/exist.sh. I don't mind if startup.sh becomes mvn jetty:run in a dev environment as long as I have full control over the jvm and its settings, but I still need all of the above choices (and some other utilities) for effective maintenance and troubleshooting.

**Comment by shabanovd** [comment]
@wolfgangmm do you need 1,3,4 with installer or in development too?

**Comment by wolfgangmm** [comment]
@shabanovd both, in development and production (the distinction is often blurred anyway). I normally start eXist using the start.jar launcher, but switch to bin/client.sh -l for debugging, maintenance and troubleshooting. And on some systems (windows), the wrapper is the only really save way to run eXist.

**Comment by eduarddrenth** [comment]
Any idea when exist-db will be mavenized? For me this is rather a big thing. I have migrated projects from ant to maven before and may consider contributing to this issue. Note that such a migration requires you to know how to do things properly in maven.

**Comment by dizzzz** [comment]
@eduarddrenth please can you describe in concrete terms why this is a big thing for you right now? Please don't expect this to be happening very soon

**Comment by dizzzz** [comment]
@adamretter in your description you say that exist would be started with `mvn jetty:run` ... but how would that work when ppl are only interested in running exist-db? We could only rely on this when we distribute a copy of maven as well?

**Comment by adamretter** [comment]
@eduarddrenth I am already working on it, if you email me @exist-db.org, I will make sure to try and include you in discussions. I would value your feedback.

**Comment by joewiz** [comment]
@eduarddrenth Thank you for interest in contributing to eXist! For your information, the current status of this, as discussed in the eXist Community Call last week (see the [agenda and notes](https://docs.google.com/document/d/1XkUvvsdU1Xqea9aay1_VIzwzmzRqXaJgcN_PjEgSD_o/edit?usp=sharing) on this topic), is that @adamretter proposed preparing a script to transform a checked out copy of the develop branch into a proper maven project. The script would allow the community to test the results locally, and discuss questions/concerns they have, in preparation for a final decision. He estimated it would take about 2 weeks' development time on his part to prepare the script. He also noted that before the script is applied, all existing PRs should be merged or closed, as files referenced in these PRs will certainly be moved into new locations according to the maven project structure.

Certainly, as @dizzzz and just now @adamretter mentioned, we'd like to hear more about your interest in this project.

**Comment by adamretter** [comment]
@dizzzz That would only be for developers using the source code. Users would still have the shell scripts; I did try and highlight that above.

**Comment by adamretter** [comment]
@joewiz Just to add to Joe's comments, I plan to focus on the Maven'ization work once the 3.1.0 release is out on the 7th March 2017.

**Comment by eduarddrenth** [comment]
Thanks for the quick responses. At the Fryske Akademy in the netherlands we
have tei material we want to publish and query (linguistic research, corpus
query language probably). We have some options here,
http://inl.github.io/BlackLab/, https://github.com/meertensinstituut/mtas,
diy, basex, existdb. Personally I favor existdb because it feels mature,
integrates well with tei and oxygen, has a plugin mechanism and there is
https://github.com/BCDH/cql-module. Having maven (dependency management,
build system, release and other plugins) in place greatly adds to the
overall quality of a project, hence my question.

**Comment by dizzzz** [comment]
@eduarddrenth sorry you did not answer, why it 'is a big thing' ? What is the use case what is blocking you?

**Comment by eduarddrenth** [comment]
Nothing blocking, so not a big thing in that respect, it is a big thing in
my selection process

**Comment by adamretter** [comment]
@eduarddrenth Nice to heart that you are using the CQL Module that we recently added :-)

If you want just artifacts for eXist-db, the current best option is here: https://github.com/exist-db/mvn-repo

We can do much better though, which is why I am pushing the Maven'ization. I am looking forward to collaborating with you.

**Comment by eduarddrenth** [comment]
Sounds ok...

But first.... I want to see things running and I am having problems with that.

- exist install ok
- dashboard etc. ok
- install tei publisher ok
- copy tei corpora via webdav ok
- create tei publisher app ok
- load xml in exide ok
- convert to pdf NOT OK

url for pdf: http://localhost:8080/exist/apps/tdb/works/.pdf?token=3ffbdf37-63e2-469d-99c2-39791a94865a&cache=no&odd=tei_simplePrint.odd **=> the /.pdf seems weird.**

fault: exerr:ERROR XPTY0004: The actual cardinality for parameter 1 does not match the cardinality declared in the function's signature: tpu:parse-pi($doc as document-node(), $view as xs:string?) item()*. Expected cardinality: exactly one, got 0. [at line 97, column 29, source: /db/apps/tdb/modules/lib/pdf.xql]
In function:
	tpu:parse-pi(document-node(), xs:string?) [97:16:/db/apps/tdb/modules/lib/util.xql]

any ideas?

**Comment by joewiz** [comment]
@eduarddrenth That is an issue unique to the tei-publisher-app.  Could you please file this report at http://gitlab.exist-db.org/tei-publisher/tei-publisher-app/issues, indicating the usual details, e.g., version of eXist, version of tei-publisher-app, and any relevant modifications to the generated app that you might've made?

**Comment by eduarddrenth** [comment]
done

**Comment by adamretter** [comment]
@eduarddrenth @joewiz I am going to remove the above 3 messages as they are off-topic. Ok?

**Comment by joewiz** [comment]
Yes, go ahead - the report is now captured elsewhere.

**Comment by eduarddrenth** [comment]
fine
