### ISSUE TITLE
use of "order by" is too restrictive

### ISSUE THREAD

**Issue by telic** [eXist-db/exist#739]
According to the spec, FLWOR expressions may contain any number of "order by" clauses intermingled with other clauses before the return. However, eXist only allows a single "order by" clause as the final clause before the return; all other uses result in a parse error.

For example, this is a valid XQuery that results in a parse error in eXist:

```
for $x in (3, 2, 4)
order by $x
for $y in (1 to $x)
return $y
```

This can usually be worked around by rearranging the clauses or using nested FLWOR expressions (eg. simply inserting a `return` clause between the `order by` and second `for` in the above example), but it's not always obvious how to do so while getting the same result.

**Comment by ljo** [comment]
Thanks, this is a chasing problem.

**Comment by telic** [comment]
@wolfgangmm will your groupby-fix branch be addressing this issue?

**Comment by wolfgangmm** [comment]
Yes, "order by" and "group by" are now expressions on the same level as "for" or "let". I just need to finish my cleanup of the xquery grammar, which is what I'm working on right now.

**Comment by adamretter** [comment]
Closed by https://github.com/eXist-db/exist/pull/763
