### ISSUE TITLE
catch does not support partial wildcards

### ISSUE THREAD

**Issue by telic** [eXist-db/exist#742]
According to the XQuery 3 spec, the catch clause in a try/catch expression should support any NameTest, including `*:name`, and `ns:*` wildcard forms.  However, only NCName's, QName's, and " * " are currently supported by eXist.  eXide reports an "<AST>:0:0: Unexpected AST node" error for other wildcard types.

PS: URIQualifiedName's aren't supported either, but they seem to be generally unsupported in eXist, not just in try/catch.

**Comment by ljo** [comment]
Yes, this is an area where some improvements can be done. Thanks.

**Comment by adamretter** [comment]
Should be addressed at the same time as https://github.com/eXist-db/exist/issues/743 and https://github.com/eXist-db/exist/issues/745
