### ISSUE TITLE
error variables in catch occluded by namespace definition

### ISSUE THREAD

**Issue by telic** [eXist-db/exist#743]
Try/catch clauses make some "magic variables" available in the catch block under the "err" namespace which the XQuery spec defines as "http://www.w3.org/2005/xqt-errors" (eg. $err:code, $err:description, etc).  However, eXist only understands these variables if the 'err' prefix is **unbound** in the query.

For example, this works as one would expect, returning 'just a test':
```
try {
  error(xs:QName('test'), 'just a test')
} catch * {
  $err:description
}
```
But simply adding the namespace definition for 'err' as below results in an XPDY0002 compile-time error:
```
declare namespace err="http://www.w3.org/2005/xqt-errors";
try {
  error(xs:QName('test'), 'just a test')
} catch * {
  $err:description
}
```

This is the exact **opposite** behaviour than expected by the spec, since it states that the 'err' namespace prefix is not predeclared.

**Comment by ljo** [comment]
Yes, you are right.

**Comment by adamretter** [comment]
Should be addressed at the same time as https://github.com/eXist-db/exist/issues/745

**Comment by adamretter** [comment]
So this is an interesting one. The error message produced by eXist is not very clear at the moment, I will shortly send a fix to improve it, after the improvement the error you would get looks like this:

> An exception occurred during query execution: err:XQST0033 Cannot bind prefix 'err' to 'http://www.w3.org/2005/xqt-errors' it is already bound to 'http://www.w3.org/2005/xqt-errors/'

Basically different W3C documents have used either of those namespaces (note the trailing or omitted `/` char) to refer to the same thing, in fact I previously opened a bug for that here: https://www.w3.org/Bugs/Public/show_bug.cgi?id=29610.

I think it was intended to be `http://www.w3.org/2005/xqt-errors`; That is what Saxon is using, and it is also what is in all of the F+O specs, so I will send a change for that too shortly.

**Comment by adamretter** [comment]
Here are the fixes: https://github.com/eXist-db/exist/pull/1089

**Comment by dizzzz** [comment]
Nice ! @wolfgangmm @ljo
