### ISSUE TITLE
unbound namespaces allowed in catch clause

### ISSUE THREAD

**Issue by telic** [eXist-db/exist#744]
eXist allows unbound namespaces to be used in the NameTest of a catch clause.  I'm not entirely convinced this is actually a bug according to the spec, but it still feels wrong.

For example, the following compiles and runs just fine

```
try {
  'test'
} catch unbound:test {
  'caught'
}
```

but I would expect it to fail with a err:XPST0008 during compile time since the "unbound" prefix is not statically known.  Is there any case where this would do something useful and isn't a sign of a possible typo?

**Comment by ljo** [comment]
Thanks, lets see.

**Comment by duncdrum** [comment]
closed with test in #764
