### ISSUE TITLE
XML RPC, query vs retrieveAll

### ISSUE THREAD

**Issue by ambs** [eXist-db/exist#755]
Looking to `src/org/exist/xmlrpc/RpcConnection.java`, there are mainly two approaches to query eXist:

   1. Using the pair `executeQuery` + `retrieve(All)` methods.
   2. Using the `query` method.

The second has two interfaces, one returning a byte array, and marked as deprecated in the website, and another one returning a string, that I am not sure if it is deprecated or not. 

Nevertheless, using `retrieveAll` or `query` behaves differently. If the query return a set of text() values, the result is the same from both methods: a `<exist:result>` with the strings concatenated. In the other hand, if the query returns a set of URI (for example, mapping `fn:base-uri` to a set of resources), `retrieveAll` returns a `exist:result` with the URI concatenated. If using `query`, the result is a `exist:result` that contain `exist:value` elements.

If this difference is the desired one, then I need to know if `query` returning a string is or not deprecated (and I hope it is not). In the other hand, if the difference is not desired, probably this should be fixed.

Looking to the code, the main different is that `retrieveAll` uses `retrieveAllAsString` that does the following code for each answer:

``````java
                   if (Type.subTypeOf(current.getType(), Type.NODE)) {
                        current.toSAX(broker, handler, null);
                    } else {
                        value = current.toString().toCharArray();
                        handler.characters(value, 0, value.length);
                    }
``````
that is, if the result is a XML fragment, return it, if not, string the string without any outer tag.

In the other hand, `query` uses `printAll` that has a similar iteration, with this code:
`````java
            if (item.getType() == Type.ELEMENT) {
                final NodeValue node = (NodeValue) item;
                writer.write(serializer.serialize(node));
            } else {
                writer.write("<exist:value type=\"");
                writer.write(Type.getTypeName(item.getType()));
                writer.write("\">");
                writer.write(item.getStringValue());
                writer.write("</exist:value>");
            }
``````
I am not sure what the difference between a `Type.ELEMENT` or a `Type.NODE`, but I would say the second option is better and should be used in both situations.

Note that when using the REST API, the structured result is what is obtained. Using the XML-RPC, it depends on what method you call.

(not sure if I made myself clear, also happy for any extra explanation)

**Comment by ambs** [comment]
Some examples:

   1. REST:
      1. concatenated strings: http://per-fide.di.uminho.pt:8080/exist/rest/db/?_query=collection%28%27/db/dicaberto%27%29/entry/form/orth/text%28%29[contains%28.,%27avalo%27%29]
      2. structured result: http://per-fide.di.uminho.pt:8080/exist/rest/db/?_query=collection%28%27/db/dicaberto%27%29/entry[.//usg[@type=%22dom%22%20and%20contains%28.,%22Astron.%22%29]]!fn:base-uri%28.%29

   2. XML RPC using `retrieveAll` for the first query:
````
<exist:result xmlns:exist="http://exist.sourceforge.net/NS/exist" exist:hits="2" exist:start="1" exist:count="2" exist:session="1">CavaloarCavalo</exist:result>
`````

   3. XML RPC using `retrieveAll`, for the second query:
````````
<exist:result xmlns:exist="http://exist.sourceforge.net/NS/exist" hitCount="23">/db/dicaberto/014096.xml/db/dicaberto/011319.xml/db/dicaberto/009635.xml/db/dicaberto/125442.xml/db/dicaberto/123110.xml/db/dicaberto/116644.xml/db/dicaberto/116544.xml/db/dicaberto/096455.xml/db/dicaberto/096448.xml/db/dicaberto/096132.xml/db/dicaberto/093604.xml/db/dicaberto/093576.xml/db/dicaberto/080881.xml/db/dicaberto/075936.xml/db/dicaberto/046602.xml/db/dicaberto/042346.xml/db/dicaberto/042119.xml/db/dicaberto/042078.xml/db/dicaberto/037269.xml/db/dicaberto/036344.xml/db/dicaberto/036241.xml/db/dicaberto/032711.xml/db/dicaberto/032710.xml</exist:result>
``````````

**Comment by ambs** [comment]
-- as an extra note, this was tested with version 2.2, but looked to code from git. Installing now 3.0rc1.

**Comment by dizzzz** [comment]
in this context very little changes have been made since a few years

**Comment by ambs** [comment]
Just confirmed the same behavior on 3.0rc1.

**Comment by ambs** [comment]
In case you think my analysis is correct and retrieveAll should be changed, let me know, and I'll try to work on a pull request.

**Comment by adamretter** [comment]
@ambs I am not sure if the behvaiour should be changed or not.

Certainly the difference is in the two `else` statements of the code fragments that you posted. One of them is wrapping each atomic value in an `<exist:value>` whereas the other is not.

Does the current behavior cause a problem for you? If it does and it seems incorrect, then please do send a pull-request (don't forget you may need to modify the Java Admin Client to work with any changes you make).

**Comment by ambs** [comment]
Dear @adamretter, thanks for your answer. At the moment I am in vacation mode, but I'll try to find out where in eXist that method is being used, and check if the change can break something.

Meanwhile, a little help would be good: what is the "semantic" difference from a `Type.NODE` and a `Type.ELEMENT`?

**Comment by adamretter** [comment]
@ambs An Element is a type of Node, you can see the type model here - http://www.w3.org/TR/xpath-datamodel-30/#types-hierarchy

**Comment by ambs** [comment]
:+1: thanks

**Comment by ambs** [comment]
I am working on this, and have code already working, but I am trying to work with Perl XML::eXistDB author in order to make it behaving correctly (I hope).

But as far as I cold tell, eXist behavior on some things is quie ad-hoc, and difficult to convince the Perl module of the changed I am proposing.

Therefore, it would happen if there is a schema describing the `<exist:result>` element.
The schema it is being used is this one: http://cpansearch.perl.org/src/MARKOV/XML-ExistDB-0.14/lib/XML/eXistDB/xsd-exist/existdb.xsd

but as you might notice, it doesn't allow `<exist:result>` to include `<exist:value>`.

Is there such a document? If not, are you willing to help me to define one?
(in that case I might open another issue to work on that)

**Comment by adamretter** [comment]
@ambs We don't provide any schemas for the XML-RPC API as the XML itself is generated from code. You can of course work backwards (as you have done) to create Schemas.

If for some reason it helps to add the Schemas to the official eXist, you can send a PR to place them in $EXIST_HOME/schemas. However please keep in mind that this then requires them to be maintained. I guess in the least you need to mention them in some JavaDoc for the RPCAPI and RPCConnection classes.
