### ISSUE TITLE
XML-RPC example fix

### ISSUE THREAD

**Issue by ambs** [eXist-db/exist#756]
Sorry for not preparing a full pull request, but no idea where these pages are stored (if they are at all) in github.

But this page: http://exist-db.org/exist/apps/doc/devguide_xmlrpc.xml
the third example (with caption 'Another Query Examplet (XML-RPC)')
doesn't work as the executeQuery needs a third parameter with options.

This diff
https://gist.github.com/ambs/ea0a58cc14ac990b42d3
runs with 2.2 and 3.0rc1, and latest Perl RPC::XML module.

Cheers

**Comment by joewiz** [comment]
See https://github.com/eXist-db/documentation/blob/master/data/devguide_xmlrpc.xml. A pull request there would be most welcome.

**Comment by ambs** [comment]
Will do it :)

**Comment by ambs** [comment]
Done. So, closing this issue. Cheers.
