### ISSUE TITLE
unwanted unescaping escaped text in ExistDB 2.2 

### ISSUE THREAD

**Issue by agucabral21** [eXist-db/exist#760]
I'm tying to migrate to 2.2 from 2.1.

I have an xml stored in my db that contains this element 
```
<cmnext:text> 
         
               &lt;ul&gt;
               &lt;li&gt;LTE&lt;/li&gt;
               &lt;li&gt;Blackberry 10.2 OS&lt;/li&gt;
               &lt;li&gt;Pantalla de 5&amp;#34;&lt;/li&gt;
               &lt;li&gt;Cámara de 8 MP&lt;/li&gt;
               &lt;/ul&gt;
               </cmnext:text>
```

I call an xquery using rest and what the response in 2.1 comes exactly the same, with the escape characters, but when i do the same with 2.2 the response comes like this
```
 <cmnext:text><![CDATA[<ul>
               <li>LTE</li>
               <li>Blackberry 10.2 OS</li>
               <li>Pantalla de 5&#34;</li>
               <li>Cámara de 8 MP</li>
               </ul>]]></cmnext:text>
```

I want to be able to recieve the same response i was getting in existdb 2.1.

Is there any way to unable this escape processing exist is doing?

**Comment by joewiz** [comment]
Could you provide a little more context?  What serialization options are you using?  Are there any other transformations operating on the output of your query, such as a `<view>` directive in a `controller.xql` file?  Also, you say you're using the rest interface - so I assume your request is to a URL like `/exist/rest/db/...`; but if not, please specify.

**Comment by agucabral21** [comment]
No there are no transformations, i just filter some xml to get some elements and return it.
And im not using the controller.xql, im calling a .xquery file using soapui like this /exist/rest/db/.../file.xquery

Im using xquery version "3.0" , and im not using any serialization options

**Comment by agucabral21** [comment]
ive edited my previous response

**Comment by agucabral21** [comment]
The problem was soapui when if i save the document in the db it stays with the scape characters, sorry... and thanks!!!
