### ISSUE TITLE
Wrapper writes all logging into tools/wrapper/logs

### ISSUE THREAD

**Issue by dizzzz** [eXist-db/exist#771]
When eXist-db is started via the service wrapper, all logfiles are written into the `tools/wrapper/logs` directory.

For me it is OK to have all logs in one directory but it might be a bit confusing for existing users (the old logfiles are still on the old location).

Any opinions on this?

**Comment by ljo** [comment]
I don't think it is confusing to that many people. If you are running the wrapper you know where they are by default and can change it to any suitable location. If you run it container directly way you find the logs where most of the documentation refers to it. The only strangeness I have found people react to is when using the java admin client with other user than the wrapper is running.
