### ISSUE TITLE
html5 method eating attribute value when value is eq to name

### ISSUE THREAD

**Issue by christophe-g** [eXist-db/exist#777]
With very recent build on develop branch,

``` xquery
xquery version "3.0";

declare namespace output = "http://www.w3.org/2010/xslt-xquery-serialization";
declare option output:method "html5";

<html>
    <div test="test">Hello</div>
</html>
```

will return 

``` xml

<html>
    <div test>Hello</div>
</html>
```

This causes the browser to report 

```
This page contains the following errors:

error on line 3 at column 13: Specification mandate value for attribute test
Below is a rendering of the page up to the first error.
```

... and the wiki app to behave strangely as some parameter will never be sent to the server, like `name` in : 

``` xml
 <input class="form-control" data-template="app:edit-name" type="text" name="name" placeholder="ShortName" required="required" pattern="[A-Za-zäöüÄÖÜ]{1}[\w-äöüßÄÖÜ]{2,}"/>
```

C.

**Comment by christophe-g** [comment]
@wolfgangmm... just before it disappears on page 2, can it be confirmed as a bug ?
Cheers,
C.

**Comment by wolfgangmm** [comment]
Well, I guess the HTML5 serialiser needs a list of attributes which can be empty (e.g. "disabled") and should thus be collapsed. All other attributes should be preserved. I have not found such a list yet though.

**Comment by joewiz** [comment]
According to the HTML5 spec on [boolean attributes](http://www.w3.org/html/wg/drafts/html/master/infrastructure.html#boolean-attributes) (see also the [WHATWG version](https://html.spec.whatwg.org/#boolean-attributes)), `<div test="test">` is absolutely equivalent to `<div test>`.  I think eXist's HTML5 serializer is correct.

My question is: what is responsible for issuing the error, "Specification mandate value for attribute test"?  Is it the browser (if so, which?) or some script running in the page (if so, is there an HTML5-compatible version?)?

**Comment by christophe-g** [comment]
@joewiz Agreed (and thanks for the refs), but in this specific case, `test` is not a boolean attribute. 
@wolfgangmm Should really `test="test"`, `name="name"` or `data-keepme="data-keepme"` attributes  be collapsed under html5 serialization? 

There are 2 problems here : 
- the actual string value of the attribute disappears. In the following, the submission data a server will receive are not equivalent. 
Consider
```html
<form action="submit.xql">
  Name: <input type="text" name="name"><br>
  <input type="submit" value="Submit">
</form>
```
parsed as (without value `name` as it is the case in the wiki) : 
```html
<form action="submit.xql">
  Name: <input type="text" name><br>
  <input type="submit" value="Submit">
</form>
```
- Apparently the markup is malformed (error reported on Chrome 45 - htm5 compliant)

**Comment by joewiz** [comment]
Here's a list of boolean attributes drawn from the spec:

  https://github.com/kangax/html-minifier/issues/63#issuecomment-37763316

Since that list might be out of date, I've applied the same methodology to produce an up to date list from the current HTML 5.1 spec:

```xquery
xquery version "3.0";

declare namespace html="http://www.w3.org/1999/xhtml";

import module namespace http="http://expath.org/ns/http-client";

<results>{
    let $url := "http://www.w3.org/TR/html51/single-page.html"
    let $request := <http:request href="{$url}" method="get"/>
    let $response-body := http:send-request($request)[2]
    let $hits := $response-body//text()[contains(., 'attribute boolean')]/following-sibling::html:a[1]
    for $attribute in distinct-values($hits)
    order by $attribute
    return
        <result>{$attribute}</result>
}</results>
```

Results:

```xml
<results>
    <result>allowFullscreen</result>
    <result>async</result>
    <result>autofocus</result>
    <result>autoplay</result>
    <result>badInput</result>
    <result>checked</result>
    <result>closed</result>
    <result>commandChecked</result>
    <result>commandDisabled</result>
    <result>commandHidden</result>
    <result>compact</result>
    <result>complete</result>
    <result>controls</result>
    <result>cookieEnabled</result>
    <result>customError</result>
    <result>declare</result>
    <result>default</result>
    <result>defaultChecked</result>
    <result>defaultMuted</result>
    <result>defaultSelected</result>
    <result>defer</result>
    <result>disabled</result>
    <result>draggable</result>
    <result>enabled</result>
    <result>ended</result>
    <result>formNoValidate</result>
    <result>hidden</result>
    <result>indeterminate</result>
    <result>isContentEditable</result>
    <result>isMap</result>
    <result>itemScope</result>
    <result>javaEnabled</result>
    <result>loop</result>
    <result>multiple</result>
    <result>muted</result>
    <result>noHref</result>
    <result>noResize</result>
    <result>noShade</result>
    <result>noValidate</result>
    <result>noWrap</result>
    <result>onLine</result>
    <result>open</result>
    <result>patternMismatch</result>
    <result>pauseOnExit</result>
    <result>paused</result>
    <result>persisted</result>
    <result>rangeOverflow</result>
    <result>rangeUnderflow</result>
    <result>readOnly</result>
    <result>required</result>
    <result>reversed</result>
    <result>scoped</result>
    <result>seamless</result>
    <result>seeking</result>
    <result>selected</result>
    <result>sortable</result>
    <result>spellcheck</result>
    <result>stepMismatch</result>
    <result>tooLong</result>
    <result>tooShort</result>
    <result>translate</result>
    <result>trueSpeed</result>
    <result>typeMismatch</result>
    <result>typeMustMatch</result>
    <result>valid</result>
    <result>valueMissing</result>
    <result>visible</result>
    <result>willValidate</result>
</results>
```

**Comment by devatwork** [comment]
I just hit this issue by following the steps described at http://www.exist-db.org/exist/apps/doc/development-starter which is kind of confusing for first-time developers using the `evolvedbinary/exist-db:eXist-5.0.0-RC1-minimal` Docker image. It would be good to fix this bug. If not possible, at the very least document the behavior and change the tutorial to work around this issue.

**Comment by devatwork** [comment]
Just took a quick look at the source code and the problem seems to be at https://github.com/eXist-db/exist/blob/develop/src/org/exist/util/serializer/HTML5Writer.java#L103

Would you be open to a PR implementing a check on the boolean whitelist as reported by @joewiz?

**Comment by duncdrum** [comment]
@devatwork thanks for taking a look at this, PRs with fixes are always welcome. When you open the PR  could you please indicate if the documentation is now working as expected or include any necessary adjustments in a separate PR at [the docs](https://github.com/eXist-db/documentation)
