### ISSUE TITLE
New range index causing trouble when going up an XML tree

### ISSUE THREAD

**Issue by christian-schwaderer** [eXist-db/exist#779]
Consider an HTML file like this:

```
<html>
    <head/>
    <body>
        <span id="foo1">
            <span id="foo2">Foo!</span>
        </span>
    </body>
</html>
```

Now we try the query below:

```
doc('/db/apps/test/test.html')//span[@id='foo2']/parent::span[@id='foo1']
```

This works perfectly fine without an index (and also in Oxygen). Once you set a new range index for @id with the following lines

```
<range>
    <create qname="@id" type="xs:string"/>  
</range>
```

-- it won't work anymore. It works for a single step, i.e. you can either go to the first span or to the second. It also works top-down, going first to the "higher" span than to the lower, but going up the tree with parent:: and ancestor:: doesn't work after setting the index for @id.

This was tested and reproduced on two eXist 3.0 RC1 installtions on Windows 7 and Mac iOs.

**Comment by dizzzz** [comment]
after updating `conf.xml`, did you perform a re-index?
the engine does not return results if a collection of documents is only partially indexed...

**Comment by christian-schwaderer** [comment]
Yes I did (sorry, forgot to mention). And I tested it also the other way round: Removing the index entry in collection.xconf (I guess, this is what you meant? Or does EXIST_HOME/conf.xml actually affect that behaviour?), re-indexing -> works perfectly. Re-inserting the entry for @id, re-index again -> doesn't work.

**Comment by dizzzz** [comment]
ah sorry I meant `collection.xconf`

**Comment by dizzzz** [comment]
please could you install Monex? This app provides details about the indexes......

**Comment by christian-schwaderer** [comment]
Well, the output is not particularily helpful, I guess.
For the query
doc('/db/apps/test/test.html')//span[@id='foo2']/parent::span[@id='foo1']
 being the only line in "test_query", the profiling says
test_query.xq [1:41] 	new-range 	Full 	1 	0.0
test_query.xq [1:66] 	new-range 	Full 	1 	0.0

The "indexes" page is also not very exciting:

Keys for the New Range index defined on "@id" in the /db/apps/test collection, by node.
term ↓ 	frequency 	documents 	position
foo1 	1 	1 	1
foo2 	1 	1 	2

**Comment by christian-schwaderer** [comment]
Did you succeed in reproducing this phenomenon?
BTW, it's meant more to be a bug report than a question. For my own project, I was able to re-structure my query to avoid that issue. However, if I'm right and it turns out that adding a range index prevents eXist from return the expected results of formerly working XPath expressions, that would be, in my opinion, a serious issue.

**Comment by wolfgangmm** [comment]
I was able to reproduce the issue. It seems to be a problem with the optimizer rewriting the expression. Debugging it...

**Comment by dizzzz** [comment]
Sorry I did not have time to reproduce it yet. Yes I think it is a bug too....

**Comment by duncdrum** [comment]
I m no longer able to reproduce this on 4.0.0. 

Good to close?
