### ISSUE TITLE
Feature request: map:put

### ISSUE THREAD

**Issue by wshager** [eXist-db/exist#786]
map:put is a very useful operation and part of the xquery 3.1 spec. please add it.

**Comment by wolfgangmm** [comment]
Yes,  some functions were renamed or added between the last and the newest version of the spec. I planned to address them all in one go before 3.0 final. In fact, put does the same as

map:new(($map, map:entry($key, $value)))

in eXist 3.0RC1 (map:new is now called map:merge in the spec).

**Comment by wshager** [comment]
Ok great. That's indeed how I wrote it.
