### ISSUE TITLE
lock resouce

### ISSUE THREAD

**Issue by mjFakhar** [eXist-db/exist#793]
enable lockResource method in xmldb module.
i want lock documents in shared collection for any user. i want lock document for edit user

**Comment by duncdrum** [comment]
lock mechanism have undergone a fairly comprehensive overhaul. Please open a new issue, if there are new problems in that area. It would help the discussion if you could outline your use cases and how the current approach is not serving them. Thx

**Comment by adamretter** [comment]
@duncdrum Probably better to reopen the same issue rather than a new issue (if it is still relevant)
