### ISSUE TITLE
Update Java Service Wrapper to 3.5.27

### ISSUE THREAD

**Issue by adamretter** [eXist-db/exist#800]
Tanuki have release version 3.5.27 of the Java Service Wrapper. We should check whether this addresses the memory leaks previously detailed here - http://static.adamretter.org.uk/wrapper-patched/

I have emailed the wrapper-user mailing list asking for clarification - http://sourceforge.net/p/wrapper/mailman/message/34515098/

If they have fixed the issues we can do a straight upgrade. If not we will need to patch 3.5.27 and upgrade to our patched version.

**Comment by dizzzz** [comment]
simon released the 64bit windows version on http://www.krenger.ch/blog/java-service-wrapper-3-5-27-for-windows-x64/

**Comment by dizzzz** [comment]
the memory leak is not mentioned on http://wrapper.tanukisoftware.com/doc/english/release-notes.html .... i can ask the project, if i can find the reference....

**Comment by dizzzz** [comment]
when implementing... please keep compatible as the original wrapper; it is not really acceptable if the patched version would not run on my RHEL whilst the original does!

**Comment by adamretter** [comment]
@dizzzz I didn't previously update us to the patched version, I just built the patched version for a very specific need i.e. http://sourceforge.net/p/wrapper/mailman/message/33046914/. I was surprised when my patched version was added to eXist as it was without some testing on multiple platforms.

I performed the build on CentOS 7 which I guess has a newer glibc than your Centos/RHEL 6 platform. I am not sure how we can build one version which will be agnostic to the GLIBC version. Perhaps CentOS 7 has a backwards compatible package for libraries which use an older GLIBC version?

**Comment by dizzzz** [comment]
Hmmm I am pretty sure 'we' all agreed to have the patch included; yes if we can do things agnostic it would be great ~:-)

**Comment by joewiz** [comment]
As stated in the thread Adam linked to, Tanuki has fixed the glibc memory leak in the forthcoming version, 3.5.28: http://sourceforge.net/p/wrapper/code/1938/tree/trunk/wrapper/doc/revisions.txt (wrapper-cvs, revision 1938, dated November 4). It's not out yet (they said November, and it's now December), but this is promising!

**Comment by adamretter** [comment]
The latest version of Tanuki only fixes one of the leaks. The leak related to an older glibc version won't ever be fixed by them as I think they expect you to just update to a newer OS. There is also a small bug with their SYSTEMD script which I reported and will be fixed in the next subsequent release. When their next release appears my preference would be to just move eXist to that.

**Comment by joewiz** [comment]
The entry in the revisions.txt file I linked to suggested that 3.5.28 does work around the problem caused by older glibc:

> * Fix a memory leak on CentOS and Amazon Linux AMI. It happened when activating
>  log rolling in size mode. This memory leak comes from an issue in the GNU C 
>  Library (glibc) which was fixed on version 2.21. However, a workaround was 
>  added so that the Wrapper can run without problem on any version of glibc.

As I read this, this means no OS upgrade is necessary, right?

Thanks for your catch of the SYSTEMD script issue - that's awesome.

+1 to upgrading when 3.5.28 is released.

**Comment by adamretter** [comment]
Okay weird. The email I had from Tanuki said that only one of the memory leak issues that I had patches for was fixed. Perhaps the other has somehow gone away?

**Comment by adamretter** [comment]
No longer relevant as we have switched from Tanuki Java Server Wrapper to YAJSW here - https://github.com/eXist-db/exist/pull/1016

**Comment by joewiz** [comment]
Glad to leave this knotty problem behind! The old wrapper's darn memory leak caused me no end of grief.
