### ISSUE TITLE
Strange cardinality error when using field-index

### ISSUE THREAD

**Issue by trondaal** [eXist-db/exist#808]
When querying a collection after adding a combined/field index I ended up with the following error that puzzled me:

`exerr:ERROR XPTY0004: The actual cardinality for parameter 1 does not match the cardinality declared in the function's signature: 
range:field-eq($fields as xs:string+, $keys as xs:anyAtomicType*, ...) node()*. 
Expected cardinality: one or more, got 0. [source: String]`

This seems to be caused by the range:field functions not working according to the signature. Using an empty sequence as second parameter should be valid, but gives  a cardinality error on the first parameter...

Simply using any of the field-functions reproduces the error regardless if there is an index or not:

`range:field-eq('about-field', ())`

I am running 3.0RC1, but it seems this problems also appears in 2.2.

Trond Aalberg

**Comment by duncdrum** [comment]
@trondaal could you confirm if this is still an issue with a more recent version of exist, and update this ticket with some example code demonstrating the behaviour?

**Comment by duncdrum** [comment]
close due to inactivity, please open a new ticket with the requested information if the problem persists.
