### ISSUE TITLE
Modification times for existing resources will change on a failed parse attempt after uploading using XML-RPC

### ISSUE THREAD

**Issue by olvidalo** [eXist-db/exist#811]
While using eXist's XML-RPC API I encountered some strange behavior. When parsing an uploaded resource to overwrite an existing one, and parsing fails due to non-wellformed XHTML, the modification time of the old existing resource gets updated while its content does not get changed.

Is this intended behavior? Because it strikes me as a little unlogical and it makes it tricky for example to only upload locally changed files to eXist by checking the mtimes in the database without some workarounds.

This seems to be happening on 2.2 and also 3RC1.

**Comment by adamretter** [comment]
Nope that's not intended. Sounds like a bug
