### ISSUE TITLE
nested order by kills performance

### ISSUE THREAD

**Issue by wshager** [eXist-db/exist#839]
I have a data-intensive query that looks like this:

``` xquery
declare function local:get-subjects() {
    let $subjects := collection("/db/catalog/subject")/subject:subject
    return element root {
        for $sp in $subjects
        order by $sp/@name
            return
                for $sc in $sp/subject:subjects/subject:subject/@code return
                    lib:resolve-links-internal($sc,"has_title","from")
        }
};
```

The query causes CPU usage to go off the charts. When the order by clauses are removed, resource usage remains low.

**Comment by joewiz** [comment]
You said "nested" in your title. Is the nesting significant?

**Comment by wshager** [comment]
The impact of the single order by is there, but not as severe as having the second (nested) clause. Perhaps the nesting isn't significant, the second `order by` is.

**Comment by wshager** [comment]
This was discussed around September 28 on the exist mailing list.

**Comment by joewiz** [comment]
A link to the thread from exist-open.markmail.org would be useful for reference.

**Comment by wshager** [comment]
http://exist-open.markmail.org/thread/bghfqexokge6iyh3
http://exist-open.markmail.org/thread/kfrkkfao2xgbmyu5

**Comment by duncdrum** [comment]
there have been two fixes referenced here, if this is still a problem. Please open a new issue.
