### ISSUE TITLE
XQuery sometimes doesn't return any results

### ISSUE THREAD

**Issue by wshager** [eXist-db/exist#840]
This problem occurs sometimes after a batch insert of XML files using the ant task. The request remains empty, and the only thing that helps is a reindex of the collection.

The xquery typically is retrieved via REST. The problem exists in some versions after 2.2. I can't find anything in the logs are reproduce the issue.

**Comment by wshager** [comment]
I sent this in an email to the eXist mailing list (October 11 2015):

> After an automated sync with a remote instance using the
> Ant XMLDB tasks, an important collection can no longer be queried. It's
> quite hard to pinpoint when this exactly occurs, but it's fixed after a
> manual reindex.

@wolfgangmm replied (October 11 2015):

This would indicate an issue with the structural index, which is
strange because that code didn't change since 2.1 or so. However, I
saw a similar problem recently, but blamed it on the development
version I'm using, which has a lot of other modifications. I'm
somewhat able to reproduce it though and will have a closer look.
Maybe it's the same issue.

**Comment by wshager** [comment]
I changed the title, because the issue may also occur with fn:collection()

**Comment by wshager** [comment]
http://exist-open.markmail.org/thread/qnhuvqv2gtxnlzuk

**Comment by wshager** [comment]
The remarks in the email thread considering Windows or fn:doc can be ignored. The problem seems to be more structural.

**Comment by wshager** [comment]
@claudius108 suspected this was an issue for documents in the null namespace. I can confirm this. It isn't a Windows-specific issue AFAICT. I need to manually reindex documents that return empty results, inevitably leading to reindexing issues (#902).

**Comment by joewiz** [comment]
Four months since your initial report. Have you had any luck nailing down steps to reproduce the issue?

**Comment by wshager** [comment]
@joewiz How could I repoduce it?

**Comment by wolfgangmm** [comment]
Just to be sure, "null namespace" means: xmlns=""?

**Comment by wshager** [comment]
@wolfgangmm yes, any xml node without explicit xmlns declaration.

**Comment by wolfgangmm** [comment]
So it applies to any document which does not have a namespace set? Would it be possible to provide me a dump of one of your data sets via private email?

**Comment by wshager** [comment]
@wolfgangmm sure. I usually don't set namespaces on HTML documents/fragments, for example.

**Comment by wshager** [comment]
@wolfgangmm I have a problem with triggers not starting at db launch, which may indicate that XML within an XMLNS may appear empty too. I can't imagine that I'm the only user that experiences this. Perhaps it's caused by some configuration problem, but I only slightly divert from the default setup.

**Comment by wshager** [comment]
Again, an empty document encountered, just a simple config file that wasn't returned. Storing it again solved the issue...

```XML
<configuration>
    <content-domain>cms.benjamins.com</content-domain>
</configuration>
```

**Comment by wolfgangmm** [comment]
Since I have no idea how to reproduce this, the only option would be to get my hands on a binary dump. So next time the issue happens, could you tar up your data directory (with eXist stopped) and put it somewhere, along with a description of how the issue can be seen?

Unfortunately none of the apps we're actively working on does show similar issues.

**Comment by joewiz** [comment]
@wshager Please reopen if you are still encountering the issue and are able to provide a reproducible test.
