### ISSUE TITLE
Trailing slash shows xql source

### ISSUE THREAD

**Issue by meshkin** [eXist-db/exist#842]
Hi all;
The security bugs of jetty are listed there: http://www.eclipse.org/jetty/documentation/current/security-reports.html
One of them is "Trailing slash shows JSP source"; that unfortunately there is same bug for xql files, too.
How can I fix this bug or neutralize it in eXist-db.
Or How can I update jetty to new version of it, because jetty version in eXist2.2 is very old!?
Thanks

**Comment by adamretter** [comment]
@meshkin The version of Jetty we are using is not "very old", eXist HEAD is on Jetty `8.1.17.v20150415` which is the latest version of Jetty in the 8 series. If you are looking for a newer version of eXist then I would suggest eXist 3.0-RC1 or just taking a nightly build which will have the latest.

The reason we have not moved to Jetty 9 is that it requires both code and config changes as Jetty's API has changed, so it is a non-trivial change. This work requires investment by a developer, and as open source contributors we are all contributing our own time and have our own priorities.

I have looked at this myself, however I would rather invest my time (if I had any) to migrate eXist away from Servlets to an Asynchronous HTTP stack like Spray, Akka Http or even Netty.

If you wish to update eXist for Jetty 9, then you are free to send us a pull-request and we would be happy to review it and most likely accept it.

**Comment by meshkin** [comment]
When the eXist-db 2.2 released, I downloaded, installed and using it. my logs are similar this:
30 Nov 2015 16:54:14,663 [main] INFO  (JettyStart.java [run]:122) - Running with Java 1.8.0_65 [Oracle Corporation (OpenJDK 64-Bit Server VM) in /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.65-3.b17.fc22.x86_64/jre] 
30 Nov 2015 16:54:14,678 [main] INFO  (JettyStart.java [run]:131) - [eXist Version : 2.2] 
30 Nov 2015 16:54:14,679 [main] INFO  (JettyStart.java [run]:133) - [eXist Build : 20151101] 
30 Nov 2015 16:54:14,680 [main] INFO  (JettyStart.java [run]:137) - [Git commmit : ${git.commit}] 
30 Nov 2015 16:54:14,680 [main] INFO  (JettyStart.java [run]:140) - [Operating System : Linux 4.2.6-200.fc22.x86_64 amd64] 
30 Nov 2015 16:54:14,682 [main] INFO  (JettyStart.java [run]:145) - [jetty.home : /usr/local/eXist/tools/jetty] 
30 Nov 2015 16:54:14,682 [main] INFO  (JettyStart.java [run]:147) - [log4j.configuration : file:/usr/local/eXist/log4j.xml]
30 Nov 2015 16:54:21,428 [main] INFO  (Server.java [doStart]:270) - jetty-8.1.9.v20130131 
the jetty version in 2.2 is jetty-8.1.9.v20130131 and I have wondered when you said "8.1.17.v20150415".
do you recommend to me that clone the exist-db is github and use it as server? is it stable version?
Thanks

**Comment by adamretter** [comment]
@meshkin HEAD of GitHub `develop` branch of 3.0-RC1 are currently stable.

**Comment by meshkin** [comment]
In download part of eXist-db site, for Version 3.0 RC1, is written : "not recommended for production"!
Do I download from that or clone from github?

**Comment by adamretter** [comment]
I would suggest cloning from GitHub or taking a nightly build from http://static.adamretter.org.uk/exist-nightly/

I am led to believe that there should be an eXist 3.0-RC2 appearing around the end of December...

**Comment by adamretter** [comment]
I am closing this as eXist-db 3.5.0 is available, and that includes Jetty 9. Also 3.6.0 released tomorrow will have the latest Jetty 9.
