### ISSUE TITLE
Incomplete regex character class with XQuery analyze-string()

### ISSUE THREAD

**Issue by ptrckb** [eXist-db/exist#846]
It seems that the shorthand character class '\w' does not include some (any?) accented letter in patterns for `analyze-string()`.

For example:

``` xquery
analyze-string('é', '\w')
```

return:

``` xml
<fn:analyze-string-result xmlns:fn="http://www.w3.org/2005/xpath-functions">
<fn:non-match>é</fn:non-match>
</fn:analyze-string-result>
```

Still the same shorthand character class does include them in patterns for `matches()`.

``` xquery
matches('é', '\w')        
```

return

``` xquery
true
```

Tested with 2.2 and develop (395c00091059929adcef6f537c662e60f0a4e3a8)

**Comment by dizzzz** [comment]
I might be wrong but the xpath regexp is different from the Java one. Maybe the wrong pattern || engine is used here....

**Comment by joewiz** [comment]
@ptrckb Somewhere between 2015 and today (i.e., eXist 5.3.0-SNAPSHOT develop branch), eXist began to return the correct results from `fn:analyze-string`:

```xml
<fn:analyze-string-result xmlns:fn="http://www.w3.org/2005/xpath-functions">
    <fn:match>é</fn:match>
</fn:analyze-string-result>
```

So, happily, this issue can be closed!
