### ISSUE TITLE
NativeTextEngine has illegal contains calls

### ISSUE THREAD

**Issue by alebastrov** [eXist-db/exist#854]
stoplist.contains(token)
where TreeSet<String> stoplist = new TreeSet<String>();
but token is TextToken

contains in TreeSet is based on equality checking (o.equals(e))
but String NEVER equals to non-string classes,
so this would never contain

I suggest to check if it needs, it should be rewritten like
stoplist.contains(token.getText())

**Comment by adamretter** [comment]
NativeTextEngine was removed from eXist when the legacy Full-text index was removed.
