### ISSUE TITLE
Collection.getDocument() method holds the lock too long time

### ISSUE THREAD

**Issue by alebastrov** [eXist-db/exist#856]
It uses schema:
- acquire lock
- get document
- check permissions
- release lock

It could be more effectively, if it uses
- acquire lock
- get document
- release lock
- check permissions

```
public DocumentImpl getDocument(final DBBroker broker, final XmldbURI path) throws PermissionDeniedException {
        DocumentImpl doc = null;
        try {
            getLock().acquire(Lock.READ_LOCK);
            doc = documents.get(path.getRawCollectionPath());
        }
        catch(final LockException e) {
            LOG.error("Could not get lock", e);
            return null;
        }
        finally {
            getLock().release(Lock.READ_LOCK);
        }
        if (doc == null) {
            LOG.debug("Document " + path + " not found!");
            return null;
        }
        if(!doc.getPermissions().validate(broker.getSubject(), Permission.READ)) {
            throw new PermissionDeniedException("Permission denied to read document: " + path.toString());
        }
        return doc;
    }
```

**Comment by adamretter** [comment]
@alebastrov If we released the lock early as you suggest then we would have a concurrency issue between a document and its permissions where the two may no longer be in sync

**Comment by alebastrov** [comment]
No
Because when we write document/collection/permission we are holding lock all the time, so just after got read document, no matter how permission changed, because we do not see changes anyway

**Comment by alebastrov** [comment]
Maybe it will be clearer, if we draw schema:
T1 --WRITE-LOCK----WRITE_DOC-----CHANGE-PERMS----RELEASE-LOCK----
T2 -------READ-LOCK(WAITS)----------------------------------------------------------------GOT_LOCK---...---

where ... is reading collection/doc, checking permission, etc

**Comment by alebastrov** [comment]
so if we got read lock - it means there were writing successfully

**Comment by alebastrov** [comment]
Other situation is:

T1 --READ_LOCK-----GOT_DOC----RELEASE_LOCK--------CHECK_PERMS-----
T2 --------WRITE_LOCK(WAITS)---------------------------GOT_LOCK----WRITE_DOC---....-RELEASE_LOCK

**Comment by alebastrov** [comment]
I believe that permissions get read when document read, so whenever you place the checking, permissions would not be changed at all, so it might be checked after lock releasing

**Comment by alebastrov** [comment]
There is nobody who take care about this in 3.2.0?

**Comment by dizzzz** [comment]
Well @adamretter raised concerns, I'd take his remark seriously.

**Comment by alebastrov** [comment]
I explained why it can be faster and there is no concern about issue. Take a look at 
 alebastrov commented on Dec 11, 2015

**Comment by adamretter** [comment]
@alebastrov This is being taken very seriously, however at the moment I am working hard on rewriting eXist's locking of Documents and Collections completely. That should close this issue but it takes a  different approach

**Comment by dizzzz** [comment]
@alebastrov we take issues seriously... but it is all about priority, a bit about opinions and often about having time available....

**Comment by duncdrum** [comment]
@adamretter good to close?

**Comment by adamretter** [comment]
I think this is likely addressed now.
