### ISSUE TITLE
Collection class has several different schemes for lock and job

### ISSUE THREAD

**Issue by alebastrov** [eXist-db/exist#858]
It should be identical for all methods
- acquire lock
- db.getProcessMonitor().startJob(...);
- db.getProcessMonitor().endJob(...);
- release lock

or
- db.getProcessMonitor().startJob(...);
- acquire lock
- release lock
- db.getProcessMonitor().endJob(...);

In fact there are several ways to do that

**Comment by adamretter** [comment]
These will be closed soon by Evolved Binary's Locking and Cache improvements.

**Comment by adamretter** [comment]
Evolved Binary's Locking and Cache improvements were merged to `develop` so this can be closed.
