### ISSUE TITLE
Some functions in the XSLT module are unimplemented

### ISSUE THREAD

**Issue by amclark42** [eXist-db/exist#874]
Some functions in the XSLT module return the message "Method not implemented". The functions still show up in the XQuery Function Docs, because they have some documentation, but there is no code implementing those functions.

Functions in question: `xsl:unparsed-text`, `xsl:unparsed-text-available`, `xsl:unparsed-entity-uri`, `xsl:unparsed-entity-public-id`.

I'm using eXist 2.2. I'm not bothered by the fact that the functions don't work - there were other ways to accomplish what I needed. Mostly I was confused that these apparently-available functions didn't work **because** I knew the functions from writing XSLT.

**Comment by adamretter** [comment]
@amclark42 An implementation of XSLT for eXist was started some years ago by @shabanovd but it was never finished. I think it is abandonware now, @shabanovd should we remove it?

**Comment by dizzzz** [comment]
Yeas, we should at least consider it.... @wolfgangmm, @ljo  ?

**Comment by dizzzz** [comment]
Well there are two aspects: (1) the 'native' XSLT engine and (2) the XSL functions @amclark42 refers to.

**Comment by adamretter** [comment]
@dizzzz Both of those things are part of the same "native" XSLT engine, no?

**Comment by dizzzz** [comment]
Looks like, But I think the functions could be split off

**Comment by adamretter** [comment]
@dizzzz Okay, but what would be the benefit of that?

**Comment by dizzzz** [comment]
note sure yet :-)

I can imagine there are a few functions in the xsl: function namespace that are in that namespace exclusive only which provide nice functionality. I can also imagine that really require XSL domain things making them useless in xquery.

**Comment by adamretter** [comment]
@dizzzz Hopefully as of XPath 3.1, there are no functions in the XSL namespace that are useful in XQuery. Some effort was undertaken by the WG to ensure that any useful common functions were promoted from XQuery or XSL into XPath.

**Comment by dizzzz** [comment]
@adamretter ok that makes sense :-)

**Comment by joewiz** [comment]
I think this report of what XQuery 3.1 functions eXist has and lacks is still basically up to date: https://gist.github.com/joewiz/acb0558f078c0576a5e7#file-exist-xpath-functions_results-xml-L10

**Comment by adamretter** [comment]
@joewiz You might want to re-run your comparison after https://github.com/eXist-db/exist/pull/879 is merged.

**Comment by joewiz** [comment]
As a preview, here's what eXist registers as available using your map-improvements branch:

```
<module>
    <namespace-uri>http://www.w3.org/2005/xpath-functions/map</namespace-uri>
    <function>map:contains</function>
    <function>map:entry</function>
    <function>map:for-each</function>
    <function>map:for-each-entry</function>
    <function>map:get</function>
    <function>map:keys</function>
    <function>map:merge</function>
    <function>map:new</function>
    <function>map:put</function>
    <function>map:remove</function>
    <function>map:size</function>
</module>
```

Thanks so much for getting these into place, not to mention adding support for the older deprecated functions. I should look to see whether the util functions for probing modules & function signatures can tell us which functions are deprecated, to be able to add that distinction to scripts like mine.

**Comment by joewiz** [comment]
So, 18 months later, the XSLT module is even more clearly abandoned. +1 to removing it. Would removing it have to come with 4.0.0? If so, I propose that we change the issue title to "Remove incomplete, abandoned XSLT module" and tag this issue with 4.0.0.

**Comment by joewiz** [comment]
And perhaps we should label the module as deprecated in the next 3.x release.

**Comment by adamretter** [comment]
@joewiz I agree this should be removed, and yes it should be 4.0.0

**Comment by adamretter** [comment]
I believe this has already been removed.
