### ISSUE TITLE
login problem with 3.0RC2

### ISSUE THREAD

**Issue by pherk** [eXist-db/exist#875]
I did clean build of today's develop branch (RC2 2016-01-07)
the JNDI error (class not found, see issue#844) pops up, despite this the server starts
... but I cannot login via dashboard (admin, guest passswords should be blank after clean build)
exist log shows:
2016-01-07 09:16:49,733 [eXistThread-26] WARN (ServletHandler.java [doHandle]:538) -
javax.servlet.ServletException: An error occurred while processing request to /exist/apps/dashboard/plugins/userManager/api/user/: exerr:ERROR You must be an authenticated user [at line 44, column 17, source: /db/apps/dashboard/plugins/userManager/userManager.xqm]

... restoring a existdb2.2master backup completes (after build.sh clean-default-data-dir),
    eXide allowed to repair packages
    but the login problem persists
... oddly, after refreshing the webpage the login top left is showing admin, but all further actions on
    dashboard fail

**Comment by dizzzz** [comment]
"fail" ... how does this reflect? messages in exist.log?

**Comment by pherk** [comment]
user not authenticated (errors in exist.log)

**Comment by dizzzz** [comment]
it must be something local; can you login into a completely empty database?
if not: then it is something local to your system/configuration

please provide details like OS/java version/browser etc.

**Comment by dizzzz** [comment]
do you have privacy blockers installed in your browser? noscript? please switch off...

**Comment by pherk** [comment]
I have no blockers. Meanwhile I had another try. 
Ubuntu 14.04LTS, Oracle Java1.8_66, FF 43.0
my steps/observations:
fresh dir, fresh git clone of develop branch, no changes, browser cache cleared
build.sh (no errors, eXist 3.0.RC2 build)
servers started with startup.sh, banner shows eXist 3.0.RC1 !?
- JNDI not found
admin with blank password -> login error
refresh of dashboard website -> admin logged in
- click on usermanager, pops up and gives "Es ist ein Fehler aufgetreten" (exist.log: see first message
  above, no other errors)
- shutdown is ok
- package manager shows packages
- collection browser shows apps dir but not system dir (auth error)
- the logged in status is lost after auth error or after switching the browser tab
I hope it helps
Peter

**Comment by dizzzz** [comment]
I have no idea.... what does `git status` show? did you update conf.xml(.tmp)? did you run `build.sh rebuild` ?

**Comment by wolfgangmm** [comment]
I just fixed the error you always get on develop if you first log into the dashboard. Please try version 0.4.5 of the dashboard available from the public repo. 

I don't know if this will also help on the other issues reported (user manager), which might have other causes.

**Comment by pherk** [comment]
AFAICS the login problem is resolved.
many thanks
Peter

> I just fixed the error you always get on develop if you first log  
> into the dashboard. Please try version 0.4.5 of the dashboard  
> available from the public repo.
>
> I don't know if this will also help on the other issues reported  
> (user manager), which might have other causes.
>

**Comment by dizzzz** [comment]
good to hear!
