### ISSUE TITLE
XQuery fails to compile try-catch under certain circumstances

### ISSUE THREAD

**Issue by median1st** [eXist-db/exist#880]
I've encountered a possible bug in XQuery parser in eXist 3.0 RC1 while evaluating the database. The try-catch parses and works correctly when used as this (XQuery 3.0):

    <dates>
    {  
        let $coll := collection('/db/ray')
        for $i in $coll//item[datace]
        where (string-length($i/datace) gt 0)
        return try {
            xs:integer($i/datace)
        }
        catch err:FORG0001 {
            <error>
            {
                $i/id_abs,
                $i/datace
            }
            </error>
        }
    }
    </dates>

Evaluating simple XQuery with try-catch, like `try { xs:integer('abc') } catch err:FORG0001 { 0 }` works well, but the following function does not compile:

    declare function ran:in-range($what as node()?, $q as xs:integer) as xs:boolean
    {
        try
        {
            (($what/range) and
                not(empty(
                    filter($what/range, function($n){ (xs:integer($n/@start) le $q) and (xs:integer($n/@end) ge $q)})
                    )
                )
            )
            or
            ( ($what/enum)  and
                not(empty(
                        filter($what/enum/eni, function($n){ xs:integer($n/@value) = $q })
                    )
                )
            )
            or 
            (matches($what/text(),'^[0-9]+$') and (xs:integer($what/text()) = $q ))
        }
        catch err:FORG0001
        {
            false
        }
    };

The function is declared within a module. The eXide does not complain about any syntax errors when editing and/or saving the module, but once the module is imported, the following error shows up immediately:
`error found while loading module ran: Error while loading module /db/ray/scripts/ranges.xq: error found while loading module from /db/ray/scripts/ranges.xq: <AST>:0:0: unexpected end of subtree`
As soon as the try-catch construct is removed from the source code, the module compiles and imports flawlessly. 
Please don't hesitate to contact me back if I could be of any help in diagnosing the issue.

**Comment by joewiz** [comment]
1. Could you reduce this report to a set of steps we can follow to reproduce your results (without your data or other application fragments)?

2. Could you confirm whether the contents of the `catch` clause of your 2nd sample code snippet are correct? It says `false` - which I imagine is a typo and should be `false()`.

**Comment by median1st** [comment]
Hello Joe,

Thanks for your reply and the hint with the typo - indeed, this was my error
(false instead of false() in the catch block) and it was also the cause of 
the error message. Once corrected to false(), the funciton behaves as 
expected. 
A question remains whether a bit more explicative error message would be 
helpful here. I guess such typo could possibly happen frequently to those 
who have to switch among several different programming languages in a single
project (like me now).
The behavior could be reproduced always:
1. Open a new XQuery in eXide
2. Write a simple try-catch expression - the content of the "try" block does
not matter here, just put 1 
3. Use any bareword in the catch for a specific error (like err:FORG0001) 
block, e.g.  "false" (no quotation marks). Your query then: try { 1 } catch 
* { false }
4. Run the query. This results in "Cannot compile xquery: exerr:ERROR <AST>:
0:0: unexpected end of subtree"

The behavior is similar when the bareword is used in the "try" block with a 
correct "catch" block:
1. Write a simple try-catch expression in XQuery in eXide
2. Use a bareword in the try block and provide a correct catch block for 
err:FORG0001, for example:
    try {  false } catch err:FORG0001 { 1 }
3. Run the query. This results in "exerr:ERROR Error."

It's really only a minor issue, but a bit more specific error messages here 
would help you to avoid nitpickers like me filing in issue reports ;-)

Regards,
Rene



---------- Původní zpráva ----------
Od: Joe Wicentowski <notifications@github.com>
Komu: eXist-db/exist <exist@noreply.github.com>
Datum: 11. 1. 2016 19:19:21
Předmět: Re: [exist] XQuery fails to compile try-catch under certain 
circumstances (#880)

"

   1. 
   Could you reduce this report to a set of steps we can follow to reproduce
   your results (without your data or other application fragments)?
   2. 
   Could you confirm whether the contents of the catch clause of your 2nd 
   sample code snippet are correct? It says false - which I imagine is a 
   typo and should be false().
   

—
Reply to this email directly or view it on GitHub
(https://github.com/eXist-db/exist/issues/880#issuecomment-170639911). 





"=

**Comment by joewiz** [comment]
Hi Rene - Great, I'm glad this helped overcome the error, and thanks for following up.  I agree that this is a really terrible error message, and one I've never encountered before.  I would have expected an error like what you get if you enter `false` into a new XQuery tab in eXide:

    err:XPDY0002 Undefined context sequence for 'child::{}false' [at line 3, column 1, source: String]

The hint here, reinforced by syntax highlighting of `false` as if it were an XML element name in a path expression but, admittedly, not crystal clear, is that eXist assumes that `false` is part of a path expression. But without context like `/false` or `collection('/db/apps/my_app/data')/false`, eXist has to throw an error: "false relative to *what*?".  

Given that you've now overcome the original issue as stated, I'd suggest that you close this issue, and open a new one (I'd be happy to do so if this is a pain for you) which reports the problem with the error message in the query `try { 1 } catch * { false }`.

**Comment by median1st** [comment]
Not a bug.
Closing as suggested.
