### ISSUE TITLE
Collection.java has invalid equality checking

### ISSUE THREAD

**Issue by alebastrov** [eXist-db/exist#881]
class Account cannot be equal to class Subject. (line 1800)
```
final Account lockUser = oldDoc.getUserLock();
            if(lockUser != null && !lockUser.equals(broker.getCurrentSubject())) {
                throw new PermissionDeniedException("The document is locked by user '" + lockUser.getName() + "'.");
            }
```
:+1:  There should be getName() or getId() calls for checking
```
...
if(lockUser != null && !lockUser.getName().equals(broker.getCurrentSubject().getName())) {
...
```

**Comment by adamretter** [comment]
@alebastrov `lockUser.equals` calls `AbstractAccount.equals` which looks okay to me, what do you think is wrong there?

**Comment by alebastrov** [comment]
```
public interface Account extends Principal, User
public interface Subject extends Account
```
:-1: There are 2 different classes (A extends B i.e. Subject extends Account). There is no any valid way to check equality of them, see J.Bloch book (Effective Java)

**Comment by adamretter** [comment]
@alebastrov Can you be more specific? Which page in the book?

**Comment by alebastrov** [comment]
Part: Methods Common to All Objects.
Item 8: Obey the general contract when overriding equals

• Symmetric: For any non-null reference values x and y, x.equals(y) must re-
turn true if and only if y.equals(x) returns true.

In this case we have an error, because A equals B but B not equals A if B extends A
