### ISSUE TITLE
Implement Text serialization

### ISSUE THREAD

**Issue by gspringtech** [eXist-db/exist#888]
It would be greatly appreciated if Text serialization could be added as per the XQuery Serialization specification.

http://www.w3.org/TR/xslt-xquery-serialization-31/#text-output

In particular, the output:item-separator should be supported.

**Comment by joewiz** [comment]
From @gspringtech's original post to exist-open (http://markmail.org/message/khfsbkb4s4syuz5n), here is some sample code that might be of use for testing:

```xquery
xquery version "3.0";

declare namespace output  = "http://www.w3.org/2010/xslt-xquery-serialization";
declare option output:method "text";
declare option output:item-separator "-";

("abc","123")
```

@gspringtech wrote:

> In Saxon 9.x the output is "abc-123" while eXist produces the sequence of two strings.
> 
> Currently I'm writing very unpleasant string-joins to achieve a CSV output - text serialisation would do it easily.

@adamretter responded:

> Open an issue with a feature request and I will implement it, as it is a trivial change...

**Comment by adamretter** [comment]
@joewiz @gspringtech So I did spend some time looking into this previously. Unfortunately eXist's serializers are a bit crufty and fixing the `item-separator` was not as simple as I had envisaged.

**Comment by joewiz** [comment]
@adamretter I see, thanks for looking into it!

**Comment by joewiz** [comment]
Superseded by #1483.
