### ISSUE TITLE
xmlrpc shows paths as base64 java-object

### ISSUE THREAD

**Issue by markov2** [eXist-db/exist#894]
Running 3.0RC1 XMLRPC, some calls not return "serializable" paths, in stead of strings in previous releases.  For instance, /db/rO0ABXNyABhvcmcuZXhpc3QueG1sZGIuWG1sZGJVUkltDg3x/lYKSgIAAloADmhhZFhtbGRiUHJlZml4TAAVZW5jb2RlZENvbGxlY3Rpb25QYXRodAASTGphdmEvbGFuZy9TdHJpbmc7eHABdAAEYXBwcw==

The returned is a java serialized object, where the documentation and previous release say that
it is a simple string.  An org.exist.xmldb.XmldbURI object.  I have seen this with listCollectionPermissions but probably on other spots as well.

**Comment by line-o** [comment]
@markov2 Can you provide an example call?

**Comment by duncdrum** [comment]
`3.0RC1` is long dead, both Java and exist have moved on, if there is still a problem with recent versions of exist and java please open a new issue, with steps to reproduce.
