### ISSUE TITLE
Unable to select nodes after rename

### ISSUE THREAD

**Issue by median1st** [eXist-db/exist#898]
When elements whose names consist of mixed case letters are renamed to lowercase equivalents, the XPath expression is unable to find them under the new names, e.g. renaming &lt;Level&gt; to &lt;level&gt; causes the newly named element to be unaddressable. Exist version 3.0 RC1.
Steps to reproduce:
1. Create an empty collection.
2. Upload a simple XML file, containing four elements under its root, each containing two elements with textual content. Name the root element all lowercase, the 1st level elements all uppercase, the first of the 2nd level elements all uppercase, and the second using different mixed case for each (e.g. Level, LEVEL, lEVEL and level). An example file is attached: [diag.zip](https://github.com/eXist-db/exist/files/99065/diag.zip). The example XPath expressions below assume that the root is named `root`, the 1st level subelements are named `ELEM` and the 2nd level elements are named `ID`, `Level`, `LEVEL`, `lEVEL` and `level`, respectively.
3. Verify that all the elements are accessible using XPath:
    - `collection(...)/root/ELEM` should return 4 results as well as `collection(...)/root/ELEM[ID]`
    - `collection(...)/root/*[Level]`, `collection(...)/root/*[LEVEL]`, `collection(...)/root/*[lEVEL]` and `collection(...)/root/*[level]` should return a single result each
4. Rename all the elements so that their names result in all lowercase:
`for $i in collection(...)/root//* let $newname := lower-case(name($i)) return update rename $i as $newname`
5. Open the XML file in the Admin Client to verify that all element names are lowercase.
6. Query the database for all `elem` elements containing `level` element (`collection(...)/root/elem[level]`) - this should return four elements, but only the single element whose `level` element was originally named in lowercase, is returned. 
7. Only the `level` elements that were named lowercase in the original file are visible to the XPath expression - this can be verified by collection(...)/root/elem[$n]/level. When the $n equals the position of the element whose `level` element was lowercase in the original file, the expression returns the correct result, but it returns empty sequence for all remaining cases.

**Comment by jensopetersen** [comment]
I don't know what `collection(...)` is supposed to do, but I get all 4 elements in 6.

I do `for $i in //root//* let $newname := lower-case(name($i)) return update rename $i as $newname` and then run `//root/elem[level]` and get 4 `<elem>`.

**Comment by dizzzz** [comment]
I agree with @jensopetersen , please provide more concrete details e.g. about 'collection(...)', since details might count.

**Comment by median1st** [comment]
Gentlemen,

The ellipsis in collection(...) is no magic. It is just a placeholder, 
because I did not know in advance how you named your diagnostic collection. 
So for example, if you named your collection '/db/diag', then collection(...
) became collection('/db/diag').

The described behavior repeated once again just few minutes ago - I've 
imported an XML export from MS Access containing the mixed-case named 
elements, renamed all to lowercase and again, the mixed-case names could not
be found. When I export the renamed document, delete it from the collection 
and then upload the exported contents back, it works as expected. So I 
suppose this might have something in common with the structural indices that
eXist-db creates for the collection.

Just for sake of clarity - I'm using the officially provided eXist-db 3.0 RC
1 in the default build (exist.war) on a Tomcat 8.0.24 server with no 
optional modules, no nightly builds, no patches etc. And I'm using eXide for
all the work except uploads and exports of the documents. The collection is 
a newly created one with no collection.xconf, just defaults.
These are the steps that lead to the error:
1. Create collection /db/diag
2. Upload the diag.xml file to the collection
3. Rename all the elements to lowercase: for $i in collection('/db/diag')/
root//* return update rename $i as lower-case(name($i))
4. Try to find all the elements using XPath collection('/db/diag')/root/*
[level] - on my installation this returns only the elem whose level='5', the
one that was originally lower-case in the uploaded file. No others are 
returned.

I can repeat this error anytime. If you needed screenshots of the actions 
and results, I can record and provide them.


---------- Původní zpráva ----------
Od: Dannes Wessels <notifications@github.com>
Komu: eXist-db/exist <exist@noreply.github.com>
Datum: 21. 1. 2016 15:27:51
Předmět: Re: [exist] Unable to select nodes after rename (#898)

"

I agree with @jensopetersen(https://github.com/jensopetersen) , please 
provide more concrete details e.g. about 'collection(...)', since details 
might count.

—
Reply to this email directly or view it on GitHub
(https://github.com/eXist-db/exist/issues/898#issuecomment-173584577). 





"=

**Comment by jensopetersen** [comment]
I have tried with a fresh install of eXist-db-3.0.RC1 and I still get 4 items returned. 

I see your point about the structural index, but I can't see anything wrong here. I don't use Tomcat and run this on Mac OS X, but I don't think this should make any difference.

**Comment by median1st** [comment]
I agree that the OS and web container should not make difference in this 
case. 
I've tried a fresh deploy of the same exist.war to a different server (both 
SW and HW) and to repeat the steps and this time the query behaved 
correctly. The only difference between the faulty db and the fresh install 
is the data within. I've left the freshly installed one empty and it behaves
correctly. The faulty one maintains another collection containing two files 
of which one has about 1.7GB and the other about 60MB. This collection is 
indexed using lucene and new range indices (data + indices = 19GB total). 
I cannot perform it right now due to the space limitations on the other 
virtual server, but I'll try to feed the fresh install with the same data 
that is maintained by the faulty instance and repeat the diagnostic 
experiment and let you know the results.


---------- Původní zpráva ----------
Od: Jens Østergaard Petersen <notifications@github.com>
Komu: eXist-db/exist <exist@noreply.github.com>
Datum: 22. 1. 2016 12:14:06
Předmět: Re: [exist] Unable to select nodes after rename (#898)

"

I have tried with a fresh install of eXist-db-3.0.RC1 and I still get 4 
items returned. 

I see your point about the structural index, but I can't see anything wrong 
here. I don't use Tomcat and run this on Mac OS X, but I don't think this 
should make any difference.

—
Reply to this email directly or view it on GitHub
(https://github.com/eXist-db/exist/issues/898#issuecomment-173884374). 





"=

**Comment by dizzzz** [comment]
>> This collection is
indexed using lucene and new range indices (data + indices = 19GB total).

please provide index config details too when you find query issues

**Comment by median1st** [comment]
The collection has no index config at all. The lucene and new range indices are used in a different collection.

**Comment by median1st** [comment]
Update: it seems that the failing database instance has a corrupted index due to previous lack of disk space. When backed up and restored to a different instance with all the pertinent data and indices the error occurs no more. Closing the issue.
