### ISSUE TITLE
file:serialize prepends content to file

### ISSUE THREAD

**Issue by wshager** [eXist-db/exist#906]
In current develop file:serialize inserts the serialized content into file. Is this the expected behavior or a bug?

**Comment by joewiz** [comment]
> inserts the serialized content into file

... as opposed to?

**Comment by wshager** [comment]
@joewiz replacing the content, obviously.

**Comment by joewiz** [comment]
Have you read the docs on `file:serialize()`?

http://exist-db.org/exist/apps/fundocs/view.html?uri=http://exist-db.org/xquery/file#serialize.3

See especially the variant with the `$append` parameter.

**Comment by wshager** [comment]
I would expect file:serialize#3 to replace the entire file, not prepend the content. I didn't mention appending.

**Comment by joewiz** [comment]
Ah, thanks for clarifying. I can confirm your issue. Test to reproduce:

```xquery
file:serialize(<an-unassuming-node/>, 'file:/Users/joe/Downloads/test-serialize.xml', "method=xml"),
file:serialize(<poof/>, 'file:/Users/joe/Downloads/test-serialize.xml', "method=xml")
```

Expected result:

```
<poof/>
```

Actual result:

```
<poof/>ssuming-node/>
```

I'd suggest
