### ISSUE TITLE
Rounding error xs:double math

### ISSUE THREAD

**Issue by wshager** [eXist-db/exist#921]
```xquery
function ($a as xs:double,$b as xs:double){
    $a - $b
}(2.10, 0.01)
```
yields 2.0900000000000003

There's more but I'm leaving for holidays so no time to investigate now.

**Comment by wshager** [comment]
`number(xs:double(2.1) - .01)` yields 2.0900000000000003
`number(xs:float(2.1) - .01)` yields 2.0899999141693115

**Comment by opax** [comment]
That is not a bug. xs:double is assumed to be IEEE 754 double (64bit), which yields a precision of 15 to 16 decimal digits. A xs:float is assumed to be a IEEE 754 single precision float (32bit), with a precision of between 7 and 8 decimal digits. If you look at your examples, you will see that this is exactly the precision you get.

You can try the same calculations in any other programming language with these datatypes, the results will be the same.

**Comment by dizzzz** [comment]
@opax thx for referring to the IEEE specs; did not find the time yet.

**Comment by wshager** [comment]
The double - double is correct, the float - double is not, unless I'm missing something.
```c
#include "stdio.h"

int main(void) {
    float x = 2.1;
    double y = 0.01;
    printf("%.17g",(double) x - y);
    return 0;
}
```
yields 2.0899999046325686

**Comment by wshager** [comment]
```javascript
Number(Math.fround(2.1) -.01)
```

yields 2.0899999046325686

**Comment by wshager** [comment]
Finally, this is incorrect:

```xquery
2.1 - .01
```

yields 2.09

**Comment by wshager** [comment]
Ah, so the default floating point number is xs:float, that changes things...

**Comment by opax** [comment]
Your example:

 #include "stdio.h"

> int main(void) {
>     float x = 2.1;
>     double y = 0.01;
>     printf("%.17g",(double) x - y);
>     return 0;
> }

is also correct, because the 2.1 stored in a float is of course only an approximation, i.e. it is within a precision of 8 decimal digits approximately 2.1. If you convert it to a double afterwards, it cannot be more precise than before. For reference, `(float) 2.1` has the value `2.099999904632568359375`

**Comment by wshager** [comment]
No it's xs:decimal, of course.

**Comment by opax** [comment]
And that is why 2.1 - 0.01 is 2.09.

**Comment by opax** [comment]
So I guess the issue may be closed?

**Comment by wshager** [comment]
What the hell is a decimal?

**Comment by opax** [comment]
A number that is not stored in binary but in decimal format, hence no rounding errors when using decimal literals.

**Comment by wshager** [comment]
@opax isn't that called a fixed-point? Java doesn't have that, right?

**Comment by opax** [comment]
BigDecimal.

**Comment by shabanovd** [comment]
note: `fn:number() as xs:double`

**Comment by wshager** [comment]
Ok, so to conclude, 

```xquery
xs:float(2.1) - xs:decimal(.01)
```

How does that work?

**Comment by wshager** [comment]
float - decimal yields a float, which is rounded. That probably explains the source of my confusion. It's a mad world...

**Comment by shabanovd** [comment]
@wshager you are right https://www.w3.org/TR/xpath-31/#mapping

**Comment by wshager** [comment]
@shabanovd about what exactly?

I'm reopening the issue, because the resulting float should not be rounded IMO.

**Comment by wshager** [comment]
Or should it?

"Numeric type promotion:
...
A value of type xs:decimal (or any type derived by restriction from xs:decimal) can be promoted to either of the types xs:float or xs:double. The result of this promotion is created by casting the original value to the required type. This kind of promotion may cause loss of precision."

https://www.w3.org/TR/xpath-31/#dt-type-promotion

**Comment by wshager** [comment]
Aargh...

**Comment by wshager** [comment]
Hah!

`xs:float(4.1) - xs:float(0.01)`

**Comment by wshager** [comment]
I guess it all depends on how the float is rounded. I use eXide to run the scripts, so I think the rounding may occur anywhere on the server or the client.

**Comment by dizzzz** [comment]
Always verify with Saxon if an xquery bug is suspected:
`xs:float(4.1) - xs:float(0.01)` = 4.0899997
`number(xs:float(2.1) - .01)` = 2.0899999141693115
`2.0900000000000003` = xs:double(2.1) - .01
