### ISSUE TITLE
Issue with attributes

### ISSUE THREAD

**Issue by windauer** [eXist-db/exist#923]
Following query return also TEI:blibl elements with types different to linguistic (e.g. 'auxiliary')

``` xquery
collection('/db/apps/lgpn-data/data/ling/names')//TEI:orth[.='Agathōnymos']/ancestor::TEI:entry//TEI:bibl[@type = 'linguistic']
```

if the query is split like this:  

``` xquery
let $bibls  := collection('/db/apps/lgpn-data/data/ling/names')//TEI:orth[.='Agathōnymos']/ancestor::TEI:entry//TEI:bibl
return $bibls[@type = 'linguistic']
```

the results are as expected. 

I can provide access to a server demonstrating this issue if someone wants to have a look and fix it.

**Comment by dizzzz** [comment]
optimizer issue?

**Comment by ljo** [comment]
Or too lazy evaluation. I can reproduce it so no need for access.

**Comment by dizzzz** [comment]
@wolfgangmm have you seen /talked about this ?

**Comment by tuurma** [comment]
I have another case (mentioned above) which I don't have time to properly isolate atm but looks the underlying problem may be identical to this one so happy to test after this issue is fixed.

**Comment by wolfgangmm** [comment]
Closing because it seems to have been fixed along the way.
