### ISSUE TITLE
eXist-db 2.2 web.xml validation issue

### ISSUE THREAD

**Issue by lagivan** [eXist-db/exist#924]
Not sure if there are plans for maintenance releases in 2.x. But there is a validation issue with web.xml and it'd be great to fix it. There is a big stacktrace which ends with:

```
Caused by: javax.xml.stream.XMLStreamException: ParseError at [row,col]:[350,7]
Message: Unexpected element '{http://java.sun.com/xml/ns/j2ee}init-param' encountered
```

I face it when building war and deploying it under JBoss AS 7. Element `init-param` is not allowed as a child of `servlet-mapping` and should be added under `servlet` element instead. The issue occurs for `ResourceServlet`. The valid code will look like:

```
<servlet>
   <servlet-name>ResourceServlet</servlet-name>
   <servlet-class>
      de.betterform.agent.web.resources.ResourceServlet
   </servlet-class>
   <init-param>
      <param-name>caching</param-name>
      <param-value>true</param-value>
   </init-param>
</servlet>
...
<servlet-mapping>
   <servlet-name>ResourceServlet</servlet-name>
   <url-pattern>/bfResources/*</url-pattern>
</servlet-mapping>
```

**Comment by dizzzz** [comment]
@zwobit one for you ?
