### ISSUE TITLE
BrokerPool has insufficient synchronization on activeBrokers field

### ISSUE THREAD

**Issue by alebastrov** [eXist-db/exist#925]
Though MapRWLock is looked OK (on the first glance)

```
...
private MapRWLock<Thread, DBBroker> activeBrokers = new MapRWLock<>(new IdentityHashMap<Thread, DBBroker>());
...
BrokerPool rely on **activeBrokers** state.
for instance there are many block of code like, which are OK
```

synchronized(this) {
...
activeBrokers.remove(Thread.currentThread())
...
if(activeBrokers.size() == 0) ...
}

```
but the same time there are blocks like
```

public boolean setSubject(final Subject subject) {
        //synchronized(this) {
        //Try to get an active broker
        final DBBroker broker = activeBrokers.get(Thread.currentThread());
        if(broker != null) {
            broker.setSubject(subject);
            return true;
        }
        //}

```
    return false;
}
```

```
without sync by **this** object, so activeBrokers may not contain current thread reference
```

**Comment by alebastrov** [comment]
I would suggest to use ObjectPool from apache project instead of using this obsolete code

**Comment by adamretter** [comment]
I am not sure which version of the code you are looking at, but the latest version doesn't look as you mention above, instead it looks like:
```
private final Map<Thread, DBBroker> activeBrokers = new ConcurrentHashMap<>();
```

However, there may still be synchronisation issues with the members of brokerPool.

**Comment by alebastrov** [comment]
Yea. I see the latest code (last commit was 4 days ago)
and there are lot inactiveBrokers calls without sync
```
inactiveBrokers.push(broker);
...
final DBBroker broker = inactiveBrokers.peek();
...
return inactiveBrokers.size();
```
It needs to be fixed because though logic of Stack is based on Vector (which is synchronized inside itself), the inactiveBrokers logic (in couple with activeBrokers) should use external sync

**Comment by adamretter** [comment]
@alebastrov I have spent some time looking into Apache Commons Pool 2 as you suggested. Unfortunately out of the box it is not suitable, as we rely on the fact that a single thread can call `getBroker` (i.e.. `borrowObject`) over and over and always be handed the same object.

I have attempted to extend `GenericObjectPool` from Commons Pool to add such a facility by using `ThreadLocal` caching. I could really do with a second pair-of-eyes on this to check that I am not doing anything daft with regards to synchronization or memory visibility. Would you have a moment to look at it? https://github.com/adamretter/exist/blob/broker-pool-pool/src/org/exist/storage/pool/ReentrantGenericObjectPool.java#L50

**Comment by alebastrov** [comment]
OK, I'll look at it

**Comment by duncdrum** [comment]
@adamretter is this still relevant?
