### ISSUE TITLE
Is any state or some build artifacts kept in /build even when switching commits?

### ISSUE THREAD

**Issue by line-o** [eXist-db/exist#940]
All of a sudden my existDB instance threw errors on each startup.
It was complaining about some duplicate entries or similar in `PermissionRequiredAspect.class`.
A rebuild of exist to get rid of the problems failed as well.
It failed for any version that was checked out (develop branch  and hsg-shell tag).
Neither `git reset --hard <commit>` nor `./build.sh clean-default-data-dir` did help.
It always failed with
```
[iajc] Problem processing attributes in /eXist/build/classes/org/exist/security/PermissionRequiredAspect.class
```
`rm -rf build && git checkout -- build` helped, but how can this be? 
Does anyone know what state or build artifact might have   here?

**Comment by adamretter** [comment]
No I haven't seen that before. Perhaps you had a interesting JDK installed which was not compatible with  iajc?

**Comment by line-o** [comment]
It is an OSX Capitan with the standard Oracle JDK.

**Comment by adamretter** [comment]
@line-o Then I am afraid that I don't know. You could perhaps also ask the AspectJ people who make `iajc`...

**Comment by line-o** [comment]
Currently, it is just important that work can go on again. If anyone else ever has this issue, removing the build folder and checking it out again did the trick.

**Comment by adamretter** [comment]
Okay thanks for reporting @line-o. I am going to close this for now.

**Comment by shabanovd** [comment]
@line-o do `build.sh rebuild` help?
