### ISSUE TITLE
Restore leads to "Reason: networking error" errors using backup.sh and JAC

### ISSUE THREAD

**Issue by ChiSamurai** [eXist-db/exist#942]
Easy way to reproduce (submitted by @jensopetersen ):

- clone exist-develop
- build.sh 
- install a few apps from the package manager (imo not needed)
- backup from the Dashboard
- clean build of the installation
- restore the backup through rpc (ie using backup.sh or JAC)

Leads to:

> WARN: Failed to restore resource 'functx.xql' from file 'xxx.zip#db/system/repo/functx-1.0/functx/functx.xql'.
Reason: networking error
WARN: Failed to restore resource 'icon.png'
from file 'xxx.zip#db/system/repo/xqjson-0.2.0/icon.png'.
Reason: networking error

@wolfgangmm added:
> While the restore seems to work if eXist is running in embedded mode
(bin/client.sh -l), I can reproduce the issue with a remote
connection.

It still works with commit #927, but since #928 the problems appear.

**Comment by wolfgangmm** [comment]
A similar issue pops up when using ant to upload binary resources. Rolling back to #927 fixes it as well:

at java.util.Objects.requireNonNull(Objects.java:203) ~[?:1.8.0_66]
        at java.nio.file.Files.copy(Files.java:2984) ~[?:1.8.0_66]
        at org.exist.storage.NativeBroker.lambda$storeBinaryResource$23(NativeBroker.java:2077) ~[exist.jar:?]
        at org.exist.storage.NativeBroker.storeBinaryResource(NativeBroker.java:2099) ~[exist.jar:?]

**Comment by adamretter** [comment]
@ChiSamurai @wolfgangmm I will look into this later today/tomorrow.

**Comment by ChiSamurai** [comment]
Fix works like a charme! Thanks a lot.

**Comment by dizzzz** [comment]
thnx guys!  ()also @ChiSamurai for testing!)
