### ISSUE TITLE
Update XMLCalabash plugin for Saxon HE-9.6.0-7 (for eXist-3.0)

### ISSUE THREAD

**Issue by adamretter** [eXist-db/exist#950]
When we release eXist 3.0.RC2, the XML Calabash plugin will need to be updated to the correct version of Calabash which supports Saxon HE-9.6.0-7. See:

https://github.com/eXist-db/eXist-XMLCalabash/pull/2
https://github.com/eXist-db/eXist-XMLCalabash/pull/1

**Comment by joewiz** [comment]
Should this be tagged with the 3.1 milestone?

**Comment by joewiz** [comment]
Or does the betterform dependency prevent an update of Saxon?

Asking because of @welblaud's question about the status of XProc support in 3.0 on exist-open earlier today, in which he referenced this issue.

**Comment by adamretter** [comment]
https://github.com/eXist-db/eXist-XMLCalabash/pull/6

**Comment by joewiz** [comment]
@adamretter So once eXist 3.1.0 and the new version of eXist-XMLCalabash are released (including eXist-db/eXist-XMLCalabash#6), this issue can be closed, right?

**Comment by adamretter** [comment]
@joewiz Indeedy.
