### ISSUE TITLE
Configuration error on startup

### ISSUE THREAD

**Issue by wshager** [eXist-db/exist#962]
I've configured exist to use the snowball analyzer, but I get a long list of error messages. This causes the db to take a long time to start.

[exist.log.txt](https://github.com/eXist-db/exist/files/195751/exist.log.txt)

I run windows server 2008r2 
current develop

**Comment by wshager** [comment]
I run windows server 2008r2

**Comment by wshager** [comment]
current develop

**Comment by dizzzz** [comment]
@wshager please make compact mails/notes/issues ; please don;t use exist-open or this tracker as an notebook of one-liners

**Comment by dizzzz** [comment]
can you share the `conf.xml` file?

**Comment by dizzzz** [comment]
it is possible to call an specific Analyser constructor manually: http://www.exist-db.org/exist/apps/doc/lucene.xml#D2.2.4.27.6 

the Constructor def is at https://lucene.apache.org/core/4_0_0/analyzers-common/org/apache/lucene/analysis/snowball/SnowballAnalyzer.html ....

**Comment by wshager** [comment]
@dizzzz thanks for the research on this one. I'll try a replacing analyzer.

**Comment by dizzzz** [comment]
I propose to close this ticket.
