### ISSUE TITLE
Feature Request: Unattended Console Install

### ISSUE THREAD

**Issue by awagner-mainz** [eXist-db/exist#964]
Dear all,
presently I am reying on the 'expect' command to automate my -console install, but this brings in lots of dependencies that are otherwise unnecessary. A mail on the list (from a long time ago) mentioned it was possible to read install parameters from stdin, but it required re-packaging the distribution jarfile.

Could you make an unattended mode for the console installer?

**Comment by funkyfuture** [comment]
i do absolutely agree, this is a freature that is long overdue in a world where automated deployments are a common practice.

beside the possibility to provide configuration values like `--data-dir`, also a `--default` flag should be available that sets the default values for configuration keys that have not explicitly been defined as arguments.

**Comment by funkyfuture** [comment]
i also refrained from using `expect` due to its 'weight'. i tried feeding the input through `stdin`, but iirc the installer then raised string handling-related exceptions.

**Comment by funkyfuture** [comment]
@dizzzz could please add the 'Installer' label to this issue?

**Comment by dizzzz** [comment]
yes sir :-)
