### ISSUE TITLE
Question about feature: SCXML support inside existdb

### ISSUE THREAD

**Issue by atanasg** [eXist-db/exist#968]
Hello existdb-Community,

I wanted to ask the question whether SCXML support (similar to Apache's Commons SCXML) is planned for existdb in any of the future releases? I wasn't able to find such information on the web page or here in GitHub.

Best regards,
atanasg

**Comment by dizzzz** [comment]
I did not hear of a request like this before. If one would build such an extension, probably the apache library will be used (But I am not really impressed by the quality of the documentation...)

**Comment by atanasg** [comment]
Thank you for the quick answer!

**Comment by dizzzz** [comment]
You might want to ask the question on exist-open ; there are many more ppl reading messages (and answering them)

**Comment by atanasg** [comment]
Thank you for the hint, I didn't know the mailing list. I will email my question there as well.

**Comment by duncdrum** [comment]
Since this has moved to the mailing list  i m going to close. If you would like to request a new feature, please open a new issue.
