### ISSUE TITLE
range index not working as expected

### ISSUE THREAD

**Issue by sonymoparthi** [eXist-db/exist#974]
My xml file is with the structure:

```
<compound>హరి ర్హరతి<parts>హరిః హరతి</parts></compound>
<compound>తద్విష్ణోః<parts>తత్ విష్ణోః</parts></compound>
```

I have created a range index:

```
<range>
    <create qname="compound" type="xs:string"/>
</range>
```

I expected the index terms are హరి ర్హరతిహరిః హరతి and తద్విష్ణోఃతత్ విష్ణోః but I found హరి ర్హరతి and తద్విష్ణోః under index link in monitoring and profiling window. And also the search string:

`//compound[.="హరి ర్హరతిహరిః హరతి"]`
giving 0 results.

Can any one help in creating index on the whole contents of compound like హరి ర్హరతిహరిః హరతి, తద్విష్ణోఃతత్ విష్ణోః so on?

**Comment by joewiz** [comment]
Please surround your XML markup with backticks, e.g., `<compound>`. For more info on marking up text with GitHub-flavored markdown, see https://guides.github.com/features/mastering-markdown/.

**Comment by duncdrum** [comment]
I get
```xml
<compound>హరి ర్హరతి<parts>హరిః హరతి</parts>
</compound>
```
 which looks correct, so good to close.
