### ISSUE TITLE
multi-field range index returns only first result

### ISSUE THREAD

**Issue by telic** [eXist-db/exist#988]
The new range index doesn't seem to handle comparison to sequences in predicates properly when using multi-field "combined" indexes. Instead of returning all results that compare true to any item in the sequence, only items that compare true to the first item are returned.

For example, given the following index configuration:

``` xml
<collection xmlns="http://exist-db.org/collection-config/1.0" xmlns:ex="http://example.com">
    <index xmlns:xs="http://www.w3.org/2001/XMLSchema">
        <range>
            <create qname="ex:ms">
                <field name="type" match="@t" type="xs:string"/>
                <field name="num" match="@n" type="xs:string"/>
            </create>
        </range>
    </index>
</collection>
```

applied to the document:

``` xml
<test xmlns="http://example.com">
  <ms t="q" n="a"/>
  <ms t="q" n="b"/>
  <ms t="r" n="a"/>
</test>
```

The xquery `//ex:ms[@t=('q','r')]` should return all the `ms` nodes, but it only returns the first two. Similarly, `//ex:ms[@t=('r','q')]` only returns the last.

If I understand correctly, these would get rewritten by the optimizer to something like `range:field('type', 'eq', ('q','r'))`, which exhibits the same behaviour.

The same problem occurs if both fields are used. Eg. `//ex:ms[@t='q'][@n=('a','b')]`, `//ex:ms[@t=('q','r')][@n='a']` and `//ex:ms[@t=('q','r')][@n=('a','b')]` all only return the first node. 

Using a loop to run the comparisons on single items works as expected (eg. `for $t in ('q','r') return //ex:ms[@t=$t]` returns everything).

Tested in eXist-2.2 and 3.0rc1 on Mac OS 10.11.4.

**Comment by jensopetersen** [comment]
In 3.0.RC2, build from 20160412, all three elements are correctly returned in the first test. The second test also succeeds.
